"""Tests for the genus-1 averaging-kernel toy engine."""

from compute.lib.genus1_averaging_kernel_engine import (
    QUASI_MODULAR_SECTORS,
    compute_genus1_averaging_kernel,
)


RESULT = compute_genus1_averaging_kernel()


def test_genus0_kernel_dim():
    # VERIFIED: [DC] dim Lambda^2(sl_2) = C(3,2) = 3 from antisymmetric tensors.
    # VERIFIED: [SY] 3⊗3 splits as Sym^2(C^3) ⊕ Lambda^2(C^3) with 9 = 6 + 3.
    assert RESULT.genus0_kernel_dim == 3


def test_genus1_kernel_strictly_larger():
    # VERIFIED: [DC] genus-1 domain has four 9-dimensional sectors, so the three
    # invariant sectors already contribute 3 * 3 = 9 antisymmetric kernel vectors.
    # VERIFIED: [LT] QM_*(SL_2(Z)) is generated by 1, E2*, E4, E6 in weight <= 6,
    # matching the four-sector truncation used in the engine.
    assert RESULT.genus1_kernel_dim > RESULT.genus0_kernel_dim


def test_rank_nullity_genus0():
    # VERIFIED: [DC] rank-nullity for a linear map V -> V gives dim ker + rank = dim V.
    # VERIFIED: [SY] av_0 = (I + P)/2 is a projector onto the symmetric summand.
    assert RESULT.genus0_kernel_dim + RESULT.genus0_image_dim == RESULT.genus0_domain_dim


def test_rank_nullity_genus1():
    # VERIFIED: [DC] rank-nullity still applies to the 36 x 36 block matrix.
    # VERIFIED: [DA] domain dimension is 9 * 4 = 36 from (sl_2⊗sl_2) times four sectors.
    assert RESULT.genus1_kernel_dim + RESULT.genus1_image_dim == RESULT.genus1_domain_dim


def test_kernel_enlargement_positive():
    # VERIFIED: [DC] the matrix computation gives a larger null space at genus 1.
    # VERIFIED: [LC] the three modular sectors 1, E4, E6 already force kernel dim >= 9 > 3.
    assert RESULT.kernel_enlargement > 0


def test_quasi_modular_sector_labels():
    # VERIFIED: [LT] the truncated genus-1 quasi-modular ring basis is {1, E2*, E4, E6}.
    # VERIFIED: [DC] the engine constructs exactly four matching matrix blocks.
    assert RESULT.quasi_modular_sectors == QUASI_MODULAR_SECTORS
