#!/usr/bin/env python3
"""Compute KM bar cohomology via spectral sequence.

For V_k(g) at generic level, the bar spectral sequence collapses at E_1:
  E_1^{p,q} = H_p(g; S^q(g[t^{-1}t^{-2},...]))

This computes:
  sum_n dim(H^n(B(V_k(g)))) * x^n = prod_{d>=1} (1 - x^d)^{-b_d}

where b_d = dim(g) * p(d-1) with p = partition function, accounting for
the PBW basis at each conformal weight.

Actually, the correct formula is simpler. For a KM algebra V_k(g):
  dim B-bar^n = dim(g)^n * (n-1)!  (chain groups)
  dim H^n(B-bar) = sum over weight decomposition

The generating function is determined by the free resolution of the
vacuum module. For sl_2, this is the Riordan number formula.

Let me derive the GF from the structural formula:
  GF(x) = sum_n h_n x^n

For a Lie algebra g of dim d, the bar complex of the LOOP algebra g[t^{-1}]
(not the vertex algebra) has chain groups (g[t^{-1}])^{wedge n} and the
spectral sequence relates to H*(g; S*(g[t^{-1}])).

For generic k, the key result (Theorem 7.1.4 in manuscript) is:
  The bar spectral sequence for V_k(g) has E_1 page given by
  CE homology of g with coefficients in the symmetric algebra S(g[t^{-1}]).
  The spectral sequence collapses at E_1 for Koszul algebras.

The total bar generating function is then:
  GF(x) = sum_{n>=0} (sum_q dim H_n(g; S^q(g))) * x^n * y^q

where the y-grading tracks conformal weight. Setting y=1 gives the total.

For a semisimple g, H_n(g; M) = 0 for n>0 if M is a direct sum of
trivials (Whitehead lemma). But S^q(g) is NOT trivial for q>0.

Actually, for the FULL bar complex of V_k(g), the generating function
can be derived from the observation that V_k(g) is generated by dim(g)
fields of conformal weight 1, with relations from the OPE. The bar
complex resolves these relations.

The bar GF for sl_2 is known:
  P_{sl_2}(x) = (1 + x - sqrt((1-3x)(1+x))) / (2x(1+x))
  = 3x + 6x^2 + 15x^3 + 36x^4 + 91x^5 + ...

This is the Riordan number R(n+3) generating function.

For sl_3, we have three data points: 8, 36, 204.
Conjectured: a(n) = 11a(n-1) - 23a(n-2) - 8a(n-3).
"""

import numpy as np

print("="*60)
print("KM bar cohomology via generating functions")
print("="*60)

# sl_2: Riordan numbers R(n+3)
# GF satisfies: x(1+x)P^2 - (1+x)P + 1 = 0 (after shifting)
# P(x) = (1+x-sqrt(Delta))/(2x(1+x)) where Delta = (1-3x)(1+x) = 1-2x-3x^2
def sl2_bar_gf(max_n=12):
    """Compute sl_2 bar cohomology from algebraic GF."""
    # Recurrence: a(n) = (2n+1)*a(n-1)/(n+2) + 3(n-1)*a(n-2)/(n+2) ... no
    # Direct: extract coefficients from GF via Newton's method on series
    a = [0, 3]  # a[0]=0, a[1]=3
    # From the equation: x(1+x)P^2 - (1+x)P + 1 = 0
    # => P = (1+x - sqrt((1-3x)(1+x))) / (2x(1+x))
    # Series expansion:
    # Use recurrence derived from the ODE for P(x):
    # 2x(1+x)^2 P'(x)(1+x) + ... this is complex
    # Instead, use the explicit Riordan number formula:
    # R(n) = (1/(n+1)) sum_{k=1}^{n} C(n+1,k+1)*C(n-1,k-1) (Riordan formula)
    # Actually, simpler: known recurrence (n+1)a(n) = (2n-1)a(n-1) + 3(n-2)a(n-2)
    # with a(0)=1, a(1)=0 for Riordan numbers. Our sequence is shifted by 3.
    # R(n+3) for n>=1: R(4)=3, R(5)=6, R(6)=15, R(7)=36, R(8)=91, R(9)=232

    # Riordan recurrence: (n+1)R(n) = (2n-1)R(n-1) + 3(n-2)R(n-2)
    R = [1, 0, 1, 1, 3, 6, 15, 36, 91, 232, 603, 1585, 4213]  # R(0),...,R(12)
    return [R[n+3] for n in range(max_n)]

sl2_vals = sl2_bar_gf(10)
print("\nsl_2 bar cohomology (Riordan R(n+3)):")
for n in range(1, len(sl2_vals)):
    print(f"  H^{n} = {sl2_vals[n]:>8d}")

# sl_3: conjectured recurrence
def sl3_bar_gf(max_n=10):
    a = [0, 8, 36, 204]
    for n in range(4, max_n):
        a.append(11*a[n-1] - 23*a[n-2] - 8*a[n-3])
    return a

sl3_vals = sl3_bar_gf(10)
print("\nsl_3 bar cohomology (conjectured recurrence):")
for n in range(1, len(sl3_vals)):
    proved = "proved" if n <= 3 else "conjectured"
    print(f"  H^{n} = {sl3_vals[n]:>8d}  ({proved})")

# Verify growth rate
print("\nGrowth rate analysis:")
print("  sl_2: lim a(n+1)/a(n) = 3 (from discriminant root)")
for n in range(2, min(10, len(sl2_vals))):
    if sl2_vals[n-1] > 0:
        ratio = sl2_vals[n] / sl2_vals[n-1]
        print(f"    a({n})/a({n-1}) = {ratio:.4f}")

print("  sl_3: conjectured growth rate from recurrence roots")
# Characteristic equation: t^3 - 11t^2 + 23t + 8 = 0
import numpy.polynomial.polynomial as P
roots = np.roots([1, -11, 23, 8])
print(f"    Roots: {sorted(roots.real, reverse=True)}")
print(f"    Dominant root: {max(abs(r) for r in roots):.6f}")

for n in range(2, len(sl3_vals)):
    if sl3_vals[n-1] > 0:
        ratio = sl3_vals[n] / sl3_vals[n-1]
        print(f"    a({n})/a({n-1}) = {ratio:.4f}")

# ================================================================
# Cross-check: sl_3 discriminant prediction
# ================================================================
print("\n" + "="*60)
print("Discriminant analysis")
print("="*60)

# sl_2 GF: algebraic degree 2 with discriminant Delta = 1-2x-3x^2 = (1-3x)(1+x)
# Conjecture: sl_3 GF is algebraic degree 3 (rational = degree 1, but our recurrence is depth 3)
# The recurrence a(n) = 11a(n-1) - 23a(n-2) - 8a(n-3) corresponds to the
# rational GF: P(x) = N(x)/D(x) where D(x) = 1 - 11x + 23x^2 + 8x^3

# Check: is 1-11x+23x^2+8x^3 factorizable?
D_roots = np.roots([8, 23, -11, 1])
print(f"  D(x) = 1-11x+23x^2+8x^3, roots: {sorted(1/D_roots.real)}")
# If the roots are "nice" (rational), D factors over Q
# D(x) = 8x^3 + 23x^2 - 11x + 1
# Try x = -1/8: 8(-1/512) + 23(1/64) - 11(-1/8) + 1 = -1/64 + 23/64 + 11/8 + 1
# = 22/64 + 11/8 + 1 = 11/32 + 11/8 + 1 = 11/32 + 44/32 + 32/32 = 87/32 != 0
# Not rational roots. So D is irreducible over Q => sl_3 GF is NOT rational.
# Wait — the recurrence gives a RATIONAL GF if the initial conditions match.
# P(x) = (8x + 36x^2 + 204x^3 + ...) satisfying P(x) * (1-11x+23x^2+8x^3) = polynomial in x
# P(x) * D(x) = 8x + (36-88)x^2 + ... = 8x - 52x^2 + ...
# Let me compute:
coeffs = sl3_vals[:8]
D = [1, -11, 23, 8]
# N(x) = P(x) * D(x) = finite polynomial (the numerator)
N = [0] * 8
for i in range(8):
    for j in range(min(4, 8-i)):
        if i+j < 8:
            N[i+j] += coeffs[i] * D[j]

print(f"\n  Numerator N(x) = P(x)*D(x): {N}")
print(f"  -> N(x) = {N[1]}*x + {N[2]}*x^2 + {N[3]}*x^3")
# Check that higher coefficients are 0
for i in range(4, 8):
    assert abs(N[i]) < 1e-10, f"N[{i}] = {N[i]} != 0"
print(f"  -> P(x) = ({N[1]}*x + {N[2]}*x^2 + {N[3]}*x^3) / (1 - 11x + 23x^2 + 8x^3)")
print(f"  -> P(x) = x*({N[1]} + {N[2]}*x + {N[3]}*x^2) / (1 - 11x + 23x^2 + 8x^3)")

# Compare with sl_2: P_{sl_2} is algebraic degree 2 (quadratic in P)
# sl_3: P_{sl_3} is RATIONAL (degree 0 algebraic) if the recurrence holds
print("\n  If the recurrence is correct, sl_3 bar GF is RATIONAL.")
print("  This is different from sl_2 which is algebraic degree 2.")
print("  The DS discriminant conjecture predicts sl_3 and W_3 share a discriminant,")
print("  but if sl_3 GF is rational, there is no discriminant (denominator factors).")
