"""Chiral bar-cobar compute engine.

Core types and algebra constructors for the monograph's computational kernel.

Governing principle (Dual Imperative):
    Every computation serves a theorem. State the theorem FIRST, predict the
    answer, THEN compute. If mismatch: the THEORY is suspect, not the computation.
    Maximalist ambition (push for the most powerful results) is amplified by
    maximal truth-seeking (every numerical claim verified, every formula derived
    before it enters the manuscript). These are synergistic, not competing.

Usage:
    from compute.lib import OPEAlgebra, Generator
    from compute.lib import heisenberg_algebra, sl2_algebra, virasoro_algebra
    from compute.lib import GradedVectorSpace, ChainComplex
"""

# Core types
from compute.lib.utils import GradedVectorSpace, ChainComplex, partition_number, lambda_fp, F_g
from compute.lib.bar_complex import OPEAlgebra, Generator

# Standard algebra constructors
from compute.lib.bar_complex import (
    heisenberg_algebra,
    sl2_algebra,
    virasoro_algebra,
    free_fermion_algebra,
)

# Lie algebra data
from compute.lib.lie_algebra import cartan_data, sugawara_c, ff_dual_level, kappa_km

# Cross-algebra registry
from compute.lib.cross_algebra import ALGEBRA_REGISTRY

# Bar cohomology dimensions (known values)
from compute.lib.bar_complex import KNOWN_BAR_DIMS, verify_bar_dim

# Koszul dual Hilbert series
from compute.lib.koszul_hilbert import quadratic_dual_dims, verify_koszul, riordan, motzkin

# Orlik-Solomon algebra
from compute.lib.os_algebra import os_dimension, os_basis, residue_map

# Pronilpotent weight-filtered completion (MC4 scaffold)
from compute.lib.pronilpotent_bar import (
    max_bar_degree,
    effective_generator_weights,
    w_infinity_generator_weights,
    ordered_weight_monomials,
    weight_sector_profile,
    degree_sector_dimension_formula,
    total_sector_dimension_formula,
    w_infinity_weight_sector,
    verify_w_infinity_completion,
)

# Truncated W_infinity structural OPE scaffold (MC4 / Tool 8.2)
from compute.lib.w_infinity_ope import (
    TruncatedWinfinityOPE,
    verify_truncated_w_infinity_ope,
)
from compute.lib.w_infinity_support_complex import (
    TruncatedWinfinitySupportComplex,
    verify_w_infinity_support_complex,
)
from compute.lib.w_infinity_dual_candidate import (
    completed_bar_candidate_descriptor,
    stage3_dual_constraint_report,
    stage4_higher_spin_constraint_map,
    stage4_virasoro_constraint_map,
    stage4_dual_constraint_report,
    stage4_residue_symbol_map,
    stage4_dual_defect_map,
    stage4_dual_goal_report,
    stage4_primitive_square_class_report,
    stage4_pairing_reduction_report,
    stage4_primitive_transport_report,
    stage4_borcherds_transport_report,
    stage4_two_primitive_square_closure_report,
    stage4_local_attack_order_report,
    stage4_target_packet_at_level,
    evaluate_stage4_dual_defects_at_level,
    stage4_defect_vanishing_report,
    stage5_dual_frontier_report,
    stage5_local_attack_order_report,
    stage5_visible_pairing_normal_form_report,
    stage5_principal_one_coefficient_normal_form_report,
    stage5_principal_target5_no_new_independent_data_report,
    stage5_principal_residual_front_one_coefficient_report,
    stage5_principal_one_coefficient_factorization_report,
    stage5_effective_independent_frontier_report,
    stage5_one_coefficient_reduction_report,
    stage5_one_defect_family_report,
    stage5_conjecture_defect_dictionary_report,
    stage5_exact_remaining_input_report,
    stage5_visible_conjecture_network_collapse_report,
    stage5_one_coefficient_comparison_report,
    standard_winfinity_dual_candidate_report,
    verify_standard_winfinity_dual_candidate,
)

# Genus-1 PBW generalized diagnostics (MC1 frontier)
from compute.lib.genus1_pbw_sl2 import (
    CASIMIR_EXACT_CUTOFF,
    CASIMIR_MODULAR_PRIMES,
    CASIMIR_MODULAR_STRATEGY,
    casimir_method_for_tensor_power,
    casimir_modular_strategy_for_tensor_power,
    casimir_eigenspace_multiplicities_modular_weight_block_on_tensor_power,
    casimir_eigenspace_multiplicities_on_tensor_power,
    staged_frontier_diagnostics_on_tensor_power,
)

# MC2 scaffold: cyclic CE cohomology (Step 1 foundation)
from compute.lib.mc2_cyclic_ce import (
    sl2_structure_constants,
    sl2_killing_form,
    sl3_structure_constants,
    sl3_killing_form,
    sp4_structure_constants,
    sp4_killing_form,
    ce_cohomology,
    cyclic_ce_cohomology,
    ce_exterior_differential,
    cyclic_ce_via_exterior,
    verify_sl2_ce_cohomology,
    verify_sl2_cyclic_ce_cohomology,
    verify_sl3_ce_cohomology,
    verify_sl3_cyclic_ce_cohomology,
    verify_sp4_ce_cohomology,
    verify_sp4_cyclic_ce_cohomology,
    verify_sl2_exterior_cross_check,
)

# MC2 scaffold: cyclic L-infinity control on coderivations
from compute.lib.mc2_cyclic_linf import (
    CoderivationDGLieModel,
    CyclicLInfinityModel,
    build_mc2_coderivation_dg_lie_model,
    build_mc2_cyclic_linf_model,
    cyclic_ce_profile_from_cyclic_seed,
    build_cyclic_l3_marker_extension_from_seed,
    build_mc2_sl2_coderivation_seed,
    build_mc2_sl2_cyclic_linf_seed,
    build_mc2_sl2_cyclic_linf_l3_seed,
    build_shifted_symmetric_cyclic_linf_from_seed,
    build_mc2_sl2_shifted_cyclic_linf_l3_seed,
    shifted_seed_eta_channel_scaling_profile,
    build_mc2_root_string_family_cyclic_linf_seed,
    build_mc2_root_string_seed_packet_cyclic_linf_seed,
    build_mc2_root_string_family_shifted_cyclic_linf_l3_seed,
    build_mc2_root_string_seed_packet_shifted_cyclic_linf_l3_seed,
    shifted_eta_root_string_family_profile,
    shifted_eta_root_string_seed_packet_profile,
    visible_lowarity_root_string_packet_from_shifted_seed,
    infer_visible_lowarity_root_string_packet_from_obstruction,
    visible_lowarity_root_string_transfer_package_from_shifted_seed,
    visible_lowarity_root_string_l3_channel_recovery_from_shifted_seed,
    reconstruct_root_string_shifted_seed_from_obstruction_profile,
    root_string_ordered_seed_support_permutations,
    visible_lowarity_root_string_incidence_orbit_profile_from_shifted_seed,
    visible_lowarity_root_string_invariant_signature_from_shifted_seed,
    visible_lowarity_root_string_signed_seed_character_from_shifted_seed,
    visible_lowarity_root_string_two_sign_normalization_scalar_from_shifted_seed,
    visible_lowarity_root_string_parity_sign_normalization_scalar_from_shifted_seed,
    mc2_visible_lowarity_root_string_orbit_table_profiles,
    mc2_shifted_eta_root_string_signature_profiles,
    shifted_seed_obstruction_polynomial_profile,
    shifted_seed_obstruction_support_profile,
    completed_tensor_product_surrogate,
    completed_pairing_series,
    clutching_map_via_l2,
    clutching_series_via_l2,
    boundary_clutching_series_via_l2,
    verify_boundary_clutching_compatibility,
    completed_l2_series,
    completed_l3_series,
    mc_residual_completed_truncated,
    solve_completed_mc_single_basis_truncated,
    solve_completed_mc_basis_family_truncated,
    completed_mc_obstruction_term_at_genus,
    verify_genus_stratified_obstruction_identity,
    solve_completed_mc_single_basis_recursive,
    solve_completed_mc_basis_family_recursive,
    verify_completed_cyclic_l2,
    verify_completed_cyclic_l3,
    mc_residual_single_parameter,
    mc_residual_three_parameter,
    solve_mc_single_parameter,
    verify_mc2_cyclic_linf_scaffold,
    verify_mc2_completion_clutching_scaffold,
    verify_mc2_sl2_seed_from_bar,
    verify_mc2_sl2_l3_seed,
    verify_mc2_sl2_shifted_seed_nontrivial_mc,
    mc2_shifted_seed_one_channel_normalization_profiles,
    verify_mc2_shifted_seed_one_channel_normalization,
    verify_mc2_shifted_seed_eta_scaling_law,
    verify_mc2_shifted_eta_root_string_signature_law,
    verify_mc2_shifted_eta_root_string_family_law,
    verify_mc2_shifted_eta_root_string_seed_packet_law,
    verify_mc2_visible_lowarity_root_string_packet_law,
    verify_mc2_visible_lowarity_root_string_packet_identifiability,
    verify_mc2_visible_lowarity_root_string_transfer_package_law,
    verify_mc2_visible_lowarity_root_string_l3_channel_recovery_law,
    verify_mc2_visible_lowarity_root_string_chart_recovery_law,
    verify_mc2_visible_lowarity_root_string_automorphism_rigidity_law,
    verify_mc2_visible_lowarity_root_string_incidence_orbit_law,
    verify_mc2_visible_lowarity_root_string_orbit_table_law,
    verify_mc2_visible_lowarity_root_string_invariant_signature_law,
    verify_mc2_visible_lowarity_root_string_seed_character_law,
    verify_mc2_visible_lowarity_root_string_two_sign_scalar_law,
    verify_mc2_visible_lowarity_root_string_parity_scalar_law,
    verify_mc2_shifted_seed_obstruction_polynomial_law,
    verify_mc2_shifted_eta_channel_ce_alignment,
    verify_mc2_shifted_obstruction_support_truncation,
    verify_mc2_shifted_one_channel_criterion_package,
    # sl_3 seed (Step 3 universality)
    build_mc2_sl3_coderivation_seed,
    build_mc2_sl3_cyclic_linf_seed,
    build_mc2_sl3_cyclic_linf_l3_seed,
    build_mc2_sl3_shifted_cyclic_linf_l3_seed,
    verify_mc2_sl3_seed,
    verify_mc2_sl3_kappa_extraction,
    verify_mc2_sl3_shifted_seed_nontrivial_mc,
    # sp_4 seed (non-simply-laced universality)
    build_mc2_sp4_coderivation_seed,
    build_mc2_sp4_cyclic_linf_seed,
    build_mc2_sp4_cyclic_linf_l3_seed,
    build_mc2_sp4_shifted_cyclic_linf_l3_seed,
    verify_mc2_sp4_seed,
    verify_mc2_sp4_kappa_extraction,
    verify_mc2_sp4_shifted_seed_nontrivial_mc,
    # g_2 seed (exceptional universality)
    build_mc2_g2_coderivation_seed,
    build_mc2_g2_cyclic_linf_seed,
    build_mc2_g2_cyclic_linf_l3_seed,
    build_mc2_g2_shifted_cyclic_linf_l3_seed,
    verify_mc2_g2_seed,
    verify_mc2_g2_kappa_extraction,
    verify_mc2_g2_shifted_seed_nontrivial_mc,
    # Step 3: kappa extraction
    adjoint_casimir_matrix,
    adjoint_casimir_eigenvalue,
    dual_coxeter_from_seed,
    kappa_from_seed,
    kappa_two_channel,
    verify_linf_arity4_identity,
    verify_cyclic_l2_full,
    verify_cyclic_l3_full,
    verify_mc2_kappa_extraction,
    verify_mc2_linf_identities,
)

# Non-principal DS orbit scaffold (hook/subregular frontier)
from compute.lib.nonprincipal_ds_orbits import (
    TRACK_CORE_PRINCIPAL,
    TRACK_FRONTIER_NONPRINCIPAL,
    STATUS_PROVED_SUBREGULAR_SL3,
    STATUS_HOOK_EVIDENCE,
    STATUS_PROGRAMME,
    MatrixBasisExpression,
    MatrixSl2Triple,
    OrbitDualityCase,
    HookOrbitPairProfile,
    normalize_partition,
    partition_size,
    transpose_partition,
    is_hook_partition,
    hook_partition,
    two_row_nonhook_partition,
    subregular_partition,
    type_a_bv_dual,
    hook_dual_partition,
    type_a_nilpotent_matrix,
    type_a_hook_nilpotent_matrix,
    type_a_partition_sl2_triple,
    type_a_hook_sl2_triple,
    type_a_hook_pair_sl2_triples,
    standard_traceless_basis_sl_n,
    matrix_to_traceless_basis_expression_sl_n,
    nilpotent_partition_from_matrix,
    matrix_centralizer_dimension_sl_n,
    matrix_centralizer_basis_sl_n,
    homogeneous_f_centralizer_basis_sl_n,
    ad_h_grade_multiplicities_sl_n,
    ad_h_graded_basis_labels_sl_n,
    type_a_orbit_class,
    centralizer_dimension_sl_n,
    orbit_dimension_sl_n,
    principal_ff_level_shift_type_a,
    type_a_orbit_level_shift_correction_data,
    nonprincipal_orbit_level_shift_type_a,
    nonprincipal_hook_level_shift_type_a,
    nonprincipal_hook_level_shift_ansatz_type_a,
    nonprincipal_type_a_case,
    type_a_general_nonprincipal_partitions,
    nonprincipal_hook_case,
    nonprincipal_hook_cases,
    nonprincipal_general_cases,
    nonprincipal_two_row_case,
    nonprincipal_two_row_cases,
    hook_orbit_pair_profile,
    hook_orbit_pair_profile_catalog,
    first_nonselfdual_hook_pair_nilpotent_matrices,
    first_nonselfdual_hook_pair_centralizer_bases,
    first_nonselfdual_hook_pair_sl2_triples,
    first_nonselfdual_hook_pair_f_centralizer_bases,
    verify_hook_orbit_pair_profile_catalog,
    verify_nonprincipal_general_orbit_scaffold,
    verify_nonprincipal_two_row_orbit_scaffold,
    verify_nonprincipal_ds_orbit_scaffold,
)

# BV duality + non-principal DS seed reductions
from compute.lib.bv_duality import (
    BVDualOrbit,
    STATUS_EXACT_TYPE_A,
    STATUS_HOOK_FRONTIER,
    type_a_bv_dual,
    is_type_a_self_dual_orbit,
    type_a_bv_pair,
    type_a_hook_bv_pair,
    first_nonselfdual_type_a_hook_pair,
    verify_bv_duality_scaffold,
)
from compute.lib.nonprincipal_ds_reduction import (
    NonprincipalDSSeed,
    bp_dual_level,
    bp_residual_sl2_level,
    bp_residual_sl2_dual_relation,
    bp_central_charge,
    bp_complementarity_sum,
    bp_complementarity_constant,
    bp_curvature_proxy,
    bp_curvature_dual_relation,
    sl3_subregular_good_grading_multiplicities,
    hook_constraint_count_ansatz_type_a,
    hook_pair_constraint_counts_ansatz_type_a,
    verify_hook_constraint_count_ansatz,
    bp_current_presentation,
    bp_strong_presentation,
    nonprincipal_type_a_seed,
    sl3_subregular_bp_seed,
    nonprincipal_hook_seed,
    nonprincipal_hook_seed_catalog,
    nonprincipal_general_seed,
    nonprincipal_general_seed_catalog,
    nonprincipal_two_row_seed,
    nonprincipal_two_row_seed_catalog,
    first_nonselfdual_hook_seed,
    verify_nonprincipal_general_seed_catalog,
    verify_nonprincipal_hook_seed_catalog,
    verify_nonprincipal_two_row_seed_catalog,
    verify_nonprincipal_ds_reduction_seed,
)
from compute.lib.nonprincipal_ds_normalization import (
    CentralChargeConvention,
    RAW_BP_CONVENTION,
    CHAPTER_BP_SUM_CONVENTION,
    bp_dual_sum_under_convention,
    shift_to_target_dual_sum,
    bp_shift_to_target_sum,
    bp_shifted_convention_for_target,
    verify_nonprincipal_ds_normalization,
)
from compute.lib.ds_reduction import (
    Sl2TripleSeed,
    DSGhostWeight,
    DSReductionSeed,
    TruncatedBRSTComplex,
    HookPairDSComplexSeed,
    LinearConstraintBRSTBlock,
    MixedConstraintGhostBRSTBlock,
    SurvivorCoupledBRSTBlock,
    InternalSurvivorCEBlock,
    SemidirectSurvivorBRSTBlock,
    DSBasisElement,
    DSConstraint,
    DSBRSTBlueprint,
    DSReducedFieldCandidate,
    CurrentActionTermEntry,
    SurvivorActionTermEntry,
    SurvivorActionLiftWitness,
    SurvivorDerivationDefectWitness,
    FirstTransferCorrectionWitness,
    QuadraticGhostTermEntry,
    STATUS_DS_SEED,
    brst_ghost_weights,
    matrix_commutator,
    ds_basis_expression_matrix,
    exterior_basis_indices,
    homogeneous_monomial_exponents,
    linear_constraint_block_basis,
    character_wedge_differential,
    quadratic_ghost_differential,
    ghost_brst_differential,
    linear_constraint_koszul_differential,
    build_character_wedge_complex,
    build_ghost_brst_complex,
    build_mixed_constraint_ghost_brst_block,
    current_action_differential,
    survivor_action_differential,
    build_survivor_coupled_brst_block,
    build_internal_survivor_ce_block,
    build_semidirect_survivor_brst_block,
    combine_survivor_action_terms,
    solve_survivor_derivation_correction_for_ghost,
    solve_survivor_derivation_correction_terms,
    relabel_quadratic_ghost_terms,
    relabel_current_action_terms,
    relabel_truncated_brst_complex,
    relabel_mixed_constraint_ghost_block,
    build_linear_constraint_koszul_block,
    differential_square_blocks,
    chain_homology_dimensions,
    mixed_constraint_ghost_block_basis,
    mixed_constraint_ghost_brst_differential,
    mixed_constraint_ghost_block_homology_dimensions,
    survivor_coupled_block_basis,
    survivor_coupled_block_homology_dimensions,
    internal_survivor_ce_block_basis,
    internal_survivor_ce_h0_basis,
    internal_survivor_ce_block_homology_dimensions,
    internal_survivor_h0_monomial_labels,
    internal_survivor_linear_h0_labels,
    semidirect_survivor_block_basis,
    semidirect_survivor_block_homology_dimensions,
    complex_has_nilpotent_differential,
    mixed_constraint_ghost_block_has_square_zero,
    mixed_constraint_ghost_block_is_acyclic,
    survivor_coupled_block_has_square_zero,
    survivor_coupled_block_is_acyclic,
    internal_survivor_ce_block_has_square_zero,
    internal_survivor_ce_block_is_acyclic,
    semidirect_survivor_block_has_square_zero,
    semidirect_survivor_block_is_acyclic,
    linear_constraint_block_has_square_zero,
    linear_constraint_contracting_homotopy,
    specialize_complex_chi,
    truncated_cohomology_dimensions,
    complex_is_acyclic,
    linear_constraint_block_has_contracting_homotopy,
    linear_constraint_block_is_positive_acyclic,
    sl3_subregular_sl2_triple,
    sl3_subregular_basis_grades,
    sl3_subregular_basis_matrices,
    sl3_subregular_basis_profile,
    sl3_subregular_ad_e_image_witnesses,
    sl3_subregular_ad_e_image_basis,
    sl3_subregular_split_expression,
    sl3_subregular_expand_ad_e_terms_to_witness_preimage,
    sl3_subregular_project_expression_to_strong_candidates,
    sl3_subregular_project_basis_label_to_strong_candidates,
    sl3_subregular_projected_strong_brackets,
    sl3_subregular_strong_generator_candidates,
    sl3_subregular_positive_grades,
    sl3_subregular_ghost_profile,
    sl3_subregular_constraint_character,
    sl3_subregular_constraints,
    sl3_subregular_survivor_action_terms,
    sl3_subregular_survivor_action_lift_witnesses,
    sl3_subregular_survivor_derivation_defects,
    sl3_subregular_derivation_defect_witnesses,
    sl3_subregular_first_transfer_correction_witnesses,
    sl3_subregular_first_transfer_correction_terms,
    sl3_subregular_corrected_survivor_action_terms,
    sl3_subregular_corrected_survivor_derivation_defects,
    sl3_subregular_positive_nilpotent_brackets,
    sl3_subregular_ds_seed,
    sl3_subregular_linear_constraint_blocks,
    sl3_subregular_mixed_constraint_ghost_blocks,
    sl3_subregular_nonlinear_mixed_constraint_ghost_blocks,
    sl3_subregular_internal_survivor_ce_blocks,
    sl3_subregular_semidirect_survivor_blocks,
    sl3_subregular_corrected_semidirect_survivor_blocks,
    sl3_subregular_survivor_coupled_blocks,
    sl3_subregular_truncated_brst_complex,
    first_nonselfdual_hook_pair_basis_profiles,
    first_nonselfdual_hook_pair_brst_blueprints,
    hook_pair_ds_seed,
    hook_pair_ghost_profiles,
    hook_pair_constraint_characters,
    hook_pair_constraints,
    hook_pair_positive_nilpotent_brackets,
    hook_pair_quadratic_ghost_term_support,
    hook_pair_current_action_terms,
    hook_pair_survivor_action_terms,
    hook_pair_survivor_action_lift_witnesses,
    hook_pair_constraint_current_witnesses,
    hook_pair_first_transfer_correction_witnesses,
    hook_pair_first_transfer_correction_terms,
    hook_pair_corrected_survivor_action_terms,
    hook_pair_derivation_defect_witnesses,
    hook_pair_corrected_survivor_derivation_defects,
    partition_pair_constraints,
    partition_pair_positive_nilpotent_brackets,
    partition_pair_quadratic_ghost_term_support,
    partition_pair_current_action_terms,
    partition_pair_survivor_action_terms,
    partition_pair_survivor_action_lift_witnesses,
    partition_pair_constraint_current_witnesses,
    partition_pair_survivor_derivation_defects,
    partition_pair_first_transfer_correction_witnesses,
    partition_pair_first_transfer_correction_terms,
    partition_pair_corrected_survivor_action_terms,
    partition_pair_corrected_survivor_derivation_defects,
    partition_pair_surviving_field_candidates,
    partition_pair_reduced_brackets,
    partition_pair_internal_survivor_ce_blocks,
    nonprincipal_partition_pair_mixed_constraint_ghost_blocks,
    nonprincipal_partition_pair_nonlinear_mixed_constraint_ghost_blocks,
    nonprincipal_partition_pair_semidirect_survivor_blocks,
    nonprincipal_partition_pair_corrected_semidirect_survivor_blocks,
    nonprincipal_partition_pair_survivor_coupled_blocks,
    nonprincipal_partition_pair_mixed_blocks_match_under_dual_swap,
    nonprincipal_partition_pair_nonlinear_blocks_match_under_dual_swap,
    nonprincipal_partition_pair_survivor_coupled_blocks_match_under_dual_swap,
    nonprincipal_partition_pair_corrected_semidirect_blocks_match_under_dual_swap,
    hook_pair_survivor_derivation_defects,
    hook_pair_specialized_complexes,
    hook_pair_ds_seed_catalog,
    verify_hook_pair_ds_seed_catalog,
    verify_hook_pair_seed_alignment,
    verify_hook_pair_first_transfer_correction_catalog,
    verify_hook_pair_corrected_semidirect_catalog,
    verify_hook_pair_corrected_semidirect_duality_catalog,
    hook_pair_corrected_semidirect_family_holds_via_duality,
    verify_hook_pair_corrected_semidirect_family_via_duality_catalog,
    hook_pair_linear_constraint_blocks,
    hook_pair_mixed_constraint_ghost_blocks,
    hook_pair_nonlinear_mixed_constraint_ghost_blocks,
    hook_pair_survivor_coupled_blocks,
    nonprincipal_two_row_internal_survivor_ce_blocks,
    nonprincipal_two_row_mixed_constraint_ghost_blocks,
    nonprincipal_two_row_nonlinear_mixed_constraint_ghost_blocks,
    nonprincipal_two_row_semidirect_survivor_blocks,
    nonprincipal_two_row_corrected_semidirect_survivor_blocks,
    nonprincipal_two_row_survivor_coupled_blocks,
    hook_pair_semidirect_survivor_blocks,
    hook_pair_corrected_semidirect_survivor_blocks,
    nonprincipal_two_row_mixed_blocks_match_under_dual_swap,
    nonprincipal_two_row_nonlinear_blocks_match_under_dual_swap,
    nonprincipal_two_row_survivor_coupled_blocks_match_under_dual_swap,
    nonprincipal_two_row_corrected_semidirect_blocks_match_under_dual_swap,
    hook_pair_mixed_blocks_match_under_dual_swap,
    hook_pair_nonlinear_blocks_match_under_dual_swap,
    hook_pair_survivor_coupled_blocks_match_under_dual_swap,
    hook_pair_corrected_semidirect_blocks_match_under_dual_swap,
    verify_hook_pair_mixed_block_duality_catalog,
    hook_pair_mixed_family_holds_via_duality,
    verify_hook_pair_mixed_family_via_duality_catalog,
    verify_hook_pair_nonlinear_block_duality_catalog,
    hook_pair_nonlinear_family_holds_via_duality,
    verify_hook_pair_nonlinear_family_via_duality_catalog,
    verify_hook_pair_survivor_coupled_block_duality_catalog,
    hook_pair_survivor_coupled_family_holds_via_duality,
    verify_hook_pair_survivor_coupled_family_via_duality_catalog,
    verify_nonprincipal_general_mixed_block_duality_catalog,
    general_nonprincipal_mixed_family_holds_via_duality,
    verify_nonprincipal_general_mixed_family_via_duality_catalog,
    verify_nonprincipal_general_nonlinear_block_duality_catalog,
    general_nonprincipal_nonlinear_family_holds_via_duality,
    verify_nonprincipal_general_nonlinear_family_via_duality_catalog,
    verify_nonprincipal_general_survivor_coupled_block_duality_catalog,
    general_nonprincipal_survivor_coupled_family_holds_via_duality,
    verify_nonprincipal_general_survivor_coupled_family_via_duality_catalog,
    verify_nonprincipal_general_corrected_semidirect_catalog,
    verify_nonprincipal_general_corrected_semidirect_duality_catalog,
    general_nonprincipal_corrected_semidirect_family_holds_via_duality,
    verify_nonprincipal_general_corrected_semidirect_family_via_duality_catalog,
    verify_nonprincipal_two_row_mixed_block_duality_catalog,
    nonprincipal_two_row_mixed_family_holds_via_duality,
    verify_nonprincipal_two_row_mixed_family_via_duality_catalog,
    verify_nonprincipal_two_row_nonlinear_block_duality_catalog,
    nonprincipal_two_row_nonlinear_family_holds_via_duality,
    verify_nonprincipal_two_row_nonlinear_family_via_duality_catalog,
    verify_nonprincipal_two_row_survivor_coupled_block_duality_catalog,
    verify_nonprincipal_two_row_survivor_coupled_bundle,
    nonprincipal_two_row_survivor_coupled_family_holds_via_duality,
    verify_nonprincipal_two_row_survivor_coupled_family_via_duality_catalog,
    verify_nonprincipal_two_row_corrected_semidirect_catalog,
    verify_nonprincipal_two_row_corrected_semidirect_duality_catalog,
    verify_nonprincipal_two_row_corrected_semidirect_bundle,
    nonprincipal_two_row_corrected_semidirect_family_holds_via_duality,
    verify_nonprincipal_two_row_corrected_semidirect_family_via_duality_catalog,
    hook_pair_surviving_field_candidates,
    hook_pair_reduced_brackets,
    first_nonselfdual_hook_pair_ds_seed,
    first_nonselfdual_hook_pair_ghost_profiles,
    first_nonselfdual_hook_pair_constraint_characters,
    first_nonselfdual_hook_pair_constraints,
    first_nonselfdual_hook_pair_current_action_terms,
    first_nonselfdual_hook_pair_survivor_action_terms,
    first_nonselfdual_hook_pair_survivor_action_lift_witnesses,
    first_nonselfdual_hook_pair_constraint_current_witnesses,
    first_nonselfdual_hook_pair_survivor_derivation_defects,
    first_nonselfdual_hook_pair_derivation_defect_witnesses,
    first_nonselfdual_hook_pair_first_transfer_correction_witnesses,
    first_nonselfdual_hook_pair_first_transfer_correction_terms,
    first_nonselfdual_hook_pair_corrected_survivor_action_terms,
    first_nonselfdual_hook_pair_corrected_survivor_derivation_defects,
    first_nonselfdual_hook_pair_positive_nilpotent_brackets,
    first_nonselfdual_hook_pair_quadratic_ghost_term_support,
    first_nonselfdual_hook_pair_ghost_label_map,
    first_nonselfdual_hook_pair_ghost_side_map,
    first_nonselfdual_hook_pair_ghost_complexes_match_under_relabeling,
    first_nonselfdual_hook_pair_linear_constraint_blocks,
    first_nonselfdual_hook_pair_mixed_constraint_ghost_blocks,
    first_nonselfdual_hook_pair_mixed_blocks_match_under_relabeling,
    first_nonselfdual_hook_pair_nonlinear_mixed_constraint_ghost_blocks,
    first_nonselfdual_hook_pair_nonlinear_blocks_match_under_relabeling,
    first_nonselfdual_hook_pair_survivor_coupled_blocks_match_under_relabeling,
    first_nonselfdual_hook_pair_internal_survivor_ce_blocks,
    first_nonselfdual_hook_pair_semidirect_survivor_blocks,
    first_nonselfdual_hook_pair_corrected_semidirect_survivor_blocks,
    first_nonselfdual_hook_pair_survivor_coupled_blocks,
    first_nonselfdual_hook_pair_surviving_field_candidates,
    first_nonselfdual_hook_pair_reduced_brackets,
    first_nonselfdual_hook_pair_specialized_complexes,
    sl3_subregular_brst_blueprint,
    verify_ds_reduction_seed,
)

__all__ = [
    # Types
    "GradedVectorSpace", "ChainComplex", "OPEAlgebra", "Generator",
    # Algebra constructors
    "heisenberg_algebra", "sl2_algebra", "virasoro_algebra", "free_fermion_algebra",
    # Lie algebra
    "cartan_data", "sugawara_c", "ff_dual_level", "kappa_km",
    # Registry
    "ALGEBRA_REGISTRY", "KNOWN_BAR_DIMS", "verify_bar_dim",
    # Koszul dual
    "quadratic_dual_dims", "verify_koszul", "riordan", "motzkin",
    # Orlik-Solomon
    "os_dimension", "os_basis", "residue_map",
    # Pronilpotent completion
    "max_bar_degree", "effective_generator_weights",
    "w_infinity_generator_weights", "ordered_weight_monomials",
    "weight_sector_profile", "degree_sector_dimension_formula",
    "total_sector_dimension_formula", "w_infinity_weight_sector",
    "verify_w_infinity_completion",
    # Truncated W_infinity OPE
    "TruncatedWinfinityOPE", "verify_truncated_w_infinity_ope",
    # Truncated W_infinity support complex
    "TruncatedWinfinitySupportComplex", "verify_w_infinity_support_complex",
    # W_infinity dual-candidate package
    "completed_bar_candidate_descriptor",
    "stage3_dual_constraint_report",
    "stage4_higher_spin_constraint_map",
    "stage4_virasoro_constraint_map",
    "stage4_dual_constraint_report",
    "stage4_residue_symbol_map",
    "stage4_dual_defect_map",
    "stage4_dual_goal_report",
    "stage4_primitive_square_class_report",
    "stage4_pairing_reduction_report",
    "stage4_primitive_transport_report",
    "stage4_borcherds_transport_report",
    "stage4_two_primitive_square_closure_report",
    "stage4_local_attack_order_report",
    "stage4_target_packet_at_level",
    "evaluate_stage4_dual_defects_at_level",
    "stage4_defect_vanishing_report",
    "stage5_dual_frontier_report",
    "stage5_local_attack_order_report",
    "stage5_visible_pairing_normal_form_report",
    "stage5_principal_one_coefficient_normal_form_report",
    "stage5_principal_target5_no_new_independent_data_report",
    "stage5_principal_residual_front_one_coefficient_report",
    "stage5_principal_one_coefficient_factorization_report",
    "stage5_effective_independent_frontier_report",
    "stage5_one_coefficient_reduction_report",
    "stage5_one_defect_family_report",
    "stage5_conjecture_defect_dictionary_report",
    "stage5_exact_remaining_input_report",
    "stage5_visible_conjecture_network_collapse_report",
    "stage5_one_coefficient_comparison_report",
    "standard_winfinity_dual_candidate_report",
    "verify_standard_winfinity_dual_candidate",
    # MC2 cyclic CE
    "sl2_structure_constants", "sl2_killing_form",
    "sl3_structure_constants", "sl3_killing_form",
    "sp4_structure_constants", "sp4_killing_form",
    "ce_cohomology", "cyclic_ce_cohomology",
    "ce_exterior_differential", "cyclic_ce_via_exterior",
    "verify_sl2_ce_cohomology", "verify_sl2_cyclic_ce_cohomology",
    "verify_sl3_ce_cohomology", "verify_sl3_cyclic_ce_cohomology",
    "verify_sp4_ce_cohomology", "verify_sp4_cyclic_ce_cohomology",
    "verify_sl2_exterior_cross_check",
    # MC2 scaffolds
    "CoderivationDGLieModel", "CyclicLInfinityModel",
    "build_mc2_coderivation_dg_lie_model",
    "build_mc2_cyclic_linf_model",
    "build_mc2_sl2_coderivation_seed",
    "build_mc2_sl2_cyclic_linf_seed",
    "build_mc2_sl2_cyclic_linf_l3_seed",
    "build_shifted_symmetric_cyclic_linf_from_seed",
    "build_mc2_sl2_shifted_cyclic_linf_l3_seed",
    "shifted_seed_eta_channel_scaling_profile",
    "build_mc2_root_string_family_cyclic_linf_seed",
    "build_mc2_root_string_seed_packet_cyclic_linf_seed",
    "build_mc2_root_string_family_shifted_cyclic_linf_l3_seed",
    "build_mc2_root_string_seed_packet_shifted_cyclic_linf_l3_seed",
    "shifted_eta_root_string_family_profile",
    "shifted_eta_root_string_seed_packet_profile",
    "visible_lowarity_root_string_packet_from_shifted_seed",
    "infer_visible_lowarity_root_string_packet_from_obstruction",
    "visible_lowarity_root_string_transfer_package_from_shifted_seed",
    "visible_lowarity_root_string_l3_channel_recovery_from_shifted_seed",
    "reconstruct_root_string_shifted_seed_from_obstruction_profile",
    "root_string_ordered_seed_support_permutations",
    "visible_lowarity_root_string_incidence_orbit_profile_from_shifted_seed",
    "visible_lowarity_root_string_invariant_signature_from_shifted_seed",
    "visible_lowarity_root_string_signed_seed_character_from_shifted_seed",
    "mc2_visible_lowarity_root_string_orbit_table_profiles",
    "mc2_shifted_eta_root_string_signature_profiles",
    "shifted_seed_obstruction_polynomial_profile",
    "shifted_seed_obstruction_support_profile",
    "completed_tensor_product_surrogate",
    "clutching_map_via_l2",
    "clutching_series_via_l2",
    "boundary_clutching_series_via_l2",
    "verify_boundary_clutching_compatibility",
    "completed_l2_series",
    "completed_l3_series",
    "mc_residual_completed_truncated",
    "mc_residual_single_parameter",
    "mc_residual_three_parameter",
    "solve_mc_single_parameter",
    "verify_mc2_cyclic_linf_scaffold",
    "verify_mc2_completion_clutching_scaffold",
    "verify_mc2_sl2_seed_from_bar",
    "verify_mc2_sl2_l3_seed",
    "verify_mc2_sl2_shifted_seed_nontrivial_mc",
    "mc2_shifted_seed_one_channel_normalization_profiles",
    "verify_mc2_shifted_seed_one_channel_normalization",
    "verify_mc2_shifted_seed_eta_scaling_law",
    "verify_mc2_shifted_eta_root_string_signature_law",
    "verify_mc2_shifted_eta_root_string_family_law",
    "verify_mc2_shifted_eta_root_string_seed_packet_law",
    "verify_mc2_visible_lowarity_root_string_packet_law",
    "verify_mc2_visible_lowarity_root_string_packet_identifiability",
    "verify_mc2_visible_lowarity_root_string_transfer_package_law",
    "verify_mc2_visible_lowarity_root_string_l3_channel_recovery_law",
    "verify_mc2_visible_lowarity_root_string_chart_recovery_law",
    "verify_mc2_visible_lowarity_root_string_automorphism_rigidity_law",
    "verify_mc2_visible_lowarity_root_string_incidence_orbit_law",
    "verify_mc2_visible_lowarity_root_string_orbit_table_law",
    "verify_mc2_visible_lowarity_root_string_invariant_signature_law",
    "verify_mc2_visible_lowarity_root_string_seed_character_law",
    "verify_mc2_shifted_seed_obstruction_polynomial_law",
    "verify_mc2_shifted_eta_channel_ce_alignment",
    "verify_mc2_shifted_obstruction_support_truncation",
    "verify_mc2_shifted_one_channel_criterion_package",
    # MC2 sl_3 seed (universality)
    "build_mc2_sl3_coderivation_seed", "build_mc2_sl3_cyclic_linf_seed",
    "build_mc2_sl3_cyclic_linf_l3_seed",
    "build_mc2_sl3_shifted_cyclic_linf_l3_seed",
    "verify_mc2_sl3_seed", "verify_mc2_sl3_kappa_extraction",
    "verify_mc2_sl3_shifted_seed_nontrivial_mc",
    # MC2 sp_4 seed (non-simply-laced universality)
    "build_mc2_sp4_coderivation_seed", "build_mc2_sp4_cyclic_linf_seed",
    "build_mc2_sp4_cyclic_linf_l3_seed",
    "build_mc2_sp4_shifted_cyclic_linf_l3_seed",
    "verify_mc2_sp4_seed", "verify_mc2_sp4_kappa_extraction",
    "verify_mc2_sp4_shifted_seed_nontrivial_mc",
    # MC2 g_2 seed (exceptional universality)
    "build_mc2_g2_coderivation_seed", "build_mc2_g2_cyclic_linf_seed",
    "build_mc2_g2_cyclic_linf_l3_seed",
    "build_mc2_g2_shifted_cyclic_linf_l3_seed",
    "verify_mc2_g2_seed", "verify_mc2_g2_kappa_extraction",
    "verify_mc2_g2_shifted_seed_nontrivial_mc",
    # MC2 Step 3: kappa extraction
    "adjoint_casimir_matrix", "adjoint_casimir_eigenvalue",
    "dual_coxeter_from_seed", "kappa_from_seed", "kappa_two_channel",
    "verify_linf_arity4_identity", "verify_cyclic_l2_full", "verify_cyclic_l3_full",
    "verify_mc2_kappa_extraction", "verify_mc2_linf_identities",
    # Non-principal DS orbit scaffold
    "TRACK_CORE_PRINCIPAL", "TRACK_FRONTIER_NONPRINCIPAL",
    "STATUS_PROVED_SUBREGULAR_SL3", "STATUS_HOOK_EVIDENCE", "STATUS_PROGRAMME",
    "MatrixBasisExpression", "MatrixSl2Triple", "OrbitDualityCase", "HookOrbitPairProfile",
    "normalize_partition", "partition_size",
    "transpose_partition", "is_hook_partition", "hook_partition",
    "two_row_nonhook_partition",
    "subregular_partition", "type_a_bv_dual", "hook_dual_partition",
    "type_a_nilpotent_matrix", "type_a_hook_nilpotent_matrix",
    "type_a_partition_sl2_triple", "type_a_hook_sl2_triple",
    "type_a_hook_pair_sl2_triples",
    "standard_traceless_basis_sl_n", "matrix_to_traceless_basis_expression_sl_n",
    "nilpotent_partition_from_matrix", "matrix_centralizer_dimension_sl_n",
    "matrix_centralizer_basis_sl_n", "homogeneous_f_centralizer_basis_sl_n",
    "ad_h_grade_multiplicities_sl_n",
    "ad_h_graded_basis_labels_sl_n",
    "type_a_orbit_class", "centralizer_dimension_sl_n", "orbit_dimension_sl_n",
    "principal_ff_level_shift_type_a",
    "type_a_orbit_level_shift_correction_data",
    "nonprincipal_orbit_level_shift_type_a",
    "nonprincipal_hook_level_shift_type_a",
    "nonprincipal_hook_level_shift_ansatz_type_a",
    "nonprincipal_type_a_case", "type_a_general_nonprincipal_partitions",
    "nonprincipal_hook_case", "nonprincipal_hook_cases", "nonprincipal_general_cases",
    "nonprincipal_two_row_case", "nonprincipal_two_row_cases",
    "hook_orbit_pair_profile", "hook_orbit_pair_profile_catalog",
    "first_nonselfdual_hook_pair_nilpotent_matrices",
    "first_nonselfdual_hook_pair_centralizer_bases",
    "first_nonselfdual_hook_pair_sl2_triples",
    "first_nonselfdual_hook_pair_f_centralizer_bases",
    "verify_hook_orbit_pair_profile_catalog",
    "verify_nonprincipal_general_orbit_scaffold",
    "verify_nonprincipal_two_row_orbit_scaffold",
    "verify_nonprincipal_ds_orbit_scaffold",
    # BV duality scaffold
    "BVDualOrbit", "STATUS_EXACT_TYPE_A", "STATUS_HOOK_FRONTIER",
    "type_a_bv_dual", "is_type_a_self_dual_orbit", "type_a_bv_pair",
    "type_a_hook_bv_pair", "first_nonselfdual_type_a_hook_pair",
    "verify_bv_duality_scaffold",
    # Non-principal DS seed reductions
    "NonprincipalDSSeed", "bp_dual_level", "bp_central_charge",
    "bp_residual_sl2_level", "bp_residual_sl2_dual_relation",
    "bp_complementarity_sum", "bp_complementarity_constant",
    "bp_curvature_proxy", "bp_curvature_dual_relation",
    "sl3_subregular_good_grading_multiplicities",
    "hook_constraint_count_ansatz_type_a",
    "hook_pair_constraint_counts_ansatz_type_a",
    "verify_hook_constraint_count_ansatz",
    "bp_current_presentation", "bp_strong_presentation",
    "nonprincipal_type_a_seed",
    "sl3_subregular_bp_seed", "nonprincipal_hook_seed",
    "nonprincipal_hook_seed_catalog", "nonprincipal_general_seed",
    "nonprincipal_general_seed_catalog", "nonprincipal_two_row_seed",
    "nonprincipal_two_row_seed_catalog",
    "first_nonselfdual_hook_seed",
    "verify_nonprincipal_general_seed_catalog",
    "verify_nonprincipal_hook_seed_catalog",
    "verify_nonprincipal_two_row_seed_catalog",
    "verify_nonprincipal_ds_reduction_seed",
    # Non-principal DS normalization bridge
    "CentralChargeConvention", "RAW_BP_CONVENTION", "CHAPTER_BP_SUM_CONVENTION",
    "bp_dual_sum_under_convention", "shift_to_target_dual_sum",
    "bp_shift_to_target_sum", "bp_shifted_convention_for_target",
    "verify_nonprincipal_ds_normalization",
    # DS reduction seed scaffold
    "Sl2TripleSeed", "DSGhostWeight", "DSReductionSeed",
    "TruncatedBRSTComplex", "HookPairDSComplexSeed", "LinearConstraintBRSTBlock",
    "MixedConstraintGhostBRSTBlock", "SurvivorCoupledBRSTBlock", "InternalSurvivorCEBlock",
    "SemidirectSurvivorBRSTBlock",
    "DSBasisElement", "DSConstraint", "DSBRSTBlueprint", "DSReducedFieldCandidate",
    "CurrentActionTermEntry", "SurvivorActionTermEntry",
    "SurvivorActionLiftWitness", "SurvivorDerivationDefectWitness",
    "FirstTransferCorrectionWitness", "QuadraticGhostTermEntry",
    "STATUS_DS_SEED", "brst_ghost_weights", "matrix_commutator",
    "ds_basis_expression_matrix", "exterior_basis_indices", "homogeneous_monomial_exponents",
    "linear_constraint_block_basis", "character_wedge_differential",
    "quadratic_ghost_differential", "ghost_brst_differential",
    "linear_constraint_koszul_differential", "build_character_wedge_complex",
    "build_ghost_brst_complex",
    "build_mixed_constraint_ghost_brst_block",
    "current_action_differential", "survivor_action_differential",
    "build_survivor_coupled_brst_block", "build_internal_survivor_ce_block",
    "build_semidirect_survivor_brst_block",
    "relabel_quadratic_ghost_terms", "relabel_current_action_terms",
    "relabel_truncated_brst_complex",
    "relabel_mixed_constraint_ghost_block",
    "build_linear_constraint_koszul_block", "differential_square_blocks",
    "chain_homology_dimensions", "mixed_constraint_ghost_block_basis",
    "mixed_constraint_ghost_brst_differential",
    "mixed_constraint_ghost_block_homology_dimensions",
    "survivor_coupled_block_basis",
    "survivor_coupled_block_homology_dimensions",
    "internal_survivor_ce_block_basis",
    "internal_survivor_ce_h0_basis",
    "internal_survivor_ce_block_homology_dimensions",
    "internal_survivor_h0_monomial_labels",
    "internal_survivor_linear_h0_labels",
    "semidirect_survivor_block_basis",
    "semidirect_survivor_block_homology_dimensions",
    "complex_has_nilpotent_differential",
    "mixed_constraint_ghost_block_has_square_zero",
    "mixed_constraint_ghost_block_is_acyclic",
    "survivor_coupled_block_has_square_zero",
    "survivor_coupled_block_is_acyclic",
    "internal_survivor_ce_block_has_square_zero",
    "internal_survivor_ce_block_is_acyclic",
    "semidirect_survivor_block_has_square_zero",
    "semidirect_survivor_block_is_acyclic",
    "linear_constraint_block_has_square_zero", "linear_constraint_contracting_homotopy",
    "specialize_complex_chi",
    "truncated_cohomology_dimensions", "complex_is_acyclic",
    "linear_constraint_block_has_contracting_homotopy",
    "linear_constraint_block_is_positive_acyclic",
    "sl3_subregular_sl2_triple",
    "sl3_subregular_basis_grades", "sl3_subregular_basis_matrices",
    "sl3_subregular_basis_profile", "sl3_subregular_ad_e_image_witnesses",
    "sl3_subregular_ad_e_image_basis",
    "sl3_subregular_project_expression_to_strong_candidates",
    "sl3_subregular_project_basis_label_to_strong_candidates",
    "sl3_subregular_projected_strong_brackets",
    "sl3_subregular_strong_generator_candidates",
    "sl3_subregular_positive_grades", "sl3_subregular_ghost_profile",
    "sl3_subregular_constraint_character", "sl3_subregular_constraints",
    "sl3_subregular_survivor_action_terms",
    "sl3_subregular_survivor_action_lift_witnesses",
    "sl3_subregular_survivor_derivation_defects",
    "sl3_subregular_derivation_defect_witnesses",
    "sl3_subregular_first_transfer_correction_witnesses",
    "sl3_subregular_first_transfer_correction_terms",
    "sl3_subregular_corrected_survivor_action_terms",
    "sl3_subregular_corrected_survivor_derivation_defects",
    "sl3_subregular_positive_nilpotent_brackets",
    "sl3_subregular_ds_seed", "sl3_subregular_linear_constraint_blocks",
    "sl3_subregular_mixed_constraint_ghost_blocks",
    "sl3_subregular_nonlinear_mixed_constraint_ghost_blocks",
    "sl3_subregular_internal_survivor_ce_blocks",
    "sl3_subregular_semidirect_survivor_blocks",
    "sl3_subregular_corrected_semidirect_survivor_blocks",
    "sl3_subregular_survivor_coupled_blocks",
    "sl3_subregular_truncated_brst_complex",
    "first_nonselfdual_hook_pair_basis_profiles",
    "first_nonselfdual_hook_pair_brst_blueprints",
    "hook_pair_ds_seed",
    "hook_pair_ghost_profiles",
    "hook_pair_constraint_characters",
    "hook_pair_constraints",
    "hook_pair_positive_nilpotent_brackets",
    "hook_pair_quadratic_ghost_term_support",
    "hook_pair_current_action_terms",
    "hook_pair_survivor_action_terms",
    "hook_pair_survivor_action_lift_witnesses",
    "hook_pair_constraint_current_witnesses",
    "partition_pair_constraints",
    "partition_pair_positive_nilpotent_brackets",
    "partition_pair_quadratic_ghost_term_support",
    "partition_pair_current_action_terms",
    "partition_pair_survivor_action_terms",
    "partition_pair_survivor_action_lift_witnesses",
    "partition_pair_constraint_current_witnesses",
    "partition_pair_survivor_derivation_defects",
    "partition_pair_first_transfer_correction_witnesses",
    "partition_pair_first_transfer_correction_terms",
    "partition_pair_corrected_survivor_action_terms",
    "partition_pair_corrected_survivor_derivation_defects",
    "partition_pair_surviving_field_candidates",
    "partition_pair_reduced_brackets",
    "partition_pair_internal_survivor_ce_blocks",
    "hook_pair_survivor_derivation_defects",
    "hook_pair_first_transfer_correction_witnesses",
    "hook_pair_first_transfer_correction_terms",
    "hook_pair_derivation_defect_witnesses",
    "hook_pair_corrected_survivor_action_terms",
    "hook_pair_corrected_survivor_derivation_defects",
    "hook_pair_specialized_complexes", "hook_pair_ds_seed_catalog",
    "verify_hook_pair_ds_seed_catalog", "verify_hook_pair_seed_alignment",
    "verify_hook_pair_first_transfer_correction_catalog",
    "verify_hook_pair_corrected_semidirect_catalog",
    "verify_hook_pair_corrected_semidirect_duality_catalog",
    "hook_pair_corrected_semidirect_family_holds_via_duality",
    "verify_hook_pair_corrected_semidirect_family_via_duality_catalog",
    "hook_pair_linear_constraint_blocks",
    "hook_pair_mixed_constraint_ghost_blocks",
    "hook_pair_nonlinear_mixed_constraint_ghost_blocks",
    "hook_pair_survivor_coupled_blocks",
    "nonprincipal_partition_pair_mixed_constraint_ghost_blocks",
    "nonprincipal_partition_pair_nonlinear_mixed_constraint_ghost_blocks",
    "nonprincipal_partition_pair_semidirect_survivor_blocks",
    "nonprincipal_partition_pair_corrected_semidirect_survivor_blocks",
    "nonprincipal_partition_pair_survivor_coupled_blocks",
    "hook_pair_semidirect_survivor_blocks",
    "hook_pair_corrected_semidirect_survivor_blocks",
    "nonprincipal_two_row_internal_survivor_ce_blocks",
    "nonprincipal_two_row_mixed_constraint_ghost_blocks",
    "nonprincipal_two_row_nonlinear_mixed_constraint_ghost_blocks",
    "nonprincipal_two_row_semidirect_survivor_blocks",
    "nonprincipal_two_row_corrected_semidirect_survivor_blocks",
    "nonprincipal_two_row_survivor_coupled_blocks",
    "nonprincipal_partition_pair_mixed_blocks_match_under_dual_swap",
    "nonprincipal_partition_pair_nonlinear_blocks_match_under_dual_swap",
    "nonprincipal_partition_pair_survivor_coupled_blocks_match_under_dual_swap",
    "nonprincipal_partition_pair_corrected_semidirect_blocks_match_under_dual_swap",
    "nonprincipal_two_row_mixed_blocks_match_under_dual_swap",
    "nonprincipal_two_row_nonlinear_blocks_match_under_dual_swap",
    "nonprincipal_two_row_survivor_coupled_blocks_match_under_dual_swap",
    "nonprincipal_two_row_corrected_semidirect_blocks_match_under_dual_swap",
    "hook_pair_mixed_blocks_match_under_dual_swap",
    "hook_pair_nonlinear_blocks_match_under_dual_swap",
    "hook_pair_survivor_coupled_blocks_match_under_dual_swap",
    "hook_pair_corrected_semidirect_blocks_match_under_dual_swap",
    "verify_hook_pair_mixed_block_duality_catalog",
    "hook_pair_mixed_family_holds_via_duality",
    "verify_hook_pair_mixed_family_via_duality_catalog",
    "verify_hook_pair_nonlinear_block_duality_catalog",
    "hook_pair_nonlinear_family_holds_via_duality",
    "verify_hook_pair_nonlinear_family_via_duality_catalog",
    "verify_hook_pair_survivor_coupled_block_duality_catalog",
    "hook_pair_survivor_coupled_family_holds_via_duality",
    "verify_hook_pair_survivor_coupled_family_via_duality_catalog",
    "verify_nonprincipal_general_mixed_block_duality_catalog",
    "general_nonprincipal_mixed_family_holds_via_duality",
    "verify_nonprincipal_general_mixed_family_via_duality_catalog",
    "verify_nonprincipal_general_nonlinear_block_duality_catalog",
    "general_nonprincipal_nonlinear_family_holds_via_duality",
    "verify_nonprincipal_general_nonlinear_family_via_duality_catalog",
    "verify_nonprincipal_general_survivor_coupled_block_duality_catalog",
    "general_nonprincipal_survivor_coupled_family_holds_via_duality",
    "verify_nonprincipal_general_survivor_coupled_family_via_duality_catalog",
    "verify_nonprincipal_general_corrected_semidirect_catalog",
    "verify_nonprincipal_general_corrected_semidirect_duality_catalog",
    "general_nonprincipal_corrected_semidirect_family_holds_via_duality",
    "verify_nonprincipal_general_corrected_semidirect_family_via_duality_catalog",
    "verify_nonprincipal_two_row_mixed_block_duality_catalog",
    "nonprincipal_two_row_mixed_family_holds_via_duality",
    "verify_nonprincipal_two_row_mixed_family_via_duality_catalog",
    "verify_nonprincipal_two_row_nonlinear_block_duality_catalog",
    "nonprincipal_two_row_nonlinear_family_holds_via_duality",
    "verify_nonprincipal_two_row_nonlinear_family_via_duality_catalog",
    "verify_nonprincipal_two_row_survivor_coupled_block_duality_catalog",
    "verify_nonprincipal_two_row_survivor_coupled_bundle",
    "nonprincipal_two_row_survivor_coupled_family_holds_via_duality",
    "verify_nonprincipal_two_row_survivor_coupled_family_via_duality_catalog",
    "verify_nonprincipal_two_row_corrected_semidirect_catalog",
    "verify_nonprincipal_two_row_corrected_semidirect_duality_catalog",
    "verify_nonprincipal_two_row_corrected_semidirect_bundle",
    "nonprincipal_two_row_corrected_semidirect_family_holds_via_duality",
    "verify_nonprincipal_two_row_corrected_semidirect_family_via_duality_catalog",
    "hook_pair_surviving_field_candidates",
    "hook_pair_reduced_brackets",
    "first_nonselfdual_hook_pair_ds_seed",
    "first_nonselfdual_hook_pair_ghost_profiles",
    "first_nonselfdual_hook_pair_constraint_characters",
    "first_nonselfdual_hook_pair_constraints",
    "first_nonselfdual_hook_pair_current_action_terms",
    "first_nonselfdual_hook_pair_survivor_action_terms",
    "first_nonselfdual_hook_pair_survivor_action_lift_witnesses",
    "first_nonselfdual_hook_pair_constraint_current_witnesses",
    "first_nonselfdual_hook_pair_survivor_derivation_defects",
    "first_nonselfdual_hook_pair_derivation_defect_witnesses",
    "first_nonselfdual_hook_pair_first_transfer_correction_witnesses",
    "first_nonselfdual_hook_pair_first_transfer_correction_terms",
    "first_nonselfdual_hook_pair_corrected_survivor_action_terms",
    "first_nonselfdual_hook_pair_corrected_survivor_derivation_defects",
    "first_nonselfdual_hook_pair_positive_nilpotent_brackets",
    "first_nonselfdual_hook_pair_quadratic_ghost_term_support",
    "first_nonselfdual_hook_pair_ghost_label_map",
    "first_nonselfdual_hook_pair_ghost_side_map",
    "first_nonselfdual_hook_pair_ghost_complexes_match_under_relabeling",
    "first_nonselfdual_hook_pair_linear_constraint_blocks",
    "first_nonselfdual_hook_pair_mixed_constraint_ghost_blocks",
    "first_nonselfdual_hook_pair_mixed_blocks_match_under_relabeling",
    "first_nonselfdual_hook_pair_nonlinear_mixed_constraint_ghost_blocks",
    "first_nonselfdual_hook_pair_nonlinear_blocks_match_under_relabeling",
    "first_nonselfdual_hook_pair_survivor_coupled_blocks_match_under_relabeling",
    "first_nonselfdual_hook_pair_internal_survivor_ce_blocks",
    "first_nonselfdual_hook_pair_semidirect_survivor_blocks",
    "first_nonselfdual_hook_pair_corrected_semidirect_survivor_blocks",
    "first_nonselfdual_hook_pair_survivor_coupled_blocks",
    "first_nonselfdual_hook_pair_surviving_field_candidates",
    "first_nonselfdual_hook_pair_reduced_brackets",
    "first_nonselfdual_hook_pair_specialized_complexes",
    "sl3_subregular_brst_blueprint",
    "verify_ds_reduction_seed",
    # Utility
    "partition_number", "lambda_fp", "F_g",
]
