"""Chiral bar-cobar compute engine.

Core types and algebra constructors for the monograph's computational kernel.

Usage:
    from compute.lib import OPEAlgebra, Generator
    from compute.lib import heisenberg_algebra, sl2_algebra, virasoro_algebra
    from compute.lib import GradedVectorSpace, ChainComplex
"""

# Core types
from compute.lib.utils import GradedVectorSpace, ChainComplex, partition_number, lambda_fp, F_g
from compute.lib.bar_complex import OPEAlgebra, Generator

# Standard algebra constructors
from compute.lib.bar_complex import (
    heisenberg_algebra,
    sl2_algebra,
    virasoro_algebra,
    free_fermion_algebra,
)

# Lie algebra data
from compute.lib.lie_algebra import cartan_data, sugawara_c, ff_dual_level, kappa_km

# Cross-algebra registry
from compute.lib.cross_algebra import ALGEBRA_REGISTRY

# Bar cohomology dimensions (known values)
from compute.lib.bar_complex import KNOWN_BAR_DIMS, verify_bar_dim

# Koszul dual Hilbert series
from compute.lib.koszul_hilbert import quadratic_dual_dims, verify_koszul, riordan, motzkin

# Orlik-Solomon algebra
from compute.lib.os_algebra import os_dimension, os_basis, residue_map

# Pronilpotent weight-filtered completion (MC4 scaffold)
from compute.lib.pronilpotent_bar import (
    max_bar_degree,
    effective_generator_weights,
    w_infinity_generator_weights,
    ordered_weight_monomials,
    weight_sector_profile,
    degree_sector_dimension_formula,
    total_sector_dimension_formula,
    w_infinity_weight_sector,
    verify_w_infinity_completion,
)

# Truncated W_infinity structural OPE scaffold (MC4 / Tool 8.2)
from compute.lib.w_infinity_ope import (
    TruncatedWinfinityOPE,
    verify_truncated_w_infinity_ope,
)
from compute.lib.w_infinity_support_complex import (
    TruncatedWinfinitySupportComplex,
    verify_w_infinity_support_complex,
)

# MC2 scaffold: cyclic L-infinity control on coderivations
from compute.lib.mc2_cyclic_linf import (
    CoderivationDGLieModel,
    CyclicLInfinityModel,
    build_mc2_coderivation_dg_lie_model,
    build_mc2_cyclic_linf_model,
    mc_residual_single_parameter,
    solve_mc_single_parameter,
    verify_mc2_cyclic_linf_scaffold,
)

# Non-principal DS orbit scaffold (hook/subregular frontier)
from compute.lib.nonprincipal_ds_orbits import (
    TRACK_CORE_PRINCIPAL,
    TRACK_FRONTIER_NONPRINCIPAL,
    STATUS_PROVED_SUBREGULAR_SL3,
    STATUS_HOOK_EVIDENCE,
    STATUS_PROGRAMME,
    MatrixBasisExpression,
    MatrixSl2Triple,
    OrbitDualityCase,
    HookOrbitPairProfile,
    normalize_partition,
    partition_size,
    transpose_partition,
    is_hook_partition,
    hook_partition,
    subregular_partition,
    type_a_bv_dual,
    hook_dual_partition,
    type_a_nilpotent_matrix,
    type_a_hook_nilpotent_matrix,
    type_a_partition_sl2_triple,
    type_a_hook_sl2_triple,
    type_a_hook_pair_sl2_triples,
    standard_traceless_basis_sl_n,
    matrix_to_traceless_basis_expression_sl_n,
    nilpotent_partition_from_matrix,
    matrix_centralizer_dimension_sl_n,
    matrix_centralizer_basis_sl_n,
    homogeneous_f_centralizer_basis_sl_n,
    ad_h_grade_multiplicities_sl_n,
    ad_h_graded_basis_labels_sl_n,
    type_a_orbit_class,
    centralizer_dimension_sl_n,
    orbit_dimension_sl_n,
    principal_ff_level_shift_type_a,
    nonprincipal_hook_level_shift_ansatz_type_a,
    nonprincipal_hook_case,
    nonprincipal_hook_cases,
    hook_orbit_pair_profile,
    hook_orbit_pair_profile_catalog,
    first_nonselfdual_hook_pair_nilpotent_matrices,
    first_nonselfdual_hook_pair_centralizer_bases,
    first_nonselfdual_hook_pair_sl2_triples,
    first_nonselfdual_hook_pair_f_centralizer_bases,
    verify_hook_orbit_pair_profile_catalog,
    verify_nonprincipal_ds_orbit_scaffold,
)

# BV duality + non-principal DS seed reductions
from compute.lib.bv_duality import (
    BVDualOrbit,
    STATUS_EXACT_TYPE_A,
    STATUS_HOOK_FRONTIER,
    type_a_bv_dual,
    is_type_a_self_dual_orbit,
    type_a_bv_pair,
    type_a_hook_bv_pair,
    first_nonselfdual_type_a_hook_pair,
    verify_bv_duality_scaffold,
)
from compute.lib.nonprincipal_ds_reduction import (
    NonprincipalDSSeed,
    bp_dual_level,
    bp_residual_sl2_level,
    bp_residual_sl2_dual_relation,
    bp_central_charge,
    bp_complementarity_sum,
    bp_complementarity_constant,
    bp_curvature_proxy,
    bp_curvature_dual_relation,
    sl3_subregular_good_grading_multiplicities,
    hook_constraint_count_ansatz_type_a,
    hook_pair_constraint_counts_ansatz_type_a,
    verify_hook_constraint_count_ansatz,
    bp_current_presentation,
    bp_strong_presentation,
    sl3_subregular_bp_seed,
    nonprincipal_hook_seed,
    nonprincipal_hook_seed_catalog,
    first_nonselfdual_hook_seed,
    verify_nonprincipal_hook_seed_catalog,
    verify_nonprincipal_ds_reduction_seed,
)
from compute.lib.nonprincipal_ds_normalization import (
    CentralChargeConvention,
    RAW_BP_CONVENTION,
    CHAPTER_BP_SUM_CONVENTION,
    bp_dual_sum_under_convention,
    shift_to_target_dual_sum,
    bp_shift_to_target_sum,
    bp_shifted_convention_for_target,
    verify_nonprincipal_ds_normalization,
)
from compute.lib.ds_reduction import (
    Sl2TripleSeed,
    DSGhostWeight,
    DSReductionSeed,
    TruncatedBRSTComplex,
    HookPairDSComplexSeed,
    LinearConstraintBRSTBlock,
    MixedConstraintGhostBRSTBlock,
    SurvivorCoupledBRSTBlock,
    InternalSurvivorCEBlock,
    DSBasisElement,
    DSConstraint,
    DSBRSTBlueprint,
    DSReducedFieldCandidate,
    CurrentActionTermEntry,
    SurvivorActionTermEntry,
    QuadraticGhostTermEntry,
    STATUS_DS_SEED,
    brst_ghost_weights,
    matrix_commutator,
    ds_basis_expression_matrix,
    exterior_basis_indices,
    homogeneous_monomial_exponents,
    linear_constraint_block_basis,
    character_wedge_differential,
    quadratic_ghost_differential,
    ghost_brst_differential,
    linear_constraint_koszul_differential,
    build_character_wedge_complex,
    build_ghost_brst_complex,
    build_mixed_constraint_ghost_brst_block,
    current_action_differential,
    survivor_action_differential,
    build_survivor_coupled_brst_block,
    build_internal_survivor_ce_block,
    relabel_quadratic_ghost_terms,
    relabel_current_action_terms,
    relabel_truncated_brst_complex,
    relabel_mixed_constraint_ghost_block,
    build_linear_constraint_koszul_block,
    differential_square_blocks,
    chain_homology_dimensions,
    mixed_constraint_ghost_block_basis,
    mixed_constraint_ghost_brst_differential,
    mixed_constraint_ghost_block_homology_dimensions,
    survivor_coupled_block_basis,
    survivor_coupled_block_homology_dimensions,
    internal_survivor_ce_block_basis,
    internal_survivor_ce_block_homology_dimensions,
    complex_has_nilpotent_differential,
    mixed_constraint_ghost_block_has_square_zero,
    mixed_constraint_ghost_block_is_acyclic,
    survivor_coupled_block_has_square_zero,
    survivor_coupled_block_is_acyclic,
    internal_survivor_ce_block_has_square_zero,
    internal_survivor_ce_block_is_acyclic,
    linear_constraint_block_has_square_zero,
    linear_constraint_contracting_homotopy,
    specialize_complex_chi,
    truncated_cohomology_dimensions,
    complex_is_acyclic,
    linear_constraint_block_has_contracting_homotopy,
    linear_constraint_block_is_positive_acyclic,
    sl3_subregular_sl2_triple,
    sl3_subregular_basis_grades,
    sl3_subregular_basis_matrices,
    sl3_subregular_basis_profile,
    sl3_subregular_ad_e_image_witnesses,
    sl3_subregular_ad_e_image_basis,
    sl3_subregular_project_expression_to_strong_candidates,
    sl3_subregular_project_basis_label_to_strong_candidates,
    sl3_subregular_projected_strong_brackets,
    sl3_subregular_strong_generator_candidates,
    sl3_subregular_positive_grades,
    sl3_subregular_ghost_profile,
    sl3_subregular_constraint_character,
    sl3_subregular_constraints,
    sl3_subregular_survivor_action_terms,
    sl3_subregular_positive_nilpotent_brackets,
    sl3_subregular_ds_seed,
    sl3_subregular_linear_constraint_blocks,
    sl3_subregular_mixed_constraint_ghost_blocks,
    sl3_subregular_nonlinear_mixed_constraint_ghost_blocks,
    sl3_subregular_internal_survivor_ce_blocks,
    sl3_subregular_survivor_coupled_blocks,
    sl3_subregular_truncated_brst_complex,
    first_nonselfdual_hook_pair_basis_profiles,
    first_nonselfdual_hook_pair_brst_blueprints,
    hook_pair_ds_seed,
    hook_pair_ghost_profiles,
    hook_pair_constraint_characters,
    hook_pair_constraints,
    hook_pair_positive_nilpotent_brackets,
    hook_pair_quadratic_ghost_term_support,
    hook_pair_current_action_terms,
    hook_pair_specialized_complexes,
    hook_pair_ds_seed_catalog,
    verify_hook_pair_ds_seed_catalog,
    verify_hook_pair_seed_alignment,
    hook_pair_linear_constraint_blocks,
    hook_pair_mixed_constraint_ghost_blocks,
    hook_pair_nonlinear_mixed_constraint_ghost_blocks,
    hook_pair_mixed_blocks_match_under_dual_swap,
    hook_pair_nonlinear_blocks_match_under_dual_swap,
    verify_hook_pair_mixed_block_duality_catalog,
    verify_hook_pair_nonlinear_block_duality_catalog,
    hook_pair_surviving_field_candidates,
    hook_pair_reduced_brackets,
    first_nonselfdual_hook_pair_ds_seed,
    first_nonselfdual_hook_pair_ghost_profiles,
    first_nonselfdual_hook_pair_constraint_characters,
    first_nonselfdual_hook_pair_constraints,
    first_nonselfdual_hook_pair_current_action_terms,
    first_nonselfdual_hook_pair_survivor_action_terms,
    first_nonselfdual_hook_pair_positive_nilpotent_brackets,
    first_nonselfdual_hook_pair_quadratic_ghost_term_support,
    first_nonselfdual_hook_pair_ghost_label_map,
    first_nonselfdual_hook_pair_ghost_side_map,
    first_nonselfdual_hook_pair_ghost_complexes_match_under_relabeling,
    first_nonselfdual_hook_pair_linear_constraint_blocks,
    first_nonselfdual_hook_pair_mixed_constraint_ghost_blocks,
    first_nonselfdual_hook_pair_mixed_blocks_match_under_relabeling,
    first_nonselfdual_hook_pair_nonlinear_mixed_constraint_ghost_blocks,
    first_nonselfdual_hook_pair_nonlinear_blocks_match_under_relabeling,
    first_nonselfdual_hook_pair_internal_survivor_ce_blocks,
    first_nonselfdual_hook_pair_survivor_coupled_blocks,
    first_nonselfdual_hook_pair_surviving_field_candidates,
    first_nonselfdual_hook_pair_reduced_brackets,
    first_nonselfdual_hook_pair_specialized_complexes,
    sl3_subregular_brst_blueprint,
    verify_ds_reduction_seed,
)

__all__ = [
    # Types
    "GradedVectorSpace", "ChainComplex", "OPEAlgebra", "Generator",
    # Algebra constructors
    "heisenberg_algebra", "sl2_algebra", "virasoro_algebra", "free_fermion_algebra",
    # Lie algebra
    "cartan_data", "sugawara_c", "ff_dual_level", "kappa_km",
    # Registry
    "ALGEBRA_REGISTRY", "KNOWN_BAR_DIMS", "verify_bar_dim",
    # Koszul dual
    "quadratic_dual_dims", "verify_koszul", "riordan", "motzkin",
    # Orlik-Solomon
    "os_dimension", "os_basis", "residue_map",
    # Pronilpotent completion
    "max_bar_degree", "effective_generator_weights",
    "w_infinity_generator_weights", "ordered_weight_monomials",
    "weight_sector_profile", "degree_sector_dimension_formula",
    "total_sector_dimension_formula", "w_infinity_weight_sector",
    "verify_w_infinity_completion",
    # Truncated W_infinity OPE
    "TruncatedWinfinityOPE", "verify_truncated_w_infinity_ope",
    # Truncated W_infinity support complex
    "TruncatedWinfinitySupportComplex", "verify_w_infinity_support_complex",
    # Non-principal DS orbit scaffold
    "TRACK_CORE_PRINCIPAL", "TRACK_FRONTIER_NONPRINCIPAL",
    "STATUS_PROVED_SUBREGULAR_SL3", "STATUS_HOOK_EVIDENCE", "STATUS_PROGRAMME",
    "MatrixBasisExpression", "MatrixSl2Triple", "OrbitDualityCase", "HookOrbitPairProfile",
    "normalize_partition", "partition_size",
    "transpose_partition", "is_hook_partition", "hook_partition",
    "subregular_partition", "type_a_bv_dual", "hook_dual_partition",
    "type_a_nilpotent_matrix", "type_a_hook_nilpotent_matrix",
    "type_a_partition_sl2_triple", "type_a_hook_sl2_triple",
    "type_a_hook_pair_sl2_triples",
    "standard_traceless_basis_sl_n", "matrix_to_traceless_basis_expression_sl_n",
    "nilpotent_partition_from_matrix", "matrix_centralizer_dimension_sl_n",
    "matrix_centralizer_basis_sl_n", "homogeneous_f_centralizer_basis_sl_n",
    "ad_h_grade_multiplicities_sl_n",
    "ad_h_graded_basis_labels_sl_n",
    "type_a_orbit_class", "centralizer_dimension_sl_n", "orbit_dimension_sl_n",
    "principal_ff_level_shift_type_a", "nonprincipal_hook_level_shift_ansatz_type_a",
    "nonprincipal_hook_case", "nonprincipal_hook_cases",
    "hook_orbit_pair_profile", "hook_orbit_pair_profile_catalog",
    "first_nonselfdual_hook_pair_nilpotent_matrices",
    "first_nonselfdual_hook_pair_centralizer_bases",
    "first_nonselfdual_hook_pair_sl2_triples",
    "first_nonselfdual_hook_pair_f_centralizer_bases",
    "verify_hook_orbit_pair_profile_catalog",
    "verify_nonprincipal_ds_orbit_scaffold",
    # BV duality scaffold
    "BVDualOrbit", "STATUS_EXACT_TYPE_A", "STATUS_HOOK_FRONTIER",
    "type_a_bv_dual", "is_type_a_self_dual_orbit", "type_a_bv_pair",
    "type_a_hook_bv_pair", "first_nonselfdual_type_a_hook_pair",
    "verify_bv_duality_scaffold",
    # Non-principal DS seed reductions
    "NonprincipalDSSeed", "bp_dual_level", "bp_central_charge",
    "bp_residual_sl2_level", "bp_residual_sl2_dual_relation",
    "bp_complementarity_sum", "bp_complementarity_constant",
    "bp_curvature_proxy", "bp_curvature_dual_relation",
    "sl3_subregular_good_grading_multiplicities",
    "hook_constraint_count_ansatz_type_a",
    "hook_pair_constraint_counts_ansatz_type_a",
    "verify_hook_constraint_count_ansatz",
    "bp_current_presentation", "bp_strong_presentation",
    "sl3_subregular_bp_seed", "nonprincipal_hook_seed",
    "nonprincipal_hook_seed_catalog", "first_nonselfdual_hook_seed",
    "verify_nonprincipal_hook_seed_catalog",
    "verify_nonprincipal_ds_reduction_seed",
    # Non-principal DS normalization bridge
    "CentralChargeConvention", "RAW_BP_CONVENTION", "CHAPTER_BP_SUM_CONVENTION",
    "bp_dual_sum_under_convention", "shift_to_target_dual_sum",
    "bp_shift_to_target_sum", "bp_shifted_convention_for_target",
    "verify_nonprincipal_ds_normalization",
    # DS reduction seed scaffold
    "Sl2TripleSeed", "DSGhostWeight", "DSReductionSeed",
    "TruncatedBRSTComplex", "HookPairDSComplexSeed", "LinearConstraintBRSTBlock",
    "MixedConstraintGhostBRSTBlock", "SurvivorCoupledBRSTBlock", "InternalSurvivorCEBlock",
    "DSBasisElement", "DSConstraint", "DSBRSTBlueprint", "DSReducedFieldCandidate",
    "CurrentActionTermEntry", "SurvivorActionTermEntry",
    "QuadraticGhostTermEntry",
    "STATUS_DS_SEED", "brst_ghost_weights", "matrix_commutator",
    "ds_basis_expression_matrix", "exterior_basis_indices", "homogeneous_monomial_exponents",
    "linear_constraint_block_basis", "character_wedge_differential",
    "quadratic_ghost_differential", "ghost_brst_differential",
    "linear_constraint_koszul_differential", "build_character_wedge_complex",
    "build_ghost_brst_complex",
    "build_mixed_constraint_ghost_brst_block",
    "current_action_differential", "survivor_action_differential",
    "build_survivor_coupled_brst_block", "build_internal_survivor_ce_block",
    "relabel_quadratic_ghost_terms", "relabel_current_action_terms",
    "relabel_truncated_brst_complex",
    "relabel_mixed_constraint_ghost_block",
    "build_linear_constraint_koszul_block", "differential_square_blocks",
    "chain_homology_dimensions", "mixed_constraint_ghost_block_basis",
    "mixed_constraint_ghost_brst_differential",
    "mixed_constraint_ghost_block_homology_dimensions",
    "survivor_coupled_block_basis",
    "survivor_coupled_block_homology_dimensions",
    "internal_survivor_ce_block_basis",
    "internal_survivor_ce_block_homology_dimensions",
    "complex_has_nilpotent_differential",
    "mixed_constraint_ghost_block_has_square_zero",
    "mixed_constraint_ghost_block_is_acyclic",
    "survivor_coupled_block_has_square_zero",
    "survivor_coupled_block_is_acyclic",
    "internal_survivor_ce_block_has_square_zero",
    "internal_survivor_ce_block_is_acyclic",
    "linear_constraint_block_has_square_zero", "linear_constraint_contracting_homotopy",
    "specialize_complex_chi",
    "truncated_cohomology_dimensions", "complex_is_acyclic",
    "linear_constraint_block_has_contracting_homotopy",
    "linear_constraint_block_is_positive_acyclic",
    "sl3_subregular_sl2_triple",
    "sl3_subregular_basis_grades", "sl3_subregular_basis_matrices",
    "sl3_subregular_basis_profile", "sl3_subregular_ad_e_image_witnesses",
    "sl3_subregular_ad_e_image_basis",
    "sl3_subregular_project_expression_to_strong_candidates",
    "sl3_subregular_project_basis_label_to_strong_candidates",
    "sl3_subregular_projected_strong_brackets",
    "sl3_subregular_strong_generator_candidates",
    "sl3_subregular_positive_grades", "sl3_subregular_ghost_profile",
    "sl3_subregular_constraint_character", "sl3_subregular_constraints",
    "sl3_subregular_survivor_action_terms",
    "sl3_subregular_positive_nilpotent_brackets",
    "sl3_subregular_ds_seed", "sl3_subregular_linear_constraint_blocks",
    "sl3_subregular_mixed_constraint_ghost_blocks",
    "sl3_subregular_nonlinear_mixed_constraint_ghost_blocks",
    "sl3_subregular_internal_survivor_ce_blocks",
    "sl3_subregular_survivor_coupled_blocks",
    "sl3_subregular_truncated_brst_complex",
    "first_nonselfdual_hook_pair_basis_profiles",
    "first_nonselfdual_hook_pair_brst_blueprints",
    "hook_pair_ds_seed",
    "hook_pair_ghost_profiles",
    "hook_pair_constraint_characters",
    "hook_pair_constraints",
    "hook_pair_positive_nilpotent_brackets",
    "hook_pair_quadratic_ghost_term_support",
    "hook_pair_current_action_terms",
    "hook_pair_specialized_complexes", "hook_pair_ds_seed_catalog",
    "verify_hook_pair_ds_seed_catalog", "verify_hook_pair_seed_alignment",
    "hook_pair_linear_constraint_blocks",
    "hook_pair_mixed_constraint_ghost_blocks",
    "hook_pair_nonlinear_mixed_constraint_ghost_blocks",
    "hook_pair_mixed_blocks_match_under_dual_swap",
    "hook_pair_nonlinear_blocks_match_under_dual_swap",
    "verify_hook_pair_mixed_block_duality_catalog",
    "verify_hook_pair_nonlinear_block_duality_catalog",
    "hook_pair_surviving_field_candidates",
    "hook_pair_reduced_brackets",
    "first_nonselfdual_hook_pair_ds_seed",
    "first_nonselfdual_hook_pair_ghost_profiles",
    "first_nonselfdual_hook_pair_constraint_characters",
    "first_nonselfdual_hook_pair_constraints",
    "first_nonselfdual_hook_pair_current_action_terms",
    "first_nonselfdual_hook_pair_survivor_action_terms",
    "first_nonselfdual_hook_pair_positive_nilpotent_brackets",
    "first_nonselfdual_hook_pair_quadratic_ghost_term_support",
    "first_nonselfdual_hook_pair_ghost_label_map",
    "first_nonselfdual_hook_pair_ghost_side_map",
    "first_nonselfdual_hook_pair_ghost_complexes_match_under_relabeling",
    "first_nonselfdual_hook_pair_linear_constraint_blocks",
    "first_nonselfdual_hook_pair_mixed_constraint_ghost_blocks",
    "first_nonselfdual_hook_pair_mixed_blocks_match_under_relabeling",
    "first_nonselfdual_hook_pair_nonlinear_mixed_constraint_ghost_blocks",
    "first_nonselfdual_hook_pair_nonlinear_blocks_match_under_relabeling",
    "first_nonselfdual_hook_pair_internal_survivor_ce_blocks",
    "first_nonselfdual_hook_pair_survivor_coupled_blocks",
    "first_nonselfdual_hook_pair_surviving_field_candidates",
    "first_nonselfdual_hook_pair_reduced_brackets",
    "first_nonselfdual_hook_pair_specialized_complexes",
    "sl3_subregular_brst_blueprint",
    "verify_ds_reduction_seed",
    # Utility
    "partition_number", "lambda_fp", "F_g",
]
