r"""PBW spectral sequence engine: E_1, E_2, and collapse for standard families.

Computes the PBW spectral sequence for the bar complex B(A) of chirally
Koszul algebras.  The PBW filtration on B(A) yields a spectral sequence:

    E_1^{p,h} = Lambda^p(g_-^*)_h,    d_1 = CE differential

converging to E_infinity = H*(B(A)).  Koszulness (MC1) means the spectral
sequence collapses at E_2:

    E_2 = E_infinity = H*(B(A))

CRITICAL GRADING DISTINCTION (two gradings on bar cohomology):

  1. CE DEGREE p (= exterior degree in Lambda^p(g_-^*)):
     This is the grading of the CE complex.  H^p_CE(g_-) can be nonzero
     for ALL p.  For sl_2: dim H^n = 2n+1 at weight n(n+1)/2.
     For Virasoro: H^1 nonzero at h=2,3,4; H^2 nonzero at h=7..11;
     H^3 nonzero at h=15+.  The Koszul dual A^! = H*(B(A))^v has
     generators in degree 1, relations in degree 2, syzygies in degree 3.

  2. PBW DEGREE (= number of generator applications):
     The Koszul dual dimensions 1, 2, 5, 12, 30, 76, ... (for Virasoro)
     count total dimension at each PBW degree.  This is a COARSER grading
     than conformal weight.

  Koszulness does NOT mean H^p = 0 for p >= 2.  It means E_2 = E_infinity
  (no higher differentials), so the CE cohomology IS the bar cohomology.
  The Koszul DUAL A^! has a QUADRATIC presentation: it is generated by
  H^1(B(A)) with relations in H^2(B(A)), syzygies in H^3(B(A)), etc.
  All these groups can be nonzero.

MATHEMATICAL FRAMEWORK:

1. AFFINE KM (sl_2):
   Generators: {J^a_{-n} : a in {e,h,f}, n >= 1}
   d_1 = CE differential of g_- = sl_2 tensor t^{-1}C[t^{-1}]
   Bracket: [(a,m), (b,n)] = [a,b] tensor t^{-(m+n)}, NO central extension
   (m,n >= 1 implies m+n >= 2 > 0, so the central term k delta_{m+n,0} = 0).
   E_2 = H*_CE(g_-, C).  H^n concentrated at weight n(n+1)/2, dim = 2n+1.

2. VIRASORO:
   Generators: {L_{-n} : n >= 2}
   d_1 = CE differential of Vir_- = span{L_{-n} : n >= 2}
   Bracket: [L_{-m}, L_{-n}] = (n-m) L_{-(m+n)}, NO central extension
   (m,n >= 2 implies m+n >= 4 > 0, so the central term vanishes).
   E_2 = H*_CE(Vir_-, C).  H^1 at weights 2,3,4 (3 generators of A^!).
   H^2 at weights 7..11 (relations).  H^3 at weights 15+ (syzygies).
   Total Koszul dual dims by PBW degree: 1, 2, 5, 12, 30, 76, ...

3. W_3:
   Generators: {T_{-n} : n >= 2} union {W_{-m} : m >= 3}
   d_1 from LEADING-POLE OPE:
     T_{(1)}T = 2T  => [T_{-m}, T_{-n}] = (n-m)T_{-(m+n)}
     T_{(1)}W = 3W  => [T_{-m}, W_{-n}] = (n-2m)W_{-(m+n)}
     W_{(3)}W = 2T  => [W_{-m}, W_{-n}] has L_{-(m+n)} component
   NOTE (AP37): The W_3 self-OPE has pole order 6 (W_{(5)}W = c/3), so
   the spectral sequence has higher differentials d_r for r >= 2 that
   arise from sub-leading poles.  For W_N: max pole order 2N, so d_{2N-1}
   is the LAST potentially nonzero differential.  Koszulness means ALL
   higher differentials vanish anyway (E_2 = E_infinity).

4. COLLAPSE VERIFICATION:
   For Koszul algebras, E_2 = E_infinity.  Verification:
   (a) Euler characteristic chi(E_1)_h = chi(E_2)_h (holds for any SS)
   (b) E_2^{p,h} matches known H^p(B(A))_h from independent computation
   (c) d^2 = 0 at all bidegrees (Lie algebra axiom)

5. NON-KOSZUL EXAMPLE (minimal model):
   At c = 1/2 (Ising model), the simple quotient L_{1/2}(Vir) has null
   vectors that modify the bar complex.  The generator set changes (L_{-2}
   becomes a descendant), and the PBW SS may have nontrivial d_r for r >= 2.

GRADING CONVENTIONS (per signs_and_shifts.tex):
  - Cohomological grading, |d| = +1
  - CE degree p = exterior degree in Lambda^p(g_-^*)
  - d_r: E_r^{p,q} -> E_r^{p+r, q-r+1}
  - Conformal weight h is the second grading

DESUSPENSION (AP45): |s^{-1}v| = |v| - 1 (desuspension LOWERS degree).

References:
  thm:koszul-equivalences-meta (chiral_koszul_pairs.tex)
  prop:pbw-universality (chiral_koszul_pairs.tex)
  comp:sl2-ce-verification (bar_complex_tables.tex)
  comp:virasoro-dim-table (bar_complex_tables.tex)
  conj:w3-bar-gf (landscape_census.tex)
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
from itertools import combinations
from typing import Dict, List, Optional, Tuple

import numpy as np


# ============================================================================
# Exact rational arithmetic helpers
# ============================================================================

FR = Fraction


def _frac(x) -> Fraction:
    """Coerce to Fraction."""
    if isinstance(x, Fraction):
        return x
    if isinstance(x, (int, np.integer)):
        return Fraction(int(x))
    return Fraction(x)


def _frac_array(shape) -> np.ndarray:
    """Create a zero array of Fraction objects."""
    arr = np.empty(shape, dtype=object)
    arr.fill(Fraction(0))
    return arr


def _exact_rank(M: np.ndarray) -> int:
    """Compute rank of a Fraction-object matrix via Gaussian elimination."""
    if M.size == 0:
        return 0
    rows, cols = M.shape
    if rows == 0 or cols == 0:
        return 0
    A = np.array([[_frac(M[i, j]) for j in range(cols)]
                   for i in range(rows)], dtype=object)
    r = 0
    for c in range(cols):
        pivot = None
        for i in range(r, rows):
            if A[i, c] != Fraction(0):
                pivot = i
                break
        if pivot is None:
            continue
        A[[r, pivot]] = A[[pivot, r]]
        scale = A[r, c]
        for j in range(cols):
            A[r, j] = A[r, j] / scale
        for i in range(rows):
            if i == r:
                continue
            factor = A[i, c]
            if factor != Fraction(0):
                for j in range(cols):
                    A[i, j] = A[i, j] - factor * A[r, j]
        r += 1
    return r


def _exact_kernel_dim(M: np.ndarray) -> int:
    """Dimension of kernel of M."""
    if M.size == 0:
        rows, cols = M.shape
        return cols
    return M.shape[1] - _exact_rank(M)


# ============================================================================
# Partition helpers
# ============================================================================

@lru_cache(maxsize=1024)
def _partitions_distinct(n: int, min_part: int, max_part: int) -> Tuple[Tuple[int, ...], ...]:
    """Partitions of n into distinct parts in [min_part, max_part]."""
    if n == 0:
        return ((),)
    if n < min_part or min_part > max_part:
        return ()
    results = []
    for part in range(min(n, max_part), min_part - 1, -1):
        for rest in _partitions_distinct(n - part, min_part, part - 1):
            results.append((part,) + rest)
    return tuple(results)


# ============================================================================
# Abstract Lie algebra for the negative-mode algebra
# ============================================================================

class NegativeModeAlgebra:
    """Abstract negative-mode Lie algebra for the PBW spectral sequence.

    Generators indexed 0, 1, ..., n_gens - 1, each with a conformal weight.
    Bracket table: dict mapping (i, j) -> {k: coeff} for i < j.
    """

    def __init__(self, gen_weights: List[int],
                 bracket_table: Dict[Tuple[int, int], Dict[int, Fraction]],
                 gen_names: Optional[List[str]] = None):
        self.n_gens = len(gen_weights)
        self.gen_weights = gen_weights
        self.bracket_table = bracket_table
        self.gen_names = gen_names or [f"g_{i}" for i in range(self.n_gens)]

        # Cache
        self._basis_cache: Dict[Tuple[int, int], List[Tuple[int, ...]]] = {}
        self._diff_cache: Dict[Tuple[int, int], np.ndarray] = {}

    def weight_basis(self, degree: int, weight: int) -> List[Tuple[int, ...]]:
        """Basis of Lambda^degree at conformal weight h.

        Returns sorted list of degree-element subsets of generator indices
        whose weights sum to the given weight.
        """
        key = (degree, weight)
        if key in self._basis_cache:
            return self._basis_cache[key]
        result = list(self._enum_subsets(degree, weight, 0))
        self._basis_cache[key] = result
        return result

    def _enum_subsets(self, degree: int, weight: int, start: int):
        """Generate degree-subsets with exact total weight."""
        if degree == 0:
            if weight == 0:
                yield ()
            return
        if degree < 0 or weight <= 0:
            return
        for i in range(start, self.n_gens - degree + 1):
            w = self.gen_weights[i]
            if w > weight:
                continue
            remaining = weight - w
            # At least (degree-1) more generators needed, each with weight >= 1
            if remaining < degree - 1:
                continue
            for rest in self._enum_subsets(degree - 1, remaining, i + 1):
                yield (i,) + rest

    def chain_dim(self, degree: int, weight: int) -> int:
        """Dimension of Lambda^degree at conformal weight h."""
        return len(self.weight_basis(degree, weight))

    def ce_differential(self, degree: int, weight: int) -> np.ndarray:
        """CE differential d: Lambda^degree_weight -> Lambda^{degree+1}_weight.

        The CE differential on Lambda^p(g^*) is dual to the Lie bracket:
        (d omega)(v_0,...,v_p) = sum_{i<j} (-1)^{i+j} omega([v_i,v_j],...)

        Returns matrix with Fraction entries.
        """
        key = (degree, weight)
        if key in self._diff_cache:
            return self._diff_cache[key]

        source = self.weight_basis(degree, weight)
        target = self.weight_basis(degree + 1, weight)
        n_src, n_tgt = len(source), len(target)

        if n_src == 0 or n_tgt == 0:
            mat = _frac_array((max(n_tgt, 0), max(n_src, 0)))
            self._diff_cache[key] = mat
            return mat

        target_idx = {t: i for i, t in enumerate(target)}
        mat = _frac_array((n_tgt, n_src))

        for col, alpha in enumerate(source):
            alpha_set = set(alpha)
            alpha_list = list(alpha)

            for (beta, gamma), br in self.bracket_table.items():
                for c_idx, coeff in br.items():
                    if c_idx not in alpha_set:
                        continue
                    new_set = (alpha_set - {c_idx}) | {beta, gamma}
                    if len(new_set) != degree + 1:
                        continue
                    new_tuple = tuple(sorted(new_set))
                    row = target_idx.get(new_tuple)
                    if row is None:
                        continue
                    # Sign computation
                    pos_c = alpha_list.index(c_idx)
                    sorted_new = list(new_tuple)
                    pos_beta = sorted_new.index(beta)
                    remaining_after_beta = sorted(new_set - {beta})
                    pos_gamma = remaining_after_beta.index(gamma)
                    sign = Fraction((-1) ** (pos_c + pos_beta + pos_gamma))
                    mat[row, col] += sign * _frac(coeff)

        self._diff_cache[key] = mat
        return mat

    def differential_rank(self, degree: int, weight: int) -> int:
        """Rank of d: Lambda^degree -> Lambda^{degree+1} at given weight."""
        mat = self.ce_differential(degree, weight)
        if mat.size == 0:
            return 0
        return _exact_rank(mat)

    def cohomology_dim(self, degree: int, weight: int) -> int:
        """dim H^degree_weight = dim ker(d^degree) - dim im(d^{degree-1})."""
        dim_p = self.chain_dim(degree, weight)
        if dim_p == 0:
            return 0

        # ker(d^degree)
        d_curr = self.ce_differential(degree, weight)
        rank_curr = _exact_rank(d_curr) if d_curr.size > 0 else 0
        ker_dim = dim_p - rank_curr

        # im(d^{degree-1})
        if degree > 0:
            d_prev = self.ce_differential(degree - 1, weight)
            im_dim = _exact_rank(d_prev) if d_prev.size > 0 else 0
        else:
            im_dim = 0

        return ker_dim - im_dim

    def verify_d_squared(self, degree: int, weight: int) -> bool:
        """Verify d^2 = 0 at (degree, weight)."""
        d0 = self.ce_differential(degree, weight)
        d1 = self.ce_differential(degree + 1, weight)

        if d0.size == 0 or d1.size == 0:
            return True

        # Check d1 . d0 = 0
        rows1, cols1 = d1.shape
        rows0, cols0 = d0.shape
        if cols1 != rows0:
            # Dimension mismatch means one of them is zero
            return True

        prod = _frac_array((rows1, cols0))
        for i in range(rows1):
            for j in range(cols0):
                s = Fraction(0)
                for k in range(cols1):
                    s += d1[i, k] * d0[k, j]
                prod[i, j] = s

        return all(prod[i, j] == Fraction(0)
                   for i in range(rows1) for j in range(cols0))


# ============================================================================
# E_1 and E_2 page data structure
# ============================================================================

class SpectralSequencePage:
    """Data for a page E_r of the PBW spectral sequence.

    E_r^{p,q} is stored as a dict (p, q) -> dim, along with
    the family name and metadata.
    """

    def __init__(self, page_number: int, family: str):
        self.page = page_number
        self.family = family
        self.dims: Dict[Tuple[int, int], int] = {}

    def set_dim(self, p: int, q: int, dim: int):
        if dim > 0:
            self.dims[(p, q)] = dim

    def get_dim(self, p: int, q: int) -> int:
        return self.dims.get((p, q), 0)

    def total_dim_at_degree(self, n: int) -> int:
        """Total dimension at total degree n = p + q."""
        return sum(d for (p, q), d in self.dims.items() if p + q == n)

    def total_dim_at_bar_degree(self, p: int) -> int:
        """Total dimension at bar degree p (summing over all q)."""
        return sum(d for (pp, q), d in self.dims.items() if pp == p)

    def total_dim_at_weight(self, w: int) -> int:
        """Total dimension at conformal weight w (stored in q)."""
        return sum(d for (p, q), d in self.dims.items() if q == w)

    def nonzero_entries(self) -> Dict[Tuple[int, int], int]:
        return {k: v for k, v in self.dims.items() if v > 0}

    def euler_char_at_weight(self, w: int) -> int:
        """Euler characteristic at weight w: sum (-1)^p dim E^{p,w}."""
        chi = 0
        for (p, q), d in self.dims.items():
            if q == w:
                chi += ((-1) ** p) * d
        return chi


# ============================================================================
# 1. sl_2 PBW spectral sequence
# ============================================================================

DIM_SL2 = 3

# Basis: e=0, h=1, f=2
# Full bracket table with BOTH orderings (needed for loop algebra construction)
SL2_BRACKET = {
    (0, 1): {0: Fraction(-2)},   # [e, h] = -2e
    (0, 2): {1: Fraction(1)},    # [e, f] = h
    (1, 0): {0: Fraction(2)},    # [h, e] = 2e
    (1, 2): {2: Fraction(-2)},   # [h, f] = -2f
    (2, 0): {1: Fraction(-1)},   # [f, e] = -h
    (2, 1): {2: Fraction(2)},    # [f, h] = 2f
}


def build_sl2_negative_mode_algebra(max_weight: int = 8) -> NegativeModeAlgebra:
    """Build the negative-mode Lie algebra g_- = sl_2 tensor t^{-1}C[t^{-1}].

    Generators: (a, n) for a in {e,h,f}, n = 1,...,max_weight.
    Flat index: a + 3*(n-1).
    Weight of (a,n) = n.
    Bracket: [(a,m), (b,n)] = [a,b] tensor t^{-(m+n)}, NO central extension.
    """
    gen_weights = []
    gen_names = []
    name_map = {0: 'e', 1: 'h', 2: 'f'}
    for n in range(1, max_weight + 1):
        for a in range(DIM_SL2):
            gen_weights.append(n)
            gen_names.append(f"{name_map[a]}_{n}")

    n_gens = len(gen_weights)
    bracket_table: Dict[Tuple[int, int], Dict[int, Fraction]] = {}

    for n1 in range(1, max_weight + 1):
        for a in range(DIM_SL2):
            i = a + DIM_SL2 * (n1 - 1)
            for n2 in range(n1, max_weight + 1):
                for b in range(DIM_SL2):
                    j = b + DIM_SL2 * (n2 - 1)
                    if i >= j:
                        continue
                    m_sum = n1 + n2
                    if m_sum > max_weight:
                        continue
                    br = SL2_BRACKET.get((a, b))
                    if br:
                        result = {}
                        for c_lie, coeff in br.items():
                            flat_c = c_lie + DIM_SL2 * (m_sum - 1)
                            if flat_c < n_gens:
                                result[flat_c] = _frac(coeff)
                        if result:
                            bracket_table[(i, j)] = result

    return NegativeModeAlgebra(gen_weights, bracket_table, gen_names)


def compute_sl2_e1_page(max_weight: int = 8,
                         max_degree: int = 6) -> SpectralSequencePage:
    """Compute E_1 page for sl_2 affine: dimensions of Lambda^p(g_-^*)_h.

    E_1^{p,h} = dim Lambda^p(g_-^*)_h.
    """
    alg = build_sl2_negative_mode_algebra(max_weight)
    page = SpectralSequencePage(1, "sl_2")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.chain_dim(p, h)
            page.set_dim(p, h, dim)

    return page


def compute_sl2_e2_page(max_weight: int = 8,
                         max_degree: int = 6) -> SpectralSequencePage:
    """Compute E_2 page for sl_2 affine: H^p_CE(g_-, C) at each weight.

    E_2^{p,h} = dim H^p(CE(g_-))_h.
    By Koszulness, E_2 = E_infinity.
    """
    alg = build_sl2_negative_mode_algebra(max_weight)
    page = SpectralSequencePage(2, "sl_2")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.cohomology_dim(p, h)
            page.set_dim(p, h, dim)

    return page


def verify_sl2_collapse(max_weight: int = 8,
                         max_degree: int = 5) -> Dict[str, object]:
    """Verify E_2 = E_infinity for sl_2 by comparing with known bar cohomology.

    Known: H^n(B(V_k(sl_2))) is concentrated at weight n(n+1)/2 with dim 2n+1.
    """
    e2 = compute_sl2_e2_page(max_weight, max_degree)

    results = {"collapsed": True, "mismatches": []}

    for n in range(1, max_degree + 1):
        expected_weight = n * (n + 1) // 2
        expected_dim = 2 * n + 1

        # Check that E_2 at bar degree n is concentrated at the expected weight
        for h in range(0, max_weight + 1):
            dim = e2.get_dim(n, h)
            if h == expected_weight:
                if dim != expected_dim:
                    results["collapsed"] = False
                    results["mismatches"].append(
                        f"E_2^{{{n},{h}}} = {dim}, expected {expected_dim}")
            else:
                if dim != 0:
                    results["collapsed"] = False
                    results["mismatches"].append(
                        f"E_2^{{{n},{h}}} = {dim}, expected 0")

    return results


# ============================================================================
# 2. Virasoro PBW spectral sequence
# ============================================================================

def build_virasoro_negative_mode_algebra(max_weight: int = 16) -> NegativeModeAlgebra:
    """Build Vir_- = span{L_{-n} : n >= 2}.

    Generator indexed i corresponds to L_{-(i+2)}, weight = i+2.
    Bracket: [L_{-(a+2)}, L_{-(b+2)}] = (b-a) L_{-(a+b+4)},
    i.e. output index = a+b+2, coefficient = b-a.
    NO central extension (m+n >= 4 for m,n >= 2).
    """
    n_gens = max_weight - 1  # indices 0, ..., max_weight-2
    gen_weights = list(range(2, max_weight + 1))
    gen_names = [f"L_{-(i+2)}" for i in range(n_gens)]

    bracket_table: Dict[Tuple[int, int], Dict[int, Fraction]] = {}
    for a in range(n_gens):
        for b in range(a + 1, n_gens):
            c_idx = a + b + 2  # output generator index
            coeff = b - a      # (b+2) - (a+2) = b - a ... NO
            # [L_{-(a+2)}, L_{-(b+2)}] = ((b+2) - (a+2)) L_{-(a+2+b+2)}
            #                           = (b - a) L_{-(a+b+4)}
            # Output generator index for L_{-(a+b+4)} is (a+b+4) - 2 = a+b+2
            if c_idx < n_gens and coeff != 0:
                bracket_table[(a, b)] = {c_idx: Fraction(coeff)}

    return NegativeModeAlgebra(gen_weights, bracket_table, gen_names)


def compute_virasoro_e1_page(max_weight: int = 16,
                              max_degree: int = 4) -> SpectralSequencePage:
    """Compute E_1 page for Virasoro: dim Lambda^p(Vir_-^*)_h.

    E_1^{p,h} = number of p-element subsets of {L_{-n} : n >= 2}
    with total weight h.  Equivalently: partitions of h into p
    distinct parts, each >= 2.
    """
    alg = build_virasoro_negative_mode_algebra(max_weight)
    page = SpectralSequencePage(1, "Virasoro")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.chain_dim(p, h)
            page.set_dim(p, h, dim)

    return page


def compute_virasoro_e2_page(max_weight: int = 16,
                              max_degree: int = 4) -> SpectralSequencePage:
    """Compute E_2 page for Virasoro: H^p_CE(Vir_-)_h.

    By Koszulness, E_2 = E_infinity = H*(B(Vir_c)).
    Bar cohomology is concentrated in bar degree 1 (Koszul dual generators).
    """
    alg = build_virasoro_negative_mode_algebra(max_weight)
    page = SpectralSequencePage(2, "Virasoro")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.cohomology_dim(p, h)
            page.set_dim(p, h, dim)

    return page


# Known Virasoro bar cohomology (Koszul dual) dimensions by PBW degree
VIRASORO_BAR_COH_PBW = {
    1: 1, 2: 2, 3: 5, 4: 12, 5: 30,
    6: 76, 7: 196, 8: 512, 9: 1353, 10: 3610,
}


@lru_cache(maxsize=512)
def motzkin(n: int) -> int:
    """Motzkin number M(n). M(0)=1, M(1)=1, M(2)=2, M(3)=4, M(4)=9, ..."""
    if n < 0:
        return 0
    if n <= 1:
        return 1
    return ((2 * n + 1) * motzkin(n - 1) + 3 * (n - 1) * motzkin(n - 2)) // (n + 2)


def virasoro_koszul_dual_dim(n: int) -> int:
    """dim(Vir^!)_n in PBW degree = sum_{j=0}^{n-1} M(j)*M(n-1-j)."""
    if n < 1:
        return 0
    return sum(motzkin(j) * motzkin(n - 1 - j) for j in range(n))


def verify_virasoro_collapse(max_weight: int = 12,
                              max_degree: int = 3) -> Dict[str, object]:
    """Verify E_2 = E_infinity for Virasoro.

    Collapse at E_2 means the CE cohomology IS the bar cohomology.
    H^p_CE(Vir_-) can be nonzero for p >= 2 (relations, syzygies of A^!).

    Verification paths:
    1. chi(E_1)_h = chi(E_2)_h (Euler char preserved by differential)
    2. d^2 = 0 at all bidegrees
    3. H^1 generators match: H^1 at weights 2, 3, 4 only
    4. H^2 (relations) at weights 7-11: the Koszul dual has quadratic rels
    """
    alg = build_virasoro_negative_mode_algebra(max_weight)
    e1 = compute_virasoro_e1_page(max_weight, max_degree)
    e2 = compute_virasoro_e2_page(max_weight, max_degree)

    results = {
        "e2_computed": True,
        "euler_char_preserved": True,
        "d_squared_zero": True,
        "h_dims": {},
    }

    # Collect all CE cohomology dimensions
    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = e2.get_dim(p, h)
            if dim > 0:
                results["h_dims"][(p, h)] = dim

    # Verify Euler characteristic preservation
    for h in range(0, max_weight + 1):
        chi1 = e1.euler_char_at_weight(h)
        chi2 = e2.euler_char_at_weight(h)
        if chi1 != chi2:
            results["euler_char_preserved"] = False

    # Verify d^2 = 0
    for p in range(0, max_degree):
        for h in range(0, max_weight + 1):
            if not alg.verify_d_squared(p, h):
                results["d_squared_zero"] = False

    return results


# ============================================================================
# 3. W_3 PBW spectral sequence
# ============================================================================

def build_w3_generator_data(max_weight: int = 14) -> Dict[str, object]:
    """Data for the W_3 bar complex generators and OPE structure.

    Generators: T_{-n} (n >= 2, weight n) and W_{-m} (m >= 3, weight m).

    IMPORTANT (AP37): The W_3 negative modes do NOT form a Lie algebra.
    The full [W_m, W_n] commutator involves the COMPOSITE field Lambda
    (= :TT: - 3/10 d^2T), which is NOT a generator.  The Jacobi identity
    holds only in the full W-algebra, not in the leading-pole truncation.

    Therefore, we CANNOT build a NegativeModeAlgebra for W_3 and compute
    CE cohomology as d_1 of the PBW spectral sequence.  Instead:

    1. The E_1 page dimensions (chain groups) can be computed: they are
       exterior powers of the generator space {T_{-n}, W_{-m}}.
    2. The E_2 page CANNOT be computed by CE cohomology alone; it requires
       the full W-algebra structure including composites.
    3. Koszulness means E_2 = E_infinity, and the E_2 = known bar cohomology
       (from the recurrence a_n = 4a_{n-1} - 2a_{n-2} - a_{n-3}).

    Returns dict with generator data for E_1 chain group computation.
    """
    gen_weights = []
    gen_names = []
    gen_type = []

    for n in range(2, max_weight + 1):
        gen_weights.append(n)
        gen_names.append(f"T_{-n}")
        gen_type.append('T')

    for m in range(3, max_weight + 1):
        gen_weights.append(m)
        gen_names.append(f"W_{-m}")
        gen_type.append('W')

    return {
        "gen_weights": gen_weights,
        "gen_names": gen_names,
        "gen_type": gen_type,
        "n_gens": len(gen_weights),
        "n_T": max_weight - 1,   # T generators
        "n_W": max_weight - 2,   # W generators
    }


def w3_chain_dim(degree: int, weight: int, max_weight: int = 20) -> int:
    """Dimension of Lambda^degree at conformal weight h for W_3 generators.

    Counts degree-element subsets of {T_{-n}: n>=2} union {W_{-m}: m>=3}
    with total weight = h.
    """
    data = build_w3_generator_data(max_weight)
    weights = data["gen_weights"]
    n_gens = data["n_gens"]

    # Count subsets of size `degree` from generators with weights summing to `weight`
    count = 0

    def _count(remaining_deg, remaining_wt, start):
        nonlocal count
        if remaining_deg == 0:
            if remaining_wt == 0:
                count += 1
            return
        for i in range(start, n_gens):
            w = weights[i]
            if w > remaining_wt:
                continue
            if n_gens - i - 1 < remaining_deg - 1:
                break
            _count(remaining_deg - 1, remaining_wt - w, i + 1)

    _count(degree, weight, 0)
    return count


def compute_w3_e1_page(max_weight: int = 12,
                        max_degree: int = 3) -> SpectralSequencePage:
    """Compute E_1 page for W_3: chain group dimensions.

    E_1^{p,h} = dim Lambda^p(generators)_h where generators are
    {T_{-n} : n >= 2} union {W_{-m} : m >= 3}.

    NOTE: The E_1 differential for W_3 is NOT simply the CE differential
    of a Lie algebra (AP37).  The W_3 modes include composites (Lambda),
    so the d_1 involves the full OPE structure.  We can still compute
    the chain group dimensions.
    """
    page = SpectralSequencePage(1, "W_3")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = w3_chain_dim(p, h, max_weight)
            page.set_dim(p, h, dim)

    return page


def compute_w3_e2_from_known(max_bar_degree: int = 8) -> SpectralSequencePage:
    """E_2 = E_infinity for W_3 from known bar cohomology.

    Since W_3 is Koszul (cor:universal-koszul), E_2 = E_infinity.
    The bar cohomology dimensions are known from the recurrence:
      a_n = 4*a_{n-1} - 2*a_{n-2} - a_{n-3} (n >= 4)
    with a_1 = 2, a_2 = 5, a_3 = 16.

    NOTE: These are TOTAL dimensions by bar degree, not decomposed
    by conformal weight.  The conformal-weight decomposition requires
    the full W_3 bar complex computation.
    """
    page = SpectralSequencePage(2, "W_3")

    for n in range(1, max_bar_degree + 1):
        dim = w3_bar_dim_recurrence(n)
        # Store with h = n as a placeholder (actual weight decomposition is complex)
        page.set_dim(n, n, dim)

    return page


# W_3 bar cohomology dimensions (from landscape_census.tex)
W3_BAR_COH = {1: 2, 2: 5, 3: 16, 4: 52, 5: 171, 6: 564, 7: 1862, 8: 6149}


def w3_bar_dim_recurrence(n: int) -> int:
    """a_n = 4*a_{n-1} - 2*a_{n-2} - a_{n-3} for n >= 4."""
    if n <= 0:
        return 0
    if n == 1:
        return 2
    if n == 2:
        return 5
    if n == 3:
        return 16
    return 4 * w3_bar_dim_recurrence(n - 1) - 2 * w3_bar_dim_recurrence(n - 2) - w3_bar_dim_recurrence(n - 3)


# ============================================================================
# 4. PBW filtration: explicit description
# ============================================================================

class PBWFiltration:
    """Explicit PBW filtration F^0 superset F^1 superset ... on the bar complex.

    The PBW filtration on B^n(A) = A_bar^{tensor n} is:
      F^p B^n = span{ [v_1|...|v_n] : sum of PBW grades >= p }

    For the bar complex of a vertex algebra A with generators {a_i} of
    conformal weights {h_i}, the PBW grade of a_i applied n times with
    modes m_1,...,m_n is sum(m_j) (total mode number).

    The associated graded gr^p_F B^n has d_1 = d_{leading pole} (the
    bracket term), and d_r for r >= 2 from sub-leading OPE poles.

    For QUADRATIC algebras (affine KM): max pole order = 2, so d_2 is
    the last differential.  But d_2 = 0 by Koszulness, giving E_2 = E_infty.

    For W_N: max pole order = 2N (from W_{(2N-1)}W), so d_r could be
    nonzero up to r = 2N-1.  Koszulness forces all d_r = 0 for r >= 2.
    """

    def __init__(self, family: str, max_pole_order: int):
        self.family = family
        self.max_pole_order = max_pole_order
        # The SS has d_r: E_r^{p,q} -> E_r^{p+r,q-r+1}
        # d_r can be nonzero only for r <= max_pole_order - 1
        self.max_differential_page = max_pole_order - 1

    def filtration_level(self, mode_numbers: List[int]) -> int:
        """PBW filtration level = sum of mode numbers."""
        return sum(mode_numbers)

    def last_possible_differential(self) -> int:
        """Last page r where d_r could be nonzero."""
        return self.max_differential_page

    def collapse_page_koszul(self) -> int:
        """For a Koszul algebra, the SS collapses at E_2."""
        return 2

    def collapse_page_generic(self) -> int:
        """For a generic (possibly non-Koszul) algebra, latest collapse page."""
        return self.max_differential_page + 1


def pbw_filtration_sl2() -> PBWFiltration:
    """PBW filtration for sl_2-hat.  Max pole order = 2 (quadratic OPE)."""
    return PBWFiltration("sl_2", max_pole_order=2)


def pbw_filtration_virasoro() -> PBWFiltration:
    """PBW filtration for Virasoro.  Max pole order = 4 (T_{(3)}T = c/2)."""
    return PBWFiltration("Virasoro", max_pole_order=4)


def pbw_filtration_w3() -> PBWFiltration:
    """PBW filtration for W_3.  Max pole order = 6 (W_{(5)}W = c/3)."""
    return PBWFiltration("W_3", max_pole_order=6)


def pbw_filtration_wN(N: int) -> PBWFiltration:
    """PBW filtration for W_N.  Max pole order = 2N (W_{(2N-1)}W)."""
    return PBWFiltration(f"W_{N}", max_pole_order=2 * N)


# ============================================================================
# 5. Collapse page for W_N (AP37)
# ============================================================================

def wN_collapse_page_upper_bound(N: int) -> int:
    """Upper bound on collapse page for W_N spectral sequence.

    The W_N self-OPE W_{(2N-1)}W has pole order 2N.
    This drives d_{2N-1} differentials from scalar contact terms.
    For N >= 3, the last potentially nonzero differential is at page 2N-1.
    But Koszulness forces collapse at E_2.

    For generic (non-Koszul) W_N quotients: collapse at E_{2N}.

    Returns: 2N (the page AFTER the last possible differential).
    """
    return 2 * N


def wN_collapse_page_koszul() -> int:
    """For Koszul W_N (universal algebra), collapse at E_2."""
    return 2


# ============================================================================
# 6. E_2 vs E_infinity comparison
# ============================================================================

def compare_e2_with_bar_cohomology(
    e2_page: SpectralSequencePage,
    known_bar_coh: Dict[int, int],
    max_degree: int = 6,
) -> Dict[str, object]:
    """Compare E_2 page total dimensions with known bar cohomology.

    If E_2 = E_infinity (Koszulness), then:
      sum_h E_2^{p,h} = dim H^p(B(A))
    and the total H^p dimensions should match known values.

    known_bar_coh: dict mapping bar degree p -> dim H^p.
    """
    results = {"match": True, "details": {}}

    for p in range(1, max_degree + 1):
        e2_total = sum(
            e2_page.get_dim(p, h)
            for h in range(0, 100)  # generous upper bound
        )
        known = known_bar_coh.get(p, 0)

        match = (known == 0 and e2_total >= 0) if known == 0 else (e2_total == known)
        results["details"][p] = {
            "e2_total": e2_total,
            "known": known,
            "match": match,
        }
        if not match and known > 0:
            results["match"] = False

    return results


# ============================================================================
# 7. d^2 = 0 verification
# ============================================================================

def verify_d_squared_zero(algebra: NegativeModeAlgebra,
                          max_weight: int = 10,
                          max_degree: int = 4) -> Dict[Tuple[int, int], bool]:
    """Verify d^2 = 0 at all (degree, weight) pairs.

    Returns dict mapping (degree, weight) -> True/False.
    """
    results = {}
    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            results[(p, h)] = algebra.verify_d_squared(p, h)
    return results


# ============================================================================
# 8. Non-Koszul example: minimal model quotient
# ============================================================================

def minimal_model_e1_dims(max_weight: int = 10, max_degree: int = 3) -> SpectralSequencePage:
    """E_1 page for the Virasoro UNIVERSAL algebra (same as Virasoro E_1).

    For the minimal model at c = 1/2 (Ising), the SIMPLE QUOTIENT L_{1/2}(Vir)
    has additional null vectors that modify the bar complex.  The universal
    algebra V_c(Vir) is always Koszul; the simple quotient may not be.

    The null vector at weight 2 in the c=1/2 Verma module is:
      (L_{-1}^2 - (4/3) L_{-2}) |h_{1,2}> = 0 at h = 1/2.

    For the VACUUM module (h=0) at c=1/2: the null vector is at weight 2:
      (L_{-2} + (2/3) L_{-1}^2) |0> = 0  (Kac det vanishes at level 2).

    This means L_{-2}|0> is NOT independent in L_{1/2}(Vir), which
    removes one generator from the bar complex.  The remaining generators
    are {L_{-n} : n >= 3}, and the E_1 page changes.

    We compute E_1 for the QUOTIENT by removing the weight-2 generator.
    """
    # Quotient Vir_- by the relation identifying L_{-2} with descendants.
    # Generators: {L_{-n} : n >= 3} only.
    n_gens = max_weight - 2  # n from 3 to max_weight
    if n_gens <= 0:
        return SpectralSequencePage(1, "MinModel_c=1/2")

    gen_weights = list(range(3, max_weight + 1))
    gen_names = [f"L_{-(i+3)}" for i in range(n_gens)]

    # Bracket: same as Virasoro but restricted to n >= 3
    bracket_table: Dict[Tuple[int, int], Dict[int, Fraction]] = {}
    for a in range(n_gens):
        for b in range(a + 1, n_gens):
            wa = a + 3  # weight of generator a
            wb = b + 3  # weight of generator b
            w_out = wa + wb
            # Output generator index: w_out - 3
            c_idx = w_out - 3
            coeff = wb - wa  # = (b+3) - (a+3) = b - a
            if c_idx >= 0 and c_idx < n_gens and coeff != 0:
                bracket_table[(a, b)] = {c_idx: Fraction(coeff)}

    alg = NegativeModeAlgebra(gen_weights, bracket_table, gen_names)
    page = SpectralSequencePage(1, "MinModel_c=1/2")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.chain_dim(p, h)
            page.set_dim(p, h, dim)

    return page


def minimal_model_e2_dims(max_weight: int = 10, max_degree: int = 3) -> SpectralSequencePage:
    """E_2 page for the minimal model quotient.

    Uses the reduced generator set {L_{-n} : n >= 3}.
    If the SS does NOT collapse at E_2, there will be discrepancies
    with the true bar cohomology.
    """
    n_gens = max_weight - 2
    if n_gens <= 0:
        return SpectralSequencePage(2, "MinModel_c=1/2")

    gen_weights = list(range(3, max_weight + 1))
    gen_names = [f"L_{-(i+3)}" for i in range(n_gens)]

    bracket_table: Dict[Tuple[int, int], Dict[int, Fraction]] = {}
    for a in range(n_gens):
        for b in range(a + 1, n_gens):
            wa = a + 3
            wb = b + 3
            w_out = wa + wb
            c_idx = w_out - 3
            coeff = wb - wa
            if c_idx >= 0 and c_idx < n_gens and coeff != 0:
                bracket_table[(a, b)] = {c_idx: Fraction(coeff)}

    alg = NegativeModeAlgebra(gen_weights, bracket_table, gen_names)
    page = SpectralSequencePage(2, "MinModel_c=1/2")

    for p in range(0, max_degree + 1):
        for h in range(0, max_weight + 1):
            dim = alg.cohomology_dim(p, h)
            page.set_dim(p, h, dim)

    return page


# ============================================================================
# 9. Euler characteristic cross-checks
# ============================================================================

def euler_char_e1(page: SpectralSequencePage, weight: int) -> int:
    """Euler characteristic of the E_1 page at given weight.

    chi(E_1)_h = sum_p (-1)^p dim E_1^{p,h}.
    This equals the Euler characteristic of the full bar complex at weight h,
    which is preserved by all differentials.
    """
    return page.euler_char_at_weight(weight)


def euler_char_e2(page: SpectralSequencePage, weight: int) -> int:
    """Euler characteristic of the E_2 page at given weight.

    Must equal chi(E_1)_h = chi(E_infinity)_h.
    """
    return page.euler_char_at_weight(weight)


def verify_euler_char_preservation(
    e1: SpectralSequencePage,
    e2: SpectralSequencePage,
    max_weight: int = 10,
) -> Dict[int, bool]:
    """Verify chi(E_1)_h = chi(E_2)_h for all weights.

    The Euler characteristic is invariant under the differential.
    """
    results = {}
    for h in range(0, max_weight + 1):
        chi1 = euler_char_e1(e1, h)
        chi2 = euler_char_e2(e2, h)
        results[h] = (chi1 == chi2)
    return results


# ============================================================================
# 10. Concentration criterion
# ============================================================================

def is_concentrated_in_degree(page: SpectralSequencePage,
                               target_degree: int,
                               max_weight: int = 20) -> bool:
    """Check if all nonzero entries (excluding p=0) are at a single CE degree.

    NOTE: For Koszul algebras, E_2 is generally NOT concentrated in
    CE degree 1.  The Koszul dual A^! = bigoplus H^p(B(A))^v has
    generators (p=1), relations (p=2), syzygies (p=3), etc.  All can
    be nonzero.  This function is useful for detecting special structure,
    e.g. sl_2 at weight n(n+1)/2 has only H^n nonzero.
    """
    for (p, h), d in page.dims.items():
        if p != target_degree and p != 0 and d > 0:
            return False
    return True


# ============================================================================
# 11. Summary tables
# ============================================================================

def print_spectral_sequence_table(page: SpectralSequencePage,
                                   max_degree: int = 5,
                                   max_weight: int = 12):
    """Print a formatted table of the spectral sequence page."""
    header = f"E_{page.page} page for {page.family}"
    print(header)
    print("=" * len(header))
    print(f"{'p\\h':>6}", end="")
    for h in range(0, max_weight + 1):
        print(f"{h:>5}", end="")
    print()
    print("-" * (6 + 5 * (max_weight + 1)))

    for p in range(0, max_degree + 1):
        print(f"{p:>6}", end="")
        for h in range(0, max_weight + 1):
            d = page.get_dim(p, h)
            print(f"{d:>5}", end="")
        print()


def summary_table(family: str, max_weight: int = 10) -> Dict[str, object]:
    """Compute full summary for a family: E_1, E_2, collapse check."""
    if family == "sl_2":
        e1 = compute_sl2_e1_page(max_weight)
        e2 = compute_sl2_e2_page(max_weight)
        filt = pbw_filtration_sl2()
        euler_check = verify_euler_char_preservation(e1, e2, max_weight)
        return {
            "family": family,
            "e1": e1,
            "e2": e2,
            "filtration": filt,
            "euler_char_preserved": all(euler_check.values()),
            "euler_check_details": euler_check,
            "collapse_page_koszul": filt.collapse_page_koszul(),
            "collapse_page_generic": filt.collapse_page_generic(),
        }
    elif family == "Virasoro":
        e1 = compute_virasoro_e1_page(max_weight)
        e2 = compute_virasoro_e2_page(max_weight)
        filt = pbw_filtration_virasoro()
        euler_check = verify_euler_char_preservation(e1, e2, max_weight)
        return {
            "family": family,
            "e1": e1,
            "e2": e2,
            "filtration": filt,
            "euler_char_preserved": all(euler_check.values()),
            "euler_check_details": euler_check,
            "collapse_page_koszul": filt.collapse_page_koszul(),
            "collapse_page_generic": filt.collapse_page_generic(),
        }
    elif family == "W_3":
        e1 = compute_w3_e1_page(max_weight)
        filt = pbw_filtration_w3()
        return {
            "family": family,
            "e1": e1,
            "e2_note": "W_3 E_2 requires full W-algebra structure (AP37)",
            "filtration": filt,
            "collapse_page_koszul": filt.collapse_page_koszul(),
            "collapse_page_generic": filt.collapse_page_generic(),
        }
    else:
        raise ValueError(f"Unknown family: {family}")
