r"""Categorical zeta functions from the Drinfeld-Kohno category.

Mathematical foundation
-----------------------
The Drinfeld-Kohno (DK) category of type g has objects = finite-dimensional
representations V_lambda of the quantum group U_q(g) (or equivalently, of the
Yangian Y(g) via the DK bridge), and morphisms = intertwiners.  MC3
(thm:categorical-cg-all-types, cor:mc3-all-types) proves that the evaluation
modules {V(a_i)} thick-generate this category for ALL simple Lie types.

The categorical zeta function counts irreducible objects weighted by dimension:

    zeta^{DK}_g(s) = sum_{lambda dominant, V_lambda != 0} dim(V_lambda)^{-s}

This is the Dirichlet series generated by the dimensions of irreducible
representations of g.

KEY IDENTITY (sl_2):
    For g = sl_2, the irreducible representations are V_n with dim = n+1 for
    n = 0, 1, 2, ...  The nontrivial irreps have dimensions 1, 2, 3, 4, ...
    Therefore:
        zeta^{DK}_{sl_2}(s) = sum_{n >= 1} n^{-s} = zeta(s)
    where zeta(s) is the Riemann zeta function.

    More precisely: with trivial rep (dim=1) INCLUDED, the sum is zeta(s)
    (since 1^{-s} + 2^{-s} + 3^{-s} + ... = zeta(s)).  The function
    object_counting_zeta() defaults to include_trivial=False, returning
    zeta(s) - 1.  Set include_trivial=True to get the full zeta(s).

This is NOT a coincidence --- the sl_2 representation ring is Z[x] with
x = [V_1], and dim: Z[x] -> Z sends x -> 2, so the dimension zeta is the
Dirichlet series of Z_>0 = {dim V_n : n >= 0, V_n nontrivial}.

For higher rank, the representation dimensions are given by the Weyl dimension
formula and the zeta function has richer structure:
    sl_3: dims = 1, 3, 3*, 6, 8, 10, 15, 15*, ...
    sl_4: dims = 1, 4, 4*, 6, 10, 15, 20, ...

The Euler product structure reflects the "prime decomposition" of representations
under tensor product (i.e., the structure of the representation ring).

Verification paths
------------------
    Path 1: Direct summation of dim(V_lambda)^{-s} over dominant weights
    Path 2: Weyl dimension formula (independent computation of dim)
    Path 3: For sl_2: comparison with scipy.special.zeta (Riemann zeta)
    Path 4: Euler product from prime indecomposable decomposition
    Path 5: Functional equation / analytic continuation checks
    Path 6: Growth asymptotics (Weyl law for rep dimensions)

Connections to the monograph
----------------------------
    - MC3 (cor:mc3-all-types): thick generation by evaluation modules
    - DK bridge (thm:drinfeld-kohno-bridge): Y(g) <-> U_q(hat{g})
    - Yangian R-matrix: genus-0 binary shadow of Theta_A
    - kappa(A): the dimension zeta at s=0 relates to kappa via regularization
    - Transfer matrix T(a): eigenvalues at evaluation parameter a encode
      how the integrable system "sees" the zeta at that spectral parameter

Conventions
-----------
    - Highest weight lambda in fundamental weight coordinates (Bourbaki).
    - dim V_lambda via the Weyl dimension formula.
    - Dirichlet series convention: sum a_n n^{-s} with n = dim(V_lambda).
    - Quantum parameter q = exp(2*pi*i / (k+h^vee)) for level k.
    - Cohomological grading (|d| = +1).

References
----------
    Chari-Pressley, "A Guide to Quantum Groups", Cambridge 1994.
    Molev, "Yangians and classical Lie algebras", AMS 2007.
    thm:categorical-cg-all-types (yangians_drinfeld_kohno.tex)
    concordance.tex: MC3 status
"""

from __future__ import annotations

import cmath
import math
from fractions import Fraction
from itertools import product as iter_product
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

import numpy as np


# =========================================================================
# 0. Root system data and Weyl dimension formula
# =========================================================================

def _cartan_matrix(typ: str, n: int) -> List[List[int]]:
    """Cartan matrix for simple Lie algebra of type (typ, n).

    Supports: A_n (sl_{n+1}), B_n (so_{2n+1}), C_n (sp_{2n}), D_n (so_{2n}).
    """
    A = [[0] * n for _ in range(n)]
    for i in range(n):
        A[i][i] = 2
    if typ == 'A':
        for i in range(n - 1):
            A[i][i + 1] = -1
            A[i + 1][i] = -1
    elif typ == 'B':
        for i in range(n - 1):
            A[i][i + 1] = -1
            A[i + 1][i] = -1
        if n >= 2:
            A[n - 2][n - 1] = -2  # short root
    elif typ == 'C':
        for i in range(n - 1):
            A[i][i + 1] = -1
            A[i + 1][i] = -1
        if n >= 2:
            A[n - 1][n - 2] = -2  # long root
    elif typ == 'D':
        for i in range(n - 2):
            A[i][i + 1] = -1
            A[i + 1][i] = -1
        if n >= 3:
            A[n - 3][n - 1] = -1
            A[n - 1][n - 3] = -1
    else:
        raise ValueError(f"Unsupported type: {typ}")
    return A


def _positive_roots(typ: str, n: int) -> List[Tuple[int, ...]]:
    """Positive roots in simple root coordinates for (typ, n)."""
    A = _cartan_matrix(typ, n)
    # Build positive roots by reflection algorithm
    roots = set()
    # Start with simple roots
    for i in range(n):
        r = [0] * n
        r[i] = 1
        roots.add(tuple(r))

    changed = True
    max_iter = 200
    it = 0
    while changed and it < max_iter:
        changed = False
        it += 1
        new_roots = set()
        for r in list(roots):
            for i in range(n):
                # Reflect root r in simple root alpha_i
                # s_i(r) = r - <r, alpha_i^vee> * alpha_i
                # <r, alpha_i^vee> = sum_j r_j * A[j][i]
                inner = sum(r[j] * A[j][i] for j in range(n))
                new_r = list(r)
                new_r[i] -= inner
                new_r_t = tuple(new_r)
                if all(c >= 0 for c in new_r) and new_r_t not in roots:
                    new_roots.add(new_r_t)
                    changed = True
        roots.update(new_roots)

    return sorted(roots)


def _positive_coroots(typ: str, n: int) -> List[Tuple[int, ...]]:
    """Positive coroots in simple coroot coordinates.

    For the pairing <lambda, beta^vee> with lambda in fund wt coords,
    the coroots of A^T are the positive roots of the TRANSPOSE Cartan matrix.
    """
    A = _cartan_matrix(typ, n)
    AT = [[A[j][i] for j in range(n)] for i in range(n)]
    # Positive roots of AT
    roots = set()
    for i in range(n):
        r = [0] * n
        r[i] = 1
        roots.add(tuple(r))

    changed = True
    max_iter = 200
    it = 0
    while changed and it < max_iter:
        changed = False
        it += 1
        new_roots = set()
        for r in list(roots):
            for i in range(n):
                inner = sum(r[j] * AT[j][i] for j in range(n))
                new_r = list(r)
                new_r[i] -= inner
                new_r_t = tuple(new_r)
                if all(c >= 0 for c in new_r) and new_r_t not in roots:
                    new_roots.add(new_r_t)
                    changed = True
        roots.update(new_roots)

    return sorted(roots)


def weyl_dimension(typ: str, n: int, hw: Tuple[int, ...]) -> int:
    """Dimension of V_lambda via the Weyl dimension formula.

    hw = (lambda_1, ..., lambda_n) in fundamental weight coordinates.

    dim V_lambda = prod_{beta^vee > 0} <lambda + rho, beta^vee> / <rho, beta^vee>

    where rho = (1, 1, ..., 1) in fundamental weight coordinates.
    """
    if any(c < 0 for c in hw):
        return 0

    coroots = _positive_coroots(typ, n)
    rho = tuple(1 for _ in range(n))
    hw_rho = tuple(hw[i] + rho[i] for i in range(n))

    dim = Fraction(1)
    for cv in coroots:
        num = sum(hw_rho[j] * cv[j] for j in range(n))
        den = sum(rho[j] * cv[j] for j in range(n))
        if den == 0:
            continue
        dim *= Fraction(num, den)

    return int(dim)


def weyl_dimension_slN(N: int, hw: Tuple[int, ...]) -> int:
    """Weyl dimension for sl_N = A_{N-1}.

    hw in fundamental weight coordinates of sl_N (length N-1).
    """
    return weyl_dimension('A', N - 1, hw)


def weyl_dimension_sl2(n: int) -> int:
    """Dimension of the irreducible sl_2 representation V_n.

    V_n has highest weight n (= n * omega_1).  dim V_n = n + 1.
    """
    return n + 1


def weyl_dimension_sl3(a: int, b: int) -> int:
    """Dimension of the irreducible sl_3 representation V(a, b).

    V(a*omega_1 + b*omega_2) has dim = (a+1)(b+1)(a+b+2)/2.
    """
    if a < 0 or b < 0:
        return 0
    return (a + 1) * (b + 1) * (a + b + 2) // 2


# =========================================================================
# 1. Dominant weight enumeration
# =========================================================================

def dominant_weights_slN(N: int, max_total: int) -> List[Tuple[int, ...]]:
    """All dominant weights lambda = (a_1, ..., a_{N-1}) with sum(a_i) <= max_total.

    Returns weights in lexicographic order, EXCLUDING the zero weight (trivial rep).
    """
    rank = N - 1
    if rank == 0:
        return []
    result = []
    _enumerate_dominant(rank, max_total, [], result)
    return result


def _enumerate_dominant(rank: int, remaining: int,
                        partial: List[int], result: List[Tuple[int, ...]]) -> None:
    """Recursive enumeration of nonneg integer tuples of given length with bounded sum."""
    if len(partial) == rank:
        if any(c > 0 for c in partial):
            result.append(tuple(partial))
        return
    for c in range(remaining + 1):
        _enumerate_dominant(rank, remaining - c, partial + [c], result)


def dominant_weights_bounded_dim(typ: str, n: int,
                                 max_dim: int) -> List[Tuple[Tuple[int, ...], int]]:
    """All dominant weights whose irrep dimension is <= max_dim.

    Returns list of (hw, dim) pairs, sorted by dimension.
    Uses iterative deepening on the sum of fundamental weight coordinates.
    """
    results = []
    seen_dims = set()
    for total in range(1, max_dim + 1):
        weights = []
        _enumerate_dominant(n, total, [], weights)
        for hw in weights:
            d = weyl_dimension(typ, n, hw)
            if d <= max_dim and (hw, d) not in seen_dims:
                results.append((hw, d))
                seen_dims.add((hw, d))
        # Heuristic early exit: if all new weights produce dims > max_dim, stop
        if total > 2 and all(
            weyl_dimension(typ, n, tuple(
                total if i == j else 0 for i in range(n)
            )) > max_dim for j in range(n)
        ):
            break
    results.sort(key=lambda x: (x[1], x[0]))
    return results


# =========================================================================
# 2. Object counting zeta: zeta^{DK}_g(s)
# =========================================================================

def object_counting_zeta(typ: str, n: int, s: complex,
                         max_total_weight: int = 30,
                         include_trivial: bool = False) -> complex:
    r"""Categorical zeta function of the DK category.

    zeta^{DK}_g(s) = sum_{lambda dominant, nontrivial} dim(V_lambda)^{-s}

    For sl_2 (A_1): this equals sum_{n >= 1} (n+1)^{-s} = zeta(s) - 1
    where zeta(s) is the Riemann zeta function.  Or equivalently,
    sum_{d >= 2} d^{-s} = zeta(s) - 1.

    Note: the sl_2 nontrivial representations have dimensions 2, 3, 4, ...
    so the sum is zeta(s) - 1 (missing the d=1 term from the Riemann zeta).

    BUT: there are ALSO representations of dimension 1 (the trivial rep).
    If include_trivial=True: the sum is sum_{d >= 1} d^{-s} = zeta(s).
    Actually, for sl_2, dim(V_n) = n + 1 for n = 0, 1, 2, ...
    so the dimensions are {1, 2, 3, 4, ...} = all positive integers.
    Therefore INCLUDING the trivial rep, zeta^{DK}_{sl_2}(s) = zeta(s).

    CORRECTION: For higher rank, different irreps can have the SAME dimension.
    E.g., sl_3 has V(1,0) and V(0,1) both of dimension 3.  In the Dirichlet
    series, these contribute 2 * 3^{-s}.  The Dirichlet coefficients a_d count
    the NUMBER of irreps of dimension d:

        zeta^{DK}_g(s) = sum_{d >= 1} a_d * d^{-s}

    For sl_2: a_d = 1 for all d >= 1 (each dimension occurs exactly once).
    This gives zeta(s) exactly.

    Args:
        typ: Lie type ('A', 'B', 'C', 'D')
        n: rank
        s: complex parameter
        max_total_weight: cutoff for weight enumeration
        include_trivial: whether to include the trivial representation (dim=1)

    Returns:
        Partial sum of the Dirichlet series.
    """
    result = complex(0)
    if include_trivial:
        result += 1.0  # trivial rep contributes 1^{-s} = 1

    # Enumerate nontrivial dominant weights
    weights = []
    _enumerate_dominant(n, max_total_weight, [], weights)
    for hw in weights:
        d = weyl_dimension(typ, n, hw)
        if d > 0:
            result += d ** (-s)

    return result


def object_counting_zeta_sl2(s: complex, N_terms: int = 1000,
                             include_trivial: bool = True) -> complex:
    r"""Categorical zeta for sl_2 = sum_{n >= start} n^{-s}.

    If include_trivial: sum_{n >= 1} n^{-s} = zeta(s).
    If not include_trivial: sum_{n >= 2} n^{-s} = zeta(s) - 1.

    Uses direct partial sum (no analytic continuation).
    For Re(s) > 1, converges to the Riemann zeta.
    """
    start = 1 if include_trivial else 2
    result = complex(0)
    for n in range(start, start + N_terms):
        result += n ** (-s)
    return result


def riemann_zeta_partial(s: complex, N_terms: int = 10000) -> complex:
    """Partial sum of the Riemann zeta function: sum_{n=1}^{N} n^{-s}.

    For Re(s) > 1, converges to zeta(s).
    """
    return sum(n ** (-s) for n in range(1, N_terms + 1))


def riemann_zeta_euler_maclaurin(s: complex, N: int = 100) -> complex:
    """Riemann zeta via Euler-Maclaurin summation (better convergence).

    zeta(s) = sum_{n=1}^{N} n^{-s} + N^{1-s}/(s-1) + N^{-s}/2
              + sum_k B_{2k}/(2k)! * prod_{j=0}^{2k-2}(s+j) * N^{-(s+2k-1)}

    Uses first few Bernoulli correction terms for improved accuracy.
    """
    if abs(s - 1.0) < 1e-12:
        return complex(float('inf'))

    # Partial sum
    partial = sum(n ** (-s) for n in range(1, N + 1))

    # Euler-Maclaurin tail correction
    tail = N ** (1 - s) / (s - 1) + 0.5 * N ** (-s)

    # Bernoulli number corrections
    bernoulli = [
        Fraction(1, 6),       # B_2
        Fraction(-1, 30),     # B_4
        Fraction(1, 42),      # B_6
        Fraction(-1, 30),     # B_8
        Fraction(5, 66),      # B_10
        Fraction(-691, 2730), # B_12
    ]

    correction = complex(0)
    s_prod = s  # running product s(s+1)...(s+2k-2) / (2k)!
    for k_idx, bk in enumerate(bernoulli):
        k = k_idx + 1  # k = 1, 2, 3, ...
        # Factor = B_{2k} / (2k)! * s(s+1)...(s+2k-2) * N^{-(s+2k-1)}
        if k == 1:
            fact = float(bk) / 2.0 * s * N ** (-(s + 1))
        else:
            # s(s+1)...(s+2k-2) / (2k)!
            numerator_prod = complex(1)
            for j in range(2 * k - 1):
                numerator_prod *= (s + j)
            denom = math.factorial(2 * k)
            fact = float(bk) * numerator_prod / denom * N ** (-(s + 2 * k - 1))
        correction += fact

    return partial + tail + correction


# =========================================================================
# 3. Dirichlet coefficients: a_d = #{irreps of dimension d}
# =========================================================================

def dirichlet_coefficients(typ: str, n: int,
                           max_dim: int) -> Dict[int, int]:
    r"""Compute a_d = number of irreducible representations of dimension d.

    For sl_2: a_d = 1 for all d >= 1 (dimensions are 1, 2, 3, 4, ...).
    For sl_3: a_d can be > 1 (e.g., a_3 = 2 from V(1,0) and V(0,1)).

    Returns dict {d: a_d} for 1 <= d <= max_dim.
    """
    coeffs: Dict[int, int] = {}
    # Include trivial
    coeffs[1] = 1

    # Enumerate nontrivial dominant weights, iterating over total weight sum.
    # For each total, we enumerate weights with sum EXACTLY equal to total
    # (not <= total) to avoid double-counting.
    for total in range(1, max_dim + 1):
        weights_le: List[Tuple[int, ...]] = []
        _enumerate_dominant(n, total, [], weights_le)
        # Filter to weights with sum == total (exact, not <=)
        weights_exact = [w for w in weights_le if sum(w) == total]
        all_big = True
        for hw in weights_exact:
            d = weyl_dimension(typ, n, hw)
            if d <= max_dim:
                all_big = False
                coeffs[d] = coeffs.get(d, 0) + 1
        # Early exit: if all weights at this total have dim > max_dim,
        # all higher totals will too (dimensions grow monotonically)
        if total > 2 and all_big and len(weights_exact) > 0:
            break

    return coeffs


def dimension_spectrum(typ: str, n: int,
                       max_dim: int) -> List[Tuple[int, int]]:
    """Sorted list of (dim, multiplicity) pairs.

    The multiplicity is a_d = #{irreps of dimension d}.
    """
    coeffs = dirichlet_coefficients(typ, n, max_dim)
    return sorted(coeffs.items())


# =========================================================================
# 4. Euler product structure
# =========================================================================

def sl2_euler_product(s: complex, N_primes: int = 100) -> complex:
    r"""Euler product for the sl_2 categorical zeta = Riemann zeta.

    zeta(s) = prod_{p prime} (1 - p^{-s})^{-1}

    For sl_2, every representation V_n is indecomposable (simple), and the
    tensor product V_a x V_b decomposes via the Clebsch-Gordan series:
        V_a x V_b = V_{|a-b|} + V_{|a-b|+2} + ... + V_{a+b}

    The "primes" in the representation ring are the V_n themselves (each is
    simple, hence indecomposable).  However, the tensor product is NOT
    analogous to integer multiplication --- the dimension is multiplicative
    (dim(V_a x V_b) = dim(V_a) * dim(V_b)), but the decomposition is
    additive in the Grothendieck group.

    The Euler product of zeta(s) uses the ORDINARY primes p, coming from
    the factorization of the integer d (the dimension).  This is because
    zeta^{DK}_{sl_2}(s) = sum_{d >= 1} d^{-s} = zeta(s), and the Euler
    product of zeta(s) is prod_p (1 - p^{-s})^{-1}.

    This is a DIMENSION-LEVEL Euler product, not a representation-level one.
    """
    primes = _sieve_primes(N_primes)
    result = complex(1)
    for p in primes:
        result *= 1.0 / (1.0 - p ** (-s))
    return result


def _sieve_primes(count: int) -> List[int]:
    """Return the first `count` primes via sieve of Eratosthenes."""
    if count <= 0:
        return []
    # Upper bound for the count-th prime (generous)
    if count < 6:
        limit = 15
    else:
        limit = int(count * (math.log(count) + math.log(math.log(count)) + 2)) + 10
    sieve = [True] * (limit + 1)
    sieve[0] = sieve[1] = False
    for i in range(2, int(limit ** 0.5) + 1):
        if sieve[i]:
            for j in range(i * i, limit + 1, i):
                sieve[j] = False
    primes = [i for i in range(2, limit + 1) if sieve[i]]
    return primes[:count]


# =========================================================================
# 5. Evaluation module zeta
# =========================================================================

def evaluation_module_zeta_sl2(s: complex, a: complex,
                               N_terms: int = 100) -> complex:
    r"""Evaluation module zeta for sl_2.

    zeta^{eval}_{sl_2}(s, a) = sum_{n >= 1} dim(V_n)^{-s} * chi_n(a)

    where chi_n(a) = trace of the evaluation morphism on V_n at parameter a.
    For sl_2, V_n is the (n+1)-dimensional irrep with highest weight n.
    The character evaluated at a diagonal element diag(a, a^{-1}) is:

        chi_n(a) = sum_{k=0}^{n} a^{n-2k} = (a^{n+1} - a^{-(n+1)}) / (a - a^{-1})

    (the Weyl character formula for sl_2).

    For the Yangian evaluation representation, the evaluation parameter u
    enters as a shift: V(u) has the same dimension as V but the Yangian
    generators act with a u-dependent twist.  At the level of dimensions,
    dim V(u) = dim V is independent of u.  The trace of the transfer matrix
    T(u) = tr_{aux} R_{aux,phys}(u) at the evaluation parameter u gives the
    Baxter T-Q eigenvalue, which for sl_2 at a Bethe root encodes the
    integrability condition.

    Here we use the simpler character-weighted version.
    """
    if abs(a - 1.0 / a) < 1e-15:
        # a = +-1: degenerate, use L'Hopital
        # chi_n(1) = n + 1
        return sum((n + 1) ** (-s) * (n + 1) for n in range(N_terms))

    result = complex(0)
    for n in range(N_terms):
        dim_n = n + 1
        # Character of V_n at diag(a, a^{-1})
        if abs(a - 1.0 / a) < 1e-10:
            chi = complex(dim_n)
        else:
            chi = (a ** (n + 1) - a ** (-(n + 1))) / (a - 1.0 / a)
        result += dim_n ** (-s) * chi
    return result


# =========================================================================
# 6. R-matrix zeta
# =========================================================================

def sl2_yang_r_matrix(u: complex) -> np.ndarray:
    """Yang R-matrix for sl_2 on V_1 x V_1 (= C^2 x C^2).

    R(u) = u * I + P   (additive convention)

    where P is the permutation (swap) operator.
    In the multiplicative convention: R^{mult}(u) = I + P/u.
    """
    I4 = np.eye(4, dtype=complex)
    P = np.array([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ], dtype=complex)
    return u * I4 + P


def r_matrix_power_trace(u: complex, n_max: int = 100) -> List[complex]:
    r"""Traces of powers of the sl_2 Yang R-matrix.

    tr(R(u)^n) for n = 1, ..., n_max.

    The eigenvalues of R(u) on C^2 x C^2 are:
        - (u + 1) with multiplicity 3 (symmetric part Sym^2 C^2)
        - (u - 1) with multiplicity 1 (antisymmetric part Lambda^2 C^2)

    So tr(R(u)^n) = 3*(u+1)^n + (u-1)^n.
    """
    traces = []
    for n in range(1, n_max + 1):
        tr_val = 3.0 * (u + 1) ** n + (u - 1) ** n
        traces.append(tr_val)
    return traces


def r_matrix_zeta(s: complex, u: complex = 1.0,
                  n_max: int = 100) -> complex:
    r"""R-matrix zeta function.

    zeta^R(s) = sum_{n=1}^{n_max} |tr(R(u)^n)|^{-s}

    For u = 1: eigenvalues are 2 (mult 3) and 0 (mult 1).
    tr(R(1)^n) = 3 * 2^n + 0 = 3 * 2^n.
    So zeta^R(s) = sum_n (3 * 2^n)^{-s} = 3^{-s} sum_n 2^{-ns}
                 = 3^{-s} * 2^{-s} / (1 - 2^{-s})  (geometric series, Re(s) > 0).

    For general u: uses eigenvalue formula tr(R^n) = 3(u+1)^n + (u-1)^n.
    """
    traces = r_matrix_power_trace(u, n_max)
    result = complex(0)
    for tr_val in traces:
        abs_tr = abs(tr_val)
        if abs_tr > 1e-50:
            result += abs_tr ** (-s)
    return result


def r_matrix_zeta_exact(s: complex, u: complex = 1.0) -> complex:
    r"""Exact R-matrix zeta via geometric series.

    zeta^R(s) = sum_{n >= 1} |3(u+1)^n + (u-1)^n|^{-s}

    For u such that |u+1| > |u-1| and s real > 0, the dominant term
    is 3|u+1|^n, and the series behaves like 3^{-s} * |u+1|^{-ns} / (1 - |u+1|^{-s}).

    For u = 1 exactly: tr(R^n) = 3 * 2^n (the (u-1) eigenvalue is 0).
    zeta^R(s) = 3^{-s} * sum_{n >= 1} 2^{-ns} = 3^{-s} * 2^{-s} / (1 - 2^{-s}).
    """
    if abs(u - 1.0) < 1e-14:
        # u = 1: exact formula
        return 3 ** (-s) * 2 ** (-s) / (1 - 2 ** (-s))
    else:
        # General: numerical partial sum (no closed form)
        return r_matrix_zeta(s, u, n_max=200)


# =========================================================================
# 7. Grothendieck ring K_0 and its zeta
# =========================================================================

def sl2_representation_ring_zeta(s: complex, N_terms: int = 200) -> complex:
    r"""Zeta function of the sl_2 representation ring K_0(Rep(sl_2)).

    K_0(Rep(sl_2)) = Z[x] where x = [V_1] (the fundamental representation).
    Under the dimension homomorphism dim: K_0 -> Z, x -> 2.

    The tensor product structure:
        V_a tensor V_b = V_{|a-b|} + V_{|a-b|+2} + ... + V_{a+b}
    gives the Clebsch-Gordan multiplication in K_0.

    The "Hasse-Weil zeta of Spec(K_0)" is the zeta function of the ring Z[x].
    Since Z[x] is a polynomial ring over Z, Spec(Z[x]) = A^1_Z.
    The Hasse-Weil zeta of A^1_Z is:

        Z(A^1_Z, s) = prod_p zeta_{F_p[x]}(s)
                     = prod_p 1/((1 - p^{-s})(1 - p^{1-s}))
                     = zeta(s) * zeta(s-1)

    Partial sum approximation.
    """
    # zeta(s) * zeta(s-1) via partial sums
    z1 = riemann_zeta_euler_maclaurin(s, N=100)
    z2 = riemann_zeta_euler_maclaurin(s - 1, N=100)
    return z1 * z2


# =========================================================================
# 8. MC3 thick generation function
# =========================================================================

def sl2_generation_function(n_max: int) -> List[int]:
    r"""Generation function g(n) for sl_2 DK category.

    g(n) = minimum number of evaluation modules V(a_i) needed to thick-generate
    all irreps V_k with k <= n.

    For sl_2, the evaluation modules V(a) at different spectral parameters a
    are ALL isomorphic as sl_2-modules to the fundamental V_1 = C^2.
    Thick generation means: the thick subcategory generated by {V(a_i)} contains
    all finite-dimensional representations.

    By the Clebsch-Gordan decomposition, V_1^{tensor n} contains V_n as a
    summand.  So a SINGLE evaluation module V(a) already thick-generates
    the entire category (since V_n is a direct summand of V(a)^{tensor(n+1)},
    and thick subcategories are closed under direct summands and finite limits).

    More precisely: g(n) = 1 for all n >= 0.  ONE evaluation module suffices.

    This is a consequence of MC3: the evaluation-generated core = full category.

    However, the tensor power needed grows: to reach V_n, we need tensor
    power n + 1 (or n in some conventions).  So the "generation complexity"
    is better measured by the tensor power, not the number of generators.
    """
    return [1] * (n_max + 1)


def sl2_tensor_generation_depth(n: int) -> int:
    r"""Minimum tensor power of V_1 needed to generate V_n.

    V_1^{tensor k} = V_k + V_{k-2} + V_{k-4} + ...
    So V_n first appears in V_1^{tensor n}.
    Generation depth = n.
    """
    return n


def slN_generation_function(N: int, max_weight: int) -> List[int]:
    r"""Generation function for sl_N DK category.

    For sl_N, the fundamental representation V = C^N is an evaluation module.
    The exterior powers Lambda^k(V) (k = 1, ..., N-1) give the fundamental
    representations.  Tensor products of these generate all irreps.

    g(n) counts the minimum number of distinct evaluation modules needed
    to generate all irreps with highest weight of total <= n.

    By MC3 (all simple types): a single evaluation module V(a) at a generic
    point thick-generates the entire category, since tensor powers of V(a)
    produce all fundamental representations (via Schur-Weyl duality), and
    these generate everything.

    Returns list g(0), g(1), ..., g(max_weight).
    """
    # For all types, MC3 gives g(n) = 1 for n >= 1
    return [0] + [1] * max_weight


def generation_zeta(s: complex, g_func: List[int]) -> complex:
    r"""Generation zeta: zeta^{gen}(s) = sum_{n >= 1} g(n)^{-s}.

    When g(n) = 1 for all n >= 1 (as in sl_2), this is
    sum_{n >= 1} 1 = infinity (diverges for all s).

    When g(n) grows, the series can converge.  For the tensor-power
    generation depth g(n) = n, this gives:
    sum_{n >= 1} n^{-s} = zeta(s).
    """
    result = complex(0)
    for n in range(1, len(g_func)):
        gn = g_func[n]
        if gn > 0:
            result += gn ** (-s)
    return result


def tensor_generation_zeta_sl2(s: complex, N_terms: int = 1000) -> complex:
    r"""Tensor generation zeta for sl_2.

    Using tensor generation depth g(n) = n:
    zeta^{gen}(s) = sum_{n >= 1} n^{-s} = zeta(s).

    This gives ANOTHER route from the DK category to the Riemann zeta:
    the representation counting zeta and the generation depth zeta
    BOTH equal zeta(s) for sl_2.
    """
    return sum(n ** (-s) for n in range(1, N_terms + 1))


# =========================================================================
# 9. Knot invariant zeta
# =========================================================================

def colored_jones_sl2(n: int, q: complex) -> complex:
    r"""n-colored Jones polynomial of the trefoil at quantum parameter q.

    The n-colored Jones polynomial J_n(K; q) uses the n-dimensional irrep
    V_{n-1} of U_q(sl_2).  For the trefoil (positive braid sigma_1^3 on 2 strands):

    J_n(3_1; q) = sum_{k=0}^{n-1} q^{k(k+3)/2} * prod_{j=1}^{k} (1 - q^{n+j}) / (1 - q^j)

    (Habiro's formula, normalized so J_1 = 1).
    Actually, we use the formula from the quantum sl_2 representation theory:

    For the trefoil (closure of sigma_1^3 on 2 strands), the colored Jones
    polynomial in color V_n (dimension n) is computed from the R-matrix eigenvalue.

    On V_{n-1} tensor V_{n-1}, the R-matrix has eigenvalues
        q^{j(j+1)/2 - n(n-1)/4} for j = 0, 1, ..., n-1
    (from the Clebsch-Gordan decomposition).

    For small n, we use direct computation via quantum 6j symbols or
    the skein relation.  Here we give an efficient implementation for
    small colors.
    """
    # Use the cabled Jones polynomial formula
    # For trefoil = closure of sigma_1^3 on 2 strands:
    # The quantum trace of R^3 in the n-dim rep gives J_n.
    #
    # R-matrix eigenvalues on V_{n-1} tensor V_{n-1}:
    # The decomposition is V_{n-1} tensor V_{n-1} = V_0 + V_2 + ... + V_{2n-2}
    # On the V_{2j} summand, the eigenvalue of check_R is
    # (-1)^j q^{j(2n-1-j)/2}   ... no, let me use the standard formula.
    #
    # For U_q(sl_2), the Casimir eigenvalue on V_m is
    # c_m = [m/2]_q [m/2 + 1]_q  where [x]_q = (q^x - q^{-x})/(q - q^{-1})
    #
    # The R-matrix eigenvalue on V_j inside V_a tensor V_b is
    # q^{(c_j - c_a - c_b)/2}
    #
    # For the trefoil (braid word sigma_1^3), the quantum trace is
    # sum_j dim_q(V_j) * (R-eigenvalue on V_j)^3 / dim_q(V_a tensor V_b)

    # Simpler approach: use the Rosso-Jones formula
    # J_n(trefoil; q) = sum_{j} q^{3*c_j/2} * [j+1]_q / [1]_q
    # where the sum is over j in the decomposition of V_{n-1}^{tensor 2}

    if abs(q - 1.0) < 1e-12:
        return complex(n)  # classical limit

    def q_number(m: int) -> complex:
        """[m]_q = (q^m - q^{-m}) / (q - q^{-1})."""
        if abs(q - 1.0 / q) < 1e-14:
            return complex(m)
        return (q ** m - q ** (-m)) / (q - q ** (-1))

    def q_dim(m: int) -> complex:
        """Quantum dimension of V_m = [m+1]_q."""
        return q_number(m + 1)

    def casimir_eigenvalue(m: int) -> complex:
        """Eigenvalue of the quadratic Casimir on V_m.

        c_m = m(m+2)/4 in the convention where R eigenvalue = q^{c_j - c_a - c_b}.
        """
        return m * (m + 2) / 4.0

    # Decomposition: V_{n-1} tensor V_{n-1} = V_0 + V_2 + ... + V_{2(n-1)}
    a = n - 1  # highest weight of the input
    c_a = casimir_eigenvalue(a)

    # Braid word sigma_1^3: the invariant is the quantum trace of R^3
    # divided by the quantum dimension of the input.
    # Quantum Markov trace:
    # J_n = sum_{j in decomp} q^{3 * (c_j - 2*c_a)} * q_dim(j) * q^{writhe_correction}
    #
    # More precisely, for the closure of sigma_1^{2m+1} on 2 strands:
    # Jones_n = (-1)^{n-1} * q^{(2m+1)(n^2-1)/4} * sum_{j=0}^{n-1}
    #           (-1)^j * q^{-(2m+1)*j(j+1)/2} * [2j+1]_q / [n]_q

    # Use the well-known Rosso-Jones formula (see Ohtsuki, Theorem 10.3.2):
    # J_n(K; q) for K = trefoil with framing 0 and braid index 3
    # is given by the quantum group invariant.
    #
    # For the trefoil as closure of sigma_1^3:
    # J_n = sum_{j=0}^{n-1} (-1)^j q^{3j(j+1)/2} [2j+1]_q /
    #        ( prod_{k=1}^j [n-k]_q [n+k]_q / [k]_q^2 * ... )
    #
    # Simpler: use Habiro's cyclotomic expansion
    # J_n(3_1; q) = sum_{k=0}^{n-1} q^{k(k+3)/2}
    #               * prod_{j=1}^{k} (1 - q^{n+j})*(1 - q^{-n+j}) / ((1-q^j)*(1-q^{-j}))
    #
    # Wait -- Habiro's formula is for the colored Jones of the trefoil with
    # a specific normalization.  Let me use a cleaner formula.
    #
    # Standard formula (Morton-Lukac / Garoufalidis-Le):
    # For the trefoil 3_1 (right-handed, closure of sigma_1^3):
    # J_n(q) = q^{(n^2-1)/2} * sum_{k=0}^{n-1}
    #          prod_{j=1}^k (q^{(n-j)/2} - q^{-(n-j)/2}) * (q^{(n+j)/2} - q^{-(n+j)/2})
    #          / (q^{j/2} - q^{-j/2})^2
    #          * q^{-k(k+3)/2}
    #
    # This is getting complicated.  Let me use the simplest correct formula.

    # The simplest route: the quantum 2-strand braid.
    # V_{n-1} tensor V_{n-1} = direct sum V_{2j} for j = 0, 1, ..., n-1
    # R-eigenvalue on V_{2j} component: (-1)^{(n-1-j)} * q^{(j(2j+2) - (n-1)(n+1))/2}
    #   = eps(j) * q^{j(j+1) - (n-1)(n+1)/2}
    #
    # Actually, for sl_2, the braiding eigenvalue on V_m inside V_a tensor V_a is
    #   lambda_m = (-1)^{a - m/2} * q^{(m(m+2) - 2a(a+2))/4}
    # where m runs over {0, 2, 4, ..., 2a} in steps of 2.
    # Setting a = n-1, m = 2j (j = 0, ..., n-1):
    #   lambda_{2j} = (-1)^{n-1-j} * q^{(2j(2j+2) - 2(n-1)(n+1))/4}
    #               = (-1)^{n-1-j} * q^{(j(j+1) - (n^2-1)/2)}

    result = complex(0)
    for j in range(n):
        m = 2 * j
        sign = (-1) ** (n - 1 - j)
        casimir_diff = (j * (j + 1) - (n * n - 1) / 2.0)
        lam = sign * q ** casimir_diff
        qdim = q_dim(m)
        # The quantum trace of R^3:
        # sum_j qdim(V_{2j}) * lambda_{2j}^3
        result += qdim * lam ** 3

    # Normalize: J_n = result / qdim(V_{n-1})
    overall_qdim = q_dim(n - 1)
    if abs(overall_qdim) < 1e-50:
        return complex(0)

    return result / overall_qdim


def colored_jones_figure_eight(n: int, q: complex) -> complex:
    r"""n-colored Jones polynomial of the figure-eight knot at parameter q.

    The figure-eight knot 4_1 = closure of sigma_1 sigma_2^{-1} sigma_1 sigma_2^{-1}
    on 3 strands.

    Uses the Habiro-Le formula (cyclotomic expansion):
    J_n(4_1; q) = sum_{k=0}^{n-1} prod_{j=1}^{k} |1 - q^{n+j}|^2 / |1 - q^j|^2

    More precisely (Masbaum formula):
    J_n(4_1; q) = sum_{k=0}^{n-1} prod_{j=1}^{k}
                  (q^{(n-j)/2} - q^{-(n-j)/2})(q^{(n+j)/2} - q^{-(n+j)/2})
                  / (q^{j/2} - q^{-j/2})^2

    where we use q^{1/2} as the square root of q.
    """
    if abs(q - 1.0) < 1e-12:
        return complex(n)

    q_half = q ** 0.5

    def q_bracket(m: int) -> complex:
        """(q^{m/2} - q^{-m/2})."""
        return q_half ** m - q_half ** (-m)

    result = complex(1)  # k=0 term
    running_product = complex(1)
    for k in range(1, n):
        factor_num = q_bracket(n - k) * q_bracket(n + k)
        factor_den = q_bracket(k) ** 2
        if abs(factor_den) < 1e-50:
            break
        running_product *= factor_num / factor_den
        result += running_product

    return result


def knot_invariant_zeta(knot: str, s: complex, q: complex,
                        n_max: int = 30) -> complex:
    r"""Knot invariant zeta function.

    zeta^K(s) = sum_{n=2}^{n_max} |J_n(K; q)|^{-s}

    where J_n is the n-colored Jones polynomial.  We start from n=2
    since J_1 = 1 for all knots (contributes 1 for all s).

    Args:
        knot: 'trefoil' or 'figure_eight'
        s: complex parameter
        q: quantum parameter (e.g., e^{2*pi*i/(k+2)})
        n_max: maximum color
    """
    result = complex(0)
    for n in range(2, n_max + 1):
        if knot == 'trefoil':
            jn = colored_jones_sl2(n, q)
        elif knot == 'figure_eight':
            jn = colored_jones_figure_eight(n, q)
        else:
            raise ValueError(f"Unknown knot: {knot}")
        abs_jn = abs(jn)
        if abs_jn > 1e-50:
            result += abs_jn ** (-s)
    return result


# =========================================================================
# 10. Transfer matrix at zeta zeros
# =========================================================================

def sl2_transfer_matrix_eigenvalues(u: complex, n_sites: int = 4) -> np.ndarray:
    r"""Eigenvalues of the sl_2 transfer matrix T(u) on a spin chain of n_sites.

    T(u) = tr_{aux}(R_{aux,1}(u) R_{aux,2}(u) ... R_{aux,n}(u))

    where R(u) = u I + P is the Yang R-matrix, and the trace is over the
    auxiliary space C^2.

    T(u) acts on (C^2)^{tensor n_sites}.  Its eigenvalues are given by
    the Bethe ansatz (for the XXX spin chain).

    For the XXX Heisenberg spin chain, the transfer matrix eigenvalues are:

        Lambda(u) = (u + 1)^L prod_j (u - u_j - 1)/(u - u_j)
                  + (u - 1) * ... (wrong for general Bethe state)

    Actually, for the Yang R-matrix R(u) = uI + P, the transfer matrix
    T(u) = tr_0(R_{01}(u) ... R_{0L}(u)) acts on the physical space V^{tensor L}.

    For L small, we compute T(u) directly by matrix multiplication.
    """
    # Direct computation for small chains
    L = n_sites
    phys_dim = 2 ** L
    aux_dim = 2

    # Build the product R_{0,1}(u) R_{0,2}(u) ... R_{0,L}(u)
    # as an operator on C^2 (aux) tensor (C^2)^{tensor L} (physical)
    total_dim = aux_dim * phys_dim
    product = np.eye(total_dim, dtype=complex)

    P_2x2 = np.array([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ], dtype=complex)

    for site in range(L):
        # R_{0, site+1}(u) acts on aux (space 0) and physical space (site+1)
        # In the total space: aux tensor phys_1 tensor ... tensor phys_L
        # We need to embed P acting on spaces 0 and (site+1) into the full space.
        R_site = _embed_r_matrix(u, P_2x2, 0, site + 1, L + 1)
        product = R_site @ product

    # Trace over auxiliary space (space 0 = first tensor factor)
    T_matrix = np.zeros((phys_dim, phys_dim), dtype=complex)
    for a in range(aux_dim):
        for i in range(phys_dim):
            row = a * phys_dim + i
            for j in range(phys_dim):
                col = a * phys_dim + j
                T_matrix[i, j] += product[row, col]

    eigenvalues = np.linalg.eigvals(T_matrix)
    return np.sort_complex(eigenvalues)


def _embed_r_matrix(u: complex, P_2x2: np.ndarray,
                    i: int, j: int, n_spaces: int) -> np.ndarray:
    """Embed R(u) = u*I + P acting on spaces i, j into an n_spaces tensor product of C^2.

    R acts as u*I_{4} + P on C^2_i tensor C^2_j, and as identity on all other factors.
    """
    dim_each = 2
    total_dim = dim_each ** n_spaces
    R = np.zeros((total_dim, total_dim), dtype=complex)

    # Iterate over basis states
    for state_in in range(total_dim):
        bits_in = _int_to_bits(state_in, n_spaces, dim_each)
        # u * I contribution: diagonal
        R[state_in, state_in] += u

        # P contribution: swap bits at positions i and j
        bits_out = list(bits_in)
        bits_out[i], bits_out[j] = bits_out[j], bits_out[i]
        state_out = _bits_to_int(bits_out, dim_each)
        R[state_out, state_in] += 1.0

    return R


def _int_to_bits(n: int, length: int, base: int = 2) -> List[int]:
    """Convert integer to list of digits in given base."""
    bits = []
    for _ in range(length):
        bits.append(n % base)
        n //= base
    return bits[::-1]


def _bits_to_int(bits: List[int], base: int = 2) -> int:
    """Convert list of digits to integer."""
    n = 0
    for b in bits:
        n = n * base + b
    return n


def transfer_matrix_at_zeta_zeros(n_sites: int = 4,
                                  n_zeros: int = 5) -> Dict[int, Dict[str, Any]]:
    r"""Eigenvalues of the sl_2 transfer matrix T(u) at u = rho_k / 2.

    rho_k is the k-th nontrivial zero of the Riemann zeta function.
    (Using the standard approximation for the first few zeros.)

    The idea: the Yangian evaluation parameter u can be set to rho_k / 2
    (half a zeta zero on the critical line).  The transfer matrix T(rho_k/2)
    encodes the spectral data of the integrable system at this parameter.

    We check:
    - Whether T(rho_k/2) has any zero eigenvalues
    - The spectral radius and spectral gap
    - The trace = sum of eigenvalues (relates to the free energy)
    """
    # First 20 nontrivial zeros of the Riemann zeta function (imaginary parts)
    # zeta(1/2 + i*gamma_k) = 0
    # Source: LMFDB / standard tables
    zeta_zeros_imag = [
        14.134725141734693,
        21.022039638771555,
        25.010857580145688,
        30.424876125859513,
        32.935061587739189,
        37.586178158825671,
        40.918719012147495,
        43.327073280914999,
        48.005150881167159,
        49.773832477672302,
        52.970321477714460,
        56.446247697063394,
        59.347044002602353,
        60.831778524609809,
        65.112544048081607,
        67.079810529494173,
        69.546401711173979,
        72.067157674481907,
        75.704690699083933,
        77.144840068874805,
    ]

    results = {}
    for k in range(min(n_zeros, len(zeta_zeros_imag))):
        gamma_k = zeta_zeros_imag[k]
        # The zeta zero is at s = 1/2 + i*gamma_k
        # Evaluation parameter: u = rho_k / 2 = (1/2 + i*gamma_k) / 2
        u = complex(0.25, gamma_k / 2)

        eigs = sl2_transfer_matrix_eigenvalues(u, n_sites)
        spectral_radius = float(np.max(np.abs(eigs)))
        trace_T = complex(np.sum(eigs))

        # Check for near-zero eigenvalues
        min_abs_eig = float(np.min(np.abs(eigs)))
        has_near_zero = min_abs_eig < 1e-6

        results[k + 1] = {
            'gamma_k': gamma_k,
            'u': u,
            'eigenvalues': eigs,
            'spectral_radius': spectral_radius,
            'trace': trace_T,
            'min_abs_eigenvalue': min_abs_eig,
            'has_near_zero_eigenvalue': has_near_zero,
            'n_eigenvalues': len(eigs),
        }

    return results


# =========================================================================
# 11. Higher-rank categorical zeta: sl_3, sl_4, sl_5
# =========================================================================

def object_counting_zeta_sl3(s: complex, max_total: int = 20) -> complex:
    r"""Categorical zeta for sl_3.

    zeta^{DK}_{sl_3}(s) = sum_{(a,b) != (0,0)} dim(V(a,b))^{-s}

    Dimensions: dim V(a,b) = (a+1)(b+1)(a+b+2)/2.

    The first few: 3, 3, 6, 8, 10, 10, 15, 15, 15, 21, 24, 24, ...
    Note: V(1,0) and V(0,1) both have dim 3 (fundamental and antifundamental).
    """
    result = complex(0)
    for total in range(1, max_total + 1):
        for a in range(total + 1):
            b = total - a
            d = weyl_dimension_sl3(a, b)
            if d > 0:
                result += d ** (-s)
    return result


def object_counting_zeta_slN(N: int, s: complex, max_total: int = 15) -> complex:
    r"""Categorical zeta for sl_N = A_{N-1}.

    zeta^{DK}_{sl_N}(s) = sum_{lambda nontrivial dominant} dim(V_lambda)^{-s}
    """
    rank = N - 1
    if rank == 0:
        return complex(0)

    result = complex(0)
    weights = dominant_weights_slN(N, max_total)
    for hw in weights:
        d = weyl_dimension('A', rank, hw)
        if d > 0:
            result += d ** (-s)
    return result


# =========================================================================
# 12. Analytic properties
# =========================================================================

def sl2_zeta_residue_at_1() -> float:
    r"""Residue of zeta^{DK}_{sl_2}(s) at s = 1.

    Since zeta^{DK}_{sl_2}(s) = zeta(s), the residue at s = 1 is 1.
    """
    return 1.0


def slN_zeta_abscissa(N: int, max_total: int = 20) -> float:
    r"""Estimate the abscissa of convergence of zeta^{DK}_{sl_N}(s).

    The abscissa sigma_c is the infimum of Re(s) such that the Dirichlet
    series converges.

    For sl_2: sigma_c = 1 (same as Riemann zeta).

    For sl_N with N >= 3: the dominant weights grow like a lattice cone
    in R^{N-1}, and the dimensions grow polynomially.  The Weyl dimension
    formula gives dim V_lambda ~ C * prod_{alpha > 0} <lambda, alpha> for
    large lambda.  The number of irreps with dim <= D grows like D^alpha
    for some alpha depending on the rank.  The abscissa is determined by
    this growth rate.

    For sl_3: dimensions grow like ~ (total_weight)^3 / 2, and the number
    of irreps with total weight = k is ~ k (linear).  So the Dirichlet
    series behaves like sum_k k * (k^3)^{-s} = sum_k k^{1-3s}, converging
    for Re(s) > 2/3.

    General sl_N: the number of dominant weights with total <= k is
    C(k+r-1, r-1) ~ k^{r-1}/(r-1)! where r = rank = N-1.  The typical
    dimension at total k is ~ k^{|Phi^+|} where |Phi^+| = N(N-1)/2.
    So the series behaves like sum_k k^{r-1} * k^{-|Phi^+| * s},
    converging for Re(s) > r / |Phi^+| = (N-1) / (N(N-1)/2) = 2/N.

    Returns numerical estimate.
    """
    # Theoretical prediction: sigma_c = 2/N for sl_N
    return 2.0 / N


def verify_sl2_is_riemann_zeta(s: float, N_terms: int = 5000) -> Dict[str, Any]:
    r"""Verify that zeta^{DK}_{sl_2}(s) = zeta(s) for real s > 1.

    Computes the categorical zeta via direct representation counting
    and compares with the Riemann zeta via Euler-Maclaurin.

    This is the KEY IDENTITY: for sl_2, every positive integer occurs
    exactly once as the dimension of an irreducible representation
    (dim V_n = n + 1), so the categorical zeta IS the Riemann zeta.
    """
    # Path 1: Direct representation counting
    cat_zeta = sum((n + 1) ** (-s) for n in range(N_terms))

    # Path 2: Riemann zeta partial sum
    riem_partial = sum(n ** (-s) for n in range(1, N_terms + 1))

    # Path 3: Euler-Maclaurin
    riem_em = riemann_zeta_euler_maclaurin(s, N=200)

    # Path 4: Euler product
    primes = _sieve_primes(200)
    euler = complex(1)
    for p in primes:
        euler *= 1.0 / (1.0 - p ** (-s))

    return {
        'categorical_zeta': cat_zeta,
        'riemann_partial_sum': riem_partial,
        'riemann_euler_maclaurin': riem_em,
        'euler_product': euler,
        'cat_vs_partial_diff': abs(cat_zeta - riem_partial),
        'cat_vs_em_diff': abs(cat_zeta - riem_em.real),
        'euler_vs_em_diff': abs(euler.real - riem_em.real),
        's': s,
        'N_terms': N_terms,
    }


# =========================================================================
# 13. Cross-family comparison
# =========================================================================

def zeta_comparison(s: float, max_total: int = 15) -> Dict[str, complex]:
    r"""Compare categorical zeta across Lie types at the same s.

    Returns a dict with the partial sums for sl_2, sl_3, sl_4, sl_5.
    """
    return {
        'sl_2': object_counting_zeta('A', 1, s, max_total_weight=max_total),
        'sl_3': object_counting_zeta('A', 2, s, max_total_weight=max_total),
        'sl_4': object_counting_zeta('A', 3, s, max_total_weight=max_total),
        'sl_5': object_counting_zeta('A', 4, s, max_total_weight=max_total),
    }


def zeta_rank_scaling(s: float, N_max: int = 6,
                      max_total: int = 12) -> List[Tuple[int, complex]]:
    r"""How the categorical zeta grows with the rank N of sl_N.

    For large rank, the number of representations grows rapidly, so
    the categorical zeta increases.  The abscissa of convergence
    decreases as 2/N.
    """
    results = []
    for N in range(2, N_max + 1):
        z = object_counting_zeta_slN(N, s, max_total)
        results.append((N, z))
    return results


# =========================================================================
# 14. Multipath verification
# =========================================================================

def multipath_sl2_zeta(s: float) -> Dict[str, Any]:
    r"""5-path verification that zeta^{DK}_{sl_2}(s) = zeta(s).

    Path 1: Direct sum over representations dim(V_n)^{-s}
    Path 2: Sum over positive integers n^{-s} (Weyl dimension gives bijection)
    Path 3: Euler-Maclaurin accelerated Riemann zeta
    Path 4: Euler product over primes
    Path 5: Dirichlet coefficient check (a_d = 1 for all d)
    """
    N = 5000

    # Path 1: sum dim(V_n)^{-s} for n = 0, 1, ...
    path1 = sum(weyl_dimension_sl2(n) ** (-s) for n in range(N))

    # Path 2: sum n^{-s} for n = 1, 2, ...
    path2 = sum(n ** (-s) for n in range(1, N + 1))

    # Path 3: Euler-Maclaurin
    path3 = riemann_zeta_euler_maclaurin(s, N=200)

    # Path 4: Euler product
    primes = _sieve_primes(300)
    path4 = complex(1)
    for p in primes:
        path4 *= 1.0 / (1.0 - p ** (-s))

    # Path 5: Dirichlet coefficients
    coeffs = dirichlet_coefficients('A', 1, 100)
    all_ones = all(v == 1 for v in coeffs.values())

    return {
        'path1_rep_counting': path1,
        'path2_integer_sum': path2,
        'path3_euler_maclaurin': path3.real,
        'path4_euler_product': path4.real,
        'path5_dirichlet_all_ones': all_ones,
        'max_pairwise_diff': max(
            abs(path1 - path2),
            abs(path1 - path3.real),
            abs(path1 - path4.real),
            abs(path2 - path3.real),
        ),
    }


def multipath_sl3_dimensions() -> Dict[str, Any]:
    r"""Verify sl_3 dimensions via two independent methods.

    Path 1: Weyl dimension formula dim V(a,b) = (a+1)(b+1)(a+b+2)/2
    Path 2: General Weyl dimension via positive coroots
    """
    results = {}
    mismatches = 0
    for a in range(8):
        for b in range(8):
            d1 = weyl_dimension_sl3(a, b)
            d2 = weyl_dimension('A', 2, (a, b))
            match = (d1 == d2)
            if not match:
                mismatches += 1
            results[(a, b)] = {'direct': d1, 'weyl': d2, 'match': match}

    return {
        'all_match': mismatches == 0,
        'n_checked': len(results),
        'n_mismatches': mismatches,
        'details': results,
    }
