r"""Non-commutative distance function on shadow geometry and geodesics at zeros.

Mathematical foundation
-----------------------
Connes' spectral distance formula defines a metric on the state space of a
non-commutative algebra (A, H, D):

    d(phi, psi) = sup{ |phi(a) - psi(a)| : ||[D, a]|| <= 1 }

for states phi, psi on the NC algebra A. Applied to the shadow spectral triple
(A^sh, H, D_sh) of a chirally Koszul algebra, this produces a genuine metric
on the "shadow parameter space" whose geometry encodes arithmetic structure.

For the Virasoro family, the shadow algebra A^sh = C[kappa, S_3, S_4, ...]
is parametrized by the central charge c. States are evaluation functionals
phi_c(f) = f(c), and the Connes distance d(phi_c, phi_{c'}) gives a
non-commutative deformation of the Euclidean metric on the c-line.

The shadow Dirac operator D_sh acts on the shadow Hilbert space
H = L^2(A^sh, <,>) with the inner product inherited from the cyclic pairing.
On the primary (kappa) sector, D_sh = d/dc acts as differentiation.
Higher-arity sectors contribute correction terms from the shadow connection
nabla^sh = d - Q'/(2Q) dt (thm:shadow-connection).

Key objects
-----------
1. SHADOW SPECTRAL TRIPLE: (A^sh, H_sh, D_sh) where
   - A^sh = polynomial algebra generated by shadow projections {S_r}_{r>=2}
   - H_sh = l^2 completion of A^sh with inner product from cyclic pairing
   - D_sh = shadow Dirac operator with kappa-weighted spectrum

2. CONNES DISTANCE: d(phi_c, phi_{c'}) = sup{ |f(c) - f(c')| : ||[D_sh, f]|| <= 1 }
   On the kappa sector: the Lipschitz condition ||[D_sh, f]|| <= 1 becomes
   |f'(c)| * |d(kappa)/dc| <= 1 (since [D_sh, f] ~ f' * kappa'(c)).
   For Virasoro kappa(c) = c/2: d(phi_c, phi_{c'}) = |c - c'| / |kappa'| = |c - c'| / (1/2) ...
   BUT the higher-arity corrections from S_3, S_4, ... modify this.

3. SHADOW GEODESICS: Shortest paths in the NC metric. The geodesic equation
   is gamma''(t) + Gamma^c_{cc} gamma'(t)^2 = 0 where the Christoffel symbol
   is determined by the shadow metric g_cc = sum_r (dS_r/dc)^2 * w_r.

4. WASSERSTEIN DISTANCE: W_p(mu_A, mu_{A'}) between shadow spectral measures
   at different central charges, compared with Connes distance.

Verification paths
------------------
    Path 1: Direct Connes formula (Lipschitz supremum)
    Path 2: Geodesic equation integration
    Path 3: Lipschitz norm from spectral data
    Path 4: Wasserstein comparison from spectral measures
    Path 5: Numerical convergence in truncation level

Anti-patterns guarded
---------------------
    AP1:  kappa formulas computed from first principles per family
    AP8:  Virasoro self-dual at c=13, NOT c=26
    AP10: Expected values derived from multiple independent paths
    AP20: kappa(A) is intrinsic to A; kappa_eff is different
    AP24: kappa(Vir_c) + kappa(Vir_{26-c}) = 13, NOT 0
    AP39: kappa = c/2 for Virasoro ONLY; not for general VOAs
    AP48: kappa depends on full algebra, not just Virasoro subalgebra

Connections to monograph
------------------------
    thm:shadow-connection (higher_genus_modular_koszul.tex)
    def:shadow-metric (higher_genus_modular_koszul.tex)
    thm:riccati-algebraicity (higher_genus_modular_koszul.tex)
    thm:single-line-dichotomy (higher_genus_modular_koszul.tex)
    Connes, "Noncommutative Geometry", Academic Press 1994
    Connes-Marcolli, "Noncommutative Geometry, Quantum Fields
      and Motives", AMS 2008

Conventions
-----------
    - Virasoro: kappa(Vir_c) = c/2. Self-dual at c=13.
    - Koszul duality: c -> 26-c. kappa + kappa' = 13 (AP24).
    - Shadow tower: S_2 = c/2, S_3 = 2, S_4 = 10/[c(5c+22)].
    - Cohomological grading (|d| = +1).
    - Zeta zeros: rho_n = 1/2 + i*gamma_n, c(rho) = 26*rho.
"""

from __future__ import annotations

import cmath
import math
from fractions import Fraction
from typing import Any, Callable, Dict, List, Optional, Tuple, Union

import numpy as np
from numpy.linalg import eigh, norm


# =========================================================================
# 0. Virasoro shadow tower data (first-principles computation)
# =========================================================================

def virasoro_kappa(c_val: complex) -> complex:
    """kappa(Vir_c) = c/2. AP39: this is Virasoro-specific."""
    return c_val / 2


def virasoro_shadow_coefficients(c_val: complex, max_r: int = 20) -> Dict[int, complex]:
    """Shadow tower coefficients S_r(c) for Virasoro at central charge c.

    S_2 = c/2, S_3 = 2, S_4 = 10/[c(5c+22)].
    Higher arities from the bracket recurrence.
    """
    if abs(c_val) < 1e-15:
        # c=0: S_2=0, S_3=2, S_4 diverges. Return what we can.
        Sr: Dict[int, complex] = {2: 0.0, 3: 2.0}
        return Sr

    P = 2.0 / c_val  # propagator
    Sr = {}
    Sr[2] = c_val / 2
    Sr[3] = 2.0
    denom4 = c_val * (5 * c_val + 22)
    if abs(denom4) < 1e-30:
        Sr[4] = float('inf')
        return Sr
    Sr[4] = 10.0 / denom4

    for r in range(5, max_r + 1):
        o_r = 0.0
        for j in range(2, r + 1):
            kk = r + 2 - j
            if kk < 2 or kk > r or kk not in Sr:
                continue
            if j > kk:
                continue
            bracket = j * Sr[j] * P * kk * Sr[kk]
            if j == kk:
                o_r += 0.5 * bracket
            else:
                o_r += bracket
        Sr[r] = -o_r / (2 * r)
    return Sr


def virasoro_shadow_derivatives(c_val: float, max_r: int = 15,
                                 dc: float = 1e-6) -> Dict[int, float]:
    """Numerical derivatives dS_r/dc at given c, via central differences.

    These encode how the shadow tower varies with the central charge.
    """
    Sr_plus = virasoro_shadow_coefficients(c_val + dc, max_r)
    Sr_minus = virasoro_shadow_coefficients(c_val - dc, max_r)
    derivs = {}
    for r in Sr_plus:
        if r in Sr_minus:
            val = (Sr_plus[r] - Sr_minus[r]) / (2 * dc)
            if isinstance(val, complex) and abs(val.imag) < 1e-10:
                val = val.real
            derivs[r] = val
    return derivs


# =========================================================================
# 1. Shadow spectral triple and Dirac operator
# =========================================================================

def shadow_metric_tensor(c_val: float, max_r: int = 10,
                          weights: Optional[Dict[int, float]] = None) -> float:
    """Shadow metric g_cc(c) = sum_r w_r * (dS_r/dc)^2.

    The metric on the c-line induced by the shadow embedding
    c -> (S_2(c), S_3(c), S_4(c), ...). Each arity component contributes
    to the metric with weight w_r. Default weights: w_r = 1/r^2
    (spectral decay).

    Returns g_cc as a positive real number.
    """
    if weights is None:
        weights = {r: 1.0 / r**2 for r in range(2, max_r + 1)}

    derivs = virasoro_shadow_derivatives(c_val, max_r)
    g_cc = 0.0
    for r, dSr in derivs.items():
        w = weights.get(r, 0.0)
        g_cc += w * dSr**2
    return g_cc


def shadow_dirac_spectrum(c_val: float, N_trunc: int = 20) -> np.ndarray:
    """Spectrum of the shadow Dirac operator D_sh at central charge c.

    D_sh acts on the truncated shadow Hilbert space spanned by
    {|r>}_{r=2}^{N_trunc+1} with eigenvalues lambda_r = r * S_r(c).

    This is the spectral data of the NC geometry: the eigenvalues of D_sh
    encode the shadow obstruction tower with arity weighting.
    """
    Sr = virasoro_shadow_coefficients(c_val, N_trunc + 1)
    eigenvalues = []
    for r in range(2, N_trunc + 2):
        if r in Sr:
            lam = r * Sr[r]
            if isinstance(lam, complex):
                lam = lam.real if abs(lam.imag) < 1e-10 else lam
            eigenvalues.append(lam)
    return np.array(eigenvalues, dtype=complex)


def shadow_commutator_norm(f_vals: np.ndarray, dirac_eigenvalues: np.ndarray) -> float:
    """||[D_sh, f]|| for a diagonal operator f in the shadow eigenbasis.

    In the eigenbasis of D_sh, [D_sh, f] has matrix elements
    (lambda_i - lambda_j) * <i|f|j>. For a function on the shadow space
    (diagonal in eigenbasis), the commutator norm is
    max_{i != j} |lambda_i - lambda_j| * |f_{ij}|.

    For diagonal f: [D_sh, f] is off-diagonal with entries
    (lambda_i - lambda_j) * f_{ij}. If f is multiplication by a shadow
    observable, f_{ij} encodes the transition amplitudes.

    Simplified model: f acts by multiplication on the truncated space,
    so ||[D, f]|| = max_i |df/d(lambda_i)| * gap_i where gap_i are spectral gaps.
    We use the Lipschitz estimate: ||[D, f]|| ~ max|f'| * max spectral gap^{-1}.
    """
    n = len(dirac_eigenvalues)
    if n < 2:
        return 0.0

    # Spectral gaps
    sorted_eigs = np.sort(dirac_eigenvalues.real)
    gaps = np.diff(sorted_eigs)
    nonzero_gaps = gaps[np.abs(gaps) > 1e-15]
    if len(nonzero_gaps) == 0:
        return float('inf')

    # For diagonal f: norm of commutator is max spectral variation of f
    # divided by the minimum spectral gap
    f_diffs = np.abs(np.diff(np.sort(f_vals.real)))
    if len(f_diffs) == 0:
        return 0.0

    max_f_variation = np.max(f_diffs)
    min_gap = np.min(np.abs(nonzero_gaps))

    return max_f_variation / min_gap if min_gap > 1e-15 else float('inf')


# =========================================================================
# 2. Connes distance function
# =========================================================================

def connes_distance_kappa_sector(c1: float, c2: float) -> float:
    """Connes distance in the pure kappa sector (arity 2 only).

    In the kappa sector, kappa(c) = c/2 is the only observable.
    The Lipschitz condition ||[D, f]|| <= 1 becomes |f'(c)| * |kappa'(c)| <= 1.
    Since kappa'(c) = 1/2: d(phi_{c1}, phi_{c2}) = |kappa(c1) - kappa(c2)|
    = |c1 - c2| / 2.

    This is the LEADING approximation. Higher arities correct this.
    """
    return abs(c1 - c2) / 2.0


def connes_distance_truncated(c1: float, c2: float, max_r: int = 10,
                                weights: Optional[Dict[int, float]] = None,
                                N_sample: int = 200) -> float:
    """Connes distance between phi_{c1} and phi_{c2} including arities up to max_r.

    Computed via the geodesic integral:
        d(c1, c2) = int_{c1}^{c2} sqrt(g_cc(c)) dc

    where g_cc is the shadow metric tensor. This equals the Connes distance
    when the algebra is commutative (which A^sh is, being polynomial).

    For commutative A^sh, the Connes distance reduces to the geodesic
    distance in the Riemannian metric induced by the shadow embedding.

    N_sample: number of quadrature points for the integral.
    """
    if abs(c1 - c2) < 1e-15:
        return 0.0

    a, b = min(c1, c2), max(c1, c2)

    # Trapezoidal quadrature
    cs = np.linspace(a, b, N_sample + 1)
    integrand = np.zeros(N_sample + 1)
    for i, cv in enumerate(cs):
        # Avoid c=0 and singular points
        if abs(cv) < 0.01:
            cv_safe = 0.01 if cv >= 0 else -0.01
        elif abs(5 * cv + 22) < 0.01:
            cv_safe = cv + 0.1
        else:
            cv_safe = cv
        g = shadow_metric_tensor(cv_safe, max_r, weights)
        integrand[i] = math.sqrt(max(g, 0.0))

    dc = (b - a) / N_sample
    distance = np.trapz(integrand, dx=dc)
    return float(distance)


def connes_distance_matrix(c_values: List[float], max_r: int = 10,
                            weights: Optional[Dict[int, float]] = None,
                            N_sample: int = 100) -> np.ndarray:
    """Distance matrix d(c_i, c_j) for a list of central charge values.

    Returns an n x n symmetric matrix where n = len(c_values).
    """
    n = len(c_values)
    D = np.zeros((n, n))
    for i in range(n):
        for j in range(i + 1, n):
            d_ij = connes_distance_truncated(
                c_values[i], c_values[j], max_r, weights, N_sample
            )
            D[i, j] = d_ij
            D[j, i] = d_ij
    return D


def connes_distance_via_lipschitz(c1: float, c2: float, max_r: int = 10,
                                    N_test: int = 500) -> float:
    """Connes distance via Lipschitz supremum (direct definition).

    d(phi_{c1}, phi_{c2}) = sup{ |f(c1) - f(c2)| : ||[D, f]|| <= 1 }

    We sample test functions f from the shadow algebra and compute the
    supremum. Test functions: f = S_r for each r, plus linear combinations.
    The Lipschitz constraint is ||[D, f]|| <= 1.

    For commutative algebras, this equals the geodesic distance.
    """
    Sr1 = virasoro_shadow_coefficients(c1, max_r)
    Sr2 = virasoro_shadow_coefficients(c2, max_r)

    # Method: for each shadow observable S_r, the Lipschitz constant is
    # L_r = sup_c |dS_r/dc|. The normalized observable f_r = S_r / L_r
    # satisfies ||[D, f_r]|| <= 1 (approximately). Then:
    # d >= |f_r(c1) - f_r(c2)| = |S_r(c1) - S_r(c2)| / L_r.
    # The Connes distance is the supremum over all such test functions.

    # Also use the geodesic integral as a tighter bound
    max_val = 0.0

    for r in range(2, max_r + 1):
        if r not in Sr1 or r not in Sr2:
            continue
        delta_Sr = abs(Sr1[r] - Sr2[r])

        # Estimate Lipschitz constant of S_r via derivative sampling
        c_min, c_max = min(c1, c2), max(c1, c2)
        # Also sample outside the interval to get the global Lip constant
        c_sample_min = max(0.5, c_min - 2)
        c_sample_max = c_max + 2
        test_cs = np.linspace(c_sample_min, c_sample_max, 50)
        lip_r = 0.0
        for tc in test_cs:
            deriv = virasoro_shadow_derivatives(tc, max_r=r)
            if r in deriv:
                lip_r = max(lip_r, abs(deriv[r]))

        if lip_r > 1e-15:
            val = delta_Sr / lip_r
            max_val = max(max_val, val)

    return max_val


# =========================================================================
# 3. Shadow geodesics
# =========================================================================

def shadow_christoffel(c_val: float, max_r: int = 10,
                        weights: Optional[Dict[int, float]] = None,
                        dc: float = 1e-5) -> float:
    """Christoffel symbol Gamma^c_{cc} for the shadow metric.

    Gamma = (1/2) * g^{cc} * dg_{cc}/dc

    where g_{cc} is the shadow metric tensor.
    """
    g = shadow_metric_tensor(c_val, max_r, weights)
    g_plus = shadow_metric_tensor(c_val + dc, max_r, weights)
    g_minus = shadow_metric_tensor(c_val - dc, max_r, weights)
    dg = (g_plus - g_minus) / (2 * dc)

    if abs(g) < 1e-15:
        return 0.0
    return 0.5 * dg / g


def geodesic_solve(c_start: float, c_end: float, max_r: int = 10,
                    weights: Optional[Dict[int, float]] = None,
                    N_steps: int = 500) -> Tuple[np.ndarray, np.ndarray]:
    """Solve the geodesic equation from c_start to c_end.

    gamma''(t) + Gamma^c_{cc}(gamma(t)) * gamma'(t)^2 = 0

    with gamma(0) = c_start, gamma(1) = c_end (boundary conditions).

    Uses shooting method: guess gamma'(0) = v0, integrate, adjust v0
    until gamma(1) = c_end.

    Returns (t_array, gamma_array).
    """
    dt = 1.0 / N_steps

    def integrate_geodesic(v0: float) -> np.ndarray:
        """Integrate geodesic ODE with initial velocity v0."""
        gamma_arr = np.zeros(N_steps + 1)
        v_arr = np.zeros(N_steps + 1)
        gamma_arr[0] = c_start
        v_arr[0] = v0

        for i in range(N_steps):
            c_cur = gamma_arr[i]
            v_cur = v_arr[i]
            # Avoid singular points
            if abs(c_cur) < 0.01:
                c_cur = 0.01
            if abs(5 * c_cur + 22) < 0.01:
                c_cur += 0.5

            Gamma = shadow_christoffel(c_cur, max_r, weights)
            # RK2 step
            a1 = -Gamma * v_cur**2
            c_mid = c_cur + 0.5 * dt * v_cur
            v_mid = v_cur + 0.5 * dt * a1
            if abs(c_mid) < 0.01:
                c_mid = 0.01
            Gamma_mid = shadow_christoffel(c_mid, max_r, weights)
            a_mid = -Gamma_mid * v_mid**2

            gamma_arr[i + 1] = c_cur + dt * v_mid
            v_arr[i + 1] = v_cur + dt * a_mid

        return gamma_arr

    # Shooting method: find v0 such that gamma(1) = c_end
    # Initial guess: straight line
    v0_guess = c_end - c_start

    # Bisection / secant method
    v_lo, v_hi = v0_guess * 0.5, v0_guess * 2.0
    if v0_guess < 0:
        v_lo, v_hi = v_hi, v_lo

    # Secant method
    v_a = v_lo
    v_b = v_hi
    gamma_a = integrate_geodesic(v_a)
    gamma_b = integrate_geodesic(v_b)
    fa = gamma_a[-1] - c_end
    fb = gamma_b[-1] - c_end

    for _ in range(50):
        if abs(fb - fa) < 1e-15:
            break
        v_new = v_b - fb * (v_b - v_a) / (fb - fa)
        gamma_new = integrate_geodesic(v_new)
        f_new = gamma_new[-1] - c_end
        if abs(f_new) < 1e-10:
            t_arr = np.linspace(0, 1, N_steps + 1)
            return t_arr, gamma_new
        v_a, fa = v_b, fb
        v_b, fb = v_new, f_new

    # Return best result
    gamma_final = integrate_geodesic(v_b)
    t_arr = np.linspace(0, 1, N_steps + 1)
    return t_arr, gamma_final


def geodesic_passes_through(c_start: float, c_end: float, c_target: float,
                             max_r: int = 10, tol: float = 0.5,
                             N_steps: int = 300) -> Tuple[bool, float]:
    """Check if the geodesic from c_start to c_end passes near c_target.

    Returns (passes, min_distance) where passes = (min_distance < tol).
    """
    _, gamma = geodesic_solve(c_start, c_end, max_r, N_steps=N_steps)
    distances = np.abs(gamma - c_target)
    min_dist = float(np.min(distances))
    return min_dist < tol, min_dist


def nc_metric_curvature(c_val: float, max_r: int = 10,
                         weights: Optional[Dict[int, float]] = None,
                         dc: float = 1e-4) -> float:
    """Scalar curvature R_NC(c) of the shadow metric.

    For a 1D metric g_{cc}(c), the scalar curvature is:
    R = -(1/g) * d^2(sqrt(g))/dc^2 / sqrt(g)
      = -(1/2g) * [g'' - (g')^2/(2g)]

    where g = g_{cc}, g' = dg/dc, g'' = d^2g/dc^2.
    """
    g = shadow_metric_tensor(c_val, max_r, weights)
    g_plus = shadow_metric_tensor(c_val + dc, max_r, weights)
    g_minus = shadow_metric_tensor(c_val - dc, max_r, weights)
    g_prime = (g_plus - g_minus) / (2 * dc)
    g_double = (g_plus - 2 * g + g_minus) / dc**2

    if abs(g) < 1e-15:
        return 0.0

    # Gaussian curvature for 1D manifold in ambient embedding
    # K = -1/(2*g) * (g'' - g'^2 / (2*g))
    R = -(1.0 / (2 * g)) * (g_double - g_prime**2 / (2 * g))
    return R


# =========================================================================
# 4. Koszul dual distance and self-dual geometry
# =========================================================================

def koszul_dual_distance(c_val: float, max_r: int = 10,
                          N_sample: int = 200) -> float:
    """Distance d(phi_c, phi_{26-c}) from a Virasoro algebra to its Koszul dual.

    By AP24: kappa(Vir_c) + kappa(Vir_{26-c}) = 13.
    This distance should vanish at c=13 (self-dual point, AP8).
    """
    c_dual = 26.0 - c_val
    return connes_distance_truncated(c_val, c_dual, max_r, N_sample=N_sample)


def koszul_dual_distance_kappa_sector(c_val: float) -> float:
    """Koszul dual distance in pure kappa sector.

    d_kappa(c, 26-c) = |kappa(c) - kappa(26-c)| = |c/2 - (26-c)/2| = |c - 13|.
    Vanishes at c=13.
    """
    return abs(c_val - 13.0)


def self_dual_vanishing_exponent(c_values: Optional[List[float]] = None,
                                  max_r: int = 8,
                                  N_sample: int = 100) -> Tuple[float, float]:
    """Compute the vanishing exponent alpha in d(c, 26-c) ~ |c-13|^alpha.

    Fits log(d) = alpha * log(|c-13|) + const near c=13.

    Returns (alpha, r_squared) for the fit quality.
    """
    if c_values is None:
        # Points near c=13 on both sides
        c_values = [13.0 + delta for delta in
                    [0.1, 0.2, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 10.0, 12.0]]

    log_x = []
    log_d = []
    for cv in c_values:
        x = abs(cv - 13.0)
        if x < 1e-10:
            continue
        d = connes_distance_truncated(cv, 26.0 - cv, max_r, N_sample=N_sample)
        if d > 1e-15:
            log_x.append(math.log(x))
            log_d.append(math.log(d))

    if len(log_x) < 2:
        return 1.0, 0.0

    # Linear regression: log_d = alpha * log_x + beta
    lx = np.array(log_x)
    ld = np.array(log_d)
    A_mat = np.vstack([lx, np.ones(len(lx))]).T
    result = np.linalg.lstsq(A_mat, ld, rcond=None)
    alpha = result[0][0]

    # R^2
    ld_pred = A_mat @ result[0]
    ss_res = np.sum((ld - ld_pred)**2)
    ss_tot = np.sum((ld - np.mean(ld))**2)
    r_sq = 1.0 - ss_res / ss_tot if ss_tot > 1e-15 else 0.0

    return float(alpha), float(r_sq)


# =========================================================================
# 5. NC distance at zeta zeros
# =========================================================================

# First 25 non-trivial Riemann zeta zeros (imaginary parts)
ZETA_ZEROS_GAMMA = [
    14.134725141734693, 21.022039638771555, 25.010857580145688,
    30.424876125859513, 32.935061587739189, 37.586178158825671,
    40.918719012147495, 43.327073280914999, 48.005150881167159,
    49.773832477672302, 52.970321477714460, 56.446247697063394,
    59.347044002602353, 60.831778524609809, 65.112544048081606,
    67.079810529494173, 69.546401711173979, 72.067157674481907,
    75.704690699083933, 77.144840068874805, 79.337375020249367,
    82.910380854086030, 84.735492980517050, 87.425274613125229,
    88.809111207634465,
]


def zeta_zero_to_c(n: int) -> complex:
    """Map the n-th zeta zero rho_n = 1/2 + i*gamma_n to central charge.

    c(rho) = 26 * rho = 13 + 26*i*gamma_n.
    The real part is 13 (self-dual point!), imaginary part scales with gamma_n.
    """
    if n < 1 or n > len(ZETA_ZEROS_GAMMA):
        raise ValueError(f"n={n} out of range [1, {len(ZETA_ZEROS_GAMMA)}]")
    gamma_n = ZETA_ZEROS_GAMMA[n - 1]
    return complex(13.0, 26.0 * gamma_n)


def nc_distance_consecutive_zeros(n: int, max_r: int = 6) -> float:
    """NC distance between consecutive zeta zeros in the shadow geometry.

    d(phi_{c(rho_n)}, phi_{c(rho_{n+1})})

    Since c(rho_n) = 13 + 26i*gamma_n, consecutive zeros have
    purely imaginary separation 26i*(gamma_{n+1} - gamma_n).

    In the kappa sector: d = |kappa(c_n) - kappa(c_{n+1})| = 13|gamma_{n+1} - gamma_n|.
    With shadow corrections from S_3, S_4, ... at complex c.
    """
    if n < 1 or n >= len(ZETA_ZEROS_GAMMA):
        raise ValueError(f"n={n} out of range [1, {len(ZETA_ZEROS_GAMMA) - 1}]")

    c_n = zeta_zero_to_c(n)
    c_n1 = zeta_zero_to_c(n + 1)

    # Kappa sector contribution
    d_kappa = abs(virasoro_kappa(c_n) - virasoro_kappa(c_n1))

    # Higher-arity corrections
    Sr_n = virasoro_shadow_coefficients(c_n, max_r)
    Sr_n1 = virasoro_shadow_coefficients(c_n1, max_r)

    corrections = 0.0
    for r in range(3, max_r + 1):
        if r in Sr_n and r in Sr_n1:
            w_r = 1.0 / r**2  # spectral weight
            delta = abs(Sr_n[r] - Sr_n1[r])
            corrections += w_r * delta**2

    return math.sqrt(d_kappa**2 + corrections)


def nc_distance_zero_to_self_dual(n: int, max_r: int = 6) -> float:
    """NC distance from n-th zeta zero to the self-dual point c=13.

    d(phi_{c(rho_n)}, phi_{13})

    Since c(rho_n) = 13 + 26i*gamma_n, the distance is purely imaginary
    in the c-plane: |c(rho_n) - 13| = 26*gamma_n.

    In the kappa sector: d = |kappa(c(rho_n)) - kappa(13)| = 13*gamma_n.
    """
    c_n = zeta_zero_to_c(n)

    # Kappa sector
    d_kappa = abs(virasoro_kappa(c_n) - virasoro_kappa(13.0))

    # Higher corrections at complex c
    Sr_n = virasoro_shadow_coefficients(c_n, max_r)
    Sr_13 = virasoro_shadow_coefficients(13.0, max_r)

    corrections = 0.0
    for r in range(3, max_r + 1):
        if r in Sr_n and r in Sr_13:
            w_r = 1.0 / r**2
            delta = abs(Sr_n[r] - Sr_13[r])
            corrections += w_r * delta**2

    return math.sqrt(d_kappa**2 + corrections)


def nc_distance_zero_to_reflected(n: int, max_r: int = 6) -> float:
    """NC distance between rho_n and its complex conjugate rho_n_bar.

    rho_n = 1/2 + i*gamma_n, rho_n_bar = 1/2 - i*gamma_n.
    c(rho_n) = 13 + 26i*gamma_n, c(rho_n_bar) = 13 - 26i*gamma_n.

    These are complex conjugates: the distance is 52*gamma_n in kappa sector.
    """
    c_n = zeta_zero_to_c(n)
    c_nbar = c_n.conjugate()

    # Kappa sector
    d_kappa = abs(virasoro_kappa(c_n) - virasoro_kappa(c_nbar))

    # Higher corrections
    Sr_n = virasoro_shadow_coefficients(c_n, max_r)
    Sr_nbar = virasoro_shadow_coefficients(c_nbar, max_r)

    corrections = 0.0
    for r in range(3, max_r + 1):
        if r in Sr_n and r in Sr_nbar:
            w_r = 1.0 / r**2
            delta = abs(Sr_n[r] - Sr_nbar[r])
            corrections += w_r * delta**2

    return math.sqrt(d_kappa**2 + corrections)


def consecutive_zero_spacings_nc(N: int = 20, max_r: int = 6) -> np.ndarray:
    """NC distance spacings between consecutive zeros: d_n = d(rho_n, rho_{n+1}).

    Returns array of N-1 spacings.
    """
    spacings = []
    for n in range(1, N):
        d = nc_distance_consecutive_zeros(n, max_r)
        spacings.append(d)
    return np.array(spacings)


def normalized_zero_spacings_nc(N: int = 20, max_r: int = 6) -> np.ndarray:
    """Normalized NC spacings: s_n = d_n / <d> where <d> is the mean spacing.

    GUE prediction: the distribution of normalized spacings follows
    the Wigner surmise p(s) = (32/pi^2) * s^2 * exp(-4s^2/pi).
    """
    spacings = consecutive_zero_spacings_nc(N, max_r)
    mean_spacing = np.mean(spacings)
    if mean_spacing < 1e-15:
        return spacings
    return spacings / mean_spacing


def gue_wigner_surmise(s: float) -> float:
    """GUE Wigner surmise: p(s) = (32/pi^2) * s^2 * exp(-4s^2/pi)."""
    return (32.0 / math.pi**2) * s**2 * math.exp(-4.0 * s**2 / math.pi)


def kolmogorov_smirnov_vs_gue(spacings_normalized: np.ndarray) -> float:
    """Kolmogorov-Smirnov statistic comparing normalized spacings to GUE.

    Returns the KS statistic D = max |F_empirical(s) - F_GUE(s)|.
    Lower is better (more GUE-like).
    """
    from scipy.integrate import quad

    sorted_s = np.sort(spacings_normalized)
    n = len(sorted_s)

    ks_stat = 0.0
    for i, si in enumerate(sorted_s):
        # Empirical CDF at si
        F_emp = (i + 1) / n
        # GUE CDF at si
        F_gue, _ = quad(gue_wigner_surmise, 0, si)
        ks_stat = max(ks_stat, abs(F_emp - F_gue))

    return ks_stat


# =========================================================================
# 6. Wasserstein distance from shadow spectral measures
# =========================================================================

def shadow_spectral_measure(c_val: float, max_r: int = 15) -> Tuple[np.ndarray, np.ndarray]:
    """Shadow spectral measure at central charge c.

    The spectral measure mu_c = sum_r delta(lambda - lambda_r(c)) * w_r
    where lambda_r = r * S_r(c) are the Dirac eigenvalues and w_r are weights.

    Returns (positions, weights) arrays.
    """
    Sr = virasoro_shadow_coefficients(c_val, max_r)
    positions = []
    weights_arr = []
    for r in range(2, max_r + 1):
        if r in Sr:
            lam = r * Sr[r]
            if isinstance(lam, complex):
                lam = lam.real if abs(lam.imag) < 1e-10 else abs(lam)
            positions.append(float(lam))
            weights_arr.append(1.0 / r**2)

    pos = np.array(positions)
    wt = np.array(weights_arr)
    # Normalize weights
    if np.sum(wt) > 0:
        wt = wt / np.sum(wt)
    return pos, wt


def wasserstein_1d(positions1: np.ndarray, weights1: np.ndarray,
                    positions2: np.ndarray, weights2: np.ndarray,
                    p: int = 1) -> float:
    """Wasserstein-p distance between two 1D discrete measures.

    Uses the closed-form for 1D distributions via quantile functions:
    W_p^p = int_0^1 |F_1^{-1}(t) - F_2^{-1}(t)|^p dt

    For discrete measures, this is computed via sorted atoms.
    """
    # Build sorted CDFs
    idx1 = np.argsort(positions1)
    idx2 = np.argsort(positions2)
    pos1 = positions1[idx1]
    w1 = weights1[idx1]
    pos2 = positions2[idx2]
    w2 = weights2[idx2]

    # Merge into common grid for quantile comparison
    # Use the standard 1D Wasserstein computation
    cdf1 = np.cumsum(w1)
    cdf2 = np.cumsum(w2)

    # All breakpoints
    all_breaks = np.sort(np.unique(np.concatenate([cdf1, cdf2, [0.0, 1.0]])))

    total = 0.0
    for i in range(len(all_breaks) - 1):
        t_lo = all_breaks[i]
        t_hi = all_breaks[i + 1]
        t_mid = (t_lo + t_hi) / 2

        # Quantile of measure 1 at t_mid
        idx_q1 = np.searchsorted(cdf1, t_mid, side='left')
        idx_q1 = min(idx_q1, len(pos1) - 1)
        q1 = pos1[idx_q1]

        # Quantile of measure 2 at t_mid
        idx_q2 = np.searchsorted(cdf2, t_mid, side='left')
        idx_q2 = min(idx_q2, len(pos2) - 1)
        q2 = pos2[idx_q2]

        dt = t_hi - t_lo
        total += abs(q1 - q2)**p * dt

    return total**(1.0 / p) if p > 0 else total


def wasserstein_shadow(c1: float, c2: float, p: int = 1,
                        max_r: int = 15) -> float:
    """Wasserstein-p distance between shadow spectral measures at c1 and c2."""
    pos1, w1 = shadow_spectral_measure(c1, max_r)
    pos2, w2 = shadow_spectral_measure(c2, max_r)

    if len(pos1) == 0 or len(pos2) == 0:
        return float('inf')

    return wasserstein_1d(pos1, w1, pos2, w2, p)


def wasserstein_vs_connes_comparison(c_pairs: List[Tuple[float, float]],
                                      max_r: int = 10) -> Dict[str, List[float]]:
    """Compare Wasserstein and Connes distances for multiple pairs.

    Returns dict with 'connes', 'W1', 'W2', 'euclidean', 'kappa_sector' lists.
    """
    result = {
        'connes': [], 'W1': [], 'W2': [],
        'euclidean': [], 'kappa_sector': [],
    }
    for c1, c2 in c_pairs:
        result['connes'].append(connes_distance_truncated(c1, c2, max_r))
        result['W1'].append(wasserstein_shadow(c1, c2, p=1, max_r=max_r))
        result['W2'].append(wasserstein_shadow(c1, c2, p=2, max_r=max_r))
        result['euclidean'].append(abs(c1 - c2))
        result['kappa_sector'].append(connes_distance_kappa_sector(c1, c2))
    return result


# =========================================================================
# 7. Multi-path convergence and consistency checks
# =========================================================================

def truncation_convergence(c1: float, c2: float,
                            max_r_values: Optional[List[int]] = None) -> Dict[int, float]:
    """Connes distance as function of truncation level max_r.

    Tests numerical convergence: d(c1, c2; max_r) should stabilize.
    Returns dict max_r -> distance.
    """
    if max_r_values is None:
        max_r_values = [2, 3, 4, 5, 6, 8, 10, 12, 15]

    result = {}
    for mr in max_r_values:
        d = connes_distance_truncated(c1, c2, mr, N_sample=100)
        result[mr] = d
    return result


def distance_triangle_inequality_check(c1: float, c2: float, c3: float,
                                         max_r: int = 8) -> Tuple[bool, float]:
    """Verify the triangle inequality: d(c1, c3) <= d(c1, c2) + d(c2, c3).

    Returns (satisfies, slack) where slack = d(c1,c2) + d(c2,c3) - d(c1,c3).
    """
    d12 = connes_distance_truncated(c1, c2, max_r)
    d23 = connes_distance_truncated(c2, c3, max_r)
    d13 = connes_distance_truncated(c1, c3, max_r)
    slack = d12 + d23 - d13
    return slack >= -1e-10, slack


def distance_symmetry_check(c1: float, c2: float, max_r: int = 8) -> float:
    """Check symmetry: |d(c1, c2) - d(c2, c1)|. Should be 0."""
    d12 = connes_distance_truncated(c1, c2, max_r)
    d21 = connes_distance_truncated(c2, c1, max_r)
    return abs(d12 - d21)


def koszul_symmetry_check(c_val: float, max_r: int = 8) -> float:
    """Check Koszul symmetry: d(c, 13) should equal d(26-c, 13).

    By the Koszul involution c -> 26-c, the distance from c to 13
    should equal the distance from 26-c to 13.
    """
    d1 = connes_distance_truncated(c_val, 13.0, max_r)
    d2 = connes_distance_truncated(26.0 - c_val, 13.0, max_r)
    return abs(d1 - d2)


def multi_path_distance_verification(c1: float, c2: float,
                                       max_r: int = 8) -> Dict[str, float]:
    """Five-path verification of the NC distance between c1 and c2.

    Path 1: Connes formula (geodesic integral)
    Path 2: Lipschitz supremum (direct definition)
    Path 3: Kappa sector (leading approximation)
    Path 4: Wasserstein W1
    Path 5: Truncation-extrapolated value

    For commutative A^sh, paths 1 and 2 should agree.
    """
    d_connes = connes_distance_truncated(c1, c2, max_r)
    d_lipschitz = connes_distance_via_lipschitz(c1, c2, max_r)
    d_kappa = connes_distance_kappa_sector(c1, c2)
    d_W1 = wasserstein_shadow(c1, c2, p=1, max_r=max_r)

    # Extrapolated value from truncation convergence
    conv = truncation_convergence(c1, c2, [4, 6, 8, 10, 12])
    values = list(conv.values())
    d_extrap = values[-1] if values else d_connes  # best available

    return {
        'connes_geodesic': d_connes,
        'lipschitz_sup': d_lipschitz,
        'kappa_sector': d_kappa,
        'wasserstein_W1': d_W1,
        'truncation_extrapolated': d_extrap,
    }


# =========================================================================
# 8. Summary statistics and distance profiles
# =========================================================================

def full_distance_profile(c_val: float, c_range: Optional[List[float]] = None,
                           max_r: int = 8) -> Dict[str, Any]:
    """Full NC distance profile from c_val to all points in c_range.

    Returns dict with keys: 'c_values', 'connes', 'euclidean', 'kappa_sector',
    'metric_tensor', 'curvature'.
    """
    if c_range is None:
        c_range = [float(i) for i in range(1, 26)]

    result = {
        'c_center': c_val,
        'c_values': c_range,
        'connes': [],
        'euclidean': [],
        'kappa_sector': [],
        'metric_tensor': [],
        'curvature': [],
    }
    for cv in c_range:
        result['connes'].append(connes_distance_truncated(c_val, cv, max_r, N_sample=80))
        result['euclidean'].append(abs(c_val - cv))
        result['kappa_sector'].append(connes_distance_kappa_sector(c_val, cv))
        result['metric_tensor'].append(shadow_metric_tensor(cv, max_r))
        result['curvature'].append(nc_metric_curvature(cv, max_r))

    return result


def zero_distance_summary(N: int = 20, max_r: int = 6) -> Dict[str, Any]:
    """Summary of NC distances at zeta zeros.

    Returns dict with:
    - consecutive_spacings: d(rho_n, rho_{n+1}) for n=1..N-1
    - to_self_dual: d(rho_n, 13) for n=1..N
    - to_reflected: d(rho_n, rho_n_bar) for n=1..N
    - kappa_spacings: kappa-sector consecutive spacings
    - normalized_spacings: normalized for GUE comparison
    """
    N_avail = min(N, len(ZETA_ZEROS_GAMMA))

    consec = []
    kappa_consec = []
    for n in range(1, N_avail):
        consec.append(nc_distance_consecutive_zeros(n, max_r))
        gamma_n = ZETA_ZEROS_GAMMA[n - 1]
        gamma_n1 = ZETA_ZEROS_GAMMA[n]
        kappa_consec.append(13.0 * abs(gamma_n1 - gamma_n))

    to_sd = [nc_distance_zero_to_self_dual(n, max_r) for n in range(1, N_avail + 1)]
    to_ref = [nc_distance_zero_to_reflected(n, max_r) for n in range(1, N_avail + 1)]

    consec_arr = np.array(consec)
    mean_spacing = np.mean(consec_arr) if len(consec_arr) > 0 else 1.0
    normalized = consec_arr / mean_spacing if mean_spacing > 1e-15 else consec_arr

    return {
        'consecutive_spacings': consec,
        'kappa_spacings': kappa_consec,
        'to_self_dual': to_sd,
        'to_reflected': to_ref,
        'normalized_spacings': normalized.tolist(),
        'mean_spacing': float(mean_spacing),
    }
