r"""Gaiotto-Witten boundary VOAs and their duality companions.

Boundary conditions of 4d N=4 super-Yang-Mills theory and the
Costello-Gaiotto boundary/corner constructions support vertex operator
algebras.
This engine computes the modular characteristic data for boundary VOAs
and keeps three maps separate:

    physical S-duality of boundary conditions,
    Feigin-Frenkel/Verdier level reflection on verified VOA families,
    free-field chiral Koszul duality.

It is a finite diagnostic surface.  It does not construct the full
holographic package (A, A^i, A^!, C, r(z), Theta_A, nabla^hol), the
full modular Koszul compute package, the full ordered Maurer-Cartan
element Theta_A, or an open-closed/holographic equivalence theorem.

MATHEMATICAL FRAMEWORK
======================

In the Costello-Gaiotto boundary/corner setup this finite engine records:
    - Boundary algebra A on C x {0} (the boundary VOA)
    - A^! only as a Verdier/continuous-linear companion when the
      finite-type or completed hypotheses are explicitly modelled
    - r(z) only as an arity-2 collision kernel / scalar projection

It never identifies Omega(B(A)) = A with Koszul duality, and it never
identifies Z_ch^der(A) = ChirHoch^*(A,A) with the dual branch A^!.

BOUNDARY CONDITIONS AND THEIR VOAs:

1. NEUMANN (N): Preserves gauge field along boundary.
   For gl_N at coupling Psi: boundary VOA is a system of symplectic bosons
   (beta-gamma system) valued in gl_N.
   Central charge: c_N = -N^2 (for Psi -> infinity)
   At finite Psi: affine gl_N at level k = Psi - N (shifted level).

2. DIRICHLET (D): Fixes gauge field to zero on boundary.
   For gl_N: boundary VOA is a system of bc fermions valued in gl_N.
   Central charge: c_D = N^2 (for Psi -> infinity)
   At finite Psi: affine gl_N at level k' = 1/Psi - N (Langlands dual level).

3. NAHM POLE (N_f): Principal Nahm pole boundary condition.
   Boundary VOA = principal W-algebra W_k(gl_N, f_princ).
   This is the DS reduction of the Neumann boundary VOA.
   Class M (infinite shadow depth).

4. REGULAR NAHM: Dirichlet + regular singularity.
   Boundary VOA = small (subregular) W-algebra or related.
   For sl_2: this gives the Virasoro algebra at specific c.

5. CORNER VOA Y_{N_1,N_2,N_3}[Psi] (Gaiotto-Rapcak 1703.00982):
   Three-parameter family. The corner VOA at the junction of three
   half-spaces with gauge groups GL(N_1), GL(N_2), GL(N_3) and
   coupling constant Psi.

   TRIALITY: Y_{N_1,N_2,N_3}[Psi] has an S_3 triality symmetry:
     Y_{N_1,N_2,N_3}[Psi]  =  Y_{N_2,N_3,N_1}[1/Psi]
                             =  Y_{N_3,N_1,N_2}[1-1/Psi]
                             =  Y_{N_2,N_1,N_3}[Psi/(Psi-1)]  etc.

   SPECIALIZATIONS:
     Y_{0,0,N}[Psi] = W_Psi(gl_N) = principal W-algebra of gl_N at level Psi-N
     Y_{0,N,0}[Psi] = affine gl_N at level Psi - N (Neumann)
     Y_{N,0,0}[Psi] = affine gl_N at level 1/Psi - N (Dirichlet)

S-DUALITY, FEIGIN-FRENKEL, AND KOSZUL DUALITY:

S-duality acts on the coupling constant as Psi -> 1/Psi and exchanges
Neumann and Dirichlet boundary conditions. On Y_{N_1,N_2,N_3}[Psi]:

    S: Y_{N_1,N_2,N_3}[Psi] -> Y_{N_2,N_1,N_3}[1/Psi]
       (exchanges first two indices and inverts Psi)

The verified comparison in this engine is negative at finite generic
coupling: physical S-duality and the Feigin-Frenkel/Verdier companion
are distinct maps.  They may agree only in explicitly modelled limits
such as the beta-gamma/bc free-field boundary pair.

The checks below verify:

    (D1) physical S-duality uses the correct target boundary and level,
    (D2) the Feigin-Frenkel level reflection gives the expected kappa sum,
    (D3) corner-VOA S_3 triality is not identified with the FF/Verdier
         companion or the free-field Koszul map.

LEVEL CONVENTIONS:

Following Costello-Gaiotto, the coupling constant Psi parametrizes the
topological twist. The relation to the standard affine level k is:

    k = Psi - h^v    (where h^v = N for gl_N)

The Feigin-Frenkel dual level is:
    k' = -k - 2h^v = -(Psi - N) - 2N = -Psi - N

In terms of Psi: k' = -Psi - N, corresponding to dual coupling:
    Psi' = k' + N = -Psi

But physical S-duality also changes the boundary slot.  For example,
Y_{0,N,0}[Psi] maps to Y_{N,0,0}[1/Psi], whose affine level is still
Psi - N.  The same-family inverted level 1/Psi - N is a different
operation.

The correct chain:
    S-duality: (N1,N2,N3,Psi) -> (N2,N1,N3,1/Psi)
    triality tau: (N1,N2,N3,Psi) -> (N1,N3,N2,1-Psi)
    FF/Verdier: same boundary indices, Psi -> -Psi on verified FF lanes

The Gaiotto-Rapcak S_3 is generated by S-duality and tau.  The
Feigin-Frenkel involution is not itself an S_3 permutation of the
corner indices.

CAUTION (AP1): kappa formulas are family-specific. Never copy between families.
CAUTION (AP8): Virasoro self-dual at c=13; c=26 is a different string-theoretic value.
CAUTION (AP19): r-matrix pole order one below OPE (d log absorption).
CAUTION (AP24): kappa + kappa' = 0 for KM/free; != 0 for W-algebras.
CAUTION (AP33): H_k^! = Sym^ch(V*) != H_{-k} as algebras.
CAUTION (AP39): kappa != c/2 for general VOA; kappa = c/2 only for Virasoro.
CAUTION (AP48): kappa depends on full algebra, not Virasoro subalgebra.

MULTI-PATH VERIFICATION:
    Path 1: Direct kappa computation from the VOA OPE data
    Path 2: DS reduction from parent affine algebra
    Path 3: Complementarity verification (kappa + kappa')
    Path 4: physical S-duality target comparison
    Path 5: Triality consistency (S_3 orbit of kappa values)
    Path 6: Large-N / 't Hooft limit consistency

References:
    Gaiotto-Rapcak, arXiv:1703.00982: Vertex Algebras at the Corner
    Costello-Gaiotto, arXiv:1812.09257: Vertex algebras and 4-manifold invariants
    Costello-Creutzig-Gaiotto, arXiv:1903.02984: Higgs and Coulomb branches from VOAs
    Creutzig-Gaiotto, arXiv:1708.00875: Vertex algebras for S-duality
    Feigin-Gukov, arXiv:1811.09408: VOA[M4]
    Prochazka-Rapcak, arXiv:1711.11408: W-algebra modules
    Beem-Lemos-Liendo-Peelaers-Rastelli-van Rees, arXiv:1312.5344 (BLLPRR)
    Arakawa, arXiv:1212.1theory, arXiv:1507.06197: associated varieties
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction
from typing import Any, Dict, List, Optional, Tuple, Union

from compute.lib.wn_central_charge_canonical import c_wn_fl as canonical_c_wn_fl
from sympy import (
    Rational,
    Symbol,
    cancel,
    expand,
    factor,
    oo,
    simplify,
    sqrt,
)


# =========================================================================
# Core data types
# =========================================================================

Num = Union[int, Fraction, Rational]


def _to_frac(x) -> Fraction:
    """Coerce to Fraction for exact arithmetic."""
    if isinstance(x, Fraction):
        return x
    if isinstance(x, Rational):
        return Fraction(int(x.p), int(x.q))
    if isinstance(x, int):
        return Fraction(x)
    return Fraction(x)


@dataclass(frozen=True)
class VOAParameter:
    """Typed boundary-VOA parameter point."""
    family: str
    boundary_type: str
    rank: int
    coupling: Optional[Fraction]
    level: Optional[Fraction]
    indices: Optional[Tuple[int, int, int]] = None


@dataclass(frozen=True)
class DualityMap:
    """Typed record of a duality map used by this engine."""
    name: str
    kind: str
    source: VOAParameter
    target: VOAParameter
    coupling_formula: str
    level_formula: str
    index_formula: str
    status: str


def _parameter(
    family: str,
    boundary_type: str,
    rank: int,
    coupling: Optional[Num],
    level: Optional[Num],
    indices: Optional[Tuple[int, int, int]] = None,
) -> VOAParameter:
    """Build a parameter point with exact Fraction coordinates."""
    return VOAParameter(
        family=family,
        boundary_type=boundary_type,
        rank=rank,
        coupling=_to_frac(coupling) if coupling is not None else None,
        level=_to_frac(level) if level is not None else None,
        indices=indices,
    )


HOLOGRAPHIC_PACKAGE_ENTRIES: Tuple[str, ...] = (
    "A",
    "A^i",
    "A^!",
    "C",
    "r(z)",
    "Theta_A",
    "nabla^hol",
)

MODULAR_KOSZUL_PROJECTION_ENTRIES: Tuple[str, ...] = (
    "Fact_X(L)",
    "barB_X(L)",
    "Theta_L",
    "L_L",
    "(V_br,T_br)",
    "R4_mod(L)",
)

KERNEL_CONSTANTS: Dict[str, str] = {
    "affine_raw": "k*Omega_tr/z",
    "affine_kz": "Omega/((k+h^vee)z)",
    "heisenberg": "k/z",
    "virasoro": "(c/2)/z^3 + 2T/z",
}

OBJECT_SEPARATION: Dict[str, str] = {
    "A": "boundary VOA algebra",
    "B(A)": "bar coalgebra, not the dual algebra",
    "Omega(B(A))": "bar-cobar inversion recovering A, not Koszul duality",
    "A^i": "bar-dual coalgebra H^*(B(A))",
    "A^!": "Verdier/continuous-linear dual branch under finite-type/completed hypotheses",
    "Z_ch^der(A)": "ChirHoch^*(A,A), the Hochschild bulk, not Koszul dual",
    "r(z)": "arity-2 collision kernel / scalar projection, not full Theta_A",
    "Theta_A": "full ordered convolution Maurer-Cartan element, not computed here",
}


def kernel_constants() -> Dict[str, str]:
    r"""Return the kernel constants used as convention firewalls.

    The constants are recorded as strings because the engine compares
    finite boundary diagnostics, not a symbolic OPE algebra.
    """
    return dict(KERNEL_CONSTANTS)


def boundary_compute_firewall() -> Dict[str, Any]:
    r"""Typed scope firewall for this finite boundary-VOA engine."""
    return {
        "holographic_package_entries": HOLOGRAPHIC_PACKAGE_ENTRIES,
        "modular_koszul_projection_entries": MODULAR_KOSZUL_PROJECTION_ENTRIES,
        "object_separation": dict(OBJECT_SEPARATION),
        "kernel_constants": kernel_constants(),
        "forbidden_promotions": (
            "finite boundary VOA diagnostics do not prove the holographic package",
            "finite OPE/kernel checks do not construct open-closed holography",
            "scalar kappa and r(z) projections do not determine Theta_A",
            "Omega(B(A))=A is bar-cobar inversion, not Koszul duality",
            "Z_ch^der(A)=ChirHoch^*(A,A) is Hochschild bulk, not A^!",
        ),
    }


@dataclass
class BoundaryVOAData:
    """Finite boundary-VOA diagnostic data."""
    name: str
    boundary_type: str          # 'neumann', 'dirichlet', 'nahm_principal',
                                # 'nahm_regular', 'corner'
    gauge_group: str            # e.g. 'gl_N', 'sl_N'
    rank: int                   # N for gl_N / sl_N
    coupling: Optional[Fraction]  # Psi
    level: Optional[Fraction]   # k = Psi - N for affine interpretation

    # VOA data
    central_charge: Fraction
    kappa: Fraction             # modular characteristic
    shadow_class: str           # 'G', 'L', 'C', 'M'
    shadow_depth: Optional[int] # 2, 3, 4, or None (infinite)

    # Duality-companion data
    dual_name: str
    dual_boundary_type: str
    dual_central_charge: Fraction
    dual_kappa: Fraction
    complementarity_sum: Fraction  # kappa + kappa'

    # S-duality data
    s_dual_name: str
    s_dual_coupling: Optional[Fraction]
    s_dual_central_charge: Optional[Fraction]
    s_dual_kappa: Optional[Fraction]

    # Typed duality maps.  The legacy dual_* values above are the target
    # of companion_map; inspect companion_map.kind before interpreting them.
    companion_map: Optional[DualityMap]
    s_duality_map: Optional[DualityMap]
    # Populated only for an explicit free-field Koszul model in this engine.
    # FF/Verdier companions are recorded in companion_map, not promoted here.
    koszul_map: Optional[DualityMap]

    # Verification flags
    companion_equals_s_duality: Optional[bool]


def finite_boundary_diagnostic_scope(data: BoundaryVOAData) -> Dict[str, Any]:
    r"""Return the non-promotion scope attached to a boundary diagnostic."""
    firewall = boundary_compute_firewall()
    return {
        "claim_status": "computed finite boundary VOA diagnostic",
        "constructs_full_holographic_package": False,
        "constructs_open_closed_package": False,
        "constructs_full_theta_A": False,
        "constructs_nabla_hol": False,
        "identifies_bar_cobar_inversion_with_koszul_duality": False,
        "identifies_hochschild_bulk_with_koszul_dual": False,
        "available_maps": {
            "companion": data.companion_map.kind if data.companion_map else None,
            "s_duality": data.s_duality_map.kind if data.s_duality_map else None,
            "koszul": data.koszul_map.kind if data.koszul_map else None,
        },
        "holographic_package_entries": firewall["holographic_package_entries"],
        "modular_koszul_projection_entries": firewall["modular_koszul_projection_entries"],
        "object_separation": firewall["object_separation"],
        "forbidden_promotions": firewall["forbidden_promotions"],
    }


# =========================================================================
# 1. Lie algebra data
# =========================================================================

_LIE_DATA: Dict[Tuple[str, int], Tuple[int, int, str]] = {
    ("A", 1): (3, 2, "sl_2"),
    ("A", 2): (8, 3, "sl_3"),
    ("A", 3): (15, 4, "sl_4"),
    ("A", 4): (24, 5, "sl_5"),
    ("A", 5): (35, 6, "sl_6"),
    ("A", 6): (48, 7, "sl_7"),
    ("A", 7): (63, 8, "sl_8"),
    ("A", 8): (80, 9, "sl_9"),
    ("A", 9): (99, 10, "sl_10"),
}


def _dim_hdual(lie_type: str, rank: int) -> Tuple[int, int]:
    """Return (dim(g), h^vee) for sl_N (= A_{N-1})."""
    key = (lie_type, rank)
    if key in _LIE_DATA:
        d, h, _ = _LIE_DATA[key]
        return d, h
    if lie_type == "A":
        N = rank + 1
        return N * N - 1, N
    raise ValueError(f"Lie algebra ({lie_type}, {rank}) not in table")


def dim_gl(N: int) -> int:
    """Dimension of gl_N = N^2."""
    return N * N


def dim_sl(N: int) -> int:
    """Dimension of sl_N = N^2 - 1."""
    return N * N - 1


# =========================================================================
# 2. Central charge formulas
# =========================================================================

def c_affine_gl(N: int, k: Num) -> Fraction:
    r"""Central charge of affine gl_N at level k.

    gl_N = sl_N + u(1).  The total central charge is:
        c(gl_N, k) = c(sl_N, k) + 1
                    = k*(N^2-1)/(k+N) + 1

    The u(1) factor contributes c = 1 (one free boson = Heisenberg).
    """
    k_f = _to_frac(k)
    N_f = Fraction(N)
    if k_f + N_f == 0:
        raise ValueError(f"Critical level k = -{N}: undefined")
    c_sl = k_f * (N_f**2 - 1) / (k_f + N_f)
    return c_sl + 1


def c_affine_sl(N: int, k: Num) -> Fraction:
    r"""Sugawara central charge of affine sl_N at level k.

    c = k * dim(sl_N) / (k + h^v) = k * (N^2 - 1) / (k + N).
    """
    k_f = _to_frac(k)
    N_f = Fraction(N)
    if k_f + N_f == 0:
        raise ValueError(f"Critical level k = -{N}: undefined")
    return k_f * (N_f**2 - 1) / (k_f + N_f)


def c_wn_principal(N: int, k: Num) -> Fraction:
    r"""Fateev-Lukyanov central charge for principal W^k(sl_N).

    c = (N-1) - N(N^2-1)(k+N-1)^2/(k+N)

    This is the CORRECT formula (verified: c(W_2, k=1) = -7).
    """
    return canonical_c_wn_fl(N, _to_frac(k))


def c_betagamma_system(n_pairs: int, weight: Num = Fraction(1, 2)) -> Fraction:
    r"""Central charge of n_pairs copies of beta-gamma system at weight lambda.

    Each pair: c = 2(6*lambda^2 - 6*lambda + 1).
    At lambda = 1/2 (symplectic bosons): c = -1 per pair.
    At lambda = 0 (standard bg): c = 2 per pair.
    At lambda = 1 (reversed bg): c = 2 per pair.
    """
    lam = _to_frac(weight)
    c_one = 2 * (6 * lam**2 - 6 * lam + 1)
    return Fraction(n_pairs) * c_one


def c_bc_system(n_pairs: int, weight: Num = Fraction(1, 2)) -> Fraction:
    r"""Central charge of n_pairs copies of bc ghost system at weight lambda.

    Each pair: c = -2(6*lambda^2 - 6*lambda + 1).
    At lambda = 1/2: c = 1 per pair.
    At lambda = 1: c = -2 per pair.
    At lambda = 2 (reparametrization ghosts, b weight 2, c weight -1): c = -26 per pair.
    """
    lam = _to_frac(weight)
    c_one = -2 * (6 * lam**2 - 6 * lam + 1)
    return Fraction(n_pairs) * c_one


def c_free_fermion(n: int) -> Fraction:
    r"""Central charge of n free real fermions: c = n/2."""
    return Fraction(n, 2)


# =========================================================================
# 3. kappa formulas (AP1, AP39, AP48: family-specific, never copy)
# =========================================================================

def kappa_affine_gl(N: int, k: Num) -> Fraction:
    r"""Modular characteristic of affine gl_N at level k.

    gl_N = sl_N + u(1).
    kappa(gl_N, k) = kappa(sl_N, k) + kappa(u(1), k)
                   = dim(sl_N) * (k + N) / (2N) + k

    The sl_N part: kappa = dim * (k + h^v) / (2 h^v) with h^v = N.
    The u(1) part: Heisenberg at level k has kappa = k.
    """
    k_f = _to_frac(k)
    N_f = Fraction(N)
    kappa_sl = (N_f**2 - 1) * (k_f + N_f) / (2 * N_f)
    kappa_u1 = k_f
    return kappa_sl + kappa_u1


def kappa_affine_sl(N: int, k: Num) -> Fraction:
    r"""Modular characteristic of affine sl_N at level k.

    kappa = dim(sl_N) * (k + h^v) / (2 * h^v) = (N^2 - 1)(k + N) / (2N).
    """
    k_f = _to_frac(k)
    N_f = Fraction(N)
    return (N_f**2 - 1) * (k_f + N_f) / (2 * N_f)


def kappa_wn_principal(N: int, k: Num) -> Fraction:
    r"""Modular characteristic of principal W^k(sl_N).

    kappa(W_N) = c * (H_N - 1)  where H_N = 1 + 1/2 + ... + 1/N.

    CAUTION (AP39): kappa != c/2 for W-algebras of rank > 1.
    kappa = c/2 only for N = 2 (Virasoro).
    """
    H_N = sum(Fraction(1, j) for j in range(1, N + 1))
    c = c_wn_principal(N, k)
    return c * (H_N - 1)


def kappa_betagamma(n_pairs: int, weight: Num = Fraction(1, 2)) -> Fraction:
    r"""Modular characteristic of n_pairs beta-gamma systems.

    Per pair: kappa = c/2 = 6*lambda^2 - 6*lambda + 1.
    Total: kappa = n_pairs * (6*lambda^2 - 6*lambda + 1).

    At lambda = 1/2 (symplectic bosons): kappa = -1/2 per pair.
    """
    lam = _to_frac(weight)
    kappa_one = 6 * lam**2 - 6 * lam + 1
    return Fraction(n_pairs) * kappa_one


def kappa_bc_ghost(n_pairs: int, weight: Num = Fraction(1, 2)) -> Fraction:
    r"""Modular characteristic of n_pairs bc ghost systems.

    Per pair: kappa = c/2 = -(6*lambda^2 - 6*lambda + 1).
    Complementarity: kappa_bg + kappa_bc = 0 (exact, AP24 safe).
    """
    return -kappa_betagamma(n_pairs, weight)


def kappa_heisenberg(k: Num) -> Fraction:
    r"""Modular characteristic of Heisenberg at level k: kappa = k."""
    return _to_frac(k)


def kappa_virasoro(c: Num) -> Fraction:
    r"""Modular characteristic of Virasoro at central charge c: kappa = c/2."""
    return _to_frac(c) / 2


# =========================================================================
# 4. Shadow depth classification
# =========================================================================

def shadow_class_affine(N: int) -> str:
    """Affine KM algebras are class L (depth 3) for N >= 2.
    Single boson (N=1, Heisenberg): class G (depth 2).
    """
    return 'G' if N <= 1 else 'L'


def shadow_class_betagamma() -> str:
    """Beta-gamma system is class C (depth 4, contact/quartic)."""
    return 'C'


def shadow_class_bc() -> str:
    """bc ghost system is class C (depth 4, contact/quartic)."""
    return 'C'


def shadow_class_w_algebra(N: int) -> str:
    """Principal W-algebra W_N is class M (infinite depth) for N >= 2."""
    return 'M'


def shadow_depth_from_class(cls: str) -> Optional[int]:
    """Convert shadow class to depth. None = infinite."""
    return {'G': 2, 'L': 3, 'C': 4, 'M': None}.get(cls)


def _affine_s_duality_map(
    N: int,
    psi: Fraction,
    source_boundary: str,
    target_boundary: str,
    source_level: Fraction,
    target_level: Fraction,
) -> DualityMap:
    """Physical GL(N) S-duality with the boundary slot included."""
    psi_s = Fraction(1) / psi
    return DualityMap(
        name="physical S-duality",
        kind="physical_s_duality",
        source=_parameter("affine_gl", source_boundary, N, psi, source_level),
        target=_parameter("affine_gl", target_boundary, N, psi_s, target_level),
        coupling_formula="Psi -> 1/Psi",
        level_formula=(
            "Neumann(Psi) -> Dirichlet(1/Psi) has level Psi-N; "
            "Dirichlet(Psi) -> Neumann(1/Psi) has level 1/Psi-N"
        ),
        index_formula="GL(N) rank fixed",
        status="exact for the single-boundary affine specializations",
    )


def _ff_level_map(
    family: str,
    boundary_type: str,
    N: int,
    psi: Fraction,
    k: Fraction,
    k_ff: Fraction,
    *,
    indices: Optional[Tuple[int, int, int]] = None,
    target_coupling: Optional[Fraction] = None,
    status: str = "exact on this verified Feigin-Frenkel lane",
) -> DualityMap:
    """Feigin-Frenkel/Verdier level reflection at fixed boundary indices."""
    return DualityMap(
        name="Feigin-Frenkel/Verdier companion",
        kind="verdier_feigin_frenkel",
        source=_parameter(family, boundary_type, N, psi, k, indices),
        target=_parameter(
            family,
            boundary_type,
            N,
            target_coupling if target_coupling is not None else -psi,
            k_ff,
            indices,
        ),
        coupling_formula="Psi -> -Psi on the convention k = Psi - h^vee",
        level_formula="k -> -k - 2h^vee",
        index_formula="boundary indices fixed",
        status=status,
    )


def _free_field_koszul_map(
    family: str,
    target_family: str,
    source_boundary: str,
    target_boundary: str,
    N: int,
) -> DualityMap:
    """Free-field beta-gamma/bc Koszul map."""
    return DualityMap(
        name="free-field chiral Koszul duality",
        kind="free_field_koszul",
        source=_parameter(family, source_boundary, N, None, None),
        target=_parameter(target_family, target_boundary, N, None, None),
        coupling_formula="strong/weak boundary limit",
        level_formula="no affine level; weight lambda=1/2",
        index_formula="N^2 beta-gamma pairs <-> N^2 bc pairs",
        status="exact for the free-field boundary limit",
    )


# =========================================================================
# 5. Neumann boundary VOA
# =========================================================================

def neumann_boundary_voa(N: int, psi: Num) -> BoundaryVOAData:
    r"""Neumann boundary VOA for GL(N) at coupling Psi.

    The Neumann boundary condition for GL(N) Chern-Simons at coupling Psi
    supports the affine gl_N algebra at level k = Psi - N.

    At generic Psi, this is an affine VOA (class L for N >= 2).

    The physical S-dual is the Dirichlet boundary at coupling 1/Psi.
    In the Y-algebra specialization this target has affine level
    1/(1/Psi) - N = Psi - N, not 1/Psi - N.

    The FF/Verdier companion on this affine lane is realized by the
    Feigin-Frenkel level reflection k' = -k - 2N.

    IMPORTANT DISTINCTION:
    S-duality: Neumann(Psi) -> Dirichlet(1/Psi), giving k^S = Psi - N
    FF-duality: k -> -k - 2N, giving k^FF = -(Psi - N) - 2N = -Psi - N

    These are different operations at every finite nonzero Psi in this
    affine boundary model.
    """
    psi_f = _to_frac(psi)
    k = psi_f - N

    # VOA data
    c = c_affine_gl(N, k)
    kap = kappa_affine_gl(N, k)
    sc = shadow_class_affine(N)
    sd = shadow_depth_from_class(sc)

    # FF/Verdier companion realized by Feigin-Frenkel level reflection.
    k_ff = -k - 2 * N
    c_dual = c_affine_gl(N, k_ff)
    kap_dual = kappa_affine_gl(N, k_ff)

    # Complementarity sum
    comp_sum = kap + kap_dual

    # S-dual: Dirichlet at coupling 1/Psi.  Since the Dirichlet
    # specialization has level 1/Phi - N, Phi = 1/Psi gives level Psi - N.
    psi_s = Fraction(1, 1) / psi_f if psi_f != 0 else None
    k_s = Fraction(1, 1) / psi_s - N if psi_s is not None else None
    c_s = c_affine_gl(N, k_s) if k_s is not None else None
    kap_s = kappa_affine_gl(N, k_s) if k_s is not None else None

    companion_map = _ff_level_map("affine_gl", "neumann", N, psi_f, k, k_ff)
    s_map = (
        _affine_s_duality_map(N, psi_f, "neumann", "dirichlet", k, k_s)
        if k_s is not None else None
    )
    companion_eq_s = (kap_dual == kap_s) if kap_s is not None else None

    return BoundaryVOAData(
        name=f"V_{{Psi={psi_f}}}(gl_{N}) [Neumann]",
        boundary_type='neumann',
        gauge_group=f'gl_{N}',
        rank=N,
        coupling=psi_f,
        level=k,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"V_{{k'={k_ff}}}(gl_{N}) [FF/Verdier companion]",
        dual_boundary_type='neumann',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"V_{{k={k_s}}}(gl_{N}) [Dirichlet at Psi={psi_s}]",
        s_dual_coupling=psi_s,
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=None,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 6. Dirichlet boundary VOA
# =========================================================================

def dirichlet_boundary_voa(N: int, psi: Num) -> BoundaryVOAData:
    r"""Dirichlet boundary VOA for GL(N) at coupling Psi.

    The Dirichlet boundary condition supports the affine gl_N algebra
    at level k = 1/Psi - N (the Langlands dual level).

    The physical S-dual is the Neumann boundary at coupling 1/Psi, whose
    affine level is again 1/Psi - N.
    """
    psi_f = _to_frac(psi)
    if psi_f == 0:
        raise ValueError("Psi = 0: Dirichlet level diverges")
    k = Fraction(1, 1) / psi_f - N

    c = c_affine_gl(N, k)
    kap = kappa_affine_gl(N, k)
    sc = shadow_class_affine(N)
    sd = shadow_depth_from_class(sc)

    # FF/Verdier companion realized by Feigin-Frenkel level reflection.
    k_ff = -k - 2 * N
    c_dual = c_affine_gl(N, k_ff)
    kap_dual = kappa_affine_gl(N, k_ff)
    comp_sum = kap + kap_dual

    # S-dual: Neumann at coupling 1/Psi.
    psi_s = Fraction(1, 1) / psi_f
    k_s = psi_s - N
    c_s = c_affine_gl(N, k_s)
    kap_s = kappa_affine_gl(N, k_s)

    companion_map = _ff_level_map("affine_gl", "dirichlet", N, psi_f, k, k_ff)
    s_map = _affine_s_duality_map(N, psi_f, "dirichlet", "neumann", k, k_s)
    companion_eq_s = (kap_dual == kap_s)

    return BoundaryVOAData(
        name=f"V_{{k={k}}}(gl_{N}) [Dirichlet]",
        boundary_type='dirichlet',
        gauge_group=f'gl_{N}',
        rank=N,
        coupling=psi_f,
        level=k,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"V_{{k'={k_ff}}}(gl_{N}) [FF/Verdier companion]",
        dual_boundary_type='dirichlet',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"V_{{Psi={psi_s}}}(gl_{N}) [Neumann/S-dual]",
        s_dual_coupling=psi_s,
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=None,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 7. Nahm pole (principal W-algebra) boundary VOA
# =========================================================================

def nahm_principal_boundary_voa(N: int, psi: Num) -> BoundaryVOAData:
    r"""Principal Nahm pole boundary VOA: W^k(sl_N, f_princ).

    The Nahm pole boundary condition with principal embedding f_princ: sl_2 -> sl_N
    supports the principal W-algebra at level k = Psi - N.

    The FF/Verdier companion on the principal W lane is
    W^{k'}(sl_N, f_princ) at the Feigin-Frenkel dual level
    k' = -k - 2N. The complementarity sum kappa + kappa' is constant.

    The same-boundary coupling-inversion proxy gives Psi -> 1/Psi, hence
    level k^S = 1/Psi - N.
    FF-duality gives k -> -k - 2N = -(Psi - N) - 2N = -Psi - N.
    """
    psi_f = _to_frac(psi)
    k = psi_f - N

    c = c_wn_principal(N, k)
    kap = kappa_wn_principal(N, k)
    sc = shadow_class_w_algebra(N)
    sd = shadow_depth_from_class(sc)

    # FF/Verdier companion: FF level
    k_ff = -k - 2 * N
    c_dual = c_wn_principal(N, k_ff)
    kap_dual = kappa_wn_principal(N, k_ff)
    comp_sum = kap + kap_dual

    # Same-boundary coupling-inversion proxy.
    psi_s = Fraction(1, 1) / psi_f if psi_f != 0 else None
    if psi_s is not None:
        k_s = psi_s - N
        c_s = c_wn_principal(N, k_s)
        kap_s = kappa_wn_principal(N, k_s)
    else:
        k_s, c_s, kap_s = None, None, None

    companion_map = _ff_level_map("principal_w", "nahm_principal", N, psi_f, k, k_ff)
    s_map = (
        DualityMap(
            name="principal Nahm coupling inversion",
            kind="same_boundary_coupling_inversion",
            source=_parameter("principal_w", "nahm_principal", N, psi_f, k),
            target=_parameter("principal_w", "nahm_principal", N, psi_s, k_s),
            coupling_formula="Psi -> 1/Psi",
            level_formula="k = Psi - N -> 1/Psi - N",
            index_formula="principal embedding fixed",
            status="computational proxy for the principal W-family parameter map",
        )
        if psi_s is not None else None
    )
    companion_eq_s = (kap_dual == kap_s) if kap_s is not None else None

    return BoundaryVOAData(
        name=f"W^{{k={k}}}(sl_{N}) [Nahm principal]",
        boundary_type='nahm_principal',
        gauge_group=f'sl_{N}',
        rank=N,
        coupling=psi_f,
        level=k,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"W^{{k'={k_ff}}}(sl_{N}) [FF/Verdier companion]",
        dual_boundary_type='nahm_principal',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"W^{{k^S}}(sl_{N}) [Nahm at 1/Psi]",
        s_dual_coupling=psi_s,
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=None,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 8. Symplectic boson boundary VOA (Neumann at Psi -> infinity)
# =========================================================================

def symplectic_boson_boundary_voa(N: int) -> BoundaryVOAData:
    r"""Symplectic boson (beta-gamma) boundary VOA.

    In the limit Psi -> infinity, the Neumann boundary condition gives
    N^2 symplectic bosons (beta-gamma pairs at weight 1/2).

    Central charge: c = -N^2 (each symplectic boson contributes c = -1).
    kappa = -N^2/2.
    Shadow class: C (contact/quartic, depth 4).

    Free-field chiral Koszul dual: N^2 bc ghosts at weight 1/2.
    c_dual = N^2, kappa_dual = N^2/2.
    Complementarity: kappa + kappa' = 0 (free field).

    S-dual (Psi -> 0): Dirichlet limit, free fermions.
    """
    n_pairs = N * N

    c = c_betagamma_system(n_pairs, Fraction(1, 2))
    kap = kappa_betagamma(n_pairs, Fraction(1, 2))
    sc = shadow_class_betagamma()
    sd = shadow_depth_from_class(sc)

    # Free-field chiral Koszul dual: bc ghosts
    c_dual = c_bc_system(n_pairs, Fraction(1, 2))
    kap_dual = kappa_bc_ghost(n_pairs, Fraction(1, 2))
    comp_sum = kap + kap_dual

    # S-dual: N^2 free fermions (bc at weight 1/2 = free fermion)
    c_s = c_dual  # bc at weight 1/2 has c = 1 per pair = N^2
    kap_s = kap_dual

    companion_map = _free_field_koszul_map(
        "beta_gamma", "bc_ghost", "neumann", "dirichlet", N
    )
    s_map = DualityMap(
        name="free-field S-duality limit",
        kind="physical_s_duality_limit",
        source=_parameter("beta_gamma", "neumann", N, None, None),
        target=_parameter("bc_ghost", "dirichlet", N, Fraction(0), None),
        coupling_formula="Psi = infinity -> 0",
        level_formula="no affine level in the free-field limit",
        index_formula="N^2 beta-gamma pairs -> N^2 bc pairs",
        status="exact boundary free-field limit",
    )
    companion_eq_s = (kap_dual == kap_s)

    return BoundaryVOAData(
        name=f"{n_pairs} symplectic bosons (bg, lambda=1/2) [Neumann limit]",
        boundary_type='neumann',
        gauge_group=f'gl_{N}',
        rank=N,
        coupling=None,
        level=None,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"{n_pairs} bc ghosts (lambda=1/2) [Koszul dual]",
        dual_boundary_type='dirichlet',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"{n_pairs} bc ghosts (lambda=1/2) [Dirichlet limit]",
        s_dual_coupling=Fraction(0),
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=companion_map,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 9. Free fermion boundary VOA (Dirichlet at Psi -> infinity)
# =========================================================================

def free_fermion_boundary_voa(N: int) -> BoundaryVOAData:
    r"""Free fermion (bc ghost) boundary VOA.

    In the Dirichlet limit, the boundary VOA consists of N^2 bc fermion pairs
    at weight 1/2.

    Central charge: c = N^2 (each bc pair at lambda=1/2 contributes c = 1).
    kappa = N^2/2.
    Shadow class: C (contact/quartic, depth 4).

    Free-field chiral Koszul dual: N^2 symplectic bosons.
    S-dual: Neumann limit -> symplectic bosons.
    """
    n_pairs = N * N

    c = c_bc_system(n_pairs, Fraction(1, 2))
    kap = kappa_bc_ghost(n_pairs, Fraction(1, 2))
    sc = shadow_class_bc()
    sd = shadow_depth_from_class(sc)

    # Free-field chiral Koszul dual: bg
    c_dual = c_betagamma_system(n_pairs, Fraction(1, 2))
    kap_dual = kappa_betagamma(n_pairs, Fraction(1, 2))
    comp_sum = kap + kap_dual

    # S-dual: symplectic bosons
    c_s = c_dual
    kap_s = kap_dual

    companion_map = _free_field_koszul_map(
        "bc_ghost", "beta_gamma", "dirichlet", "neumann", N
    )
    s_map = DualityMap(
        name="free-field S-duality limit",
        kind="physical_s_duality_limit",
        source=_parameter("bc_ghost", "dirichlet", N, None, None),
        target=_parameter("beta_gamma", "neumann", N, None, None),
        coupling_formula="Dirichlet free-field limit -> Neumann free-field limit",
        level_formula="no affine level in the free-field limit",
        index_formula="N^2 bc pairs -> N^2 beta-gamma pairs",
        status="exact boundary free-field limit",
    )
    companion_eq_s = (kap_dual == kap_s)

    return BoundaryVOAData(
        name=f"{n_pairs} bc fermions (lambda=1/2) [Dirichlet limit]",
        boundary_type='dirichlet',
        gauge_group=f'gl_{N}',
        rank=N,
        coupling=None,
        level=None,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"{n_pairs} symplectic bosons [Koszul dual]",
        dual_boundary_type='neumann',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"{n_pairs} symplectic bosons [Neumann limit]",
        s_dual_coupling=None,
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=companion_map,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 10. Corner VOA Y_{N1,N2,N3}[Psi]
# =========================================================================

def corner_voa_central_charge(N1: int, N2: int, N3: int, psi: Num) -> Fraction:
    r"""Central charge of the corner VOA Y_{N1,N2,N3}[Psi].

    SPECIALIZATIONS (exact, verified):
      Y_{0,0,N}[Psi] = W_{Psi}(gl_N):
        c = c(W^{Psi-N}(sl_N)) + 1  (the +1 is the u(1) Heisenberg)
      Y_{0,N,0}[Psi] = affine gl_N at level Psi - N:
        c = c(sl_N, Psi-N) + 1
      Y_{N,0,0}[Psi] = affine gl_N at level 1/Psi - N:
        c = c(sl_N, 1/Psi - N) + 1

    GENERAL TRIPLES: use the Prochazka-Rapcak formula from the W_{1+inf}
    free field realization. The Omega-background parameters are
    epsilon_1 = 1, epsilon_2 = -Psi, epsilon_3 = Psi - 1 (summing to 0).
    The formula (Prochazka-Rapcak arXiv:1711.11408, Gaiotto-Rapcak
    arXiv:1703.00982) for general triples is given by specialization
    recursion from the single-index cases combined with the triality
    covariance.

    For two-index cases Y_{N1,N2,0}[Psi], Y_{N1,0,N3}[Psi], Y_{0,N2,N3}[Psi],
    the algebra is a coset / extension of affine algebras.
    """
    psi_f = _to_frac(psi)
    if psi_f == 0:
        raise ValueError("Psi = 0: corner VOA undefined")

    # ---- Single-index specializations (exact) ----

    # Y_{0,0,N}[Psi] = W_Psi(gl_N)
    if N1 == 0 and N2 == 0 and N3 >= 0:
        if N3 == 0:
            return Fraction(0)
        k = psi_f - N3
        return c_wn_principal(N3, k) + Fraction(1)

    # Y_{0,N,0}[Psi] = affine gl_N at level Psi - N
    if N1 == 0 and N3 == 0 and N2 >= 0:
        if N2 == 0:
            return Fraction(0)
        k = psi_f - N2
        return c_affine_gl(N2, k)

    # Y_{N,0,0}[Psi] = affine gl_N at level 1/Psi - N
    if N2 == 0 and N3 == 0 and N1 >= 0:
        if N1 == 0:
            return Fraction(0)
        k = Fraction(1) / psi_f - N1
        return c_affine_gl(N1, k)

    # ---- General triples: use the triality-covariant formula ----
    # From Prochazka-Rapcak, the central charge can be computed by
    # summing contributions from each "corner" in the brane diagram.
    # For Y_{N1,N2,N3}[Psi], the effective formula decomposes into
    # three single-index contributions minus overlap corrections.
    #
    # The Gaberdiel-Li-Peng cubic formula uses
    #   epsilon_1 = 1, epsilon_2 = -Psi, epsilon_3 = Psi - 1
    # and gives the central charge as:
    #
    #   c = (N_tot - 1) - sum_a epsilon_a N_a (N_a^2 - 1) / (3 * prod_b epsilon_b)
    #       + cross terms
    #
    # For the EXACT formula we need the full W_{1+inf}[lambda] character theory.
    # Since this is complex and error-prone, we implement it using the identity:
    #
    #   c(Y_{N1,N2,N3}[Psi]) = c_Y(epsilon_1, epsilon_2, epsilon_3, N1, N2, N3)
    #
    # where c_Y is defined recursively by the box-adding/removing operations
    # in the plane partition model.
    #
    # For COMPUTATIONAL PURPOSES in this engine, we use the following
    # APPROXIMATE formula for general triples, with a flag that it requires
    # independent verification:
    #
    # c ~ sum of single-index contributions - corrections
    # This is flagged as approximate below.

    # Two-index cases: reduce via coset / extension
    if N3 == 0:
        # Y_{N1,N2,0}[Psi]: coset of gl_{N1} x gl_{N2} algebras
        k1 = Fraction(1) / psi_f - N1
        k2 = psi_f - N2
        return c_affine_gl(N1, k1) + c_affine_gl(N2, k2)

    if N2 == 0:
        # Y_{N1,0,N3}[Psi]: combination of affine and W-algebra
        k1 = Fraction(1) / psi_f - N1
        k3 = psi_f - N3
        return c_affine_gl(N1, k1) + c_wn_principal(N3, k3) + Fraction(1)

    if N1 == 0:
        # Y_{0,N2,N3}[Psi]: combination of affine and W-algebra
        k2 = psi_f - N2
        k3 = psi_f - N3
        return c_affine_gl(N2, k2) + c_wn_principal(N3, k3) + Fraction(1)

    # Full triple: sum all three single-index contributions.
    # This is an APPROXIMATION for the general case.
    # The exact formula requires the full Prochazka-Rapcak box model.
    k1 = Fraction(1) / psi_f - N1
    k2 = psi_f - N2
    k3 = psi_f - N3
    return (c_affine_gl(N1, k1)
            + c_affine_gl(N2, k2)
            + c_wn_principal(N3, k3)
            + Fraction(1))


def corner_voa_kappa(N1: int, N2: int, N3: int, psi: Num) -> Fraction:
    r"""Modular characteristic of corner VOA Y_{N1,N2,N3}[Psi].

    For the corner VOA, which is generically a truncation of W_{1+inf},
    the modular characteristic depends on the specific truncation.

    For Y_{0,0,N}[Psi] = W_Psi(gl_N), we use:
        kappa = kappa(W_N) + kappa(u(1))

    For general triples, we use:
        kappa = c/2 for rank-1 truncations (where the W-algebra is Virasoro-like)
        kappa = c * rho_eff for higher-rank truncations

    CAUTION (AP39, AP48): kappa != c/2 in general.

    For the purposes of this engine, we compute kappa from the anomaly ratio
    of the W_{1+inf} truncation. The anomaly ratio rho for the Y-algebra
    depends on the generator content.

    SIMPLE CASES (verified independently):
      Y_{0,0,N}[Psi]: kappa = kappa(W^{Psi-N}(sl_N)) + (Psi - N)
                       = c_{W_N} * (H_N - 1) + (Psi - N)
      Y_{0,N,0}[Psi]: kappa = kappa(gl_N, Psi-N) = (N^2-1)(Psi)/(2N) + (Psi-N)
      Y_{N,0,0}[Psi]: kappa = kappa(gl_N, 1/Psi-N)

    GENERAL CASE: For the W_{1+inf} truncation Y_{N1,N2,N3}[Psi],
    the algebra has generators of spins 1, 2, ..., max(N1,N2,N3).
    The anomaly ratio involves the harmonic number of the truncation level.

    We use the following DERIVED formula for kappa:
    For Y_{N1,N2,N3}[Psi], define the effective rank r = max(N1,N2,N3).
    Then kappa = c * (H_r - 1) where H_r is the r-th harmonic number,
    PLUS a correction from the u(1) sector.

    This formula is verified only for the specializations stated below.
    For triples where multiple N_a > 0, the generator spectrum is more
    complex and the simple H_r formula may fail.

    For now, we compute kappa ONLY for the specializations Y_{0,0,N},
    Y_{0,N,0}, Y_{N,0,0} where the answer is known, and flag general
    triples as requiring case-by-case analysis.
    """
    psi_f = _to_frac(psi)

    # Specialization: Y_{0,0,N}[Psi] = W_Psi(gl_N)
    if N1 == 0 and N2 == 0 and N3 > 0:
        k = psi_f - N3
        return kappa_wn_principal(N3, k) + kappa_heisenberg(k)

    # Specialization: Y_{0,N,0}[Psi] = affine gl_N at level Psi - N
    if N1 == 0 and N3 == 0 and N2 > 0:
        k = psi_f - N2
        return kappa_affine_gl(N2, k)

    # Specialization: Y_{N,0,0}[Psi] = affine gl_N at level 1/Psi - N
    if N2 == 0 and N3 == 0 and N1 > 0:
        if psi_f == 0:
            raise ValueError("Psi = 0: undefined")
        k = Fraction(1) / psi_f - N1
        return kappa_affine_gl(N1, k)

    # General case: use c/2 as a LOWER BOUND / first approximation.
    # Flag that this needs case-by-case verification (AP39).
    c = corner_voa_central_charge(N1, N2, N3, psi_f)

    # For a general W_{1+inf} truncation, the effective rank is
    # min(N1,N2,N3,...) where the algebra has generators at spins
    # 1 through max(N_a). The anomaly ratio generalizes H_r - 1.
    # For now, use c/2 and flag.
    return c / 2  # APPROXIMATE: valid only when all generators have weight 2


def corner_voa_shadow_class(N1: int, N2: int, N3: int) -> str:
    r"""Shadow depth class of corner VOA Y_{N1,N2,N3}.

    - If max(N_a) == 1: single boson, class G
    - If max(N_a) == 2 and all nonzero N_a == 1: affine, class L
    - If any N_a >= 2 and the truncation has weight >= 3 generators: class M
    - Symplectic boson / bc limit: class C
    """
    m = max(N1, N2, N3)
    if m <= 1:
        return 'G'

    # Y_{0,0,N} for N >= 2: W-algebra, class M
    # Y_{0,N,0} for N >= 2: affine, class L
    # Y_{N,0,0} for N >= 2: affine, class L
    n_nonzero = sum(1 for n in [N1, N2, N3] if n > 0)
    if n_nonzero == 1:
        # Single nonzero index
        n_val = max(N1, N2, N3)
        idx = [N1, N2, N3].index(n_val)
        if idx == 0:
            # Y_{N,0,0}: affine
            return 'L' if n_val >= 2 else 'G'
        elif idx == 1:
            # Y_{0,N,0}: affine
            return 'L' if n_val >= 2 else 'G'
        else:
            # Y_{0,0,N}: W-algebra
            return 'M' if n_val >= 2 else 'G'

    # Multiple nonzero: generically class M (W-algebra type)
    return 'M'


def _corner_level(N1: int, N2: int, N3: int, psi: Fraction) -> Optional[Fraction]:
    """Affine/DS level for verified single-index corner specializations."""
    if N1 == 0 and N2 == 0 and N3 > 0:
        return psi - N3
    if N1 == 0 and N3 == 0 and N2 > 0:
        return psi - N2
    if N2 == 0 and N3 == 0 and N1 > 0:
        if psi == 0:
            raise ValueError("Psi = 0: undefined")
        return Fraction(1) / psi - N1
    return None


def corner_voa_data(N1: int, N2: int, N3: int, psi: Num) -> BoundaryVOAData:
    r"""Full boundary VOA data for corner VOA Y_{N1,N2,N3}[Psi].

    S-duality acts as: (N1,N2,N3,Psi) -> (N2,N1,N3,1/Psi).
    Feigin-Frenkel companion: same indices, Psi -> -Psi on verified
    single-index FF lanes.

    The comparison tested here:
        A = Y_{N1,N2,N3}[Psi]
        A^S = Y_{N2,N1,N3}[1/Psi]   (S-dual)
        A^FF = Y_{N1,N2,N3}[-Psi]    (same-index FF companion)
        finite diagnostic: kappa(A^FF) == kappa(A^S)?

    For multiple nonzero indices, the FF companion remains a recorded
    parameter map; this engine does not promote it to a proved chiral
    Koszul dual without a case-by-case argument.  For single-index
    specializations, the FF/Verdier companion is still kept in the
    companion slot rather than promoted to a theorem flag.
    """
    psi_f = _to_frac(psi)
    level = _corner_level(N1, N2, N3, psi_f)

    c = corner_voa_central_charge(N1, N2, N3, psi_f)
    kap = corner_voa_kappa(N1, N2, N3, psi_f)
    sc = corner_voa_shadow_class(N1, N2, N3)
    sd = shadow_depth_from_class(sc)

    # S-dual: (N1,N2,N3,Psi) -> (N2,N1,N3,1/Psi)
    psi_s = Fraction(1) / psi_f if psi_f != 0 else None
    if psi_s is not None:
        c_s = corner_voa_central_charge(N2, N1, N3, psi_s)
        kap_s = corner_voa_kappa(N2, N1, N3, psi_s)
        level_s = _corner_level(N2, N1, N3, psi_s)
    else:
        c_s, kap_s, level_s = None, None, None

    # FF companion: same indices, Psi -> -Psi on verified single-index lanes.
    psi_ff = -psi_f
    try:
        c_dual = corner_voa_central_charge(N1, N2, N3, psi_ff)
        kap_dual = corner_voa_kappa(N1, N2, N3, psi_ff)
        level_ff = _corner_level(N1, N2, N3, psi_ff)
    except (ValueError, ZeroDivisionError):
        c_dual = Fraction(0)
        kap_dual = Fraction(0)
        level_ff = None

    comp_sum = kap + kap_dual

    indices = (N1, N2, N3)
    companion_map = DualityMap(
        name="same-index Feigin-Frenkel companion",
        kind="feigin_frenkel_companion",
        source=_parameter("corner_y", "corner", max(N1, N2, N3), psi_f, level, indices),
        target=_parameter("corner_y", "corner", max(N1, N2, N3), psi_ff, level_ff, indices),
        coupling_formula="Psi -> -Psi",
        level_formula="k -> -k - 2N on verified single-index specializations",
        index_formula="(N1,N2,N3) fixed",
        status=(
            "exact for verified single-index FF lanes; case-by-case "
            "obligation for multiple nonzero indices"
        ),
    )
    s_map = (
        DualityMap(
            name="Gaiotto-Rapcak sigma / physical S-duality",
            kind="physical_s_duality",
            source=_parameter("corner_y", "corner", max(N1, N2, N3), psi_f, level, indices),
            target=_parameter(
                "corner_y", "corner", max(N2, N1, N3), psi_s, level_s, (N2, N1, N3)
            ),
            coupling_formula="Psi -> 1/Psi",
            level_formula="computed from the target single-index specialization when defined",
            index_formula="(N1,N2,N3) -> (N2,N1,N3)",
            status="exact Gaiotto-Rapcak sigma on parameter space",
        )
        if psi_s is not None else None
    )
    koszul_map = None
    companion_eq_s = (kap_dual == kap_s) if kap_s is not None else None

    return BoundaryVOAData(
        name=f"Y_{{{N1},{N2},{N3}}}[Psi={psi_f}]",
        boundary_type='corner',
        gauge_group=f'gl_{{max({N1},{N2},{N3})}}',
        rank=max(N1, N2, N3),
        coupling=psi_f,
        level=level,
        central_charge=c,
        kappa=kap,
        shadow_class=sc,
        shadow_depth=sd,
        dual_name=f"Y_{{{N1},{N2},{N3}}}[Psi={psi_ff}] [FF companion]",
        dual_boundary_type='corner',
        dual_central_charge=c_dual,
        dual_kappa=kap_dual,
        complementarity_sum=comp_sum,
        s_dual_name=f"Y_{{{N2},{N1},{N3}}}[Psi={psi_s}] [S-dual]",
        s_dual_coupling=psi_s,
        s_dual_central_charge=c_s,
        s_dual_kappa=kap_s,
        companion_map=companion_map,
        s_duality_map=s_map,
        koszul_map=koszul_map,
        companion_equals_s_duality=companion_eq_s,
    )


# =========================================================================
# 11. Triality verification for corner VOAs
# =========================================================================

def verify_triality(N1: int, N2: int, N3: int, psi: Num) -> Dict[str, Any]:
    r"""Verify the S_3 triality of corner VOA central charges.

    The standard Gaiotto-Rapcak parameter is
    Psi = -epsilon_2/epsilon_1 with epsilon_1 + epsilon_2 + epsilon_3 = 0.
    Permuting the epsilon parameters gives:

      (12): swap epsilon_1 and epsilon_2:
            (N1,N2,N3,Psi) -> (N2,N1,N3,1/Psi).
      (13): swap epsilon_1 and epsilon_3:
            (N1,N2,N3,Psi) -> (N3,N2,N1,Psi/(Psi-1)).
      (23): swap epsilon_2 and epsilon_3:
            (N1,N2,N3,Psi) -> (N1,N3,N2,1-Psi).

    The full S_3 orbit of (N1,N2,N3,Psi):
      id:    (N1, N2, N3, Psi)
      (12):  (N2, N1, N3, 1/Psi)            <-- S-duality
      (23):  (N1, N3, N2, 1-Psi)
      (13):  (N3, N2, N1, Psi/(Psi-1))
      (123): (N2, N3, N1, 1/(1-Psi))
      (132): (N3, N1, N2, (Psi-1)/Psi)

    For exact corner formulas all six central charges agree.  This engine
    reports whether its implemented central-charge formula respects that
    covariance on the requested point.
    """
    psi_f = _to_frac(psi)

    results = {}

    # The six S_3 images
    orbit = [
        ('id',    N1, N2, N3, psi_f),
        ('(12)',  N2, N1, N3, Fraction(1) / psi_f if psi_f != 0 else None),
        ('(23)',  N1, N3, N2, 1 - psi_f if psi_f != 1 else None),
        ('(13)',  N3, N2, N1, psi_f / (psi_f - 1) if psi_f != 1 else None),
        ('(123)', N2, N3, N1, Fraction(1) / (1 - psi_f) if psi_f != 1 else None),
        ('(132)', N3, N1, N2, (psi_f - 1) / psi_f if psi_f != 0 else None),
    ]

    central_charges = []
    for label, n1, n2, n3, p in orbit:
        if p is not None:
            try:
                c_val = corner_voa_central_charge(n1, n2, n3, p)
                central_charges.append((label, c_val))
            except (ValueError, ZeroDivisionError):
                central_charges.append((label, None))
        else:
            central_charges.append((label, None))

    # Check all central charges agree
    valid_ccs = [c for _, c in central_charges if c is not None]
    all_equal = len(set(valid_ccs)) <= 1 if valid_ccs else True

    results['orbit'] = central_charges
    results['parameter_orbit'] = orbit
    results['triality_holds'] = all_equal
    results['distinct_values'] = len(set(valid_ccs)) if valid_ccs else 0

    return results


# =========================================================================
# 12. Physical S-duality versus duality companion comparison
# =========================================================================

def s_duality_companion_comparison(N: int, psi: Num,
                                   boundary_type: str = 'neumann') -> Dict[str, Any]:
    r"""Compare physical S-dual and recorded duality companion.

    For Neumann: A = gl_N at level k = Psi - N.
      S-dual:    Dirichlet at coupling 1/Psi, level k^S = Psi - N.
      FF/Verdier companion:
                 gl_N at level k^FF = -k - 2N = -Psi - N.

    For Dirichlet: A = gl_N at level k = 1/Psi - N.
      S-dual:    Neumann at coupling 1/Psi, level k^S = 1/Psi - N.
      FF/Verdier companion:
                 gl_N at level k^FF = -1/Psi - N.

    For affine gl_N: kappa(k) = (N^2-1)(k+N)/(2N) + k.
    The physical S-dual keeps the affine level attached to the boundary
    condition, while the FF/Verdier companion reflects the shifted level.
    """
    psi_f = _to_frac(psi)

    if boundary_type == 'neumann':
        data = neumann_boundary_voa(N, psi_f)
    elif boundary_type == 'dirichlet':
        data = dirichlet_boundary_voa(N, psi_f)
    elif boundary_type == 'nahm_principal':
        data = nahm_principal_boundary_voa(N, psi_f)
    else:
        raise ValueError(f"Unknown boundary type: {boundary_type}")

    result = {
        'name': data.name,
        'boundary_type': boundary_type,
        'N': N,
        'Psi': psi_f,
        'kappa': data.kappa,
        'kappa_companion': data.dual_kappa,
        'kappa_s_dual': data.s_dual_kappa,
        'companion_equals_s_duality': data.companion_equals_s_duality,
        'companion_kind': data.companion_map.kind if data.companion_map else None,
        'koszul_kind': data.koszul_map.kind if data.koszul_map else None,
        'complementarity_sum': data.complementarity_sum,
        'central_charge': data.central_charge,
        'companion_central_charge': data.dual_central_charge,
        's_dual_central_charge': data.s_dual_central_charge,
        'claim_status': "computed finite boundary VOA diagnostic",
        'scope_firewall': finite_boundary_diagnostic_scope(data),
        'kernel_constants': kernel_constants(),
    }

    # Compute the discrepancy
    if data.s_dual_kappa is not None:
        result['kappa_discrepancy'] = data.dual_kappa - data.s_dual_kappa
    else:
        result['kappa_discrepancy'] = None

    return result


# =========================================================================
# 13. Landscape survey: all boundary VOAs
# =========================================================================

def boundary_voa_landscape(N_max: int = 5) -> List[Dict[str, Any]]:
    r"""Survey all boundary VOA types for GL(N), N = 1, ..., N_max.

    Returns finite diagnostic dictionaries for each boundary condition type.
    """
    results = []

    for N in range(1, N_max + 1):
        # Test at several coupling values
        for psi_num, psi_den in [(3, 1), (2, 1), (5, 2), (1, 2), (1, 3)]:
            psi = Fraction(psi_num, psi_den)

            # Skip degenerate cases
            if psi == 0 or psi == N or psi == 1:
                continue

            try:
                entry = s_duality_companion_comparison(N, psi, 'neumann')
                entry['shadow_class'] = shadow_class_affine(N)
                results.append(entry)
            except (ValueError, ZeroDivisionError):
                pass

            try:
                entry = s_duality_companion_comparison(N, psi, 'dirichlet')
                entry['shadow_class'] = shadow_class_affine(N)
                results.append(entry)
            except (ValueError, ZeroDivisionError):
                pass

            if N >= 2:
                try:
                    entry = s_duality_companion_comparison(N, psi, 'nahm_principal')
                    entry['shadow_class'] = shadow_class_w_algebra(N)
                    results.append(entry)
                except (ValueError, ZeroDivisionError):
                    pass

    return results


# =========================================================================
# 14. Complementarity sum verification
# =========================================================================

def verify_complementarity_affine_gl(N: int, psi: Num) -> Dict[str, Any]:
    r"""Verify that kappa + kappa' is level-independent for affine gl_N.

    For affine algebras: kappa(k) + kappa(-k-2N) should be a constant.
    For sl_N: the sum is 0.
    For gl_N: the sum includes the u(1) contribution.

    kappa(gl_N, k) = (N^2-1)(k+N)/(2N) + k
    kappa(gl_N, -k-2N) = (N^2-1)(-k-2N+N)/(2N) + (-k-2N)
                       = (N^2-1)(-k-N)/(2N) - k - 2N

    Sum = (N^2-1)(k+N)/(2N) + (N^2-1)(-k-N)/(2N) + k + (-k-2N)
        = 0 + (-2N)
        = -2N

    So for gl_N: kappa + kappa' = -2N (level-independent!).
    """
    psi_f = _to_frac(psi)
    k = psi_f - N
    k_ff = -k - 2 * N

    kap = kappa_affine_gl(N, k)
    kap_ff = kappa_affine_gl(N, k_ff)
    total = kap + kap_ff

    expected = Fraction(-2 * N)

    return {
        'N': N,
        'Psi': psi_f,
        'k': k,
        'k_ff': k_ff,
        'kappa': kap,
        'kappa_dual': kap_ff,
        'sum': total,
        'expected': expected,
        'correct': total == expected,
    }


def verify_complementarity_wn(N: int, psi: Num) -> Dict[str, Any]:
    r"""Verify kappa + kappa' for principal W-algebra W^k(sl_N).

    The complementarity sum kappa(W_N,k) + kappa(W_N,-k-2N) is constant.
    For N=2 (Virasoro): sum = 13.
    For N=3 (W_3): sum = 250/3.
    """
    psi_f = _to_frac(psi)
    k = psi_f - N
    k_ff = -k - 2 * N

    kap = kappa_wn_principal(N, k)
    kap_ff = kappa_wn_principal(N, k_ff)
    total = kap + kap_ff

    # Expected from complementarity_landscape.py
    H_N = sum(Fraction(1, j) for j in range(1, N + 1))
    c_sum = Fraction(2 * (N - 1)) + Fraction(4 * N * (N**2 - 1))
    expected = (H_N - 1) * c_sum

    return {
        'N': N,
        'Psi': psi_f,
        'k': k,
        'k_ff': k_ff,
        'kappa': kap,
        'kappa_dual': kap_ff,
        'sum': total,
        'expected': expected,
        'correct': total == expected,
    }


# =========================================================================
# 15. Summary: physical S-duality versus companion diagnosis
# =========================================================================

def diagnose_s_duality_companion_relation() -> Dict[str, Any]:
    r"""Comprehensive diagnosis of the S-duality versus companion question.

    FINDING: physical S-duality and the FF/Verdier companion are different
    operations at finite generic coupling.

    STRUCTURE:
    - S-duality: boundary slot changes and Psi -> 1/Psi.
    - FF/Verdier companion: boundary slot fixed and k -> -k - 2h^v.
    - Free-field chiral Koszul duality: beta-gamma <-> bc at the boundary
      limit; here it agrees with the physical S-dual target.

    For affine gl_N:
      Neumann(Psi) level: k = Psi - N
      physical S-dual level: Dirichlet(1/Psi), k^S = Psi - N
      FF-dual level: k^FF = -k - 2N = -(Psi-N) - 2N = -Psi - N

      k^S = k^FF iff Psi = 0, the singular boundary of this finite-coupling
      affine model.

    ANSWER: NO, generically. But the DISCREPANCY is systematic and
    controlled by the affine kappa formula.

    For Neumann:
      kappa(A^FF) - kappa(A^S)
        = -((N^2 + 2N - 1)/N) * Psi.

    For Dirichlet:
      kappa(A^FF) - kappa(A^S)
        = -((N^2 + 2N - 1)/N) * (1/Psi).

    The Gaiotto-Rapcak S_3 triality is generated by physical S-duality
    sigma and the tau move Psi -> 1 - Psi.  The FF/Verdier same-index
    involution is recorded separately.
    """
    diagnosis = {
        'main_finding': 'physical S-duality != FF/Verdier companion (generically)',
        'coincidence_locus': 'no finite nonzero affine Neumann/Dirichlet coupling',
        'structure': 'S_3 triality = <S-duality sigma, tau>; FF/Verdier is separate',
    }

    # Verify for N = 2, 3 at several Psi values
    examples = []
    for N in [1, 2, 3]:
        for psi_num, psi_den in [(3, 1), (2, 1), (5, 2)]:
            psi = Fraction(psi_num, psi_den)
            try:
                comp = s_duality_companion_comparison(N, psi, 'neumann')
                examples.append(comp)
            except (ValueError, ZeroDivisionError):
                pass

    diagnosis['examples'] = examples

    # Count how many have the recorded companion equal to the physical S-dual.
    n_match = sum(1 for e in examples if e.get('companion_equals_s_duality'))
    n_total = len(examples)
    diagnosis['match_count'] = n_match
    diagnosis['total_count'] = n_total
    diagnosis['match_fraction'] = f"{n_match}/{n_total}"

    return diagnosis


# =========================================================================
# 16. Affine Kac-Moody kappa + kappa' for sl_N
# =========================================================================

def verify_complementarity_affine_sl(N: int, k: Num) -> Dict[str, Any]:
    r"""For sl_N: kappa(k) + kappa(-k-2N) = 0 (exact anti-symmetry)."""
    k_f = _to_frac(k)
    k_ff = -k_f - 2 * N

    kap = kappa_affine_sl(N, k_f)
    kap_ff = kappa_affine_sl(N, k_ff)
    total = kap + kap_ff

    return {
        'N': N,
        'k': k_f,
        'k_ff': k_ff,
        'kappa': kap,
        'kappa_dual': kap_ff,
        'sum': total,
        'correct': total == 0,
    }


# =========================================================================
# 17. BLLPRR boundary VOAs from 4d N=2 SCFTs
# =========================================================================

def bllprr_schur_voa(theory: str, **params) -> Dict[str, Any]:
    r"""Compute scalar boundary diagnostics for the Schur VOA of a 4d N=2 SCFT.

    The BLLPRR correspondence associates a 2d VOA A(T) to every 4d N=2 SCFT T
    via the Schur index: the Schur operators form a 2d chiral algebra.

    Known examples:
      - Free hypermultiplet: A(T) = symplectic boson pair (bg at lambda=1/2)
      - Free vector multiplet: A(T) = bc ghost pair at the conformal point lambda=2
      - SU(2) N_f=4: A(T) = affine so(8) at level -2
      - Argyres-Douglas H_0: A(T) = Virasoro at c = -22/5
      - Argyres-Douglas H_1: A(T) = Virasoro at c = -7 (= W_2 at k=1)
      - Minahan-Nemeschansky E_6: A(T) = affine e_6 at level -3
      - Minahan-Nemeschansky E_7: A(T) = affine e_7 at level -4
      - Minahan-Nemeschansky E_8: A(T) = affine e_8 at level -6

    The central charge of the VOA is:
      c_2d = -12 c_4d
    where c_4d is the Weyl anomaly coefficient of the 4d SCFT.
    """
    if theory == 'free_hyper':
        c = Fraction(-1)  # symplectic boson
        kap = Fraction(-1, 2)
        sc = 'C'
        dual_c = Fraction(1)  # bc at lambda=1/2
        dual_kap = Fraction(1, 2)
        name = "Symplectic boson (free hyper)"

    elif theory == 'free_vector':
        c = Fraction(-26)   # bc ghosts at lambda=2 (reparametrization ghosts)
        kap = Fraction(-13)
        sc = 'C'
        dual_c = Fraction(26)
        dual_kap = Fraction(13)
        name = "bc ghosts lambda=2 (free vector)"

    elif theory == 'argyres_douglas_H0':
        c = Fraction(-22, 5)
        kap = Fraction(-11, 5)
        sc = 'M'
        dual_c = 26 - c  # Virasoro: c' = 26 - c
        dual_kap = dual_c / 2
        name = "Virasoro c=-22/5 (Argyres-Douglas H_0)"

    elif theory == 'argyres_douglas_H1':
        c = Fraction(-7)
        kap = Fraction(-7, 2)
        sc = 'M'
        dual_c = Fraction(33)  # 26 - (-7) = 33
        dual_kap = Fraction(33, 2)
        name = "Virasoro c=-7 (Argyres-Douglas H_1 = W_2 at k=1)"

    elif theory == 'su2_nf4':
        # affine so(8) at level -2
        # dim(so_8) = 28, h^v(D_4) = 6
        # c = k * 28 / (k + 6) = (-2)*28/4 = -14
        # kappa = 28 * (k+6) / (2*6) = 28*4/12 = 28/3
        c = Fraction(-14)
        kap = Fraction(28, 3)
        sc = 'L'
        # FF dual: k' = -k - 2*6 = -(-2) - 12 = 2 - 12 = -10
        k_ff = -(-2) - 12
        dual_c = Fraction(k_ff * 28, k_ff + 6)  # (-10)*28/(-4) = 70
        dual_kap = Fraction(28 * (k_ff + 6), 12)  # 28*(-4)/12 = -28/3
        name = "Affine so(8) at k=-2 (SU(2) N_f=4)"

    elif theory == 'MN_E6':
        # affine e_6 at level -3
        # dim(e_6) = 78, h^v = 12
        # c = (-3)*78/(-3+12) = -234/9 = -26
        # kappa = 78 * (-3+12) / (2*12) = 78*9/24 = 702/24 = 117/4
        c = Fraction(-26)
        kap = Fraction(117, 4)
        sc = 'L'
        k_ff = -(-3) - 24  # = 3 - 24 = -21
        dual_c = Fraction((-21) * 78, -21 + 12)  # = -1638/(-9) = 182
        dual_kap = Fraction(78 * (-21 + 12), 24)  # = 78*(-9)/24 = -702/24 = -117/4
        name = "Affine e_6 at k=-3 (MN E_6)"

    elif theory == 'MN_E7':
        # affine e_7 at level -4
        # dim(e_7) = 133, h^v = 18
        # c = (-4)*133/(-4+18) = -532/14 = -38
        # kappa = 133*(-4+18)/(2*18) = 133*14/36 = 1862/36 = 931/18
        c = Fraction(-38)
        kap = Fraction(931, 18)
        sc = 'L'
        k_ff = -(-4) - 36  # = 4 - 36 = -32
        dual_c = Fraction((-32) * 133, -32 + 18)  # = -4256/(-14) = 304
        dual_kap = Fraction(133 * (-32 + 18), 36)  # = 133*(-14)/36 = -1862/36 = -931/18
        name = "Affine e_7 at k=-4 (MN E_7)"

    elif theory == 'MN_E8':
        # affine e_8 at level -6
        # dim(e_8) = 248, h^v = 30
        # c = (-6)*248/(-6+30) = -1488/24 = -62
        # kappa = 248*(-6+30)/(2*30) = 248*24/60 = 5952/60 = 992/10 = 496/5
        c = Fraction(-62)
        kap = Fraction(496, 5)
        sc = 'L'
        k_ff = -(-6) - 60  # = 6 - 60 = -54
        dual_c = Fraction((-54) * 248, -54 + 30)  # = -13392/(-24) = 558
        dual_kap = Fraction(248 * (-54 + 30), 60)  # = 248*(-24)/60 = -5952/60 = -496/5
        name = "Affine e_8 at k=-6 (MN E_8)"

    else:
        raise ValueError(f"Unknown 4d N=2 theory: {theory}")

    return {
        'name': name,
        'theory': theory,
        'central_charge': c,
        'kappa': kap,
        'shadow_class': sc,
        'dual_central_charge': dual_c,
        'dual_kappa': dual_kap,
        'complementarity_sum': kap + dual_kap,
    }


# =========================================================================
# Self-tests on import
# =========================================================================

# Verify: c(gl_2, k=1) = 1*3/3 + 1 = 2
assert c_affine_gl(2, 1) == Fraction(2), f"c(gl_2, k=1) = {c_affine_gl(2, 1)}"

# Verify: kappa(gl_1, k) = k (Heisenberg)
assert kappa_affine_gl(1, 3) == Fraction(3), f"kappa(gl_1, k=3) = {kappa_affine_gl(1, 3)}"

# Verify: kappa(sl_2, k=1) = 3*3/(2*2) = 9/4
assert kappa_affine_sl(2, 1) == Fraction(9, 4), f"kappa(sl_2, k=1) = {kappa_affine_sl(2, 1)}"

# Verify: c(W_2, k=1) = -7
assert c_wn_principal(2, 1) == Fraction(-7), f"c(W_2, k=1) = {c_wn_principal(2, 1)}"

# Verify: bg at lambda=1/2 has c = -1 per pair
assert c_betagamma_system(1, Fraction(1, 2)) == Fraction(-1)

# Verify: bg + bc complementarity = 0
assert kappa_betagamma(1, Fraction(1, 2)) + kappa_bc_ghost(1, Fraction(1, 2)) == 0

# Verify: corner VOA Y_{0,0,2}[Psi=3] central charge
# Y_{0,0,2}[3] = W^{k=1}(sl_2) + u(1) = Virasoro at c=-7 plus Heisenberg
# c = c(W_2, k=1) + 1 = -7 + 1 = -6
_c_y002_3 = corner_voa_central_charge(0, 0, 2, 3)
assert _c_y002_3 == Fraction(-6), f"c(Y_{{0,0,2}}[3]) = {_c_y002_3}, expected -6"

# Verify: corner VOA Y_{0,2,0}[3] = affine gl_2 at level 1
# c(gl_2, k=1) = 3*1/3 + 1 = 2
_c_y020_3 = corner_voa_central_charge(0, 2, 0, 3)
assert _c_y020_3 == Fraction(2), f"c(Y_{{0,2,0}}[3]) = {_c_y020_3}, expected 2"

# Verify: corner VOA Y_{2,0,0}[3] = affine gl_2 at level 1/3 - 2 = -5/3
# c(sl_2, k=-5/3) = (-5/3)*3 / (-5/3 + 2) = -5 / (1/3) = -15
# c(gl_2) = -15 + 1 = -14
_c_y200_3 = corner_voa_central_charge(2, 0, 0, 3)
assert _c_y200_3 == Fraction(-14), f"c(Y_{{2,0,0}}[3]) = {_c_y200_3}, expected -14"

# Verify: sl_N complementarity: kappa(k) + kappa(-k-2N) = 0
_v = verify_complementarity_affine_sl(2, 1)
assert _v['correct'], f"sl_2 complementarity failed: sum = {_v['sum']}"

# Verify: gl_N complementarity: kappa(k) + kappa(-k-2N) = -2N
_v2 = verify_complementarity_affine_gl(2, 3)
assert _v2['correct'], f"gl_2 complementarity failed: sum = {_v2['sum']}, expected {_v2['expected']}"
