r"""Finite CY-BKM sanity computations for K3 x E.

MATHEMATICAL FRAMEWORK
======================

The BPS spectrum of Type IIA on K3 x E is organized by a Borcherds-Kac-Moody
(BKM) algebra whose denominator function is the Igusa cusp form Phi_{10}.
This module contains a finite, low-order computational model: lattice
arithmetic, K3 elliptic-genus coefficients, signed product exponents, and
sample super root data. It does not recognize the full root system or prove
the denominator identity.

1. THE LATTICE
   The charge lattice for the BKM algebra is II_{1,1} + II_{1,1} = U + U,
   where U is the hyperbolic lattice with Gram matrix ((0,1),(1,0)).
   The full lattice has signature (2,2) and rank 4.

   A vector alpha = (m, n, l, k) in U + U has norm
     alpha^2 = 2mn + 2lk
   (using the convention that each U copy contributes a bilinear form
   (a,b).(c,d) = ad + bc).

   For the BKM algebra, simple roots live in this lattice. The Cartan
   matrix is A_{ij} = 2(alpha_i, alpha_j) / alpha_j^2 (generalized,
   allowing alpha_j^2 <= 0).

2. JACOBI COEFFICIENTS, PRODUCT EXPONENTS, SUPER ROOT DATA
   The finite routines below keep three objects separate.

   Jacobi coefficients:
     phi_{0,1}(tau,z) = sum a(n,l) q^n y^l,
     K3 elliptic genus coefficient = 2*a(n,l).

   Signed Borcherds product exponents:
     Phi_{10} starts as q*y*p times products
       (1 - q^{n0} y^l p^{m0})^{e(n0,l,m0)}.
     The Jacobi coefficient is indexed by N = n0*m0 and l:
       e(n0,l,m0) = 2*a(N,l).
     A negative exponent is a signed product exponent. It is not by
     itself an unsigned root multiplicity.

   Super root multiplicities:
     a super root datum records even and odd dimensions separately.
     Its signed dimension even - odd may agree with a product exponent
     in the toy coefficients used here, but that equality is input data
     for a finite sanity check, not recognition of a BKM root system.

   The hardcoded table in this module is therefore only a finite sample
   of low signed exponents extracted from 2*phi_{0,1}. It does not prove
   a denominator identity, a simple-root classification, or BKM
   recognition.

3. WEYL GROUP
   The Weyl group W is generated by reflections s_alpha for real simple
   roots alpha (those with alpha^2 = 2). In the lattice II_{1,1} + II_{1,1},
   the real roots form a root system of type A_1^2 (two commuting reflections
   when the simple real roots are orthogonal) or a larger system.

   For the II_{1,1} lattice with basis (e, f) where e^2 = f^2 = 0,
   (e,f) = 1, the real roots are alpha = ae + bf with 2ab = 2, so ab = 1,
   meaning (a,b) = (1,1) or (-1,-1). The simple real root is alpha = e + f.
   Its reflection: s(v) = v - (v, alpha)alpha = v - (v, e+f)(e+f).

   For II_{1,1} + II_{1,1} = U + U, the Weyl group is richer.
   It is an infinite group (hyperbolic Coxeter group).

4. PETERSON-KAC RECURSION
   The Peterson-Kac formula computes multiplicities recursively:
     sum_{k>=1} mult(alpha/k)/k * (rho, alpha/k)
       = (1/2) sum_{beta+gamma=alpha, beta,gamma>0} (beta, gamma) mult(beta) mult(gamma)
   where the sum on the right is over positive root decompositions.

   In this finite engine, the routine is only a seeded signed-dimension
   sanity calculation.

5. DENOMINATOR IDENTITY
   The Weyl-Kac-Borcherds denominator identity:
     e^{-rho} sum_{w in W} det(w) w(e^rho * S)
       = prod_{alpha>0} (1 - e^{-alpha})^{mult(alpha)}
   where S = prod_{simple imaginary alpha} (1 - e^{-alpha})^{-mult(alpha)}
   is the "correction factor" from imaginary simple roots.

   For the K3 BKM algebra, this identity is equivalent to the full product
   formula for Phi_{10}. The code below only performs finite low-order
   coefficient checks.

CONVENTIONS (AP38, AP46, AP48)
==============================
  - q = e^{2pi i tau}, y = e^{2pi i z}, p = e^{2pi i sigma}
  - eta(q) = q^{1/24} prod(1-q^n) [AP46: include q^{1/24}]
  - phi_{0,1} = Eichler-Zagier convention: phi_{0,1}(tau,0) = 12
  - K3 elliptic genus = 2*phi_{0,1}, so at z=0: 24 = chi(K3)
  - kappa(K3 sigma model) = 2 (complex dimension)
  - K3 x E has four distinct kappa lanes:
      kappa_cat(K3 x E) = chi(O_{K3 x E}) = 0,
      kappa_ch^{Heis}(K3 x E) = dim_C(K3 x E) = 3,
      kappa_BKM(Delta_5) = wt(Delta_5) = 5,
      kappa_fiber(K3) = rank H^*(K3) = 24.
    These are not aliases.
  - Root norm: alpha^2 = 2n means the Mukai/intersection form gives 2n.
  - Weyl vector: rho with (rho, alpha_i) = alpha_i^2 / 2 for simple alpha_i.
  - Igusa normalisation:
      D_5 = 64^{-1} Delta_5,
      Phi_{10}^{un} = Delta_5^2,
      Phi_{10}^{OP} = D_5^2 = 4096^{-1} Delta_5^2,
      Z_{OP/DT} = -D_5^{-2} = -4096 Delta_5^{-2}.

FINITE SANITY CHECKS
====================
  Path A: Direct lattice arithmetic
  Path B: Finite Peterson-Kac-style seeded recursion
  Path C: Truncated Borcherds product expansion
  Path D: K3 elliptic-genus coefficient extraction
  Path E: Shadow tower scalar checks (kappa, F_g)
  Path F: Leading Phi_{10} coefficient checks

References:
  Borcherds (1995): "Automorphic forms on O_{s+2,2}(R) and infinite products"
  Gritsenko-Nikulin (1996): "Automorphic forms and Lorentzian KM algebras I, II"
  Dijkgraaf-Verlinde-Verlinde (1997): "Counting dyons in N=4 string theory"
  Cheng (2010): "K3 surfaces, N=4 dyons, and the Mathieu group M_24"
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from fractions import Fraction
from functools import lru_cache
from typing import Dict, List, Optional, Tuple, Set

F = Fraction


# ============================================================================
# Section 0: Lattice infrastructure
# ============================================================================

@dataclass(frozen=True)
class LatticeVector:
    """Vector in II_{1,1} + II_{1,1} = U + U.

    Represented as (a, b, c, d) where the bilinear form is:
      (v, w) = a*b' + b*a' + c*d' + d*c'  (NOT standard!)

    CONVENTION: We use the basis (e_1, f_1, e_2, f_2) where
      U_1 has basis (e_1, f_1) with (e_1, f_1) = 1, e_1^2 = f_1^2 = 0.
      U_2 has basis (e_2, f_2) with (e_2, f_2) = 1, e_2^2 = f_2^2 = 0.

    A vector v = a*e_1 + b*f_1 + c*e_2 + d*f_2 has:
      v^2 = 2ab + 2cd
      (v, w) = a*b' + b*a' + c*d' + d*c'  for w = a'*e_1 + b'*f_1 + c'*e_2 + d'*f_2

    For the Siegel modular form connection:
      (n, l, m) in the DVV product corresponds to the lattice vector
      in the "charge" basis. We identify:
        e_1 <-> q-direction (electric charge n)
        f_1 <-> p-direction (magnetic charge m)
        e_2 <-> y-direction (angular momentum l, positive part)
        f_2 <-> y-direction (angular momentum l, negative part)

    For the finite root-coordinate samples, we work with a 3-parameter
    encoding (n, l, m) where the norm is 2(nm) - l^2 = 2nm - l^2.
    But the true lattice is rank 4 (U+U).
    """
    a: int  # coefficient of e_1
    b: int  # coefficient of f_1
    c: int  # coefficient of e_2
    d: int  # coefficient of f_2

    @property
    def norm_sq(self) -> int:
        """Norm squared v^2 = 2ab + 2cd."""
        return 2 * self.a * self.b + 2 * self.c * self.d

    def inner(self, other: 'LatticeVector') -> int:
        """Inner product (v, w) = ab' + ba' + cd' + dc'."""
        return (self.a * other.b + self.b * other.a
                + self.c * other.d + self.d * other.c)

    def __add__(self, other: 'LatticeVector') -> 'LatticeVector':
        return LatticeVector(self.a + other.a, self.b + other.b,
                             self.c + other.c, self.d + other.d)

    def __sub__(self, other: 'LatticeVector') -> 'LatticeVector':
        return LatticeVector(self.a - other.a, self.b - other.b,
                             self.c - other.c, self.d - other.d)

    def __neg__(self) -> 'LatticeVector':
        return LatticeVector(-self.a, -self.b, -self.c, -self.d)

    def scale(self, k: int) -> 'LatticeVector':
        return LatticeVector(k * self.a, k * self.b, k * self.c, k * self.d)

    def __repr__(self) -> str:
        return f"({self.a}, {self.b}, {self.c}, {self.d})"


def lattice_norm(a: int, b: int, c: int, d: int) -> int:
    """Norm squared in U + U: 2ab + 2cd."""
    return 2 * a * b + 2 * c * d


def lattice_inner(v: Tuple[int, int, int, int],
                  w: Tuple[int, int, int, int]) -> int:
    """Bilinear form in U + U."""
    return v[0] * w[1] + v[1] * w[0] + v[2] * w[3] + v[3] * w[2]


# ============================================================================
# Section 1: K3 elliptic genus and c_0(D) coefficients
# ============================================================================

# Fourier coefficients of phi_{0,1}(tau, z) = sum c(n,l) q^n y^l.
# Eichler-Zagier convention: phi_{0,1}(tau, 0) = 12.
# Verified in cy_dt_k3e_engine.py.

_PHI01_COEFFS: Dict[Tuple[int, int], int] = {
    (0, -1): 1, (0, 0): 10, (0, 1): 1,
    (1, -2): 10, (1, -1): -64, (1, 0): 108, (1, 1): -64, (1, 2): 10,
    (2, -3): 1, (2, -2): 108, (2, -1): -513, (2, 0): 808,
    (2, 1): -513, (2, 2): 108, (2, 3): 1,
}


def phi01_coeff(n: int, ell: int) -> int:
    """Fourier coefficient c(n, l) of phi_{0,1}.

    Returns 0 for entries outside the finite sample table.
    For |l| > n + 1, c(n, l) = 0 for a weak Jacobi form of index 1.
    """
    if n < 0:
        return 0
    if abs(ell) > n + 1:
        return 0
    return _PHI01_COEFFS.get((n, ell), 0)


def k3_eg_coeff(n: int, ell: int) -> int:
    """Fourier coefficient of the K3 elliptic genus = 2 * phi_{0,1}."""
    return 2 * phi01_coeff(n, ell)


def c0_from_k3_eg(D: int) -> int:
    r"""Finite c_0(D) sample extracted from the K3 elliptic genus.

    For the product formula:
      Phi_{10} = q*r*s * prod_{(n,l,m)>0} (1 - q^n y^l p^m)^{c_0(4nm-l^2)}

    The signed exponent c_0(D) for discriminant D = 4nm - l^2 is the
    coefficient extracted from the theta decomposition of the K3 elliptic
    genus.

    For a weak Jacobi form phi of weight 0, index 1, the theta
    decomposition gives:
      phi(tau, z) = h_0(tau)*theta_{0,1}(tau,z) + h_1(tau)*theta_{1,1}(tau,z)
    where theta_{mu,1} are index-1 theta functions.

    The c_0(D) coefficients are extracted by: for each D, find (n, l)
    with 4n - l^2 = D and read c(n, l) from 2*phi_{0,1}. For the
    discriminant parametrization to be well-defined, we need that
    c(n, l) depends only on D = 4n - l^2 for the THETA DECOMPOSITION
    components (which it does, by the theory of Jacobi forms).

    In practice: for D = 4n - l^2, take any (n, l) achieving this
    discriminant and return 2 * phi01_coeff(n, l).

    For D = -1: (n, l) = (0, 1) gives c(0, 1) = 1, so c_0(-1) = 2.
    For D = 0: (n, l) = (0, 0) gives c(0, 0) = 10, so c_0(0) = 20.
    For D = 3: (n, l) = (1, 1) gives c(1, 1) = -64, so c_0(3) = -128.
    For D = 4: (n, l) = (1, 0) gives c(1, 0) = 108, so c_0(4) = 216.
    For D = 7: (n, l) = (2, 1) gives c(2, 1) = -513, so c_0(7) = -1026.
    For D = 8: (n, l) = (2, 0) gives c(2, 0) = 808, so c_0(8) = 1616.

    DISCRIMINANT CONSISTENCY: For discriminant D with D = -1 mod 4 or D = 0 mod 4:
    the coefficient should be the same for all (n, l) achieving it.
    The finite table checks D = 4 via two available (n, l) pairs.

    Range: we can compute c_0(D) for D in {-1, 0, 3, 4, 7, 8} from our table.
    """
    # Find a representative (n, l) with 4n - l^2 = D and (n, l) in our table.
    # We try small n values.
    for n in range(10):
        # l^2 = 4n - D
        disc = 4 * n - D
        if disc < 0:
            continue
        import math as _math
        l_sq = disc
        l_val = int(_math.isqrt(l_sq))
        if l_val * l_val == l_sq:
            # Check if this (n, l_val) is in our table
            val = phi01_coeff(n, l_val)
            if val != 0 or (n, l_val) in _PHI01_COEFFS:
                return 2 * val
            # Try negative l
            val_neg = phi01_coeff(n, -l_val)
            if val_neg != 0 or (n, -l_val) in _PHI01_COEFFS:
                return 2 * val_neg
    # If not found, return 0 (outside our range)
    return 0


# Extended c_0 table computed from 2*phi_{0,1} theta decomposition.
# These are the Borcherds product exponents for Phi_{10}.
# Verified by cross-checking (n, l) representatives.
_C0_TABLE: Dict[int, int] = {}


def _build_c0_table() -> None:
    """Build the c_0(D) lookup table from the phi_{0,1} coefficients."""
    global _C0_TABLE
    if _C0_TABLE:
        return
    seen: Dict[int, int] = {}
    for (n, ell), val in _PHI01_COEFFS.items():
        D = 4 * n - ell * ell
        c0_val = 2 * val  # K3 EG = 2 * phi_{0,1}
        if D in seen:
            # Consistency check: c_0(D) should not depend on representative
            if seen[D] != c0_val:
                # This can happen because phi_{0,1} is WEAK:
                # c(n, l) may differ for different (n, l) with same D.
                # But for the theta decomposition, the h_mu(tau) components
                # DO depend only on D within each mu-sector. The full c(n,l)
                # involves both h_0 and h_1, so apparent inconsistency comes
                # from mixing l-parity sectors.
                # For the Borcherds product, the exponent for a triple
                # (n0,l,m0) is c_K3(N,l) with N = n0*m0, not the left
                # index n0 alone.
                # We store the VALUE for the smallest |l| representative.
                pass
        else:
            seen[D] = c0_val
    _C0_TABLE = seen


def c0_table(D: int) -> int:
    """Look up a finite signed c_0(D) exponent sample."""
    _build_c0_table()
    return _C0_TABLE.get(D, 0)


# Finite signed exponent samples from 2*phi_{0,1}. These are low-order
# coefficient sanity data, not a proof of denominator/root-system recognition.
# D = -1: c_0 = 2 (from c(0,1) = 1)
# D = 0:  c_0 = 20 (from c(0,0) = 10)
# D = 3:  c_0 = -128 (from c(1,1) = -64)
# D = 4:  c_0 = 216 (from c(1,0) = 108)
# D = 7:  c_0 = -1026 (from c(2,1) = -513)
# D = 8:  c_0 = 1616 (from c(2,0) = 808)

SIGNED_BORCHERDS_EXPONENT_SAMPLES: Dict[int, int] = {
    -1: 2,
    0: 20,
    3: -128,
    4: 216,
    7: -1026,
    8: 1616,
}

# Individual signed exponents for the finite Borcherds-product truncation.
# For a triple (n0, l, m0) > 0, the exponent sample is
# c_K3(N, l) = 2*c_{phi01}(N, l) with N = n0*m0. It is not an unsigned
# root multiplicity.


def borcherds_exponent(n: int, ell: int, m: Optional[int] = None) -> int:
    """Exponent in the Borcherds product for Phi_{10}.

    For a product triple (n_0, l_0, m_0), the exponent is indexed by
    the Jacobi product index N = n_0*m_0 and l_0:
      c_K3(N, l_0) = 2*phi01_coeff(N, l_0).

    Backward compatibility: when ``m`` is omitted, ``n`` is interpreted
    as the already-formed Jacobi index N. Calls that know the product
    triple should pass ``m`` explicitly.

    CRITICAL (AP38): the exponent for the triple (n,l,m) in the product
      Phi_{10} = q*r*s * prod_{(n,l,m)>0} (1 - q^n y^l p^m)^{f(nm,l)}
    is f(nm,l) = c_K3(nm,l) = 2*c_{phi01}(nm,l). In
    discriminant-indexed notation this is c_0(4nm-l^2) when the finite
    sample contains that coefficient.
    """
    jacobi_index = n if m is None else n * m
    return 2 * phi01_coeff(jacobi_index, ell)


# ============================================================================
# Section 2: Root system of the BKM algebra
# ============================================================================

@dataclass
class BKMRoot:
    """Root-coordinate sample in the Siegel modular parametrization.

    The full lattice is a rank-four U+U lattice. This finite engine uses
    the standard three-coordinate slice in which a vector is represented
    by a triple (n, l, m) with bilinear form
      ((n,l,m), (n',l',m')) = nm' + mn' - ll'
    and norm
      (n,l,m)^2 = 2nm - l^2.

    The optional ``multiplicity`` field stores a finite sample value. It is
    not evidence that the vector has been recognized as a simple root.
    """
    n: int
    l: int
    m: int
    multiplicity: int = 1

    @property
    def norm_sq(self) -> int:
        """Norm squared: 2nm - l^2."""
        return 2 * self.n * self.m - self.l ** 2

    @property
    def discriminant(self) -> int:
        """Root discriminant D_root = l^2 - 2nm = -norm_sq.

        This is distinct from the DVV charge discriminant
        Delta = 4nm - l^2. The finite product-exponent samples use their
        own indexing convention; callers must not identify these two
        discriminants silently.
        """
        return self.l ** 2 - 2 * self.n * self.m

    def inner(self, other: 'BKMRoot') -> int:
        """Inner product: (alpha, beta) = n*m' + m*n' - l*l'."""
        return self.n * other.m + self.m * other.n - self.l * other.l

    def __add__(self, other: 'BKMRoot') -> 'BKMRoot':
        return BKMRoot(self.n + other.n, self.l + other.l, self.m + other.m)

    def __neg__(self) -> 'BKMRoot':
        return BKMRoot(-self.n, -self.l, -self.m)

    def scale(self, k: int) -> 'BKMRoot':
        return BKMRoot(k * self.n, k * self.l, k * self.m)

    @property
    def is_positive(self) -> bool:
        """A root (n, l, m) is positive if:
        m > 0, or (m = 0 and n > 0), or (m = 0 and n = 0 and l < 0).
        """
        if self.m > 0:
            return True
        if self.m == 0 and self.n > 0:
            return True
        if self.m == 0 and self.n == 0 and self.l < 0:
            return True
        return False

    @property
    def is_real(self) -> bool:
        """Real root: norm^2 = 2 (positive definite direction)."""
        return self.norm_sq == 2

    @property
    def is_imaginary(self) -> bool:
        """Imaginary root: norm^2 <= 0."""
        return self.norm_sq <= 0

    @property
    def is_lightlike(self) -> bool:
        """Lightlike (isotropic) root: norm^2 = 0."""
        return self.norm_sq == 0

    def __repr__(self) -> str:
        return f"BKMRoot(n={self.n}, l={self.l}, m={self.m})"


@dataclass(frozen=True)
class SuperRootMultiplicity:
    """Even/odd super root multiplicity data for a finite sample root.

    The signed dimension ``even - odd`` is the exponent seen by a
    denominator product. The total dimension ``even + odd`` is the unsigned
    multiplicity of the super vector space.
    """
    even: int = 0
    odd: int = 0

    @property
    def signed_dimension(self) -> int:
        """Signed superdimension even - odd."""
        return self.even - self.odd

    @property
    def total_dimension(self) -> int:
        """Unsigned total dimension even + odd."""
        return self.even + self.odd


# ============================================================================
# Section 3: BKM Cartan matrix
# ============================================================================

def simple_real_roots() -> List[BKMRoot]:
    """Simple real roots of the BKM algebra for K3.

    A real simple root has norm^2 = 2. In the (n, l, m) basis with
    norm^2 = 2nm - l^2 = 2, we need 2nm - l^2 = 2, i.e., nm = (l^2 + 2)/2.

    For l = 0: nm = 1, so (n, m) = (1, 1). Root: (1, 0, 1). norm = 2*1 - 0 = 2.
    For l = +-1: nm = 3/2, not integral. Skip.
    For l = +-2: nm = 3. (n, m) = (1, 3) or (3, 1). But we want simple roots.

    The simple real root in the fundamental domain is alpha_1 = (1, 0, 1).
    For the BKM algebra associated to Phi_{10}, there is a SINGLE
    simple real root (up to Weyl group) corresponding to the
    norm-2 vector in II_{1,1}.

    More precisely: the "minimal" BKM algebra for the DVV system has
    simple roots at:
      alpha_0 = (1, 0, 1) (real, norm 2)
    plus the simple imaginary roots at various (n, l, m) with norm <= 0.
    """
    return [BKMRoot(1, 0, 1)]


def simple_imaginary_roots(norm_bound: int = 0) -> List[BKMRoot]:
    """Finite representatives seeded from signed exponent samples.

    This is not a simple-root recognition algorithm. It chooses one small
    representative for each stored signed exponent and records the absolute
    super-dimension in ``BKMRoot.multiplicity``. The parity information is
    recovered by ``super_root_multiplicity`` from the sign.

    ``norm_bound`` is retained for API compatibility. The default ``0`` means
    "return the whole finite sample".
    """
    result = []
    for D, signed_exp in sorted(SIGNED_BORCHERDS_EXPONENT_SAMPLES.items()):
        if norm_bound != 0 and D > norm_bound:
            continue
        if signed_exp == 0:
            continue
        multiplicity = abs(signed_exp)

        if D <= 0:
            l_sq = -D
            l_val = int(math.isqrt(l_sq))
            if l_val * l_val == l_sq:
                if l_val == 0:
                    result.append(BKMRoot(0, 0, 1, multiplicity=multiplicity))
                else:
                    result.append(BKMRoot(0, -l_val, 0, multiplicity=multiplicity))
        else:
            if D % 4 == 0:
                n_val = D // 4
                result.append(BKMRoot(n_val, 0, 0, multiplicity=multiplicity))
            elif D % 4 == 3:
                n_val = (D + 1) // 4
                result.append(BKMRoot(n_val, 1, 0, multiplicity=multiplicity))
    return result


def bkm_cartan_matrix(roots: Optional[List[BKMRoot]] = None,
                      num_roots: int = 7) -> List[List[F]]:
    """Generalized Cartan matrix A_{ij} = 2(alpha_i, alpha_j) / alpha_j^2.

    For the BKM algebra, the Cartan matrix is indexed by simple roots.
    For real roots (alpha^2 = 2): A_{ij} is the standard formula.
    For imaginary roots (alpha^2 <= 0): A_{ii} = 2*alpha_i^2/alpha_i^2 = 2
      if alpha_i^2 != 0, or A_{ii} = 0 if alpha_i^2 = 0.

    The generalized Cartan matrix for a BKM algebra satisfies:
    (1) A_{ii} = 2 or A_{ii} <= 0 (allowing non-positive diagonal)
    (2) A_{ij} <= 0 for i != j (off-diagonal non-positive)
    (3) A_{ij} = 0 implies A_{ji} = 0
    """
    if roots is None:
        # Default: real root + first imaginary roots
        real = simple_real_roots()
        imag = simple_imaginary_roots()
        roots = real + imag[:num_roots - len(real)]

    n = len(roots)
    A: List[List[F]] = [[F(0)] * n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            inner_ij = roots[i].inner(roots[j])
            norm_j = roots[j].norm_sq
            if norm_j != 0:
                A[i][j] = F(2 * inner_ij, norm_j)
            else:
                # For lightlike roots, A_{ij} is defined differently.
                # In BKM theory: A_{ii} = 0 for lightlike simple roots.
                # A_{ij} = 2*(alpha_i, alpha_j) for j lightlike (no denominator).
                # Actually: the generalized Cartan matrix is only
                # well-defined when alpha_j^2 != 0. For lightlike roots,
                # we use the convention A_{ij} = 2*(alpha_i, alpha_j).
                A[i][j] = F(2 * inner_ij)

    return A


# ============================================================================
# Section 4: Weyl group
# ============================================================================

def weyl_reflection(alpha: BKMRoot, beta: BKMRoot) -> BKMRoot:
    """Reflect beta through the hyperplane perpendicular to alpha.

    s_alpha(beta) = beta - (2*(alpha, beta) / alpha^2) * alpha

    Only defined for real roots (alpha^2 = 2) or more generally
    for any root with alpha^2 != 0.
    """
    if alpha.norm_sq == 0:
        raise ValueError("Cannot reflect through a lightlike root")
    coeff_num = 2 * alpha.inner(beta)
    coeff_den = alpha.norm_sq
    if coeff_num % coeff_den != 0:
        raise ValueError(f"Reflection coefficient {coeff_num}/{coeff_den} is not integral")
    k = coeff_num // coeff_den
    return BKMRoot(beta.n - k * alpha.n, beta.l - k * alpha.l, beta.m - k * alpha.m)


def weyl_vector() -> BKMRoot:
    """The Weyl vector rho for the BKM algebra.

    The Weyl vector satisfies: (rho, alpha_i) = alpha_i^2 / 2 for all
    simple roots alpha_i.

    For the BKM algebra associated to Phi_{10}, the Weyl vector is
    rho = (1, 0, 1) in the (n, l, m) parametrization.

    Check: (rho, alpha_0) = rho.inner(alpha_0) where alpha_0 = (1, 0, 1).
      = 1*1 + 1*1 - 0*0 = 2 = alpha_0^2 / 2 * 2 = 2. Hmm.
      alpha_0^2 = 2*1*1 - 0 = 2. So alpha_0^2/2 = 1.
      (rho, alpha_0) = 2 != 1. So rho = (1, 0, 1) gives (rho, alpha_0) = 2.

    Let me reconsider. Borcherds' convention: (rho, alpha_i) = alpha_i^2/2
    for real simple roots. So we need (rho, (1,0,1)) = 1.
    rho = (a, b, c): (a,b,c).(1,0,1) = a*1 + c*1 - b*0 = a + c = 1.
    Possible: rho = (1, 0, 0) gives a + c = 1. Check: norm = 0. OK.
    Or rho = (0, 0, 1) gives a + c = 1. Check: norm = 0. OK.

    The standard choice for the Igusa cusp form Phi_{10} is:
      Phi_{10} = q*r*s * prod ... where q = e^{2pi i tau}, r = e^{2pi i z},
      s = e^{2pi i sigma}. The prefactor q*r*s = e^{2pi i (tau + z + sigma)}
      corresponds to e^{2pi i (rho, Z)} with rho = (1, 1, 1) in the
      (tau, z, sigma) basis. In the (n, l, m) basis where
      Z = n*tau + l*z + m*sigma, rho = (1, 1, 1) means
      (rho, Z) = tau + z + sigma.

    So rho = (1, 1, 1) in the (n, l, m) basis.
    Check: rho^2 = 2*1*1 - 1^2 = 2 - 1 = 1.
    (rho, alpha_0) = (1,1,1).(1,0,1) = 1*1 + 1*1 - 1*0 = 2.
    alpha_0^2/2 = 1. So (rho, alpha_0) = 2 != 1. Still off by 2.

    In Borcherds' theory, the Weyl vector rho is NOT required to satisfy
    (rho, alpha_i) = alpha_i^2/2 for imaginary simple roots. It only
    needs to satisfy this for REAL simple roots. And the prefactor in
    the product formula is e^{(rho, Z)}, which for Phi_{10} is
    q*r*s = e^{2pi i (tau + z + sigma)}. So (rho, Z) = tau + z + sigma.

    In the (n, l, m) coordinates: (rho, Z) = rho_n * tau + rho_l * z + rho_m * sigma.
    But Z is parametrized as Z = (tau  z; z  sigma), and the quadratic form on
    the symmetric matrix is given by... this is getting into Siegel modular
    form territory.

    For the DENOMINATOR IDENTITY, the key is:
      e^{-rho} * Phi_{10} = prod_{alpha > 0} (1 - e^{-alpha})^{mult(alpha)}
    where e^{-rho} = (qrs)^{-1}.

    So rho corresponds to the "shift" (1, 1, 1) in the exponent.
    """
    return BKMRoot(1, 1, 1)


def weyl_group_orbit(v: BKMRoot, real_roots: Optional[List[BKMRoot]] = None,
                     max_orbit_size: int = 100) -> List[BKMRoot]:
    """Compute the Weyl group orbit of v under reflections by real roots.

    The Weyl group is generated by reflections s_{alpha} for real simple
    roots alpha. For the BKM algebra associated to K3, this is an infinite
    group (hyperbolic Coxeter group), so we cap the orbit size.
    """
    if real_roots is None:
        real_roots = simple_real_roots()

    orbit: Set[Tuple[int, int, int]] = {(v.n, v.l, v.m)}
    frontier = [v]

    while frontier and len(orbit) < max_orbit_size:
        new_frontier = []
        for w in frontier:
            for alpha in real_roots:
                reflected = weyl_reflection(alpha, w)
                key = (reflected.n, reflected.l, reflected.m)
                if key not in orbit:
                    orbit.add(key)
                    new_frontier.append(reflected)
                    if len(orbit) >= max_orbit_size:
                        break
            if len(orbit) >= max_orbit_size:
                break
        frontier = new_frontier

    return [BKMRoot(n, l, m) for (n, l, m) in sorted(orbit)]


def weyl_group_is_infinite() -> bool:
    """The Weyl group of the K3 BKM algebra is infinite.

    Proof: the lattice II_{1,1} has signature (1,1), so the Weyl group
    contains reflections in a hyperbolic plane, which generate an infinite
    dihedral group. For II_{2,2}, the Weyl group is even larger.
    """
    return True


# ============================================================================
# Section 5: Root multiplicities
# ============================================================================

def root_multiplicity_direct(alpha: BKMRoot) -> int:
    """Signed superdimension from the finite K3 elliptic-genus sample.

    This legacy helper returns a signed integer. Positive values represent
    even superdimension, negative values represent odd superdimension, and
    zero means no finite sample value is present. Use
    ``super_root_multiplicity`` when parity and unsigned multiplicity must be
    explicit.

    The value is a finite coefficient sanity check. It is not a denominator
    identity computation and does not recognize a root system.
    """
    ns = alpha.norm_sq
    if ns > 2:
        return 0
    if ns == 2:
        return 1
    return k3_eg_coeff(alpha.n, alpha.l)


def super_root_multiplicity(alpha: BKMRoot) -> SuperRootMultiplicity:
    """Even/odd super root multiplicity for the finite sample root."""
    signed = root_multiplicity_direct(alpha)
    if signed > 0:
        return SuperRootMultiplicity(even=signed, odd=0)
    if signed < 0:
        return SuperRootMultiplicity(even=0, odd=-signed)
    return SuperRootMultiplicity()


def root_multiplicity_table(norm_max: int = 8) -> Dict[int, int]:
    """Finite table of signed superdimensions by representative norm.

    For each stored representative norm, returns the signed dimension
    even - odd. It is not an unsigned multiplicity table and not a
    root-system recognition result.

    norm^2 = 2: mult = 1 (real root)
    norm^2 = 0: mult = 20 (c_K3(0, 0) = 2*10 = 20, lightlike)
    norm^2 = -1: mult = 2 (c_K3(0, +-1) = 2*1 = 2)
    norm^2 = -2: undefined by just norm (depends on (n,l))
    ...

    For imaginary roots, the finite value depends on the selected vector,
    not just on the norm. This routine returns only the representative
    sample used by the tests.
    """
    result: Dict[int, int] = {}
    result[2] = 1  # Real root

    # The finite discriminant sample is used only to populate small
    # representative norms. It is not a proof that the representative is a
    # simple root.
    for D in sorted(SIGNED_BORCHERDS_EXPONENT_SAMPLES.keys()):
        c0_val = SIGNED_BORCHERDS_EXPONENT_SAMPLES[D]
        # For simple roots with m = 0, norm^2 = -l^2 where l^2 = -D
        # So norm^2 = D (since D = -l^2 for m = 0, n = 0 or appropriate).
        # Actually: D_DVV = 4nm - l^2 and norm^2 = 2nm - l^2.
        # For m = 0: D_DVV = -l^2, norm^2 = -l^2. So D_DVV = norm^2.
        # For the representative with m = 0: mult(norm^2 = D) = c_0(D).
        if D <= 0:
            result[D] = c0_val
        else:
            # For D > 0: need nm > 0. Take l = 0, n*m = D/2 (if D even)
            # or l = 1, nm = (D+1)/2. norm^2 = 2nm - l^2.
            # For l = 0: norm^2 = 2nm = D (if D is even and we set nm = D/2).
            # Wait: D_DVV = 4nm - 0 = 4nm. So D = 4nm means nm = D/4.
            # norm^2 = 2nm = D/2.
            # For D = 4: nm = 1, norm^2 = 2.
            # Positive discriminant samples are signed product exponents.
            # They are not inserted as norm-indexed root multiplicities.
            pass

    return result


# ============================================================================
# Section 6: Peterson-Kac recursion
# ============================================================================

def peterson_kac_mult(target_n: int, target_l: int, target_m: int,
                      known_mults: Optional[Dict[Tuple[int, int, int], int]] = None,
                      max_decompositions: int = 1000) -> int:
    """Finite Peterson-Kac-style signed-superdimension recursion.

    The Peterson formula for BKM algebras:
      (alpha, alpha - 2*rho) * mult(alpha) / 2
        = sum_{beta+gamma=alpha, beta,gamma>0} (beta, gamma) * mult(beta) * mult(gamma)
          + sum_{k>=2} mult(alpha/k) * (alpha/k, rho)

    where rho is the Weyl vector.

    Rearranging:
      mult(alpha) = [2 / (alpha, alpha - 2*rho)] * [
        sum_{beta+gamma=alpha} (beta,gamma)*mult(beta)*mult(gamma)
        + sum_{k>=2, k|alpha} mult(alpha/k) * (alpha/k, rho)
      ]

    For alpha = (n, l, m):
    - alpha^2 = 2nm - l^2
    - (alpha, rho) = n*1 + m*1 - l*1 = n + m - l (for rho = (1,1,1))
    - (alpha, alpha - 2*rho) = alpha^2 - 2*(alpha, rho)
      = (2nm - l^2) - 2(n + m - l)

    ``known_mults`` is a seed table of signed superdimensions. In this module
    it is finite sanity data, not a recognized simple-root system.
    """
    alpha = BKMRoot(target_n, target_l, target_m)
    rho = weyl_vector()

    if not alpha.is_positive:
        return 0

    if known_mults is None:
        known_mults = {}

    key = (target_n, target_l, target_m)
    if key in known_mults:
        return known_mults[key]

    # Base case: real simple root
    if alpha.norm_sq == 2 and target_n == 1 and target_l == 0 and target_m == 1:
        return 1

    alpha_rho = alpha.inner(rho)  # (alpha, rho)
    denom = alpha.norm_sq - 2 * alpha_rho
    if denom == 0:
        # Degenerate case: need special handling
        return 0

    # Sum over decompositions beta + gamma = alpha
    pair_sum = 0
    count = 0
    for bn in range(0, target_n + 1):
        for bl in range(-abs(target_l) - 2, abs(target_l) + 3):
            for bm in range(0, target_m + 1):
                beta = BKMRoot(bn, bl, bm)
                gamma_n = target_n - bn
                gamma_l = target_l - bl
                gamma_m = target_m - bm
                gamma = BKMRoot(gamma_n, gamma_l, gamma_m)

                if not beta.is_positive or not gamma.is_positive:
                    continue
                if (bn, bl, bm) == key or (gamma_n, gamma_l, gamma_m) == key:
                    continue  # Skip alpha itself

                mb = known_mults.get((bn, bl, bm), 0)
                mg = known_mults.get((gamma_n, gamma_l, gamma_m), 0)

                if mb == 0 or mg == 0:
                    continue

                pair_sum += beta.inner(gamma) * mb * mg
                count += 1
                if count >= max_decompositions:
                    break
            if count >= max_decompositions:
                break
        if count >= max_decompositions:
            break

    # Sum over multiples: sum_{k>=2, k|alpha} mult(alpha/k) * (alpha/k, rho)
    multi_sum = 0
    for k in range(2, max(target_n, target_m, abs(target_l)) + 1):
        if target_n % k != 0 or target_l % k != 0 or target_m % k != 0:
            continue
        sub = BKMRoot(target_n // k, target_l // k, target_m // k)
        sub_key = (sub.n, sub.l, sub.m)
        ms = known_mults.get(sub_key, 0)
        if ms != 0:
            multi_sum += ms * sub.inner(rho)

    mult_val = F(2 * (pair_sum + multi_sum), denom)
    # The result should be a non-negative integer
    if mult_val.denominator == 1 and mult_val >= 0:
        return int(mult_val)
    return 0


def build_root_multiplicities_pk(max_height: int = 5) -> Dict[Tuple[int, int, int], int]:
    """Build a finite signed-superdimension table using seeded recursion.

    Start from finite coefficient seeds and build up.
    "Height" is defined as n + m (roughly the level in the root lattice).

    Returns a dict mapping (n, l, m) -> signed superdimension.
    """
    mults: Dict[Tuple[int, int, int], int] = {}

    # Initialize with finite signed-superdimension seeds.
    # Real sample root: (1, 0, 1) with even dimension 1.
    mults[(1, 0, 1)] = 1

    # Imaginary sample roots from K3 EG.
    # For m = 0 (or n = 0): these are the "level-0" sample roots.
    # (0, -1, 0): norm = -1, c_K3(0, 1) = 2, with l = -1 chosen
    # for the positive-root convention.
    mults[(0, -1, 0)] = 2  # c_K3(0, 1) = 2

    # (0, 0, 1): norm = 0, c_K3(0, 0) = 20. m = 1 > 0: POSITIVE.
    mults[(0, 0, 1)] = 20

    # (1, 0, 0): norm = 0, c_K3(1, 0) = 216. It is retained as a
    # coefficient seed, with no assertion that it is simple.

    # The full simple-root problem is not decided here. These seeds only keep
    # the finite test surface stable.

    # Additional finite sample roots at height 1:
    # (1, -1, 0): norm = 0 - 1 = -1. m=0, n=1>0: positive.
    # c_K3(1, -1) = 2*(-64) = -128.
    # Negative signed dimension records an odd contribution.
    mults[(1, -1, 0)] = -128  # From K3 EG: odd root

    # (1, 1, 0): norm = -1. m=0, n=1>0: positive.
    # Same c_K3(1, 1) = -128.
    mults[(1, 1, 0)] = -128

    # (1, -2, 0): norm = 0 - 4 = -4. m=0, n=1>0: positive.
    # c_K3(1, -2) = 2*10 = 20.
    mults[(1, -2, 0)] = 20

    # (1, 2, 0): by symmetry, c_K3(1, 2) = 20.
    mults[(1, 2, 0)] = 20

    # (1, 0, 0): lightlike. c_K3(1, 0) = 216.
    # Not asserted simple; recorded as a finite sample value.
    mults[(1, 0, 0)] = 216

    # Now apply Peterson-Kac to compute higher roots
    for height in range(2, max_height + 1):
        for n in range(0, height + 1):
            for m in range(0, height + 1 - n):
                for l in range(-height - 1, height + 2):
                    if (n, l, m) in mults:
                        continue
                    root = BKMRoot(n, l, m)
                    if not root.is_positive:
                        continue
                    mult_val = peterson_kac_mult(n, l, m, mults)
                    if mult_val != 0:
                        mults[(n, l, m)] = mult_val

    return mults


# ============================================================================
# Section 7: Denominator identity and Borcherds product
# ============================================================================

def borcherds_product_expansion(q_order: int = 5) -> Dict[Tuple[int, int, int], int]:
    """Expand the Borcherds product for Phi_{10} to given order.

    Phi_{10}(Z) = q*r*s * prod_{(n,l,m)>0} (1 - q^n y^l p^m)^{c_K3(nm,l)}

    We expand in powers of (q, y, p) = (e^{2pi i tau}, e^{2pi i z}, e^{2pi i sigma}).

    The prefactor q*r*s contributes e^{2pi i(tau + z + sigma)}.

    Returns: dict mapping (n_q, n_y, n_p) -> coefficient in the expansion
    Phi_{10} = sum c_{n,l,m} q^n y^l p^m.
    """
    # Start with the prefactor: q*y*p = coefficient 1 at (1, 1, 1)
    # Then multiply by each factor (1 - q^n y^l p^m)^{c_K3(nm,l)}

    # For efficiency, work with a truncated power series.
    # Represent as dict: (n, l, m) -> coefficient.
    coeffs: Dict[Tuple[int, int, int], int] = {(1, 1, 1): 1}

    # Enumerate positive triples (n, l, m) in the product
    # Order: first by m, then n, then l
    for m_prod in range(0, q_order):
        for n_prod in range(0, q_order):
            for l_prod in range(-q_order, q_order + 1):
                # Check positivity
                if m_prod > 0:
                    pass  # positive
                elif m_prod == 0 and n_prod > 0:
                    pass  # positive
                elif m_prod == 0 and n_prod == 0 and l_prod < 0:
                    pass  # positive
                else:
                    continue

                # Exponent from K3 EG at Jacobi index N = n_prod*m_prod.
                exp = borcherds_exponent(n_prod, l_prod, m_prod)
                if exp == 0:
                    continue

                # Multiply by (1 - q^n y^l p^m)^{exp}
                # For small |exp|, expand explicitly
                # (1 - x)^a = sum_{k=0}^{|a|?} binom(a, k) (-x)^k
                # For negative exp: (1-x)^{-|exp|} = sum binom(k+|exp|-1, k) x^k

                new_coeffs: Dict[Tuple[int, int, int], int] = {}

                if exp > 0:
                    # (1 - x)^exp: finite expansion up to x^exp
                    factor_coeffs = {}
                    for k in range(exp + 1):
                        binom_val = math.comb(exp, k) * ((-1) ** k)
                        if binom_val != 0:
                            factor_coeffs[(k * n_prod, k * l_prod, k * m_prod)] = binom_val
                elif exp < 0:
                    # (1 - x)^{exp} = (1 - x)^{-|exp|}: infinite series, truncate
                    aexp = -exp
                    factor_coeffs = {}
                    for k in range(q_order + 1):
                        idx = (k * n_prod, k * l_prod, k * m_prod)
                        if idx[0] > q_order or idx[2] > q_order:
                            break
                        binom_val = math.comb(k + aexp - 1, k)
                        if binom_val != 0:
                            factor_coeffs[idx] = binom_val
                else:
                    continue

                # Convolve: multiply coeffs by factor_coeffs
                for (cn, cl, cm), cv in coeffs.items():
                    if cv == 0:
                        continue
                    for (fn, fl, fm), fv in factor_coeffs.items():
                        nn = cn + fn
                        nl = cl + fl
                        nm = cm + fm
                        if nn > q_order or nm > q_order:
                            continue
                        key = (nn, nl, nm)
                        new_coeffs[key] = new_coeffs.get(key, 0) + cv * fv

                coeffs = new_coeffs

    return coeffs


def phi10_known_coefficients() -> Dict[Tuple[int, int, int], int]:
    """Known Fourier coefficients of Phi_{10} from the literature.

    Phi_{10} is the UNIQUE Siegel cusp form of weight 10 on Sp(4, Z).
    It was computed by Igusa (1962).

    The leading terms in the expansion
      Phi_{10}(Z) = sum a(n, l, m) q^n y^l p^m
    include:
      a(1, 1, 1) = 1  (the leading term from the Weyl vector)
      a(1, 0, 1) = -2  (from the (0, -1, 0) factor)
      a(2, 1, 1) = -24 (from Ramanujan tau and Hecke eigenvalues)

    The first few Fourier-Jacobi coefficients phi_{10,m}(tau, z):
      Phi_{10}(Z) = sum_{m>=1} phi_{10,m}(tau, z) p^m

    phi_{10,1}(tau, z) = q * (y - 2 + y^{-1}) + ...
                       = eta(tau)^{18} * theta_1(tau, z)^2
    This is the Jacobi cusp form of weight 10 and index 1.

    From eta^{18} * theta_1^2:
      eta^{18} = q^{3/4} * (1 - 18q + 135q^2 - ...)^? No.
      eta(q) = q^{1/24} prod(1-q^n), so
      eta^{18} = q^{18/24} prod(1-q^n)^{18} = q^{3/4} * prod(1-q^n)^{18}.
      theta_1(tau, z) = -i sum_{n in Z} (-1)^n q^{(n+1/2)^2/2} y^{n+1/2}
                      = 2 q^{1/8} sin(pi z) prod_{n>=1} (1-q^n)(1-yq^n)(1-y^{-1}q^n)
      theta_1^2: leading term ~ 4 q^{1/4} sin^2(pi z) ...
      = q^{1/4} (y^{1/2} - y^{-1/2})^2 * ...
      = q^{1/4} (y - 2 + y^{-1}) * ...

    So phi_{10,1} = eta^{18} * theta_1^2 = q^{3/4 + 1/4} * (y - 2 + y^{-1}) * ...
                  = q * (y - 2 + y^{-1}) * prod-terms...

    At the LEADING ORDER in q (q^1 term):
      phi_{10,1} |_{q^1} = y - 2 + y^{-1}.

    So the Fourier coefficients of Phi_{10} at m = 1 start:
      a(1, 1, 1) = 1 (coefficient of q^1 y^1 p^1)
      a(1, 0, 1) = -2 (coefficient of q^1 y^0 p^1)
      a(1, -1, 1) = 1 (coefficient of q^1 y^{-1} p^1)

    These are exactly the Fourier coefficients of phi_{10,1}(tau, z)
    which is eta(tau)^{18} * theta_1(tau, z)^2.
    """
    return {
        (1, 1, 1): 1,
        (1, 0, 1): -2,
        (1, -1, 1): 1,
    }


def denominator_identity_check_leading(q_order: int = 3) -> Dict[str, object]:
    """Finite leading-coefficient check for the product expansion.

    At the very leading order: Phi_{10} starts with q*y*p * (1 - ...).
    The leading coefficient a(1, 1, 1) = 1 is the Weyl vector contribution.

    This does not prove the denominator identity or recognize the root system.
    """
    product = borcherds_product_expansion(q_order)
    known = phi10_known_coefficients()

    checks = {}
    for key, val in known.items():
        prod_val = product.get(key, 0)
        checks[str(key)] = {
            'known': val,
            'product': prod_val,
            'match': val == prod_val,
        }

    return checks


# ============================================================================
# Section 8: Connection to shadow obstruction tower
# ============================================================================

def shadow_kappa_k3_sigma() -> F:
    """Modular characteristic kappa for the K3 sigma model chiral algebra.

    kappa = complex dimension of K3 = 2.
    This is the genus-1 obstruction class coefficient.
    """
    return F(2)


def shadow_kappa_k3xe_total() -> F:
    """Categorical/BCOV modular characteristic for K3 x E as a CY3.

    This is the total compact CY3 comparator.  It is not the Stage-2
    chiral Heisenberg invariant, not the Borcherds weight, and not the
    K3 fibre rank.
    """
    return F(0)


def k3xe_kappa_split() -> Dict[str, F]:
    """The four non-interchangeable kappa lanes attached to K3 x E."""
    return {
        'kappa_cat': F(0),            # chi(O_{K3 x E})
        'kappa_ch_heisenberg': F(3),  # dim_C(K3 x E)
        'kappa_bkm_delta5': F(5),     # wt(Delta_5)
        'kappa_fiber_mukai': F(24),   # rank H^*(K3)
    }


def igusa_delta5_normalization() -> Dict[str, object]:
    """Scalar normalisation bridge between Delta_5, D_5, and OP chi_10."""
    return {
        'delta5_leading_coeff': 64,
        'D5_formula': 'D_5 = 64^{-1} Delta_5',
        'Phi10_un_formula': 'Phi_10^un = Delta_5^2',
        'Phi10_OP_formula': 'Phi_10^OP = D_5^2 = 4096^{-1} Delta_5^2',
        'Z_OP_DT_formula': 'Z_OP/DT = -D_5^{-2} = -4096 Delta_5^{-2}',
        'theta_to_monic_square_factor': 4096,
        'op_dt_scalar_factor': -4096,
    }


def shadow_kappa_complementarity() -> Dict[str, object]:
    """Check kappa complementarity for K3 x E.

    For the K3 sigma model A = V_{K3}:
      kappa(A) = 2 (complex dimension of K3)

    The Koszul dual A^! of the K3 sigma model:
    For a lattice VOA V_Lambda: kappa = rank(Lambda) (AP48).
    K3 sigma model is NOT a lattice VOA in general (it depends on moduli).
    At the Gepner point: kappa(A^!) is determined by the dual theory.

    For the CY3 = K3 x E the scalar "kappa" must be lane-qualified:
      kappa_cat = chi(O_{K3 x E}) = 0,
      kappa_ch^{Heis} = dim_C(K3 x E) = 3,
      kappa_BKM(Delta_5) = wt(Delta_5) = 5,
      kappa_fiber(K3) = rank H^*(K3) = 24.
    The categorical zero comes from the compact total space; the other
    three numbers come from different constructions and do not add to it.

    Complementarity (Theorem C): kappa(A) + kappa(A^!) = 0 for KM/free fields.
    For K3 sigma model: kappa(A) = 2, so kappa(A^!) = -2 if complementarity holds.
    """
    split = k3xe_kappa_split()
    return {
        'kappa_k3': shadow_kappa_k3_sigma(),
        'kappa_k3xe_cat': split['kappa_cat'],
        'kappa_k3xe_ch_heisenberg': split['kappa_ch_heisenberg'],
        'kappa_k3xe_bkm_delta5': split['kappa_bkm_delta5'],
        'kappa_k3xe_fiber_mukai': split['kappa_fiber_mukai'],
        'kappa_k3xe': split['kappa_cat'],  # backward-compatible alias
        'chi_k3': 24,
        'chi_e': 0,
        'chi_product': 0,
        'additivity_holds': False,  # chi is multiplicative, not additive
        'note': 'K3xE kappa values are lane-qualified: {0, 3, 5, 24}.',
    }


@lru_cache(maxsize=256)
def lambda_fp(g: int) -> F:
    r"""Faber-Pandharipande lambda_g^{FP}.

    lambda_g = (2^{2g-1} - 1) / (2^{2g-1}) * |B_{2g}| / (2g)!
    """
    if g < 1:
        raise ValueError(f"lambda_fp requires g >= 1, got {g}")
    # Bernoulli number B_{2g}
    B2g = _bernoulli_number_frac(2 * g)
    num = 2 ** (2 * g - 1) - 1
    den = 2 ** (2 * g - 1)
    return F(num, den) * abs(B2g) / F(math.factorial(2 * g))


def _bernoulli_number_frac(n: int) -> F:
    """Bernoulli number B_n as exact Fraction."""
    if n < 0:
        return F(0)
    if n == 1:
        return F(-1, 2)
    if n % 2 == 1 and n > 1:
        return F(0)
    B = [F(0)] * (n + 1)
    B[0] = F(1)
    for m in range(1, n + 1):
        B[m] = F(0)
        for k in range(m):
            B[m] -= F(math.comb(m, k), m - k + 1) * B[k]
    return B[n]


def shadow_fg_k3_relative(g: int) -> F:
    """Genus-g shadow amplitude for the relative K3 chiral algebra.

    F_g = kappa * lambda_g^FP = 2 * lambda_g^FP.
    """
    if g < 1:
        raise ValueError(f"F_g requires g >= 1, got {g}")
    return shadow_kappa_k3_sigma() * lambda_fp(g)


def shadow_denominator_connection() -> Dict[str, object]:
    """Connection between the shadow tower and the BKM denominator.

    The BKM denominator Phi_{10} encodes signed target denominator data.
    It becomes a Lie/Hall source statement only after a finite recognition
    datum supplies source spaces, parity fixtures, brackets, PBW, and
    comparison maps. The shadow obstruction tower Theta_A encodes the genus
    expansion of the chiral algebra A.

    KEY RELATIONSHIP: Both are controlled by MC elements in different
    convolution algebras:
    - Phi_{10}: Borcherds product = MC in the quantum torus algebra
    - Theta_A: MC in the modular cyclic deformation complex Def_cyc^mod(A)

    The lane separation: the K3 elliptic genus 2*phi_{0,1} supplies
    (a) finite signed-character input for the Borcherds product exponents,
    and
    (b) the protected genus-1 index of the K3 sigma model.

    So the genus-1 shadow kappa = 2 is connected to the BKM algebra via:
      kappa(K3) = chi(K3)/12 = 24/12 = 2
    and the finite super root samples are extracted from the same elliptic
    genus that determines kappa.

    At higher genus, a comparison of F_g(K3) with the BKM denominator is a
    scalar shadow target until a source-level forgetful/trace map and the
    finite Hall--Borcherds recognition datum are constructed.
    """
    return {
        'kappa_k3': shadow_kappa_k3_sigma(),
        'F_1': shadow_fg_k3_relative(1),
        'F_2': shadow_fg_k3_relative(2),
        'F_3': shadow_fg_k3_relative(3),
        'product_exp_c_minus1': SIGNED_BORCHERDS_EXPONENT_SAMPLES[-1],
        'product_exp_c0': SIGNED_BORCHERDS_EXPONENT_SAMPLES[0],
        'sample_real_even_dim': 1,
        'sample_lightlike_even_dim': SIGNED_BORCHERDS_EXPONENT_SAMPLES[0],
        'bridge': 'K3 EG = input to both Borcherds product and shadow tower',
    }


# ============================================================================
# Section 9: Enumeration and census
# ============================================================================

def enumerate_positive_roots(height_bound: int = 3) -> List[BKMRoot]:
    """Enumerate positive roots up to given height = n + m.

    Returns all positive roots (n, l, m) with n + m <= height_bound
    and the root having nonzero multiplicity from the K3 EG.
    """
    roots = []
    for n in range(0, height_bound + 1):
        for m in range(0, height_bound + 1 - n):
            for l in range(-height_bound - 2, height_bound + 3):
                root = BKMRoot(n, l, m)
                if not root.is_positive:
                    continue
                mult = root_multiplicity_direct(root)
                if mult != 0:
                    root.multiplicity = mult
                    roots.append(root)
    return roots


def root_norm_distribution(height_bound: int = 3) -> Dict[int, int]:
    """Distribution of root norms among positive roots.

    Returns: dict mapping norm^2 -> count of roots with that norm.
    """
    roots = enumerate_positive_roots(height_bound)
    dist: Dict[int, int] = {}
    for r in roots:
        ns = r.norm_sq
        dist[ns] = dist.get(ns, 0) + 1
    return dist


@dataclass
class BKMAlgebraSummary:
    """Summary of the BKM algebra for K3 x E."""
    real_simple_roots: List[BKMRoot]
    imaginary_simple_roots: List[BKMRoot]
    weyl_vector: BKMRoot
    weyl_group_infinite: bool
    c0_table: Dict[int, int]
    cartan_matrix_size: int
    shadow_kappa: F
    shadow_F1: F


def bkm_algebra_summary() -> BKMAlgebraSummary:
    """Compute a summary of the K3 BKM algebra."""
    real = simple_real_roots()
    imag = simple_imaginary_roots()
    rho = weyl_vector()

    return BKMAlgebraSummary(
        real_simple_roots=real,
        imaginary_simple_roots=imag,
        weyl_vector=rho,
        weyl_group_infinite=weyl_group_is_infinite(),
        c0_table=dict(SIGNED_BORCHERDS_EXPONENT_SAMPLES),
        cartan_matrix_size=1 + len(imag),
        shadow_kappa=shadow_kappa_k3_sigma(),
        shadow_F1=shadow_fg_k3_relative(1),
    )


# ============================================================================
# Section 10: Multi-path cross-checks
# ============================================================================

def cross_check_c0_consistency() -> bool:
    """Verify c_0(D) is consistent between direct computation and table.

    For D = 4 (which has two representatives in the phi01 table):
    (n=1, l=0): c = 108, c_K3 = 216
    (n=2, l=2): c = 108, c_K3 = 216
    Both give c_0(4) = 216.
    """
    # D = 4: check both representatives
    c1 = 2 * phi01_coeff(1, 0)   # n=1, l=0: 4*1 - 0 = 4
    c2 = 2 * phi01_coeff(2, 2)   # n=2, l=2: 4*2 - 4 = 4
    if c1 != c2:
        return False
    if c1 != SIGNED_BORCHERDS_EXPONENT_SAMPLES[4]:
        return False
    return True


def cross_check_phi01_sum_rule() -> bool:
    """Verify phi_{0,1}(tau, 0) = 12: sum_l c(n, l) = 12*delta_{n,0}."""
    # n = 0
    s0 = sum(phi01_coeff(0, l) for l in range(-5, 6))
    if s0 != 12:
        return False
    # n = 1
    s1 = sum(phi01_coeff(1, l) for l in range(-5, 6))
    if s1 != 0:
        return False
    # n = 2
    s2 = sum(phi01_coeff(2, l) for l in range(-5, 6))
    if s2 != 0:
        return False
    return True


def cross_check_root_norm() -> bool:
    """Verify root norm formula: alpha^2 = 2nm - l^2."""
    alpha = BKMRoot(1, 0, 1)
    if alpha.norm_sq != 2:
        return False
    alpha2 = BKMRoot(0, 1, 0)
    if alpha2.norm_sq != -1:
        return False
    alpha3 = BKMRoot(1, 1, 1)
    if alpha3.norm_sq != 1:
        return False
    alpha4 = BKMRoot(0, 0, 1)
    if alpha4.norm_sq != 0:
        return False
    return True


def cross_check_weyl_reflection() -> bool:
    """Verify Weyl reflection s_alpha is an involution: s_alpha^2 = id."""
    alpha = BKMRoot(1, 0, 1)  # Real simple root
    beta = BKMRoot(2, 1, 3)   # Test vector
    reflected = weyl_reflection(alpha, beta)
    double = weyl_reflection(alpha, reflected)
    return (double.n == beta.n and double.l == beta.l and double.m == beta.m)


def cross_check_reflection_preserves_norm() -> bool:
    """Verify Weyl reflection preserves the bilinear form."""
    alpha = BKMRoot(1, 0, 1)
    beta = BKMRoot(2, 1, 3)
    gamma = BKMRoot(1, -1, 2)
    s_beta = weyl_reflection(alpha, beta)
    s_gamma = weyl_reflection(alpha, gamma)
    # (s(beta), s(gamma)) should equal (beta, gamma)
    return s_beta.inner(s_gamma) == beta.inner(gamma)


def cross_check_rho_prefactor() -> bool:
    """Verify Weyl vector gives correct Phi_{10} prefactor.

    The Borcherds product starts with e^{2pi i (rho, Z)} = q*y*p.
    So rho should give (rho, Z) = tau + z + sigma, meaning the
    coefficient of the first Fourier term is at (1, 1, 1).
    """
    rho = weyl_vector()
    return rho.n == 1 and rho.l == 1 and rho.m == 1


def cross_check_phi10_leading() -> bool:
    """Verify the leading Phi_{10} coefficients against known values."""
    known = phi10_known_coefficients()
    # a(1, 1, 1) = 1
    if known.get((1, 1, 1)) != 1:
        return False
    # a(1, 0, 1) = -2
    if known.get((1, 0, 1)) != -2:
        return False
    # a(1, -1, 1) = 1
    if known.get((1, -1, 1)) != 1:
        return False
    return True


def cross_check_shadow_consistency() -> bool:
    """Verify shadow tower values for K3 relative.

    F_1 = kappa/24 = 2/24 = 1/12.
    F_2 = kappa * 7/5760 = 7/2880.
    """
    if shadow_fg_k3_relative(1) != F(1, 12):
        return False
    if shadow_fg_k3_relative(2) != F(7, 2880):
        return False
    return True


def cross_check_euler_char_product() -> bool:
    """Verify chi(K3 x E) = chi(K3) * chi(E) = 24 * 0 = 0."""
    return 24 * 0 == 0


def full_cross_check_battery() -> Dict[str, bool]:
    """Run all cross-checks and return results."""
    return {
        'c0_consistency': cross_check_c0_consistency(),
        'phi01_sum_rule': cross_check_phi01_sum_rule(),
        'root_norm': cross_check_root_norm(),
        'weyl_reflection_involution': cross_check_weyl_reflection(),
        'reflection_preserves_norm': cross_check_reflection_preserves_norm(),
        'rho_prefactor': cross_check_rho_prefactor(),
        'phi10_leading': cross_check_phi10_leading(),
        'shadow_consistency': cross_check_shadow_consistency(),
        'euler_char_product': cross_check_euler_char_product(),
    }
