"""Fulton-MacPherson compactification and configuration space forms.

FM_n(X) is the compactification of Conf_n(X) used for bar complex propagators.

Ground truth from the manuscript (configuration_spaces.tex, bar_cobar_construction.tex):
  - FM_n(C) is built by iterated real blowups along diagonals
  - FM_n(X) = Bl_{diags}(X^n), NOT X^n \\ Delta
  - Boundary strata: nested trees, operad structure
  - Log forms on FM: propagator omega_{ij} = d log(z_i - z_j)
  - Arnold relation: omega_{ij}^omega_{jk} + omega_{jk}^omega_{ki} + omega_{ki}^omega_{ij} = 0
  - Orlik-Solomon algebra: H*(Conf_n(C)) generated by eta_{ij} with Arnold
  - Poincare polynomial: P_t(Conf_n(C)) = prod_{j=1}^{n-1}(1+jt)
  - Top degree: dim H^{n-1}(Conf_n(C)) = (n-1)!

  From CLAUDE.md:
  - M-bar_{0,5} = Bl_4(P^2) (del Pezzo degree 5), dim H^2 = 5 (NOT P^2)
  - Normal bundle N_{Delta_S/X^n} = direct-sum T_X (tangent, NOT cotangent)

CONVENTIONS:
- Cohomological grading
"""

from __future__ import annotations

from math import factorial, comb
from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# Configuration space cohomology
# ---------------------------------------------------------------------------

def poincare_polynomial(n: int) -> List[int]:
    """Poincare polynomial of Conf_n(C).

    P_t = prod_{j=1}^{n-1}(1+jt).
    Returns [b_0, b_1, ..., b_{n-1}].
    """
    if n <= 0:
        return []
    poly = [1]
    for j in range(1, n):
        new_poly = [0] * (len(poly) + 1)
        for k, c in enumerate(poly):
            new_poly[k] += c
            new_poly[k + 1] += j * c
        poly = new_poly
    return poly


def os_dim(n: int, degree: int) -> int:
    """Dimension of H^degree(Conf_n(C)).

    From the Poincare polynomial.
    """
    poly = poincare_polynomial(n)
    if 0 <= degree < len(poly):
        return poly[degree]
    return 0


def os_top_dim(n: int) -> int:
    """Top-degree OS dimension = (n-1)!."""
    if n <= 0:
        return 0
    return factorial(n - 1)


def euler_char(n: int) -> int:
    """Euler characteristic of Conf_n(C).

    chi = P_{-1} = prod_{j=1}^{n-1}(1-j).
    For n >= 2: chi = 0 (odd Betti numbers equal even).
    Actually: chi = prod (1-j) for j=1..n-1.
    n=2: (1-1) = 0. n=3: (1-1)(1-2) = 0. Always 0 for n >= 2.
    n=1: empty product = 1.
    """
    if n <= 1:
        return 1
    result = 1
    for j in range(1, n):
        result *= (1 - j)
    return result


# ---------------------------------------------------------------------------
# Arnold relations
# ---------------------------------------------------------------------------

def arnold_relation_count(n: int) -> int:
    """Number of independent Arnold relations for n points.

    For each triple {i,j,k}, one Arnold relation:
    eta_{ij}^eta_{jk} + eta_{jk}^eta_{ki} + eta_{ki}^eta_{ij} = 0

    Total = C(n, 3).
    """
    return comb(n, 3)


def form_space_dim_after_arnold(n: int, degree: int) -> int:
    """Dimension of form space after Arnold relations.

    This equals H^degree(Conf_n(C)) = os_dim(n, degree).
    """
    return os_dim(n, degree)


# ---------------------------------------------------------------------------
# FM boundary strata
# ---------------------------------------------------------------------------

def fm_boundary_strata_count(n: int) -> int:
    """Number of codimension-1 boundary strata of FM_n(C).

    Each stratum corresponds to a subset S of {1,...,n} with |S| >= 2
    colliding to a point. The number of such subsets is
    sum_{k=2}^{n} C(n,k) = 2^n - n - 1.
    """
    return 2**n - n - 1


def fm_codim1_strata(n: int) -> List[Tuple[int, ...]]:
    """List codimension-1 boundary strata of FM_n(C).

    Each is a subset S with |S| >= 2 of {1,...,n} (points that collide).
    Returns subsets as sorted tuples.
    """
    from itertools import combinations
    strata = []
    for k in range(2, n + 1):
        for subset in combinations(range(1, n + 1), k):
            strata.append(subset)
    return strata


# ---------------------------------------------------------------------------
# Propagator forms
# ---------------------------------------------------------------------------

def propagator_form(i: int, j: int) -> str:
    """Log form omega_{ij} = d log(z_i - z_j).

    The propagator on FM_n(C) used for bar complex.
    """
    return f"d log(z_{i} - z_{j})"


def propagator_residue(i: int, j: int) -> str:
    """Residue of omega_{ij} along D_{ij} (collision divisor).

    Res_{D_{ij}} omega_{ij} = 1 (simple pole).
    This extracts OPE data via Res_{z_i=z_j} A(z_i)B(z_j).
    """
    return f"Res_{{D_{{{i}{j}}}}} omega_{{{i}{j}}} = 1"


# ---------------------------------------------------------------------------
# Special cases
# ---------------------------------------------------------------------------

def mbar_05_data() -> Dict[str, object]:
    """Data for M-bar_{0,5} = Bl_4(P^2) (del Pezzo degree 5).

    Ground truth: CLAUDE.md.
    """
    return {
        "blowup": "Bl_4(P^2)",
        "del_pezzo_degree": 5,
        "dim_H2": 5,  # NOT 1 (it's not P^2)
        "euler_char": 1 + 5 + 1,  # h^0 + h^2 + h^4 = 7? No, del Pezzo has h^2 = 5
        "note": "M-bar_{0,5} is a smooth surface (del Pezzo)",
    }


def normal_bundle_diagonal() -> str:
    """Normal bundle of diagonal in X^n.

    N_{Delta/X^n} = bigoplus T_X (TANGENT bundle, NOT cotangent).

    Ground truth: CLAUDE.md.
    """
    return "N_{Delta/X^n} = direct_sum T_X (tangent bundle)"


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify_fm():
    results = {}

    # Poincare polynomial
    results["P(Conf_2) = [1,1]"] = poincare_polynomial(2) == [1, 1]
    results["P(Conf_3) = [1,3,2]"] = poincare_polynomial(3) == [1, 3, 2]
    results["P(Conf_4) = [1,6,11,6]"] = poincare_polynomial(4) == [1, 6, 11, 6]

    # Top degrees
    results["top dim(2) = 1"] = os_top_dim(2) == 1
    results["top dim(3) = 2"] = os_top_dim(3) == 2
    results["top dim(4) = 6"] = os_top_dim(4) == 6
    results["top dim(5) = 24"] = os_top_dim(5) == 24

    # Arnold
    results["Arnold rels(3) = 1"] = arnold_relation_count(3) == 1
    results["Arnold rels(4) = 4"] = arnold_relation_count(4) == 4
    results["Arnold rels(5) = 10"] = arnold_relation_count(5) == 10

    # FM boundary strata
    results["FM_3 strata = 4"] = fm_boundary_strata_count(3) == 4
    results["FM_4 strata = 11"] = fm_boundary_strata_count(4) == 11

    # Euler char
    results["chi(Conf_1) = 1"] = euler_char(1) == 1
    results["chi(Conf_2) = 0"] = euler_char(2) == 0
    results["chi(Conf_3) = 0"] = euler_char(3) == 0

    # M-bar_{0,5}
    m05 = mbar_05_data()
    results["M05 is del Pezzo deg 5"] = m05["del_pezzo_degree"] == 5
    results["M05 dim H^2 = 5"] = m05["dim_H2"] == 5

    return results


if __name__ == "__main__":
    print("=" * 60)
    print("FM COMPACTIFICATION: VERIFICATION")
    print("=" * 60)

    for name, ok in verify_fm().items():
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
