"""Genus-3 stable graph enumeration and amplitude computation.

Extends stable_graph_enumeration.py to genus 3, the first genus where
genuinely rich graph topology appears (three-loop graphs, theta subgraphs,
banana chains, K_4 complete graph, etc.).

The genus-3 amplitude decomposition provides:
1. lambda_3^FP = (2^5 - 1)/2^5 * |B_6|/6! = 31/967680
2. F_3(H_k) = k * 31/967680
3. Graph-by-graph decomposition for all standard families
4. Genus spectral sequence E_1 at p = 3

GENUS-3 GRAPH TYPES (42 total, n = 0):
  h^1 = 0 (trees):       4 graphs, vertices carry total genus 3
  h^1 = 1 (one-loop):    9 graphs, vertices carry total genus 2
  h^1 = 2 (two-loop):   14 graphs, vertices carry total genus 1
  h^1 = 3 (three-loop): 15 graphs, vertices carry genus 0 (deepest stratum)

BOUNDARY STRATA:
  codim 0:  1 graph  (smooth genus-3 curve)
  codim 1:  2 graphs (irreducible node Delta_irr, separating node Delta_1)
  codim 2:  5 graphs
  codim 3:  9 graphs
  codim 4: 12 graphs
  codim 5:  8 graphs
  codim 6:  5 graphs (deepest: includes K_4 = complete graph on 4 vertices)

References:
  - Faber, "A conjectural description of the tautological ring" (1999)
  - Harer-Zagier, "The Euler characteristic of the moduli space of curves" (1986)
  - higher_genus_modular_koszul.tex: def:stable-graph-coefficient-algebra
  - concordance.tex: const:vol1-genus-spectral-sequence
"""

from __future__ import annotations

from fractions import Fraction
from typing import Dict, List, Tuple

from compute.lib.stable_graph_enumeration import (
    StableGraph,
    enumerate_stable_graphs,
    orbifold_euler_characteristic,
    graph_weight,
    graph_sum_scalar,
    _bernoulli_exact,
    _lambda_fp_exact,
    _chi_orb_open,
)


# ---------------------------------------------------------------------------
# Genus-3 stable graph classification
# ---------------------------------------------------------------------------

# Shadow depth classes from concordance.tex:
#   G (Gaussian):  r_max = 2 (Heisenberg)
#   L (Lie/tree):  r_max = 3 (affine Kac-Moody)
#   C (contact):   r_max = 4 (beta-gamma)
#   M (mixed):     r_max = inf (Virasoro, W_N)
SHADOW_DEPTH_CLASSES = ("G", "L", "C", "M")


def genus3_stable_graphs_n0() -> List[StableGraph]:
    """Complete enumeration of the 42 genus-3 stable graphs with n = 0.

    Generated by the general engine in stable_graph_enumeration.py and
    validated against the orbifold Euler characteristic
    chi^orb(M_bar_{3,0}) = -12419/90720.

    The 42 graphs decompose as:
      |V| = 1:  4 graphs (smooth, irr-node, double-loop, triple-loop)
      |V| = 2: 12 graphs
      |V| = 3: 15 graphs
      |V| = 4: 11 graphs

    By loop number h^1:
      h^1 = 0:  4 (trees)
      h^1 = 1:  9 (one-loop)
      h^1 = 2: 14 (two-loop)
      h^1 = 3: 15 (three-loop)
    """
    return enumerate_stable_graphs(3, 0)


def genus3_graph_count() -> int:
    """Total count of genus-3 stable graphs with n = 0: 42."""
    return len(genus3_stable_graphs_n0())


def genus3_automorphism_table() -> Dict[int, List[int]]:
    """Automorphism orders grouped by graph index.

    Returns a dictionary {graph_index: |Aut(Gamma)|} for each of the
    42 genus-3 stable graphs (0-indexed).

    The sorted automorphism spectrum is:
      [1, 1, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       6, 6, 6, 8, 8, 8, 8, 8, 8, 8, 8, 12, 12, 16, 16, 16, 16, 16,
       24, 48, 48, 48]
    """
    graphs = genus3_stable_graphs_n0()
    return {i: g.automorphism_order() for i, g in enumerate(graphs)}


def genus3_automorphism_spectrum() -> List[int]:
    """Sorted list of all automorphism orders for genus-3 n=0 graphs."""
    return sorted(g.automorphism_order() for g in genus3_stable_graphs_n0())


# ---------------------------------------------------------------------------
# Orbifold Euler characteristic
# ---------------------------------------------------------------------------

def genus3_euler_check() -> Tuple[Fraction, Fraction, bool]:
    """Verify the orbifold Euler characteristic of M_bar_{3,0}.

    The vertex-product formula gives:
      chi^orb(M_bar_{3,0}) = sum_Gamma prod_v chi^orb(M_{g(v),val(v)}) / |Aut(Gamma)|

    The known value from the graph sum is -12419/90720.

    Returns (computed_chi, expected_chi, match).
    """
    graphs = genus3_stable_graphs_n0()
    computed = orbifold_euler_characteristic(graphs)
    expected = Fraction(-12419, 90720)
    return (computed, expected, computed == expected)


def genus3_euler_decomposition() -> List[Tuple[int, Fraction]]:
    """Per-graph orbifold Euler characteristic contributions.

    Returns a list of (graph_index, chi_contribution) pairs.
    The sum of all contributions equals chi^orb(M_bar_{3,0}).
    """
    graphs = genus3_stable_graphs_n0()
    result = []
    for i, gamma in enumerate(graphs):
        val = gamma.valence
        vertex_product = Fraction(1)
        for v in range(gamma.num_vertices):
            vertex_product *= _chi_orb_open(gamma.vertex_genera[v], val[v])
        contrib = vertex_product / Fraction(gamma.automorphism_order())
        result.append((i, contrib))
    return result


# ---------------------------------------------------------------------------
# Lambda number and Faber-Pandharipande
# ---------------------------------------------------------------------------

def lambda3_fp() -> Fraction:
    """Faber-Pandharipande intersection number at genus 3.

    lambda_3^FP = (2^5 - 1) |B_6| / (2^5 * 6!)
               = 31 * (1/42) / (32 * 720)
               = 31 / 967680

    This is the tautological integral:
      int_{M_bar_{3,1}} psi^4 lambda_3 = 31/967680
    """
    return _lambda_fp_exact(3)


# ---------------------------------------------------------------------------
# Amplitude computations
# ---------------------------------------------------------------------------

def genus3_amplitudes_heisenberg(k: Fraction = Fraction(1),
                                 d: int = 1) -> Fraction:
    """Genus-3 free energy for Heisenberg of rank d at level k.

    F_3(H_k^d) = kappa(H_k^d) * lambda_3^FP = k * d * 31/967680

    Heisenberg is shadow-depth class G (Gaussian, r_max = 2): the shadow
    tower terminates at arity 2, so F_g is purely determined by kappa.
    No cubic or higher corrections.
    """
    kappa = k * d
    return kappa * lambda3_fp()


def genus3_amplitudes_affine(k: Fraction, g_type: str = "sl2") -> Fraction:
    """Genus-3 free energy for affine Kac-Moody V_k(g).

    F_3(V_k(g)) = kappa(V_k(g)) * lambda_3^FP + (cubic shadow corrections)

    At the SCALAR level (shadow depth class L, r_max = 3), the cubic
    shadow C_3 contributes a correction proportional to the structure
    constants. For the purpose of this module, we compute the scalar
    (kappa-only) contribution:

      kappa(V_k(g)) = dim(g) * (k + h^v) / 2

    The cubic correction is genus-dependent and involves integration
    over M_{g(v), val(v)} at vertices with val >= 3. At genus 3 the
    correction involves all graphs with at least one vertex of valence >= 3.

    Supported types: "sl2" (dim=3, h^v=2), "sl3" (dim=8, h^v=3),
    "slN" with N given, or general (dim, h_vee) pair.

    Returns the scalar-level F_3 (kappa contribution only).
    """
    if g_type == "sl2":
        dim_g, h_vee = 3, 2
    elif g_type == "sl3":
        dim_g, h_vee = 8, 3
    elif g_type.startswith("sl"):
        N = int(g_type[2:])
        dim_g = N * N - 1
        h_vee = N
    else:
        raise ValueError(f"Unknown type: {g_type}. Use 'sl2', 'sl3', 'slN'.")

    kappa = Fraction(dim_g) * (k + h_vee) / Fraction(2)
    return kappa * lambda3_fp()


def genus3_amplitudes_affine_general(k: Fraction, dim_g: int,
                                     h_vee: int) -> Fraction:
    """Genus-3 scalar free energy for V_k(g) with explicit dim and h^v.

    kappa(V_k(g)) = dim(g) * (k + h^v) / 2
    F_3 = kappa * lambda_3^FP   (scalar level)
    """
    kappa = Fraction(dim_g) * (k + h_vee) / Fraction(2)
    return kappa * lambda3_fp()


def genus3_amplitudes_virasoro(c: Fraction) -> Fraction:
    """Genus-3 free energy for Virasoro at central charge c.

    F_3(Vir_c) = kappa(Vir_c) * lambda_3^FP + (higher shadow corrections)

    kappa(Vir_c) = c/2. Virasoro is shadow-depth class M (mixed, r_max = inf),
    so the full answer involves the infinite shadow tower. This function
    returns the scalar-level (kappa-only) contribution.

    The cubic correction is proportional to c and involves only graphs with
    at least one vertex of valence >= 3 carrying a genus >= 1 vertex.
    The quartic contact invariant Q^contact_Vir = 10/[c(5c+22)] is nonzero,
    confirming that the quartic correction is present at genus 3.
    """
    kappa = c / Fraction(2)
    return kappa * lambda3_fp()


def genus3_amplitudes_betagamma() -> Fraction:
    """Genus-3 scalar free energy for beta-gamma (bc ghost system).

    kappa(beta-gamma) = -2 (the negative value reflects the fermionic ghost
    number anomaly). Shadow-depth class C (contact, r_max = 4).

    At the scalar level: F_3 = -2 * lambda_3^FP = -2 * 31/967680
                              = -31/483840
    """
    kappa = Fraction(-2)
    return kappa * lambda3_fp()


# ---------------------------------------------------------------------------
# Spectral sequence decomposition
# ---------------------------------------------------------------------------

def genus3_spectral_sequence_e1() -> Dict[int, List[StableGraph]]:
    """Genus spectral sequence E_1 page at total genus 3.

    Separates the 42 graphs by loop number h^1 = p. The E_1 page is:
      E_1^{p,q} with p + q = 3 - 1 = 2... actually, the filtration by
      loop genus gives:
        p = 0: trees (h^1 = 0), 4 graphs
        p = 1: one-loop (h^1 = 1), 9 graphs
        p = 2: two-loop (h^1 = 2), 14 graphs
        p = 3: three-loop (h^1 = 3), 15 graphs

    The differentials d_r: E_r^{p,q} -> E_r^{p+r, q-r+1} are the
    obstruction maps Ob_g from the genus spectral sequence
    (const:vol1-genus-spectral-sequence).

    Returns {h1: [list of graphs]}.
    """
    graphs = genus3_stable_graphs_n0()
    result: Dict[int, List[StableGraph]] = {}
    for g in graphs:
        h1 = g.first_betti
        result.setdefault(h1, []).append(g)
    return result


def genus3_spectral_sequence_counts() -> Dict[int, int]:
    """Count of graphs at each loop level.

    Returns {h1: count}:
      0 -> 4, 1 -> 9, 2 -> 14, 3 -> 15
    """
    pages = genus3_spectral_sequence_e1()
    return {h1: len(graphs) for h1, graphs in pages.items()}


# ---------------------------------------------------------------------------
# Boundary strata
# ---------------------------------------------------------------------------

def genus3_boundary_strata() -> Dict[int, List[StableGraph]]:
    """Classify boundary components of M_bar_{3,0} by codimension.

    The boundary Delta = M_bar_{3,0} - M_3 consists of all graphs with
    at least one edge. The codimension of a stratum is the number of
    edges (= number of nodes of the curve).

    dim(M_bar_{3,0}) = 3(3) - 3 = 6, so:
      codim 0:  1 graph  (interior = smooth genus-3 curve)
      codim 1:  2 graphs (irreducible node g=2, separating g=2+1)
      codim 2:  5 graphs
      codim 3:  9 graphs
      codim 4: 12 graphs
      codim 5:  8 graphs
      codim 6:  5 graphs (maximally degenerate, |E| = dim(M) = 6)

    The boundary divisors at codimension 1 are:
      Delta_0 (irreducible): genus-2 curve with a non-separating node
      Delta_1 (separating):  genus-2 + genus-1 curves joined at a point

    Returns {codimension: [list of graphs]}.
    """
    graphs = genus3_stable_graphs_n0()
    result: Dict[int, List[StableGraph]] = {}
    for g in graphs:
        codim = g.num_edges
        result.setdefault(codim, []).append(g)
    return result


def genus3_boundary_divisor_types() -> Dict[str, List[StableGraph]]:
    """Classify the codimension-1 boundary divisors of M_bar_{3,0}.

    Returns:
      "Delta_irr": the irreducible boundary (1 vertex g=2, 1 self-loop)
      "Delta_1": the separating node (vertices g=2 and g=1, 1 edge)

    These are the two boundary divisors of M_bar_{3,0} at codimension 1.
    """
    graphs = genus3_stable_graphs_n0()
    codim1 = [g for g in graphs if g.num_edges == 1]

    result: Dict[str, List[StableGraph]] = {"Delta_irr": [], "Delta_1": []}
    for g in codim1:
        if g.num_vertices == 1:
            # Self-loop on a single vertex: irreducible boundary
            result["Delta_irr"].append(g)
        else:
            # Two vertices joined by an edge: separating node
            result["Delta_1"].append(g)
    return result


# ---------------------------------------------------------------------------
# Graph profiles by shadow depth class
# ---------------------------------------------------------------------------

def genus3_graph_profiles(family: str = "G") -> Dict[str, object]:
    """Which graphs are active for each shadow depth class.

    At the scalar level (class G = Gaussian, Heisenberg), ALL graphs
    contribute via kappa^|E| / |Aut|.

    For shadow-depth class L (Lie/tree, r_max = 3), the cubic correction
    activates at graphs with at least one vertex of valence >= 3.

    For class C (contact, r_max = 4), the quartic correction activates
    at graphs with at least one vertex of valence >= 4.

    For class M (mixed, r_max = inf), all arity corrections are active.

    Returns a dict with keys:
      "active_count": number of graphs receiving corrections beyond scalar
      "scalar_only_count": number of graphs at pure scalar level
      "active_graphs": list of graph indices receiving higher corrections
      "scalar_sum": the pure scalar sum for this family
    """
    graphs = genus3_stable_graphs_n0()

    if family == "G":
        # Gaussian: shadow terminates at arity 2, everything is scalar
        min_val_for_correction = 999  # never triggers
    elif family == "L":
        # Lie/tree: cubic correction at valence >= 3
        min_val_for_correction = 3
    elif family == "C":
        # Contact: quartic correction at valence >= 4
        min_val_for_correction = 4
    elif family == "M":
        # Mixed: corrections at all arities >= 3
        min_val_for_correction = 3
    else:
        raise ValueError(f"Unknown family: {family}. Use 'G', 'L', 'C', 'M'.")

    active = []
    scalar_only = []
    for i, g in enumerate(graphs):
        max_val = max(g.valence)
        if max_val >= min_val_for_correction:
            active.append(i)
        else:
            scalar_only.append(i)

    # Scalar sum with kappa = 1 for normalization
    scalar_sum = graph_sum_scalar(graphs, kappa=Fraction(1))

    return {
        "active_count": len(active),
        "scalar_only_count": len(scalar_only),
        "active_graphs": active,
        "scalar_only_graphs": scalar_only,
        "scalar_sum_kappa1": scalar_sum,
    }


# ---------------------------------------------------------------------------
# Scalar graph sum (polynomial in kappa)
# ---------------------------------------------------------------------------

def genus3_scalar_sum_polynomial() -> Dict[int, Fraction]:
    """Scalar graph sum as a polynomial in kappa.

    sum_Gamma kappa^|E(Gamma)| / |Aut(Gamma)| = sum_{e=0}^{6} c_e * kappa^e

    where c_e = sum_{Gamma: |E|=e} 1/|Aut(Gamma)|.

    Returns {edge_count: coefficient}:
      0 -> 1
      1 -> 3/2
      2 -> 15/8
      3 -> 107/48
      4 -> 97/48
      5 -> 55/48
      6 -> 5/16
    """
    graphs = genus3_stable_graphs_n0()
    coeffs: Dict[int, Fraction] = {}
    for g in graphs:
        ne = g.num_edges
        coeffs[ne] = coeffs.get(ne, Fraction(0)) + Fraction(1, g.automorphism_order())
    return coeffs


def genus3_scalar_sum_at(kappa: Fraction) -> Fraction:
    """Evaluate the scalar graph sum at a specific kappa value.

    This is sum_Gamma kappa^|E(Gamma)| / |Aut(Gamma)|.
    """
    return graph_sum_scalar(genus3_stable_graphs_n0(), kappa=kappa)


# ---------------------------------------------------------------------------
# Graph weight sum (signed)
# ---------------------------------------------------------------------------

def genus3_graph_weight_sum() -> Fraction:
    """Sum of signed graph weights: sum_Gamma (-1)^|E| / |Aut(Gamma)|.

    For genus 3, n = 0, this equals 1/3.

    This is the coefficient of the genus-3 term in the expansion of
    the Euler characteristic of the free algebra.
    """
    return sum(graph_weight(g) for g in genus3_stable_graphs_n0())


# ---------------------------------------------------------------------------
# Vertex count and edge count statistics
# ---------------------------------------------------------------------------

def genus3_by_vertex_count() -> Dict[int, int]:
    """Count of genus-3 stable graphs by number of vertices.

    Returns {num_vertices: count}:
      1 -> 4, 2 -> 12, 3 -> 15, 4 -> 11
    """
    graphs = genus3_stable_graphs_n0()
    result: Dict[int, int] = {}
    for g in graphs:
        nv = g.num_vertices
        result[nv] = result.get(nv, 0) + 1
    return result


def genus3_by_edge_count() -> Dict[int, int]:
    """Count of genus-3 stable graphs by number of edges.

    Returns {num_edges: count}:
      0 -> 1, 1 -> 2, 2 -> 5, 3 -> 9, 4 -> 12, 5 -> 8, 6 -> 5
    """
    graphs = genus3_stable_graphs_n0()
    result: Dict[int, int] = {}
    for g in graphs:
        ne = g.num_edges
        result[ne] = result.get(ne, 0) + 1
    return result


# ---------------------------------------------------------------------------
# Named graph identification
# ---------------------------------------------------------------------------

def genus3_named_graphs() -> Dict[str, StableGraph]:
    """Identify the most important named graphs at genus 3.

    Returns a dictionary of descriptive names to StableGraph objects
    for the key graph types that appear in the modular Koszul theory:

    Single-vertex (4):
      "smooth":       g=3, no edges. The interior of M_3.
      "irr_node":     g=2, 1 self-loop. Delta_irr restricted to genus 3.
      "double_loop":  g=1, 2 self-loops. The banana at genus 1.
      "triple_loop":  g=0, 3 self-loops. Deepest single-vertex graph.

    Two-vertex, notable (4):
      "separating_21":  g=(2,1), 1 edge. Separating boundary Delta_1.
      "parallel_11":    g=(1,1), 2 parallel edges. One-loop cylinder.
      "theta_10":       g=(1,0), 3 parallel edges. Theta with genus shift.
      "quadruple_00":   g=(0,0), 4 parallel edges. h^1 = 3 banana-4.

    Tree (4):
      "tree_3":         Smooth genus-3. (= smooth above)
      "tree_21":        g=(2,1), 1 edge. (= separating_21 above)
      "tree_111_chain": g=(1,1,1), 2-edge chain.
      "tree_1110_star": g=(1,1,1,0), 3-edge star with central g=0.

    Deepest stratum (1):
      "K4":  Complete graph K_4 on 4 genus-0 vertices. 6 edges. |Aut| = 24.
    """
    graphs = genus3_stable_graphs_n0()
    named = {}

    for g in graphs:
        nv = g.num_vertices
        ne = g.num_edges
        vg = g.vertex_genera

        # Single-vertex graphs
        if nv == 1:
            loops = g.self_loop_count(0)
            if loops == 0:
                named["smooth"] = g
            elif loops == 1:
                named["irr_node"] = g
            elif loops == 2:
                named["double_loop"] = g
            elif loops == 3:
                named["triple_loop"] = g

        # Two-vertex graphs: pick notable ones
        elif nv == 2:
            multi = g.edge_multiplicity(0, 1)
            l0, l1 = g.self_loop_count(0), g.self_loop_count(1)
            sorted_genera = tuple(sorted(vg))

            if sorted_genera == (1, 2) and ne == 1:
                named["separating_21"] = g
            elif sorted_genera == (1, 1) and multi == 2 and l0 == 0 and l1 == 0:
                named["parallel_11"] = g
            elif sorted_genera == (0, 1) and multi == 3:
                named["theta_10"] = g
            elif sorted_genera == (0, 0) and multi == 4:
                named["quadruple_00"] = g

        # Three-vertex trees
        elif nv == 3 and g.first_betti == 0:
            named["tree_111_chain"] = g

        # Four-vertex special
        elif nv == 4:
            if g.first_betti == 0:
                named["tree_1110_star"] = g
            elif (ne == 6 and all(gv == 0 for gv in vg)
                  and g.automorphism_order() == 24):
                # K_4: complete graph, every pair connected by exactly one edge
                # Check: 6 edges on 4 vertices, all distinct pairs
                edge_set = set(g.edges)
                if len(edge_set) == 6:
                    named["K4"] = g

    return named


# ---------------------------------------------------------------------------
# Consistency with genus 2
# ---------------------------------------------------------------------------

def genus3_genus2_consistency_check() -> bool:
    """Verify structural consistency between genus-2 and genus-3 enumerations.

    Check 1: The number of genus-2 graphs (6) is less than genus-3 (42).
    Check 2: lambda_2 and lambda_3 satisfy the correct ratio:
      lambda_3 / lambda_2 = (31/967680) / (7/5760) = 31*5760 / (7*967680)
                          = 178560 / 6773760 = 31 / 1176 = 31/(168*7)
    Check 3: The orbifold Euler characteristics are computed from the same formula.
    """
    from compute.lib.stable_graph_enumeration import genus2_stable_graphs_n0
    g2 = genus2_stable_graphs_n0()
    g3 = genus3_stable_graphs_n0()

    # Check 1: count growth
    if not (len(g3) > len(g2)):
        return False

    # Check 2: lambda ratio
    l2 = _lambda_fp_exact(2)
    l3 = _lambda_fp_exact(3)
    ratio = l3 / l2
    expected_ratio = Fraction(31 * 5760, 7 * 967680)
    if ratio != expected_ratio:
        return False

    # Check 3: Euler characteristics from same engine
    chi2 = orbifold_euler_characteristic(g2)
    chi3 = orbifold_euler_characteristic(g3)
    if chi2 != Fraction(-181, 1440):
        return False
    if chi3 != Fraction(-12419, 90720):
        return False

    return True


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def genus3_summary() -> Dict[str, object]:
    """Complete summary of genus-3 stable graph data.

    Returns a dictionary with all key invariants:
      total_graphs: 42
      by_h1: {0: 4, 1: 9, 2: 14, 3: 15}
      by_vertices: {1: 4, 2: 12, 3: 15, 4: 11}
      by_edges: {0: 1, 1: 2, 2: 5, 3: 9, 4: 12, 5: 8, 6: 5}
      aut_spectrum: sorted list of |Aut| values
      chi_orb_mbar: -12419/90720
      chi_orb_open: 1/1008
      lambda3_fp: 31/967680
      graph_weight_sum: 1/3
      scalar_sum_kappa1: 121/12
    """
    graphs = genus3_stable_graphs_n0()
    return {
        "total_graphs": len(graphs),
        "by_h1": genus3_spectral_sequence_counts(),
        "by_vertices": genus3_by_vertex_count(),
        "by_edges": genus3_by_edge_count(),
        "aut_spectrum": genus3_automorphism_spectrum(),
        "chi_orb_mbar": orbifold_euler_characteristic(graphs),
        "chi_orb_open": _chi_orb_open(3, 0),
        "lambda3_fp": lambda3_fp(),
        "graph_weight_sum": genus3_graph_weight_sum(),
        "scalar_sum_kappa1": genus3_scalar_sum_at(Fraction(1)),
    }
