"""Homotopy Koszul dual A!_infty = D(B-bar(A)) for non-Koszul algebras.

For a Koszul algebra A, the bar cohomology H*(B(A)) is concentrated in
a single internal degree, and the transferred A-infinity structure is
formal (m_k = 0 for k >= 3). Off the Koszul locus, genuine higher
operations m_3, m_4, ... appear.

MAIN COMPUTATION: For A = k[x]/(x^n) (augmented by x -> 0):
- B(A) = T^c(s * I) with I = (x, x^2, ..., x^{n-1}), the bar differential
- H*(B(A)) = Tor^A(k, k), the bar cohomology as a coalgebra
- The A-infinity structure on H*(B(A)) via homological perturbation lemma

For n = 2: A = k[x]/(x^2) = k[epsilon] (dual numbers). This IS Koszul:
  B(A) has cohomology k in each degree, generated by [epsilon|...|epsilon].
  A! = k[y] (polynomial ring). All m_k = 0 for k >= 3.

For n = 3: A = k[x]/(x^3). This is NOT Koszul (not quadratic in the
  graded sense needed). Bar cohomology is NOT generated in degree 1.
  Genuine m_3 appears = Massey product.

For n >= 3: increasingly complex A-infinity structure.

GRADING: We use HOMOLOGICAL grading on B(A). The bar construction
B(A) = bigoplus_{p >= 0} (s*I)^{otimes p} with |s*a| = |a| - 1.
The bar differential d: B_p -> B_{p-1} has degree -1.
"""

from __future__ import annotations

import numpy as np
from itertools import product as cartesian_product
from typing import Dict, List, Optional, Tuple
from fractions import Fraction


# =========================================================================
# Truncated polynomial algebra A = k[x]/(x^n)
# =========================================================================

class TruncatedPolynomialAlgebra:
    """A = k[x]/(x^n), augmented by x -> 0.

    Basis of A: {1, x, x^2, ..., x^{n-1}}
    Augmentation ideal I: {x, x^2, ..., x^{n-1}}, dim = n-1
    Multiplication: x^a * x^b = x^{a+b} if a+b < n, else 0.

    We work over Q (using Fraction for exactness).
    """

    def __init__(self, n: int):
        assert n >= 2, "Need n >= 2 for nontrivial algebra"
        self.n = n
        self.aug_ideal_dim = n - 1  # basis: x, x^2, ..., x^{n-1}

    def multiply(self, a: int, b: int) -> Optional[int]:
        """Multiply basis elements x^{a+1} and x^{b+1} of the aug ideal.

        a, b are 0-indexed: element a corresponds to x^{a+1}.
        Returns index c (0-indexed) of x^{a+1+b+1} = x^{a+b+2},
        or None if the product is zero (i.e., a+b+2 >= n).
        """
        power = (a + 1) + (b + 1)
        if power >= self.n:
            return None
        return power - 1  # 0-indexed: x^power -> index power-1

    def multiply_indices(self, indices: List[int]) -> Optional[int]:
        """Multiply a list of augmentation ideal basis elements.

        Each index i means x^{i+1}. Product = x^{sum(i+1)}.
        Returns index of result, or None if zero.
        """
        total_power = sum(i + 1 for i in indices)
        if total_power >= self.n:
            return None
        return total_power - 1


# =========================================================================
# Bar complex of k[x]/(x^n)
# =========================================================================

class BarComplex:
    """Bar complex B(A) for A = k[x]/(x^n).

    B_p = (sI)^{otimes p} has basis indexed by tuples (a_1, ..., a_p)
    where each a_i in {0, ..., n-2} (representing x^{a_i+1}).

    The bar differential d_1: B_p -> B_{p-1} is:
    d_1[a_1|...|a_p] = sum_{i=1}^{p-1} (-1)^i [a_1|...|mu(a_i,a_{i+1})|...|a_p]
    where mu(a_i, a_{i+1}) is the product in A (if nonzero).
    """

    def __init__(self, algebra: TruncatedPolynomialAlgebra):
        self.A = algebra
        self.d = algebra.aug_ideal_dim  # dimension of augmentation ideal

    def basis_size(self, p: int) -> int:
        """Dimension of B_p = (sI)^{otimes p}."""
        if p <= 0:
            return 1 if p == 0 else 0
        return self.d ** p

    def _index_to_tuple(self, p: int, idx: int) -> Tuple[int, ...]:
        """Convert flat index to tuple of basis elements."""
        result = []
        for _ in range(p):
            result.append(idx % self.d)
            idx //= self.d
        return tuple(reversed(result))

    def _tuple_to_index(self, tup: Tuple[int, ...]) -> int:
        """Convert tuple of basis elements to flat index."""
        idx = 0
        for a in tup:
            idx = idx * self.d + a
        return idx

    def differential_matrix(self, p: int) -> np.ndarray:
        """Bar differential d: B_p -> B_{p-1} as a matrix over Q.

        Returns matrix M where M[target_idx, source_idx] = coefficient.
        Uses exact rational arithmetic via Fraction, stored as float.
        """
        if p <= 1:
            return np.zeros((self.basis_size(max(p - 1, 0)),
                             self.basis_size(p)))

        src_dim = self.basis_size(p)
        tgt_dim = self.basis_size(p - 1)
        M = np.zeros((tgt_dim, src_dim), dtype=float)

        for src_idx in range(src_dim):
            tup = self._index_to_tuple(p, src_idx)
            for i in range(p - 1):
                # Multiply a_i and a_{i+1}
                prod = self.A.multiply(tup[i], tup[i + 1])
                if prod is None:
                    continue
                # Build target tuple: replace (a_i, a_{i+1}) with prod
                new_tup = tup[:i] + (prod,) + tup[i + 2:]
                tgt_idx = self._tuple_to_index(new_tup)
                sign = (-1) ** (i + 1)  # standard bar sign convention
                M[tgt_idx, src_idx] += sign

        return M

    def verify_d_squared(self, p: int) -> float:
        """Check ||d_{p-1} d_p|| for d^2 = 0 verification."""
        if p <= 2:
            return 0.0
        d_p = self.differential_matrix(p)
        d_pm1 = self.differential_matrix(p - 1)
        d_sq = d_pm1 @ d_p
        return np.max(np.abs(d_sq))

    def cohomology_dim(self, p: int, max_p: int = None) -> int:
        """Dimension of H_p(B(A)) = ker(d_p) / im(d_{p+1}).

        Note: we use homological convention, d lowers degree.
        """
        if max_p is None:
            max_p = p + 1

        d_p = self.differential_matrix(p)
        d_pp1 = self.differential_matrix(p + 1)

        dim_Bp = self.basis_size(p)

        if dim_Bp == 0:
            return 0

        # ker(d_p)
        if d_p.shape[0] == 0 or d_p.shape[1] == 0:
            ker_dim = dim_Bp
        else:
            rank_dp = np.linalg.matrix_rank(d_p, tol=1e-10)
            ker_dim = dim_Bp - rank_dp

        # im(d_{p+1})
        if d_pp1.shape[0] == 0 or d_pp1.shape[1] == 0:
            im_dim = 0
        else:
            im_dim = np.linalg.matrix_rank(d_pp1, tol=1e-10)

        return ker_dim - im_dim

    def cohomology_all(self, max_p: int) -> Dict[int, int]:
        """Compute H_p(B(A)) for p = 0, 1, ..., max_p."""
        result = {}
        for p in range(max_p + 1):
            result[p] = self.cohomology_dim(p, max_p + 1)
        return result


# =========================================================================
# Homological Perturbation Lemma for A-infinity transfer
# =========================================================================

class AInfinityTransfer:
    """Compute the transferred A-infinity structure on H*(B(A)).

    Given the bar complex (B, d) with a decomposition B = H + C
    (cohomology + complement), the HPL produces an A-infinity
    structure on H with operations m_k for k >= 2.

    For the bar complex of an augmented algebra, this gives the
    A-infinity coalgebra structure on Tor^A(k, k).

    The dual gives the A-infinity algebra structure on Ext_A(k, k) = A!_infty.
    """

    def __init__(self, bar: BarComplex, max_p: int):
        self.bar = bar
        self.max_p = max_p
        self._compute_hdr()

    def _compute_hdr(self):
        """Compute the Hodge decomposition data (pi, iota, h).

        For each bar degree p:
        - pi_p: B_p -> H_p (projection to cohomology)
        - iota_p: H_p -> B_p (inclusion of representatives)
        - h_p: B_p -> B_{p+1} (contracting homotopy, dh + hd = id - iota*pi)

        We use SVD to find ker/im decomposition.
        """
        self.pi = {}      # pi[p] = matrix H_p <- B_p
        self.iota = {}    # iota[p] = matrix B_p <- H_p
        self.h = {}       # h[p] = matrix B_{p+1} <- B_p
        self.H_dims = {}  # dimension of H_p

        for p in range(self.max_p + 2):
            d_p = self.bar.differential_matrix(p)
            d_pp1 = self.bar.differential_matrix(p + 1)

            dim_Bp = self.bar.basis_size(p)
            if dim_Bp == 0:
                self.H_dims[p] = 0
                self.pi[p] = np.zeros((0, 0))
                self.iota[p] = np.zeros((0, 0))
                self.h[p] = np.zeros((self.bar.basis_size(p + 1), 0))
                continue

            # Find ker(d_p)
            if d_p.shape[0] == 0:
                ker_basis = np.eye(dim_Bp)
            else:
                U, S, Vt = np.linalg.svd(d_p, full_matrices=True)
                rank_dp = np.sum(S > 1e-10)
                ker_basis = Vt[rank_dp:].T  # columns are kernel basis

            # Find im(d_{p+1})
            if d_pp1.shape[0] == 0 or d_pp1.shape[1] == 0:
                im_basis = np.zeros((dim_Bp, 0))
            else:
                U2, S2, Vt2 = np.linalg.svd(d_pp1, full_matrices=True)
                rank_dpp1 = np.sum(S2 > 1e-10)
                im_basis = U2[:, :rank_dpp1]  # columns span im(d_{p+1})

            # H_p = ker(d_p) / im(d_{p+1})
            # Find complement of im in ker
            if im_basis.shape[1] == 0:
                H_basis = ker_basis
            elif ker_basis.shape[1] == 0:
                H_basis = np.zeros((dim_Bp, 0))
            else:
                # Project im_basis onto ker_basis coordinates
                ker_coords_of_im = np.linalg.lstsq(ker_basis, im_basis, rcond=None)[0]
                # SVD to find complement
                if ker_coords_of_im.shape[1] > 0:
                    U3, S3, Vt3 = np.linalg.svd(ker_coords_of_im, full_matrices=True)
                    rank_im_in_ker = np.sum(S3 > 1e-10)
                    # Complement directions in ker-coordinates
                    complement_coords = U3[:, rank_im_in_ker:]
                    H_basis = ker_basis @ complement_coords
                else:
                    H_basis = ker_basis

            H_dim = H_basis.shape[1]
            self.H_dims[p] = H_dim

            # iota: H -> B (inclusion of representatives)
            self.iota[p] = H_basis  # dim_Bp x H_dim

            # pi: B -> H (projection)
            if H_dim > 0:
                # pi = (iota^T iota)^{-1} iota^T (least squares projection)
                gram = H_basis.T @ H_basis
                gram_inv = np.linalg.inv(gram)
                self.pi[p] = gram_inv @ H_basis.T  # H_dim x dim_Bp
            else:
                self.pi[p] = np.zeros((0, dim_Bp))

        # Compute contracting homotopy h: B_p -> B_{p+1} satisfying
        # d_{p+1} h_p + h_{p-1} d_p = id - iota_p pi_p
        # We solve this iteratively
        for p in range(self.max_p + 1):
            dim_Bp = self.bar.basis_size(p)
            dim_Bpp1 = self.bar.basis_size(p + 1)

            if dim_Bp == 0 or dim_Bpp1 == 0:
                self.h[p] = np.zeros((dim_Bpp1, dim_Bp))
                continue

            d_pp1 = self.bar.differential_matrix(p + 1)

            # RHS = id - iota*pi - h_{p-1}*d_p
            rhs = np.eye(dim_Bp)
            if self.H_dims.get(p, 0) > 0:
                rhs -= self.iota[p] @ self.pi[p]
            if p > 0 and p - 1 in self.h:
                d_p = self.bar.differential_matrix(p)
                rhs -= self.h[p - 1] @ d_p

            # Solve d_{p+1} @ h_p = rhs for h_p
            # h_p = pseudoinverse(d_{p+1}) @ rhs
            self.h[p] = np.linalg.lstsq(d_pp1, rhs, rcond=None)[0]

    def m2(self, p: int, q: int) -> np.ndarray:
        """The binary operation m_2 on H*(B(A)).

        m_2: H_p x H_q -> H_{p+q} is the transferred multiplication.
        For the bar complex, this is the shuffle product composed with pi.

        Actually, for the bar complex of an associative algebra, the
        natural coalgebra structure uses the deconcatenation coproduct.
        The A-infinity ALGEBRA structure on A! = (H*(B(A)))^dual uses
        the transferred multiplication.

        For the bar construction, the relevant operation is:
        m_2 = pi * mu * (iota tensor iota)
        where mu is the concatenation product on the bar complex
        (which is NOT a chain map -- that's the point of the A-infinity
        structure).

        Returns matrix H_{p+q} <- (H_p tensor H_q).
        """
        H_p = self.H_dims.get(p, 0)
        H_q = self.H_dims.get(q, 0)
        H_pq = self.H_dims.get(p + q, 0)

        if H_p == 0 or H_q == 0 or H_pq == 0:
            return np.zeros((H_pq, H_p * H_q))

        # Concatenation: (sI)^p x (sI)^q -> (sI)^{p+q}
        # [a_1|...|a_p] * [b_1|...|b_q] = [a_1|...|a_p|b_1|...|b_q]
        iota_p = self.iota[p]  # B_p <- H_p
        iota_q = self.iota[q]  # B_q <- H_q
        pi_pq = self.pi[p + q]  # H_{p+q} <- B_{p+q}

        d = self.bar.d
        result = np.zeros((H_pq, H_p * H_q))

        for i in range(H_p):
            for j in range(H_q):
                # Get representative vectors
                v_p = iota_p[:, i]  # in B_p
                v_q = iota_q[:, j]  # in B_q

                # Concatenation: tensor product in the bar complex
                concat = np.zeros(self.bar.basis_size(p + q))
                for a_idx in range(self.bar.basis_size(p)):
                    if abs(v_p[a_idx]) < 1e-14:
                        continue
                    a_tup = self.bar._index_to_tuple(p, a_idx)
                    for b_idx in range(self.bar.basis_size(q)):
                        if abs(v_q[b_idx]) < 1e-14:
                            continue
                        b_tup = self.bar._index_to_tuple(q, b_idx)
                        c_tup = a_tup + b_tup
                        c_idx = self.bar._tuple_to_index(c_tup)
                        concat[c_idx] += v_p[a_idx] * v_q[b_idx]

                # Project to cohomology
                result[:, i * H_q + j] = pi_pq @ concat

        return result

    def m3_tree_level(self, p: int, q: int, r: int) -> np.ndarray:
        """The ternary A-infinity operation m_3 on H*(B(A)).

        m_3: H_p x H_q x H_r -> H_{p+q+r-1}

        Via the homological perturbation lemma / tree formula:
        m_3 = pi * mu * (id tensor mu) * (iota tensor h tensor iota)
            + pi * mu * (mu tensor id) * (iota tensor h tensor iota)
        ... actually, the correct HPL formula for m_3 is:

        m_3(a, b, c) = pi( mu(h(mu(iota(a), iota(b))), iota(c)) )
                      - pi( mu(iota(a), h(mu(iota(b), iota(c)))) )

        where mu is concatenation, h is the contracting homotopy.

        The sign depends on degree conventions. For the bar complex
        with elements in degree p, q, r:
        m_3: H_p tensor H_q tensor H_r -> H_{p+q+r+1}
        (degree shift by +1 for m_3 in the A-infinity convention).

        Actually, the correct target degree for the bar complex:
        m_k maps B_{p_1} x ... x B_{p_k} -> B_{p_1+...+p_k-k+2}
        For m_3: target = p + q + r - 1.
        """
        H_p = self.H_dims.get(p, 0)
        H_q = self.H_dims.get(q, 0)
        H_r = self.H_dims.get(r, 0)
        target_deg = p + q + r - 1
        H_t = self.H_dims.get(target_deg, 0)

        if H_p == 0 or H_q == 0 or H_r == 0 or H_t == 0:
            return np.zeros((H_t, H_p * H_q * H_r))

        iota_p = self.iota[p]
        iota_q = self.iota[q]
        iota_r = self.iota[r]
        pi_t = self.pi[target_deg]

        result = np.zeros((H_t, H_p * H_q * H_r))

        for i in range(H_p):
            for j in range(H_q):
                for k_idx in range(H_r):
                    a = iota_p[:, i]
                    b = iota_q[:, j]
                    c = iota_r[:, k_idx]

                    # Term 1: pi(concat(h(concat(a, b)), c))
                    ab_concat = self._concatenate(a, b, p, q)
                    h_ab = self._apply_h(ab_concat, p + q)
                    if h_ab is not None:
                        term1 = self._concatenate(h_ab, c, p + q + 1, r)
                        if term1 is not None:
                            val1 = pi_t @ term1
                        else:
                            val1 = np.zeros(H_t)
                    else:
                        val1 = np.zeros(H_t)

                    # Term 2: -pi(concat(a, h(concat(b, c))))
                    bc_concat = self._concatenate(b, c, q, r)
                    h_bc = self._apply_h(bc_concat, q + r)
                    if h_bc is not None:
                        term2 = self._concatenate(a, h_bc, p, q + r + 1)
                        if term2 is not None:
                            val2 = pi_t @ term2
                        else:
                            val2 = np.zeros(H_t)
                    else:
                        val2 = np.zeros(H_t)

                    col = i * (H_q * H_r) + j * H_r + k_idx
                    result[:, col] = val1 - val2

        return result

    def m4_tree_level(self, p: int, q: int, r: int, s: int) -> np.ndarray:
        """The quaternary A-infinity operation m_4 on H*(B(A)).

        m_4 via HPL tree formula: sum over binary trees with 4 leaves.
        There are 5 planar binary trees with 4 leaves (Catalan number C_3 = 5).

        m_4(a,b,c,d) = sum over trees T: sign(T) * pi(tree_composition_T(a,b,c,d))

        Target degree: p + q + r + s - 2.
        """
        H_p = self.H_dims.get(p, 0)
        H_q = self.H_dims.get(q, 0)
        H_r = self.H_dims.get(r, 0)
        H_s = self.H_dims.get(s, 0)
        target_deg = p + q + r + s - 2
        H_t = self.H_dims.get(target_deg, 0)

        if H_p == 0 or H_q == 0 or H_r == 0 or H_s == 0 or H_t == 0:
            return np.zeros((H_t, H_p * H_q * H_r * H_s))

        iota_p = self.iota[p]
        iota_q = self.iota[q]
        iota_r = self.iota[r]
        iota_s = self.iota[s]
        pi_t = self.pi[target_deg]

        result = np.zeros((H_t, H_p * H_q * H_r * H_s))

        for i in range(H_p):
            for j in range(H_q):
                for k_idx in range(H_r):
                    for l_idx in range(H_s):
                        a = iota_p[:, i]
                        b = iota_q[:, j]
                        c = iota_r[:, k_idx]
                        d = iota_s[:, l_idx]

                        val = np.zeros(H_t)

                        # Tree 1: ((a*b)*c)*d
                        val += self._tree_4_1(a, b, c, d, p, q, r, s, pi_t)
                        # Tree 2: (a*(b*c))*d
                        val -= self._tree_4_2(a, b, c, d, p, q, r, s, pi_t)
                        # Tree 3: (a*b)*(c*d)
                        val -= self._tree_4_3(a, b, c, d, p, q, r, s, pi_t)
                        # Tree 4: a*((b*c)*d)
                        val += self._tree_4_4(a, b, c, d, p, q, r, s, pi_t)
                        # Tree 5: a*(b*(c*d))
                        val -= self._tree_4_5(a, b, c, d, p, q, r, s, pi_t)

                        col = (i * H_q * H_r * H_s +
                               j * H_r * H_s +
                               k_idx * H_s +
                               l_idx)
                        result[:, col] = val

        return result

    def _tree_4_1(self, a, b, c, d, p, q, r, s, pi_t):
        """Tree ((a*b)*c)*d: left-comb."""
        ab = self._concatenate(a, b, p, q)
        h_ab = self._apply_h(ab, p + q)
        if h_ab is None:
            return np.zeros(pi_t.shape[0])
        h_ab_c = self._concatenate(h_ab, c, p + q + 1, r)
        if h_ab_c is None:
            return np.zeros(pi_t.shape[0])
        h2 = self._apply_h(h_ab_c, p + q + r)
        if h2 is None:
            return np.zeros(pi_t.shape[0])
        final = self._concatenate(h2, d, p + q + r + 1, s)
        if final is None:
            return np.zeros(pi_t.shape[0])
        return pi_t @ final

    def _tree_4_2(self, a, b, c, d, p, q, r, s, pi_t):
        """Tree (a*(b*c))*d."""
        bc = self._concatenate(b, c, q, r)
        h_bc = self._apply_h(bc, q + r)
        if h_bc is None:
            return np.zeros(pi_t.shape[0])
        a_hbc = self._concatenate(a, h_bc, p, q + r + 1)
        if a_hbc is None:
            return np.zeros(pi_t.shape[0])
        h2 = self._apply_h(a_hbc, p + q + r)
        if h2 is None:
            return np.zeros(pi_t.shape[0])
        final = self._concatenate(h2, d, p + q + r + 1, s)
        if final is None:
            return np.zeros(pi_t.shape[0])
        return pi_t @ final

    def _tree_4_3(self, a, b, c, d, p, q, r, s, pi_t):
        """Tree (a*b)*(c*d)."""
        ab = self._concatenate(a, b, p, q)
        h_ab = self._apply_h(ab, p + q)
        if h_ab is None:
            return np.zeros(pi_t.shape[0])
        cd = self._concatenate(c, d, r, s)
        h_cd = self._apply_h(cd, r + s)
        if h_cd is None:
            return np.zeros(pi_t.shape[0])
        final = self._concatenate(h_ab, h_cd, p + q + 1, r + s + 1)
        if final is None:
            return np.zeros(pi_t.shape[0])
        return pi_t @ final

    def _tree_4_4(self, a, b, c, d, p, q, r, s, pi_t):
        """Tree a*((b*c)*d)."""
        bc = self._concatenate(b, c, q, r)
        h_bc = self._apply_h(bc, q + r)
        if h_bc is None:
            return np.zeros(pi_t.shape[0])
        hbc_d = self._concatenate(h_bc, d, q + r + 1, s)
        if hbc_d is None:
            return np.zeros(pi_t.shape[0])
        h2 = self._apply_h(hbc_d, q + r + s)
        if h2 is None:
            return np.zeros(pi_t.shape[0])
        final = self._concatenate(a, h2, p, q + r + s + 1)
        if final is None:
            return np.zeros(pi_t.shape[0])
        return pi_t @ final

    def _tree_4_5(self, a, b, c, d, p, q, r, s, pi_t):
        """Tree a*(b*(c*d))."""
        cd = self._concatenate(c, d, r, s)
        h_cd = self._apply_h(cd, r + s)
        if h_cd is None:
            return np.zeros(pi_t.shape[0])
        b_hcd = self._concatenate(b, h_cd, q, r + s + 1)
        if b_hcd is None:
            return np.zeros(pi_t.shape[0])
        h2 = self._apply_h(b_hcd, q + r + s)
        if h2 is None:
            return np.zeros(pi_t.shape[0])
        final = self._concatenate(a, h2, p, q + r + s + 1)
        if final is None:
            return np.zeros(pi_t.shape[0])
        return pi_t @ final

    def _concatenate(self, v1, v2, p1: int, p2: int) -> Optional[np.ndarray]:
        """Concatenation product in the bar complex.

        [a_1|...|a_{p1}] * [b_1|...|b_{p2}] = [a_1|...|a_{p1}|b_1|...|b_{p2}]
        """
        target_p = p1 + p2
        target_dim = self.bar.basis_size(target_p)
        if target_dim == 0:
            return None

        result = np.zeros(target_dim)
        d = self.bar.d

        for a_idx in range(self.bar.basis_size(p1)):
            if abs(v1[a_idx]) < 1e-14:
                continue
            a_tup = self.bar._index_to_tuple(p1, a_idx)
            for b_idx in range(self.bar.basis_size(p2)):
                if abs(v2[b_idx]) < 1e-14:
                    continue
                b_tup = self.bar._index_to_tuple(p2, b_idx)
                c_tup = a_tup + b_tup
                c_idx = self.bar._tuple_to_index(c_tup)
                result[c_idx] += v1[a_idx] * v2[b_idx]

        return result

    def _apply_h(self, v, p: int) -> Optional[np.ndarray]:
        """Apply contracting homotopy h_p: B_p -> B_{p+1}."""
        if p not in self.h or v is None:
            return None
        h_p = self.h[p]
        if h_p.shape[1] != len(v):
            return None
        result = h_p @ v
        if np.max(np.abs(result)) < 1e-14:
            return None
        return result


# =========================================================================
# Explicit computations for specific algebras
# =========================================================================

def compute_truncated_poly(n: int, max_bar_degree: int = 6,
                           verbose: bool = False) -> Dict:
    """Compute bar cohomology and A-infinity structure for k[x]/(x^n).

    Returns dict with:
    - 'cohomology': {p: dim H_p(B(A))}
    - 'd_squared': {p: max|d^2|}
    - 'm3': description of m_3 operations
    - 'm4': description of m_4 operations
    """
    A = TruncatedPolynomialAlgebra(n)
    bar = BarComplex(A)

    # d^2 = 0 check
    d2_check = {}
    for p in range(2, max_bar_degree + 1):
        d2_check[p] = bar.verify_d_squared(p)

    # Cohomology
    coh = bar.cohomology_all(max_bar_degree)

    if verbose:
        print(f"\n=== k[x]/(x^{n}) ===")
        print(f"Aug ideal dim = {A.aug_ideal_dim}")
        for p in range(max_bar_degree + 1):
            dim_Bp = bar.basis_size(p)
            print(f"  B_{p}: dim = {dim_Bp}, H_{p} = {coh[p]}")
        print(f"  d^2 = 0 checks: {d2_check}")

    # A-infinity transfer (only if small enough)
    m3_data = {}
    m4_data = {}
    if n <= 5 and max_bar_degree >= 3:
        try:
            transfer = AInfinityTransfer(bar, min(max_bar_degree, 8))

            if verbose:
                print(f"  Cohomology dims from transfer: {transfer.H_dims}")

            # m3 on degree-1 classes
            if transfer.H_dims.get(1, 0) > 0:
                m3_111 = transfer.m3_tree_level(1, 1, 1)
                m3_data['(1,1,1)'] = {
                    'matrix': m3_111,
                    'nonzero': np.any(np.abs(m3_111) > 1e-10),
                    'target_deg': 2,
                }
                if verbose:
                    print(f"  m_3(H_1, H_1, H_1) -> H_2:")
                    print(f"    nonzero = {m3_data['(1,1,1)']['nonzero']}")
                    if m3_data['(1,1,1)']['nonzero']:
                        print(f"    matrix =\n{m3_111}")

                # m4 on degree-1 classes
                m4_1111 = transfer.m4_tree_level(1, 1, 1, 1)
                m4_data['(1,1,1,1)'] = {
                    'matrix': m4_1111,
                    'nonzero': np.any(np.abs(m4_1111) > 1e-10),
                    'target_deg': 2,
                }
                if verbose:
                    print(f"  m_4(H_1, H_1, H_1, H_1) -> H_2:")
                    print(f"    nonzero = {m4_data['(1,1,1,1)']['nonzero']}")
                    if m4_data['(1,1,1,1)']['nonzero']:
                        print(f"    matrix =\n{m4_1111}")

        except Exception as e:
            if verbose:
                print(f"  A-infinity transfer failed: {e}")

    return {
        'algebra': f'k[x]/(x^{n})',
        'n': n,
        'cohomology': coh,
        'd_squared': d2_check,
        'm3': m3_data,
        'm4': m4_data,
    }


def dual_numbers_verification():
    """Verify k[x]/(x^2) = k[epsilon] is Koszul.

    Bar cohomology should be k in each degree: H_p = 1 for all p.
    A! = k[y] (polynomial ring). All m_k = 0 for k >= 3.
    """
    return compute_truncated_poly(2, max_bar_degree=6, verbose=False)


def cubic_truncation():
    """Compute A-infinity structure for k[x]/(x^3).

    This is the simplest non-Koszul example. The algebra has basis
    {1, x, x^2} with x^3 = 0. The augmentation ideal I = span{x, x^2}
    has dim 2, so bar degree p has dim 2^p.

    Expected:
    - H_1 = 2 (generated by [x] and [x^2])
    - H_2: should have dim > 0 from [x|x] class (x*x = x^2 is nonzero,
      so [x|x] is NOT a cycle; but [x^2|x] - [x|x^2] might be)
    - Nontrivial m_3 should appear (Massey product)
    """
    return compute_truncated_poly(3, max_bar_degree=6, verbose=False)


# =========================================================================
# Admissible-level simple quotient analysis
# =========================================================================

def admissible_sl2_analysis(verbose: bool = False) -> Dict:
    """Analyze L_{-1/2}(sl_2) at the admissible level k = -1/2.

    V_k(sl_2) is chirally Koszul for all k (PBW/universality).
    L_k(sl_2) = V_k(sl_2) / (null ideal) at admissible levels.

    For k = -1/2 (the simplest admissible level for sl_2):
    - h^v(sl_2) = 2, so k = -1/2 is admissible (k + h^v = 3/2)
    - The null vector appears at level 2: (e_{-1})^2 |0>
    - After quotienting, the simple module L_{-1/2}(sl_2) is a
      rational VOA (BPZ/WZW model)

    The question: is L_{-1/2}(sl_2) chirally Koszul?

    Key insight: the bar complex of L_k(sl_2) differs from that of
    V_k(sl_2) precisely by the ideal generated by null vectors.
    The bar cohomology of V_k(sl_2) is Koszul (concentrated) for
    all k. But the quotient may destroy this concentration.

    ANSWER (from the manuscript, prop:pbw-universality):
    V_k(g) is chirally Koszul for ALL k. The simple quotient L_k(g)
    may fail Koszulness at admissible levels due to vacuum null vectors.
    For L_{-1/2}(sl_2): the null vector at level 2 creates a new
    generator in bar degree 2, potentially breaking concentration.

    However, L_{-1/2}(sl_2) = Vir_{c=-1} (the Ising model Virasoro
    at c = 1/2... no, that's not right). Actually:
    L_{-1/2}(sl_2) is a rational VOA with 2 simple modules.

    The precise Koszulness status of L_k(g) at admissible levels
    is OPEN in general (see manuscript remarks).
    """
    result = {
        'algebra': 'L_{-1/2}(sl_2)',
        'level': -0.5,
        'h_dual': 2,
        'admissible': True,
        'universal_koszul': True,  # V_k(sl_2) is Koszul for all k
        'simple_quotient_koszul': 'OPEN',
        'null_vector_level': 2,
        'null_vector': '(e_{-1})^2 |0>',
        'analysis': (
            'V_{-1/2}(sl_2) is chirally Koszul (prop:pbw-universality). '
            'The simple quotient L_{-1/2}(sl_2) has a null vector at level 2, '
            'which introduces a new relation in the bar complex. Whether this '
            'breaks bar cohomology concentration is an open question for this '
            'specific admissible level. The PBW criterion applies only to the '
            'universal algebra V_k(g), not to simple quotients.'
        ),
    }

    if verbose:
        print(f"\n=== Admissible sl_2 analysis ===")
        for key, val in result.items():
            print(f"  {key}: {val}")

    return result


# =========================================================================
# Main entry point
# =========================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("HOMOTOPY KOSZUL DUAL: A-INFINITY STRUCTURE OFF KOSZUL LOCUS")
    print("=" * 70)

    # Dual numbers (Koszul case)
    print("\n" + "=" * 50)
    r2 = compute_truncated_poly(2, max_bar_degree=6, verbose=True)

    # Cubic truncation (non-Koszul)
    print("\n" + "=" * 50)
    r3 = compute_truncated_poly(3, max_bar_degree=6, verbose=True)

    # Quartic truncation
    print("\n" + "=" * 50)
    r4 = compute_truncated_poly(4, max_bar_degree=5, verbose=True)

    # Admissible sl_2
    print("\n" + "=" * 50)
    admissible_sl2_analysis(verbose=True)
