r"""Kuranishi map parity analysis at genus 2 for multi-weight algebras.

FRONTIER COMPUTATION.  The current proof that obs_g = kappa * lambda_g
for UNIFORM-WEIGHT algebras uses two ingredients:

  (A) Cyclic rigidity: dim H^2_cyc(A,A) = 1, forcing the minimal MC
      element to factor as Theta^min = eta tensor Gamma_A.
  (B) Parity vanishing of the Kuranishi map: s^{-1}eta has odd degree 1
      in s^{-1}H, so l_n^{tr}(eta,...,eta) = 0 for n >= 2 by graded
      antisymmetry of L_infinity operations.

Together these show the one-dimensional cyclic direction is UNOBSTRUCTED,
but they do NOT identify the tautological coefficient Gamma_A with
kappa(A) * Lambda.

THIS MODULE ANALYZES the missing step at genus 2 for multi-weight
algebras (specifically W_3 with generators of weights 2 and 3).

THE KEY FINDING:  The genus-0 Kuranishi map parity argument is CORRECT
and extends to the full modular L_infinity structure: at each genus g,
the modular MC equation restricted to the one-dimensional cyclic line
spanned by eta is automatically satisfied (no obstruction).  But this
tells us ONLY that some MC solution exists on the cyclic line — it does
NOT determine which tautological class appears at genus g.

The obstruction to multi-generator universality at genus 2 is NOT a
failure of the Kuranishi map to vanish.  It is the failure to identify
the actual coefficient Gamma_A^{(2)} with kappa * lambda_2.

QUANTITATIVELY:  For W_3 at genus 2, the cross-channel correction
delta_F2 = (c + 204)/(16c) (rem:w3-genus2-cross-channel) measures
exactly how far the actual genus-2 free energy deviates from the
scalar-universal prediction kappa * lambda_2^FP.

MATHEMATICAL STRUCTURE:

The modular deformation complex Def_cyc^mod(A) at genus g has:
  - Degree 0: g_A (the Lie algebra of infinitesimal automorphisms)
  - Degree 1: infinitesimal deformations, controlled by stable graphs
               of genus g
  - Degree 2: obstructions, controlled by H^2 of the modular complex

At genus 2, the relevant complex is built from the four types of stable
graphs (theta, sunset/banana, figure-eight, smooth) with their channel
assignments.

For multi-weight algebras, the channel space is MULTI-DIMENSIONAL:
each edge carries a label from {T, W} for W_3.  The Kuranishi map at
the MODULAR level sends

    Obs_2: H^1(Def^{(2,0)}_cyc) --> H^2(Def^{(2,0)}_cyc)

but the relevant question for universality is different: it is whether
the genus-2 AMPLITUDE (a NUMBER, not a class) equals kappa * lambda_2^FP.

PARITY ANALYSIS:

The Z/2-grading that forces vanishing in the uniform-weight case comes
from the conformal weight modulo 2.  For uniform weight h:
  - Every edge carries weight h
  - The propagator is scalar: eta^{-1} = 1/kappa
  - No mixed channels exist

For W_3 (weights 2 and 3):
  - Edges can carry T (weight 2, even) or W (weight 3, odd)
  - The Z_2 symmetry W -> -W forces C_{TTW} = C_{WWW} = 0
  - But C_{TWW} = C_{WWT} = c is NONZERO (even W-count)
  - Cross-channel amplitudes arise from (T,W,W)-type assignments

The Z_2 parity does NOT force cross-channel amplitudes to vanish.
In fact, the theta graph with (T,W,W) assignment gives the dominant
cross-channel contribution 9/(2c).

SUMMARY OF DIMENSIONS:

For W_3 at genus 2:
  dim H^1(Def^{(2,0)}_cyc(W_3)) = 1  (the level deformation direction)
  dim H^2(Def^{(2,0)}_cyc(W_3)) = 1  (generated by eta)

The Kuranishi map Obs_2: H^1 -> H^2 vanishes by the same parity
argument as genus 0 (s^{-1}eta has odd degree 1).  This means the
one-channel deformation is UNOBSTRUCTED at genus 2.

The cross-channel correction delta_F2 is NOT an obstruction in the
Kuranishi sense.  It is a correction to the AMPLITUDE that arises from
multi-channel graph sums within the SAME one-channel MC element
Theta^min = eta tensor Gamma_A.

The open problem (op:multi-generator-universality) asks whether
Gamma_A^{(2)} = kappa * lambda_2, which is a statement about the
tautological coefficient, not about the Kuranishi obstruction.

Manuscript references:
    thm:algebraic-family-rigidity (higher_genus_modular_koszul.tex)
    op:multi-generator-universality (higher_genus_modular_koszul.tex)
    rem:w3-genus2-cross-channel (higher_genus_modular_koszul.tex)
    rem:multi-gen-independence (higher_genus_modular_koszul.tex)
    thm:multi-generator-universality (higher_genus_modular_koszul.tex)

Conventions:
    - Cohomological grading: |d| = +1.
    - Bar uses DESUSPENSION: |s^{-1}v| = |v| - 1 (AP45).
    - kappa(W_3) = 5c/6 (AP1, landscape_census.tex).
    - Bar propagator weight 1 for ALL channels (AP27).
    - Kuranishi map = MC equation on H^2, NOT the graph-sum amplitude.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import product as cartprod
from math import comb, factorial
from typing import Dict, List, Optional, Tuple

from sympy import Matrix, Rational, S, Symbol, factor, simplify, symbols


# ============================================================================
# 1. Cyclic deformation complex dimensions
# ============================================================================

@dataclass
class CyclicCohomologyData:
    """Cohomology of the cyclic deformation complex at a given genus.

    H^p(Def_cyc^{(g,0)}(A)) at each degree p, for a multi-weight
    algebra A with specified generators and Lie symmetry.
    """
    genus: int
    algebra_name: str
    generator_weights: Tuple[int, ...]
    lie_symmetry: Optional[str]
    h0: int  # dim H^0: infinitesimal automorphisms
    h1: int  # dim H^1: infinitesimal deformations
    h2: int  # dim H^2: obstructions
    # The Euler characteristic chi = h0 - h1 + h2
    parity_grading_intact: bool  # whether Z/2 grading from weight parity works
    notes: str = ""


def w3_cyclic_cohomology_genus0() -> CyclicCohomologyData:
    r"""Cyclic deformation complex of W_3 at genus 0.

    By algebraic-family-rigidity (thm:algebraic-family-rigidity):
      dim H^2_cyc(W_3, W_3) = 1 at all non-critical levels.

    The single generator eta of H^2_cyc corresponds to the level
    deformation k -> k + epsilon.  The Kodaira-Spencer class
    eta = d/dk is nonzero even at c = 0 (it is a tangent vector
    to the family, not the curvature).

    H^0 = 0 for simple algebras (no infinitesimal automorphisms
    beyond the identity, since the Lie algebra is simple).
    Actually for W_3 with sl_3 symmetry, H^0 = sl_3 (the current
    algebra acts as automorphisms).  But for the CYCLIC complex
    (quotient by inner derivations), H^0 = 0.

    H^1: deformations of the OPE structure.  For W_3 with fixed
    Lie symmetry, these are parameterized by the level k only.
    dim H^1 = 1 (the level direction).

    H^2 = 1: the unique cyclic cohomology class eta.
    """
    return CyclicCohomologyData(
        genus=0,
        algebra_name="W_3",
        generator_weights=(2, 3),
        lie_symmetry="sl_3",
        h0=0,
        h1=1,
        h2=1,
        parity_grading_intact=True,
        notes=(
            "H^2_cyc = 1 by algebraic-family-rigidity "
            "(thm:algebraic-family-rigidity). "
            "The Z_2 parity W -> -W is a symmetry of the OPE, "
            "forcing odd-W-count structure constants to vanish. "
            "This parity persists at genus 0."
        ),
    )


def w3_cyclic_cohomology_genus1() -> CyclicCohomologyData:
    r"""Cyclic deformation complex of W_3 at genus 1.

    At genus 1, the modular deformation complex receives contributions
    from the elliptic curves with marked points.

    dim H^2(Def_cyc^{(1,0)}(W_3)) = 1: still generated by eta.
    This is the genus-1 universality theorem (PROVED unconditionally):
    obs_1 = kappa * lambda_1 for ALL modular Koszul algebras.

    The genus-1 vertex factor is kappa_i/24 per channel i, and the
    total is (kappa_T + kappa_W)/24 = kappa/24 = (5c/6)/24.

    At genus 1, the Z_2 parity forces cross-channel corrections to
    vanish: the figure-eight graph (the only genus-1 stable graph at
    n=0 with edges) has a single self-loop, so no mixed channels exist.
    """
    return CyclicCohomologyData(
        genus=1,
        algebra_name="W_3",
        generator_weights=(2, 3),
        lie_symmetry="sl_3",
        h0=0,
        h1=1,
        h2=1,
        parity_grading_intact=True,
        notes=(
            "Genus-1 universality is PROVED unconditionally "
            "(thm:genus-universality). The only boundary graph at "
            "(1,0) is the figure-eight with 1 self-loop, so no "
            "mixed channels arise. Parity forces vanishing of cross-"
            "channel terms at genus 1."
        ),
    )


def w3_cyclic_cohomology_genus2() -> CyclicCohomologyData:
    r"""Cyclic deformation complex of W_3 at genus 2.

    THE KEY COMPUTATION.

    dim H^2(Def_cyc^{(2,0)}(W_3)):
      By the same algebraic-family-rigidity argument, the CYCLIC
      cohomology is still 1-dimensional at genus 2.  The rigidity
      argument is genus-independent: it depends on the OPE algebra
      (which is a genus-0 datum), not on the moduli space.

      HOWEVER: the modular deformation complex at genus 2 has
      ADDITIONAL structure from the stable-graph decomposition of
      the boundary of M_bar_{2,0}.  The 5 boundary graphs contribute
      5 independent boundary strata, each with their own channel
      decomposition.

    dim H^1(Def_cyc^{(2,0)}(W_3)):
      The infinitesimal deformations at genus 2 are still 1-dimensional
      (level deformation k -> k + epsilon), since the algebra structure
      is determined by genus-0 data.

    The Kuranishi map Obs_2: H^1 -> H^2 vanishes:
      - H^2 is 1-dimensional, generated by eta.
      - s^{-1}eta has degree 1 (odd) in the desuspension s^{-1}H.
      - l_n^{tr}(eta, ..., eta) = 0 for n >= 2 by graded antisymmetry.
      - This is INDEPENDENT of genus: the parity argument uses only the
        degree of s^{-1}eta, not the genus of the moduli space.

    The Z_2 parity W -> -W is BROKEN at genus 2:
      At genus 0, the Z_2 parity forces odd-W-count amplitudes to vanish.
      At genus 1, single-edge graphs have no mixed channels.
      At genus 2, multi-edge graphs (banana, theta, lollipop) admit
      channel assignments with EVEN W-count on each vertex but MIXED
      overall.  These contribute nonzero cross-channel corrections.

      Example: theta graph with (T,W,W) assignment.
        Vertex 1: (T,W,W) -> C_{TWW} = c (even W-count at vertex).
        Vertex 2: (T,W,W) -> C_{TWW} = c (even W-count at vertex).
        Total W-count across all edges: 2 (even globally).
        Amplitude: nonzero.

      The Z_2 parity forces vanishing of amplitudes with ODD total
      W-count, but does NOT force vanishing of MIXED assignments
      with EVEN total W-count.
    """
    return CyclicCohomologyData(
        genus=2,
        algebra_name="W_3",
        generator_weights=(2, 3),
        lie_symmetry="sl_3",
        h0=0,
        h1=1,
        h2=1,
        parity_grading_intact=False,  # Z_2 parity broken for cross-channel terms
        notes=(
            "H^2_cyc = 1 by algebraic-family-rigidity (genus-independent). "
            "The Kuranishi map vanishes by the SAME parity argument as "
            "genus 0: s^{-1}eta has odd degree, forcing l_n(eta,...,eta) = 0. "
            "HOWEVER: the Z_2 parity W -> -W does NOT force vanishing of "
            "mixed-channel graph amplitudes at genus 2. The theta graph "
            "with (T,W,W) assignment gives nonzero cross-channel correction "
            "9/(2c). Total delta_F2 = (c+204)/(16c)."
        ),
    )


def heisenberg_cyclic_cohomology_genus2() -> CyclicCohomologyData:
    """Cyclic deformation complex of Heisenberg at genus 2 (baseline).

    Heisenberg has a single generator of weight 1 (uniform weight).
    dim H^2_cyc = 1 at all genera.
    No mixed channels (single generator).
    Parity argument works: obs_g = kappa * lambda_g PROVED at all genera.
    """
    return CyclicCohomologyData(
        genus=2,
        algebra_name="Heisenberg",
        generator_weights=(1,),
        lie_symmetry="u(1)",
        h0=0,
        h1=1,
        h2=1,
        parity_grading_intact=True,
        notes=(
            "Single generator: no mixed channels at any genus. "
            "obs_g = kappa * lambda_g is PROVED at all genera."
        ),
    )


def virasoro_cyclic_cohomology_genus2() -> CyclicCohomologyData:
    """Cyclic deformation complex of Virasoro at genus 2 (uniform weight).

    Virasoro has a single generator T of weight 2 (uniform weight).
    dim H^2_cyc = 1 at all genera.
    No mixed channels (single generator).
    """
    return CyclicCohomologyData(
        genus=2,
        algebra_name="Virasoro",
        generator_weights=(2,),
        lie_symmetry=None,
        h0=0,
        h1=1,
        h2=1,
        parity_grading_intact=True,
        notes=(
            "Single generator: no mixed channels. "
            "obs_g = kappa * lambda_g is PROVED at all genera on the "
            "uniform-weight lane."
        ),
    )


# ============================================================================
# 2. Kuranishi map parity analysis
# ============================================================================

@dataclass
class KuranishiParityResult:
    """Result of the Kuranishi parity analysis at a given genus."""
    genus: int
    algebra_name: str
    dim_h2_cyc: int
    desuspended_degree: int  # |s^{-1}eta| in s^{-1}H
    parity_forces_vanishing: bool  # whether l_n(eta,...,eta) = 0 by parity
    kuranishi_map_vanishes: bool  # whether the Kuranishi map Obs_g vanishes
    cross_channel_correction_vanishes: bool
    cross_channel_formula: Optional[str]
    tautological_identification_proved: bool
    explanation: str


def kuranishi_parity_genus0(algebra: str = "W_3") -> KuranishiParityResult:
    r"""Kuranishi map parity analysis at genus 0.

    For any algebra with dim H^2_cyc = 1:
      - eta generates H^2_cyc.
      - s^{-1}eta has degree |eta| - 1 = 2 - 1 = 1 (ODD).
      - l_n^{tr}(eta,...,eta) = 0 for n >= 2 by graded antisymmetry:
        permuting two copies of the odd element s^{-1}eta in
        T^c(s^{-1}H) introduces a sign (-1).
      - l_1^{tr} = 0 by minimality of the model.
      - Therefore MC_H(x) = 0 for all x in H^2 tensor G_mod.

    This is INDEPENDENT of the algebra type and the number of generators.
    It depends ONLY on dim H^2_cyc = 1 and the degree of eta.
    """
    return KuranishiParityResult(
        genus=0,
        algebra_name=algebra,
        dim_h2_cyc=1,
        desuspended_degree=1,
        parity_forces_vanishing=True,
        kuranishi_map_vanishes=True,
        cross_channel_correction_vanishes=True,
        cross_channel_formula=None,
        tautological_identification_proved=(algebra in ("Heisenberg", "Virasoro")),
        explanation=(
            f"At genus 0, dim H^2_cyc({algebra}) = 1. "
            f"s^{{-1}}eta has degree 1 (odd). "
            f"l_n(eta,...,eta) = 0 for n >= 2 by graded antisymmetry. "
            f"The Kuranishi map vanishes identically. "
            f"No cross-channel correction at genus 0 (tree level)."
        ),
    )


def kuranishi_parity_genus1(algebra: str = "W_3") -> KuranishiParityResult:
    r"""Kuranishi map parity analysis at genus 1.

    At genus 1, the modular MC equation has additional terms from
    l_n^{(1)} (genus-1 L_infinity operations).

    The parity argument still works: s^{-1}eta has degree 1 at ALL genera.
    The modular L_infinity operations l_n^{(g)} satisfy the same graded
    symmetry as l_n^{(0)}.

    For cross-channel corrections: the only stable graph at (g=1, n=0)
    with edges is the figure-eight (1 self-loop).  A single edge cannot
    have mixed channels.  Therefore delta_F1 = 0 for ALL multi-weight
    algebras.

    This is why genus-1 universality obs_1 = kappa * lambda_1 is PROVED
    unconditionally.
    """
    return KuranishiParityResult(
        genus=1,
        algebra_name=algebra,
        dim_h2_cyc=1,
        desuspended_degree=1,
        parity_forces_vanishing=True,
        kuranishi_map_vanishes=True,
        cross_channel_correction_vanishes=True,
        cross_channel_formula="delta_F1 = 0 (single-edge graphs only)",
        tautological_identification_proved=True,  # UNCONDITIONAL at genus 1
        explanation=(
            f"At genus 1, dim H^2_cyc({algebra}) = 1. "
            f"s^{{-1}}eta has degree 1 (odd). "
            f"Kuranishi map vanishes by parity. "
            f"Cross-channel corrections vanish because the only stable "
            f"graph at (1,0) with edges is the figure-eight (1 edge), "
            f"which cannot have mixed channels. "
            f"Genus-1 universality is PROVED UNCONDITIONALLY."
        ),
    )


def kuranishi_parity_genus2(algebra: str = "W_3") -> KuranishiParityResult:
    r"""Kuranishi map parity analysis at genus 2 — THE KEY COMPUTATION.

    THE KURANISHI MAP STILL VANISHES by parity at genus 2.  This is
    because the parity argument is INDEPENDENT of genus: it depends
    only on |s^{-1}eta| = 1 being odd, which forces l_n(eta,...,eta) = 0
    at ALL genera simultaneously.

    HOWEVER: the cross-channel correction delta_F2 is NONZERO for W_3.
    This is NOT a failure of the Kuranishi map to vanish — it is a
    different phenomenon entirely.

    The distinction:
      - KURANISHI MAP VANISHING means: the one-channel deformation
        Theta^min = eta tensor Gamma_A is unobstructed.  Some MC
        solution exists on the one-dimensional cyclic line.

      - TAUTOLOGICAL IDENTIFICATION means: the actual coefficient
        Gamma_A^{(g)} equals kappa * lambda_g at each genus.

    The first is proved (by parity).  The second is OPEN.

    For uniform-weight algebras (Heisenberg, Virasoro):
      - No mixed channels exist (single generator type).
      - The graph sum is purely per-channel.
      - Each channel independently gives kappa_i * lambda_g^FP.
      - Total = kappa * lambda_g^FP.

    For multi-weight algebras (W_3, W_N with N >= 3):
      - Mixed channels exist on multi-edge graphs.
      - The cross-channel correction delta_F2 = (c+204)/(16c) for W_3.
      - This is the EXPLICIT OBSTRUCTION to universality at genus 2.
      - Whether R-matrix corrections at genus >= 1 cancel delta_F2
        is op:multi-generator-universality (OPEN).
    """
    if algebra in ("Heisenberg", "Virasoro"):
        return KuranishiParityResult(
            genus=2,
            algebra_name=algebra,
            dim_h2_cyc=1,
            desuspended_degree=1,
            parity_forces_vanishing=True,
            kuranishi_map_vanishes=True,
            cross_channel_correction_vanishes=True,
            cross_channel_formula="delta_F2 = 0 (single generator)",
            tautological_identification_proved=True,
            explanation=(
                f"At genus 2, {algebra} has a single generator. "
                f"No mixed channels exist. Kuranishi map vanishes by parity. "
                f"obs_2 = kappa * lambda_2 is PROVED on the uniform-weight lane."
            ),
        )

    # Multi-weight case: W_3
    return KuranishiParityResult(
        genus=2,
        algebra_name=algebra,
        dim_h2_cyc=1,
        desuspended_degree=1,
        parity_forces_vanishing=True,  # The parity argument STILL works
        kuranishi_map_vanishes=True,    # Kuranishi map vanishes at ALL genera
        cross_channel_correction_vanishes=False,  # delta_F2 != 0
        cross_channel_formula="delta_F2 = (c + 204) / (16c)",
        tautological_identification_proved=False,  # OPEN
        explanation=(
            "At genus 2, dim H^2_cyc(W_3) = 1. "
            "s^{-1}eta has degree 1 (odd). "
            "The Kuranishi map Obs_2: H^1 -> H^2 vanishes by parity "
            "(same argument as genus 0 — degree-independent). "
            "HOWEVER: the cross-channel correction "
            "delta_F2 = (c+204)/(16c) is NONZERO. "
            "This is NOT a Kuranishi obstruction; it is a correction to "
            "the graph-sum AMPLITUDE within the unobstructed MC element "
            "Theta^min = eta tensor Gamma_A. "
            "Whether Gamma_A^{(2)} = kappa * lambda_2 (equivalently, "
            "whether R-matrix corrections cancel delta_F2) is "
            "op:multi-generator-universality (OPEN)."
        ),
    )


# ============================================================================
# 3. Genus-2 stable graph channel analysis
# ============================================================================

@dataclass
class GraphChannelAnalysis:
    """Channel-by-channel analysis of a genus-2 stable graph."""
    graph_name: str
    num_edges: int
    num_channels: int  # 2^{num_edges} total assignments
    num_diagonal: int  # assignments with all edges same type
    num_mixed: int     # assignments with mixed types
    z2_vanishing_count: int  # assignments killed by Z_2 parity
    z2_surviving_mixed: int  # mixed assignments that survive Z_2
    dominant_mixed_type: Optional[str]


def analyze_genus2_graph_channels() -> List[GraphChannelAnalysis]:
    r"""Analyze channel structure of all genus-2 stable graphs.

    For each graph, count:
      - Total channel assignments: 2^{|E|}
      - Diagonal assignments: 2 (all-T and all-W)
      - Mixed assignments: 2^{|E|} - 2
      - Z_2-vanishing: assignments where some vertex has odd W-count
      - Z_2-surviving mixed: the potentially nonzero mixed terms

    The Z_2 parity W -> -W of the W_3 algebra forces:
      C_{i_1,...,i_n} = 0 if the total number of W-indices is odd.

    For VERTEX factors: each vertex independently requires even W-count.
    This is STRONGER than requiring even total W-count globally.
    """
    results = []

    # Graph 0: smooth (0 edges)
    results.append(GraphChannelAnalysis(
        graph_name="smooth", num_edges=0, num_channels=1,
        num_diagonal=1, num_mixed=0, z2_vanishing_count=0,
        z2_surviving_mixed=0, dominant_mixed_type=None,
    ))

    # Graph 1: figure-eight (1 self-loop)
    # Assignments: T, W. Both are diagonal. No mixed.
    results.append(GraphChannelAnalysis(
        graph_name="fig_eight", num_edges=1, num_channels=2,
        num_diagonal=2, num_mixed=0, z2_vanishing_count=0,
        z2_surviving_mixed=0, dominant_mixed_type=None,
    ))

    # Graph 2: banana (2 self-loops at vertex g=0, val=4)
    # Assignments: (T,T), (T,W), (W,T), (W,W). 4 total.
    # Diagonal: (T,T), (W,W). 2.
    # Mixed: (T,W), (W,T). 2.
    # Vertex half-edges: each loop contributes 2 half-edges to the vertex.
    # For (T,W): vertex gets half-edges (T,T,W,W) — 2 W's (even). SURVIVES.
    # For (W,T): vertex gets half-edges (W,W,T,T) — 2 W's (even). SURVIVES.
    results.append(GraphChannelAnalysis(
        graph_name="banana", num_edges=2, num_channels=4,
        num_diagonal=2, num_mixed=2, z2_vanishing_count=0,
        z2_surviving_mixed=2,
        dominant_mixed_type="(T,W) and (W,T): vertex gets (T,T,W,W)",
    ))

    # Graph 3: dumbbell (1 bridge between two g=1 vertices)
    # Assignments: T, W. Both are diagonal from each vertex's perspective:
    #   T: vertex A gets 1 T-half-edge, vertex B gets 1 T-half-edge.
    #       Each vertex has 1 half-edge. genus-1 vertex factor = kappa_T/24.
    #   W: similarly kappa_W/24.
    # No mixed possible (single edge).
    results.append(GraphChannelAnalysis(
        graph_name="dumbbell", num_edges=1, num_channels=2,
        num_diagonal=2, num_mixed=0, z2_vanishing_count=0,
        z2_surviving_mixed=0, dominant_mixed_type=None,
    ))

    # Graph 4: theta (3 bridges between two g=0 trivalent vertices)
    # Assignments: 2^3 = 8. Diagonal: (T,T,T), (W,W,W). 2.
    # Mixed: 6.
    # Each vertex gets 3 half-edges (one from each bridge).
    # Z_2 parity at each vertex: C_{i,j,k} = 0 if odd W-count.
    # (T,T,W): vertex gets (T,T,W) -> C_{TTW} = 0. KILLED.  (3 such assignments)
    # (T,W,W): vertex gets (T,W,W) -> C_{TWW} = c. SURVIVES. (3 such assignments)
    # (W,W,W): vertex gets (W,W,W) -> C_{WWW} = 0. KILLED. (diagonal, already counted)
    # Net surviving mixed: 3 (the (T,W,W)-type).
    results.append(GraphChannelAnalysis(
        graph_name="theta", num_edges=3, num_channels=8,
        num_diagonal=2, num_mixed=6,
        z2_vanishing_count=3,  # the 3 (T,T,W)-type assignments
        z2_surviving_mixed=3,  # the 3 (T,W,W)-type assignments
        dominant_mixed_type="(T,W,W)-type: C_{TWW}^2 * eta^T * (eta^W)^2",
    ))

    # Graph 5: lollipop (1 self-loop at g=0 trivalent vertex + 1 bridge to g=1 vertex)
    # Assignments: (sigma_loop, sigma_bridge). 4 total.
    # Diagonal: (T,T), (W,W). 2.
    # Mixed: (T,W), (W,T). 2.
    #
    # (T,W): loop=T, bridge=W.
    #   g=0 vertex: half-edges (T,T,W) -> C_{TTW} = 0. KILLED by Z_2.
    # (W,T): loop=W, bridge=T.
    #   g=0 vertex: half-edges (W,W,T) -> C_{WWT} = c. SURVIVES.
    #   g=1 vertex: half-edge T -> V_{1,1}(T) = kappa_T/24.
    # Net surviving mixed: 1 (the (W,T) assignment).
    results.append(GraphChannelAnalysis(
        graph_name="lollipop", num_edges=2, num_channels=4,
        num_diagonal=2, num_mixed=2,
        z2_vanishing_count=1,  # the (T,W) assignment
        z2_surviving_mixed=1,  # the (W,T) assignment
        dominant_mixed_type="(W,T): loop=W, bridge=T. C_{WWT} * V_{1,1}(T)",
    ))

    # Graph 6: barbell (2 vertices g=0, each with 1 self-loop, joined by 1 bridge)
    # 3 edges total: self-loop at v0, self-loop at v1, bridge.
    # Assignments: (sigma_loop0, sigma_loop1, sigma_bridge). 2^3 = 8 total.
    # Diagonal: (T,T,T), (W,W,W). 2.
    # Mixed: 6.
    # Z_2 parity at each vertex (valence 3: loop contributes 2 half-edges + bridge 1):
    #   v0 half-edges: (s0, s0, s2), W-count = 2*[s0=W] + [s2=W]
    #   v1 half-edges: (s1, s1, s2), W-count = 2*[s1=W] + [s2=W]
    # (T,T,W): v0=(T,T,W) W=1 ODD -> KILLED.
    # (T,W,T): v0=(T,T,T) W=0, v1=(W,W,T) W=2 -> SURVIVES.
    # (T,W,W): v0=(T,T,W) W=1 ODD -> KILLED.
    # (W,T,T): v0=(W,W,T) W=2, v1=(T,T,T) W=0 -> SURVIVES.
    # (W,T,W): v0=(W,W,W) W=3 ODD -> KILLED.
    # (W,W,T): v0=(W,W,T) W=2, v1=(W,W,T) W=2 -> SURVIVES.
    # Net: 3 killed (bridge=W assignments), 3 survive (bridge=T assignments).
    # AP123: this is the 7th genus-2 stable graph; omitting it was the original bug.
    results.append(GraphChannelAnalysis(
        graph_name="barbell", num_edges=3, num_channels=8,
        num_diagonal=2, num_mixed=6,
        z2_vanishing_count=3,  # (T,T,W), (T,W,W), (W,T,W): all have bridge=W
        z2_surviving_mixed=3,  # (T,W,T), (W,T,T), (W,W,T): all have bridge=T
        dominant_mixed_type="bridge=T: (T,W,T) and (W,T,T) and (W,W,T)",
    ))

    return results


# ============================================================================
# 4. Explicit cross-channel amplitude computation
# ============================================================================

def w3_cross_channel_at_genus2(c_val: Fraction) -> Dict[str, Fraction]:
    r"""Compute the W_3 cross-channel correction at genus 2.

    This computes delta_F2 = F_2^{full} - F_2^{diagonal}
    where F_2^{diagonal} = kappa * lambda_2^FP is the per-channel
    universal prediction and F_2^{full} is the actual multi-channel
    graph sum.

    Per-graph cross-channel contributions:

    Gamma_2 (banana): 2 mixed assignments survive Z_2.
      (T,W): vertex factor = V_{0,4}(T,T,W,W) = 2c (universally).
              propagator = eta^T * eta^W = (2/c)(3/c) = 6/c^2.
              raw = 12/c. Two such, with 1/|Aut|=1/8: 24/(8c) = 3/c.

    Gamma_4 (theta): 3 mixed assignments survive Z_2.
      (T,W,W)-type: each vertex gets (T,W,W) -> C_{TWW} = c.
                     propagators: eta^T * (eta^W)^2 = (2/c)(3/c)^2 = 18/c^3.
                     raw per assignment = 18c^2/c^3 = 18/c.
                     3 such, with 1/|Aut|=1/12: 3*18/(12c) = 9/(2c).

    Gamma_5 (lollipop): 1 mixed assignment survives Z_2.
      (W,T): g=0 vertex (W,W,T) -> C_{WWT} = c.
             g=1 vertex (T) -> kappa_T/24 = c/48.
             propagators: eta^W * eta^T = (3/c)(2/c) = 6/c^2.
             raw = 6c * c/(48 * c^2) = 6/(48) = 1/8.
             With 1/|Aut|=1/2: 1/16.

    Gamma_6 (barbell): 3 mixed assignments survive Z_2.
      2 vertices g=0, 1 bridge + 1 self-loop on each vertex. |Aut|=8.
      (W,T,W): v0=(W,W,T)->C_{WWT}=c, v1=(T,W,W)->C_{TWW}=c.
               props: (3/c)(2/c)(3/c)=18/c^3. raw=18/c. With 1/8: 9/(4c).
      (T,T,W): v0=(T,T,T)->c, v1=(T,W,W)->c.
               props: (2/c)(2/c)(3/c)=12/c^3. raw=12/c. With 1/8: 3/(2c).
      (W,T,T): v0=(W,W,T)->c, v1=(T,T,T)->c.
               props: (3/c)(2/c)(2/c)=12/c^3. raw=12/c. With 1/8: 3/(2c).
      Mixed total: 9/(4c) + 3/(2c) + 3/(2c) = 9/(4c) + 3/c = 21/(4c).

    Total: delta_F2 = 3/c + 9/(2c) + 1/16 + 21/(4c) = (c + 204)/(16c).
    """
    # Per-graph contributions
    delta_banana = Fraction(3) / c_val
    delta_theta = Fraction(9) / (2 * c_val)
    delta_lollipop = Fraction(1, 16)
    delta_barbell = Fraction(21) / (4 * c_val)

    # Total cross-channel correction
    delta_total = delta_banana + delta_theta + delta_lollipop + delta_barbell

    # Verify closed form
    delta_closed = (c_val + 204) / (16 * c_val)

    return {
        'delta_banana': delta_banana,
        'delta_theta': delta_theta,
        'delta_lollipop': delta_lollipop,
        'delta_barbell': delta_barbell,
        'delta_total': delta_total,
        'delta_closed_form': delta_closed,
        'match': delta_total == delta_closed,
        'kappa_times_lambda2': Fraction(5) * c_val / 6 * Fraction(7, 5760),
        'ratio_delta_over_diagonal': (
            delta_total / (Fraction(5) * c_val / 6 * Fraction(7, 5760))
            if c_val != 0 else None
        ),
    }


# ============================================================================
# 5. Parity obstruction classification for multi-weight algebras
# ============================================================================

@dataclass
class ParityObstructionClassification:
    """Classification of parity obstruction at given genus."""
    genus: int
    algebra_name: str
    num_generators: int
    generator_weights: Tuple[int, ...]
    weight_parity_classes: int  # number of distinct weight parities
    kuranishi_obstructed: bool
    amplitude_correction_nonzero: bool
    min_genus_for_mixed_channels: int
    explanation: str


def classify_parity_obstruction(
    algebra_name: str,
    generator_weights: Tuple[int, ...],
    genus: int,
) -> ParityObstructionClassification:
    r"""Classify the parity obstruction for a given algebra at given genus.

    The key insight: the Kuranishi map ALWAYS vanishes (for dim H^2_cyc = 1),
    but the amplitude correction (cross-channel terms) may be nonzero.

    The minimal genus at which cross-channel corrections can appear is g=2:
      - g=0: tree level, no edges, no channels.
      - g=1: single-edge boundary graphs only (figure-eight at n=0).
             Single edge cannot have mixed channels.
      - g=2: multi-edge boundary graphs exist (banana 2, theta 3, lollipop 2).
             Mixed channels are possible.

    For uniform-weight algebras (all generators same weight):
      - There is only one channel type.
      - Mixed channels are impossible at ANY genus.
      - obs_g = kappa * lambda_g is PROVED at all genera.

    For multi-weight algebras:
      - Mixed channels exist at genus >= 2.
      - The cross-channel correction may be nonzero.
      - Whether it vanishes (after R-matrix corrections) is OPEN.
    """
    n_gen = len(generator_weights)
    weight_parities = set(w % 2 for w in generator_weights)
    n_parity_classes = len(weight_parities)

    # Uniform-weight check
    uniform = (len(set(generator_weights)) == 1)

    # Minimum genus for mixed channels
    if n_gen == 1 or uniform:
        min_genus_mixed = float('inf')  # never
    else:
        min_genus_mixed = 2  # genus-2 boundary graphs have multi-edge structure

    # Amplitude correction analysis
    if uniform:
        amplitude_nonzero = False
    elif genus < 2:
        amplitude_nonzero = False
    else:
        # At genus >= 2, multi-weight algebras generically have nonzero corrections
        amplitude_nonzero = True

    return ParityObstructionClassification(
        genus=genus,
        algebra_name=algebra_name,
        num_generators=n_gen,
        generator_weights=generator_weights,
        weight_parity_classes=n_parity_classes,
        kuranishi_obstructed=False,  # NEVER obstructed when dim H^2_cyc = 1
        amplitude_correction_nonzero=amplitude_nonzero,
        min_genus_for_mixed_channels=min_genus_mixed if isinstance(min_genus_mixed, int) else -1,
        explanation=(
            f"{algebra_name} with generators of weights {generator_weights}: "
            f"{'uniform' if uniform else 'multi'}-weight. "
            f"Kuranishi map vanishes at ALL genera (parity of s^{{-1}}eta). "
            + (
                f"No mixed channels at any genus (uniform weight). "
                f"Tautological identification PROVED."
                if uniform else
                f"Mixed channels appear at genus >= {min_genus_mixed}. "
                f"{'Cross-channel correction is nonzero.' if amplitude_nonzero else 'Cross-channel correction vanishes at this genus.'} "
                f"Tautological identification {'PROVED (genus < 2)' if genus < 2 else 'OPEN (genus >= 2)'}."
            )
        ),
    )


# ============================================================================
# 6. Multi-weight deformation complex dimension computation
# ============================================================================

def genus2_deformation_complex_dimensions(
    algebra_name: str,
    generator_weights: Tuple[int, ...],
    c_val: Optional[Fraction] = None,
) -> Dict[str, object]:
    r"""Compute dimensions of the genus-2 deformation complex.

    For a modular Koszul algebra A with generators of specified weights:

    H^0(Def^{(2,0)}_cyc(A)):
      Infinitesimal automorphisms at genus 2.  For algebras with simple
      Lie symmetry acting by inner derivations, H^0 = 0 in the cyclic
      quotient.

    H^1(Def^{(2,0)}_cyc(A)):
      Infinitesimal deformations at genus 2.  This equals 1 for algebras
      with a single continuous parameter (the level k).  The deformation
      is the level direction d/dk.

    H^2(Def^{(2,0)}_cyc(A)):
      Obstructions.  By algebraic-family-rigidity, dim H^2_cyc = 1 for
      the entire standard Lie-theoretic landscape.

    The GRAPH-SUM SPACE at genus 2 has dimension:
      sum over boundary graphs of (number of channel assignments)
    This is the AMBIENT space in which the graph-sum amplitude lives.
    It is much larger than H^2_cyc = 1.

    For W_3 at genus 2:
      - 5 boundary graphs with a total of 2+4+2+8+4 = 20 channel assignments.
      - Z_2 parity kills some: 3 (theta) + 1 (lollipop) = 4 killed.
      - Surviving: 16 assignments.
      - Of these, 6 are diagonal (per-channel), 10 are surviving mixed.
      - Wait: let us count more carefully.
    """
    n_gen = len(generator_weights)
    n_channels = n_gen  # number of channel types

    # Count graph-sum assignments at genus 2
    # 6 graphs with edge counts 0, 1, 2, 1, 3, 2
    edge_counts = [0, 1, 2, 1, 3, 2]
    graph_names = ["smooth", "fig_eight", "banana", "dumbbell", "theta", "lollipop"]

    total_assignments = sum(n_channels ** e for e in edge_counts)
    diagonal_assignments = sum(n_channels if e > 0 else 1 for e in edge_counts)
    mixed_assignments = total_assignments - diagonal_assignments

    # For W_3: count Z_2-killed assignments
    z2_killed = 0
    z2_surviving_mixed = 0
    if n_gen == 2 and set(generator_weights) == {2, 3}:
        # Banana (2 edges): 2 mixed, both survive (vertex gets even W-count)
        # Theta (3 edges): 6 mixed, 3 killed (TTW-type), 3 survive (TWW-type)
        # Lollipop (2 edges): 2 mixed, 1 killed (TW: C_{TTW}=0), 1 survives (WT)
        z2_killed = 3 + 1  # theta TTW-type + lollipop TW
        z2_surviving_mixed = mixed_assignments - z2_killed

    return {
        'algebra_name': algebra_name,
        'generator_weights': generator_weights,
        'num_generators': n_gen,
        'h0_cyc': 0,
        'h1_cyc': 1,
        'h2_cyc': 1,
        'euler_char': 0,  # 0 - 1 + 1 = 0
        'kuranishi_vanishes': True,
        'graph_sum_space_dim': total_assignments,
        'diagonal_assignments': diagonal_assignments,
        'mixed_assignments': mixed_assignments,
        'z2_killed_assignments': z2_killed,
        'z2_surviving_mixed': z2_surviving_mixed,
        'cross_channel_nonzero': z2_surviving_mixed > 0,
        'notes': (
            f"H^2_cyc = 1 by algebraic-family-rigidity. "
            f"Kuranishi map vanishes by parity (s^{{-1}}eta odd). "
            f"Graph-sum space has {total_assignments} total assignments, "
            f"of which {z2_surviving_mixed} are surviving mixed-channel terms."
        ),
    }


# ============================================================================
# 7. The decisive computation: cross-channel vs R-matrix
# ============================================================================

def decisive_genus2_analysis(c_val: Fraction) -> Dict[str, object]:
    r"""The decisive analysis of multi-generator universality at genus 2.

    The question: does obs_2(W_3) = kappa(W_3) * lambda_2?

    This decomposes into:
      F_2^{full}(W_3) = F_2^{diagonal} + delta_F2^{cross-channel}

    where:
      F_2^{diagonal} = kappa * lambda_2^FP = 7c/6912 * 5/1 = 35c/6912 = 5c * 7/6912
                      = (5c/6) * (7/5760) = 7c/6912 * 5 = 35c/6912
                      Wait: kappa = 5c/6, lambda_2^FP = 7/5760.
                      F_2^{diagonal} = (5c/6)*(7/5760) = 35c/34560 = 7c/6912.

      delta_F2 = (c+204)/(16c).

    For universality at genus 2, we need delta_F2 = 0, which requires
    c + 204 = 0, i.e., c = -204.

    At generic c, delta_F2 != 0, so universality FAILS at genus 2 for W_3
    (in the absence of R-matrix corrections cancelling delta_F2).

    The ratio delta_F2 / F_2^{diagonal} = 432(c+204)/(7c^2):
      - At c = 4 (free boson pair):   432*124/(7*16) = 53568/112 = 478.3
      - At c = 50 (large c):          432*170/(7*2500) = 73440/17500 = 4.20
      - At c = 100:                    432*220/(7*10000) = 95040/70000 = 1.36
      - At c = infinity:              approaches 432/(7c) -> 0

    The cross-channel correction is LARGE relative to the diagonal term
    for small c, indicating that universality fails dramatically.

    CAVEAT (op:multi-generator-universality): This computation uses the
    TREE-LEVEL genus-1 vertex factor kappa_i/24.  The full CohFT
    R-matrix could introduce corrections that modify the genus-1 vertex
    factors in the multi-channel context.  Whether such R-corrections
    exactly cancel delta_F2 at ALL values of c simultaneously is the
    open problem.  This would require a MIRACULOUS cancellation:
    the R-matrix would need to produce exactly -(c+204)/(16c) at
    genus 2, which is a nontrivial functional identity in c.
    """
    kappa = Fraction(5) * c_val / 6
    fp2 = Fraction(7, 5760)
    F2_diag = kappa * fp2  # = 7c/6912

    delta = (c_val + 204) / (16 * c_val)
    F2_full = F2_diag + delta

    # Ratio
    if c_val != 0 and F2_diag != 0:
        ratio = delta / F2_diag
    else:
        ratio = None

    return {
        'c': c_val,
        'kappa': kappa,
        'lambda2_fp': fp2,
        'F2_diagonal': F2_diag,
        'delta_F2': delta,
        'F2_full': F2_full,
        'ratio_delta_over_diag': ratio,
        'universality_holds': delta == 0,
        'universality_c_value': Fraction(-204),  # only c where delta = 0
        'r_matrix_cancellation_needed': delta,
        'notes': (
            f"At c = {c_val}: "
            f"kappa = {kappa}, F2^diag = {F2_diag}, "
            f"delta_F2 = {delta}, F2^full = {F2_full}. "
            f"Universality {'holds' if delta == 0 else 'FAILS'} "
            f"(delta/diag = {ratio})."
        ),
    }


# ============================================================================
# 8. General multi-weight analysis for W_N
# ============================================================================

def wn_generator_weights(N: int) -> Tuple[int, ...]:
    """Generator weights for the W_N algebra.

    W_N has generators W_2 = T, W_3, ..., W_N of weights 2, 3, ..., N.
    """
    return tuple(range(2, N + 1))


def wn_kappa_components(N: int, c_val: Fraction) -> Dict[int, Fraction]:
    r"""Per-generator kappa components for W_N.

    kappa_h = c/h (leading pole of W_h(z) W_h(w) OPE divided by h).

    Actually: kappa(W_N) = c * (H_N - 1) where H_N = sum_{j=1}^N 1/j.
    Per-generator: kappa_j = c/j for j = 2, ..., N.
    Total: sum_{j=2}^N c/j = c * (H_N - 1).
    """
    return {j: c_val / j for j in range(2, N + 1)}


def wn_parity_analysis_genus2(N: int) -> Dict[str, object]:
    r"""Parity analysis for W_N at genus 2.

    Key finding: for N >= 3, W_N has generators of MULTIPLE weights
    (2, 3, ..., N), so mixed channels exist at genus 2.

    The Z_2 parity of W_N (when it exists) depends on N:
      - N = 3: W -> -W symmetry (Z_2).
               Forces odd-W-count structure constants to vanish.
               Some mixed channels survive (even W-count).
      - N = 4: W_3 -> -W_3 (Z_2 for odd-weight generators).
               W_4 is even-weight, not affected.
      - General: generators of odd weight have Z_2 parity;
                 generators of even weight do not.

    For ALL N >= 3:
      - The Kuranishi map vanishes by parity (independent of N).
      - Cross-channel corrections exist at genus 2.
      - The number of surviving mixed channels grows with N.
    """
    weights = wn_generator_weights(N)
    n_gen = len(weights)

    # Count weight parity classes
    even_weights = [w for w in weights if w % 2 == 0]
    odd_weights = [w for w in weights if w % 2 == 1]

    # At genus 2, count channel assignments on each graph
    edge_counts = [0, 1, 2, 1, 3, 2]  # smooth, fig8, banana, dumbbell, theta, lollipop
    total_assignments = sum(n_gen ** e for e in edge_counts)

    return {
        'N': N,
        'generator_weights': weights,
        'num_generators': n_gen,
        'even_weight_generators': even_weights,
        'odd_weight_generators': odd_weights,
        'total_genus2_assignments': total_assignments,
        'kuranishi_vanishes': True,
        'cross_channel_exists': N >= 3,
        'universality_proved': N <= 2,
        'universality_open': N >= 3,
        'notes': (
            f"W_{N} has {n_gen} generators of weights {weights}. "
            f"{'Uniform' if n_gen == 1 else 'Multi'}-weight. "
            f"Kuranishi map vanishes at ALL genera. "
            f"Cross-channel corrections {'exist' if N >= 3 else 'do not exist'} "
            f"at genus 2. "
            f"Tautological identification is "
            f"{'PROVED' if N <= 2 else 'OPEN'} at genus 2."
        ),
    }


# ============================================================================
# 9. Summary: the precise gap in multi-generator universality
# ============================================================================

def universality_gap_summary() -> Dict[str, object]:
    r"""Summary of the precise gap in multi-generator universality.

    PROVED:
      (1) dim H^2_cyc(A, A) = 1 for the standard Lie-theoretic landscape
          (thm:algebraic-family-rigidity).
      (2) The Kuranishi map vanishes at ALL genera, by parity of s^{-1}eta.
          This means Theta^min = eta tensor Gamma_A is unobstructed.
      (3) At genus 1, Gamma_A^{(1)} = kappa * lambda_1 UNCONDITIONALLY
          (thm:genus-universality).
      (4) For uniform-weight algebras, Gamma_A^{(g)} = kappa * lambda_g
          at ALL genera (no mixed channels possible).

    OPEN:
      (5) For multi-weight algebras at genus g >= 2, whether
          Gamma_A^{(g)} = kappa * lambda_g.

    THE GAP IS NOT IN THE KURANISHI MAP.  The Kuranishi map vanishes
    unconditionally.  The gap is in the TAUTOLOGICAL IDENTIFICATION:
    knowing that some MC solution Theta^min = eta tensor Gamma_A exists
    does not determine the actual value of Gamma_A at each genus.

    QUANTITATIVE EVIDENCE AGAINST UNIVERSALITY:
      For W_3 at genus 2: delta_F2 = (c+204)/(16c) is nonzero at generic c.
      This is the cross-channel correction from mixed-channel graph sums.

    The cross-channel correction arises from THREE graphs:
      - Banana: 3/c (2 mixed assignments, even W-count at vertex)
      - Theta: 9/(2c) (3 TWW-type assignments)
      - Lollipop: 1/16 (1 WT assignment)

    For universality to hold, the CohFT R-matrix corrections at genus >= 1
    must EXACTLY CANCEL delta_F2 at ALL values of c.  This is a nontrivial
    functional identity that has not been verified.

    STRUCTURE OF THE OBSTRUCTION:
      delta_F2 = 51/(4c) + 1/16
      = (c-dependent part from genus-0 vertices) + (genus-1 vertex correction)

    The 51/(4c) comes from PURE genus-0 data (banana + theta + barbell vertex factors).
    The 1/16 comes from the lollipop, which mixes genus-0 and genus-1 vertices.

    Even if R-matrix corrections modify the genus-1 vertex factor, they
    CANNOT change the genus-0 vertex factors (which are R-independent).
    Therefore, R-corrections can at most cancel the 1/16 piece.
    The 51/(4c) piece would need to be cancelled by a DIFFERENT mechanism
    (modified propagators, higher-genus R-corrections, or structural
    identities in the tautological ring).

    CORRECTION TO THE ABOVE: R-matrix corrections at genus g >= 1 modify
    the FULL graph amplitude, not just individual vertex factors.  The
    Givental-Teleman R-action acts on the ENTIRE CohFT, reshuffling
    contributions between graphs.  So in principle, R-corrections could
    cancel both the 51/(4c) and 1/16 pieces simultaneously.  Whether
    they do so for W_3 specifically requires computing the R-matrix
    and verifying the cancellation — this is op:multi-generator-universality.
    """
    return {
        'kuranishi_map_vanishes': True,
        'parity_argument_genus_independent': True,
        'genus_0_universality': 'PROVED (no cross-channel at tree level)',
        'genus_1_universality': 'PROVED UNCONDITIONALLY (single-edge graphs only)',
        'genus_2_uniform_weight': 'PROVED (no mixed channels)',
        'genus_2_multi_weight': 'OPEN (cross-channel corrections nonzero)',
        'w3_genus2_delta': '(c + 204) / (16c)',
        'w3_genus2_delta_decomposition': {
            'banana': '3/c',
            'theta': '9/(2c)',
            'lollipop': '1/16',
        },
        'gap_location': (
            'NOT the Kuranishi map (which vanishes by parity). '
            'The gap is the tautological identification '
            'Gamma_A^{(g)} = kappa * lambda_g at genus g >= 2 '
            'for multi-weight algebras.'
        ),
        'decisive_question': (
            'Does the CohFT R-matrix for W_3 produce corrections that '
            'exactly cancel delta_F2 = (c+204)/(16c) at ALL values of c?'
        ),
    }
