r"""Moonshine shadow tower: MC framework analysis of V^natural and monstrous moonshine.

MATHEMATICAL FRAMEWORK
======================

The Monster module V^natural (Frenkel-Lepowsky-Meurman 1988) is a holomorphic
VOA of central charge c = 24 with Monster group symmetry.  It is constructed
from the Leech lattice via a Z/2Z orbifold.

The j-function j(tau) = q^{-1} + 744 + 196884q + ... is the graded trace over
V^natural (Zhu's theorem for holomorphic VOAs + Borcherds' proof of monstrous
moonshine).  The normalized function J(tau) = j(tau) - 744 is the partition
function: Z(V^natural; tau) = J(tau).

SHADOW TOWER ANALYSIS
=====================

1. KAPPA(V^natural):

   V^natural has c = 24 and dim V_1 = 0 (no weight-1 currents).  The Leech
   lattice has no roots (shortest vectors have norm 4), and the Z/2Z orbifold
   kills the U(1) currents.

   For V^natural, there is no Heisenberg sector.  The modular characteristic
   is determined by the Virasoro sector alone:
     kappa(V^natural) = kappa(Vir_24) = c/2 = 12.

   This is DIFFERENT from kappa(V_Leech) = rank = 24, because the Leech lattice
   VOA V_Leech has 24 weight-1 currents (the Heisenberg sector at rank 24),
   while V^natural has none.

   AP20 verification: kappa(V^natural) = 12 is the modular characteristic of
   the FULL algebra V^natural, not just the Virasoro subalgebra.  Since the
   weight-2 primaries do not generate additional weight-1 currents, and the
   Sugawara construction is trivial (no affine subalgebra), the Virasoro
   contribution exhausts kappa.

2. SHADOW CLASS:

   V^natural is CLASS M (infinite shadow depth).  The argument:

   (a) The stress tensor T generates the Virasoro subalgebra at c = 24.
       The Virasoro self-OPE T(z)T(w) ~ c/2/(z-w)^4 + 2T/(z-w)^2 + dT/(z-w)
       has a quartic pole, which drives infinite shadow depth through the
       quartic contact invariant Q^contact_Vir = 10/[c(5c+22)].

   (b) At c = 24: Q^contact = 10/(24 * 142) = 10/3408 = 5/1704.
       This is nonzero, so Delta = 8*kappa*S_4 = 8*12*(5/1704) = 20/71 != 0.
       Therefore V^natural is class M by the single-line dichotomy
       (thm:single-line-dichotomy).

   (c) The 196883 weight-2 primaries contribute ADDITIONAL cubic and quartic
       terms.  The Griess algebra structure constants C^k_{ij} give nonzero
       three-point functions that modify S_3, S_4 beyond their Virasoro values.
       But the Virasoro contribution alone already forces class M.

3. VIRASORO SHADOW TOWER OF V^natural:

   The Virasoro subsector of V^natural gives a LOWER BOUND on the shadow tower.
   The full shadow tower receives contributions from all weight-2 primaries.

   At the Virasoro level (treating V^natural as generated by T alone):
     S_2 = kappa = 12
     S_3 = alpha = 2  (universal Virasoro value)
     S_4 = 10/[c(5c+22)] = 5/1704
     S_5, S_6, ... from the shadow tower ODE recursion at c = 24.

   The full V^natural tower has corrections from the Griess algebra at S_3
   and higher.  Computing these requires the full Griess algebra structure
   constants (frontier).

4. McKAY-THOMPSON SHADOW TOWERS:

   For each conjugacy class g of the Monster, the McKay-Thompson series
     T_g(tau) = sum_n Tr(g|V_n) q^{n-1}
   is a Hauptmodul for a genus-0 group Gamma_g < SL(2,R).

   The "twisted kappa" for class g is:
     kappa_g = (1/24) * sum_n n * Tr(g|V_n) * (leading modular weight)

   More precisely, the equivariant genus-1 amplitude is:
     F_1^g = Tr(g|V_1) * lambda_1^FP = 0  (since dim V_1 = 0 for V^natural)

   WAIT: this is wrong.  F_1 is NOT the dimension of V_1.  F_1 = kappa/24
   is an INTEGRAL over M_1.  The equivariant version should be:
     F_1^g = kappa_g / 24
   where kappa_g is the equivariant modular characteristic.

   For g = 1A (identity): kappa_1A = kappa = 12, F_1 = 1/2.
   For other g: kappa_g is read from the McKay-Thompson series T_g.

   The McKay-Thompson series T_g(tau) for class g has a q-expansion:
     T_g(tau) = q^{-1} + c_g(0) + c_g(1)*q + c_g(2)*q^2 + ...
   where c_g(n) = Tr(g|V_{n+1}).

   The genus-0 property (T_g is a Hauptmodul for Gamma_g) constrains
   the shadow tower: if T_g is a Hauptmodul, then the Rademacher exact
   formula determines all c_g(n) from c_g(-1) = 1 and the group Gamma_g.

5. ARITHMETIC DEPTH:

   The j-function j(tau) = E_4^3/Delta has the properties:
   - It is a WEIGHT-0 modular function for SL(2,Z).
   - The space of weight-0 modular functions (with at most a simple pole
     at infinity) is 1-dimensional: spanned by j - 744.
   - There are NO cusp forms of weight 0 for SL(2,Z).

   Naively, d_arith(V^natural) = 0 (no cusp-form obstruction at weight 0).
   But this misidentifies the arithmetic depth.  The SHADOW TOWER arithmetic
   depth measures obstructions at WEIGHT 12 (from lambda_1 in H^2(M_1) with
   its Hodge pairing).  The constrained Epstein zeta E_A(s) for V^natural
   involves the j-function's Fourier coefficients {c(n)}, which ARE related
   to L-functions through:
     sum c(n) n^{-s} = (Hecke L-series for j)
   This object does NOT factor into standard L-functions in any known way.

   The arithmetic of j is encoded in:
   - Singular moduli: j(tau_D) for CM points tau_D, which generate class fields
   - The Borcherds product: j(tau) = p^{-1} prod (1-p^m*q^n)^{c(mn)}
     where c(n) are the J-coefficients
   - The moonshine Lie algebra: the denominator formula for the Monster Lie
     algebra is related to the j-function

   CONCLUSION: d_arith(V^natural) = 0 at the genus-1 level (no cusp forms at
   weight 0), but the genus-2+ arithmetic involves the Borcherds product
   structure, which is vastly richer.  The shadow tower at genus 1 sees only
   kappa = 12; the arithmetic richness of moonshine lives at higher genera
   and in the equivariant (McKay-Thompson) data.

Mathematical references:
  - Frenkel-Lepowsky-Meurman (1988): Vertex Operator Algebras and the Monster
  - Conway-Norton (1979): Monstrous Moonshine
  - Borcherds (1992): Monstrous moonshine and monstrous Lie superalgebras
  - Zhu (1996): Modular invariance of characters of vertex operator algebras
  - Griess (1982): The friendly giant
  - Norton (1996): The Monster algebra
  - Conway-Norton (1979), Table 1: McKay-Thompson series for 194 classes
"""

from __future__ import annotations

import math
from fractions import Fraction
from functools import lru_cache
from typing import Any, Dict, List, Optional, Tuple

from sympy import (
    Rational, Symbol, Abs, bernoulli, cancel, factorial, sqrt,
)


# =========================================================================
# Constants
# =========================================================================

MONSTER_CENTRAL_CHARGE = Rational(24)
MONSTER_ORDER = 808017424794512875886459904961710757005754368000000000

# Dimensions of the first irreducible representations of the Monster
MONSTER_IRREP_DIMS = {
    'chi_1': 1,            # trivial
    'chi_2': 196883,       # smallest nontrivial
    'chi_3': 21296876,     # second smallest
    'chi_4': 842609326,    # third
}


# =========================================================================
# Faber-Pandharipande (local copy for independence)
# =========================================================================

def _faber_pandharipande(g: int) -> Rational:
    r"""lambda_g^FP = (2^{2g-1} - 1) / 2^{2g-1} * |B_{2g}| / (2g)!"""
    if g < 1:
        raise ValueError(f"Genus must be >= 1, got {g}")
    B_2g = Rational(bernoulli(2 * g))
    numerator = (Rational(2) ** (2 * g - 1) - 1) * Abs(B_2g)
    denominator = Rational(2) ** (2 * g - 1) * factorial(2 * g)
    return Rational(numerator, denominator)


# =========================================================================
# Shadow tower of V^natural: Virasoro sector
# =========================================================================

def monster_kappa() -> Rational:
    r"""kappa(V^natural) = c/2 = 12.

    V^natural has c = 24 and dim V_1 = 0 (no weight-1 currents).
    The modular characteristic is determined by the Virasoro sector:
    kappa(Vir_{24}) = 24/2 = 12.

    This is DIFFERENT from kappa(V_Leech) = rank = 24 for the Leech
    lattice VOA (which has 24 weight-1 currents).
    """
    return Rational(12)


def leech_kappa() -> Rational:
    r"""kappa(V_Leech) = rank = 24.

    The Leech lattice VOA has 24 weight-1 currents (Heisenberg at rank 24).
    Each boson contributes kappa_i = 1, so kappa_total = 24.
    """
    return Rational(24)


def _virasoro_shadow_coefficient(r: int) -> Rational:
    r"""Virasoro shadow coefficient S_r at c = 24.

    These are the shadow tower coefficients for the Virasoro subalgebra
    of V^natural (i.e., treating V^natural as if generated by T alone).

    S_2 = c/2 = 12
    S_3 = 2  (universal for Virasoro)
    S_4 = 10/[c(5c+22)] = 10/(24*142) = 5/1704
    S_r for r >= 5: recursion from the master equation.
    """
    if r < 2:
        return Rational(0)
    if r == 2:
        return Rational(12)  # c/2 = 24/2
    if r == 3:
        return Rational(2)   # universal Virasoro
    if r == 4:
        return Rational(5, 1704)  # 10/(24*142)

    # Recursion for r >= 5 (shadow tower ODE at c = 24)
    # 2r * S_r + sum_{j<k, j+k=r+2, j,k>=3} 2jk*S_j*S_k/c
    #          + [if r+2 even: m^2*S_m^2/c, m=(r+2)/2] = 0
    c = Rational(24)
    obstruction = Rational(0)
    for j in range(3, (r + 2) // 2 + 1):
        k = r + 2 - j
        if k < 3:
            continue
        Sj = _virasoro_shadow_coefficient(j)
        Sk = _virasoro_shadow_coefficient(k)
        if j < k:
            obstruction += 2 * j * k * Sj * Sk / c
        else:  # j == k
            obstruction += j * k * Sj * Sk / c

    return Rational(-obstruction, 2 * r)


@lru_cache(maxsize=64)
def virasoro_shadow_tower(max_r: int = 10) -> Dict[int, Rational]:
    """Virasoro shadow tower at c = 24: {r: S_r(c=24)} for r = 2..max_r.

    This is the LOWER BOUND on the V^natural shadow tower,
    computed from the Virasoro subsector alone.
    """
    return {r: _virasoro_shadow_coefficient(r) for r in range(2, max_r + 1)}


# =========================================================================
# Shadow tower invariants for V^natural
# =========================================================================

def monster_shadow_class() -> str:
    """Shadow class of V^natural: class M (infinite depth, proved).

    The Virasoro subalgebra at c = 24 has:
      S_4 = 5/1704 != 0
      Delta = 8 * kappa * S_4 = 8 * 12 * 5/1704 = 20/71 != 0.

    By the single-line dichotomy (thm:single-line-dichotomy),
    Delta != 0 implies infinite shadow depth (class M).

    The 196883 weight-2 primaries give additional contributions
    but cannot reduce the shadow depth (only increase it or keep
    it at infinity).
    """
    return 'M'


def monster_critical_discriminant() -> Rational:
    r"""Critical discriminant Delta(V^natural) at the Virasoro level.

    Delta = 8 * kappa * S_4.

    At the Virasoro level (S_4 = Q^contact_Vir at c=24):
      Delta = 8 * 12 * 5/1704 = 480/1704 = 20/71.

    The full discriminant receives additional contributions from
    the Griess algebra OPE, but is >= 20/71 > 0 in any case.
    """
    return Rational(20, 71)


def monster_shadow_growth_rate() -> float:
    r"""Shadow growth rate rho(V^natural) at the Virasoro level.

    rho = sqrt(9*alpha^2 + 2*Delta) / (2*|kappa|)

    With alpha = S_3 = 2, Delta = 20/71, kappa = 12:
      rho = sqrt(9*4 + 2*20/71) / (2*12)
          = sqrt(36 + 40/71) / 24
          = sqrt(2596/71) / 24
          = sqrt(649/71) / 12

    This is the growth rate from the Virasoro sector alone.
    """
    alpha = Rational(2)
    Delta = Rational(20, 71)
    kappa = Rational(12)
    rho_sq = (9 * alpha**2 + 2 * Delta) / (4 * kappa**2)
    return float(rho_sq) ** 0.5


def monster_shadow_data() -> Dict[str, Any]:
    """Complete shadow tower data for V^natural.

    Combines proved values (kappa, shadow class) with
    Virasoro-level shadow coefficients and frontier markers.
    """
    vir_tower = virasoro_shadow_tower(10)
    return {
        'label': 'V^natural',
        'central_charge': Rational(24),
        'kappa': monster_kappa(),
        'shadow_class': 'M',
        'shadow_depth': float('inf'),
        'dim_V1': 0,
        'dim_V2': 196884,
        'griess_algebra_dim': 196884,
        # Virasoro-level shadow coefficients (lower bounds)
        'S2_virasoro': vir_tower[2],
        'S3_virasoro': vir_tower[3],
        'S4_virasoro': vir_tower[4],
        'S5_virasoro': vir_tower[5],
        # Full shadow coefficients (with Griess algebra corrections)
        'S3_full': None,   # frontier
        'S4_full': None,   # frontier
        'critical_discriminant_virasoro': monster_critical_discriminant(),
        'shadow_growth_rate_virasoro': monster_shadow_growth_rate(),
        # Genus amplitudes (scalar level)
        'F1': monster_kappa() * _faber_pandharipande(1),
        'F2': monster_kappa() * _faber_pandharipande(2),
    }


# =========================================================================
# Comparison: V^natural vs V_Leech
# =========================================================================

def leech_shadow_data() -> Dict[str, Any]:
    """Shadow data for the Leech lattice VOA V_Leech."""
    kappa = leech_kappa()
    return {
        'label': 'V_Leech',
        'central_charge': Rational(24),
        'kappa': kappa,
        'shadow_class': 'G',
        'shadow_depth': 2,
        'dim_V1': 24,
        'dim_V2': 196884 + 24,  # 196884 primaries + 24 Heisenberg descendant
        'S2': kappa,
        'S3': Rational(0),
        'S4': Rational(0),
        'S5': Rational(0),
        'critical_discriminant': Rational(0),
        'shadow_growth_rate': 0.0,
        'F1': kappa * _faber_pandharipande(1),
        'F2': kappa * _faber_pandharipande(2),
    }


def monster_vs_leech_comparison() -> Dict[str, Any]:
    """Side-by-side comparison of V^natural and V_Leech.

    These are the two most important holomorphic c = 24 VOAs.
    V_Leech is a lattice VOA (class G); V^natural is an orbifold (class M).

    Same central charge, different kappa, different shadow class:
    this is the FIRST example where two holomorphic VOAs of the
    same c have different shadow classes.
    """
    monster = monster_shadow_data()
    leech = leech_shadow_data()

    return {
        'same_central_charge': monster['central_charge'] == leech['central_charge'],
        'same_kappa': monster['kappa'] == leech['kappa'],
        'same_shadow_class': monster['shadow_class'] == leech['shadow_class'],
        # Quantitative comparison
        'kappa_monster': monster['kappa'],
        'kappa_leech': leech['kappa'],
        'kappa_ratio': monster['kappa'] / leech['kappa'],
        'kappa_difference': leech['kappa'] - monster['kappa'],
        # Shadow class
        'class_monster': monster['shadow_class'],
        'class_leech': leech['shadow_class'],
        # Why different: V^natural has no weight-1 currents
        'dim_V1_monster': 0,
        'dim_V1_leech': 24,
        # Genus-1 amplitude (differs by factor 2!)
        'F1_monster': monster['F1'],
        'F1_leech': leech['F1'],
        'F1_ratio': leech['F1'] / monster['F1'],
        # The orbifold kills half the scalar curvature
        'orbifold_kappa_halving': True,
        # Summary
        'distinguishing_invariants': [
            'kappa: 12 vs 24',
            'shadow class: M vs G',
            'dim V_1: 0 vs 24',
            'S_3: 2 (Virasoro) vs 0',
            'shadow depth: infinity vs 2',
        ],
    }


# =========================================================================
# Genus amplitudes
# =========================================================================

def monster_genus_amplitude(g: int) -> Rational:
    r"""Scalar genus-g amplitude F_g(V^natural) = kappa * lambda_g^FP.

    F_g = 12 * lambda_g^FP.

    At genus >= 2, there are planted-forest corrections from the
    nonzero S_3, S_4 of the Virasoro sector.  These are NOT included
    here (this is the scalar-level amplitude only).
    """
    return monster_kappa() * _faber_pandharipande(g)


def leech_genus_amplitude(g: int) -> Rational:
    r"""Scalar genus-g amplitude F_g(V_Leech) = 24 * lambda_g^FP.

    Class G: no planted-forest corrections (S_3 = 0).
    """
    return leech_kappa() * _faber_pandharipande(g)


def genus_amplitude_comparison(max_g: int = 5) -> Dict[int, Dict[str, Rational]]:
    """Compare genus-g amplitudes for V^natural vs V_Leech."""
    result = {}
    for g in range(1, max_g + 1):
        F_monster = monster_genus_amplitude(g)
        F_leech = leech_genus_amplitude(g)
        result[g] = {
            'F_monster': F_monster,
            'F_leech': F_leech,
            'ratio': F_leech / F_monster,
        }
    return result


def monster_planted_forest_g2() -> Rational:
    r"""Genus-2 planted-forest correction for V^natural (Virasoro level).

    delta_pf = S_3 * (10*S_3 - kappa) / 48
             = 2 * (10*2 - 12) / 48
             = 2 * 8 / 48
             = 1/3.
    """
    S3 = _virasoro_shadow_coefficient(3)
    kappa = monster_kappa()
    return S3 * (10 * S3 - kappa) / 48


def monster_total_genus2() -> Rational:
    """Total genus-2 amplitude for V^natural (Virasoro level).

    A_2 = F_2 + delta_pf = 12*(7/5760) + 1/3 = 7/480 + 1/3 = 167/480.
    """
    return monster_genus_amplitude(2) + monster_planted_forest_g2()


# =========================================================================
# J-function coefficients
# =========================================================================

# Known coefficients of J(tau) = j(tau) - 744 (OEIS A014708)
KNOWN_J_COEFFICIENTS = {
    -1: 1,      # polar term q^{-1}
    0: 0,       # constant term (j has 744, J = j - 744 has 0)
    1: 196884,
    2: 21493760,
    3: 864299970,
    4: 20245856256,
    5: 333202640600,
    6: 4252023300096,
    7: 44656994071935,
    8: 401490886656000,
    9: 3176440229784420,
    10: 22567393309593600,
}


def j_coefficient(n: int) -> int:
    """Coefficient c(n) of J(tau) = sum c(n) q^n for n >= -1.

    J = j - 744 = q^{-1} + 196884q + 21493760q^2 + ...
    """
    if n in KNOWN_J_COEFFICIENTS:
        return KNOWN_J_COEFFICIENTS[n]
    raise ValueError(
        f"J-function coefficient at n={n} not tabulated (n must be in [-1, 10])"
    )


# =========================================================================
# Monster representation decompositions
# =========================================================================

# V_n decomposes into Monster irreps.  The first few:
# dim V_1 = 196884 = 1 + 196883  (McKay's observation)
# dim V_2 = 21493760 = 1 + 196883 + 21296876
# dim V_3 = 864299970 = 1 + 196883 + 196883 + 21296876 + 842609326

MONSTER_DECOMPOSITIONS = {
    0: {
        'total': 1,
        'irreps': [(1, 'chi_1')],
        'description': 'vacuum',
    },
    1: {
        'total': 196884,
        'irreps': [(1, 'chi_1'), (196883, 'chi_2')],
        'description': '196884 = 1 + 196883 (McKay observation)',
    },
    2: {
        'total': 21493760,
        'irreps': [(1, 'chi_1'), (196883, 'chi_2'), (21296876, 'chi_3')],
        'description': '21493760 = 1 + 196883 + 21296876',
    },
    3: {
        'total': 864299970,
        'irreps': [
            (1, 'chi_1'), (1, 'chi_1'),
            (196883, 'chi_2'), (196883, 'chi_2'),
            (21296876, 'chi_3'), (842609326, 'chi_4'),
        ],
        'description': (
            '864299970 = 2*1 + 2*196883 + 21296876 + 842609326'
        ),
    },
}


def monster_rep_decomposition(n: int) -> Optional[Dict[str, Any]]:
    """Decomposition of V_n into Monster representations.

    Returns None if not tabulated.
    """
    if n in MONSTER_DECOMPOSITIONS:
        d = MONSTER_DECOMPOSITIONS[n].copy()
        d['weight'] = n
        return d
    return None


def verify_decomposition_totals() -> bool:
    """Verify that irrep dimensions sum to the J-function coefficients.

    dim V_0 = 1 = J[-1] (from the q^{-1} term)
    dim V_n = J[n] for n >= 1 (since J = q^{-1} + sum_{n>=1} c(n) q^n
    and dim V_n = c(n) for the n-th graded piece).

    CORRECTION: The graded piece V_n of V^natural has n >= 0 with
    V_0 = vacuum (1-dimensional), and the grading convention is
    Z(tau) = q^{-1} + sum_{n>=0} dim(V_{n+1}) q^n.
    Actually: Z = sum_{n>=0} dim(V_n) q^{n-1} = q^{-1} * sum dim(V_n) q^n.
    So dim(V_0) = 1 (from q^{-1}), dim(V_1) = 0 (from c(0) = 0),
    dim(V_2) = 196884 (from c(1) = 196884).

    BUT: the standard convention for V^natural is:
      V^natural = bigoplus_{n >= -1} V_n with V_{-1} = vacuum.
    So V_{-1} = 1 (q^{-1}), V_0 = 0, V_1 = 196884, V_2 = 21493760.

    The decomposition table uses the convention where the "weight-n"
    space V_n has dim = J[n] for n >= 1, dim(V_0) = 1 from the vacuum.
    Actually: the standard grading has V^natural = bigoplus V_n with
    L_0 eigenvalue n >= 0.  The partition function is
      Z(tau) = Tr q^{L_0 - c/24} = q^{-1} sum dim(V_n) q^n
    So the q^{-1} coefficient gives dim(V_0) = 1.
    The q^0 coefficient gives dim(V_1) = 0.
    The q^1 coefficient gives dim(V_2) = 196884.

    Convention here: MONSTER_DECOMPOSITIONS[n] describes V_{n+1}, the
    space at L_0 = n+1, whose dimension is J[n] for n >= 1, and
    V_0 (the vacuum) at J[-1] = 1.

    SIMPLIFICATION: Just verify the sum of irrep dims equals the total.
    """
    for n, data in MONSTER_DECOMPOSITIONS.items():
        total = sum(dim for dim, _ in data['irreps'])
        if total != data['total']:
            return False
    return True


# =========================================================================
# McKay-Thompson series
# =========================================================================

# Known McKay-Thompson series coefficients for small conjugacy classes.
# Convention: T_g(tau) = q^{-1} + sum_{n >= 0} c_g(n) q^n.
# These are Hauptmoduln for genus-0 groups Gamma_g.

MCKAY_THOMPSON_DATA = {
    '1A': {
        'description': 'Identity (= J-function)',
        'genus_zero_group': 'SL(2,Z)',
        'element_order': 1,
        'coefficients': {
            0: 0, 1: 196884, 2: 21493760, 3: 864299970,
            4: 20245856256, 5: 333202640600,
        },
        'centralizer_order': MONSTER_ORDER,
    },
    '2A': {
        'description': 'Baby Monster involution (class 2A)',
        'genus_zero_group': 'Gamma_0(2)+',
        'element_order': 2,
        'coefficients': {
            0: 0, 1: 4372, 2: 96256, 3: 1240002,
            4: 10698752, 5: 74428120,
        },
        'centralizer_order': 4154781481226426191177580544000000,
        'related_group': 'Baby Monster 2.B',
    },
    '2B': {
        'description': 'Fischer involution (class 2B)',
        'genus_zero_group': 'Gamma_0(2)',
        'element_order': 2,
        'coefficients': {
            0: 0, 1: -4372, 2: 96256, 3: -1240002,
            4: 10698752, 5: -74428120,
        },
        'centralizer_order': None,  # 2^1+24 . Co_1
        'related_group': '2^{1+24}.Co_1',
    },
    '3A': {
        'description': 'Class 3A',
        'genus_zero_group': 'Gamma_0(3)+',
        'element_order': 3,
        'coefficients': {
            0: 0, 1: 783, 2: 8672, 3: 65367,
            4: 371520, 5: 1741655,
        },
    },
    '3B': {
        'description': 'Class 3B',
        'genus_zero_group': 'Gamma_0(3)',
        'element_order': 3,
        'coefficients': {
            0: 0, 1: -54, 2: 782, 3: -4860,
            4: 20430, 5: -72576,
        },
    },
    '5A': {
        'description': 'Class 5A',
        'genus_zero_group': 'Gamma_0(5)+',
        'element_order': 5,
        'coefficients': {
            0: 0, 1: 134, 2: 760, 3: 3345,
            4: 12256, 5: 39350,
        },
    },
    '7A': {
        'description': 'Class 7A',
        'genus_zero_group': 'Gamma_0(7)+',
        'element_order': 7,
        'coefficients': {
            0: 0, 1: 51, 2: 204, 3: 681,
            4: 1956, 5: 5135,
        },
    },
    '13A': {
        'description': 'Class 13A',
        'genus_zero_group': 'Gamma_0(13)+',
        'element_order': 13,
        'coefficients': {
            0: 0, 1: 12, 2: 28, 3: 66,
            4: 132, 5: 260,
        },
    },
}


def mckay_thompson_coefficients(conjugacy_class: str,
                                 max_n: int = 5) -> Tuple[int, ...]:
    """Coefficients of T_g(tau) for a given conjugacy class g.

    Returns (c(0), c(1), ..., c(max_n)) where T_g = q^{-1} + sum c(n) q^n.
    """
    if conjugacy_class not in MCKAY_THOMPSON_DATA:
        raise ValueError(
            f"Unknown conjugacy class: {conjugacy_class}. "
            f"Known: {list(MCKAY_THOMPSON_DATA.keys())}"
        )
    data = MCKAY_THOMPSON_DATA[conjugacy_class]['coefficients']
    result = []
    for n in range(max_n + 1):
        if n in data:
            result.append(data[n])
        else:
            result.append(None)
    return tuple(result)


def mckay_thompson_shadow_kappa(conjugacy_class: str) -> Optional[Rational]:
    """Equivariant modular characteristic kappa_g.

    For the identity 1A: kappa_1A = kappa(V^natural) = 12.

    For a general element g of order N, the McKay-Thompson series
    T_g(tau) has level N.  The equivariant kappa is related to the
    Rademacher sum:
      kappa_g = (1/24) * c_g(0) (if the Hauptmodul has c_g(0) = 0,
      then the equivariant genus-1 amplitude vanishes).

    NOTE: c_g(0) = 0 for ALL conjugacy classes (this is a consequence
    of the Hauptmodul property: the unique Hauptmodul for Gamma_g
    normalized to have q^{-1} leading term has vanishing constant term).
    Therefore kappa_g is NOT simply c_g(0)/24.

    CORRECT APPROACH: kappa_g is defined via the equivariant bar complex.
    At genus 1, the g-twisted partition function Tr(g * q^{L_0 - c/24})
    gives T_g(tau).  The equivariant modular characteristic is:
      kappa_g = Tr(g|curvature class) = Tr(g on the kappa-eigenspace)
    For the identity: kappa_1A = Tr(1|V) * kappa = kappa = 12.
    For a general g: kappa_g = Tr(g acting on the bar-complex genus-1 class).

    Without the explicit bar complex of V^natural, we can only compute
    kappa_g for the Virasoro sector:
      kappa_g^{Vir} = (c/2) * chi_g(1) where chi_g(1) = 1 for all g.
    So kappa_g^{Vir} = 12 for all g.

    The actual kappa_g for V^natural includes corrections from the
    weight-2 primaries: kappa_g = 12 + (correction from Griess algebra).
    These corrections are the equivariant version of the S_3 contribution.
    """
    if conjugacy_class == '1A':
        return Rational(12)
    # For other classes: the Virasoro contribution is always 12
    # (the Virasoro algebra is a singlet under M, so Tr(g|Vir) = 1 for all g).
    # The Griess algebra correction is frontier.
    return Rational(12)  # Virasoro level only


def mckay_thompson_equivariant_F1(conjugacy_class: str) -> Optional[Rational]:
    """Equivariant genus-1 amplitude F_1^g.

    F_1^g = kappa_g / 24.

    At the Virasoro level, kappa_g = 12 for all g, so F_1^g = 1/2.

    The equivariant corrections from the Griess algebra would modify this.
    """
    kappa_g = mckay_thompson_shadow_kappa(conjugacy_class)
    if kappa_g is None:
        return None
    return kappa_g / 24


# =========================================================================
# McKay-Thompson shadow towers (equivariant)
# =========================================================================

def mckay_thompson_genus0_property(conjugacy_class: str) -> Dict[str, Any]:
    """The genus-0 property of T_g and its implications for the MC framework.

    Conway-Norton conjecture (proved by Borcherds 1992):
    T_g is a Hauptmodul (= generator of function field) for a
    genus-0 group Gamma_g < SL(2,R).

    MC IMPLICATION: The genus-0 property means that the modular
    data of V^natural at genus 0 is MAXIMALLY SIMPLE for every g.
    The Hauptmodul property is equivalent to:
      (a) T_g has no poles except at the cusp.
      (b) T_g generates the function field of X(Gamma_g).
      (c) The Rademacher sum converges and determines T_g exactly.

    In the MC framework, this translates to: the genus-0 shadow
    (the arity-2 component of Theta_A projected to the g-twisted sector)
    is determined by a SINGLE parameter (the level N = order(g)).
    """
    if conjugacy_class not in MCKAY_THOMPSON_DATA:
        raise ValueError(f"Unknown conjugacy class: {conjugacy_class}")
    data = MCKAY_THOMPSON_DATA[conjugacy_class]
    return {
        'conjugacy_class': conjugacy_class,
        'element_order': data['element_order'],
        'genus_zero_group': data['genus_zero_group'],
        'hauptmodul': True,
        'constant_term_vanishes': data['coefficients'].get(0) == 0,
        'mc_interpretation': (
            'genus-0 Hauptmodul property = maximally simple '
            'genus-0 shadow; g-twisted arity-2 component of Theta_A '
            'is determined by element order N alone'
        ),
    }


# =========================================================================
# Arithmetic depth of V^natural
# =========================================================================

def monster_arithmetic_depth() -> Dict[str, Any]:
    """Arithmetic depth analysis of V^natural.

    The arithmetic depth d_arith classifies the cusp-form content
    of the genus-1 theta/partition function.

    For V^natural: Z = J(tau) = j(tau) - 744.
    j(tau) = E_4^3 / Delta, a weight-0 modular function.

    The space of weight-0 modular functions with at most a simple
    pole at infinity is 1-dimensional (spanned by J).  There are
    NO cusp forms of weight 0 for SL(2,Z).

    Therefore: d_arith(V^natural) = 0 at genus 1.

    However, the arithmetic content of moonshine is VASTLY richer
    than what d_arith captures:

    (a) The J-function coefficients {c(n)} are related to Monster
        representations (moonshine = arithmetic of the Monster).
    (b) Singular moduli j(tau_D) generate class fields.
    (c) The Borcherds product connects to automorphic forms on O(2,26).
    (d) At genus 2+, the moonshine Lie algebra provides additional
        arithmetic structure.

    The MC framework sees moonshine primarily through:
    - The equivariant McKay-Thompson shadow towers (194 towers)
    - The genus-0 property (Hauptmodul constraint on Theta_A)
    - The Griess algebra structure constants (determining S_3, S_4 corrections)
    """
    return {
        'genus_1_arithmetic_depth': 0,
        'cusp_form_content_weight_0': 'none (dim S_0(SL_2Z) = 0)',
        'partition_function': 'J(tau) = j(tau) - 744',
        'j_function_factorization': 'E_4^3 / Delta',
        'genus_0_hauptmodul': True,
        'rademacher_exact': True,
        'arithmetic_beyond_shadow_tower': [
            'singular moduli and class field theory',
            'Borcherds product on O(2,26)',
            'moonshine Lie algebra denominator formula',
            'equivariant McKay-Thompson towers (194 classes)',
            'genus-2+ Siegel modular forms',
        ],
        'mc_moonshine_interface': (
            'The MC framework sees moonshine through the equivariant '
            'shadow towers T_g -> kappa_g, S_3^g, ... and the genus-0 '
            'Hauptmodul constraint. The full arithmetic of moonshine '
            '(singular moduli, Borcherds products, class field theory) '
            'lives beyond the scalar shadow tower and is accessed through '
            'the equivariant and higher-genus MC data.'
        ),
    }


# =========================================================================
# Leech lattice arithmetic depth
# =========================================================================

def leech_arithmetic_depth() -> Dict[str, Any]:
    """Arithmetic depth of V_Leech.

    The Leech lattice theta series:
      Theta_Leech = E_12 - (65520/691) * Delta_12

    This has d_arith = 1 (one cusp form Delta_12 of weight 12).
    The Epstein zeta of the Leech lattice connects to L(s, Delta_12).
    """
    return {
        'genus_1_arithmetic_depth': 1,
        'cusp_form': 'Delta_12 (Ramanujan discriminant)',
        'c_delta': Fraction(-65520, 691),
        'theta_decomposition': 'E_12 - (65520/691) * Delta_12',
        'L_function': 'L(s, Delta_12) = sum tau(n) n^{-s}',
    }


# =========================================================================
# The orbifold shadow dichotomy
# =========================================================================

def orbifold_shadow_dichotomy() -> Dict[str, Any]:
    """The V_Leech -> V^natural orbifold and its shadow tower effect.

    V^natural is the Z/2Z orbifold of V_Leech.  The orbifold:
    (1) Kills the 24 weight-1 currents (Heisenberg sector).
    (2) Introduces 196884 weight-2 fields (from the twisted sector).
    (3) Halves kappa: 24 -> 12.
    (4) Changes shadow class: G -> M.

    This is the SHADOW TOWER MANIFESTATION of the orbifold:
    - Removing weight-1 currents eliminates the Heisenberg contribution
      to kappa (which was rank = 24).
    - The surviving Virasoro gives kappa = c/2 = 12.
    - The twisted sector introduces nonlinear OPE structure (the Griess
      algebra), driving the shadow class from G (terminates at arity 2)
      to M (infinite depth).
    """
    return {
        'orbifold_type': 'Z/2Z',
        'source': 'V_Leech',
        'target': 'V^natural',
        'kappa_change': {'before': 24, 'after': 12, 'ratio': Rational(1, 2)},
        'class_change': {'before': 'G', 'after': 'M'},
        'depth_change': {'before': 2, 'after': float('inf')},
        'mechanism': (
            'Orbifold kills weight-1 currents (Heisenberg sector), '
            'halving kappa. Twisted sector introduces Griess algebra '
            '(dim = 196884) with nonlinear OPE, forcing infinite shadow depth.'
        ),
        'dim_V1_change': {'before': 24, 'after': 0},
    }


# =========================================================================
# Griess algebra and the cubic shadow
# =========================================================================

def griess_algebra_data() -> Dict[str, Any]:
    """Data about the Griess algebra of V^natural.

    The Griess algebra is the weight-2 space V_2 with the product
    induced by the OPE: a * b = a_{(1)} b (the mode-(1) product).
    It is a commutative nonassociative algebra of dimension 196884.

    The Monster M acts as automorphisms (Griess 1982).

    The algebra decomposes under the Virasoro as:
      V_2 = C*omega/2 + W
    where omega/2 = L_{-2}|0> is the conformal vector (generating
    the Virasoro) and W is the 196883-dimensional space of weight-2
    primaries (the smallest nontrivial Monster representation).

    The cubic shadow S_3 for V^natural involves:
      S_3 = S_3^{Vir} + S_3^{Griess correction}
    where S_3^{Vir} = 2 (the universal Virasoro value at any c)
    and S_3^{Griess correction} depends on the three-point function
    of weight-2 primaries.

    The three-point function <W_i(z_1) W_j(z_2) W_k(z_3)> gives
    the Griess algebra structure constants C_{ijk}.  The Norton
    inequality constrains these: |C_{ijk}|^2 <= <W_i,W_i><W_j,W_j><W_k,W_k>.
    """
    return {
        'dimension': 196884,
        'decomposition_under_virasoro': {
            'conformal_vector': 1,
            'primary_space': 196883,
        },
        'algebra_properties': [
            'commutative',
            'nonassociative',
            'Monster symmetry',
            'Norton inequality',
            'positive-definite inner product',
        ],
        'S3_virasoro_contribution': Rational(2),
        'S3_griess_correction': 'frontier (requires structure constants)',
        'known_constraints': {
            'norton_inequality': True,
            'positive_definite_form': True,
            'monster_invariant_subspace': 'C*omega/2 (trivial rep)',
        },
    }


# =========================================================================
# Synthesis: where moonshine lives in the MC framework
# =========================================================================

def moonshine_mc_synthesis() -> Dict[str, Any]:
    """Summary: how the MC framework sees monstrous moonshine.

    The MC framework organizes moonshine data through the MC element
    Theta_{V^natural} in the modular convolution algebra g^mod_{V^natural}.

    What the MC framework SEES:

    1. SCALAR LEVEL (kappa):
       kappa(V^natural) = 12. This is the SAME as kappa(Vir_{24}).
       At this level, V^natural is indistinguishable from any other
       c = 24 VOA with no weight-1 currents.
       kappa(V_Leech) = 24. This IS distinguished.

    2. SHADOW CLASS:
       V^natural is class M (infinite depth).
       V_Leech is class G (depth 2).
       The shadow class distinguishes the orbifold from the parent.

    3. VIRASORO SHADOW TOWER:
       {S_r^{Vir}(c=24)} is computable to arbitrary order.
       This is a LOWER BOUND on the V^natural shadow tower.

    4. GRIESS ALGEBRA CORRECTIONS:
       The full shadow tower of V^natural is S_r^{Vir} + delta S_r^{Griess}.
       Computing delta S_r^{Griess} requires the Griess algebra structure
       constants.  This is a frontier computation.

    5. EQUIVARIANT SHADOW TOWERS:
       The 194 McKay-Thompson series give 194 equivariant shadow towers.
       At the Virasoro level, all 194 have kappa_g = 12 (the Virasoro
       is a Monster singlet).  The Griess algebra corrections are
       g-dependent and encode the full moonshine data.

    6. GENUS-0 PROPERTY:
       The Hauptmodul property of T_g is a constraint on the genus-0
       component of the equivariant MC element.  In the MC language:
       "the genus-0 g-twisted shadow is maximally simple."

    What the MC framework DOES NOT SEE (at the scalar level):

    1. The j-function coefficients (these are encoded in the FULL
       genus-0 OPE, not just the shadow tower).
    2. Singular moduli and class field theory.
    3. The Borcherds product structure.
    4. The moonshine Lie algebra.
    5. The specific Monster representation content of each V_n.
    """
    return {
        'what_mc_sees': {
            'kappa': 'V^natural distinguished from V_Leech (12 vs 24)',
            'shadow_class': 'class M (infinite depth) vs class G for lattices',
            'virasoro_tower': 'computable lower bound on full tower',
            'equivariant_towers': '194 McKay-Thompson shadow towers',
            'genus_0_constraint': 'Hauptmodul = maximally simple genus-0 shadow',
        },
        'what_mc_does_not_see_at_scalar_level': {
            'j_coefficients': 'encoded in full genus-0 OPE',
            'singular_moduli': 'CM theory, not shadow tower data',
            'borcherds_product': 'denominator formula for moonshine Lie algebra',
            'monster_reps': 'specific irrep decomposition of V_n',
        },
        'frontier_computations': [
            'Griess algebra structure constants -> S_3, S_4 corrections',
            'equivariant bar complex -> kappa_g corrections',
            'genus-2 moonshine -> Siegel modular forms for Monster',
            'Borcherds-Kac-Moody connection -> MC for moonshine Lie algebra',
        ],
        'key_insight': (
            'Monstrous moonshine lives primarily in the EQUIVARIANT data '
            '(194 McKay-Thompson towers) and the GRIESS ALGEBRA corrections '
            'to the scalar shadow tower. The scalar shadow tower alone sees '
            'only the Virasoro subsector, which distinguishes V^natural from '
            'V_Leech but not from other hypothetical c=24 VOAs with dim V_1 = 0. '
            'The genus-0 Hauptmodul property is a constraint on Theta_{V^natural} '
            'that the MC framework can formalize but not yet derive.'
        ),
    }


# =========================================================================
# Full atlas construction
# =========================================================================

def full_moonshine_shadow_atlas() -> Dict[str, Any]:
    """Complete moonshine shadow atlas.

    Combines:
    - V^natural shadow data
    - V_Leech shadow data (for comparison)
    - Monster vs Leech comparison
    - Virasoro shadow tower at c = 24
    - McKay-Thompson data for first few classes
    - Arithmetic depth analysis
    - Orbifold dichotomy
    - MC synthesis
    """
    atlas = {
        'monster': monster_shadow_data(),
        'leech': leech_shadow_data(),
        'comparison': monster_vs_leech_comparison(),
        'virasoro_tower': virasoro_shadow_tower(10),
        'mckay_thompson': {
            cls: {
                'coefficients': mckay_thompson_coefficients(cls, 5),
                'genus_0': mckay_thompson_genus0_property(cls),
                'kappa_equivariant': mckay_thompson_shadow_kappa(cls),
                'F1_equivariant': mckay_thompson_equivariant_F1(cls),
            }
            for cls in MCKAY_THOMPSON_DATA
        },
        'arithmetic_depth_monster': monster_arithmetic_depth(),
        'arithmetic_depth_leech': leech_arithmetic_depth(),
        'orbifold_dichotomy': orbifold_shadow_dichotomy(),
        'griess_algebra': griess_algebra_data(),
        'genus_amplitudes': genus_amplitude_comparison(5),
        'synthesis': moonshine_mc_synthesis(),
    }
    return atlas
