"""Baxter TQ relation for Y(sl_2) — pilot computation for MC3 path.

The Baxter TQ relation is the three-term identity in K_0(O_Y):

    [V_1(a)] * [M(lambda, b)] = [M(lambda+1, ...)] + [M(lambda-1, ...)]

where V_1(a) is the 2-dimensional evaluation module (pullback of the
standard sl_2 rep via ev_a), and M(lambda, b) is a Verma-like module
of highest weight lambda.

This module verifies:
  1. The K_0 identity at the level of characters (formal weight multiplicities).
  2. The short exact sequence 0 -> M(lam-1) -> V_1 tensor M(lam) -> M(lam+1) -> 0
     at the level of graded dimensions.
  3. The Yang R-matrix computation for V_1(a) tensor V_1(b).
  4. Transfer matrix eigenvalues and the TQ functional equation.

Mathematical setup:
  - Y(sl_2) in the Drinfeld presentation: generators e, f, h (level 0)
    and E, F, H (level 1).
  - [h, e] = 2e, [h, f] = -2f, [e, f] = h  (level 0 = sl_2)
  - [h, E] = 2E, [h, F] = -2F, [H, e] = 2E, [H, f] = -2F  (mixed)
  - [E, F] = H + h^2/2  (level 1 commutation)
  - Evaluation homomorphism ev_a: E -> a*e, F -> a*f, H -> a*h
  - V_1(a) = pullback of standard 2-dim sl_2 rep via ev_a
  - Verma module M(lambda): infinite-dimensional, weight spaces
    lambda, lambda-2, lambda-4, ... each of dimension 1.

CONVENTIONS:
  - Cohomological grading (consistent with the monograph).
  - sl_2 basis: e, h, f with standard structure constants.
  - Weights are integers (or half-integers for spin reps).
  - K_0 classes are formal sums of weight-space dimensions.

References:
  - yangians.tex, sec:yangian-rep-bar, conj:baxter-exact-triangles
  - Hernandez-Jimbo, Baxter's relations and spectra of quantum integrable models
  - Zhang, Shifted Yangians and TQ relations
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import numpy as np
from sympy import Matrix, Rational, Symbol, eye, simplify, symbols, oo


# ---------------------------------------------------------------------------
# Weight data types
# ---------------------------------------------------------------------------

# A formal character is a dict: weight -> multiplicity.
# Weights are integers (for integral highest weight modules).
FormalCharacter = Dict[int, int]


def formal_character_equal(chi1: FormalCharacter, chi2: FormalCharacter,
                           max_depth: int = 50) -> bool:
    """Compare two formal characters up to a finite depth.

    For infinite-dimensional modules (Verma), we truncate at max_depth
    weight levels below the highest weight.
    """
    all_weights = set(chi1.keys()) | set(chi2.keys())
    for w in all_weights:
        if chi1.get(w, 0) != chi2.get(w, 0):
            return False
    return True


# ---------------------------------------------------------------------------
# sl_2 representations
# ---------------------------------------------------------------------------

def sl2_fd_character(dim: int) -> FormalCharacter:
    """Formal character of the (dim)-dimensional irreducible sl_2 representation.

    V_n has dimension n+1 and weights n, n-2, ..., -n.
    So the dim-dimensional rep has highest weight dim-1.

    Args:
        dim: dimension of the representation (dim >= 1).

    Returns:
        dict: weight -> multiplicity (all multiplicities are 1).
    """
    if dim < 1:
        raise ValueError(f"Dimension must be >= 1, got {dim}")
    hw = dim - 1  # highest weight
    return {hw - 2 * k: 1 for k in range(dim)}


def sl2_verma_character(lam: int, depth: int = 50) -> FormalCharacter:
    """Formal character of the Verma module M(lambda) for sl_2.

    M(lambda) has weight spaces: lambda, lambda-2, lambda-4, ...
    Each weight space is 1-dimensional (generated by f^k applied to
    the highest weight vector).

    Args:
        lam: highest weight (integer).
        depth: number of weight levels to compute.

    Returns:
        dict: weight -> multiplicity.
    """
    return {lam - 2 * k: 1 for k in range(depth)}


def tensor_product_characters(chi1: FormalCharacter,
                              chi2: FormalCharacter) -> FormalCharacter:
    """Compute the character of the tensor product of two representations.

    (chi1 tensor chi2)(mu) = sum_{mu1 + mu2 = mu} chi1(mu1) * chi2(mu2).
    """
    result: FormalCharacter = {}
    for w1, m1 in chi1.items():
        for w2, m2 in chi2.items():
            w = w1 + w2
            result[w] = result.get(w, 0) + m1 * m2
    return result


def sum_characters(*chars: FormalCharacter) -> FormalCharacter:
    """Compute the direct sum of formal characters."""
    result: FormalCharacter = {}
    for chi in chars:
        for w, m in chi.items():
            result[w] = result.get(w, 0) + m
    return result


def subtract_characters(chi1: FormalCharacter,
                        chi2: FormalCharacter) -> FormalCharacter:
    """Subtract chi2 from chi1 (for exact sequence verification)."""
    result = dict(chi1)
    for w, m in chi2.items():
        result[w] = result.get(w, 0) - m
    # Clean up zeros
    return {w: m for w, m in result.items() if m != 0}


# ---------------------------------------------------------------------------
# Evaluation modules for Y(sl_2)
# ---------------------------------------------------------------------------

def eval_module_V1() -> FormalCharacter:
    """Character of the 2-dimensional evaluation module V_1(a).

    V_1(a) = pullback of the standard 2-dim sl_2 rep via ev_a.
    Weights: +1, -1 (each multiplicity 1).
    The evaluation parameter a does not affect the character.
    """
    return sl2_fd_character(2)


def eval_module_Vn(n: int) -> FormalCharacter:
    """Character of the (n+1)-dimensional evaluation module V_n(a).

    V_n(a) = pullback of the (n+1)-dim irreducible sl_2 rep via ev_a.
    """
    return sl2_fd_character(n + 1)


# ---------------------------------------------------------------------------
# Baxter TQ relation in K_0
# ---------------------------------------------------------------------------

def baxter_tq_k0(lam: int, depth: int = 50) -> Tuple[FormalCharacter,
                                                       FormalCharacter]:
    """Verify the Baxter TQ relation in K_0(O_Y) for Y(sl_2).

    The identity is:
        [V_1] * [M(lam)] = [M(lam+1)] + [M(lam-1)]

    in K_0, where * is the tensor product.

    Returns:
        (lhs_character, rhs_character) — both truncated to depth levels.
    """
    V1 = eval_module_V1()
    M_lam = sl2_verma_character(lam, depth=depth)

    # LHS: V_1 tensor M(lam)
    lhs = tensor_product_characters(V1, M_lam)

    # RHS: M(lam+1) + M(lam-1)
    M_plus = sl2_verma_character(lam + 1, depth=depth)
    M_minus = sl2_verma_character(lam - 1, depth=depth)
    rhs = sum_characters(M_plus, M_minus)

    return lhs, rhs


def verify_baxter_tq_k0(lam: int, depth: int = 50) -> bool:
    """Check whether the Baxter TQ identity holds at K_0 level.

    Returns True if [V_1][M(lam)] = [M(lam+1)] + [M(lam-1)]
    as formal characters, truncated at the given depth.
    """
    lhs, rhs = baxter_tq_k0(lam, depth=depth)
    return formal_character_equal(lhs, rhs)


def baxter_tq_higher_spin(n: int, lam: int,
                           depth: int = 50) -> Tuple[FormalCharacter,
                                                      FormalCharacter]:
    """Higher-spin Baxter TQ relation in K_0.

    [V_n] * [M(lam)] = sum_{j=0}^{n} [M(lam + n - 2j)]
                      = [M(lam+n)] + [M(lam+n-2)] + ... + [M(lam-n)]

    This is the Clebsch-Gordan decomposition at the K_0 level.

    Args:
        n: spin label (V_n is (n+1)-dimensional).
        lam: highest weight of the Verma module.
        depth: truncation depth.

    Returns:
        (lhs, rhs) characters.
    """
    Vn = eval_module_Vn(n)
    M_lam = sl2_verma_character(lam, depth=depth)

    lhs = tensor_product_characters(Vn, M_lam)

    # RHS: sum of shifted Verma modules
    summands = [sl2_verma_character(lam + n - 2 * j, depth=depth)
                for j in range(n + 1)]
    rhs = sum_characters(*summands)

    return lhs, rhs


def verify_baxter_tq_higher_spin(n: int, lam: int,
                                  depth: int = 50) -> bool:
    """Verify the higher-spin TQ relation."""
    lhs, rhs = baxter_tq_higher_spin(n, lam, depth=depth)
    return formal_character_equal(lhs, rhs)


# ---------------------------------------------------------------------------
# Short exact sequence: 0 -> M(lam-1) -> V_1 tensor M(lam) -> M(lam+1) -> 0
# ---------------------------------------------------------------------------

def ses_dimension_check(lam: int, depth: int = 50) -> Dict[int, Tuple[int, int, int]]:
    """Verify the short exact sequence at the level of weight-space dimensions.

    For each weight mu, we check:
        dim (V_1 tensor M(lam))_mu = dim M(lam+1)_mu + dim M(lam-1)_mu

    This is equivalent to the K_0 identity but presented weight-by-weight.

    Returns:
        dict: weight -> (dim_tensor, dim_M_plus, dim_M_minus)
    """
    V1 = eval_module_V1()
    M_lam = sl2_verma_character(lam, depth=depth)
    M_plus = sl2_verma_character(lam + 1, depth=depth)
    M_minus = sl2_verma_character(lam - 1, depth=depth)

    tensor = tensor_product_characters(V1, M_lam)

    all_weights = sorted(set(tensor.keys()) | set(M_plus.keys()) | set(M_minus.keys()),
                         reverse=True)

    result = {}
    for w in all_weights:
        d_tensor = tensor.get(w, 0)
        d_plus = M_plus.get(w, 0)
        d_minus = M_minus.get(w, 0)
        result[w] = (d_tensor, d_plus, d_minus)

    return result


def verify_ses_dimensions(lam: int, depth: int = 50) -> bool:
    """Verify that the SES holds at the level of dimensions for every weight."""
    data = ses_dimension_check(lam, depth=depth)
    return all(d_t == d_p + d_m for d_t, d_p, d_m in data.values())


# ---------------------------------------------------------------------------
# Explicit highest-weight vector construction
# ---------------------------------------------------------------------------

def hw_vector_in_tensor(lam: int) -> Dict[str, Rational]:
    """Construct the highest weight vector of M(lam+1) inside V_1 tensor M(lam).

    The tensor product V_1 tensor M(lam) has a unique (up to scalar)
    vector of weight lam+1 in the top weight space. This is:

        v_{hw} = e_+ tensor v_lam

    where e_+ is the weight-1 basis vector of V_1 and v_lam is the
    highest weight vector of M(lam).

    The key point is that this vector is a highest-weight vector for sl_2:
        e . v_{hw} = (e . e_+) tensor v_lam + e_+ tensor (e . v_lam) = 0

    because e . e_+ = 0 (e_+ is the highest weight vector of V_1)
    and e . v_lam = 0 (v_lam is the highest weight vector of M(lam)).

    Returns:
        dict describing the vector in the natural basis.
    """
    return {
        "description": "e_+ tensor v_lam",
        "weight": lam + 1,
        "e_action": Rational(0),  # e annihilates this vector
        "is_hw": True,
    }


def submodule_quotient_structure(lam: int) -> Dict[str, object]:
    """Describe the structure of V_1 tensor M(lam) as an sl_2-module.

    For generic lambda:
    - Top weight: lam+1 (multiplicity 1) — generates M(lam+1) subquotient
    - Weight lam-1 appears with multiplicity 2:
      one copy from f . (e_+ tensor v_lam) and one from e_- tensor v_lam

    The short exact sequence is:
        0 -> M(lam-1) -> V_1 tensor M(lam) -> M(lam+1) -> 0

    For lambda >= 0 (dominant), this is a non-split short exact sequence.
    For lambda < 0, the structure may differ (but the K_0 identity still holds).

    Returns:
        dict with structural information.
    """
    # Weight lam+1: only e_+ tensor v_lam — generates the quotient M(lam+1)
    # Weight lam-1: two vectors:
    #   (i) f . (e_+ tensor v_lam) = (f.e_+) tensor v_lam + e_+ tensor (f.v_lam)
    #                                = e_- tensor v_lam + e_+ tensor f.v_lam
    #   (ii) e_- tensor v_lam (pure tensor)
    # The quotient M(lam+1) accounts for one combination;
    # the other generates the submodule M(lam-1).

    # For the submodule: the vector that generates M(lam-1) is the
    # "singular vector" — the weight-(lam-1) vector annihilated by e
    # that is NOT in the submodule generated by the hw vector.

    # Explicitly: in the 2-dim space at weight lam-1,
    # e_- tensor v_lam has weight lam-1, and
    # e_+ tensor (f.v_lam) has weight lam-1.
    # The e-action on these:
    #   e . (e_- tensor v_lam) = h.e_- tensor v_lam / ... = e_+ tensor v_lam (proportional to hw)
    #   Wait: more carefully, Delta(e) = e tensor 1 + 1 tensor e.
    #   e . (e_- tensor v_lam) = (e.e_-) tensor v_lam + e_- tensor (e.v_lam)
    #                          = h tensor v_lam + 0
    #   This is NOT zero (it's in a different weight space entirely).
    #
    # So the singular vector construction is more subtle. Let's be precise.
    #
    # At weight lam-1, the two basis vectors are:
    #   u1 = e_+ tensor f.v_lam   (weight (1) + (lam-2) = lam-1)
    #   u2 = e_- tensor v_lam     (weight (-1) + (lam) = lam-1)
    #
    # e acts as Delta(e) = e tensor 1 + 1 tensor e:
    #   e.u1 = (e.e_+) tensor f.v_lam + e_+ tensor (e.f.v_lam)
    #        = 0 + e_+ tensor h.v_lam
    #        = lam * (e_+ tensor v_lam)
    #   e.u2 = (e.e_-) tensor v_lam + e_- tensor (e.v_lam)
    #        = h tensor v_lam + 0
    #        Hmm, but h tensor v_lam is NOT in the weight-(lam+1) space.
    #        Actually h = e_+ is wrong. Let me be precise about the V_1 basis.
    #
    # V_1 basis: v_+ (weight +1), v_- (weight -1).
    # sl_2 action on V_1:
    #   e.v_- = v_+, e.v_+ = 0
    #   f.v_+ = v_-, f.v_- = 0
    #   h.v_+ = v_+, h.v_- = -v_-
    #
    # So:
    #   e.u1 = e.(v_+ tensor f.v_lam) = (e.v_+) tensor f.v_lam + v_+ tensor (e.f.v_lam)
    #        = 0 + v_+ tensor [e,f].v_lam = v_+ tensor h.v_lam = lam * (v_+ tensor v_lam)
    #
    #   e.u2 = e.(v_- tensor v_lam) = (e.v_-) tensor v_lam + v_- tensor (e.v_lam)
    #        = v_+ tensor v_lam + 0 = v_+ tensor v_lam
    #
    # The singular vector (annihilated by e) at weight lam-1 is:
    #   w = lam * u2 - u1 = lam * (v_- tensor v_lam) - (v_+ tensor f.v_lam)
    # Check: e.w = lam * (v_+ tensor v_lam) - lam * (v_+ tensor v_lam) = 0. Good!

    sing_vector_coeffs = {"v_- tensor v_lam": lam, "v_+ tensor f.v_lam": -1}

    return {
        "hw_weight": lam + 1,
        "hw_vector": "v_+ tensor v_lam",
        "quotient": f"M({lam + 1})",
        "submodule": f"M({lam - 1})",
        "singular_vector_weight": lam - 1,
        "singular_vector": sing_vector_coeffs,
        "singular_vector_formula": f"{lam} * (v_- tensor v_lam) - (v_+ tensor f.v_lam)",
        "e_annihilates_singular": True,
        "ses": f"0 -> M({lam - 1}) -> V_1 tensor M({lam}) -> M({lam + 1}) -> 0",
    }


def verify_singular_vector(lam: int) -> bool:
    """Verify the singular vector is annihilated by e.

    At weight lam-1 in V_1 tensor M(lam), there are two basis vectors:
      u1 = v_+ tensor f.v_lam
      u2 = v_- tensor v_lam

    e acts as:
      e.u1 = lam * (v_+ tensor v_lam)
      e.u2 = 1 * (v_+ tensor v_lam)

    The singular vector w = lam * u2 - u1 satisfies e.w = 0.
    """
    # e.w = lam * e.u2 - e.u1 = lam * 1 - lam = 0
    e_on_u1_coeff = lam   # coefficient of (v_+ tensor v_lam) in e.u1
    e_on_u2_coeff = 1     # coefficient of (v_+ tensor v_lam) in e.u2

    # w = lam * u2 - u1, so e.w = lam * e_on_u2_coeff - e_on_u1_coeff
    result = lam * e_on_u2_coeff - e_on_u1_coeff
    return result == 0


# ---------------------------------------------------------------------------
# Yang R-matrix for V_1 tensor V_1
# ---------------------------------------------------------------------------

def yang_r_matrix(u: complex) -> np.ndarray:
    """The Yang R-matrix R(u) for V_1 tensor V_1.

    R(u) = u*I + hbar*P  (with hbar = 1)

    where P is the permutation operator on C^2 tensor C^2.
    In the basis {e_1 tensor e_1, e_1 tensor e_2, e_2 tensor e_1, e_2 tensor e_2}:

    P = [[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]

    So R(u) = [[u+1,0,0,0],[0,u,1,0],[0,1,u,0],[0,0,0,u+1]]

    This satisfies the Yang-Baxter equation:
        R_{12}(u-v) R_{13}(u) R_{23}(v) = R_{23}(v) R_{13}(u) R_{12}(u-v)

    Returns:
        4x4 numpy array.
    """
    P = np.array([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ], dtype=complex)
    I4 = np.eye(4, dtype=complex)
    return u * I4 + P


def yang_r_matrix_normalized(u: complex) -> np.ndarray:
    """Normalized R-matrix: R(u)/u = I + P/u.

    This form is used in the RTT presentation.
    """
    if abs(u) < 1e-15:
        raise ValueError("R-matrix has a pole at u=0")
    return yang_r_matrix(u) / u


def verify_yang_baxter(u: complex, v: complex) -> float:
    """Verify the Yang-Baxter equation R12(u-v) R13(u) R23(v) = R23(v) R13(u) R12(u-v).

    Works on V^{tensor 3} = C^2 tensor C^2 tensor C^2 (8-dimensional).

    Returns the Frobenius norm of the difference (should be 0).
    """
    # Embed R-matrices into 8x8 space
    I2 = np.eye(2, dtype=complex)

    def R12(w):
        """R acting on factors 1,2 tensored with identity on factor 3."""
        return np.kron(yang_r_matrix(w), I2)

    def R23(w):
        """R acting on factors 2,3 tensored with identity on factor 1."""
        return np.kron(I2, yang_r_matrix(w))

    def R13(w):
        """R acting on factors 1,3 with identity on factor 2.
        Need to permute indices."""
        R = yang_r_matrix(w)
        # R13 in basis (i,j,k) acts on (i,k) and leaves j alone.
        # R13_{(i,j,k),(i',j',k')} = R_{(i,k),(i',k')} * delta_{j,j'}
        R13 = np.zeros((8, 8), dtype=complex)
        for i in range(2):
            for j in range(2):
                for k in range(2):
                    for ip in range(2):
                        for kp in range(2):
                            # Index in 8-dim space: 4*i + 2*j + k
                            row = 4 * i + 2 * j + k
                            col = 4 * ip + 2 * j + kp
                            R13[row, col] += R[2 * i + k, 2 * ip + kp]
        return R13

    lhs = R12(u - v) @ R13(u) @ R23(v)
    rhs = R23(v) @ R13(u) @ R12(u - v)

    return np.linalg.norm(lhs - rhs)


def r_matrix_decomposition(u: complex) -> Dict[str, np.ndarray]:
    """Decompose R(u) into symmetric and antisymmetric projectors.

    V_1 tensor V_1 = Sym^2(V_1) + Lambda^2(V_1)
                   = V_2 + V_0 (3-dim + 1-dim)

    P_sym = (I + P)/2 projects onto the symmetric part (V_2)
    P_asym = (I - P)/2 projects onto the antisymmetric part (V_0)

    R(u) = (u + 1) * P_sym + (u - 1) * P_asym

    Eigenvalues: u+1 (on Sym^2) and u-1 (on Lambda^2).
    """
    P = np.array([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ], dtype=complex)
    I4 = np.eye(4, dtype=complex)

    P_sym = (I4 + P) / 2
    P_asym = (I4 - P) / 2

    return {
        "P_sym": P_sym,
        "P_asym": P_asym,
        "R_on_sym": complex(u + 1),   # scalar on 3-dim symmetric subspace
        "R_on_asym": complex(u - 1),  # scalar on 1-dim antisymmetric subspace
        "eigenvalues": {"symmetric": u + 1, "antisymmetric": u - 1},
    }


def verify_r_matrix_clebsch_gordan() -> bool:
    """Verify V_1 tensor V_1 = V_2 + V_0 via the R-matrix at u=0.

    At u=0: R(0) = P (the permutation).
    P has eigenvalue +1 on Sym^2 (dim 3 = dim V_2) and -1 on Lambda^2 (dim 1 = dim V_0).

    This matches the Clebsch-Gordan decomposition:
        V_1 tensor V_1 = V_2 + V_0  (dimensions: 3 + 1 = 4)
    """
    R0 = yang_r_matrix(0)
    eigenvalues = np.linalg.eigvalsh(R0.real)
    eigenvalues_sorted = sorted(eigenvalues)

    # Should have eigenvalues: -1 (once) and +1 (three times)
    expected = [-1.0, 1.0, 1.0, 1.0]
    return np.allclose(eigenvalues_sorted, expected, atol=1e-10)


# ---------------------------------------------------------------------------
# Transfer matrix and TQ functional equation
# ---------------------------------------------------------------------------

def transfer_matrix_eigenvalue(u: complex, lam: int,
                               eval_point: complex = 0.0) -> complex:
    """Eigenvalue of the transfer matrix T(u) on M(lam).

    For the Y(sl_2) transfer matrix T(u) = tr_{V_1} R(u-a) acting on
    an evaluation module or weight space:

    T(u) eigenvalue on weight mu state of M(lam) is:
        t(u) = (u - a + 1) * (weight of symmetric channel)
             + (u - a - 1) * (weight of antisymmetric channel)

    For a highest-weight state of M(lam), the transfer matrix acts as:
        T(u)|lam> = (u + lam/2 + 1)/(u) + (u - lam/2)/(u) ... (schematic)

    More precisely, for the evaluation module V_lam(a), the transfer
    matrix eigenvalue on the weight-mu subspace is a polynomial in u
    determined by the Drinfeld polynomial.

    For the fundamental case (V_1 auxiliary space), on the hw vector
    of a Verma module M(lam) at evaluation point a:

        T(u) |v_lam> = tr_{C^2} R_{aux, phys}(u - a) |v_lam>

    The R-matrix for aux=V_1, phys=V_lam is more complex.
    For the simplest case (Verma = evaluation V_lam(a)):

        T(u) eigenvalue = (u - a + (lam+1)/2) * prod_j (...) / (u - a)^N

    We implement the simpler formula for evaluation modules.
    For V_1(a) as the physical space:

        t(u, a) = (u - a + 1) + (u - a - 1) = 2(u - a)
    Wait, this is the trace of R(u-a) restricted to V_1.

    Actually: T(u) = tr_{aux=V_1} [R_{aux,phys}(u-b)] where phys = module at point b.

    For phys = V_1(b): tr of R(u-b) on C^2 tensor C^2 (partial trace over first factor):
        T(u-b) = (u-b)*I_2 + P summed over auxiliary index
    The partial trace over the auxiliary C^2 is:
        T_{kl} = sum_i R_{ik,il}(u-b) = (u-b)*delta_{kl} + delta_{kl} = (u-b+1)*delta_{kl}
    Wait that's not right. Let me compute more carefully.

    R(w) = w*I_{4} + P, so R_{(ij),(kl)}(w) = w*delta_{ik}*delta_{jl} + delta_{il}*delta_{jk}.
    Partial trace over first index: T_{jl}(w) = sum_i R_{(ij),(il)}(w)
        = sum_i [w*delta_{ii}*delta_{jl} + delta_{il}*delta_{ji}]
        = 2w*delta_{jl} + delta_{jl}
        = (2w + 1)*delta_{jl}

    So T(u-b) = (2(u-b) + 1) * I_2.
    This is a scalar operator on the physical space. Its eigenvalue is 2(u-b)+1.
    """
    w = u - eval_point
    # Partial trace of R(w) = w*I + P over the 2-dim auxiliary space
    # gives (2w + 1)*I on the physical 2-dim space.
    return 2 * w + 1


def tq_functional_equation(u: complex, Q_func, a: complex = 0.0) -> complex:
    """The TQ functional equation: T(u)*Q(u) = Q(u+1) + Q(u-1).

    Args:
        u: spectral parameter
        Q_func: a callable Q(u) -> complex
        a: evaluation point of the physical space

    Returns:
        residual: T(u)*Q(u) - Q(u+1) - Q(u-1), should be zero.
    """
    T_u = transfer_matrix_eigenvalue(u, 0, a)
    return T_u * Q_func(u) - Q_func(u + 1) - Q_func(u - 1)


def baxter_q_operator_eigenvalue(u: complex, lam: int) -> complex:
    """Eigenvalue of the Baxter Q-operator on the hw state of M(lam).

    For the Yangian Y(sl_2), the Baxter Q-operator eigenvalue on a
    highest weight state of weight lam is:

        Q(u) = prod_{j=1}^{...} (u - u_j)

    where u_j are the Bethe roots. For a Verma module, we use the
    formal Q-polynomial.

    For the simplest case: M(lam) at evaluation point 0 (Verma module).
    The Q-polynomial is Q(u) = u^{lam} (for the trivial Bethe state).

    More precisely, for the evaluation module V_lam(0):
    The Drinfeld polynomial is P(u) = (u)(u-1)...(u-lam+1)/(lam!) (normalized).
    But the standard convention is P_1(u) = u+1 for V_1.

    For verification purposes, we use the known formula:
    For T(u) = 2u + 1 (on V_1(0)), the TQ relation is:
        (2u+1) Q(u) = Q(u+1) + Q(u-1)
    This is a second-order difference equation with solution:
        Q(u) = alpha * r_+^u + beta * r_-^u
    where r_+, r_- are roots of (2u+1)x = x^2 + 1, i.e., at fixed u
    this doesn't make sense. The TQ relation is really about
    Q as a function of u satisfying the recurrence.

    Rewrite: Q(u+1) - (2u+1)Q(u) + Q(u-1) = 0.
    This is a 3-term recurrence in u.

    For the polynomial solution: Q(u) = u*(u-1) for lam=1 gives:
        T(u)*Q(u) = (2u+1)*u*(u-1)
        Q(u+1) = (u+1)*u
        Q(u-1) = (u-1)*(u-2)
        Q(u+1) + Q(u-1) = u^2 + u + u^2 - 3u + 2 = 2u^2 - 2u + 2
        T(u)*Q(u) = (2u+1)(u^2-u) = 2u^3 - 2u^2 + u^2 - u = 2u^3 - u^2 - u
    These are not equal. So Q(u) = u*(u-1) is wrong.

    Actually, for the CORRECT setup: the transfer matrix in the
    RTT formalism for V_1(a) as auxiliary space and a general
    representation M as physical space, the eigenvalue of T(u)
    depends on the Bethe state, not just the module.

    Let us take a simpler, well-established approach. For the
    Y(sl_2) spin chain with L sites of spin-1/2 at positions a_j,
    the transfer matrix eigenvalue on a Bethe state is:

        Lambda(u) = prod_j (u - a_j + 1/2) * prod_k (u - u_k - 1)/(u - u_k)
                  + prod_j (u - a_j - 1/2) * prod_k (u - u_k + 1)/(u - u_k)

    and the TQ relation is:
        Lambda(u) * Q(u) = phi(u+1/2) * Q(u-1) + phi(u-1/2) * Q(u+1)

    where phi(u) = prod_j (u - a_j) and Q(u) = prod_k (u - u_k).

    For a SINGLE site at a=0 with V_1(0):
        phi(u) = u
        Lambda(u) = (u + 1/2)(u - u_1 - 1)/(u - u_1) + (u - 1/2)(u - u_1 + 1)/(u - u_1)

    The vacuum state (no Bethe roots) has Q(u) = 1:
        Lambda(u) * 1 = phi(u+1/2) * 1 + phi(u-1/2) * 1
        Lambda(u) = (u + 1/2) + (u - 1/2) = 2u

    Hmm, so T(u)|vacuum> = 2u. And the TQ relation is 2u = (u+1/2) + (u-1/2) = 2u. Checks!

    Returns the Q-operator eigenvalue for the simplest cases.
    """
    # For the vacuum Bethe state (no roots): Q(u) = 1
    if lam == 0:
        return 1.0

    # For lam = 1: one Bethe root at u_1 = 0, Q(u) = u
    # Check: Lambda(u) * u = (u+1/2) * (u-1) + (u-1/2) * (u+1)
    #       = u^2 - u/2 - 1/2 + u^2 + u/2 - 1/2 = 2u^2 - 1
    # And phi(u+1/2)*Q(u-1) + phi(u-1/2)*Q(u+1)
    #   = (u+1/2)(u-1) + (u-1/2)(u+1) = u^2 - u/2 - 1/2 + u^2 + u/2 - 1/2 = 2u^2 - 1. Checks!
    if lam == 1:
        return complex(u)

    # General: Q(u) = prod_{k=1}^{lam} (u - u_k)
    # For the ground state Bethe roots of the single-site spin-lam/2:
    # u_k = (lam-1)/2 - (k-1) for k=1,...,lam (centered roots)
    # Wait, this is for the spin chain. For Verma modules, the situation is different.
    # Use the formal expression.
    roots = [(lam - 1) / 2.0 - k for k in range(lam)]
    result = 1.0
    for r in roots:
        result *= (u - r)
    return complex(result)


# ---------------------------------------------------------------------------
# Shift operator interpretation
# ---------------------------------------------------------------------------

def shift_operator_action(lam: int, depth: int = 50) -> Dict[str, FormalCharacter]:
    """Show that [V_1] acts as a shift operator on the K_0 lattice.

    In K_0(O_Y), the class [V_1] acts on the lattice of standard
    module classes {[M(n)] : n in Z} by:

        [V_1] * [M(n)] = [M(n+1)] + [M(n-1)]

    This means [V_1] is the "adjacency matrix" of the Z-lattice,
    i.e., the discrete Laplacian / Chebyshev recurrence operator.

    Formally: if we set X_n = [M(n)], then [V_1] acts as the
    operator X_n -> X_{n+1} + X_{n-1}, which is the shift
    (x + x^{-1}) in the group ring Z[Z].

    Returns dict demonstrating the shift action for several values of lam.
    """
    results = {}
    for n in range(max(0, lam - 2), lam + 3):
        V1 = eval_module_V1()
        Mn = sl2_verma_character(n, depth=depth)
        tensor = tensor_product_characters(V1, Mn)
        results[f"V1 tensor M({n})"] = tensor
        results[f"M({n+1}) + M({n-1})"] = sum_characters(
            sl2_verma_character(n + 1, depth=depth),
            sl2_verma_character(n - 1, depth=depth),
        )
    return results


def verify_shift_operator(max_lam: int = 10, depth: int = 30) -> bool:
    """Verify the shift operator property for lam = 0, 1, ..., max_lam."""
    return all(verify_baxter_tq_k0(lam, depth=depth)
               for lam in range(max_lam + 1))


# ---------------------------------------------------------------------------
# Chebyshev structure in K_0
# ---------------------------------------------------------------------------

def chebyshev_recurrence(n: int, x_char: FormalCharacter,
                         depth: int = 50) -> FormalCharacter:
    """Compute U_n(x/2) in K_0 via the Chebyshev recurrence.

    The Chebyshev polynomials of the second kind satisfy:
        U_0 = 1, U_1 = x, U_{n+1} = x * U_n - U_{n-1}

    In our context, x = [V_1] and the multiplication is tensor product.
    U_n([V_1]/2) = [V_n] (the (n+1)-dimensional evaluation module).

    We verify: [V_n] is the n-th Chebyshev polynomial of [V_1].

    Args:
        n: degree of Chebyshev polynomial.
        x_char: character to use as x (should be V_1 character).
        depth: truncation depth.
    """
    if n == 0:
        return {0: 1}  # trivial 1-dim rep
    if n == 1:
        return dict(x_char)

    U_prev = {0: 1}
    U_curr = dict(x_char)
    for _ in range(2, n + 1):
        U_next = subtract_characters(
            tensor_product_characters(x_char, U_curr),
            U_prev,
        )
        U_prev = U_curr
        U_curr = U_next
    return U_curr


def verify_chebyshev_structure(max_n: int = 6) -> bool:
    """Verify that [V_n] = U_n([V_1]) in K_0 (Chebyshev recurrence).

    This is the categorical shadow of the Clebsch-Gordan fusion rules:
        V_1 tensor V_n = V_{n+1} + V_{n-1}

    which is the same as the Chebyshev recurrence.
    """
    V1 = eval_module_V1()
    for n in range(max_n + 1):
        Vn_direct = eval_module_Vn(n)
        Vn_chebyshev = chebyshev_recurrence(n, V1)
        if not formal_character_equal(Vn_direct, Vn_chebyshev):
            return False
    return True


# ---------------------------------------------------------------------------
# Iterated TQ: building the K_0 lattice from V_1
# ---------------------------------------------------------------------------

def build_k0_lattice(max_lam: int = 5,
                     depth: int = 30) -> Dict[int, FormalCharacter]:
    """Build the K_0 lattice of standard module classes using TQ iterations.

    Starting from M(0) = trivial module and V_1, recursively build
    M(n) classes using the TQ relation:

        [M(n+1)] = [V_1] * [M(n)] - [M(n-1)]

    This is exactly the Chebyshev recurrence, confirming that the
    standard modules are Chebyshev-generated from V_1 and the trivial module.
    """
    V1 = eval_module_V1()
    lattice: Dict[int, FormalCharacter] = {}

    # Seed: M(0) is trivial, M(1) is V_1 itself... but actually M(lam) are Verma modules.
    # The TQ relation says [V_1]*[M(n)] = [M(n+1)] + [M(n-1)].
    # So [M(n+1)] = [V_1]*[M(n)] - [M(n-1)].
    # Seed: M(0) = Verma of hw 0, M(1) = Verma of hw 1.

    lattice[0] = sl2_verma_character(0, depth=depth)
    lattice[1] = sl2_verma_character(1, depth=depth)

    for n in range(1, max_lam):
        tensor = tensor_product_characters(V1, lattice[n])
        lattice[n + 1] = subtract_characters(tensor, lattice[n - 1])

    return lattice


def verify_k0_lattice(max_lam: int = 5, depth: int = 30) -> bool:
    """Verify that the K_0 lattice built by TQ iteration matches
    direct Verma module characters."""
    lattice = build_k0_lattice(max_lam, depth=depth)
    for n in range(max_lam + 1):
        direct = sl2_verma_character(n, depth=depth)
        if not formal_character_equal(lattice[n], direct):
            return False
    return True


# ---------------------------------------------------------------------------
# Verification suite
# ---------------------------------------------------------------------------

def verify_all() -> Dict[str, bool]:
    """Run all verification checks."""
    results = {}

    # K_0 TQ identity for various lambda
    for lam in range(8):
        results[f"TQ K_0 identity lam={lam}"] = verify_baxter_tq_k0(lam)

    # Higher-spin TQ
    for n in range(1, 5):
        for lam in [0, 1, 3]:
            results[f"Higher-spin TQ n={n} lam={lam}"] = \
                verify_baxter_tq_higher_spin(n, lam)

    # SES dimensions
    for lam in [0, 1, 2, 5]:
        results[f"SES dimensions lam={lam}"] = verify_ses_dimensions(lam)

    # Singular vector
    for lam in [1, 2, 3, 5, 10]:
        results[f"Singular vector lam={lam}"] = verify_singular_vector(lam)

    # R-matrix
    results["R-matrix CG decomposition"] = verify_r_matrix_clebsch_gordan()

    # Yang-Baxter
    for u, v in [(1.0, 2.0), (0.5, -1.3), (3.7, 0.1)]:
        err = verify_yang_baxter(u, v)
        results[f"Yang-Baxter u={u} v={v}"] = err < 1e-10

    # Shift operator
    results["Shift operator (lam=0..10)"] = verify_shift_operator(10)

    # Chebyshev structure
    results["Chebyshev V_n = U_n(V_1)"] = verify_chebyshev_structure(6)

    # K_0 lattice
    results["K_0 lattice built by TQ iteration"] = verify_k0_lattice(5)

    return results


if __name__ == "__main__":
    print("=" * 70)
    print("SL_2 BAXTER TQ RELATION: PILOT COMPUTATION FOR MC3")
    print("=" * 70)

    results = verify_all()
    n_pass = sum(1 for v in results.values() if v)
    n_fail = sum(1 for v in results.values() if not v)

    for name, ok in results.items():
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {name}")

    print(f"\n{n_pass} passed, {n_fail} failed out of {len(results)} checks.")
