r"""Spectral curve engine for the quadratic shadow curve.

The shadow obstruction tower generates rational functions S_r(c) at arity r.
On a stationary rank-one primary line, the MC equation gives a Riccati
diagnostic for the weighted generating function
H(t) = t^2 sqrt(Q_L(t)).

The shadow spectral curve is the double cover defined by
    y^2 = Q_L(t) = q_0 + q_1 t + q_2 t^2
where Q_L is the shadow metric.  This finite curve records the stationary
Riccati data on the chosen primary line.  It is not, by itself, the full KdV,
Eynard-Orantin, Seiberg-Witten, JT, or Weil-Petersson spectral curve; those
require separately supplied Lax/recursion/sewing/descendant data.

This module implements:

1. **Shadow ODE to algebraic curve** (Section 1): Riccati structure and
   extraction of the shadow curve y^2 = Q(t) from primary-line data.

2. **Branch points** (Section 2): Zeros of Q_L(t) as functions of c,
   transition between complex conjugate and real branch points at
   the critical central charge c* ~ 6.125.

3. **Monodromy** (Section 3): Numerical path integration around branch
   points, verifying the square-root sign monodromy -1.

4. **Period integrals** (Section 4): elementary contour integrals of dt/y
   on the genus-zero shadow curve; no elliptic period lattice is asserted.

5. **Auxiliary theta functions** (Section 5): standard theta functions on
   an externally supplied lattice; the rank-one shadow curve itself has
   trivial Jacobian.

6. **Multi-channel generalization** (Section 6): W_3 two-channel
   spectral curve from the bivariate shadow metric.

7. **External integrable-system comparisons** (Section 7): finite
   genus/radius diagnostics against separately supplied Toda or KdV data.
   The engine does not construct a full dg-shifted Yangian, KdV hierarchy,
   or EO recursion from Q_L alone.

References:
    thm:riccati-algebraicity (higher_genus_modular_koszul.tex)
    thm:shadow-connection (higher_genus_modular_koszul.tex)
    def:shadow-metric (higher_genus_modular_koszul.tex)
    thm:single-line-dichotomy (higher_genus_modular_koszul.tex)
    thm:shadow-radius (higher_genus_modular_koszul.tex)
    shadow_radius.py -- shadow growth rate
    shadow_tower_ode.py -- shadow obstruction tower ODE recursion
    shadow_hamilton_jacobi.py -- 2D Hamilton-Jacobi structure
"""

from __future__ import annotations

import cmath
import math
from functools import lru_cache
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

from sympy import (
    Abs, I, Poly, Rational, S, Symbol,
    cancel, conjugate, cos, diff, expand, factor,
    im, log, numer, denom, oo, pi, re, simplify,
    sin, solve, sqrt, symbols,
)


c_sym = Symbol('c')
t_sym = Symbol('t')
y_sym = Symbol('y')


def shadow_curve_scope() -> dict:
    """Scope firewall for the quadratic shadow curve.

    The curve y^2 = Q_L(t) is a finite stationary Riccati diagnostic.  It
    determines the Taylor coefficients generated by sqrt(Q_L) on the chosen
    primary line, but it does not determine descendant, EO, KdV, SW, JT/WP, or
    isomonodromic structures without additional data.
    """
    return {
        'shadow_spectral_curve': (
            'y^2 = Q_L(t), the quadratic shadow metric curve on a specified '
            'stationary primary line'
        ),
        'stationary_riccati_diagnostic': (
            'H(t)^2 = t^4 Q_L(t), with coefficients recovered from the '
            'chosen branch of sqrt(Q_L)'
        ),
        'external_eo_recursion_data': (
            'Requires x, y, Bergman kernel, local involutions, and recursion '
            'contours; Q_L supplies at most the y^2 part of a shadow input.'
        ),
        'wp_jt_sine_curve_data': (
            'Weil-Petersson and JT use the sine/Airy recursion package, not '
            'the quadratic shadow curve by default.'
        ),
        'kdv_spectral_data': (
            'Requires a KdV Lax or Schrodinger operator and descendant times; '
            'Q_L records only the primary-line shadow diagnostic.'
        ),
        'descendant_or_isomonodromic_structure': (
            'Requires separately supplied descendant pairings, Stokes data, '
            'or an isomonodromic deformation problem.'
        ),
    }


# =========================================================================
# Section 1: Shadow ODE to algebraic curve
# =========================================================================

def shadow_metric_from_data(kappa, alpha, S4):
    """Construct the shadow metric Q_L(t) = q0 + q1*t + q2*t^2.

    The shadow metric is the quadratic polynomial whose square root
    gives the weighted generating function:
        H(t)^2 = t^4 * Q_L(t).

    Parameters
    ----------
    kappa : sympy expr
        Curvature kappa = S_2 (arity-2 shadow).
    alpha : sympy expr
        Cubic shadow alpha = S_3.
    S4 : sympy expr
        Quartic shadow S_4.

    Returns
    -------
    dict with keys 'q0', 'q1', 'q2', 'Q', 'discriminant', 'Delta'.
    """
    a0 = 2 * kappa
    a1 = 3 * alpha
    a2 = 4 * S4

    q0 = a0**2                     # 4 kappa^2
    q1 = 2 * a0 * a1               # 12 kappa alpha
    q2 = a1**2 + 2 * a0 * a2       # 9 alpha^2 + 16 kappa S4

    Delta = 8 * kappa * S4          # critical discriminant
    disc_Q = q1**2 - 4 * q0 * q2   # disc of Q as poly in t; = -32 kappa^2 Delta

    t = t_sym
    Q = q0 + q1 * t + q2 * t**2

    return {
        'q0': simplify(q0),
        'q1': simplify(q1),
        'q2': simplify(q2),
        'Q': expand(Q),
        'discriminant': simplify(disc_Q),
        'Delta': simplify(Delta),
    }


def virasoro_shadow_metric():
    """Shadow metric for Virasoro at central charge c.

    kappa = c/2, alpha = 2, S4 = 10/(c(5c+22)).
    Q_Vir(t) = c^2 + 12c t + alpha_Vir t^2
    with alpha_Vir = (180c+872)/(5c+22).

    Returns shadow_metric_from_data output.
    """
    c = c_sym
    kappa = c / 2
    alpha = Rational(2)
    S4 = Rational(10) / (c * (5 * c + 22))
    return shadow_metric_from_data(kappa, alpha, S4)


def affine_shadow_metric(level_sym=None):
    """Shadow metric for affine sl_2 at level k.

    The local census normalization is
        kappa = dim(g)*(k+h^vee)/(2h^vee) = 3*(k+2)/4
    for sl_2, with h^vee=2 and dim(sl_2)=3.  The affine cubic shadow in
    the class-L normalization is S_3 = 4/(k+2), and S_4 = 0.

    The raw collision kernel is k*Omega_tr/z, while the KZ connection uses
    Omega/((k+h^vee)z) after rescaling.  Those kernel conventions are not
    interchangeable with the scalar shadow kappa.
    """
    if level_sym is None:
        level_sym = Symbol('k')
    k = level_sym
    kappa = 3 * (k + 2) / 4
    alpha = 4 / (k + 2)
    S4 = Rational(0)  # class L: terminates at arity 3
    return shadow_metric_from_data(kappa, alpha, S4)


def spectral_curve_equation(metric_data: dict) -> dict:
    """Extract the shadow curve y^2 = Q(t) from shadow metric data.

    For single-channel shadow data this is a degree-2 genus-zero double
    cover.  It is a finite shadow curve, not a full KdV/EO/SW/JT/WP spectral
    curve without external structure.

    Returns dict with 'equation' (sympy), 'genus', 'degree'.
    """
    Q = metric_data['Q']
    t = t_sym
    y = y_sym

    equation = y**2 - Q

    # Genus of y^2 = degree-2 polynomial is 0 (rational curve)
    return {
        'equation': equation,
        'genus': 0,
        'degree': 2,
        'Q': Q,
        'description': 'Shadow curve y^2 = Q(t), genus 0 (rational).',
        'scope': shadow_curve_scope(),
    }


def riccati_from_shadow_tower(kappa, alpha, S4):
    """Extract the Riccati ODE for the stationary primary-line shadow data.

    The weighted GF H(t) = sum r S_r t^r satisfies H^2 = t^4 Q_L(t).
    Define u(t) = H(t)/t^2 = sqrt(Q_L(t)).  Then:

        u' = Q_L'(t) / (2 sqrt(Q_L(t))) = Q_L'(t) / (2 u)

    i.e., 2 u u' = Q_L'(t), or (u^2)' = Q_L'(t), which integrates to
    u^2 = Q_L(t) + const.  Since u(0) = sqrt(q0) = 2|kappa| and
    Q_L(0) = q0 = 4 kappa^2, the constant is 0.

    For the ORIGINAL generating function G(t) = sum S_r t^r, we have
    G'(t) = H(t)/t = t sqrt(Q_L(t)), leading to:
        (G'/t)^2 = Q_L(t)

    This is a RICCATI equation when written in the form:
        G'' = [some rational expression in G', t].

    Returns the Riccati coefficients and the ODE data.
    """
    t = t_sym
    metric = shadow_metric_from_data(kappa, alpha, S4)
    q0 = metric['q0']
    q1 = metric['q1']
    q2 = metric['q2']

    # The Riccati ODE: set v = G'/t, then v^2 = Q(t) = q0 + q1*t + q2*t^2
    # Differentiating: 2v v' = q1 + 2 q2 t
    # So v' = (q1 + 2 q2 t) / (2v)
    # This is equivalent to: v'^2 = (q1 + 2 q2 t)^2 / (4(q0 + q1 t + q2 t^2))

    return {
        'v_equation': 'v^2 = q0 + q1*t + q2*t^2',
        'v_ode': "v' = (q1 + 2*q2*t) / (2*v)",
        'q0': q0,
        'q1': q1,
        'q2': q2,
        'metric': metric,
        'scope': shadow_curve_scope(),
    }


# =========================================================================
# Section 2: Branch points
# =========================================================================

def branch_points_symbolic(kappa, alpha, S4):
    """Compute the branch points of the shadow curve y^2 = Q(t).

    These are the zeros of Q_L(t) = q0 + q1*t + q2*t^2.

    Returns (t_plus, t_minus) as sympy expressions.
    """
    metric = shadow_metric_from_data(kappa, alpha, S4)
    q0, q1, q2 = metric['q0'], metric['q1'], metric['q2']

    disc = q1**2 - 4 * q0 * q2
    sq = sqrt(disc)
    t_plus = (-q1 + sq) / (2 * q2)
    t_minus = (-q1 - sq) / (2 * q2)

    return simplify(t_plus), simplify(t_minus)


def virasoro_branch_points():
    """Branch points of the Virasoro shadow curve as functions of c.

    Q_Vir(t) = c^2 + 12c t + alpha_Vir t^2 with alpha_Vir = (180c+872)/(5c+22).
    disc(Q_Vir) = (12c)^2 - 4 c^2 alpha_Vir
                = c^2 (144 - 4 alpha_Vir)
                = -320 c^2 / (5c+22).

    For c > 0: disc < 0, so branch points are complex conjugate.

    Returns dict with symbolic branch points and their properties.
    """
    c = c_sym
    kappa = c / 2
    alpha = Rational(2)
    S4 = Rational(10) / (c * (5 * c + 22))

    t_plus, t_minus = branch_points_symbolic(kappa, alpha, S4)

    # Branch point modulus squared = |t_+|^2 = |t_-|^2
    # |t|^2 = q0/q2 = 4 kappa^2 / q2 = c^2 / ((180c+872)/(5c+22))
    #       = c^2 (5c+22) / (180c+872)
    q2 = (180 * c + 872) / (5 * c + 22)
    modulus_sq = cancel(c**2 / q2)

    # Shadow growth rate rho = 1/|t_0| = sqrt(q2)/|c| = sqrt(q2/c^2)
    rho_sq = cancel(q2 / c**2)

    return {
        't_plus': t_plus,
        't_minus': t_minus,
        'modulus_squared': modulus_sq,
        'rho_squared': rho_sq,
        'complex_conjugate': True,  # for c > 0
        'disc_sign': 'negative (complex conjugate pair for c > 0)',
    }


def branch_points_numerical(c_val: float = None, kappa_val: float = None,
                             alpha_val: float = None, S4_val: float = None):
    """Numerical branch points for given parameter values.

    If only c_val is given, uses Virasoro data.
    Handles c_val = 0 and other degenerate cases gracefully.
    """
    if kappa_val is None:
        if c_val is None or abs(c_val) < 1e-30:
            return {
                't_plus': 0.0, 't_minus': 0.0, 'modulus': 0.0,
                'argument': 0.0, 'rho': float('inf'), 'disc': 0.0,
                'complex_pair': False, 'degenerate': True,
            }
        denom_5c22 = 5.0 * c_val + 22.0
        if abs(denom_5c22) < 1e-30:
            return {
                't_plus': 0.0, 't_minus': 0.0, 'modulus': 0.0,
                'argument': 0.0, 'rho': float('inf'), 'disc': 0.0,
                'complex_pair': False, 'degenerate': True,
            }
        kappa_val = c_val / 2.0
        alpha_val = 2.0
        S4_val = 10.0 / (c_val * denom_5c22)

    q0 = 4.0 * kappa_val**2
    q1 = 12.0 * kappa_val * alpha_val
    q2 = 9.0 * alpha_val**2 + 16.0 * kappa_val * S4_val

    disc = q1**2 - 4.0 * q0 * q2

    if disc >= 0:
        sq = math.sqrt(disc)
        t_plus = (-q1 + sq) / (2.0 * q2)
        t_minus = (-q1 - sq) / (2.0 * q2)
    else:
        sq = cmath.sqrt(disc)
        t_plus = (-q1 + sq) / (2.0 * q2)
        t_minus = (-q1 - sq) / (2.0 * q2)

    return {
        't_plus': t_plus,
        't_minus': t_minus,
        'modulus': abs(t_plus),
        'argument': cmath.phase(t_plus) if isinstance(t_plus, complex) else (
            0.0 if t_plus >= 0 else math.pi),
        'rho': 1.0 / abs(t_plus) if abs(t_plus) > 0 else float('inf'),
        'disc': disc,
        'complex_pair': disc < 0,
    }


def critical_central_charge():
    """The critical central charge c* where rho(Vir) = 1.

    Solves 5c^3 + 22c^2 - 180c - 872 = 0.  The unique positive real root
    is c* ~ 6.1243.

    At c = c*: the shadow-curve branch points have modulus 1,
    and the shadow obstruction tower transitions between convergent (c > c*)
    and divergent (c < c*).
    """
    c = c_sym
    poly = 5 * c**3 + 22 * c**2 - 180 * c - 872
    roots = solve(poly, c)

    real_pos = []
    for r in roots:
        val = complex(r.evalf())
        if abs(val.imag) < 1e-10 and val.real > 0:
            real_pos.append(r)

    return {
        'polynomial': poly,
        'all_roots': roots,
        'c_star': real_pos[0] if real_pos else None,
        'c_star_numerical': float(real_pos[0].evalf()) if real_pos else None,
    }


def branch_point_regime(c_val: float) -> str:
    """Classify the branch point regime at a given central charge.

    Returns 'convergent' (c > c*), 'divergent' (c < c*), or 'critical'.
    """
    c_star = critical_central_charge()['c_star_numerical']
    if c_val > c_star + 1e-10:
        return 'convergent'
    elif c_val < c_star - 1e-10:
        return 'divergent'
    else:
        return 'critical'


# =========================================================================
# Section 3: Monodromy computation
# =========================================================================

def shadow_connection_matrix(t_val: complex, c_val: float):
    """Evaluate the shadow connection nabla^sh = d - Q'/(2Q) dt at t_val.

    The connection 1-form is omega = -Q'(t)/(2Q(t)) dt.
    The flat section satisfies f'(t) = Q'(t)/(2Q(t)) f(t),
    so f(t) = sqrt(Q(t)) / sqrt(Q(0)).

    Returns the connection coefficient omega(t) = -Q'(t)/(2Q(t)).
    """
    q0 = c_val**2
    q1 = 12.0 * c_val
    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)
    q2 = alpha_c

    Q_val = q0 + q1 * t_val + q2 * t_val**2
    Q_prime = q1 + 2.0 * q2 * t_val

    if abs(Q_val) < 1e-30:
        return complex('inf')

    return -Q_prime / (2.0 * Q_val)


def monodromy_numerical(c_val: float, n_steps: int = 1000) -> dict:
    """Compute monodromy around a branch point of the Virasoro shadow curve.

    We integrate the shadow connection nabla^sh around a closed loop
    encircling one branch point.  The expected monodromy is the square-root
    sign -1.

    Method: parametrize a circular path around t_+ (one branch point),
    numerically integrate the connection 1-form, and compute the
    holonomy exp(oint omega).

    Returns dict with monodromy value, expected -1.
    """
    bp = branch_points_numerical(c_val)
    t_bp = bp['t_plus']

    # Small loop radius: fraction of the distance to the other branch point
    if bp['complex_pair']:
        # Branch points are complex conjugates; circle around one
        loop_radius = abs(t_bp - bp['t_minus']) * 0.1
    else:
        loop_radius = abs(t_bp) * 0.1

    if loop_radius < 1e-15:
        return {'monodromy': None, 'error': 'degenerate branch points'}

    # Parametrize the loop: gamma(s) = t_bp + loop_radius * exp(2*pi*i*s), s in [0,1]
    integral = 0.0 + 0.0j
    ds = 1.0 / n_steps

    for j in range(n_steps):
        s = (j + 0.5) * ds  # midpoint rule
        gamma = t_bp + loop_radius * cmath.exp(2.0j * cmath.pi * s)
        gamma_prime = loop_radius * 2.0j * cmath.pi * cmath.exp(2.0j * cmath.pi * s)

        # Connection coefficient at gamma(s)
        omega = shadow_connection_matrix(gamma, c_val)

        if omega == complex('inf'):
            return {'monodromy': None, 'error': 'hit singularity'}

        integral += omega * gamma_prime * ds

    holonomy = cmath.exp(integral)

    return {
        'monodromy': holonomy,
        'monodromy_real': holonomy.real,
        'monodromy_imag': holonomy.imag,
        'expected': -1.0,
        'error_from_expected': abs(holonomy - (-1.0)),
        'log_holonomy': integral,
        'branch_point': t_bp,
        'loop_radius': loop_radius,
        'n_steps': n_steps,
    }


def verify_koszul_monodromy(c_val: float, tol: float = 1e-4,
                              n_steps: int = 2000) -> bool:
    """Verify that monodromy around each branch point is the sign -1.

    The shadow connection nabla^sh = d - Q'/(2Q) dt has logarithmic
    singularities at zeros of Q.  Around each zero, the flat section
    sqrt(Q(t)) picks up a factor of -1 (square root monodromy).

    This is compatible with the bar desuspension sign.  It is not a
    curve-level construction of the Verdier dual algebra A^!.
    """
    result = monodromy_numerical(c_val, n_steps=n_steps)
    if result['monodromy'] is None:
        return False
    return result['error_from_expected'] < tol


# =========================================================================
# Section 4: Period integrals
# =========================================================================

def period_A_cycle(c_val: float, n_steps: int = 2000) -> complex:
    """Compute the branch-cut integral of dt/y on the Virasoro shadow curve.

    The shadow curve is y^2 = Q(t) = c^2 + 12c*t + alpha*t^2.
    The holomorphic differential is omega = dt/y = dt/sqrt(Q(t)).

    The A-cycle encircles both branch points.  For a quadratic Q(t)
    with roots t_+, t_-, this is the standard elliptic integral
    (which is elementary for genus 0):

        omega_1 = integral_{t_-}^{t_+} dt / sqrt(Q(t))

    For genus 0, this integral has a closed form involving arcsin or log
    depending on the discriminant sign.

    For complex conjugate branch points (disc < 0, generic Virasoro),
    we parametrize a path from t_- to t_+ in the complex plane and
    integrate numerically.
    """
    bp = branch_points_numerical(c_val)
    t_plus = bp['t_plus']
    t_minus = bp['t_minus']

    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)

    # For complex conjugate branch points, integrate along the
    # straight-line segment from t_- to t_+
    dt_total = t_plus - t_minus
    integral = 0.0 + 0.0j

    for j in range(n_steps):
        s = (j + 0.5) / n_steps  # midpoint
        t_val = t_minus + s * dt_total

        Q_val = c_val**2 + 12.0 * c_val * t_val + alpha_c * t_val**2
        sq_Q = cmath.sqrt(Q_val)

        if abs(sq_Q) < 1e-30:
            continue

        integral += (dt_total / n_steps) / sq_Q

    return integral


def period_B_cycle(c_val: float, n_steps: int = 2000) -> complex:
    """Compute a second contour integral of dt/y on the genus-zero shadow curve.

    The genus-zero curve has no independent B-cycle or Jacobian period
    lattice.  This routine integrates around a loop encircling the branch
    cut as a diagnostic contour only.
    """
    bp = branch_points_numerical(c_val)
    t_plus = bp['t_plus']
    t_minus = bp['t_minus']

    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)

    # Center and semi-axes of the ellipse encircling the branch cut
    center = (t_plus + t_minus) / 2.0
    semi_major = abs(t_plus - t_minus) / 2.0 * 1.5  # slightly larger than branch cut
    semi_minor = semi_major * 0.8

    integral = 0.0 + 0.0j

    for j in range(n_steps):
        theta = 2.0 * math.pi * (j + 0.5) / n_steps
        gamma = center + semi_major * math.cos(theta) + 1.0j * semi_minor * math.sin(theta)
        gamma_prime = (-semi_major * math.sin(theta)
                       + 1.0j * semi_minor * math.cos(theta))

        Q_val = c_val**2 + 12.0 * c_val * gamma + alpha_c * gamma**2
        sq_Q = cmath.sqrt(Q_val)

        if abs(sq_Q) < 1e-30:
            continue

        d_theta = 2.0 * math.pi / n_steps
        integral += gamma_prime * d_theta / sq_Q

    return integral


def period_ratio(c_val: float, n_steps: int = 2000) -> complex:
    """Compute a formal contour ratio tau = omega_2 / omega_1.

    For an elliptic curve, tau is a period-lattice parameter.  For the
    genus-zero shadow curve, these contours are non-independent; the ratio is
    a diagnostic number, not the Jacobian modulus of the shadow curve.

    For Q(t) = q0 + q1 t + q2 t^2, the formal period ratio is:
        tau = omega_B / omega_A = i * pi / (A-period * sqrt(q2))

    We compute numerically for verification.
    """
    omega_A = period_A_cycle(c_val, n_steps)
    omega_B = period_B_cycle(c_val, n_steps)

    if abs(omega_A) < 1e-30:
        return complex('nan')

    return omega_B / omega_A


def period_closed_form(c_val: float) -> dict:
    """Closed-form contour diagnostics for the genus-zero shadow curve.

    For y^2 = q0 + q1 t + q2 t^2 with disc = q1^2 - 4 q0 q2 < 0,
    the integral int dt/sqrt(Q) from t_- to t_+ is:

        omega_A = pi / sqrt(q2)

    (This is the standard result for elliptic integrals of the first kind
    with a quadratic integrand.)

    The B-period (loop around branch cut):
        omega_B = 2*pi*i / sqrt(-disc/(4*q2))

    But for genus 0 these are not independent.
    """
    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)
    q0 = c_val**2
    q1 = 12.0 * c_val
    q2 = alpha_c

    disc = q1**2 - 4.0 * q0 * q2

    # A-period: pi / sqrt(q2)
    omega_A = cmath.pi / cmath.sqrt(q2)

    # B-period: involves the discriminant
    if disc < 0:
        # Complex conjugate case: B-period is pure imaginary multiple of A
        omega_B = 2.0j * cmath.pi / cmath.sqrt(q2)
    else:
        omega_B = 2.0 * cmath.pi / cmath.sqrt(q2)

    return {
        'omega_A': omega_A,
        'omega_B': omega_B,
        'q2': q2,
        'disc': disc,
    }


# =========================================================================
# Section 5: Jacobian and theta functions
# =========================================================================

def theta_function(z: complex, tau: complex, n_terms: int = 50) -> complex:
    """Jacobi theta function theta_3(z|tau) = sum_{n=-N}^{N} exp(pi*i*n^2*tau + 2*pi*i*n*z).

    This is the standard theta function associated to the lattice Z + tau*Z.

    Parameters
    ----------
    z : complex
        Argument on the Jacobian.
    tau : complex
        Period ratio, Im(tau) > 0.
    n_terms : int
        Truncation: sum from -n_terms to +n_terms.
    """
    if tau.imag <= 0:
        # tau should be in the upper half-plane
        return complex('nan')

    result = 0.0 + 0.0j
    for n in range(-n_terms, n_terms + 1):
        exponent = cmath.pi * 1.0j * n**2 * tau + 2.0 * cmath.pi * 1.0j * n * z
        # Prevent overflow
        if exponent.real > 500:
            continue
        result += cmath.exp(exponent)

    return result


def theta_1(z: complex, tau: complex, n_terms: int = 50) -> complex:
    """Jacobi theta_1(z|tau) = 2 sum_{n=0}^N (-1)^n q^{(n+1/2)^2} sin((2n+1)*pi*z).

    where q = exp(pi*i*tau).
    """
    if tau.imag <= 0:
        return complex('nan')

    q = cmath.exp(cmath.pi * 1.0j * tau)
    result = 0.0 + 0.0j
    for n in range(n_terms + 1):
        q_power = q**((n + 0.5)**2)
        if abs(q_power) < 1e-100:
            break
        sign = (-1)**n
        result += sign * q_power * cmath.sin((2 * n + 1) * cmath.pi * z)

    return 2.0 * result


def jacobian_torus(tau: complex) -> dict:
    """Construct an auxiliary torus C / (Z + tau*Z).

    The genus-zero shadow curve has trivial Jacobian.  This helper is only a
    standard theta/lattice utility for externally supplied genus-one data.

    Returns lattice data.
    """
    return {
        'tau': tau,
        'omega_1': 1.0 + 0.0j,
        'omega_2': tau,
        'area': abs(tau.imag),
        'j_invariant': _j_invariant(tau),
    }


def _j_invariant(tau: complex) -> complex:
    """Klein j-invariant j(tau) from the theta functions.

    j = 1728 * g_2^3 / (g_2^3 - 27 g_3^2)

    where g_2 and g_3 are the Eisenstein invariants.
    We use theta functions: g_2 = (pi^4/12)(theta_2^8 + theta_3^8 + theta_4^8)
    but for simplicity compute via the Eisenstein series.
    """
    if tau.imag <= 0:
        return complex('nan')

    q = cmath.exp(2.0j * cmath.pi * tau)

    # E_4(tau) = 1 + 240 sum_{n=1}^N n^3 q^n / (1 - q^n)
    # E_6(tau) = 1 - 504 sum_{n=1}^N n^5 q^n / (1 - q^n)
    E4 = 1.0 + 0.0j
    E6 = 1.0 + 0.0j
    for n in range(1, 100):
        qn = q**n
        if abs(qn) < 1e-100:
            break
        denom = 1.0 - qn
        if abs(denom) < 1e-100:
            continue
        E4 += 240.0 * n**3 * qn / denom
        E6 -= 504.0 * n**5 * qn / denom

    g2 = E4 * (cmath.pi**4) * (4.0 / 3.0)
    g3 = E6 * (cmath.pi**6) * (8.0 / 27.0)

    delta = g2**3 - 27.0 * g3**2
    if abs(delta) < 1e-100:
        return complex('inf')

    return 1728.0 * g2**3 / delta


def shadow_theta_identification(c_val: float, r_max: int = 10) -> dict:
    """Recover shadow coefficients by Taylor expansion, not by theta data.

    For the Virasoro spectral curve at central charge c, the shadow
    coefficients S_r(c) are generated by the algebraic function
    H(t) = t^2 sqrt(Q(t)).  On the spectral curve, H is a rational
    function (genus 0), so no intrinsic theta-function identification is
    asserted.

    For this genus-zero shadow curve, the identification is with the Taylor
    coefficients of sqrt(Q(t)) around t = 0:

        sqrt(Q(t)) = c + 6t/c * ... = sum a_n t^n

    and S_r = a_{r-2} (up to normalization).

    Returns the Taylor coefficients and the shadow data for comparison.
    """
    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)
    q0 = c_val**2
    q1 = 12.0 * c_val
    q2 = alpha_c

    # Taylor expand sqrt(Q(t)) around t=0
    # sqrt(Q) = sqrt(q0) * sqrt(1 + (q1/q0)*t + (q2/q0)*t^2)
    #         = sqrt(q0) * (1 + (1/2)(q1/q0)*t + ...)
    # Use binomial expansion
    sqrt_q0 = cmath.sqrt(q0)  # = |c| for c > 0
    u = q1 / q0  # = 12/c
    v = q2 / q0  # = alpha_c / c^2

    # sqrt(1 + u*t + v*t^2) = sum a_n t^n
    # a_0 = 1
    # Recurrence: 2(n+1) a_{n+1} = u * (2n+1) a_n - (n-1) * ... complicated
    # Easier: direct numerical differentiation
    coeffs = [0.0] * (r_max + 1)  # a_0, a_1, ..., a_{r_max}
    coeffs[0] = 1.0

    # Use the identity: if f = sqrt(1 + u*t + v*t^2), then
    # f^2 = 1 + u*t + v*t^2, so sum_{k=0}^n a_k a_{n-k} = [n=0: 1, n=1: u, n=2: v, n>=3: 0]
    for n in range(1, r_max + 1):
        # a_0 * a_n + a_1 * a_{n-1} + ... + a_n * a_0 = rhs_n
        if n == 1:
            rhs = u
        elif n == 2:
            rhs = v
        else:
            rhs = 0.0

        # sum_{k=1}^{n-1} a_k * a_{n-k} = known
        known_sum = sum(coeffs[k] * coeffs[n - k] for k in range(1, n))
        # 2 * a_0 * a_n = rhs - known_sum  (since a_0 = 1)
        coeffs[n] = (rhs - known_sum) / 2.0

    # H(t) = t^2 * sqrt(q0) * sqrt(1 + u*t + v*t^2)
    #       = sqrt(q0) * sum_{n} a_n * t^{n+2}
    # So S_r = r-th coefficient of H(t) / t^r = ... no,
    # G(t) = sum S_r t^r, and G'(t) = sum r S_r t^{r-1} = H(t)/t = t sqrt(Q)
    # => r S_r = coeff of t^{r-1} in t*sqrt(Q) = sqrt(q0) * coeff of t^{r-1} in t*(sum a_n t^n)
    # => r S_r = sqrt(q0) * a_{r-2}  for r >= 2
    # => S_r = sqrt(q0) * a_{r-2} / r

    shadow_from_curve = {}
    for r in range(2, r_max + 1):
        if r - 2 < len(coeffs):
            shadow_from_curve[r] = float(sqrt_q0.real) * coeffs[r - 2] / r

    return {
        'taylor_coefficients': coeffs,
        'shadow_from_curve': shadow_from_curve,
        'sqrt_q0': sqrt_q0,
        'u': u,
        'v': v,
    }


# =========================================================================
# Section 6: Multi-channel generalization (W_3)
# =========================================================================

def w3_spectral_surface(c_val: float) -> dict:
    """Shadow spectral surface for the W_3 primary-line data.

    W_3 has two strong generators T (weight 2) and W (weight 3).
    The shadow metric is a BIVARIATE quadratic form Q(x_T, x_W) on the
    2D deformation space.

    The spectral surface is the zero locus of:
        z^2 = Q(x_T, x_W)
    in C^3, which is a quadric surface (not a curve).

    For W_3, the quadratic form Q has the block structure:
        Q = Q_TT x_T^2 + 2 Q_TW x_T x_W + Q_WW x_W^2

    where Q_TT, Q_TW, Q_WW are the shadow metric components
    (each quadratic in t, but here evaluated at a given t).

    For a one-dimensional shadow curve of W_3, restrict to a 1D slice
    (e.g., the T-line x_W = 0 or a generic line).

    Returns the spectral surface data.
    """
    # Curvature matrix for W_3
    kappa_T = c_val / 2.0  # Virasoro curvature
    # W-line census gives Q_W(0) = (2c/3)^2, hence kappa_W = c/3.
    kappa_W = c_val / 3.0

    # Propagators
    P_T = 2.0 / c_val
    P_W = 3.0 / c_val

    # Mixing: the T-W cross terms come from the cubic OPE T x W -> W
    # and the quartic OPE T x T x W x W
    mixing = 0.0  # vanishes at leading order by weight parity

    # T-line spectral curve: restrict to x_W = 0
    # Q_TT = same as Virasoro shadow metric
    alpha_c_T = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)

    # W-line spectral curve: restrict to x_T = 0
    # Q_WW depends on the W-W-W-W quartic OPE (vanishes by conformal weight parity)
    # and the W-W curvature (S_2 in the W-direction)

    return {
        'dimension': 2,
        'curvature_matrix': [[kappa_T, mixing], [mixing, kappa_W]],
        'propagator_matrix': [[P_T, 0.0], [0.0, P_W]],
        'T_line_alpha': alpha_c_T,
        'genus_T_line': 0,
        'description': (
            'W_3 spectral surface: z^2 = Q(x_T, x_W), a quadric in C^3. '
            'The T-line restriction recovers the Virasoro spectral curve. '
            'The W-line restriction has enhanced symmetry (weight parity).'
        ),
    }


def w3_spectral_curve_T_line(c_val: float) -> dict:
    """Shadow curve on the T-line (x_W = 0) for W_3.

    This is identical to the Virasoro spectral curve, since the W-generator
    does not contribute on the T-line at leading order.
    """
    return {
        'curve': 'y^2 = Q_TT(t)',
        'genus': 0,
        'branch_points': branch_points_numerical(c_val),
        'coincides_with_virasoro': True,
    }


def w3_spectral_discriminant(c_val: float) -> dict:
    """Discriminant locus of the W_3 shadow spectral surface.

    The discriminant locus is the set of (x_T, x_W) where Q(x_T, x_W) = 0,
    i.e., where the spectral surface degenerates.

    For the W_3 quadratic form:
        det(Q_matrix) = Q_TT * Q_WW - Q_TW^2
    The discriminant is the zero set of this determinant.
    """
    # The propagator variance delta_mix (from thm:propagator-variance)
    # measures the non-autonomy of the 2D system
    # P(W_3) = 25c^2 + 100c - 428, the mixing polynomial
    P_mixing = 25.0 * c_val**2 + 100.0 * c_val - 428.0

    return {
        'mixing_polynomial': P_mixing,
        'mixing_zeros': [(-100 + math.sqrt(10000 + 4 * 25 * 428)) / 50.0,
                         (-100 - math.sqrt(10000 + 4 * 25 * 428)) / 50.0],
        'enhanced_symmetry': abs(P_mixing) < 1e-10,
        'description': (
            'W_3 mixing polynomial P(c) = 25c^2 + 100c - 428. '
            'Vanishes at c ~ 3.067 and c ~ -7.067 (enhanced symmetry points).'
        ),
    }


# =========================================================================
# Section 7: Connection to integrable systems
# =========================================================================

def toda_spectral_curve(k_val: float = 1.0) -> dict:
    """External Toda lattice reference curve for sl_2.

    The sl_2 Toda spectral curve is:
        det(L(z) - w) = 0
    where L(z) is the Lax matrix.  For sl_2:
        w^2 - (z + k/z) w + 1 = 0
    at level k.

    This is not reconstructed from the shadow metric.  It is external Lax
    data used only for finite comparison diagnostics.
    """
    # Toda Lax matrix eigenvalues: w = ((z + k/z) +/- sqrt((z-k/z)^2)) / 2
    # = z or k/z  (the curve is rational, genus 0)
    return {
        'equation': 'w^2 - (z + k/z)*w + 1 = 0',
        'genus': 0,
        'branch_points_w': [0.0],  # w-plane branch points at z^2 = k
        'branch_points_z': [cmath.sqrt(k_val), -cmath.sqrt(k_val)],
        'level': k_val,
        'status': 'external_lax_reference',
        'shadow_identification': 'not asserted from Q_L alone',
        'description': (
            f'Toda sl_2 spectral curve at level k={k_val}. '
            f'Rational (genus 0). Branch points at z = +/-sqrt(k).'
        ),
    }


def kdv_spectral_curve(c_val: float = 26.0) -> dict:
    """Shadow diagnostic compared with external KdV data.

    The engine does not construct the KdV Lax curve, descendant hierarchy,
    tau-function, or analytic convergence theory.  It reports the Virasoro
    shadow radius and the finite quantum discriminant
    Delta = 40/(5c+22).  A full KdV comparison needs external KdV spectral
    data.
    """
    # In the large-c limit, the shadow metric becomes:
    # Q(t) ~ c^2 + 12ct + 36 t^2 = (c + 6t)^2
    # which is a perfect square (no branch points, Gaussian).
    # Quantum corrections from Delta = 40/(5c+22) create the branch cut.

    rho_sq = (180.0 * c_val + 872.0) / ((5.0 * c_val + 22.0) * c_val**2)
    rho = math.sqrt(rho_sq) if rho_sq > 0 else 0.0

    Delta_val = 40.0 / (5.0 * c_val + 22.0)

    return {
        'classical_limit': '(c + 6t)^2 (perfect square, no branch points)',
        'quantum_correction': f'Delta = {Delta_val:.6f}',
        'shadow_growth_rate': rho,
        'status': 'shadow_diagnostic_only',
        'external_data_required': [
            'KdV Lax or Schrodinger operator',
            'descendant times',
            'tau-function or isomonodromic data',
        ],
        'connection': (
            'Q_Vir supplies a primary-line shadow radius and discriminant. '
            'It is not the full KdV spectral curve without external KdV data.'
        ),
    }


def yangian_spectral_identification(family: str, c_val: float = None,
                                     k_val: float = None) -> dict:
    """Compare shadow-curve diagnostics with external integrable-system data.

    For affine sl_2 at level k:
        - Shadow spectral curve: y^2 = Q_aff(t) (perfect square, genus 0)
        - Toda reference curve: external Lax curve (genus 0)
        - Genus agrees, but equality of curves is not asserted by Q_L alone.

    For Virasoro at central charge c:
        - Shadow spectral curve: y^2 = Q_Vir(t) (genus 0, complex branch pts)
        - KdV spectral data requires external Lax/descendant input.

    The binary collision residue r(z) and the quadratic shadow curve are
    projections of the MC element.  This routine checks finite invariants; it
    does not prove a full dg-shifted Yangian/KdV/Toda spectral equivalence.
    """
    if family == 'affine_sl2':
        if k_val is None:
            k_val = 1.0
        kappa = 3.0 * (k_val + 2.0) / 4.0
        alpha = 4.0 / (k_val + 2.0)
        S4 = 0.0  # class L

        shadow_bp = branch_points_numerical(
            c_val=None, kappa_val=kappa, alpha_val=alpha, S4_val=S4)
        toda = toda_spectral_curve(k_val)

        return {
            'family': 'affine_sl2',
            'level': k_val,
            'shadow_genus': 0,
            'yangian_genus': toda['genus'],
            'genus_match': True,
            'shadow_branch_points': shadow_bp,
            'yangian_branch_points': toda['branch_points_z'],
            'shadow_class': 'L (perfect square, no true branch points)',
            'identification_status': 'finite rational-genus comparison only',
            'external_data_required': ['Toda Lax matrix', 'Yangian coproduct/r-matrix data'],
            'identification': (
                'Both spectral curves are rational (genus 0). '
                'Shadow metric is a perfect square (Delta=0, class L). '
                'The Toda curve is external Lax data; genus agreement is a '
                'finite diagnostic, not a curve-level equivalence.'
            ),
        }

    elif family == 'virasoro':
        if c_val is None:
            c_val = 26.0
        shadow_bp = branch_points_numerical(c_val)
        kdv = kdv_spectral_curve(c_val)

        return {
            'family': 'virasoro',
            'c': c_val,
            'shadow_genus': 0,
            'yangian_type': 'KdV',
            'shadow_growth_rate': shadow_bp['rho'],
            'kdv_growth_rate': kdv['shadow_growth_rate'],
            'rates_match': abs(shadow_bp['rho'] - kdv['shadow_growth_rate']) < 1e-10,
            'identification_status': 'shadow radius only; full KdV data external',
            'external_data_required': kdv['external_data_required'],
            'identification': (
                'The reported rate is the Virasoro shadow radius computed '
                'from Q_Vir. A full KdV spectral curve requires external KdV '
                'hierarchy data.'
            ),
        }

    else:
        return {'family': family, 'error': f'Family {family} not yet implemented.'}


# =========================================================================
# Section 8: Unified spectral curve analysis
# =========================================================================

def full_spectral_analysis(family: str, **params) -> dict:
    """Run the finite shadow-curve analysis for a given family.

    Parameters
    ----------
    family : str
        One of 'virasoro', 'affine_sl2', 'heisenberg', 'betagamma', 'w3'.
    **params
        Family-specific parameters (c_val, k_val, etc.)

    Returns
    -------
    dict with the shadow curve diagnostics available from this engine.
    """
    result = {'family': family, 'params': params}

    if family == 'heisenberg':
        c_val = params.get('c_val', 1.0)
        kappa = c_val / 2.0
        result['class'] = 'G'
        result['depth'] = 2
        result['metric'] = {'q0': 4 * kappa**2, 'q1': 0.0, 'q2': 0.0}
        result['spectral_curve'] = 'degenerate (metric is constant)'
        result['branch_points'] = 'none (entire function)'
        result['monodromy'] = 'trivial'
        result['periods'] = 'not applicable (no branch points)'

    elif family == 'affine_sl2':
        k_val = params.get('k_val', 1.0)
        kappa = 3.0 * (k_val + 2.0) / 4.0
        alpha = 4.0 / (k_val + 2.0)
        S4 = 0.0
        q0 = 4.0 * kappa**2
        q1 = 12.0 * kappa * alpha
        q2 = 9.0 * alpha**2  # since S4=0
        disc = q1**2 - 4.0 * q0 * q2

        result['class'] = 'L'
        result['depth'] = 3
        result['kappa'] = kappa
        result['metric'] = {'q0': q0, 'q1': q1, 'q2': q2, 'disc': disc}
        result['spectral_curve'] = 'degenerate (Q is perfect square, Delta=0)'
        result['branch_points'] = 'double root (perfect square)'
        result['double_root'] = -q1 / (2.0 * q2)
        result['monodromy'] = 'trivial (no true branch points)'
        result['integrable_system'] = toda_spectral_curve(k_val)

    elif family == 'betagamma':
        c_val = params.get('c_val', 2.0)
        # Class C terminates by stratum separation.  The optional curve below
        # is only the Virasoro primary-line comparison used in the local
        # topological-recursion shadow tests.
        kappa = c_val / 2.0
        alpha = 2.0
        S4 = params.get('S4_val', 10.0 / (c_val * (5.0 * c_val + 22.0)))

        bp = branch_points_numerical(c_val, kappa, alpha, S4)
        result['class'] = 'C'
        result['depth'] = 4
        result['kappa'] = kappa
        result['branch_points'] = bp
        result['spectral_curve'] = 'primary-line shadow curve only; class-C depth is external stratum data'
        result['monodromy'] = 'not a class-C depth invariant'
        result['scope'] = shadow_curve_scope()

    elif family == 'virasoro':
        c_val = params.get('c_val', 26.0)
        bp = branch_points_numerical(c_val)
        mono = monodromy_numerical(c_val, n_steps=params.get('n_steps', 1000))
        periods = period_closed_form(c_val)
        regime = branch_point_regime(c_val)
        theta_id = shadow_theta_identification(c_val, r_max=params.get('r_max', 10))
        kdv = kdv_spectral_curve(c_val)

        result['class'] = 'M'
        result['depth'] = float('inf')
        result['kappa'] = c_val / 2.0
        result['branch_points'] = bp
        result['monodromy'] = mono
        result['periods'] = periods
        result['regime'] = regime
        result['theta_identification'] = theta_id
        result['spectral_curve'] = 'y^2 = Q_Vir(t), genus 0'
        result['integrable_system'] = kdv
        result['scope'] = shadow_curve_scope()

    elif family == 'w3':
        c_val = params.get('c_val', 50.0)
        surface = w3_spectral_surface(c_val)
        T_line = w3_spectral_curve_T_line(c_val)
        disc = w3_spectral_discriminant(c_val)

        result['class'] = 'M (multi-channel)'
        result['depth'] = float('inf')
        result['spectral_surface'] = surface
        result['T_line_curve'] = T_line
        result['discriminant'] = disc
        result['spectral_curve'] = (
            'Shadow spectral surface z^2 = Q(x_T, x_W) (quadric in C^3). '
            'T-line restriction = Virasoro spectral curve.'
        )
        result['scope'] = shadow_curve_scope()

    else:
        result['error'] = f'Unknown family: {family}'

    return result


# =========================================================================
# Section 9: Spectral curve invariants
# =========================================================================

def spectral_invariants(c_val: float) -> dict:
    """Compute finite invariants of the Virasoro shadow curve.

    Returns a dictionary of invariants that characterize the spectral
    curve up to the finite shadow diagnostics used here.
    """
    # Handle degenerate c values
    if abs(c_val) < 1e-30 or abs(5.0 * c_val + 22.0) < 1e-30:
        return {
            'c': c_val, 'rho': float('inf'), 'theta': 0.0,
            'Delta': float('inf'), 'delta_ratio': float('inf'),
            'cross_ratio': complex('nan'), 'Delta_dual': 0.0,
            'Delta_sum': float('inf'), 'kappa': c_val / 2.0,
            'alpha_c': float('inf'), 'degenerate': True,
        }

    bp = branch_points_numerical(c_val)
    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)

    # Invariant 1: shadow growth rate rho
    rho = bp['rho']

    # Invariant 2: branch point argument theta
    theta = bp['argument']

    # Invariant 3: discriminant Delta = 8*kappa*S4 = 40/(5c+22) for Virasoro
    Delta = 40.0 / (5.0 * c_val + 22.0)

    # Invariant 4: discriminant ratio Delta/kappa^2
    kappa = c_val / 2.0
    delta_ratio = Delta / kappa**2 if kappa != 0 else float('inf')

    # Invariant 5: cross-ratio of branch points with 0 and infinity
    # For two branch points t_+, t_- and the basepoint 0:
    # CR = t_+ / t_-
    if isinstance(bp['t_plus'], complex) and isinstance(bp['t_minus'], complex):
        if abs(bp['t_minus']) > 1e-30:
            cross_ratio = bp['t_plus'] / bp['t_minus']
        else:
            cross_ratio = complex('inf')
    else:
        cross_ratio = bp['t_plus'] / bp['t_minus'] if abs(bp['t_minus']) > 1e-30 else float('inf')

    # Invariant 6: complementarity discriminant on the Verdier-dual scalar lane
    c_dual = 26.0 - c_val
    if abs(c_dual) > 1e-10 and abs(5.0 * c_dual + 22.0) > 1e-10:
        Delta_dual = 40.0 / (5.0 * c_dual + 22.0)
    else:
        Delta_dual = float('inf')

    # Complementarity: Delta(A) + Delta(A!) = constant / denominator
    # (from thm:shadow-connection)
    Delta_sum = Delta + Delta_dual

    return {
        'c': c_val,
        'rho': rho,
        'theta': theta,
        'Delta': Delta,
        'delta_ratio': delta_ratio,
        'cross_ratio': cross_ratio,
        'Delta_dual': Delta_dual,
        'Delta_sum': Delta_sum,
        'kappa': kappa,
        'alpha_c': alpha_c,
    }


def complementarity_of_discriminants(c_val: float) -> dict:
    """Verify the complementarity of discriminants (from thm:shadow-connection).

    On the Virasoro Verdier-dual scalar lane, c maps to 26-c and:
        Delta(Vir_c) + Delta(Vir_{26-c}) = 40/(5c+22) + 40/(152-5c)
            = 40 * (152-5c + 5c+22) / ((5c+22)(152-5c))
            = 40 * 174 / ((5c+22)(152-5c))
            = 6960 / ((5c+22)(152-5c))

    The numerator is constant (6960), confirming complementarity.
    """
    Delta = 40.0 / (5.0 * c_val + 22.0)
    c_dual = 26.0 - c_val
    if abs(5.0 * c_dual + 22.0) < 1e-10:
        return {'error': 'dual discriminant singular'}
    Delta_dual = 40.0 / (5.0 * c_dual + 22.0)

    Delta_sum = Delta + Delta_dual
    denom_product = (5.0 * c_val + 22.0) * (152.0 - 5.0 * c_val)
    expected_numerator = 6960.0
    expected = expected_numerator / denom_product if abs(denom_product) > 1e-10 else float('inf')

    return {
        'c': c_val,
        'Delta': Delta,
        'Delta_dual': Delta_dual,
        'sum': Delta_sum,
        'expected': expected,
        'match': abs(Delta_sum - expected) < 1e-10,
        'constant_numerator': 6960.0,
        'description': (
            'Complementarity: Delta(Vir_c) + Delta(Vir_{26-c}) = '
            '6960 / ((5c+22)(152-5c)). Constant numerator = 6960.'
        ),
    }


def self_dual_spectral_data() -> dict:
    """Spectral data at the self-dual point c = 13.

    At c = 13: the Virasoro Verdier-dual scalar lane c -> 26-c fixes
    the parameter.  This is scalar complementarity data, not a construction
    of A^! from the shadow curve.
    """
    c_val = 13.0
    inv = spectral_invariants(c_val)
    comp = complementarity_of_discriminants(c_val)

    # At c=13: the cross-ratio of branch points should be the conjugate
    # (since t_+ and t_- are complex conjugates)
    bp = branch_points_numerical(c_val)

    return {
        'c': 13.0,
        'is_self_dual': True,
        'rho': inv['rho'],
        'Delta': inv['Delta'],
        'Delta_self_dual_check': abs(inv['Delta'] - inv['Delta_dual']) < 1e-10,
        'cross_ratio_modulus': abs(inv['cross_ratio']),
        'cross_ratio_modulus_is_1': abs(abs(inv['cross_ratio']) - 1.0) < 1e-10,
        'branch_points_conjugate': (
            abs(bp['t_plus'] - bp['t_minus'].conjugate()) < 1e-10
            if isinstance(bp['t_plus'], complex) and isinstance(bp['t_minus'], complex)
            else False
        ),
        'complementarity': comp,
    }


# =========================================================================
# Section 10: Utility — shadow obstruction tower coefficients from curve
# =========================================================================

def shadow_coefficients_from_curve(c_val: float, r_max: int = 20) -> dict:
    """Recover primary-line shadow coefficients from the shadow curve data.

    Given Q(t) = q0 + q1*t + q2*t^2, the shadow coefficients are:

        S_r = (1/r) * [t^{r-1}] (t * sqrt(Q(t)))

    where [t^n] denotes the coefficient of t^n in the Taylor expansion.

    This inverts the finite primary-line construction: from y^2 = Q(t), we
    recover the coefficients generated by sqrt(Q).  Descendant and
    isomonodromic data are not recovered.
    """
    alpha_c = (180.0 * c_val + 872.0) / (5.0 * c_val + 22.0)
    q0 = c_val**2
    q1 = 12.0 * c_val
    q2 = alpha_c

    # Taylor expand sqrt(Q(t)) = sqrt(q0) * sqrt(1 + u*t + v*t^2)
    sqrt_q0 = math.sqrt(q0)
    u = q1 / q0
    v = q2 / q0

    # Coefficients of sqrt(1 + u*t + v*t^2) via the convolution method
    a = [0.0] * (r_max + 1)
    a[0] = 1.0

    for n in range(1, r_max + 1):
        if n == 1:
            rhs = u
        elif n == 2:
            rhs = v
        else:
            rhs = 0.0
        known_sum = sum(a[k] * a[n - k] for k in range(1, n))
        a[n] = (rhs - known_sum) / 2.0

    # t * sqrt(Q(t)) = sqrt(q0) * sum_{n>=0} a[n] * t^{n+1}
    # coefficient of t^{r-1} in t*sqrt(Q) = sqrt(q0) * a[r-2]
    # S_r = sqrt(q0) * a[r-2] / r

    shadow_coeffs = {}
    for r in range(2, r_max + 1):
        shadow_coeffs[r] = sqrt_q0 * a[r - 2] / r

    return shadow_coeffs


def verify_curve_tower_consistency(c_val: float, r_max: int = 15) -> dict:
    """Verify that shadow-curve reconstruction matches the ODE recursion.

    Computes primary-line shadow coefficients from:
    1. The shadow curve (closed-form Taylor expansion)
    2. The ODE recursion (from shadow_tower_ode.py)
    and checks they agree.
    """
    # Method 1: from the shadow curve
    curve_coeffs = shadow_coefficients_from_curve(c_val, r_max)

    # Method 2: from ODE recursion (numerical evaluation at c_val)
    try:
        from .shadow_tower_ode import shadow_coefficient
    except (ImportError, SystemError):
        import sys
        import os
        sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
        try:
            from shadow_tower_ode import shadow_coefficient
        except ImportError:
            return {
                'error': 'shadow_tower_ode not available',
                'curve_coefficients': curve_coeffs,
            }

    ode_coeffs = {}
    for r in range(2, r_max + 1):
        Sr_sym = shadow_coefficient(r)
        ode_coeffs[r] = float(Sr_sym.subs('c', c_val))

    # Compare
    max_error = 0.0
    comparisons = {}
    for r in range(2, r_max + 1):
        curve_val = curve_coeffs[r]
        ode_val = ode_coeffs.get(r, None)
        if ode_val is not None:
            err = abs(curve_val - ode_val)
            rel_err = err / max(abs(ode_val), 1e-30)
            max_error = max(max_error, rel_err)
            comparisons[r] = {
                'curve': curve_val,
                'ode': ode_val,
                'abs_error': err,
                'rel_error': rel_err,
            }

    return {
        'c': c_val,
        'max_relative_error': max_error,
        'consistent': max_error < 1e-8,
        'comparisons': comparisons,
    }


# =========================================================================
# Section 11: Verdier-dual scalar lane
# =========================================================================

def verdier_dual_scalar_lane(c_val: float) -> dict:
    """Virasoro scalar complementarity under c -> 26-c.

    For Virasoro, the Verdier-dual scalar lane sends c to 26-c, hence
    Q_Vir(t; c) to Q_Vir(t; 26-c).  This compares shadow curves attached to
    two scalar parameters.  It is not an assertion that the curve itself
    constructs the Koszul dual algebra A^!.

    The duality acts on invariants:
    - kappa -> kappa' = (26-c)/2
    - Delta -> Delta' = 40/(152-5c)
    - rho -> rho' = sqrt((180(26-c)+872)/((5(26-c)+22)(26-c)^2))
    - branch points t_+/- transform

    At c = 13 (self-dual scalar parameter): the listed scalar invariants are
    fixed.
    """
    inv = spectral_invariants(c_val)
    c_dual = 26.0 - c_val
    inv_dual = spectral_invariants(c_dual)

    return {
        'c': c_val,
        'c_dual': c_dual,
        'rho': inv['rho'],
        'rho_dual': inv_dual['rho'],
        'Delta': inv['Delta'],
        'Delta_dual': inv_dual['Delta'],
        'complementarity': complementarity_of_discriminants(c_val),
        'self_dual': abs(c_val - 13.0) < 1e-10,
        'scope': 'Verdier-dual scalar lane; not curve-level Koszul duality',
    }


def koszul_duality_on_curve(c_val: float) -> dict:
    """Compatibility wrapper for the older API name.

    The returned data are the Virasoro Verdier-dual scalar lane.  The shadow
    curve does not construct A^!, and Omega(B(A)) = A is bar-cobar inversion,
    not Koszul duality.
    """
    return verdier_dual_scalar_lane(c_val)


# =========================================================================
# Convenience exports
# =========================================================================

__all__ = [
    # Section 1
    'shadow_metric_from_data',
    'virasoro_shadow_metric',
    'affine_shadow_metric',
    'spectral_curve_equation',
    'riccati_from_shadow_tower',
    'shadow_curve_scope',
    # Section 2
    'branch_points_symbolic',
    'virasoro_branch_points',
    'branch_points_numerical',
    'critical_central_charge',
    'branch_point_regime',
    # Section 3
    'shadow_connection_matrix',
    'monodromy_numerical',
    'verify_koszul_monodromy',
    # Section 4
    'period_A_cycle',
    'period_B_cycle',
    'period_ratio',
    'period_closed_form',
    # Section 5
    'theta_function',
    'theta_1',
    'jacobian_torus',
    'shadow_theta_identification',
    # Section 6
    'w3_spectral_surface',
    'w3_spectral_curve_T_line',
    'w3_spectral_discriminant',
    # Section 7
    'toda_spectral_curve',
    'kdv_spectral_curve',
    'yangian_spectral_identification',
    # Section 8
    'full_spectral_analysis',
    # Section 9
    'spectral_invariants',
    'complementarity_of_discriminants',
    'self_dual_spectral_data',
    # Section 10
    'shadow_coefficients_from_curve',
    'verify_curve_tower_consistency',
    # Section 11
    'verdier_dual_scalar_lane',
    'koszul_duality_on_curve',
]
