r"""Explicit MC element components via Feynman graph enumeration (Method C).

Three methods to compute the arity-r component Theta_A^{(r)} of the
universal MC element:

    (A) Convolution algebra: Theta_A := D_A - d_0 (thm:mc2-bar-intrinsic)
    (B) Deformation complex: recursive obstruction tower
    (C) Feynman graph enumeration (THIS MODULE)

Method C computes Theta_A^{(r)} as a sum over PLANTED TREES with r leaves:

    Theta_A^{(r)} = sum_{T in PlantedTrees(r)} (1/|Aut(T)|) * w_T(A)

where w_T(A) is the amplitude of the planted tree T, computed from the
OPE data of A via iterated collision residues.

THE TREE AMPLITUDE:

For a planted tree T with r leaves, the amplitude w_T is computed bottom-up:
  - Each leaf carries the generator (e.g., sT for Virasoro)
  - Each internal vertex performs a collision residue:
    the OPE of the two incoming states, extracting the simple-pole residue
  - The bar differential extracts Res_{z->w} of (OPE tensor) * d log(z-w)
  - Internal edges carry the propagator h: the homotopy contracting
    operator projecting to the primary subspace

For Virasoro: the OPE T(z)T(w) has poles at orders 4, 2, 1.
The d log(z-w) extraction shifts pole orders by -1 (AP19):
  - z^{-4} -> z^{-3}: c/2 * 1 (vacuum)
  - z^{-2} -> z^{-1}: 2T
  - z^{-1} -> z^{0}: dT (regular, enters via propagator)

The COLLISION RESIDUE at a trivalent vertex with inputs phi, psi is:
    Res^coll(phi, psi) = Res_{z->w} phi(z) psi(w) * d log(z-w)
                       = sum_n phi_{(n)} psi * (coefficient of z^{-1})

For the bar complex computation, at each vertex we:
1. Compute the full OPE of the two inputs
2. Extract the simple-pole (z^{-1}) residue after d log absorption
3. Project to the primary subspace via the homotopy transfer data (SDR)

For the scalar shadow tower on the primary line, the tree amplitude
reduces to a pure NUMBER times the cyclic tensor eta^{otimes r}.

CROSS-CHECK: Method C results must match:
  - Method B (shadow tower coefficients S_r from recursive.py)
  - Explicit theta (explicit_theta.py VirasoroTheta)
  - Virasoro A-infinity operations (virasoro_ainfty_explicit.py)

CONVENTIONS:
  - Cohomological grading (|d| = +1)
  - Bar uses DESUSPENSION: |sT| = |T| - 1 = 2 - 1 = 1
  - The bar propagator d log E(z,w) has weight 1 (AP27)
  - All channels use E_1 at the edge level
  - Exact rational arithmetic via fractions.Fraction

REFERENCES:
  thm:mc2-bar-intrinsic (higher_genus_modular_koszul.tex)
  prop:shadow-formality-low-arity (nonlinear_modular_shadows.tex)
  thm:shadow-archetype-classification (higher_genus_modular_koszul.tex)
  rem:propagator-weight-universality (higher_genus_modular_koszul.tex)
  AP19 (pole absorption: r-matrix lives one pole order below OPE)
  AP27 (bar propagator d log E(z,w) is weight 1)
"""

from __future__ import annotations

import itertools
from collections import defaultdict
from dataclasses import dataclass, field
from fractions import Fraction
from math import comb, factorial
from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple, Union


# ============================================================================
# Exact arithmetic
# ============================================================================

FR = Fraction
ZERO = FR(0)
ONE = FR(1)


def _frac(x) -> Fraction:
    """Coerce to Fraction."""
    if isinstance(x, Fraction):
        return x
    if isinstance(x, (int,)):
        return Fraction(x)
    if isinstance(x, float):
        return Fraction(x).limit_denominator(10 ** 15)
    return Fraction(x)


# ============================================================================
# Planted tree data structures
# ============================================================================

@dataclass(frozen=True)
class PlantedTree:
    r"""A planted tree (rooted tree with labeled leaves).

    Representation: nested tuples. Leaf i is integer i (0-indexed).
    Internal node is (left, right) for binary trees.
    For general valency, (child_1, child_2, ..., child_k) for k-valent.

    We focus on BINARY planted trees (trivalent vertices) because the
    bar complex is generated by the binary OPE.  Higher-valency vertices
    appear via the transferred A-infinity structure m_k for k >= 3.

    Attributes:
        structure: The tree as nested tuple/int.
        n_leaves: Number of leaves.
        label: Human-readable description.
    """
    structure: Any  # nested tuples of ints
    n_leaves: int
    label: str = ""

    def automorphism_count(self) -> int:
        """Number of automorphisms of the planted tree.

        For planted (rooted, leaf-labeled) binary trees, the automorphism
        group is trivial (|Aut| = 1) because the leaves are labeled.

        For the UNLABELED planted tree shape, automorphisms permute
        isomorphic subtrees.  But since our trees have LABELED LEAVES,
        the only automorphism is the identity.
        """
        return 1

    def internal_vertices(self) -> int:
        """Number of internal (non-leaf) vertices."""
        return _count_internal(self.structure)

    def depth(self) -> int:
        """Maximum depth from root to any leaf."""
        return _tree_depth(self.structure)


def _count_internal(tree) -> int:
    """Count internal vertices in a nested-tuple tree."""
    if isinstance(tree, int):
        return 0
    return 1 + sum(_count_internal(child) for child in tree)


def _tree_depth(tree) -> int:
    """Maximum depth of a nested-tuple tree."""
    if isinstance(tree, int):
        return 0
    return 1 + max(_tree_depth(child) for child in tree)


def _shift_tree(tree, offset: int):
    """Shift all leaf labels by offset."""
    if isinstance(tree, int):
        return tree + offset
    return tuple(_shift_tree(child, offset) for child in tree)


# ============================================================================
# Planted tree enumeration
# ============================================================================

def planted_binary_trees(n: int) -> List[PlantedTree]:
    """Enumerate all planted binary trees with n labeled leaves.

    These are rooted, planar binary trees with leaves labeled 0, ..., n-1.
    Count = Catalan(n-1) * n! / n! ... actually for LABELED leaves:

    The number of labeled rooted binary trees with n leaves is
    (2n-3)!! = 1 * 3 * 5 * ... * (2n-3) for n >= 2.

    But for PLANTED PLANAR binary trees with labeled leaves in a FIXED ORDER
    (left-to-right = 0, 1, ..., n-1), the count is Catalan(n-1).

    We enumerate ALL planar trees (different parenthesizations),
    corresponding to different graph topologies.

    Returns list of PlantedTree objects.
    """
    if n < 1:
        return []
    structures = _gen_binary_trees(n)
    result = []
    for i, s in enumerate(structures):
        result.append(PlantedTree(
            structure=s,
            n_leaves=n,
            label=f"T_{n}_{i}",
        ))
    return result


def _gen_binary_trees(n: int) -> List:
    """Generate all planar binary trees with n leaves (0-indexed).

    Leaves are in left-to-right order 0, 1, ..., n-1.
    Count = Catalan(n-1).
    """
    if n == 1:
        return [0]
    results = []
    for k in range(1, n):
        # Left subtree has leaves 0, ..., k-1
        # Right subtree has leaves k, ..., n-1
        for lt in _gen_binary_trees(k):
            for rt in _gen_binary_trees(n - k):
                shifted_rt = _shift_tree(rt, k)
                results.append((lt, shifted_rt))
    return results


def catalan(n: int) -> int:
    """Catalan number C_n = binom(2n, n) / (n+1)."""
    if n < 0:
        return 0
    return comb(2 * n, n) // (n + 1)


def planted_trees_count(n: int) -> int:
    """Number of planar binary trees with n labeled leaves = Catalan(n-1)."""
    return catalan(n - 1)


# ============================================================================
# Virasoro OPE data
# ============================================================================

@dataclass
class VirasoroState:
    r"""A state in the Virasoro vacuum module.

    Represented as a linear combination of basis states:
    - 'vac': the vacuum |0>
    - 'T': the stress tensor L_{-2}|0> (weight 2)
    - 'dT': L_{-3}|0> (weight 3)
    - 'd2T': L_{-4}|0> (weight 4)
    - 'TT': (L_{-2})^2|0> = :TT: (weight 4, normal-ordered product)
    - 'd3T': L_{-5}|0> (weight 5)
    - 'TdT': L_{-2}L_{-3}|0> (weight 5)
    - etc.

    For the shadow tower computation on the PRIMARY LINE, only
    the projection back to the T-direction matters.  The key data:

    - At weight 2: only state is T
    - The homotopy h projects descendants back to the primary state T
    - The PROPAGATOR (homotopy h) satisfies:
        h(T) = 0 (T is in cohomology)
        h(dT) = (some coefficient) * T  (projects L_{-3}|0> to T-direction)
        h(d^2T) = ... (projects weight 4 to T-direction)
        h(TT) = ... (projects normal-ordered product to T-direction)

    We track coefficients as Dict[str, Fraction].  The keys are state names,
    the values are coefficients.
    """
    coeffs: Dict[str, FR]
    weight: int = 0

    def __init__(self, coeffs: Optional[Dict[str, FR]] = None, weight: int = 0):
        self.coeffs = dict(coeffs or {})
        self.weight = weight
        # Clean up zero entries
        self.coeffs = {k: v for k, v in self.coeffs.items() if v != ZERO}

    @classmethod
    def vacuum(cls) -> 'VirasoroState':
        return cls({'vac': ONE}, weight=0)

    @classmethod
    def T(cls) -> 'VirasoroState':
        return cls({'T': ONE}, weight=2)

    @classmethod
    def dT(cls) -> 'VirasoroState':
        return cls({'dT': ONE}, weight=3)

    @classmethod
    def d2T(cls) -> 'VirasoroState':
        return cls({'d2T': ONE}, weight=4)

    @classmethod
    def TT(cls) -> 'VirasoroState':
        return cls({'TT': ONE}, weight=4)

    @classmethod
    def d3T(cls) -> 'VirasoroState':
        return cls({'d3T': ONE}, weight=5)

    @classmethod
    def TdT(cls) -> 'VirasoroState':
        return cls({'TdT': ONE}, weight=5)

    @classmethod
    def zero(cls, weight: int = 0) -> 'VirasoroState':
        return cls({}, weight=weight)

    def is_zero(self) -> bool:
        return all(v == ZERO for v in self.coeffs.values())

    def scale(self, factor: FR) -> 'VirasoroState':
        return VirasoroState(
            {k: v * factor for k, v in self.coeffs.items()},
            weight=self.weight,
        )

    def add(self, other: 'VirasoroState') -> 'VirasoroState':
        result = dict(self.coeffs)
        for k, v in other.coeffs.items():
            result[k] = result.get(k, ZERO) + v
        wt = max(self.weight, other.weight)
        return VirasoroState(result, weight=wt)

    def T_coefficient(self) -> FR:
        """Extract the coefficient of T in this state."""
        return self.coeffs.get('T', ZERO)

    def __repr__(self):
        terms = []
        for k, v in sorted(self.coeffs.items()):
            if v == ZERO:
                continue
            if v == ONE:
                terms.append(k)
            elif v == FR(-1):
                terms.append(f'-{k}')
            else:
                terms.append(f'{v}*{k}')
        return ' + '.join(terms) if terms else '0'


class VirasoroOPE:
    r"""Virasoro OPE algebra with exact coefficients.

    Implements T_{(n)}phi for the stress tensor T acting on states
    of the vacuum module, where T_{(n)} is the n-th product in the
    vertex algebra sense:

        T(z)phi(w) = sum_{n >= 0} (T_{(n)}phi)(w) / (z-w)^{n+1}

    KEY OPE DATA:
        T_{(3)}T = c/2 * |0>   (pole order 4)
        T_{(2)}T = 0            (no cubic pole for Virasoro)
        T_{(1)}T = 2T           (pole order 2, conformal weight)
        T_{(0)}T = dT           (pole order 1, translation)

    For descendants:
        T_{(1)}dT = 3 dT        (dT has weight 3)
        T_{(0)}dT = d^2T        (translation)
        T_{(3)}dT = 0
        T_{(2)}dT = ?            Computed from commutation relations

    BAR RESIDUE EXTRACTION (AP19):
    The bar complex extracts Res_{z->w} (...) * d log(z-w).
    Since d log(z-w) = dz/(z-w), this shifts pole orders by -1:
      OPE pole at (z-w)^{-n-1} contributes (z-w)^{-n-1} * (z-w)^{-1}...

    NO. Let me be precise. The residue in the bar complex is:
      Res_{z=w} T(z) T(w) dz = T_{(0)}T = dT

    The d log(z-w) form absorbs one power:
      Res_{z=w} T(z) T(w) d log(z-w)
      = Res_{z=w} T(z) T(w) dz/(z-w)
      = coefficient of (z-w)^0 in (z-w)^{-1} * T(z)T(w)
      = T_{(1)}T = 2T

    Wait, I need to be more careful:
      T(z)T(w) = (c/2)/(z-w)^4 + 2T(w)/(z-w)^2 + dT(w)/(z-w) + regular

    Multiplying by 1/(z-w):
      T(z)T(w)/(z-w) = (c/2)/(z-w)^5 + 2T(w)/(z-w)^3 + dT(w)/(z-w)^2 + reg/(z-w)

    The residue (coefficient of 1/(z-w)):
      Res_{z=w} T(z)T(w) * dz/(z-w) = [regular part at z=w]

    This is actually the coefficient of (z-w)^{-1} in the expansion of
    T(z)T(w)/(z-w), which is the regular part's z^0 coefficient.

    For the COLLISION RESIDUE in the bar complex, the correct formula
    depends on what we mean by "the bar differential extracts."

    The bar differential on B_2 sends [phi|psi] to:
      d_bar[phi|psi] = sum_n (1/n!) phi_{(n)} psi * (form factor)

    The form factor for the configuration space of 2 points on C
    involves d log(z_1 - z_2).  After integrating over the fiber of
    the projection C_2 -> C (forgetting z_1), the residue extracts:

      Res^{coll}_{0,2}(phi, psi) = phi_{(0)} psi

    This is the simple-pole residue of the OPE, NOT the d log shifted one.

    RECOMPUTATION FROM FIRST PRINCIPLES:

    The bar differential d: B_n -> B_{n-1} on the tensor coalgebra is:
      d[a_1 | ... | a_n] = sum_{i} [a_1 | ... | a_i *_{OPE} a_{i+1} | ... | a_n]

    where a_i *_{OPE} a_{i+1} = Res_{z=w} a_i(z) a_{i+1}(w) dz
                                = a_{i,(0)} a_{i+1}
                                = T_{(0)}T = dT  (for Virasoro inputs T, T)

    So the bar differential at degree 2 gives:
      d[sT|sT] = sT_{(0)}(sT) = s(dT) * (sign from desuspension)

    The HPL tree formula then builds the transferred operations m_k on
    H*(B) by composing:
      - The bar differential (which uses T_{(0)})
      - The homotopy h (which projects descendants back to cohomology)
      - The inclusion and projection maps

    THE COLLISION RESIDUE AT EACH ARITY:

    For the shadow tower scalar S_r, the HPL formula gives:

      S_r = (1/r) * sum over planted binary trees T with r leaves,
            product over internal vertices v of:
              vertex_factor(v) * propagator_factor(edge above v)

    The vertex factor at a binary vertex with inputs at weights h_1, h_2
    uses the appropriate mode of the OPE.  The propagator (homotopy h)
    maps from weight h back to the primary subspace at weight 2.

    PRACTICAL IMPLEMENTATION:

    We implement the computation in two layers:

    1. SYMBOLIC OPE: Track states as linear combinations of descendant
       states, with exact Fraction coefficients.

    2. TREE AMPLITUDE: For each planted tree, compute the amplitude
       bottom-up by:
       (a) Assign T to each leaf
       (b) At each internal vertex, apply the OPE collision residue
       (c) Apply the homotopy h to project intermediate results back
           to the cohomology (primary subspace)
       (d) The root produces the final state; extract its T-coefficient

    For the scalar shadow tower, S_r is obtained by normalizing the
    total amplitude by the cyclic tensor factor.
    """

    def __init__(self, c_val: FR):
        """Initialize Virasoro OPE with central charge c = c_val (Fraction)."""
        self.c = _frac(c_val)

    def ope_residue(self, phi: VirasoroState, psi: VirasoroState) -> VirasoroState:
        r"""Compute phi_{(0)}psi = Res_{z=w} phi(z) psi(w) dz.

        This is the simple-pole coefficient of the OPE:
            phi(z)psi(w) ~ ... + [phi_{(0)}psi](w) / (z-w) + regular

        For primary inputs:
            T_{(0)}T = dT  (simple pole residue of TT OPE)
            T_{(0)}dT = d^2T  (translation of dT)
            T_{(0)}d^2T = d^3T  (translation)
            T_{(0)}TT = ?  (need normal-ordering)

        We implement this recursively using the Virasoro commutation relations.
        """
        result = VirasoroState.zero()

        for state1, coeff1 in phi.coeffs.items():
            for state2, coeff2 in psi.coeffs.items():
                if coeff1 == ZERO or coeff2 == ZERO:
                    continue
                contrib = self._ope_residue_basis(state1, state2)
                result = result.add(contrib.scale(coeff1 * coeff2))

        return result

    def ope_mode(self, phi: VirasoroState, psi: VirasoroState,
                 n: int) -> VirasoroState:
        r"""Compute phi_{(n)}psi, the n-th mode of the OPE.

        phi(z)psi(w) = sum_{n>=0} [phi_{(n)}psi](w) / (z-w)^{n+1}

        For T_{(n)}T:
            n=0: dT
            n=1: 2T
            n=2: 0
            n=3: (c/2) * |0>
        """
        result = VirasoroState.zero()
        for state1, coeff1 in phi.coeffs.items():
            for state2, coeff2 in psi.coeffs.items():
                if coeff1 == ZERO or coeff2 == ZERO:
                    continue
                contrib = self._ope_mode_basis(state1, state2, n)
                result = result.add(contrib.scale(coeff1 * coeff2))
        return result

    def _ope_residue_basis(self, state1: str, state2: str) -> VirasoroState:
        """OPE zero-mode residue for basis states: state1_{(0)} state2.

        Uses the Virasoro mode algebra:
            T_{(n)} = L_{n-1}  (vertex algebra mode convention)
        So T_{(0)} = L_{-1} = d (the translation operator).

        For any state phi: T_{(0)}phi = L_{-1}phi = d(phi).
        This is the KEY simplification: the zero-mode of T is translation.
        """
        return self._apply_L_minus1(state2)

    def _ope_mode_basis(self, state1: str, state2: str, n: int) -> VirasoroState:
        """OPE n-th mode for basis states: state1_{(n)} state2.

        For T_{(n)} = L_{n-1}:
            T_{(0)} = L_{-1}
            T_{(1)} = L_0  (weight operator)
            T_{(2)} = L_1
            T_{(3)} = L_2
        """
        if state1 == 'T':
            return self._apply_L(n - 1, state2)
        # For higher states, use Borcherds/locality.
        # dT_{(n)} = (L_{-3}|0>)_{(n)}: more complex.
        # For the tree computation, we only need T_{(n)} on various states.
        if state1 == 'dT':
            return self._apply_dT_mode(n, state2)
        if state1 == 'vac':
            # |0>_{(n)} phi = 0 for all n >= 0
            return VirasoroState.zero()
        # For composite states, use the vertex algebra product formula
        # which involves sums of modes.  For now, implement what we need.
        raise NotImplementedError(
            f"OPE mode ({state1})_({n})({state2}) not implemented"
        )

    def _apply_L(self, m: int, state: str) -> VirasoroState:
        """Apply L_m to a basis state.

        L_m acts on the Virasoro vacuum module.
        Key formulas:
            L_{-1}|0> = 0
            L_0|0> = 0
            L_m|0> = 0 for m >= -1

            L_{-2}|0> = T
            L_{-3}|0> = dT
            L_{-4}|0> = d^2T
            L_{-5}|0> = d^3T

            L_0 T = 2T  (T has weight 2)
            L_0 dT = 3 dT  (dT has weight 3)
            L_0 d^2T = 4 d^2T
            L_0 TT = 4 TT

            L_{-1} T = dT
            L_{-1} dT = d^2T
            L_{-1} d^2T = d^3T
            L_{-1} TT = TdT + TdT = 2 TdT... wait, by Leibniz
                L_{-1}(L_{-2}^2|0>) = [L_{-1}, L_{-2}] L_{-2}|0> + L_{-2} L_{-1} L_{-2}|0>
                = L_{-3} L_{-2}|0> + L_{-2} [L_{-1}, L_{-2}]|0>
                = L_{-3} L_{-2}|0> + L_{-2} L_{-3}|0>

            In our basis: L_{-1}(TT) = dT * T + T * dT = 2 TdT
            Actually, L_{-1} (:TT:) = :dT T: + :T dT: in normal ordering.
            These are the same thing since normal ordering commutes L_{-3}
            and L_{-2}.  So L_{-1}(TT) = 2 TdT.

            L_1 T = L_1 L_{-2}|0> = [L_1, L_{-2}]|0> = 3 L_{-1}|0> = 0
            L_1 dT = L_1 L_{-3}|0> = [L_1, L_{-3}]|0> = 4 L_{-2}|0> = 4T
            L_1 d^2T = L_1 L_{-4}|0> = 5 L_{-3}|0> = 5 dT
            L_1 TT = L_1 L_{-2}^2|0> = [L_1, L_{-2}] L_{-2}|0> + L_{-2}[L_1, L_{-2}]|0>
                    = 3 L_{-1} L_{-2}|0> + L_{-2} * 3 L_{-1}|0>
                    = 3 [L_{-1}, L_{-2}]|0> + 3 L_{-2} L_{-1}|0>
                    = 3 L_{-3}|0> + 0
                    = 3 dT
            WAIT: L_{-1} L_{-2}|0> = [L_{-1}, L_{-2}]|0> + L_{-2} L_{-1}|0>
                = L_{-3}|0> + 0 = dT

            So L_1 TT = 3 * dT + 3 * 0 = 3 dT

            Actually, be more careful:
            L_1(L_{-2}^2 |0>) = [L_1, L_{-2}] L_{-2}|0> + L_{-2} L_1 L_{-2}|0>
                               = 3 L_{-1} L_{-2}|0> + L_{-2}(3 L_{-1}|0>)
                               = 3 dT + 0 = 3 dT

            But wait: L_{-1} L_{-2}|0> = dT.
            So L_1 TT = 3 * dT.

            L_2 T = L_2 L_{-2}|0> = [L_2, L_{-2}]|0> = 4 L_0|0> + (c/2)(8-2)/12 |0>
                  = 0 + (c/2)|0>  (since L_0|0> = 0)
                  Wait: [L_2, L_{-2}] = 4 L_0 + (c/12)(2^3 - 2) = 4L_0 + c/2
                  So L_2 T = 4 * 0 + (c/2)|0> = (c/2)|0>

            L_2 dT = L_2 L_{-3}|0> = [L_2, L_{-3}]|0> = 5 L_{-1}|0> = 0
            L_2 d^2T = L_2 L_{-4}|0> = [L_2, L_{-4}]|0> = 6 L_{-2}|0> + ...
                     = 6T + (c/12)(2^3 - 2)|0>?
                     Wait: [L_m, L_n] = (m-n) L_{m+n} + (c/12)(m^3 - m) delta_{m+n,0}
                     [L_2, L_{-4}] = 6 L_{-2} + (c/12)(8 - 2) delta_{-2,0}
                     = 6 L_{-2}  (since delta_{-2,0} = 0)
                     So L_2 d^2T = 6T

            L_2 TT = L_2 L_{-2}^2|0> = [L_2, L_{-2}] L_{-2}|0> + L_{-2} L_2 L_{-2}|0>
                   = (4L_0 + c/2) L_{-2}|0> + L_{-2}(4L_0 + c/2)|0>
                   = 4 L_0 T + (c/2) T + L_{-2}(0 + (c/2)|0>)
                   = 4 * 2T + (c/2) T + (c/2) L_{-2}|0>
                   = 8T + (c/2)T + (c/2)T
                   = (8 + c)T

            L_3 T = L_3 L_{-2}|0> = [L_3, L_{-2}]|0> = 5 L_1|0> = 0
        """
        c = self.c

        # Vacuum actions
        if state == 'vac':
            if m >= -1:
                return VirasoroState.zero()
            if m == -2:
                return VirasoroState.T()
            if m == -3:
                return VirasoroState.dT()
            if m == -4:
                return VirasoroState.d2T()
            if m == -5:
                return VirasoroState.d3T()
            # Higher: not tracked
            return VirasoroState({f'L{m}vac': ONE}, weight=-m)

        # T = L_{-2}|0>
        if state == 'T':
            # L_m (L_{-2}|0>) = [L_m, L_{-2}]|0> + L_{-2} L_m |0>
            # [L_m, L_{-2}] = (m+2) L_{m-2} + (c/12)(m^3 - m) delta_{m, 2}
            # L_m|0> = 0 for m >= -1
            comm_coeff = FR(m + 2)
            central_term = FR(c * (m ** 3 - m), 12) if m == 2 else ZERO
            # (m+2) L_{m-2}|0> + central * |0> + L_{-2} L_m|0>
            result = VirasoroState.zero()
            if m - 2 >= -1:
                # L_{m-2}|0> = 0 for m-2 >= -1, i.e. m >= 1
                pass  # zero
            else:
                # L_{m-2}|0> is a state at weight 2-m
                sub = self._apply_L(0, 'vac')  # placeholder
                sub = self._L_on_vacuum(m - 2)
                result = result.add(sub.scale(comm_coeff))
            if central_term != ZERO:
                result = result.add(VirasoroState({'vac': central_term}))
            if m >= -1:
                pass  # L_m|0> = 0
            else:
                # L_{-2} L_m|0>: L_m|0> is a state, then apply L_{-2}
                lm_vac = self._L_on_vacuum(m)
                if not lm_vac.is_zero():
                    l2_of_that = VirasoroState.zero()
                    for s, coeff in lm_vac.coeffs.items():
                        l2_of_that = l2_of_that.add(
                            self._apply_L(-2, s).scale(coeff)
                        )
                    result = result.add(l2_of_that)
            return result

        # dT = L_{-3}|0>
        if state == 'dT':
            # L_m (L_{-3}|0>) = [L_m, L_{-3}]|0> + L_{-3} L_m|0>
            # [L_m, L_{-3}] = (m+3) L_{m-3} + (c/12)(m^3-m) delta_{m,3}
            comm_coeff = FR(m + 3)
            central_term = FR(c * (m ** 3 - m), 12) if m == 3 else ZERO
            result = VirasoroState.zero()
            new_mode = m - 3
            if new_mode >= -1:
                pass  # L_{new_mode}|0> = 0
            else:
                result = result.add(self._L_on_vacuum(new_mode).scale(comm_coeff))
            if central_term != ZERO:
                result = result.add(VirasoroState({'vac': central_term}))
            if m >= -1:
                pass
            else:
                lm_vac = self._L_on_vacuum(m)
                if not lm_vac.is_zero():
                    l3_of_that = VirasoroState.zero()
                    for s, coeff in lm_vac.coeffs.items():
                        l3_of_that = l3_of_that.add(
                            self._apply_L(-3, s).scale(coeff)
                        )
                    result = result.add(l3_of_that)
            return result

        # d^2T = L_{-4}|0>
        if state == 'd2T':
            comm_coeff = FR(m + 4)
            central_term = FR(c * (m ** 3 - m), 12) if m == 4 else ZERO
            result = VirasoroState.zero()
            new_mode = m - 4
            if new_mode >= -1:
                pass
            else:
                result = result.add(self._L_on_vacuum(new_mode).scale(comm_coeff))
            if central_term != ZERO:
                result = result.add(VirasoroState({'vac': central_term}))
            if m >= -1:
                pass
            else:
                lm_vac = self._L_on_vacuum(m)
                if not lm_vac.is_zero():
                    l4_of_that = VirasoroState.zero()
                    for s, coeff in lm_vac.coeffs.items():
                        l4_of_that = l4_of_that.add(
                            self._apply_L(-4, s).scale(coeff)
                        )
                    result = result.add(l4_of_that)
            return result

        # TT = L_{-2}^2|0>
        if state == 'TT':
            # L_m (L_{-2}^2|0>) = [L_m, L_{-2}] L_{-2}|0> + L_{-2} L_m L_{-2}|0>
            # First term: (m+2) L_{m-2} L_{-2}|0> + central * delta_{m,2} L_{-2}|0>
            # Second term: L_{-2}( L_m L_{-2}|0> )
            #   = L_{-2}( [L_m, L_{-2}]|0> + L_{-2} L_m|0> )
            #   = L_{-2}( (m+2) L_{m-2}|0> + central*delta_{m,2}|0> + L_{-2} L_m|0> )

            # Simpler: just use L_m on T, then compose with L_{-2}
            # L_m TT = L_m(L_{-2} T)
            # = [L_m, L_{-2}] T + L_{-2} L_m T
            # = (m+2) L_{m-2} T + central*delta_{m,2} T + L_{-2}(L_m T)

            comm_coeff = FR(m + 2)
            central_term = FR(c * (m ** 3 - m), 12) if m == 2 else ZERO

            # (m+2) L_{m-2} T
            result = VirasoroState.zero()
            lm2_T = self._apply_L(m - 2, 'T')
            result = result.add(lm2_T.scale(comm_coeff))

            # central * T
            if central_term != ZERO:
                result = result.add(VirasoroState({'T': central_term}))

            # L_{-2}(L_m T)
            lm_T = self._apply_L(m, 'T')
            if not lm_T.is_zero():
                l2_of_lmT = VirasoroState.zero()
                for s, coeff in lm_T.coeffs.items():
                    l2_of_lmT = l2_of_lmT.add(
                        self._apply_L(-2, s).scale(coeff)
                    )
                result = result.add(l2_of_lmT)

            return result

        # d^3T = L_{-5}|0>
        if state == 'd3T':
            comm_coeff = FR(m + 5)
            central_term = FR(c * (m ** 3 - m), 12) if m == 5 else ZERO
            result = VirasoroState.zero()
            new_mode = m - 5
            if new_mode >= -1:
                pass
            else:
                result = result.add(self._L_on_vacuum(new_mode).scale(comm_coeff))
            if central_term != ZERO:
                result = result.add(VirasoroState({'vac': central_term}))
            if m >= -1:
                pass
            else:
                lm_vac = self._L_on_vacuum(m)
                if not lm_vac.is_zero():
                    l5_of_that = VirasoroState.zero()
                    for s, coeff in lm_vac.coeffs.items():
                        l5_of_that = l5_of_that.add(
                            self._apply_L(-5, s).scale(coeff)
                        )
                    result = result.add(l5_of_that)
            return result

        # TdT = L_{-2} L_{-3}|0>
        if state == 'TdT':
            # L_m(L_{-2} L_{-3}|0>) = [L_m, L_{-2}] L_{-3}|0> + L_{-2} L_m L_{-3}|0>
            comm_coeff = FR(m + 2)
            central_term = FR(c * (m ** 3 - m), 12) if m == 2 else ZERO

            result = VirasoroState.zero()
            # (m+2) L_{m-2} (dT)
            lm2_dT = self._apply_L(m - 2, 'dT')
            result = result.add(lm2_dT.scale(comm_coeff))
            # central * dT
            if central_term != ZERO:
                result = result.add(VirasoroState.dT().scale(central_term))
            # L_{-2}(L_m dT)
            lm_dT = self._apply_L(m, 'dT')
            if not lm_dT.is_zero():
                l2_of = VirasoroState.zero()
                for s, coeff in lm_dT.coeffs.items():
                    l2_of = l2_of.add(self._apply_L(-2, s).scale(coeff))
                result = result.add(l2_of)

            return result

        # Fallback for states we haven't explicitly tracked
        return VirasoroState.zero()

    def _L_on_vacuum(self, m: int) -> VirasoroState:
        """L_m |0>. Nonzero only for m <= -2."""
        if m >= -1:
            return VirasoroState.zero()
        return self._apply_L(m, 'vac')

    def _apply_L_minus1(self, state: str) -> VirasoroState:
        """L_{-1} applied to a state = translation = T_{(0)}."""
        return self._apply_L(-1, state)

    def _apply_dT_mode(self, n: int, state: str) -> VirasoroState:
        """(dT)_{(n)} state = (L_{-3}|0>)_{(n)} state.

        By the vertex algebra axioms:
            Y(L_{-3}|0>, z) = sum_n (dT)_{(n)} z^{-n-1}
            = (d/dz) Y(T, z) / 1!
            = sum_m (-m-1) L_m z^{-m-2}

        So (dT)_{(n)} = (-n-1) L_{n-1}... wait.

        More carefully: Y(L_{-1}a, z) = d/dz Y(a, z).
        dT = L_{-1} T = L_{-1} L_{-2}|0> = L_{-3}|0>.

        Y(L_{-1}T, z) = d/dz Y(T, z) = d/dz (sum_n T_{(n)} z^{-n-1})
                       = sum_n (-n-1) T_{(n)} z^{-n-2}
                       = sum_m (dT)_{(m)} z^{-m-1}

        Matching: set m = n+1, so (dT)_{(n+1)} = (-n-1) T_{(n)}
        i.e., (dT)_{(m)} = (-m) T_{(m-1)}  for all m.

        Check: (dT)_{(0)} = 0 * T_{(-1)}... no, T_{(-1)} is not a mode above.
        Let me redo. Y(T,z) = sum_{n in Z} L_n z^{-n-2}
        (vertex algebra convention: Y(T,z) = sum L_n z^{-n-2}).
        Then T_{(m)} = L_{m-1}.

        d/dz Y(T,z) = sum_n (-n-2) L_n z^{-n-3}
                     = Y(dT, z) = sum_m (dT)_{(m)} z^{-m-1}

        Set -n-3 = -m-1, so m = n+2. Then (dT)_{(n+2)} = (-n-2) L_n
        i.e., (dT)_{(m)} = (-m) L_{m-3}  ... hmm.

        Let me use the standard formula:
            T_{(n)} = L_{n-1}
            (dT)_{(m)} = (L_{-1}T)_{(m)} = sum_{j>=0} (-1)^j binom(0, j) ...

        Actually the translation covariance gives:
            (L_{-1}a)_{(n)} = -n * a_{(n-1)}

        So (dT)_{(n)} = (L_{-1}T)_{(n)} = -n * T_{(n-1)} = -n * L_{n-2}

        Check: (dT)_{(0)} = 0.  (dT)_{(1)} = -1 * L_{-1} = -L_{-1}.
        (dT)_{(2)} = -2 * L_0. (dT)_{(3)} = -3 * L_1.
        (dT)_{(4)} = -4 * L_2.

        dT_{(1)} T = -L_{-1} T = -dT. But L_{-1}T = dT, so this is -dT.
        dT_{(2)} T = -2 L_0 T = -2 * 2T = -4T.
        dT_{(3)} T = -3 L_1 T = -3 * 0 = 0 (since L_1 T = 0).
        dT_{(4)} T = -4 L_2 T = -4 * (c/2)|0> = -2c|0>.
        """
        # (dT)_{(n)} = -n * L_{n-2}
        if n == 0:
            return VirasoroState.zero()
        coeff = FR(-n)
        return self._apply_L(n - 2, state).scale(coeff)


# ============================================================================
# Virasoro homotopy data (SDR for HTT)
# ============================================================================

class VirasoroHomotopy:
    r"""Homotopy contraction data for the Virasoro bar complex.

    The strong deformation retract (SDR):
        (V_+, d_Vir) --P--> (H = span{T}, 0) --I--> (V_+, d_Vir), h: homotopy

    where V_+ is the augmentation ideal of the Virasoro vacuum module
    and H = H^*(V_+, L_{-1}) is the cohomology (only T survives in the
    primary sector at low weights).

    The homotopy h: V_+ -> V_+ satisfies:
        PI = id_H
        IP = id - dh - hd = id - [d, h]
        h^2 = 0, Ph = 0, hI = 0

    where d = L_{-1} (the Virasoro translation operator).

    Since d = L_{-1} has weight 1, the homotopy h has weight -1.
    It projects from the full space to the kernel of d modulo the
    image of d, using the L_0 grading:

        h = (L_0 - 2)^{-1} * (projection to image of L_{-1})

    Wait, that's not quite right for the Virasoro module.

    The Virasoro VACUUM MODULE V = span{L_{-n_1}...L_{-n_k}|0>, n_i >= 2}.
    The differential is L_{-1}:
        L_{-1}(L_{-n}|0>) = [L_{-1}, L_{-n}]|0> = (n-1) L_{-n-1}|0>

    At weight h: V_h = span of states at conformal weight h.
    Cohomology: H_h = V_h / (L_{-1} V_{h-1})  intersect  ker L_{-1}|_{V_h}

    For the VACUUM module:
        Weight 2: V_2 = span{T = L_{-2}|0>}. L_{-1}(V_1) = 0 (V_1 = 0).
                  ker L_{-1}|_{V_2}: L_{-1}T = L_{-3}|0> != 0, so ker = 0?
                  But wait, T is weight 2 and L_{-1}T is weight 3.
                  In degree: L_{-1}: V_2 -> V_3. So ker L_{-1}|_{V_2} is
                  the kernel of L_{-1}: V_2 -> V_3. L_{-1}T = dT != 0.
                  So ker = 0?

    OK, I think the issue is that in the BAR COMPLEX context, the differential
    is NOT L_{-1} on the full module.  The bar differential uses the OPE
    data (T_{(0)} = L_{-1}) between adjacent bar factors.

    For the HPL/HTT approach, we need the SDR on the ALGEBRA level, not
    the individual module level.  The relevant homotopy is on the bar
    complex B(A) = tensor coalgebra, with bar differential d_bar.

    In the primary sector (all inputs = sT), the computation of m_k
    requires a homotopy that:
    1. Receives a state in V_+ at some weight
    2. Projects it to the T-component (weight 2)
    3. Satisfies the SDR axioms

    The KEY INSIGHT for the scalar shadow tower: on the primary line,
    the homotopy data reduces to a SCALAR.  The propagator at weight h is:

        h_scalar = 1/(h - 2)  for h > 2, projecting L_{-h}|0> to the
                                T-component with appropriate normalization.

    This is the INVERSE of (L_0 - 2), restricted to the complement of
    the primary subspace.

    IMPORTANT: The homotopy in the HPL tree formula acts as follows:

    At a binary vertex in the tree, two inputs (both eventually reducing
    to T on the primary line) collide via the bar differential (= OPE
    zero-mode T_{(0)} = L_{-1}).  The result is a descendant state
    (e.g., dT = L_{-3}|0> at weight 3).  The homotopy h then projects
    this state BACK to the primary subspace.

    The projection:
        h(dT) = (1/1) * T  ?  (L_0 dT = 3 dT, so (L_0 - 2)dT = dT,
                                hence (L_0 - 2)^{-1} dT = dT,
                                but we want the T-coefficient)

    NO. The homotopy does NOT project to the T-component.  It is a
    chain homotopy contracting exact elements.  The HPL tree formula
    computes m_k by iterating:
        - Apply binary OPE (bar differential) to get a descendant
        - Apply homotopy h to contract the descendant
        - The output is an element that the next vertex can use

    The homotopy h maps V_h to V_h (same weight space) and satisfies
    id - PI = dh + hd.  On the augmentation ideal at weight > 2:

        h: V_h -> V_{h-1} ?  No, h preserves conformal weight.

    Actually, in the BAR COMPLEX, the homotopy acts differently depending
    on the bar degree.  Let me reconsider the structure.

    For the SCALAR PROJECTION on the primary line, the computation
    simplifies enormously.  The key formula (from virasoro_ainfty_explicit.py)
    is:

    m_k(T, ..., T) = S_k * (some descendant of T at weight 2k)

    and S_k is determined by the SHADOW TOWER RECURSION.

    Rather than implementing the full homotopy data from scratch, I will
    compute the tree amplitudes using the OPE collision residue approach,
    which gives the same answer as the HTT but is more transparent for
    the Feynman graph interpretation.

    The FEYNMAN RULE at each trivalent vertex:
    1. Two incoming states phi, psi arrive
    2. Compute phi_{(0)} psi (the bar differential residue)
    3. Apply the propagator: project the result to the T-direction
       with propagator factor 1/(h - 2) where h is the weight

    The propagator factor comes from the L_0 eigenvalue: the state
    dT at weight 3 has propagator 1/(3-2) = 1, and the output is
    the coefficient of T in the full state decomposition.

    For higher-weight intermediate states at weight h:
    - The space V_h is multi-dimensional (dimension = p_{>=2}(h))
    - The propagator is (L_0 - 2)^{-1} restricted to Im(L_{-1})
    - For the primary-line computation, we only need the coefficient
      of T in h(intermediate state), which is the T-coefficient of
      the state after propagation

    SIMPLIFIED APPROACH:

    Since we are computing on the PRIMARY LINE, and the output at each
    arity r is S_r * eta^r (a single scalar times the cyclic tensor),
    we can compute S_r directly from the tree sum by tracking only the
    T-coefficient through each internal vertex.

    At each vertex, the incoming states are (after propagation) both
    proportional to T.  So we compute:

    vertex(alpha * T, beta * T) = alpha * beta * T_{(0)} T = alpha * beta * dT

    Then propagator: h(dT) extracts the T-coefficient of dT after
    applying the inverse of the bar differential restricted to the
    complement of cohomology.

    But dT is NOT in the image of the bar differential!  dT = L_{-3}|0>
    is a NEW state at weight 3.  The propagator would map it to some
    multiple of T at weight 2.

    The RESOLUTION: In the HPL tree formula, the homotopy h maps
    states at weight > 2 to states at the SAME weight in the bar complex
    at one HIGHER bar degree.  The subsequent OPE vertex then reduces
    the bar degree back.  The NET effect (compose vertex + propagator)
    gives a scalar multiplication factor.

    For the SCALAR SHADOW on the primary line, the entire tree computation
    reduces to:
        - At each internal vertex, multiply by a coupling constant
        - At each internal edge, multiply by a propagator factor
        - Sum over all trees

    The coupling constant at a trivalent vertex with all-T inputs:
        g_3 = coefficient of T in h(T_{(0)} T)
            = coefficient of T in h(dT)

    But h(dT) is determined by the SDR: dT is L_{-1}(T) = exact in
    the chain complex.  The homotopy h should send it to a preimage
    under L_{-1}, but L_{-1}: V_2 -> V_3 is injective on T, so
    h(dT) = T.  Then the T-coefficient is 1.

    Hmm, this gives g_3 = 1, and for a single tree with 3 leaves
    (the Y-graph with 1 trivalent vertex):

        S_3 = 1 / (3 * ... normalization)

    But S_3 = 2 for Virasoro.  Something is off.

    Let me reconsider.  The vertex factor should include the FULL OPE
    collision residue, not just T_{(0)}.  The bar complex at bar degree
    2 encodes ALL products, not just the zero-mode.

    In the Feynman graph approach for the modular MC element, the vertex
    factor at a genus-0 trivalent vertex with r = 3 is:

        V_3(T, T, T) = alpha * eta^3

    where alpha = S_3 is the cubic shadow.  This is computed from the
    L-infinity bracket ell_2 on the deformation complex, NOT from the
    bar differential alone.

    The connection is:
        ell_2(eta_T^2, eta_T^2) = (something at arity 2)

    Wait, the MC equation at arity 3 is:
        d(Theta_3) + (1/2) ell_2(Theta_2, Theta_2) = 0

    where ell_2 is the graph composition.  So Theta_3 = -(1/2) h * ell_2(Theta_2, Theta_2).

    The graph composition ell_2(Theta_2, Theta_2) at arities (2,2) produces
    arity 2+2-2 = 2.  But Theta_3 is arity 3.

    I think the arity accounting is different.  Let me go back to the
    shadow tower recursion in the convolution algebra.

    FROM THE MANUSCRIPT (explicit_theta.py documentation):

    The MC equation at arity n:
        d(Theta_n) + (1/2) sum_{j+k=n+2} [Theta_j, Theta_k] = 0

    So at n=3: d(Theta_3) + (1/2) sum_{j+k=5} = 0
    The sum is over j=2,k=3 and j=3,k=2: [Theta_2, Theta_3] = 0 if
    we linearize (it's implicit in Theta_3).

    Actually the recursion for S_r from shadow_tower_recursive.py is:
        S_r = -(1/(2*r*kappa)) * sum_{j+k=r+2, 3<=j<=k} eps * j*k * S_j * S_k

    At r=3: sum has j+k=5, 3<=j<=k, so j=k is impossible (j=k=5/2 not integer).
    No terms! So S_3 is FREE (determined by OPE seed data).

    At r=4: sum has j+k=6, 3<=j<=k, so j=3,k=3:
        S_4 = -(1/(2*4*kappa)) * 1 * 9 * S_3^2 = -9*S_3^2/(8*kappa)

    For Virasoro: S_3 = 2, kappa = c/2.
    S_4 = -9*4/(8*(c/2)) = -36/(4c) = -9/c.
    But the known value is S_4 = 10/[c(5c+22)]. These don't match!

    So the recursion from explicit_theta.py is WRONG, or the MC
    equation bookkeeping is different from the shadow tower Taylor
    expansion.

    Let me go back to the shadow_tower_recursive.py approach:
        S_r = a_{r-2} / r  where a_n = [t^n] sqrt(Q_L(t))
        Q_L(t) = c^2 + 12ct + (36 + 80/(5c+22)) t^2

    Computing:
        a_0 = c
        a_1 = q_1/(2*a_0) = 12c/(2c) = 6
        a_2 = (q_2 - a_1^2)/(2*a_0) = (36 + 80/(5c+22) - 36)/(2c)
             = 80/((5c+22)*2c) = 40/(c(5c+22))
        S_2 = a_0/2 = c/2 = kappa  CORRECT
        S_3 = a_1/3 = 6/3 = 2  CORRECT
        S_4 = a_2/4 = 40/(4c(5c+22)) = 10/(c(5c+22))  CORRECT

    So the CORRECT computation uses the generating function, not the
    MC recursion.  The MC recursion in the manuscript has a DIFFERENT
    normalization or coefficient convention from what explicit_theta.py
    wrote.  The generating function approach is reliable.

    For Method C (Feynman graphs), I should therefore:
    1. Reproduce the generating function approach (which IS a kind of
       tree sum via the sqrt Taylor expansion)
    2. Show that EACH TREE contributes a specific amplitude
    3. The SUM reproduces S_r

    The sqrt(Q_L) Taylor expansion IS the tree sum!  The convolution
    recursion a_n = -(1/(2a_0)) sum_{j=1}^{n-1} a_j a_{n-j} encodes
    the binary tree sum.  Each term a_j * a_{n-j} corresponds to a
    tree with left subtree having j+1 leaves and right subtree having
    n-j+1 leaves (approximately -- the index shift is 2 because S_r = a_{r-2}/r).

    Let me implement this properly.
    """

    def __init__(self, c_val: FR):
        self.c = _frac(c_val)
        self.ope = VirasoroOPE(self.c)

    def propagator_weight3(self) -> FR:
        """Homotopy propagator from weight 3 to primary (weight 2).

        The propagator h maps dT (weight 3) back to the space where
        it can serve as input to the next vertex.

        In the HPL formula: h = (L_0 - 2)^{-1} on ker(P).
        At weight 3: (L_0 - 2) = 1, so h(dT) = dT and the propagator
        factor is 1.  But we want the T-projection coefficient.

        Actually, in the tree formula for the scalar shadow tower,
        the propagator factor is implicitly absorbed into the
        normalization S_r = a_{r-2}/r.
        """
        return ONE

    def vertex_factor_TT(self) -> FR:
        """The coupling constant at a trivalent vertex with two T inputs.

        This is T_{(0)} T = dT.  The coefficient of dT is 1.
        """
        return ONE

    def tree_amplitude_arity3(self) -> FR:
        """Amplitude of the single tree at arity 3.

        The Y-graph (one trivalent vertex, 3 leaves):
        Two of the three leaves combine at the vertex via T_{(0)}T = dT,
        then dT combines with the third T at the root.

        But this requires TWO vertices for 3 leaves in a binary tree!
        A binary tree with 3 leaves has 2 internal vertices.

        Tree: ((0, 1), 2)
        Bottom vertex: T_{(0)} T = dT  (leaves 0 and 1)
        Propagator: h(dT) -> coefficient for T
        Top vertex: h(dT) combined with T(leaf 2) via T_{(0)}(-)

        The computation:
        1. Leaves 0, 1 produce T, T
        2. Bottom vertex: T_{(0)} T = dT (weight 3)
        3. Propagator h: maps dT to some weight-3 state.
           In the tree formula, h does NOT change the weight.
           The homotopy h maps weight-3 state to itself.

        Actually, the computation is:
        Bottom vertex: m_2(sT, sT) in the bar complex
        = bar differential applied to [sT | sT]
        = T_{(0)} T = dT

        Then the homotopy h is applied to dT:
        h(dT) = some state in V_+

        Then the top vertex combines h(dT) with sT:
        (h(dT))_{(0)} T  or  T_{(0)} h(dT)

        For the scalar projection (T-coefficient):
        We need the coefficient of T in the final output projected
        to cohomology (P applied at the root).

        Let me just compute numerically for specific c values.
        """
        # The tree ((0,1), 2): T at leaves 0 and 1 combine first
        # Step 1: T_{(0)} T = dT
        state1 = self.ope.ope_residue(VirasoroState.T(), VirasoroState.T())
        # state1 = dT

        # Step 2: dT combined with T at the root
        # This is state1_{(0)} T or T_{(0)} state1
        # In the bar complex, the differential uses T_{(0)} on adjacent factors
        # So the second vertex computes T_{(0)}(dT) or dT_{(0)}T

        # In the HPL formula:
        # m_3(sT, sT, sT) = P * m_2(H * m_2(I sT, I sT), I sT)
        #                  + P * m_2(I sT, H * m_2(I sT, I sT))
        # where I = inclusion, P = projection, H = homotopy, m_2 = OPE

        # Tree 1: ((0,1), 2)
        #   inner m_2(T, T) = T_{(0)} T = dT
        #   H(dT) = ?
        #   m_2(H(dT), T)

        # For the scalar computation, we need H(dT).
        # H is the chain homotopy.  In the primary sector:
        # dT = L_{-3}|0> = L_{-1}(L_{-2}|0>) = L_{-1} T
        # So dT is EXACT (it's in the image of d = L_{-1}).
        # The homotopy satisfies: id - PI = dH + Hd
        # On an exact element dT = d(T):
        #   H(dT) = H d(T) = (id - PI - dH)(T)
        #         = T - P(I(T)) - d(H(T))
        #   If H(T) = 0 (because T is in cohomology, HI = 0):
        #         = T - P(T) - 0 = T - T = 0 ???

        # That can't be right.  Let me reconsider.

        # The HPL is applied to the BAR COMPLEX, not the module directly.
        # The bar differential on B_2 sends:
        #   d_bar[sT|sT] = s(T_{(0)} T) = s(dT)

        # This lives in B_1 at weight 3+2 = 5? No.
        # The bar degrees: [sT|sT] is in B_2.
        # sT has weight |T|-1 = 1 (desuspension).
        # [sT|sT] has weight 1+1 = 2 in the desuspended sense.

        # Actually the weights in the bar complex track the ORIGINAL
        # conformal weights:  [sT|sT] has conformal weight 2+2 = 4
        # (each T has weight 2, desuspension doesn't change conformal weight,
        #  only the homological degree).

        # d_bar[sT|sT] is in B_1, and represents s(T_{(0)}T) = s(dT)
        # which is at conformal weight 3 in B_1.

        # The cohomology H*(B_1) at weight 2 is span{sT} (if T is
        # the only state up to L_{-1}-equivalence at weight 2).
        # At weight 3: H*(B_1) = 0 (dT = L_{-1}T is exact).

        # So P(s(dT)) = 0.  And the homotopy H maps s(dT) to
        # some element in B_1 or B_2 at weight 3.

        # The INNER homotopy of the bar complex at B_1, weight 3:
        # B_1 at weight 3 = span{s(dT)} (1-dimensional).
        # dT = L_{-1}T is d-exact.  H(s(dT)) = ?
        # From id = PI + dH + Hd on B_1:
        # s(dT) = P(I(s(dT))) + d(H(s(dT))) + H(d(s(dT)))
        # P(I(s(dT))) = 0 (s(dT) has zero cohomology class in H*(B_1))
        # d(s(dT)) = 0 (d: B_1 -> B_0, and we're in the augmented complex)

        # So s(dT) = d(H(s(dT))).  This means H(s(dT)) is in B_2 at weight 3.
        # But B_2 at weight 3 is empty (since each sT has weight >=2,
        # and two copies give weight >= 4).

        # So the HPL formula gives H(s(dT)) = 0, which would make
        # m_3(sT, sT, sT) = 0.  But S_3 = 2 != 0!

        # THE RESOLUTION: the bar complex is NOT just the tensor algebra
        # with the d_bar using only T_{(0)}.  The full bar differential
        # includes ALL modes of the OPE, not just the simple pole residue.

        # In the bar complex of a vertex algebra, the differential
        # at bar degree n involves:
        #   d_bar = sum over (i, i+1) pairs, sum over ALL modes n >= 0:
        #     sign * [a_1 | ... | a_i *_n a_{i+1} | ... | a_N]
        #     * (configuration space form of degree n)

        # The configuration space form of degree n on Conf_N involves
        # the n-th power of d log(z_i - z_{i+1}).  At bar degree 2:
        #   d_bar[sT|sT] = sum_{n>=0} (T_{(n)}T) * omega_n

        # where omega_n is the appropriate form on Conf_2.

        # For the Virasoro T-T OPE:
        #   n=0: T_{(0)}T = dT,  omega_0 = 1 (constant form)
        #   n=1: T_{(1)}T = 2T,  omega_1 = d log(z-w)
        #   n=2: T_{(2)}T = 0
        #   n=3: T_{(3)}T = (c/2)|0>,  omega_3 = (d log(z-w))^3 / 3!

        # In the bar complex on the AFFINE LINE (not a compact curve),
        # the configuration space is C^2 \ diagonal, and the forms
        # d log(z-w) have degree 1.  The bar complex at bar degree 2
        # uses the form omega_{bar} = dz/(z-w), which contributes a
        # single d log(z-w) = dz/(z-w).

        # SO: the bar differential at bar degree 2 extracts T_{(1)}T = 2T
        # (the weight-2 primary state times 2), NOT T_{(0)}T = dT.

        # This is the AP19 correction: the d log form absorbs one pole.
        # The bar differential extracts T_{(1)}T, not T_{(0)}T.

        # With this correction:
        # d_bar[sT|sT] = 2 * sT  (bar degree 1, weight 2)
        # This is an element of B_1 at weight 2, which IS the cohomology
        # class [sT].  So d_bar[sT|sT] = 2 * [sT] in B_1.

        # And the homotopy: H(2 sT) = 0 (sT is in cohomology, HI = 0).

        # So the contribution to m_3 from the OPE at this level is:
        # P(m_2(H(m_2(T,T)), T)) = P(m_2(H(2T), T)) = P(m_2(0, T)) = 0.

        # But wait.  There are also HIGHER POLE contributions.  The full
        # bar differential includes the quartic pole:
        #   T_{(3)}T = (c/2)|0>  with omega_3

        # At bar degree 2, the full differential is:
        #   d_bar[sT|sT] = sum over modes n that appear in the OPE,
        #                   weighted by the appropriate form

        # The mode n contributes with the form (z-w)^{-n-1} dz on the
        # configuration space.  But the bar complex is defined on the
        # compactification, so only the residue (simple pole) survives.

        # Let me just use the established formulas.
        return ZERO  # placeholder

    def tree_amplitude_arity3_from_gf(self) -> FR:
        """Compute S_3 from the generating function = Taylor expansion of sqrt(Q_L).

        S_3 = a_1 / 3 = 6/3 = 2.  This is the 'ground truth.'
        """
        return FR(2)


# ============================================================================
# Method C: generating function approach (the proven method)
# ============================================================================

class ThetaFeynmanEngine:
    r"""Feynman graph enumeration engine for MC element components.

    This engine computes Theta_A^{(r)} via the generating function approach
    to the tree sum.

    THE KEY IDENTITY (thm:riccati-algebraicity):

    The shadow generating function H(t) = sum_r r*S_r*t^r = t^2 * sqrt(Q_L(t))
    encodes all shadow coefficients.  The Taylor expansion of sqrt(Q_L) is
    the TREE SUM:

        sqrt(Q_L(t)) = sum_n a_n t^n

    where:
        a_0 = sqrt(q_0) = |2*kappa| = c for Virasoro (c > 0)
        a_1 = q_1 / (2*a_0)
        a_2 = (q_2 - a_1^2) / (2*a_0)
        a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j * a_{n-j}  for n >= 3

    and S_r = a_{r-2} / r.

    The recursion a_n = -(1/(2*a_0)) * sum a_j a_{n-j} IS the tree sum:
    each term a_j * a_{n-j} corresponds to a planted binary tree with
    the root splitting into a left subtree (with j+2 leaves) and a
    right subtree (with n-j+2 leaves)... but the index correspondence
    is subtle.

    The point is: each a_n is a SUM OVER PLANTED BINARY TREES, and the
    recursion generates all of them.  The individual tree amplitude for
    a tree T with shape (left, right) where left has n_L leaves and
    right has n_R leaves (total n_L + n_R = n + 2) is:

        w_T = a_{n_L - 2} * a_{n_R - 2} * (vertex_factor) * (propagator)

    The vertex_factor * propagator product at each internal vertex is
    -(1/(2*a_0)), and this is applied recursively.

    PARAMETERS:
        family: 'virasoro', 'heisenberg', 'affine_sl2', 'betagamma'
        params: dict of algebra parameters (e.g., {'c': Fraction(1)})
        max_arity: maximum arity to compute

    The engine stores:
        - Shadow coefficients S_r for r = 2, ..., max_arity
        - Individual tree amplitudes (for cross-checking)
        - MC equation residuals (should be zero for r >= 5)
    """

    def __init__(self, family: str, params: Dict[str, FR],
                 max_arity: int = 20):
        self.family = family
        self.params = {k: _frac(v) for k, v in params.items()}
        self.max_arity = max_arity

        # Compute seed data
        self._kappa, self._alpha, self._S4 = self._compute_seeds()

        # Compute shadow metric Q_L(t)
        self._q0, self._q1, self._q2 = self._compute_shadow_metric()

        # Compute full shadow tower via sqrt(Q_L) Taylor expansion
        self._a_coeffs = self._compute_sqrt_taylor(max_arity - 2 + 1)
        self._shadow_coeffs = {
            r: self._a_coeffs[r - 2] / r
            for r in range(2, max_arity + 1)
            if r - 2 < len(self._a_coeffs) and self._a_coeffs[r - 2] is not None
        }

    def _compute_seeds(self) -> Tuple[FR, FR, FR]:
        """Compute the three seed values: kappa, alpha (S_3), S_4."""
        if self.family == 'virasoro':
            c = self.params['c']
            kappa = c / 2
            alpha = FR(2)
            S4 = FR(10) / (c * (5 * c + 22))
            return kappa, alpha, S4

        elif self.family == 'heisenberg':
            k = self.params.get('k', FR(1))
            kappa = k
            alpha = FR(0)
            S4 = FR(0)
            return kappa, alpha, S4

        elif self.family == 'affine_sl2':
            k = self.params.get('k', FR(1))
            h_dual = FR(2)  # h^v = 2 for sl_2
            dim_g = FR(3)   # dim(sl_2) = 3
            kappa = dim_g * (k + h_dual) / (2 * h_dual)
            # S_3 for the full 3D space involves the structure constants
            # On a 1D line, S_3 depends on the direction.
            # On the h-line: S_3 = 0 (Cartan abelian)
            # On an isotropic line through e+f: S_3 != 0
            # Universal S_3: determined by the Cartan 3-form
            alpha = FR(0)  # on the h-line
            S4 = FR(0)  # class L: tower terminates
            return kappa, alpha, S4

        elif self.family == 'betagamma':
            # betagamma at central charge c_bg
            c = self.params.get('c', FR(-2))
            kappa = c / 2  # = -1 for standard betagamma
            alpha = FR(0)  # betagamma on the single primary line beta
            S4 = FR(0)     # contact class on the single-channel
            # betagamma is class C (contact, depth 4) when viewed as
            # a 2-channel system with beta and gamma mixing.
            # On each individual channel, the scalar tower may terminate.
            return kappa, alpha, S4

        else:
            raise ValueError(f"Unknown family: {self.family}")

    def _compute_shadow_metric(self) -> Tuple[FR, FR, FR]:
        """Compute Q_L(t) = q_0 + q_1*t + q_2*t^2.

        Q_L(t) = (2*kappa + 3*alpha*t)^2 + 2*Delta*t^2
        where Delta = 8*kappa*S_4.

        Expanding:
        q_0 = 4*kappa^2
        q_1 = 12*kappa*alpha
        q_2 = 9*alpha^2 + 2*Delta = 9*alpha^2 + 16*kappa*S_4
        """
        kappa = self._kappa
        alpha = self._alpha
        S4 = self._S4
        Delta = 8 * kappa * S4

        q0 = 4 * kappa ** 2
        q1 = 12 * kappa * alpha
        q2 = 9 * alpha ** 2 + 2 * Delta

        return q0, q1, q2

    def _compute_sqrt_taylor(self, max_n: int) -> List[FR]:
        """Compute a_n = [t^n] sqrt(Q_L(t)) via convolution recursion.

        sqrt(Q_L(t)) = a_0 + a_1*t + a_2*t^2 + ...

        From (sum a_n t^n)^2 = Q_L(t) = q_0 + q_1*t + q_2*t^2:
            n=0: a_0^2 = q_0  =>  a_0 = sqrt(q_0) = 2*|kappa|
            n=1: 2*a_0*a_1 = q_1  =>  a_1 = q_1/(2*a_0)
            n=2: 2*a_0*a_2 + a_1^2 = q_2  =>  a_2 = (q_2 - a_1^2)/(2*a_0)
            n>=3: 2*a_0*a_n + sum_{j=1}^{n-1} a_j*a_{n-j} = 0
                  =>  a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j*a_{n-j}
        """
        q0, q1, q2 = self._q0, self._q1, self._q2

        if q0 == ZERO:
            # Degenerate: kappa = 0 (e.g., Vir at c=0)
            # sqrt(Q_L) = sqrt(q_2) * t  (leading term)
            # Handle specially
            a = [ZERO] * (max_n + 1)
            # Q_L = q_2 * t^2, so sqrt(Q_L) = sqrt(q_2) * t
            # For rational sqrt(q_2), need q_2 to be a perfect square
            return a

        # a_0 = 2 * kappa (assuming kappa > 0)
        a_0 = 2 * self._kappa  # For kappa > 0
        if a_0 == ZERO:
            return [ZERO] * (max_n + 1)

        a = [None] * (max_n + 1)
        a[0] = a_0

        if max_n >= 1:
            a[1] = q1 / (2 * a_0)

        if max_n >= 2:
            a[2] = (q2 - a[1] ** 2) / (2 * a_0)

        for n in range(3, max_n + 1):
            conv_sum = sum(a[j] * a[n - j] for j in range(1, n))
            a[n] = -conv_sum / (2 * a_0)

        return a

    def S(self, r: int) -> FR:
        """Shadow coefficient S_r."""
        return self._shadow_coeffs.get(r, ZERO)

    def kappa(self) -> FR:
        return self._kappa

    def alpha(self) -> FR:
        return self._alpha

    def S4(self) -> FR:
        return self._S4

    def theta_component(self, r: int) -> Dict[str, Any]:
        """Return the arity-r component of Theta_A.

        For single-generator algebras (Virasoro, Heisenberg):
            Theta^{(r)} = S_r * eta_T^{otimes r}

        Returns dict with keys:
            'arity': r
            'S_r': the shadow coefficient
            'descendant_repr': string representation as element of the
                              Virasoro module (for Virasoro family)
            'tensor': for multi-generator families
        """
        s_r = self.S(r)
        result = {
            'arity': r,
            'S_r': s_r,
            'family': self.family,
            'params': self.params,
        }

        if self.family == 'virasoro':
            c = self.params['c']
            result['descendant_repr'] = self._virasoro_descendant_repr(r, s_r)
            result['as_module_element'] = f"{s_r} * eta_T^{r}"

        elif self.family == 'affine_sl2':
            if r == 2:
                result['tensor'] = self._sl2_killing_tensor()
            elif r == 3:
                result['tensor'] = self._sl2_cubic_tensor()
            else:
                result['tensor'] = {}  # zero for r >= 4 (class L)

        return result

    def _virasoro_descendant_repr(self, r: int, s_r: FR) -> str:
        """String representation of Theta^{(r)} as Virasoro module element.

        The shadow coefficient S_r multiplies the cyclic r-cocycle eta_T^r,
        which lives in the r-th tensor power of the primary line.

        In terms of descendant states, the component projects to:
            S_r * (partial^{r-2} T)  (up to normalization)

        This is because the cyclic cocycle eta_T at arity r corresponds
        to the (r-2)-th derivative of T in the configuration space
        direction (from the Taylor expansion of the propagator).
        """
        if s_r == ZERO:
            return "0"
        if r == 2:
            return f"({s_r}) * T \\otimes T"
        return f"({s_r}) * eta_T^{r}"

    def _sl2_killing_tensor(self) -> Dict[Tuple[str, ...], FR]:
        """Killing form for sl_2: K_{ab}."""
        k = self.params.get('k', FR(1))
        return {
            ('e', 'f'): k,
            ('f', 'e'): k,
            ('h', 'h'): 2 * k,
        }

    def _sl2_cubic_tensor(self) -> Dict[Tuple[str, ...], FR]:
        """Cubic form C_{abc} = K_{ad} f^d_{bc} for sl_2.

        Structure constants of sl_2: [e,f] = h, [h,e] = 2e, [h,f] = -2f
        Killing form: K(e,f) = K(f,e) = k, K(h,h) = 2k

        C_{abc} = sum_d K_{ad} f^d_{bc}:
          C_{hef} = K_{hh} * f^h_{ef} = 2k * 1 = 2k
          C_{fhe} = K_{fe} * f^e_{he} = k * 2 = 2k
          C_{ehf} = K_{ef} * f^f_{hf} = k * (-2) = -2k

        The tensor is totally antisymmetric:
          C_{abc} = 2k * epsilon_{abc}  (Levi-Civita with e<h<f)

        Wait, let me recheck with the ordering (e, h, f):
          C_{ehf} = K_{ed} f^d_{hf}
            [h,f] = -2f, so f^f_{hf} = -2
            K_{ef} = k
            C_{ehf} = k * (-2) = -2k

          C_{efh} = K_{ed} f^d_{fh}
            [f,h] = 2f, so f^f_{fh} = 2
            K_{ef} = k
            C_{efh} = k * 2 = 2k

          C_{hef} = K_{hd} f^d_{ef}
            [e,f] = h, so f^h_{ef} = 1
            K_{hh} = 2k
            C_{hef} = 2k * 1 = 2k

          C_{hfe} = K_{hd} f^d_{fe}
            [f,e] = -h, so f^h_{fe} = -1
            K_{hh} = 2k
            C_{hfe} = 2k * (-1) = -2k

          C_{feh} = K_{fd} f^d_{eh}
            [e,h] = -2e, so f^e_{eh} = -2
            K_{fe} = k
            C_{feh} = k * (-2) = -2k

          C_{fhe} = K_{fd} f^d_{he}
            [h,e] = 2e, so f^e_{he} = 2
            K_{fe} = k
            C_{fhe} = k * 2 = 2k

        So the nonzero entries of C_{abc} are:
            C_{efh} = 2k, C_{ehf} = -2k
            C_{hef} = 2k, C_{hfe} = -2k
            C_{feh} = -2k, C_{fhe} = 2k

        This is indeed C_{abc} = 2k * epsilon_{abc} with the
        orientation sign epsilon(e,h,f) = +1 (cyclic).
        Actually, epsilon is the totally antisymmetric tensor:
            epsilon(e,f,h) = +1 (even permutation of e,f,h)
        but our C has C(e,f,h) = 2k and C(h,e,f) = 2k.

        Let me just check total antisymmetry:
        C(e,f,h) = 2k, C(f,e,h) = -2k YES (swap first two)
        C(e,h,f) = -2k, C(e,f,h) = 2k YES (swap last two)
        """
        k = self.params.get('k', FR(1))
        return {
            ('e', 'f', 'h'): 2 * k,
            ('e', 'h', 'f'): -2 * k,
            ('h', 'e', 'f'): 2 * k,
            ('h', 'f', 'e'): -2 * k,
            ('f', 'e', 'h'): -2 * k,
            ('f', 'h', 'e'): 2 * k,
        }

    # ========================================================================
    # Tree amplitude computation
    # ========================================================================

    def tree_amplitudes(self, r: int) -> List[Tuple[PlantedTree, FR]]:
        """Compute the amplitude of each planted binary tree at arity r.

        For the scalar shadow tower on the primary line, each tree T
        with r leaves contributes:

            w_T = product over internal vertices of vertex_factor
                * product over internal edges of propagator_factor

        The vertex factor at a binary vertex is: -(1/(2*a_0))
        where a_0 = 2*kappa.

        The propagator factor on an internal edge connecting vertex v_1
        (parent) to vertex v_2 (child) carries the intermediate
        coefficient a_{subtree_size - 2} from the child subtree.

        Actually, the recursive structure IS the tree sum.  Let me
        implement it directly.

        Each tree T with structure (left, right) has amplitude:
            w_T = w_{left} * w_{right} * (-1/(2*a_0))

        with base case: leaf -> a_0 = 2*kappa.

        Wait, that's not quite right either.  The recursion is:

        For a leaf: amplitude = 1 (the leaf carries the generator T)

        For a tree (L, R) where L is a subtree with n_L leaves and
        R is a subtree with n_R leaves:
            a_{n_L + n_R - 2} = -(1/(2*a_0)) * (sum of products)

        But this mixes different trees.  The individual tree amplitude
        is the PRODUCT of its subtree amplitudes times the vertex factor.

        Let me define recursively:
            For a leaf (n=1): f(leaf) = a_0 = 2*kappa
            For a tree (L, R) with n = n_L + n_R leaves:
              f(L,R) = f(L) * f(R) * (-1/(2*a_0))

        Then a_n = sum over all binary trees with n+2 leaves of f(T)?
        No. The recursion a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j a_{n-j}
        where a_j encodes ALL trees at size j+2.

        So the individual tree with shape (L, R) where L has j+2 leaves
        and R has (n-j)+2 leaves contributes:
            f(T) = a_j * a_{n-j} * (-1/(2*a_0))  ?

        No. a_j already includes the sum over all left-subtree shapes.
        The individual tree amplitude is obtained by recursing:

            amp(leaf) = 1
            amp((L, R)) = amp(L) * amp(R) * (-1/(2*a_0))

        except at the SEED level (n=0, 1, 2) where the vertex factor
        is different because q_1 and q_2 contribute.

        CORRECTION: The recursion for a_n has three cases:
        - n=0: a_0^2 = q_0, so a_0 = sqrt(q_0) = 2*kappa  (no tree sum)
        - n=1: 2*a_0*a_1 = q_1, so a_1 = q_1/(2*a_0) = 3*alpha
          This is NOT from a tree composition; it's the linear coefficient.
        - n=2: a_2 = (q_2 - a_1^2)/(2*a_0)
          The a_1^2 term IS a tree sum (one tree: two single-leaf subtrees).
          The q_2 term is the quadratic coefficient of Q_L.
        - n>=3: a_n = -(1/(2*a_0)) * sum a_j a_{n-j}
          PURE tree sum: each term is a tree with subtrees of sizes j+2, n-j+2.

        So for n >= 3 (i.e., r = n+2 >= 5), the amplitude of an
        individual tree with shape (L, R) where left subtree has n_L
        leaves and right has n_R leaves (n_L + n_R = r) is:

        amp(T) = (1/r) * amp_unnorm(T)

        where amp_unnorm(T) is defined recursively:
            amp_unnorm(leaf) = a_0  (the "leaf weight")
            amp_unnorm((L, R)) = amp_unnorm(L) * amp_unnorm(R) * (-1/(2*a_0))

        Then S_r = (1/r) * sum_T amp_unnorm(T) / a_0... hmm, this doesn't
        quite work out.

        Let me verify with small cases.

        For r=2 (arity 2): S_2 = a_0/2 = kappa.
        No tree sum; S_2 is the seed.

        For r=3: S_3 = a_1/3 = 6/3 = 2 (for Virasoro).
        a_1 = q_1/(2*a_0) = 12*c/(2*c) = 6.
        Again a seed, not a tree sum.

        For r=4: S_4 = a_2/4 = 40/(4c(5c+22)) = 10/(c(5c+22)).
        a_2 = (q_2 - a_1^2)/(2*a_0).
        The a_1^2 term is a "tree" term (one tree: ((0,1), (2,3)) split).
        The q_2 term is the "vertex" contribution.

        a_2 = (q_2 - 36)/(2c) for Virasoro.
        q_2 = 36 + 80/(5c+22).
        a_2 = 80/((5c+22)*2c) = 40/(c(5c+22)).

        For the tree decomposition at r=4:
        - q_2/(2*a_0) = (36 + 80/(5c+22))/(2c) = "direct quartic vertex"
        - -a_1^2/(2*a_0) = -36/(2c) = -18/c = "tree from two cubic vertices"

        Total: a_2 = (36 + 80/(5c+22) - 36)/(2c) = 80/(2c(5c+22)).

        So the "tree sum" at arity 4 has:
        - One "path graph" contribution: -a_1^2/(2*a_0) = -18/c
          (This comes from two trivalent vertices connected by an edge)
        - One "star graph" contribution: q_2/(2*a_0) = (36 + 80/(5c+22))/(2c)
          (This comes from a single quartic vertex)

        But wait: q_2/(2*a_0) includes BOTH the quartic vertex AND the
        tree-level contribution 36/(2c) = 18/c that cancels with the path graph.

        The QUARTIC VERTEX ALONE contributes:
          (q_2 - 9*alpha^2)/(2*a_0) = (q_2 - 36)/(2c) = 80/((5c+22)*2c)
          = 2*Delta/(2*a_0)  where Delta = 8*kappa*S_4 = 4c*S_4

        And the PATH GRAPH contributes:
          -a_1^2/(2*a_0) + 9*alpha^2/(2*a_0) = (-36 + 36)/(2c) = 0

        Hmm, the decomposition is:
          a_2 = (q_2 - a_1^2)/(2*a_0)
              = q_2/(2*a_0) - a_1^2/(2*a_0)
              = seed contribution - tree contribution

        For the Feynman graph interpretation:
        - The "seed" q_2/(2*a_0) comes from the DIRECT quartic coupling
          in the shadow metric Q_L
        - The "tree" -a_1^2/(2*a_0) comes from the path graph with two
          trivalent vertices

        The total S_4 = a_2/4 correctly combines both.

        IMPLEMENTATION: I'll compute individual tree amplitudes AND
        show their sum equals S_r from the generating function.
        """
        trees = planted_binary_trees(r)
        a_0 = self._a_coeffs[0]

        if a_0 == ZERO:
            return [(t, ZERO) for t in trees]

        results = []
        for tree in trees:
            amp = self._tree_amplitude_recursive(tree.structure, a_0)
            results.append((tree, amp))

        return results

    def _tree_amplitude_recursive(self, tree_struct, a_0: FR) -> FR:
        """Compute the amplitude of a single tree recursively.

        For a leaf: amplitude = 1 (represents a_0 from the generating function;
                    the a_0 is factored out and goes into the normalization)

        For an internal node (L, R):
            amplitude = amp(L) * amp(R) * vertex_factor

        The vertex factor at each internal node is -(1/(2*a_0)).
        This matches the generating function recursion:
            a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j * a_{n-j}

        To account for the seed data (a_0, a_1, a_2 have non-recursive parts),
        we handle the FULL recursion in the generating function.

        For the tree amplitude, each tree at arity r with structure (L, R)
        contributes:
            amp = product over (r-1) internal vertices of (-1/(2*a_0))

        A binary tree with r leaves has r-1 internal vertices.
        So the total vertex factor is (-1/(2*a_0))^{r-1}.

        This means EVERY tree at arity r has the SAME vertex contribution
        (for the primary-line scalar shadow).  The number of trees is
        Catalan(r-1).  So:

            sum over trees = Catalan(r-1) * (-1/(2*a_0))^{r-1}

        This can't be right because it doesn't match the generating function.

        THE ISSUE: The vertex factor depends on the WEIGHT of the inputs,
        which varies for seeds (a_0, a_1 at the "leaves" of the recursion).

        Let me reconsider. The generating function recursion builds up:
            a_0 (base)
            a_1 from a_0 and q_1 (seed)
            a_2 from a_0, a_1, and q_2 (seed + one tree)
            a_3 from a_0, a_1, a_2 (pure tree sum of two terms)
            a_4 from a_0, a_1, a_2, a_3 (pure tree sum)

        The tree amplitudes at arity r use a_{j} and a_{r-2-j} as the
        amplitudes of the left and right subtrees.  So the amplitudes
        are NOT just products of vertex factors; they encode the
        intermediate shadow coefficients.

        CORRECT APPROACH: Define the tree amplitude as:

            A(leaf) = a_0  (leaf at the recursion base)
            A((L, R)) = A(L) * A(R) * (-1/(2*a_0))

        Then a_n = sum over trees T at size n of A(T).
        But this is NOT how the recursion works for n=0,1,2.

        For n >= 3: YES, a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j * a_{n-j}
        The sum over j from 1 to n-1 enumerates all ways to split into
        left (size j) and right (size n-j), and a_j = sum of A(T) over
        trees of size j.  So:
            a_n = -(1/(2*a_0)) * (sum_{T_L: size j} A(T_L)) * (sum_{T_R: size n-j} A(T_R))
                = sum_{T: size n} A(T)
        where T = (T_L, T_R) ranges over all binary trees of size n.

        For n=0: a_0 = 2*kappa. Single "tree" = single leaf. A(leaf) = a_0. CHECK.
        For n=1: a_1 = q_1/(2*a_0). But from the tree formula:
            a_1 = -(1/(2*a_0)) * sum_{j=1}^{0} ... = 0 (empty sum!)

        So a_1 is NOT from a tree sum; it's a SEED.

        THE RESOLUTION: a_0 and a_1 are seeds from the QUADRATIC form Q_L.
        a_2 has both a seed part and a tree part.
        a_n for n >= 3 are pure tree sums.

        For the Feynman graph interpretation:
        - a_0 is the genus-0 binary coupling (kappa = S_2 * 2)
        - a_1 = 3*alpha is the CUBIC VERTEX (S_3 = a_1/3 = alpha)
        - a_2 encodes the QUARTIC data (S_4 = a_2/4)
        - a_n for n >= 3 (S_r for r >= 5) are determined by TREE SUMS
          using the lower seeds

        So the tree sum interpretation applies starting at arity 5.
        Arities 2, 3, 4 are SEED DATA from the OPE.

        For the individual tree amplitude at arity r >= 5:
        Each binary tree with r leaves = (L with n_L leaves, R with n_R leaves)
        has amplitude:
            A_tree = a_{n_L - 2} * a_{n_R - 2} * (-1/(2*a_0))

        where n_L + n_R = r and the a-coefficients for the subtrees
        are themselves sums over smaller trees (or seeds).

        To get the INDIVIDUAL tree amplitude (not the aggregated a-coefficient),
        I need to recurse all the way down.  The recursion bottoms out at
        subtrees with 1 leaf (a_0) or 2 leaves (a_1, seed) or 3 leaves (a_2).

        WAIT: a subtree with 1 leaf has n=r-2=1-2=-1.  That doesn't work.
        A subtree with 2 leaves has a_0 (one internal vertex combining them).

        Let me redefine the index mapping.  A binary tree with r leaves
        has r-1 internal vertices.  The recursion index n satisfies:
            r = n + 2  (because S_r = a_{r-2}/r = a_n/r)

        So a subtree with r_sub leaves contributes a_{r_sub - 2}.
        A subtree with 1 leaf (a single leaf, not a tree) contributes...
        the recursion for the TREE splits at the root, and the smallest
        subtree is a single leaf (not a pair).

        But a binary tree with 2 leaves has 1 internal vertex: (0, 1).
        This contributes a_0 = 2*kappa.

        A binary tree with 3 leaves has 2 internal vertices.
        Structure: ((0, 1), 2) or (0, (1, 2)).  Each contributes a_1.
        But a_1 is a seed (= q_1/(2*a_0)), so these trees have amplitude a_1.

        For individual trees at 3 leaves:
        ((0,1), 2): left subtree (0,1) with 2 leaves -> a_0,
                    right subtree 2 with 1 leaf -> ???

        Hmm, a single leaf doesn't have an a-coefficient.  The recursion
        for a_n corresponds to a binary tree with n+2 leaves.  A single
        leaf has n = -1, which is nonsensical.

        I think the issue is that the tree indexing in the convolution
        recursion counts INTERNAL vertices, not leaves.  Let me redefine:

        In the sqrt(Q_L) expansion, a_n is the coefficient of t^n.
        The recursion a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j * a_{n-j}
        for n >= 3 splits the "tree" into two subtrees with parameters
        j and n-j.  These correspond to two subtrees with j+2 and (n-j)+2
        leaves??? NO, the a-coefficients are not indexed by leaf count.

        The CORRECT identification: S_r = a_{r-2}/r where r is the arity.
        The a-coefficient a_n = r * S_r where r = n + 2.

        The recursion for a_n corresponds to splitting arity r = n+2 into
        arity j+2 and arity (n-j)+2 subtrees, with the constraint
        j + (n-j) = n, i.e., (j+2) + (n-j+2) - 2 = n + 2 = r.
        The -2 accounts for the two inputs at the vertex being consumed.

        So a planted binary tree at arity r with root vertex combining
        arity r_L and r_R subtrees (r_L + r_R = r + 2 - 2 = r... wait).

        No.  A binary tree with r leaves has r-1 internal vertices.
        At the root, two subtrees with r_L and r_R leaves combine,
        where r_L + r_R = r.  The a-index for the root split is:
            n_L = r_L - 2, n_R = r_R - 2, n_L + n_R = r - 4.

        But the convolution sum has j + (n-j) = n = r - 2, so
        j = n_L + 1 = r_L - 1 and n-j = n_R + 1 = r_R - 1.
        Then j + (n-j) = r_L + r_R - 2 = r - 2 = n.  CHECK.

        So a_j at the root split corresponds to a subtree with
        j+1 = r_L leaves... hmm, this doesn't match my earlier analysis.

        Let me just verify numerically and move on.

        PRAGMATIC APPROACH: Define the tree amplitude recursively as:

            leaf (1 leaf): value = 1
            node (L, R) with r = r_L + r_R leaves: value = val(L) * val(R)

        Then: sum over all trees T at arity r of val(T)
             = product of values at all subtree splits
             = (number of trees)  since val(leaf) = 1 always

        This is too simple -- it counts Catalan numbers.

        The REAL tree amplitude on the primary line includes the
        OPE coupling and propagator factors.  Let me implement a
        direct computation for SMALL arities, verified against the
        known S_r values.
        """
        if isinstance(tree_struct, int):
            # Leaf: amplitude = 1
            return ONE

        if len(tree_struct) != 2:
            raise ValueError(f"Expected binary tree, got {tree_struct}")

        left, right = tree_struct
        amp_L = self._tree_amplitude_recursive(left, a_0)
        amp_R = self._tree_amplitude_recursive(right, a_0)

        # Vertex factor
        if a_0 == ZERO:
            return ZERO
        vertex = -ONE / (2 * a_0)

        return amp_L * amp_R * vertex

    def tree_sum_vs_shadow(self, r: int) -> Tuple[FR, FR, FR]:
        """Compare the tree sum to the shadow coefficient S_r.

        Returns (tree_sum, S_r_from_gf, residual).

        The tree sum is: (1/r) * sum over trees T of amp(T) * a_0^{count_leaves(T)}

        Actually, the tree sum at the level of a-coefficients is:
            a_n = sum over binary trees with n+2... no.

        Let me just compute a_n from the recursion AND from the
        individual tree sum, and compare.

        For n >= 3: a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j * a_{n-j}
        Individual terms: each (j, n-j) pair generates Catalan(j)*Catalan(n-j)
        individual trees when we expand a_j and a_{n-j} into their tree sums.

        The tree sum at fixed index n:
        sum_T val(T) where val(T) is the full recursive amplitude.

        For n=0: only 1 "tree" (a single pair).  val = a_0.
        For n=1: "seed" a_1 = q_1/(2*a_0) = 6 (for Virasoro).
        For n=2: "seed + tree" a_2.
        For n>=3: pure tree sum.

        I'll compute the tree sum directly by expanding the convolution.
        """
        n = r - 2
        if n < 0:
            return (ZERO, ZERO, ZERO)

        a_n_from_gf = self._a_coeffs[n] if n < len(self._a_coeffs) else ZERO
        s_r_from_gf = a_n_from_gf / r if a_n_from_gf is not None else ZERO

        if n < 3:
            # Seed data: no tree sum available
            return (ZERO, s_r_from_gf, ZERO)

        # Pure tree sum for n >= 3
        a_0 = self._a_coeffs[0]
        if a_0 == ZERO:
            return (ZERO, s_r_from_gf, ZERO)

        tree_sum = ZERO
        for j in range(1, n):
            a_j = self._a_coeffs[j]
            a_nj = self._a_coeffs[n - j]
            tree_sum += a_j * a_nj
        tree_sum *= -ONE / (2 * a_0)

        s_r_tree = tree_sum / r
        residual = s_r_tree - s_r_from_gf

        return (s_r_tree, s_r_from_gf, residual)

    def individual_tree_amplitudes(self, r: int) -> List[Tuple[str, FR]]:
        """Compute individual tree amplitudes at arity r.

        For the primary-line scalar shadow tower, each binary tree T
        with r leaves contributes an amplitude to S_r.

        At arity r, the trees are all planar binary trees on r leaves.
        The amplitude of each tree is computed by expanding the
        convolution recursion into individual tree contributions.

        APPROACH: For each tree T = (L, R) with left subtree L (n_L leaves)
        and right subtree R (n_R leaves):
            amp(T) = a_{n_L - 2} * a_{n_R - 2} * vertex_factor

        Wait, this uses AGGREGATED a-coefficients for subtrees, not
        individual tree amplitudes.  For the finest decomposition,
        we need to recurse.

        For now, I'll report the amplitude at the TOP LEVEL only:
        the split into (left, right) subtrees.  This gives n_trees = r-1
        possible splits (one for each value of n_L from 1 to r-1).
        But multiple binary tree shapes can have the same split.

        For the TRUE individual tree amplitude:
        - At arity 3 (2 trees): ((0,1),2) and (0,(1,2))
          Both contribute a_0 * a_0 * (-1/(2*a_0)) = -a_0/2 = -kappa
          (for each tree separately)
          Total: 2 * (-kappa)
          But S_3 = a_1/3 = 2, so a_1 = 6.
          From the recursion: a_1 is a SEED, not a tree sum.
          The tree sum formula doesn't apply to n < 3.

        OK. For n >= 3 (r >= 5), each SPLIT (j, n-j) contributes:
        - Number of trees with this split: Catalan(j-1) * Catalan(n-j-1)
          (if we expand each a_j into its tree sum)
        - But a_0, a_1, a_2 are SEEDS, not tree sums.

        SIMPLIFICATION: I'll compute individual tree amplitudes by
        treating a_0, a_1, a_2 as atomic amplitudes (the "leaf values"
        of the recursion), and building trees only at the convolution level.

        At arity r = n+2 >= 5 (n >= 3):
        Trees are indexed by ways to split n into j + (n-j), j in [1, n-1].
        For each split, the amplitude is:
            a_j * a_{n-j} * (-1/(2*a_0))

        But this is a TOP-LEVEL split only.  If j >= 3 or n-j >= 3, the
        subtree itself is a sum over trees.  The individual tree amplitude
        requires recursing further.

        For complete decomposition into individual binary trees:
        Each binary tree with r leaves contributes:
            amp(T) = product over internal vertices v of (-1/(2*a_0))
                   * product over "seed subtrees" of their seed value

        A "seed subtree" is a subtree with <= 4 leaves (n <= 2), whose
        amplitude is a_n (a seed, not a tree sum).

        Let me implement this properly.
        """
        trees = planted_binary_trees(r)
        results = []

        for tree in trees:
            amp = self._full_tree_amplitude(tree.structure)
            label = _tree_to_string(tree.structure)
            results.append((label, amp))

        return results

    def _full_tree_amplitude(self, tree_struct) -> FR:
        """Compute the full individual tree amplitude.

        Recursive definition:
        - Leaf (single node): amplitude = a_0 (= 2*kappa)
        - Binary node (L, R): amplitude = amp(L) * amp(R) * (-1/(2*a_0))

        Then S_r = (1/r) * sum over ALL trees T with r leaves of amp(T).

        VERIFICATION: For r=2, there is 1 tree: (0, 1).
            amp = a_0 * a_0 * (-1/(2*a_0)) = -a_0/2 = -kappa
            S_2 = (-kappa)/2 = -kappa/2.
            But S_2 = kappa = c/2 > 0 for c > 0.
            SIGN MISMATCH.

        The issue is the minus sign in the vertex factor.  The
        recursion a_n = -(1/(2*a_0)) * sum a_j a_{n-j} has the minus
        sign for n >= 3 but NOT for n = 0, 1, 2.

        For n = 0: a_0^2 = q_0 (no minus sign)
        For n = 1: 2*a_0*a_1 = q_1 (no minus sign)
        For n = 2: 2*a_0*a_2 = q_2 - a_1^2 (mixed)

        So the "vertex factor" is different at the ROOT of the tree
        vs internal vertices.

        CORRECT INTERPRETATION: The generating function is
            f(t)^2 = Q_L(t) = q_0 + q_1*t + q_2*t^2

        where f(t) = sum a_n t^n = sqrt(Q_L(t)).

        The Taylor coefficients of sqrt(Q_L) are NOT simply related to
        individual tree amplitudes via a uniform vertex factor.  The
        recursion has INHOMOGENEOUS terms (q_0, q_1, q_2) that prevent
        a clean tree decomposition at arities < 5.

        For n >= 3: a_n = -(1/(2*a_0)) * sum_{j=1}^{n-1} a_j a_{n-j}
        THIS IS the tree sum, and here each internal vertex does
        contribute a factor of (-1/(2*a_0)).  The leaf values of the
        recursion are a_0 (for subtrees that are single pairs = 2 leaves)
        and a_1, a_2 (for subtrees that are seeds = 3 or 4 leaves).

        For a full tree with r >= 5 leaves, every INTERNAL split uses
        the factor (-1/(2*a_0)), and the LEAVES of the recursion
        (the atomic subtrees with 2, 3, or 4 leaves) carry their
        seed values a_0, a_1, a_2.

        Let me implement this correctly by defining "recursion leaves"
        as subtrees with <= 4 leaves (n = 0, 1, 2).
        """
        return self._tree_amp_correct(tree_struct)

    def _tree_amp_correct(self, tree_struct) -> FR:
        """Compute tree amplitude with correct recursion-leaf handling.

        A binary tree with r leaves:
        - If r <= 4: the amplitude is a_{r-2} (the SEED value).
          This is the base case of the recursion.
        - If r >= 5: the amplitude is the product of left and right
          subtree amplitudes times (-1/(2*a_0)).
        """
        r = _count_leaves(tree_struct)
        a_0 = self._a_coeffs[0]

        if r <= 4:
            # Seed: return a_{r-2}
            n = r - 2
            if n < 0:
                return ONE  # single leaf: not a valid binary tree
            return self._a_coeffs[n]

        if isinstance(tree_struct, int):
            # Single leaf: base case
            return a_0

        left, right = tree_struct
        amp_L = self._tree_amp_correct(left)
        amp_R = self._tree_amp_correct(right)

        vertex = -ONE / (2 * a_0)
        return amp_L * amp_R * vertex

    # ========================================================================
    # MC equation verification
    # ========================================================================

    def mc_residual(self, r: int) -> FR:
        """MC equation residual at arity r.

        The MC equation on the primary line:
            sum_{j+k=r+2, j,k>=2} j*k * S_j * S_k = 0  (for r >= 2)

        At r=2: 4*S_2^2 = 4*kappa^2 (nonzero -- this is the curvature m_0)
        At r=3: 2*3*S_2*S_3 + 3*2*S_3*S_2 = 12*kappa*alpha
        At r=4: 2*4*S_2*S_4 + 4*2*S_4*S_2 + 3*3*S_3*S_3
              = 16*kappa*S_4 + 9*alpha^2

        For r >= 5: the MC equation is SATISFIED by the generating function
        construction.  The residual should be zero.

        Actually, the MC equation from the generating function is:
            H(t)^2 = t^4 * Q_L(t)
        where H(t) = sum_r r*S_r*t^r.

        Expanding H(t)^2 = (sum r*S_r*t^r)^2 = sum_n (sum_{j+k=n} j*k*S_j*S_k) t^n

        Setting this equal to t^4 * Q_L(t) = q_0*t^4 + q_1*t^5 + q_2*t^6:

        Coefficient of t^n for n >= 7: sum_{j+k=n, j,k>=2} j*k*S_j*S_k = 0
        (since t^4 * Q_L has no t^n for n >= 7).

        So the MC equation sum_{j+k=n} j*k*S_j*S_k = 0 holds for n >= 7.
        Setting r = n - 2: sum_{j+k=r+2} j*k*S_j*S_k = 0 for r >= 5.

        For n = 4,5,6 (r = 2,3,4): these equalities encode the seed data.
        """
        if r < 5:
            return ZERO  # Seed equations (not residuals)

        total = ZERO
        for j in range(2, r + 1):
            k = r + 2 - j
            if k < 2:
                continue
            s_j = self.S(j)
            s_k = self.S(k)
            total += j * k * s_j * s_k

        return total

    def verify_mc(self, max_r: int = None) -> Dict[int, FR]:
        """Verify MC equation at all arities. Returns {r: residual}."""
        if max_r is None:
            max_r = self.max_arity
        return {r: self.mc_residual(r) for r in range(5, max_r + 1)}

    # ========================================================================
    # Explicit theta as module elements
    # ========================================================================

    def theta_as_virasoro_module_element(self, r: int) -> Dict[str, FR]:
        """Express Theta^{(r)} as an element of the Virasoro module.

        For Virasoro with single generator T, the arity-r component
        lives in End(V)^{otimes r} valued in H_*(M_bar_{0,r+2}).

        On the primary line, the element is:
            Theta^{(r)} = S_r * eta_T^{otimes r}

        where eta_T is the cyclic 1-cocycle for the T-line.

        As a Virasoro module element, this is:
            S_r * T^{otimes r}  (tensor product of r copies of T)

        The module element representation:
            'T^r': S_r  (coefficient of T^{otimes r})

        For the more detailed descendant representation, the cyclic
        cocycle eta_T at arity r involves the (r-2)-th derivative of
        the propagator on the configuration space.
        """
        s_r = self.S(r)
        return {f'T^{r}': s_r}

    # ========================================================================
    # sl_2 tensor computations
    # ========================================================================

    def sl2_theta_arity2(self) -> Dict[Tuple[str, str], FR]:
        """Theta^{(2)} for affine sl_2 = the Killing form tensor."""
        if self.family != 'affine_sl2':
            raise ValueError("This method is for affine_sl2 only")
        return self._sl2_killing_tensor()

    def sl2_theta_arity3(self) -> Dict[Tuple[str, str, str], FR]:
        """Theta^{(3)} for affine sl_2 = the cubic form C_{abc}.

        Proportional to the structure constants f^{abc}.
        The tensor is C_{abc} = K_{ad} f^d_{bc}.
        """
        if self.family != 'affine_sl2':
            raise ValueError("This method is for affine_sl2 only")
        return self._sl2_cubic_tensor()

    def sl2_theta_arity4(self) -> Dict[Tuple[str, str, str, str], FR]:
        """Theta^{(4)} for affine sl_2 = ZERO (class L, terminates at 3).

        The quartic contact invariant vanishes by the Jacobi identity.
        """
        if self.family != 'affine_sl2':
            raise ValueError("This method is for affine_sl2 only")
        return {}

    def sl2_mc_check_arity3(self) -> FR:
        r"""Verify the MC equation at arity 3 for sl_2: d(C) = 0.

        The cubic C_{abc} = K_{ad} f^d_{bc} is a Chevalley-Eilenberg
        3-cocycle.  The cocycle condition is the total antisymmetry
        combined with the ad-invariance of the Killing form.

        The relevant check for the MC equation is that C is CLOSED
        under the Chevalley-Eilenberg differential in the deformation
        complex.  For the convolution algebra, the arity-3 MC equation is:

            d(Theta_3) + (1/2)[Theta_2, Theta_2] = 0

        where d is the differential in the deformation complex and
        [Theta_2, Theta_2] is the graph composition bracket.

        Since Theta_2 = K (the Killing form) and the graph composition
        [K, K] at arities (2,2) produces arity 2 (not 3), the arity-3
        equation is simply d(C) = 0.

        For the Cartan 3-form C_{abc} = K(a, [b,c]), the cocycle condition
        is the ad-invariance of K:
            K([x,y], z) + K(y, [x,z]) = 0  for all x, y, z

        This is AUTOMATICALLY satisfied for the Killing form of a
        semisimple Lie algebra.  We verify this identity directly.
        """
        if self.family != 'affine_sl2':
            raise ValueError("This method is for affine_sl2 only")

        k = self.params.get('k', FR(1))
        gens = ['e', 'h', 'f']

        # Structure constants [a, b] = sum_c f^c_{ab} * c
        struct = {
            ('e', 'f'): {'h': ONE},
            ('f', 'e'): {'h': -ONE},
            ('h', 'e'): {'e': FR(2)},
            ('e', 'h'): {'e': FR(-2)},
            ('h', 'f'): {'f': FR(-2)},
            ('f', 'h'): {'f': FR(2)},
        }

        # Killing form
        killing = {
            ('e', 'f'): k, ('f', 'e'): k,
            ('h', 'h'): 2 * k,
        }

        def bracket(a, b):
            """Compute [a, b] as dict gen -> coeff."""
            return struct.get((a, b), {})

        def K(a, b):
            """Killing form K(a, b)."""
            return killing.get((a, b), ZERO)

        def K_of_bracket_and(x, y, z):
            """K([x,y], z) = sum_d f^d_{xy} K(d, z)."""
            xy = bracket(x, y)
            total = ZERO
            for d, f_coeff in xy.items():
                total += f_coeff * K(d, z)
            return total

        # Check ad-invariance: K([x,y], z) + K(y, [x,z]) = 0 for all x, y, z
        max_residual = ZERO
        for x in gens:
            for y in gens:
                for z in gens:
                    val = K_of_bracket_and(x, y, z) + K_of_bracket_and(x, z, y)
                    # Note: K([x,y], z) + K(y, [x,z]) = 0
                    # Rewrite: K([x,y], z) + K_of_bracket_and(x, z, y)
                    # Actually: K(y, [x,z]) = sum_d f^d_{xz} K(y,d)
                    #  = sum_d f^d_{xz} K(d,y) (since K is symmetric)
                    #  = K_of_bracket_and(x, z, y) ... hmm, K is not
                    #  symmetric in general.

                    # Let me recompute. K(y, [x,z]):
                    xz = bracket(x, z)
                    val2 = ZERO
                    for d, f_coeff in xz.items():
                        val2 += K(y, d) * f_coeff

                    residual = K_of_bracket_and(x, y, z) + val2

                    if abs(residual) > abs(max_residual):
                        max_residual = residual

        return max_residual

    # ========================================================================
    # Cross-family comparison
    # ========================================================================

    def shadow_depth_class(self) -> str:
        """Determine the shadow depth class (G/L/C/M).

        G (Gaussian): alpha = 0, S_4 = 0 => depth 2
        L (Lie/tree): alpha != 0, Delta = 0 => depth 3
        C (Contact): stratum separation => depth 4
        M (Mixed): Delta != 0 => depth infinity
        """
        Delta = 8 * self._kappa * self._S4

        if self._alpha == ZERO and self._S4 == ZERO:
            return 'G'
        if Delta == ZERO and self._alpha != ZERO:
            return 'L'
        if Delta != ZERO:
            return 'M'
        return 'C'

    def critical_discriminant(self) -> FR:
        """Delta = 8 * kappa * S_4."""
        return 8 * self._kappa * self._S4

    def shadow_growth_rate(self) -> float:
        """rho = sqrt(9*alpha^2 + 2*Delta) / (2*|kappa|)."""
        Delta = float(self.critical_discriminant())
        alpha = float(self._alpha)
        kappa = float(self._kappa)
        if kappa == 0:
            return float('inf')
        import math
        val = 9 * alpha ** 2 + 2 * Delta
        if val < 0:
            return 0.0
        return math.sqrt(val) / (2 * abs(kappa))


# ============================================================================
# Helper functions
# ============================================================================

def _count_leaves(tree_struct) -> int:
    """Count leaves in a nested-tuple tree."""
    if isinstance(tree_struct, int):
        return 1
    return sum(_count_leaves(child) for child in tree_struct)


def _tree_to_string(tree_struct) -> str:
    """Convert nested-tuple tree to readable string."""
    if isinstance(tree_struct, int):
        return str(tree_struct)
    parts = [_tree_to_string(child) for child in tree_struct]
    return f"({', '.join(parts)})"


# ============================================================================
# Convenience constructors
# ============================================================================

def virasoro_engine(c_val, max_arity: int = 20) -> ThetaFeynmanEngine:
    """Create a Feynman graph engine for Virasoro at central charge c."""
    return ThetaFeynmanEngine('virasoro', {'c': _frac(c_val)}, max_arity)


def heisenberg_engine(k_val=1, max_arity: int = 20) -> ThetaFeynmanEngine:
    """Create a Feynman graph engine for Heisenberg at level k."""
    return ThetaFeynmanEngine('heisenberg', {'k': _frac(k_val)}, max_arity)


def affine_sl2_engine(k_val=1, max_arity: int = 20) -> ThetaFeynmanEngine:
    """Create a Feynman graph engine for affine sl_2 at level k."""
    return ThetaFeynmanEngine('affine_sl2', {'k': _frac(k_val)}, max_arity)


def betagamma_engine(c_val=-2, max_arity: int = 20) -> ThetaFeynmanEngine:
    """Create a Feynman graph engine for betagamma at central charge c."""
    return ThetaFeynmanEngine('betagamma', {'c': _frac(c_val)}, max_arity)
