r"""Verlinde formula arithmetic and shadow connections.

Arithmetic structure of the Verlinde formula for affine Lie algebras
and its interplay with the shadow obstruction tower.

MATHEMATICAL FRAMEWORK
======================

The Verlinde formula for sl_2 at level k:

    N_{ij}^m = sum_l S_{il} S_{jl} S_{ml}^* / S_{0l}

where S_{jl} = sqrt(2/(k+2)) sin(pi(j+1)(l+1)/(k+2)), produces
NON-NEGATIVE INTEGER fusion coefficients.  This integrality is a
deep arithmetic fact: the Verlinde formula computes dimensions of
spaces of conformal blocks (Beauville-Laszlo, Tsuchiya-Ueno-Yamada).

ARITHMETIC CONTENT:

1. NUMBER FIELDS FROM S-MATRIX:
   The S-matrix entries for sl_2 at level k involve sin(pi*m/(k+2)).
   At prime levels k = p-2, the splitting field is the maximal real
   subfield Q(cos(2pi/p)) = Q(zeta_p)^+ of degree (p-1)/2 over Q.

2. QUANTUM DIMENSION ARITHMETIC:
   d_j = sin((j+1)pi/(k+2)) / sin(pi/(k+2)) are algebraic numbers
   with minimal polynomials of degree <= (k+1)/2.  The Galois group
   acts by d_j -> d_{sigma(j)} where sigma permutes the representations.

3. SHADOW-VERLINDE BRIDGE:
   kappa(sl_2_k) = 3(k+2)/4 is the shadow's leading invariant.
   The total quantum dimension D^2 = (k+2)/(2 sin^2(pi/(k+2))).
   The ratio kappa/D^2 = (3/2) sin^2(pi/(k+2)) is a transcendental
   function of k that approaches 3pi^2/(2(k+2)^2) for large k.

4. ARITHMETIC DEPTH:
   The arithmetic depth d_arith measures the complexity of the
   number field generated by the shadow data.  For affine sl_2,
   the shadow coefficients are RATIONAL (d_arith = 0), while the
   Verlinde/S-matrix data generates Q(zeta_{k+2})^+.  The gap
   between d_arith(shadow) = 0 and the Verlinde field degree
   is the "arithmetic gap" of the Verlinde formula.

5. FUSION RING STRUCTURE:
   R_k = Z[V_0,...,V_k] is commutative, associative, semisimple.
   Characters: chi_l(V_j) = S_{jl}/S_{0l} = d_j evaluated at
   the l-th root of unity.  The fusion ring is isomorphic to
   Z[x]/(U_{k+1}(x/2)) where U_n is the Chebyshev polynomial
   of the second kind.

Manuscript references:
    thm:modular-characteristic (higher_genus_modular_koszul.tex)
    thm:shadow-cohft (higher_genus_modular_koszul.tex)
    sec:concordance-koszulness-programme (concordance.tex)

Conventions:
    - Representations labeled j = 0, 1, ..., k (= twice the spin) for sl_2
    - S_{00} > 0 (positive normalization)
    - kappa(sl_2, k) = dim(sl_2)*(k+h^v)/(2*h^v) = 3(k+2)/4 (AP1, AP39)
    - The bar propagator is weight 1 (AP27), not weight h
"""

from __future__ import annotations

import math
from functools import lru_cache
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
from sympy import (
    Rational,
    Symbol,
    cos,
    factor,
    minimal_polynomial,
    pi as sym_pi,
    simplify,
    sin,
    sqrt,
    bernoulli as sympy_bernoulli,
)


# =========================================================================
# Section 1: S-matrix and fusion coefficients (numerical, fast)
# =========================================================================

def sl2_S_entry(j: int, l: int, k: int) -> float:
    r"""Single S-matrix entry for sl_2 at level k.

    S_{jl} = sqrt(2/(k+2)) * sin(pi*(j+1)*(l+1)/(k+2))
    """
    n = k + 2
    return math.sqrt(2.0 / n) * math.sin(math.pi * (j + 1) * (l + 1) / n)


def sl2_S_matrix(k: int) -> np.ndarray:
    r"""Full S-matrix for sl_2 at level k.

    Returns (k+1) x (k+1) numpy array.
    """
    n = k + 2
    size = k + 1
    pf = math.sqrt(2.0 / n)
    S = np.zeros((size, size))
    for j in range(size):
        for l in range(size):
            S[j, l] = pf * math.sin(math.pi * (j + 1) * (l + 1) / n)
    return S


def sl2_fusion_coefficients(k: int) -> np.ndarray:
    r"""All fusion coefficients N_{ij}^m for sl_2 at level k.

    Verlinde formula:
        N_{ij}^m = sum_l S_{il} S_{jl} S_{ml} / S_{0l}

    For sl_2 the S-matrix is real symmetric with S^2 = I,
    so conj(S_{ml}) = S_{ml}.

    Returns (k+1)^3 array.
    """
    S = sl2_S_matrix(k)
    size = k + 1
    N = np.zeros((size, size, size))
    for i in range(size):
        for j in range(size):
            for m in range(size):
                total = 0.0
                for l in range(size):
                    if abs(S[0, l]) > 1e-15:
                        total += S[i, l] * S[j, l] * S[m, l] / S[0, l]
                N[i, j, m] = total
    return N


def sl2_fusion_exact(i: int, j: int, m: int, k: int) -> int:
    r"""Exact fusion coefficient via truncated Clebsch-Gordan rule.

    N_{ij}^m = 1 if |i-j| <= m <= min(i+j, 2k-i-j) and i+j+m even,
    N_{ij}^m = 0 otherwise.

    This is the known closed form for sl_2 (unique to rank 1).
    """
    if (abs(i - j) <= m <= min(i + j, 2 * k - i - j)
            and (i + j + m) % 2 == 0):
        return 1
    return 0


def verify_verlinde_integrality(k: int, tol: float = 1e-8) -> Dict[str, Any]:
    r"""Verify that all fusion coefficients are non-negative integers.

    Returns dict with:
        all_integer: bool
        all_nonneg: bool
        max_deviation: float (max distance from nearest integer)
        total_checked: int
    """
    N = sl2_fusion_coefficients(k)
    size = k + 1
    max_dev = 0.0
    all_int = True
    all_nn = True
    total = 0

    for i in range(size):
        for j in range(size):
            for m in range(size):
                val = N[i, j, m]
                rounded = round(val)
                dev = abs(val - rounded)
                max_dev = max(max_dev, dev)
                if dev > tol:
                    all_int = False
                if rounded < 0:
                    all_nn = False
                total += 1

    return {
        "all_integer": all_int,
        "all_nonneg": all_nn,
        "max_deviation": max_dev,
        "total_checked": total,
    }


def verify_verlinde_vs_cg(k: int, tol: float = 1e-8) -> Dict[str, Any]:
    r"""Cross-verify Verlinde formula against Clebsch-Gordan rule.

    Path 1: Verlinde formula (S-matrix sum)
    Path 2: Truncated CG rule (closed form)

    These must agree for sl_2 at all levels.
    """
    N = sl2_fusion_coefficients(k)
    size = k + 1
    mismatches = []

    for i in range(size):
        for j in range(size):
            for m in range(size):
                verlinde_val = round(N[i, j, m])
                cg_val = sl2_fusion_exact(i, j, m, k)
                if verlinde_val != cg_val:
                    mismatches.append((i, j, m, verlinde_val, cg_val))

    return {
        "all_match": len(mismatches) == 0,
        "mismatches": mismatches,
        "total_checked": size ** 3,
    }


# =========================================================================
# Section 2: Quantum dimensions and shadow invariants
# =========================================================================

def sl2_quantum_dimension(j: int, k: int) -> float:
    r"""Quantum dimension of V_j for sl_2 at level k.

    d_j = sin((j+1)*pi/(k+2)) / sin(pi/(k+2))

    Properties:
        d_0 = 1, d_j = d_{k-j}, d_j > 0 for 0 <= j <= k.
    """
    n = k + 2
    return math.sin((j + 1) * math.pi / n) / math.sin(math.pi / n)


def sl2_quantum_dimensions_all(k: int) -> np.ndarray:
    """All quantum dimensions d_0, ..., d_k."""
    return np.array([sl2_quantum_dimension(j, k) for j in range(k + 1)])


def sl2_total_quantum_dim_sq(k: int) -> float:
    r"""Total quantum dimension squared D^2 = sum_j d_j^2 = 1/S_{00}^2.

    Closed form: D^2 = (k+2) / (2 sin^2(pi/(k+2)))
    """
    n = k + 2
    return n / (2.0 * math.sin(math.pi / n) ** 2)


def sl2_total_quantum_dim_sq_from_sum(k: int) -> float:
    """D^2 computed by direct summation of d_j^2."""
    dims = sl2_quantum_dimensions_all(k)
    return float(np.sum(dims ** 2))


def sl2_kappa(k: int) -> float:
    r"""Modular characteristic kappa for sl_2 at level k.

    kappa(sl_2, k) = dim(sl_2) * (k + h^v) / (2 * h^v) = 3(k+2)/4

    where dim(sl_2) = 3 and h^v = 2.
    """
    return 3.0 * (k + 2) / 4.0


def sl2_kappa_exact(k: int) -> Rational:
    """Exact kappa as Rational."""
    return Rational(3, 4) * (k + 2)


def kappa_from_quantum_dimensions(k: int) -> Dict[str, Any]:
    r"""Investigate if kappa is expressible from fusion/quantum-dimension data.

    We compute:
        D^2 = sum d_j^2 = (k+2)/(2 sin^2(pi/(k+2)))
        kappa = 3(k+2)/4
        ratio = kappa / D^2 = (3/2) sin^2(pi/(k+2))

    The ratio is NOT constant -- it depends on k through sin^2.
    For large k: ratio ~ 3 pi^2 / (2(k+2)^2) -> 0.

    So kappa is NOT a simple rational function of D^2.
    But kappa IS expressible from the S-matrix:
        kappa = (3/4) * S_{00}^{-2} * 2 * sin^2(pi/(k+2)) * (k+2)/... (circular)

    The direct connection: kappa = dim(g)*(k+h^v)/(2*h^v) uses the LEVEL
    and the LIE ALGEBRA DATA, not the fusion ring alone.
    """
    D2 = sl2_total_quantum_dim_sq(k)
    kap = sl2_kappa(k)
    ratio = kap / D2
    n = k + 2
    ratio_formula = 1.5 * math.sin(math.pi / n) ** 2
    large_k_approx = 1.5 * (math.pi / n) ** 2

    return {
        "k": k,
        "kappa": kap,
        "D_squared": D2,
        "ratio_kappa_over_D2": ratio,
        "ratio_formula": ratio_formula,
        "ratio_matches_formula": abs(ratio - ratio_formula) < 1e-12,
        "large_k_approx": large_k_approx,
    }


# =========================================================================
# Section 3: Number fields and minimal polynomials
# =========================================================================

def sl2_number_field_degree(k: int) -> int:
    r"""Degree of the number field generated by S-matrix entries.

    The S-matrix for sl_2 at level k has entries involving
    sin(pi*m/(k+2)) for m = 1, ..., k+1.

    These generate the field Q(cos(2*pi/(k+2))) = Q(zeta_{k+2})^+,
    the maximal real subfield of the (k+2)-th cyclotomic field.

    Degree = phi(k+2)/2 where phi is Euler's totient function,
    EXCEPT when k+2 = 1 or 2 (where the field is Q itself).
    """
    n = k + 2
    if n <= 2:
        return 1
    return _euler_totient(n) // 2


def _euler_totient(n: int) -> int:
    """Euler's totient function phi(n)."""
    result = n
    p = 2
    temp = n
    while p * p <= temp:
        if temp % p == 0:
            while temp % p == 0:
                temp //= p
            result -= result // p
        p += 1
    if temp > 1:
        result -= result // temp
    return result


def sl2_prime_level_field(p: int) -> Dict[str, Any]:
    r"""Number field data at prime-related level k = p - 2.

    At this level, k+2 = p (prime), so:
        - Field = Q(cos(2*pi/p)) = Q(zeta_p)^+
        - Degree = (p-1)/2
        - S-matrix entries involve sin(pi*m/p)

    The Galois group Gal(Q(zeta_p)^+/Q) = (Z/pZ)^* / {+/-1}
    is cyclic of order (p-1)/2.
    """
    if p < 3:
        raise ValueError(f"Prime p must be >= 3, got {p}")
    k = p - 2
    deg = (p - 1) // 2
    n = k + 2  # = p

    # The primitive 2cos(2*pi/p) generates Q(zeta_p)^+
    # Its minimal polynomial is the p-th minimal polynomial of 2*cos(2*pi*m/p)
    # which is the Chebyshev-related polynomial of degree (p-1)/2.

    # Galois group generators: the map cos(2*pi/p) -> cos(2*pi*g/p)
    # where g is a primitive root mod p.
    galois_order = deg

    # Sample S-matrix entries at this level
    s_entries = {}
    for j in range(k + 1):
        val = math.sqrt(2.0 / p) * math.sin(math.pi * (j + 1) / p)
        s_entries[j] = val

    return {
        "prime": p,
        "level": k,
        "field_degree": deg,
        "galois_group_order": galois_order,
        "galois_group_cyclic": True,  # (Z/pZ)^*/{+-1} is cyclic
        "s_matrix_first_row": s_entries,
    }


def quantum_dim_minimal_poly_degree(j: int, k: int) -> int:
    r"""Degree of minimal polynomial of d_j = sin((j+1)*pi/(k+2))/sin(pi/(k+2)).

    The quantum dimension d_j is an algebraic number.  Its minimal
    polynomial degree divides phi(k+2)/2.

    For j = 0: d_0 = 1, degree 1.
    For j = k: d_k = 1 (charge conjugation symmetry), degree 1.
    For j = 1 at prime k+2 = p: d_1 = 2*cos(pi/p), minimal poly degree (p-1)/2.
    """
    n = k + 2
    if j == 0 or j == k:
        return 1

    # d_j = sin((j+1)*pi/n) / sin(pi/n) = U_j(cos(pi/n))
    # where U_j is the j-th Chebyshev polynomial of the second kind.
    # The minimal polynomial degree divides phi(n)/2.

    # For a rough estimate: we use the fact that d_j lies in Q(cos(2*pi/n))
    # which has degree phi(n)/2 over Q.
    # The exact degree depends on j and n.

    # Simple cases
    if n <= 2:
        return 1

    field_deg = _euler_totient(n) // 2
    if field_deg == 0:
        field_deg = 1

    # For the fundamental rep j=1: d_1 = 2*cos(pi/n) for n >= 3.
    # Its minimal polynomial is the n-th cyclotomic-related polynomial.
    # Degree = phi(2n)/2 if n is odd, phi(n)/2 if n is even.
    # But d_1 = 2*cos(pi/n) generates the same field as cos(2*pi/n)
    # (since cos(2*pi/n) = 2*cos^2(pi/n) - 1), so degree divides phi(n)/2.

    # We return the field degree as an upper bound; the exact degree
    # requires computing the minimal polynomial.
    return field_deg


def quantum_dim_approx_minimal_poly(j: int, k: int) -> Dict[str, Any]:
    r"""Compute approximate minimal polynomial of d_j.

    Uses numerical methods to find the minimal polynomial by
    computing powers of d_j and finding integer relations.

    Returns dict with degree, approximate coefficients, and verification.
    """
    n = k + 2
    d_j = sl2_quantum_dimension(j, k)

    if abs(d_j - round(d_j)) < 1e-10:
        # d_j is (approximately) an integer
        int_val = round(d_j)
        return {
            "j": j, "k": k, "d_j": d_j,
            "degree": 1,
            "approx_coeffs": [-int_val, 1],  # x - int_val
            "is_integer": True,
        }

    # Try to find minimal polynomial up to degree 20
    max_deg = min(20, _euler_totient(n) // 2 + 2)
    powers = [d_j ** i for i in range(max_deg + 1)]

    # Use numpy to find integer linear relation
    for deg in range(2, max_deg + 1):
        # Build matrix: find integer coefficients c_0,...,c_deg
        # such that c_0 + c_1*d + ... + c_deg*d^deg = 0
        A = np.array(powers[:deg + 1]).reshape(1, -1)
        # Try LLL-like approach: scale up and look for small integer relations
        # Simple approach: build Vandermonde and check for near-integer nullspace
        scale = 1e8
        row = np.array(powers[:deg + 1]) * scale
        # Extend to (deg+1) x (deg+2) with identity block
        M = np.zeros((deg + 1, deg + 2))
        for i in range(deg + 1):
            M[i, i] = 1
        M[:, deg + 1] = row

        # Use QR to find the near-nullspace
        Q, R = np.linalg.qr(M.T)
        # The last column of Q is the candidate
        candidate = Q[:, -1]

        # Normalize so the leading coefficient is positive integer
        if abs(candidate[deg]) > 1e-15:
            candidate = candidate / candidate[deg]
            # Check if coefficients are near-integers
            rounded = np.round(candidate[:deg + 1])
            if np.max(np.abs(candidate[:deg + 1] - rounded)) < 0.01:
                # Verify
                val = sum(int(rounded[i]) * d_j ** i for i in range(deg + 1))
                if abs(val) < 1e-6:
                    coeffs = [int(rounded[i]) for i in range(deg + 1)]
                    return {
                        "j": j, "k": k, "d_j": d_j,
                        "degree": deg,
                        "approx_coeffs": coeffs,
                        "is_integer": False,
                        "residual": abs(val),
                    }

    return {
        "j": j, "k": k, "d_j": d_j,
        "degree": -1,  # Could not determine
        "approx_coeffs": None,
        "is_integer": False,
    }


def shadow_number_field_degree(k: int) -> int:
    r"""Degree of number field generated by shadow coefficients for sl_2_k.

    The shadow coefficients S_r(sl_2_k) are:
        kappa = 3(k+2)/4 (rational)
        S_3 = 0 (affine KM is class L, tower terminates at arity 3)
        S_r = 0 for r >= 4

    Since all shadow coefficients are RATIONAL, the shadow number
    field is Q itself, degree 1 over Q.
    """
    return 1  # Always Q for affine KM (class L, finite tower)


def arithmetic_gap(k: int) -> Dict[str, Any]:
    r"""The arithmetic gap between shadow and Verlinde number fields.

    Shadow data lives in Q (degree 1).
    Verlinde data lives in Q(cos(2*pi/(k+2))) (degree phi(k+2)/2).

    The gap measures how much richer the Verlinde arithmetic is
    compared to the shadow arithmetic.
    """
    shadow_deg = shadow_number_field_degree(k)
    verlinde_deg = sl2_number_field_degree(k)

    return {
        "k": k,
        "shadow_field_degree": shadow_deg,
        "verlinde_field_degree": verlinde_deg,
        "arithmetic_gap": verlinde_deg - shadow_deg,
        "gap_ratio": verlinde_deg / max(shadow_deg, 1),
    }


# =========================================================================
# Section 4: Verlinde rank and arithmetic depth
# =========================================================================

def sl2_verlinde_rank(k: int) -> int:
    """Verlinde rank = number of integrable representations = k+1."""
    return k + 1


def sl2_shadow_depth() -> int:
    r"""Shadow depth for sl_2 at any level.

    Affine sl_2 is class L (Lie/tree): shadow tower terminates at arity 3.
    Shadow depth d = 2 (= 1 + d_arith + d_alg with d_alg = 1, d_arith = 0).

    This is INDEPENDENT of k.
    """
    return 2


def sl2_arithmetic_depth(k: int) -> int:
    r"""Arithmetic depth d_arith for sl_2 at level k.

    d_arith = 0 for affine KM at all levels: the shadow coefficients
    are rational (kappa in Q, tower terminates, no cusp forms appear).

    The arithmetic depth measures cusp-form contributions to the
    shadow obstruction tower.  For class L algebras (finite tower),
    there are no higher-genus corrections involving cusp forms.
    """
    return 0


def sl3_verlinde_rank(k: int) -> int:
    r"""Verlinde rank for sl_3 at level k.

    Number of integrable weights = C(k+2, 2) = (k+1)(k+2)/2.
    """
    return (k + 1) * (k + 2) // 2


def sl3_kappa(k: int) -> float:
    r"""kappa for sl_3 at level k.

    kappa(sl_3, k) = dim(sl_3) * (k + h^v) / (2 * h^v) = 8*(k+3)/6 = 4(k+3)/3

    where dim(sl_3) = 8 and h^v = 3.
    """
    return 4.0 * (k + 3) / 3.0


def sl3_shadow_depth() -> int:
    r"""Shadow depth for sl_3 at any level.

    Affine sl_3 is class L (Lie/tree): terminates at arity 3.
    Shadow depth d = 2, same as sl_2.
    """
    return 2


def sl3_arithmetic_depth(k: int) -> int:
    r"""Arithmetic depth d_arith for sl_3 at level k.

    d_arith = 0: same reasoning as sl_2 (class L, finite tower, rational).
    """
    return 0


def verlinde_rank_vs_shadow_depth_table(max_k: int = 15) -> List[Dict[str, Any]]:
    r"""Table relating Verlinde rank and shadow depth for sl_2.

    The Verlinde rank grows linearly (k+1) while the shadow depth
    is constant (d=2, class L).  This demonstrates that the Verlinde
    fusion structure contains arithmetic information BEYOND the shadow
    tower -- the shadow captures only the leading-order (kappa) behavior.
    """
    table = []
    for k in range(1, max_k + 1):
        table.append({
            "k": k,
            "verlinde_rank_sl2": sl2_verlinde_rank(k),
            "shadow_depth_sl2": sl2_shadow_depth(),
            "d_arith_sl2": sl2_arithmetic_depth(k),
            "kappa_sl2": sl2_kappa(k),
            "verlinde_field_degree": sl2_number_field_degree(k),
        })
    return table


# =========================================================================
# Section 5: Kappa from quantum dimensions
# =========================================================================

def kappa_vs_sum_d_squared(k: int) -> Dict[str, float]:
    r"""Compare kappa with sum of squared quantum dimensions.

    kappa = 3(k+2)/4
    sum d_j^2 = D^2 = (k+2)/(2 sin^2(pi/(k+2)))
    ratio = kappa / D^2 = (3/2) sin^2(pi/(k+2))

    At large k: ratio ~ (3/2)(pi/(k+2))^2 -> 0.
    At k=1: ratio = (3/2) sin^2(pi/3) = (3/2)(3/4) = 9/8.
    """
    kap = sl2_kappa(k)
    D2 = sl2_total_quantum_dim_sq(k)
    ratio = kap / D2
    n = k + 2
    sin_val = math.sin(math.pi / n)
    formula_ratio = 1.5 * sin_val ** 2

    return {
        "k": k,
        "kappa": kap,
        "D_squared": D2,
        "ratio": ratio,
        "formula_ratio": formula_ratio,
        "match": abs(ratio - formula_ratio) < 1e-12,
    }


def kappa_not_rational_function_of_D2() -> Dict[str, Any]:
    r"""Demonstrate that kappa is NOT a rational function of D^2.

    If kappa = f(D^2) for some rational function f, then f would
    have to map D^2(k) -> kappa(k) for all k.  We show this is
    impossible by checking that the map k -> (D^2(k), kappa(k))
    does not lie on any algebraic curve of low degree.

    Evidence: the ratio kappa/D^2 is NOT constant.
    """
    ratios = []
    for k in range(1, 21):
        kap = sl2_kappa(k)
        D2 = sl2_total_quantum_dim_sq(k)
        ratios.append(kap / D2)

    # Check if ratios are constant
    is_constant = max(ratios) - min(ratios) < 1e-10
    # Check if ratios are monotone
    is_monotone = all(ratios[i] >= ratios[i + 1] for i in range(len(ratios) - 1))

    return {
        "ratios": ratios,
        "is_constant": is_constant,
        "is_monotone_decreasing": is_monotone,
        "min_ratio": min(ratios),
        "max_ratio": max(ratios),
        "conclusion": "kappa is NOT a rational function of D^2",
    }


# =========================================================================
# Section 6: Prime-level analysis
# =========================================================================

def is_prime(n: int) -> bool:
    """Simple primality test."""
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def prime_level_analysis(p: int) -> Dict[str, Any]:
    r"""Complete arithmetic analysis at prime level k = p-2.

    At level k = p-2, we have k+2 = p (prime), so:
    - S-matrix entries involve sin(pi*m/p) for m=1,...,p-1
    - These generate Q(cos(2*pi/p)) = Q(zeta_p)^+
    - Field degree = (p-1)/2
    - Galois group = (Z/pZ)^*/{+/-1}, cyclic of order (p-1)/2
    """
    if not is_prime(p):
        raise ValueError(f"{p} is not prime")
    if p < 3:
        raise ValueError(f"Prime must be >= 3, got {p}")

    k = p - 2
    n = p  # k + 2

    # Number field data
    field_deg = (p - 1) // 2

    # Quantum dimensions
    dims = sl2_quantum_dimensions_all(k)

    # kappa
    kap = sl2_kappa(k)

    # Verlinde rank
    v_rank = sl2_verlinde_rank(k)

    # Specific trigonometric values
    cos_2pi_p = math.cos(2 * math.pi / p)
    sin_pi_p = math.sin(math.pi / p)

    # D^2
    D2 = sl2_total_quantum_dim_sq(k)

    # Fusion data
    N = sl2_fusion_coefficients(k)
    # Check integrality
    max_dev = 0.0
    for i in range(k + 1):
        for j in range(k + 1):
            for m in range(k + 1):
                dev = abs(N[i, j, m] - round(N[i, j, m]))
                max_dev = max(max_dev, dev)

    return {
        "prime": p,
        "level": k,
        "field_degree": field_deg,
        "verlinde_rank": v_rank,
        "kappa": kap,
        "D_squared": D2,
        "quantum_dims": dims.tolist(),
        "cos_2pi_p": cos_2pi_p,
        "sin_pi_p": sin_pi_p,
        "fusion_integrality_max_dev": max_dev,
        "shadow_field_degree": 1,
        "arithmetic_gap": field_deg - 1,
    }


def prime_level_table() -> List[Dict[str, Any]]:
    r"""Arithmetic data for all prime-related levels up to p=23."""
    primes = [3, 5, 7, 11, 13, 17, 19, 23]
    return [prime_level_analysis(p) for p in primes]


# =========================================================================
# Section 7: Fusion ring structure
# =========================================================================

def sl2_fusion_ring_characters(k: int) -> np.ndarray:
    r"""Characters of the Verlinde ring for sl_2 at level k.

    chi_l(V_j) = S_{jl} / S_{0l}

    These are the eigenvalues of the multiplication operator M_{V_j}
    acting on R_k.  There are k+1 characters, one for each l.

    Returns (k+1) x (k+1) array where result[j, l] = chi_l(V_j).
    """
    S = sl2_S_matrix(k)
    size = k + 1
    chi = np.zeros((size, size))
    for j in range(size):
        for l in range(size):
            if abs(S[0, l]) > 1e-15:
                chi[j, l] = S[j, l] / S[0, l]
    return chi


def verify_character_multiplicativity(k: int, tol: float = 1e-8) -> bool:
    r"""Verify chi_l(V_i * V_j) = chi_l(V_i) * chi_l(V_j).

    Characters are ring homomorphisms R_k -> C.
    """
    chi = sl2_fusion_ring_characters(k)
    N = sl2_fusion_coefficients(k)
    size = k + 1

    for l in range(size):
        for i in range(size):
            for j in range(size):
                # chi_l(V_i * V_j) = sum_m N_{ij}^m chi_l(V_m)
                lhs = sum(round(N[i, j, m]) * chi[m, l] for m in range(size))
                # chi_l(V_i) * chi_l(V_j)
                rhs = chi[i, l] * chi[j, l]
                if abs(lhs - rhs) > tol:
                    return False
    return True


def sl2_fusion_ring_is_semisimple(k: int) -> Dict[str, Any]:
    r"""Check semisimplicity of the Verlinde ring.

    The Verlinde ring R_k is semisimple (as Q-algebra) iff the character
    table is a square matrix of full rank.  For sl_2 this is always true
    because the S-matrix is unitary.

    Semisimplicity means R_k tensor Q = product of fields.
    Since all characters chi_l take values in R (for sl_2), we have
    R_k tensor Q = Q^{k+1} (product of k+1 copies of Q or number fields).
    """
    chi = sl2_fusion_ring_characters(k)
    size = k + 1
    rank = np.linalg.matrix_rank(chi, tol=1e-10)

    return {
        "k": k,
        "ring_dimension": size,
        "character_matrix_rank": rank,
        "is_semisimple": rank == size,
    }


def sl2_multiplication_eigenvalues(j: int, k: int) -> np.ndarray:
    r"""Eigenvalues of multiplication by V_j in the Verlinde ring.

    The multiplication operator M_{V_j} acts on R_k by
    M_{V_j}(V_i) = sum_m N_{ij}^m V_m.

    Its eigenvalues are chi_l(V_j) = S_{jl}/S_{0l} for l = 0,...,k.
    """
    chi = sl2_fusion_ring_characters(k)
    return chi[j, :]


# =========================================================================
# Section 8: Asymptotic analysis
# =========================================================================

def verlinde_large_k_growth(j_fixed: int, l_fixed: int, k_values: List[int]) -> List[Dict[str, float]]:
    r"""Growth of fusion coefficients N_{j,l}^m as k varies.

    For large k with fixed j, l:
        N_{j,l}^m -> delta_{m in CG range}

    The fusion rules approach the classical Clebsch-Gordan decomposition
    for SU(2), with the truncation boundary at m = 2k-j-l receding to infinity.
    """
    results = []
    for k in k_values:
        if j_fixed > k or l_fixed > k:
            continue
        N = sl2_fusion_coefficients(k)
        nonzero_channels = []
        for m in range(k + 1):
            val = round(N[j_fixed, l_fixed, m])
            if val > 0:
                nonzero_channels.append((m, val))
        results.append({
            "k": k,
            "nonzero_channels": nonzero_channels,
            "num_channels": len(nonzero_channels),
        })
    return results


def shadow_large_k_growth(k_values: List[int]) -> List[Dict[str, float]]:
    r"""Growth of shadow invariants as k varies.

    kappa(sl_2_k) = 3(k+2)/4 -> 3k/4 for large k.
    The shadow tower for affine KM is class L and terminates.
    """
    results = []
    for k in k_values:
        kap = sl2_kappa(k)
        c = 3.0 * k / (k + 2)
        results.append({
            "k": k,
            "kappa": kap,
            "kappa_asymptotic": 0.75 * k,
            "kappa_ratio": kap / (0.75 * k) if k > 0 else float('inf'),
            "central_charge": c,
            "c_asymptotic": 3.0,
        })
    return results


def verlinde_vs_shadow_correlation(max_k: int = 20) -> Dict[str, Any]:
    r"""Correlation between fusion coefficients and shadow data.

    The fusion coefficients N_{ij}^m are integers in {0, 1} for sl_2.
    The shadow kappa is a rational number growing linearly in k.
    These are fundamentally different: one is combinatorial (integer),
    the other is analytic (rational/real).

    The Verlinde dimension Z_g grows polynomially:
        Z_g ~ (k+2)^{(2g-2)(N^2-1)/2} for large k (sl_N)

    The shadow F_g grows linearly:
        F_g = kappa * lambda_g ~ k for large k

    So the Verlinde dimension grows MUCH faster than the shadow.
    """
    k_values = list(range(1, max_k + 1))
    verlinde_g2 = []
    shadow_g2 = []

    for k in k_values:
        # Verlinde at genus 2
        S = sl2_S_matrix(k)
        Z2 = sum(S[0, j] ** (-2) for j in range(k + 1) if abs(S[0, j]) > 1e-15)
        verlinde_g2.append(round(Z2))

        # Shadow at genus 2: F_2 = kappa * lambda_2 = kappa * 7/5760
        kap = sl2_kappa(k)
        F2 = kap * 7.0 / 5760.0
        shadow_g2.append(F2)

    # Growth rate: log(Z_2)/log(k) for large k
    if max_k >= 10:
        growth_verlinde = math.log(verlinde_g2[-1]) / math.log(k_values[-1])
        growth_shadow = math.log(shadow_g2[-1]) / math.log(k_values[-1])
    else:
        growth_verlinde = None
        growth_shadow = None

    return {
        "k_values": k_values,
        "verlinde_genus2": verlinde_g2,
        "shadow_genus2": shadow_g2,
        "growth_exponent_verlinde": growth_verlinde,
        "growth_exponent_shadow": growth_shadow,
    }


# =========================================================================
# Section 9: sl_3 Verlinde arithmetic
# =========================================================================

def sl3_integrable_weights(k: int) -> List[Tuple[int, int]]:
    r"""Integrable highest weights for sl_3 at level k.

    Dynkin labels (a1, a2) with a1, a2 >= 0 and a1 + a2 <= k.
    """
    weights = []
    for a1 in range(k + 1):
        for a2 in range(k + 1 - a1):
            weights.append((a1, a2))
    return weights


def sl3_S_matrix(k: int) -> np.ndarray:
    r"""Modular S-matrix for sl_3 at level k (Weyl-Kac-Peterson formula).

    S_{lambda,mu} = C * sum_{w in S_3} sgn(w) *
        exp(-2*pi*i * <w(lambda+rho), mu+rho>_0 / (k+3))

    where <,>_0 is the inner product on the traceless hyperplane.
    """
    N = 3
    n = k + N

    weights = sl3_integrable_weights(k)
    num = len(weights)

    def shifted_eps(a1, a2):
        return np.array([a1 + a2 + 2, a2 + 1, 0], dtype=float)

    def inner_traceless(v, w):
        v_p = v - np.mean(v)
        w_p = w - np.mean(w)
        return np.dot(v_p, w_p)

    perms = [(0, 1, 2), (1, 0, 2), (0, 2, 1), (2, 0, 1), (1, 2, 0), (2, 1, 0)]
    signs = [1, -1, -1, 1, 1, -1]

    S_raw = np.zeros((num, num), dtype=complex)
    for i, (a1_i, a2_i) in enumerate(weights):
        p = shifted_eps(a1_i, a2_i)
        for j_idx, (a1_j, a2_j) in enumerate(weights):
            q = shifted_eps(a1_j, a2_j)
            val = 0.0j
            for perm, sgn in zip(perms, signs):
                wp = p[list(perm)]
                ip = inner_traceless(wp, q)
                val += sgn * np.exp(-2.0j * math.pi * ip / n)
            S_raw[i, j_idx] = val

    # Normalize
    SSd = S_raw @ np.conj(S_raw.T)
    c_norm = math.sqrt(np.diag(SSd).real[0])
    S_mat = S_raw / c_norm

    # Phase: S_{00} real positive
    phase = S_mat[0, 0] / abs(S_mat[0, 0])
    S_mat = S_mat / phase

    return S_mat


def sl3_quantum_dimensions(k: int) -> np.ndarray:
    r"""Quantum dimensions for sl_3 at level k.

    d_lambda = S_{0,lambda}/S_{0,0}

    Uses the q-Weyl dimension formula:
        d_{(a1,a2)} = prod_{alpha>0} sin(pi<lambda+rho,alpha>/(k+3))
                     / sin(pi<rho,alpha>/(k+3))
    """
    n = k + 3
    weights = sl3_integrable_weights(k)
    dims = np.zeros(len(weights))

    def shifted_eps(a1, a2):
        return np.array([a1 + a2 + 2, a2 + 1, 0], dtype=float)

    rho = shifted_eps(0, 0)  # [2, 1, 0]
    pos_root_pairs = [(0, 1), (0, 2), (1, 2)]

    for idx, (a1, a2) in enumerate(weights):
        lam_rho = shifted_eps(a1, a2)
        d = 1.0
        for (i, j) in pos_root_pairs:
            num = math.sin(math.pi * (lam_rho[i] - lam_rho[j]) / n)
            den = math.sin(math.pi * (rho[i] - rho[j]) / n)
            d *= num / den
        dims[idx] = d

    return dims


def sl3_fusion_coefficients(k: int) -> np.ndarray:
    r"""Fusion coefficients for sl_3 at level k via Verlinde formula."""
    S = sl3_S_matrix(k)
    num = S.shape[0]
    N = np.zeros((num, num, num))

    for i in range(num):
        for j in range(num):
            for m in range(num):
                total = 0.0j
                for l in range(num):
                    s0l = S[0, l]
                    if abs(s0l) > 1e-15:
                        total += S[i, l] * S[j, l] * np.conj(S[m, l]) / s0l
                N[i, j, m] = total.real
    return N


def sl3_verlinde_integrality(k: int, tol: float = 1e-6) -> Dict[str, Any]:
    r"""Check integrality of sl_3 fusion coefficients."""
    N = sl3_fusion_coefficients(k)
    num = N.shape[0]
    max_dev = 0.0
    all_int = True
    all_nn = True

    for i in range(num):
        for j in range(num):
            for m in range(num):
                val = N[i, j, m]
                rd = round(val)
                dev = abs(val - rd)
                max_dev = max(max_dev, dev)
                if dev > tol:
                    all_int = False
                if rd < 0:
                    all_nn = False

    return {
        "all_integer": all_int,
        "all_nonneg": all_nn,
        "max_deviation": max_dev,
        "num_weights": num,
    }


def sl3_shadow_vs_verlinde(k: int) -> Dict[str, Any]:
    r"""Compare sl_3 shadow data with Verlinde data at level k.

    kappa(sl_3, k) = 4(k+3)/3
    Verlinde rank = (k+1)(k+2)/2
    Shadow depth = 2 (class L)
    d_arith = 0
    """
    kap = sl3_kappa(k)
    v_rank = sl3_verlinde_rank(k)
    D2 = sum(sl3_quantum_dimensions(k) ** 2)

    return {
        "k": k,
        "kappa": kap,
        "verlinde_rank": v_rank,
        "shadow_depth": sl3_shadow_depth(),
        "d_arith": sl3_arithmetic_depth(k),
        "D_squared": float(D2),
        "ratio_kappa_D2": kap / D2,
    }


# =========================================================================
# Section 10: Quantum group root-of-unity connection (Path 3)
# =========================================================================

def sl2_quantum_cg_coefficients(j1: int, j2: int, k: int) -> List[Tuple[int, int]]:
    r"""Fusion channels from quantum group CG decomposition at root of unity.

    At q = exp(i*pi/(k+2)) (root of unity), the tensor product of
    U_q(sl_2) representations decomposes as:

        V_{j1} tensor V_{j2} = bigoplus_m N_{j1,j2}^m V_m

    with truncated CG rule: m in {|j1-j2|, |j1-j2|+2, ..., min(j1+j2, 2k-j1-j2)}.

    Returns list of (m, N_{j1,j2}^m) pairs.
    """
    channels = []
    m_min = abs(j1 - j2)
    m_max = min(j1 + j2, 2 * k - j1 - j2)
    for m in range(m_min, m_max + 1, 2):
        channels.append((m, 1))
    return channels


def verify_quantum_group_verlinde(k: int, tol: float = 1e-8) -> Dict[str, Any]:
    r"""Cross-verify: quantum group CG rule vs Verlinde formula (Path 3).

    Both should give the same fusion coefficients.
    """
    N_verlinde = sl2_fusion_coefficients(k)
    size = k + 1
    mismatches = []

    for j1 in range(size):
        for j2 in range(size):
            qg_channels = sl2_quantum_cg_coefficients(j1, j2, k)
            qg_dict = dict(qg_channels)
            for m in range(size):
                verlinde_val = round(N_verlinde[j1, j2, m])
                qg_val = qg_dict.get(m, 0)
                if verlinde_val != qg_val:
                    mismatches.append((j1, j2, m, verlinde_val, qg_val))

    return {
        "all_match": len(mismatches) == 0,
        "mismatches": mismatches,
        "total_checked": size ** 3,
    }


# =========================================================================
# Section 11: Genus-g Verlinde dimension and shadow comparison
# =========================================================================

def sl2_verlinde_genus_g(k: int, g: int) -> float:
    r"""Verlinde dimension at genus g for sl_2 at level k.

    Z_g = sum_{j=0}^k S_{0j}^{2-2g}
    """
    S = sl2_S_matrix(k)
    total = 0.0
    for j in range(k + 1):
        s0j = S[0, j]
        if abs(s0j) > 1e-15:
            total += s0j ** (2 - 2 * g)
    return total


def sl2_verlinde_genus_g_exact(k: int, g: int) -> int:
    """Rounded to exact integer."""
    return round(sl2_verlinde_genus_g(k, g))


def faber_pandharipande_lambda(g: int) -> float:
    r"""Faber-Pandharipande number lambda_g^{FP}.

    This is the coefficient of x^{2g} in the A-hat generating function
    evaluated at imaginary argument:

        (x/2)/sin(x/2) = 1 + sum_{g>=1} lambda_g * x^{2g}

    Equivalently, from the Bernoulli number formula:
        lambda_g = sum_{j=0}^{g} [product formula involving B_{2j}]

    The first few values (AP22, independently verified by series expansion):
        lambda_1 = 1/24
        lambda_2 = 7/5760
        lambda_3 = 31/967680
        lambda_4 = 127/154828800
        lambda_5 = 73/3503554560
    """
    # Precomputed exact values (verified via sympy series expansion
    # of (x/2)/sin(x/2) to order x^14)
    _LAMBDA_FP = {
        1: 1.0 / 24,
        2: 7.0 / 5760,
        3: 31.0 / 967680,
        4: 127.0 / 154828800,
        5: 73.0 / 3503554560,
        6: 1414477.0 / 2678117105664000,
    }
    if g in _LAMBDA_FP:
        return _LAMBDA_FP[g]

    # For higher g, compute via series expansion
    # (x/2)/sin(x/2) power series coefficient extraction
    # Using the recurrence from Bernoulli numbers:
    # The coefficient of x^{2g} in (x/2)/sin(x/2) can be computed as
    # a_{2g} = sum_{j=0}^g (-1)^j * (2^{2j} - 2) * B_{2j} / (2j)! * a_{2(g-j)}
    # with a_0 = 1, but this is circular.
    # For g <= 6 we use the precomputed table.
    # For g > 6, compute numerically via the Bernoulli-number expression.
    from sympy import symbols, series, sin as sym_sin
    x = symbols('x')
    f = (x / 2) / sym_sin(x / 2)
    s = series(f, x, 0, 2 * g + 2)
    coeff = s.coeff(x, 2 * g)
    return float(coeff)


def sl2_shadow_F_g(k: int, g: int) -> float:
    r"""Shadow partition function F_g = kappa * lambda_g^{FP}.

    lambda_g is the Faber-Pandharipande number: the coefficient of x^{2g}
    in (x/2)/sin(x/2) = Ahat(ix), the A-hat genus at imaginary argument.

    lambda_1 = 1/24, lambda_2 = 7/5760, lambda_3 = 31/967680.

    NOTE: The formula |B_{2g}|/(4g*(2g-2)!) is ONLY correct for g=1.
    For g >= 2, one must use the actual A-hat series coefficients.
    """
    kap = sl2_kappa(k)
    lam = faber_pandharipande_lambda(g)
    return kap * lam


def verlinde_shadow_genus_comparison(k: int, max_g: int = 5) -> List[Dict[str, Any]]:
    r"""Compare Verlinde dimensions with shadow F_g for genus g=1,...,max_g.

    The Verlinde dimension Z_g counts ALL channels.
    The shadow F_g is the scalar projection.
    The ratio Z_g/F_g measures how much of the partition function
    is captured by the scalar shadow alone.
    """
    results = []
    for g in range(1, max_g + 1):
        Zg = sl2_verlinde_genus_g_exact(k, g)
        Fg = sl2_shadow_F_g(k, g)
        results.append({
            "g": g,
            "verlinde_dim": Zg,
            "shadow_F_g": Fg,
            "ratio_Z_over_F": Zg / Fg if Fg > 1e-15 else float('inf'),
        })
    return results


# =========================================================================
# Section 12: Known exact values (cross-check table)
# =========================================================================

# Exact Verlinde dimensions from the literature.
# Source: direct computation via the Verlinde formula.
# Cross-checked with Beauville (1996) for small cases.
SL2_VERLINDE_EXACT = {
    # Independently computed via Z_g = sum_{j=0}^k S_{0j}^{2-2g}
    # Cross-checked with two methods: (1) direct S-matrix sum, (2) formula
    # S_{0j} = sqrt(2/(k+2)) sin(pi(j+1)/(k+2)).
    (1, 0): 1, (1, 1): 2, (1, 2): 4, (1, 3): 8, (1, 4): 16,
    (2, 0): 1, (2, 1): 3, (2, 2): 10, (2, 3): 36, (2, 4): 136,
    (3, 0): 1, (3, 1): 4, (3, 2): 20, (3, 3): 120, (3, 4): 800,
    (4, 0): 1, (4, 1): 5, (4, 2): 35, (4, 3): 329, (4, 4): 3611,
    (5, 0): 1, (5, 1): 6, (5, 2): 56, (5, 3): 784, (5, 4): 13328,
    (6, 0): 1, (6, 1): 7, (6, 2): 84, (6, 3): 1680, (6, 4): 42048,
    (7, 0): 1, (7, 1): 8, (7, 2): 120, (7, 3): 3312, (7, 4): 117072,
    (8, 0): 1, (8, 1): 9, (8, 2): 165, (8, 3): 6105, (8, 4): 294525,
    (10, 0): 1, (10, 1): 11, (10, 2): 286, (10, 3): 17732,
}

SL2_KAPPA_EXACT = {
    1: Rational(9, 4),     # 3*(1+2)/4 = 9/4
    2: Rational(3, 1),     # 3*(2+2)/4 = 3
    3: Rational(15, 4),    # 3*(3+2)/4 = 15/4
    4: Rational(9, 2),     # 3*(4+2)/4 = 9/2
    5: Rational(21, 4),    # 3*(5+2)/4 = 21/4
    10: Rational(9, 1),    # 3*(10+2)/4 = 9
    20: Rational(33, 2),   # 3*(20+2)/4 = 33/2
}


def verify_kappa_table() -> Dict[int, bool]:
    """Verify kappa computations against exact values."""
    results = {}
    for k, expected in SL2_KAPPA_EXACT.items():
        computed = sl2_kappa_exact(k)
        results[k] = (computed == expected)
    return results


def verify_verlinde_table() -> Dict[Tuple[int, int], bool]:
    """Verify computed Verlinde dimensions against known values."""
    results = {}
    for (k, g), expected in SL2_VERLINDE_EXACT.items():
        computed = sl2_verlinde_genus_g_exact(k, g)
        results[(k, g)] = (computed == expected)
    return results


# =========================================================================
# Section 13: Comprehensive cross-verification
# =========================================================================

def four_path_cross_verification(k: int) -> Dict[str, Any]:
    r"""Full 4-path cross-verification for sl_2 at level k.

    Path 1: Direct Verlinde formula (S-matrix sum)
    Path 2: Truncated Clebsch-Gordan rule (exact combinatorics)
    Path 3: Quantum group tensor product at root of unity
    Path 4: Shadow tower kappa vs quantum dimension sum

    All four must be consistent.
    """
    # Path 1 vs Path 2
    p1_vs_p2 = verify_verlinde_vs_cg(k)

    # Path 1 vs Path 3
    p1_vs_p3 = verify_quantum_group_verlinde(k)

    # Path 4: kappa vs D^2
    p4 = kappa_vs_sum_d_squared(k)

    # Integrality
    integrality = verify_verlinde_integrality(k)

    # Genus-0 normalization: Z_0 = 1
    Z0 = sl2_verlinde_genus_g_exact(k, 0)

    # Genus-1: Z_1 = k+1 (number of integrable reps)
    Z1 = sl2_verlinde_genus_g_exact(k, 1)

    return {
        "k": k,
        "path1_vs_path2_match": p1_vs_p2["all_match"],
        "path1_vs_path3_match": p1_vs_p3["all_match"],
        "path4_kappa_D2_formula_match": p4["match"],
        "integrality": integrality["all_integer"],
        "nonnegativity": integrality["all_nonneg"],
        "genus0_normalization": Z0 == 1,
        "genus1_count": Z1 == k + 1,
        "all_paths_consistent": (
            p1_vs_p2["all_match"]
            and p1_vs_p3["all_match"]
            and p4["match"]
            and integrality["all_integer"]
            and integrality["all_nonneg"]
            and Z0 == 1
            and Z1 == k + 1
        ),
    }
