r"""RTT presentation of Y(sl_3) from the bar-cobar construction.

The Yangian Y(sl_3) in the RTT presentation is generated by
t_{ij}^{(r)} (i,j = 1,2,3; r >= 0) subject to the RTT relation:

    R(u-v) (T(u) \otimes 1)(1 \otimes T(v))
        = (1 \otimes T(v))(T(u) \otimes 1) R(u-v)

where T(u) = \sum_r T^{(r)} u^{-r} with (T^{(r)})_{ij} = t_{ij}^{(r)},
and R(u) = u I + P is the rational Yang R-matrix on C^3 \otimes C^3.

Connection to the bar complex
-----------------------------
The bar construction B(V_k(\hat{sl}_3)) produces a factorization coalgebra.
The collision residue Res^{coll}_{0,2}(\Theta_A) extracts the r-matrix
r(z) = \Omega/z, which exponentiates to the Yang R-matrix.  The RTT
relation is the arity-2 component of the MC equation
D\Theta + (1/2)[\Theta,\Theta] = 0.  The Yang--Baxter equation is the
arity-3 component.  MC3 (proved for all simple types) guarantees that
the tensor category of finite-dimensional Y(sl_3) modules is equivalent
to Rep(U_q(sl_3)) at generic q.

RTT relation order by order
----------------------------
Writing T(u) = I + T^{(1)} u^{-1} + T^{(2)} u^{-2} + ..., the RTT
relation R(u-v) T_1(u) T_2(v) = T_2(v) T_1(u) R(u-v) at each order
in u^{-m} v^{-n} gives (where w = u - v):

  (m,n) = (0,0): R(w) = R(w)  (trivial).
  (1,0): R(w) T_1^{(1)} = T_1^{(1)} R(w).
         This says [T^{(1)} \otimes I, P] = 0, i.e. T^{(1)} commutes
         with the permutation in the first factor, forcing T^{(1)}_{ij}
         proportional to delta_{ij}.  Combined with [T^{(1)}, R] = 0 it
         says T^{(1)} \otimes I commutes with P, which holds iff
         T^{(1)} is scalar.
  (0,1): R(w)(I \otimes T^{(1)}) = (I \otimes T^{(1)}) R(w).  Same.
  (1,1): the key quadratic relation:
         R(w)(T_1^{(1)} T_2^{(1)} + T_1^{(1)} + T_2^{(1)}/w) = ...
         After expansion this gives the commutation relation between
         the level-1 generators.

Quantum determinant
-------------------
For sl_3 the quantum determinant is:

    qdet T(u) = \sum_{\sigma \in S_3} (-1)^{l(\sigma)}
        t_{1,\sigma(1)}(u) t_{2,\sigma(2)}(u-1) t_{3,\sigma(3)}(u-2)

This is CENTRAL in Y(sl_3): [qdet T(u), t_{ij}(v)] = 0.

Drinfeld generators
-------------------
The Drinfeld (new) presentation uses {h_i^{(r)}, e_i^{(r)}, f_i^{(r)}}
for i = 1,2 (simple roots) and r >= 0.  At level 0 these are the
standard Chevalley generators of sl_3.  The Gauss decomposition
T(u) = F(u) H(u) E(u) connects RTT to Drinfeld generators.

Adjoint representation
----------------------
The adjoint R-matrix R^{adj}(u) \in End(C^8 \otimes C^8) is obtained
by evaluating the universal R-matrix on adj \otimes adj.  For the
rational Yangian, R^{adj}(u) = u(u+1)(u+3) I + ... with poles at
u = 0, -1, -3 corresponding to the three irreducible components of
adj \otimes adj.

Ground truth references
-----------------------
* yangian_rmatrix_sl3.py: fundamental R-matrix, Casimir, YBE, DK bridge.
* yangian_residue_extraction.py: Yang R-matrix for sl_N.
* yangians.tex: RTT presentation, DK bridge.
* Chari-Pressley, "A Guide to Quantum Groups" (1994).
* Molev, "Yangians and Classical Lie Algebras" (2007).

Conventions
-----------
* R(u) = u I + P  (additive Yang R-matrix, standard RTT convention).
* T(u) = I + T^{(1)} u^{-1} + T^{(2)} u^{-2} + ...
* Cohomological grading (|d| = +1).
* N = 3 (fundamental dimension), dim(sl_3) = 8.
"""

from __future__ import annotations

from itertools import permutations
from math import factorial
from typing import Dict, List, Optional, Tuple

import numpy as np
from sympy import (
    Matrix,
    Rational,
    Symbol,
    eye,
    simplify,
    symbols,
    zeros,
)

from compute.lib.yangian_rmatrix_sl3 import (
    FUND_DIM,
    DIM_SL3,
    H_VEE_SL3,
    kappa_sl3,
    fund_rep_matrices,
    dual_basis_matrices,
    killing_form_matrix,
    inverse_killing_form,
    casimir_tensor_fund,
    permutation_matrix_3,
    R_matrix_fund_exact_yang,
    verify_casimir_identity,
    casimir_scalar_fund,
    spectral_decomposition,
)
from compute.lib.sl3_bar import (
    DIM_G,
    GEN_NAMES,
    H1, H2, E1, E2, E3, F1, F2, F3,
    sl3_structure_constants,
    sl3_killing_form,
)


N = FUND_DIM  # 3


# ============================================================
# 1. RTT generating matrix T(u)
# ============================================================

def rtt_generators_symbolic(max_level: int = 2) -> Dict[int, Matrix]:
    r"""Symbolic RTT generators T^{(r)} for r = 0, ..., max_level.

    T^{(0)} = I_3  (by convention for the Yangian).
    T^{(r)} for r >= 1 are 3x3 matrices of formal symbols t_{ij}^{(r)}.

    Returns:
        Dict mapping level r to a 3x3 sympy Matrix.
    """
    gens = {}
    gens[0] = eye(N)
    for r in range(1, max_level + 1):
        entries = []
        for i in range(N):
            row = []
            for j in range(N):
                row.append(Symbol(f't_{i+1}{j+1}^({r})', commutative=False))
            entries.append(row)
        gens[r] = Matrix(entries)
    return gens


def T_matrix_formal(u: Symbol, max_level: int = 2) -> Matrix:
    r"""Formal generating matrix T(u) = \sum_{r=0}^{max_level} T^{(r)} u^{-r}.

    Returns a 3x3 matrix of formal power series in u^{-1}.
    """
    gens = rtt_generators_symbolic(max_level)
    T = zeros(N, N)
    for r in range(max_level + 1):
        T += gens[r] * u ** (-r)
    return T


# ============================================================
# 2. RTT relation: explicit order-by-order extraction
# ============================================================

def _P_matrix_symbolic() -> Matrix:
    """Permutation matrix P on C^3 otimes C^3 as a 9x9 sympy Matrix."""
    P = zeros(N * N, N * N)
    for i in range(N):
        for j in range(N):
            P[i * N + j, j * N + i] = 1
    return P


def _I9() -> Matrix:
    """9x9 identity matrix."""
    return eye(N * N)


def _kron(A: Matrix, B: Matrix) -> Matrix:
    """Kronecker product of two matrices."""
    ra, ca = A.rows, A.cols
    rb, cb = B.rows, B.cols
    result = zeros(ra * rb, ca * cb)
    for i in range(ra):
        for j in range(ca):
            for k in range(rb):
                for l in range(cb):
                    result[i * rb + k, j * cb + l] = A[i, j] * B[k, l]
    return result


def rtt_relation_order(m: int, n: int) -> str:
    r"""Description of the RTT relation at order u^{-m} v^{-n}.

    The RTT relation R_{12}(u-v) T_1(u) T_2(v) = T_2(v) T_1(u) R_{12}(u-v)
    is expanded in powers of u^{-1} and v^{-1}.  Each order gives a
    constraint on the RTT generators.

    Returns a string description of the constraint.
    """
    descriptions = {
        (0, 0): "Trivial: R(w) = R(w).",
        (1, 0): "[T^(1) x I, R(w)] = 0: T^(1) commutes with R in first factor. "
                 "Forces T^(1) x I to commute with P, so T^(1) is scalar or "
                 "the constraint is automatically satisfied for the Yangian.",
        (0, 1): "[I x T^(1), R(w)] = 0: T^(1) commutes with R in second factor. "
                 "Same constraint as (1,0) by symmetry.",
        (1, 1): "Key quadratic relation: [T^(1)_1, T^(1)_2] = [P, T^(1)_1 - T^(1)_2]. "
                 "This is the defining relation of the Yangian at level 1. "
                 "In components: [t_{ij}^(1), t_{kl}^(1)] = t_{kj}^(1) delta_{il} - t_{il}^(1) delta_{kj}.",
        (2, 0): "T^(2) commutes with R in first factor (same type as (1,0)).",
        (0, 2): "T^(2) commutes with R in second factor.",
        (2, 1): "Mixed relation involving T^(1) and T^(2): cubic constraint.",
        (1, 2): "Mixed relation involving T^(1) and T^(2): cubic constraint.",
        (2, 2): "Quartic relation involving T^(1) and T^(2).",
    }
    return descriptions.get((m, n), f"Order ({m},{n}): higher-order constraint.")


# ============================================================
# 3. Numerical RTT verification with concrete generators
# ============================================================

def _fund_generators_level1() -> np.ndarray:
    r"""Concrete level-1 RTT generators for Y(sl_3) in fundamental rep.

    For the evaluation representation ev_a: Y(sl_3) -> End(C^3),
    T(u) is represented by:
        T^{ev_a}(u) = (u - a) I + P_{fund}
    i.e. T^{(0)} = I, T^{(1)} = a * I + generators of sl_3.

    For the standard evaluation at a = 0:
        T^{ev_0}(u) = u I (trivial).
    For a general evaluation at a:
        T^{ev_a}(u) = (u - a) I + P → T^{(0)} = I, T^{(1)}_{ij} = a delta_{ij} + E_{ij}.

    We use the EVALUATION REPRESENTATION at a = 0 for simplicity:
    T(u) maps to the L-operator L_0(u) = R_{0,phys}(u) = u I + P|_{0,phys}.
    In the fundamental of sl_3:
        L(u)_{ij,kl} = u delta_{ik} delta_{jl} + delta_{il} delta_{jk}

    The 3x3 matrix entries are: L(u)_{ij} = u delta_{ij} + E_{ji}
    (operator on physical space C^3).
    """
    # L(u)_{ij} as a map on physical C^3:
    # L(u)_{ij} = u delta_{ij} I_{phys} + E_{ji}^{phys}
    # But actually L(u) is an End(C^3)-valued 3x3 matrix.
    # The evaluation homomorphism Y(sl_3) -> End(C^3) sends
    # t_{ij}^{(1)} -> E_{ji} (the elementary matrix).
    T1 = np.zeros((N, N), dtype=complex)
    for i in range(N):
        for j in range(N):
            # t_{ij}^{(1)} -> E_{ji} in the evaluation representation
            T1[i, j] = 0  # placeholder; the actual map is T1[i,j] = E_{ji}
    return T1


def rtt_evaluation_L_operator(u: complex, a: complex = 0.0) -> np.ndarray:
    r"""L-operator for the evaluation representation ev_a of Y(sl_3).

    L_a(u) = R_{aux,phys}(u - a) = (u - a) I_{9} + P

    This is a 9x9 matrix acting on C^3_{aux} \otimes C^3_{phys}.
    The RTT relation for L-operators:
        R_{12}(u-v) L_{1a}(u) L_{2a}(v) = L_{2a}(v) L_{1a}(u) R_{12}(u-v)

    follows from the Yang-Baxter equation R_{12} R_{13} R_{23} = R_{23} R_{13} R_{12}.

    Args:
        u: spectral parameter.
        a: evaluation point.

    Returns:
        9x9 complex matrix.
    """
    return R_matrix_fund_exact_yang(u - a)


def verify_rtt_from_ybe(u: complex, v: complex, a: complex = 0.0) -> float:
    r"""Verify RTT relation for evaluation L-operators via YBE.

    R_{12}(u-v) L_{1}(u) L_{2}(v) = L_{2}(v) L_{1}(u) R_{12}(u-v)

    where L_{1}(u) = R_{13}(u-a) and L_{2}(v) = R_{23}(v-a).
    This is a 27x27 matrix equation (on C^3_{aux1} x C^3_{aux2} x C^3_{phys}).

    The RTT relation IS the YBE with spaces relabeled:
    R_{12}(u-v) R_{13}(u-a) R_{23}(v-a) = R_{23}(v-a) R_{13}(u-a) R_{12}(u-v).

    Returns: Frobenius norm of LHS - RHS (should be ~0).
    """
    from compute.lib.yangian_rmatrix_sl3 import (
        _embed_12,
        _embed_13,
        _embed_23,
    )
    R12 = _embed_12(R_matrix_fund_exact_yang(u - v), N)
    L1 = _embed_13(R_matrix_fund_exact_yang(u - a), N)
    L2 = _embed_23(R_matrix_fund_exact_yang(v - a), N)

    lhs = R12 @ L1 @ L2
    rhs = L2 @ L1 @ R12
    return float(np.linalg.norm(lhs - rhs))


def extract_rtt_relation_11(a: complex = 0.0) -> np.ndarray:
    r"""Extract the (1,1) order RTT relation numerically.

    At order u^{-1} v^{-1}, the RTT relation gives:
        [T_1^{(1)}, T_2^{(1)}] = P (T_1^{(1)} - T_2^{(1)})
                                   - (T_1^{(1)} - T_2^{(1)}) P

    In the evaluation representation ev_a, T^{(1)}_{ij} = a delta_{ij}
    (evaluation shifts). For a = 0 the relation is trivially satisfied.
    For a != 0: T^{(1)} = a I, so [T_1, T_2] = 0 and the RHS also vanishes.

    For a nontrivial check, use two DIFFERENT evaluation points a1, a2
    and verify the RTT relation for L_{1}(u) = R(u-a1) and L_{2}(v) = R(v-a2).

    Returns: the 9x9 matrix [T_1^{(1)}, T_2^{(1)}] - P(T_1^{(1)} - T_2^{(1)}) + (T_1^{(1)} - T_2^{(1)})P
    """
    P = permutation_matrix_3().astype(complex)
    I3 = np.eye(N, dtype=complex)
    # T^{(1)} in evaluation at a: T^{(1)} = a * I_3
    T1_mat = a * I3
    T1_1 = np.kron(T1_mat, I3)  # T^{(1)} x I
    T1_2 = np.kron(I3, T1_mat)  # I x T^{(1)}

    commutator = T1_1 @ T1_2 - T1_2 @ T1_1
    rhs = P @ (T1_1 - T1_2) - (T1_1 - T1_2) @ P

    return commutator - rhs


def verify_rtt_order_by_order(u_val: float = 10.0, v_val: float = 7.0,
                               a_val: float = 0.0, max_order: int = 3) -> Dict[str, float]:
    r"""Verify RTT relation order by order in 1/u and 1/v.

    Expand R(u-v) T_1(u) T_2(v) = T_2(v) T_1(u) R(u-v) numerically.
    Using evaluation L-operators at point a, compute both sides and
    extract coefficients of u^{-m} v^{-n} by numerical differentiation.

    Instead, we verify the full RTT relation at multiple (u,v) and
    check that each order coefficient matches.

    Returns: dict of norms at each order.
    """
    results = {}
    # The RTT relation = YBE with relabeled spaces.
    # Verify at multiple spectral parameter values.
    test_params = [
        (u_val, v_val),
        (u_val + 1, v_val - 1),
        (u_val * 2, v_val * 3),
        (u_val + 0.5j, v_val - 0.3j),
    ]
    for u, v in test_params:
        norm = verify_rtt_from_ybe(u, v, a_val)
        results[f"RTT at u={u}, v={v}, a={a_val}"] = norm
    return results


# ============================================================
# 4. Quantum determinant for sl_3
# ============================================================

def quantum_determinant_matrix(u: complex) -> np.ndarray:
    r"""Quantum determinant qdet T(u) for Y(sl_3) in evaluation representation.

    qdet T(u) = \sum_{\sigma \in S_3} (-1)^{l(\sigma)}
        T_{1,\sigma(1)}(u) T_{2,\sigma(2)}(u-1) T_{3,\sigma(3)}(u-2)

    In the evaluation representation ev_a, T_{ij}(u) = (u-a) delta_{ij} + E_{ji},
    so T_{ij}(u) is a 3x3 matrix-valued function.

    The quantum determinant is a scalar (central) element.  In the evaluation
    representation it acts as the scalar:
        qdet = (u - a)(u - a - 1)(u - a - 2)

    This is the value of the quantum determinant on the evaluation module V(a).

    Args:
        u: spectral parameter.

    Returns:
        The 3x3 identity times the scalar qdet value.
    """
    a = 0.0
    qdet_val = quantum_determinant_scalar(u, a)
    return qdet_val * np.eye(N, dtype=complex)


def quantum_determinant_scalar(u: complex, a: complex = 0.0) -> complex:
    r"""Scalar value of qdet T(u) on the evaluation module V(a).

    In the RTT convention R(u) = u I + P with T_{ij}(u) = u delta_{ij} + E_{ji},
    the quantum determinant on the fundamental evaluation module V(a) evaluates to:

        qdet T(u)|_{V(a)} = (u - a + 1)(u - a - 1)(u - a - 2)

    The roots are at u = a - 1, a + 1, a + 2.  The shift by +1 relative to
    the naive (u-a)(u-a-1)(u-a-2) arises from the E_{ji} term in T_{ii}(u):
    on the highest-weight vector, T_{11}(u) = u + 1 (not u).

    Verification: at a = 0, u = 5:
        (5+1)(5-1)(5-2) = 6*4*3 = 72.
    Confirmed by direct computation of the column-determinant sum over S_3.
    """
    return (u - a + 1) * (u - a - 1) * (u - a - 2)


def verify_qdet_centrality(u: complex, v: complex, a: complex = 0.0) -> float:
    r"""Verify that qdet T(u) commutes with T_{ij}(v).

    In the evaluation representation, qdet is a scalar, so it commutes
    with everything.  The nontrivial content is that qdet is central
    in the ABSTRACT Yangian, not just in a specific representation.

    For the evaluation representation, we verify:
        [qdet(u) I, L(v)] = 0

    which is trivially true since qdet(u) is scalar.  The more
    nontrivial check is done via the RTT relation.

    The centrality follows from:
    1. qdet T(u) is invariant under T(u) -> g T(u) g^{-1} for g in GL(3).
    2. The antisymmetrizer A_3 satisfies:
       A_3 R_{12}(u_1-u_2) R_{13}(u_1-u_3) R_{23}(u_2-u_3)
       = A_3 * (u_1-u_2)(u_1-u_3)(u_2-u_3)
    3. Combining: qdet T(u) commutes with T_{ij}(v) for all i,j.

    Returns: norm of [qdet, L(v)] (should be 0).
    """
    qdet_val = quantum_determinant_scalar(u, a)
    I9 = np.eye(N * N, dtype=complex)
    L = rtt_evaluation_L_operator(v, a)

    comm = qdet_val * I9 @ L - L @ (qdet_val * I9)
    return float(np.linalg.norm(comm))


def verify_qdet_antisymmetrizer(u: complex) -> float:
    r"""Verify the quantum determinant via the column-determinant formula.

    The quantum determinant qdet T(u) is defined by:
        qdet T(u) = sum_{sigma in S_3} sgn(sigma)
            T_{1,sigma(1)}(u) T_{2,sigma(2)}(u-1) T_{3,sigma(3)}(u-2)

    We verify two properties:
    1. qdet is a scalar matrix (proportional to I_3).
    2. The scalar value matches (u-a+1)(u-a-1)(u-a-2) for the evaluation at a.

    This function checks both properties at the given spectral parameter u
    for the evaluation at a = 0.

    Returns: max(off-diagonal norm, value error).
    """
    a = 0.0
    qdet = quantum_determinant_explicit(u, a)

    # Check scalar (proportional to I)
    off_diag = qdet - np.diag(np.diag(qdet))
    off_diag_norm = float(np.max(np.abs(off_diag)))

    # Check value
    expected = quantum_determinant_scalar(u, a)
    value_err = float(np.max(np.abs(np.diag(qdet) - expected)))

    return max(off_diag_norm, value_err)


def quantum_determinant_explicit(u: complex, a: complex = 0.0) -> np.ndarray:
    r"""Explicit computation of qdet T(u) as a sum over S_3.

    qdet T(u) = sum_{sigma in S_3} (-1)^{l(sigma)}
        T_{1,sigma(1)}(u) T_{2,sigma(2)}(u-1) T_{3,sigma(3)}(u-2)

    In the evaluation representation at a, T_{ij}(u) acts on physical C^3 by:
        T_{ij}(u) = (u - a) delta_{ij} + E_{ji}

    where E_{ji} is the elementary matrix.

    Returns: 3x3 matrix (should be scalar * I_3).
    """
    def T_entry(i, j, u_val):
        """T_{ij}(u) as a 3x3 matrix acting on physical space."""
        M = np.zeros((N, N), dtype=complex)
        if i == j:
            M += (u_val - a) * np.eye(N, dtype=complex)
        # E_{ji} contribution
        M[j, i] += 1.0
        return M

    qdet = np.zeros((N, N), dtype=complex)
    for sigma in permutations(range(N)):
        sign = 1
        # Count inversions
        for p in range(N):
            for q in range(p + 1, N):
                if sigma[p] > sigma[q]:
                    sign *= -1

        # Product: T_{1,sigma(1)}(u) T_{2,sigma(2)}(u-1) T_{3,sigma(3)}(u-2)
        prod = T_entry(0, sigma[0], u) @ T_entry(1, sigma[1], u - 1) @ T_entry(2, sigma[2], u - 2)
        qdet += sign * prod

    return qdet


def verify_qdet_is_scalar(u: complex, a: complex = 0.0) -> float:
    r"""Verify that qdet T(u) is a scalar matrix (proportional to I_3).

    Returns: max off-diagonal element (should be ~0).
    """
    qdet = quantum_determinant_explicit(u, a)
    # Check if off-diagonal elements are zero
    off_diag = qdet - np.diag(np.diag(qdet))
    return float(np.max(np.abs(off_diag)))


def verify_qdet_value(u: complex, a: complex = 0.0) -> float:
    r"""Verify that qdet T(u) = (u-a)(u-a-1)(u-a-2) I_3.

    Returns: norm of difference.
    """
    qdet = quantum_determinant_explicit(u, a)
    expected = quantum_determinant_scalar(u, a) * np.eye(N, dtype=complex)
    return float(np.linalg.norm(qdet - expected))


# ============================================================
# 5. Drinfeld-RTT generator map
# ============================================================

def gauss_decomposition_level0() -> Dict[str, np.ndarray]:
    r"""Gauss decomposition of T^{(0)} = I = F^{(0)} H^{(0)} E^{(0)}.

    At level 0: F^{(0)} = I (lower triangular), H^{(0)} = I (diagonal),
    E^{(0)} = I (upper triangular).  Trivially T^{(0)} = I = I * I * I.

    Returns: dict with F, H, E matrices at level 0.
    """
    I3 = np.eye(N, dtype=complex)
    return {"F": I3.copy(), "H": I3.copy(), "E": I3.copy()}


def drinfeld_generators_level0() -> Dict[str, np.ndarray]:
    r"""Drinfeld generators at level 0 in the fundamental representation.

    h_i^{(0)} = E_{ii} - E_{i+1,i+1}  (Cartan, i = 1, 2)
    e_i^{(0)} = E_{i,i+1}              (positive root, i = 1, 2)
    f_i^{(0)} = E_{i+1,i}              (negative root, i = 1, 2)

    These are the standard sl_3 Chevalley generators in the fundamental rep.

    Returns: dict with keys 'h1', 'h2', 'e1', 'e2', 'f1', 'f2'.
    """
    gens = {}
    # Cartan
    gens["h1"] = np.array([[1, 0, 0], [0, -1, 0], [0, 0, 0]], dtype=complex)
    gens["h2"] = np.array([[0, 0, 0], [0, 1, 0], [0, 0, -1]], dtype=complex)
    # Positive roots
    gens["e1"] = np.array([[0, 1, 0], [0, 0, 0], [0, 0, 0]], dtype=complex)
    gens["e2"] = np.array([[0, 0, 0], [0, 0, 1], [0, 0, 0]], dtype=complex)
    # Negative roots
    gens["f1"] = np.array([[0, 0, 0], [1, 0, 0], [0, 0, 0]], dtype=complex)
    gens["f2"] = np.array([[0, 0, 0], [0, 0, 0], [0, 1, 0]], dtype=complex)
    return gens


def drinfeld_generators_level1(a: complex = 0.0) -> Dict[str, np.ndarray]:
    r"""Drinfeld generators at level 1 in the evaluation representation ev_a.

    In the evaluation representation at evaluation point a, the level-1
    Drinfeld generators are:

        h_i^{(1)} = a * h_i^{(0)}
        e_i^{(1)} = a * e_i^{(0)}
        f_i^{(1)} = a * f_i^{(0)}

    More precisely, the evaluation homomorphism ev_a: Y(sl_3) -> U(sl_3)
    sends J^{(r)}_X -> a^r * X for all X in sl_3 and r >= 0.  At level 1:
    J^{(1)}_X -> a * X.

    Returns: dict with keys 'h1', 'h2', 'e1', 'e2', 'f1', 'f2' at level 1.
    """
    level0 = drinfeld_generators_level0()
    return {key: a * mat for key, mat in level0.items()}


def drinfeld_generators_level2(a: complex = 0.0) -> Dict[str, np.ndarray]:
    r"""Drinfeld generators at level 2 in the evaluation representation ev_a.

    In the evaluation representation at a:
        J^{(2)}_X -> a^2 * X

    Returns: dict with keys 'h1', 'h2', 'e1', 'e2', 'f1', 'f2' at level 2.
    """
    level0 = drinfeld_generators_level0()
    return {key: a ** 2 * mat for key, mat in level0.items()}


def rtt_to_drinfeld_map_level1(a: complex = 1.0) -> Dict[str, object]:
    r"""Map from RTT generators t_{ij}^{(1)} to Drinfeld generators.

    The Gauss decomposition of T(u):
        T(u) = F(u) H(u) E(u)
    where F is lower unitriangular, H is diagonal, E is upper unitriangular.

    From this decomposition:
        h_i(u) = H_{ii}(u) / H_{i+1,i+1}(u)    (ratio of diagonal entries)
        e_i(u) = E_{i,i+1}(u)                    (superdiagonal of E)
        f_i(u) = F_{i+1,i}(u)                    (subdiagonal of F)

    At level 1 in the evaluation representation ev_a:
        T^{(1)}_{ij} = a * delta_{ij} (for the trivial evaluation)

    For a nontrivial representation, the RTT-to-Drinfeld map at level 1 is:
        e_1^{(1)} = t_{12}^{(1)}
        e_2^{(1)} = t_{23}^{(1)}
        f_1^{(1)} = t_{21}^{(1)}
        f_2^{(1)} = t_{32}^{(1)}
        h_1^{(1)} = t_{11}^{(1)} - t_{22}^{(1)}
        h_2^{(1)} = t_{22}^{(1)} - t_{33}^{(1)}

    (These are the standard formulas from Molev, Theorem 1.11.2.)

    Returns: dict describing the map.
    """
    return {
        "e1^(1)": "t_{12}^{(1)}",
        "e2^(1)": "t_{23}^{(1)}",
        "f1^(1)": "t_{21}^{(1)}",
        "f2^(1)": "t_{32}^{(1)}",
        "h1^(1)": "t_{11}^{(1)} - t_{22}^{(1)}",
        "h2^(1)": "t_{22}^{(1)} - t_{33}^{(1)}",
        "source": "Molev, Thm 1.11.2",
    }


def rtt_to_drinfeld_map_level2() -> Dict[str, str]:
    r"""Map from RTT generators t_{ij}^{(r)} to Drinfeld generators at level 2.

    At level 2, the map involves products of level-1 generators:
        e_1^{(2)} = t_{12}^{(2)} - t_{12}^{(1)} t_{22}^{(1)} + t_{13}^{(1)} t_{32}^{(1)} - ...
        h_1^{(2)} = t_{11}^{(2)} - t_{22}^{(2)} + (t_{12}^{(1)} t_{21}^{(1)} - t_{21}^{(1)} t_{12}^{(1)})
        ...

    The explicit formulas are obtained by expanding the Gauss decomposition
    T(u) = F(u) H(u) E(u) to second order in u^{-1}.

    From Molev, Section 1.11:
        For the upper-triangular part:
            e_i^{(r)} = t_{i,i+1}^{(r)} - sum_{s=1}^{r-1} t_{i,i}^{(s)} e_i^{(r-s)}  (recursive)
        For the diagonal:
            h_i^{(r)} involves t_{ii}^{(r)} corrected by lower-order terms.

    Returns: dict describing the level-2 map.
    """
    return {
        "e1^(2)": "t_{12}^{(2)} - t_{11}^{(1)} * t_{12}^{(1)}",
        "e2^(2)": "t_{23}^{(2)} - t_{22}^{(1)} * t_{23}^{(1)}",
        "f1^(2)": "t_{21}^{(2)} - t_{21}^{(1)} * t_{11}^{(1)}",
        "f2^(2)": "t_{32}^{(2)} - t_{32}^{(1)} * t_{22}^{(1)}",
        "h1^(2)": "t_{11}^{(2)} - t_{22}^{(2)} - t_{12}^{(1)} * t_{21}^{(1)} + t_{22}^{(1)} * t_{21}^{(1)} (corrected)",
        "h2^(2)": "t_{22}^{(2)} - t_{33}^{(2)} - t_{23}^{(1)} * t_{32}^{(1)} + t_{33}^{(1)} * t_{32}^{(1)} (corrected)",
        "source": "Molev, Section 1.11, recursive Gauss decomposition",
    }


def verify_drinfeld_level0_bracket() -> float:
    r"""Verify that level-0 Drinfeld generators satisfy sl_3 commutation relations.

    [h_i, e_j] = A_{ij} e_j
    [h_i, f_j] = -A_{ij} f_j
    [e_i, f_j] = delta_{ij} h_i

    Returns: max norm of violations.
    """
    gens = drinfeld_generators_level0()
    A = np.array([[2, -1], [-1, 2]])  # Cartan matrix
    max_err = 0.0

    # [h_i, e_j] = A_{ij} e_j
    for i, hi in enumerate(["h1", "h2"]):
        for j, ej in enumerate(["e1", "e2"]):
            comm = gens[hi] @ gens[ej] - gens[ej] @ gens[hi]
            expected = A[i, j] * gens[ej]
            max_err = max(max_err, float(np.linalg.norm(comm - expected)))

    # [h_i, f_j] = -A_{ij} f_j
    for i, hi in enumerate(["h1", "h2"]):
        for j, fj in enumerate(["f1", "f2"]):
            comm = gens[hi] @ gens[fj] - gens[fj] @ gens[hi]
            expected = -A[i, j] * gens[fj]
            max_err = max(max_err, float(np.linalg.norm(comm - expected)))

    # [e_i, f_j] = delta_{ij} h_i
    for i in range(2):
        for j in range(2):
            ei_key = f"e{i+1}"
            fj_key = f"f{j+1}"
            hi_key = f"h{i+1}"
            comm = gens[ei_key] @ gens[fj_key] - gens[fj_key] @ gens[ei_key]
            if i == j:
                expected = gens[hi_key]
            else:
                expected = np.zeros((N, N), dtype=complex)
            max_err = max(max_err, float(np.linalg.norm(comm - expected)))

    return max_err


def verify_drinfeld_serre_relations() -> float:
    r"""Verify Serre relations for level-0 Drinfeld generators.

    For sl_3 with Cartan matrix A = [[2,-1],[-1,2]]:
        (ad e_i)^{1 - A_{ij}} (e_j) = 0 for i != j
        (ad f_i)^{1 - A_{ij}} (f_j) = 0 for i != j

    Since A_{12} = A_{21} = -1, we need 1 - (-1) = 2:
        [e_1, [e_1, e_2]] = 0
        [e_2, [e_2, e_1]] = 0
        [f_1, [f_1, f_2]] = 0
        [f_2, [f_2, f_1]] = 0

    Returns: max norm of violations.
    """
    gens = drinfeld_generators_level0()
    max_err = 0.0

    def ad(X, Y):
        return X @ Y - Y @ X

    # [e_1, [e_1, e_2]] = 0
    max_err = max(max_err, float(np.linalg.norm(ad(gens["e1"], ad(gens["e1"], gens["e2"])))))
    # [e_2, [e_2, e_1]] = 0
    max_err = max(max_err, float(np.linalg.norm(ad(gens["e2"], ad(gens["e2"], gens["e1"])))))
    # [f_1, [f_1, f_2]] = 0
    max_err = max(max_err, float(np.linalg.norm(ad(gens["f1"], ad(gens["f1"], gens["f2"])))))
    # [f_2, [f_2, f_1]] = 0
    max_err = max(max_err, float(np.linalg.norm(ad(gens["f2"], ad(gens["f2"], gens["f1"])))))

    return max_err


# ============================================================
# 6. Adjoint R-matrix
# ============================================================

def adjoint_rep_matrices() -> List[np.ndarray]:
    r"""Adjoint representation matrices for sl_3 (8x8).

    (ad X)_{ab} = f^{a}_{Xb} = structure constant.
    (ad T_c)_{ab} = f^{a}_{cb}

    where [T_c, T_b] = f^{a}_{cb} T_a.

    Returns: list of 8 matrices of shape (8, 8).
    """
    f = sl3_structure_constants()
    mats = []
    for c in range(DIM_G):
        M = np.zeros((DIM_G, DIM_G), dtype=complex)
        for b in range(DIM_G):
            if (c, b) in f:
                for a, coeff in f[(c, b)].items():
                    M[a, b] = float(coeff)
        mats.append(M)
    return mats


def adjoint_killing_form() -> np.ndarray:
    r"""Killing form in the adjoint representation: K_{ab} = tr(ad_a ad_b).

    For sl_3 (simple Lie algebra), the Killing form is proportional
    to the trace form in the adjoint: K_{ab} = 2 h^vee * g_{ab}
    where g_{ab} = tr_{fund}(T_a T_b) and h^vee = 3.

    Returns: 8x8 matrix.
    """
    mats = adjoint_rep_matrices()
    K = np.zeros((DIM_G, DIM_G))
    for a in range(DIM_G):
        for b in range(DIM_G):
            K[a, b] = np.trace(mats[a] @ mats[b]).real
    return K


def adjoint_casimir_tensor() -> np.ndarray:
    r"""Casimir tensor Omega^{adj} in the adjoint representation (64x64).

    Omega^{adj} = sum_a T^a_{adj} \otimes T_a^{adj}

    where T^a_{adj} is the adjoint matrix and T_a^{adj} is the dual basis
    (w.r.t. the trace form in the fundamental, then represented in adjoint).

    Returns: 64x64 matrix.
    """
    adj_mats = adjoint_rep_matrices()
    fund_mats = fund_rep_matrices()
    dual_fund = dual_basis_matrices()

    # Dual basis in adjoint: T_a^{adj} = sum_b (G^{-1})_{ab} T^b_{adj}
    Ginv = inverse_killing_form()
    dual_adj = []
    for a in range(DIM_G):
        M = sum(Ginv[a, b] * adj_mats[b] for b in range(DIM_G))
        dual_adj.append(M)

    d = DIM_G  # 8
    Omega = np.zeros((d * d, d * d), dtype=complex)
    for a in range(DIM_G):
        Omega += np.kron(adj_mats[a], dual_adj[a])

    return Omega.real


def adjoint_R_matrix(u: complex) -> np.ndarray:
    r"""R-matrix in the adjoint representation: R^{adj}(u).

    For the rational Yangian, the adjoint R-matrix is NOT simply u I + P.
    The formula is:

        R^{adj}(u) = 1 - Omega^{adj}/u + higher corrections

    For sl_N in general, the R-matrix on V_lambda x V_mu decomposes
    according to irreducible components of V_lambda x V_mu.

    For sl_3: adj x adj = 1 + 8 + 8 + 10 + 10* + 27
    (1 + 8_s + 8_a + 10 + 10* + 27 is the full decomposition).

    Wait, more precisely for sl_3:
    8 x 8 = 1 + 8 + 8 + 10 + 10* + 27
    (symmetric: 1 + 8 + 27 = 36, antisymmetric: 8 + 10 + 10* = 28,
     but 36 + 28 = 64 = 8^2, correct).

    Actually: 8 otimes 8 has Clebsch-Gordan decomposition:
    adj x adj = 1 + 8 + 8 + 10 + bar{10} + 27

    The R-matrix on each irreducible component acts as a scalar:
    R^{adj}(u)|_{V_lambda} = prod_{(i,j) in lambda-specific} (u + c_{ij}) / (u + c'_{ij})

    For the rational Yang R-matrix evaluated on adj x adj:
    R^{adj}(u) is obtained from the universal R-matrix R = 1 + r/u + O(1/u^2)
    evaluated on adj x adj.  At leading order it equals u * I_{64} + Omega^{adj}.

    We compute it as u * I_{64} + P^{adj} where P^{adj} is the permutation
    on the adjoint tensor product.

    However, for non-fundamental representations, the Yang R-matrix
    R(u) = u I + P is NO LONGER the correct R-matrix.  The correct
    R-matrix for adj x adj involves Casimir eigenvalues on each irreducible
    component.

    For the RATIONAL Yangian at the semiclassical level (1/kappa expansion):
    R^{adj}(u) = 1 + Omega^{adj}/(kappa * u) + O(1/kappa^2)
    and Omega^{adj} has eigenvalues corresponding to C_2 of each irrep
    in adj x adj.

    We compute eigenvalues of Omega^{adj} directly.

    Returns: 64x64 matrix R^{adj}(u) at the leading order u I + P^{adj}.
    """
    d = DIM_G  # 8
    Omega = adjoint_casimir_tensor()
    I64 = np.eye(d * d, dtype=complex)

    # Permutation on adj x adj
    P_adj = np.zeros((d * d, d * d), dtype=complex)
    for i in range(d):
        for j in range(d):
            P_adj[i * d + j, j * d + i] = 1.0

    # The R-matrix at leading semiclassical order
    # For the Yang R-matrix in the fundamental, R(u) = u I + P.
    # For the adjoint, the analogous object is u I + P^{adj},
    # which is the image of the universal R(u) = u + P under adj x adj.
    return u * I64 + P_adj


def adjoint_casimir_eigenvalues() -> Dict[str, float]:
    r"""Eigenvalues of the Casimir tensor Omega^{adj} on irreducible components.

    adj x adj for sl_3:
    8 x 8 = 1 + 8 + 8 + 10 + bar{10} + 27

    The Casimir C_2 of each irrep (in trace normalization):
        1 (trivial): C_2 = 0
        8 (adjoint): C_2 = 3  (= N for sl_N with trace normalization)
        10 (symmetric, [3,0]): C_2 = 6
        bar{10} (antisym, [0,3]): C_2 = 6
        27 ([2,2]): C_2 = 8

    Omega^{adj} eigenvalues on each component equal
    C_2(irrep) - 2*C_2(adj) = C_2(irrep) - 6 (by the standard identity).

    Wait, the correct formula for the Casimir tensor eigenvalue is:
    Omega|_{V_lambda} = (C_2(lambda) - C_2(mu) - C_2(nu)) / 2
    where V_lambda appears in V_mu x V_nu.

    For adj (8) x adj (8), C_2(adj) = 3:
    Omega|_{V_lambda} = (C_2(lambda) - 3 - 3) / 2 = (C_2(lambda) - 6) / 2

    Eigenvalues:
        1:      (0 - 6)/2 = -3
        8:      (3 - 6)/2 = -3/2
        10:     (6 - 6)/2 = 0
        bar{10}: (6 - 6)/2 = 0
        27:     (8 - 6)/2 = 1

    Let me verify: for the fundamental, C_2(fund) = 4/3.
    fund x fund = 6 (sym, [2,0]) + 3* (antisym, [0,1]).
    C_2([2,0]) = 10/3, C_2([0,1]) = 4/3.
    Omega|_{[2,0]} = (10/3 - 4/3 - 4/3)/2 = (2/3)/2 = 1/3.
    But we computed Omega|_{Sym^2} = 2/3.  Hmm.

    Actually the formula depends on normalization.  With Omega = P - I/N:
    Omega|_{Sym^2} = 1 - 1/3 = 2/3.
    Omega|_{Lambda^2} = -1 - 1/3 = -4/3.
    C_2([2,0]) = 10/3, C_2([0,1]) = 4/3, C_2(fund) = 4/3.
    (C_2([2,0]) - 2*C_2(fund))/1 = (10/3 - 8/3) = 2/3. Yes!

    So Omega|_{V_lambda in V_mu x V_nu} = (C_2(lambda) - C_2(mu) - C_2(nu)) / 1
    (NOT divided by 2 in this normalization).

    For adj x adj with C_2(adj) = 3:
        1:      0 - 3 - 3 = -6
        8:      3 - 3 - 3 = -3
        10:     C_2([3,0]) - 6
        bar{10}: C_2([0,3]) - 6
        27:     C_2([2,2]) - 6

    I need to compute C_2 in the trace normalization.
    For sl_3, C_2(lambda_1, lambda_2) = (lambda_1^2 + lambda_2^2 + lambda_1*lambda_2
        + 3*lambda_1 + 3*lambda_2) / 3  (in our normalization with tr_{fund}).

    Checked: C_2(1,0) = (1 + 0 + 0 + 3 + 0)/3 = 4/3. Correct.
    C_2(1,1) = (1 + 1 + 1 + 3 + 3)/3 = 9/3 = 3. Correct for adjoint.
    C_2(2,0) = (4 + 0 + 0 + 6 + 0)/3 = 10/3. Correct.
    C_2(0,1) = (0 + 1 + 0 + 0 + 3)/3 = 4/3. Correct.
    C_2(3,0) = (9 + 0 + 0 + 9 + 0)/3 = 18/3 = 6.
    C_2(0,3) = (0 + 9 + 0 + 0 + 9)/3 = 18/3 = 6.
    C_2(2,2) = (4 + 4 + 4 + 6 + 6)/3 = 24/3 = 8.

    So the eigenvalues of Omega^{adj} on irreducible components:
        1 (0,0):      0 - 6 = -6
        8 (1,1):      3 - 6 = -3
        10 (3,0):     6 - 6 = 0
        bar{10} (0,3): 6 - 6 = 0
        27 (2,2):     8 - 6 = 2

    Returns: dict with eigenvalues and multiplicities.
    """
    # C_2 in trace normalization (sum_a T^a T_a eigenvalue).
    # Omega_{12} = (C_2^{12} - C_2^1 - C_2^2) / 2, so
    # Omega|_{V_lam} = (C_2(lam) - 2*C_2(adj)) / 2.
    # C_2(adj) = 6, so Omega|_{V_lam} = (C_2(lam) - 12) / 2.
    return {
        "1": {"dim": 1, "hw": "(0,0)", "C2": 0, "Omega_eigenvalue": (0 - 12) / 2},
        "8_s": {"dim": 8, "hw": "(1,1)", "C2": 6, "Omega_eigenvalue": (6 - 12) / 2, "sector": "symmetric"},
        "8_a": {"dim": 8, "hw": "(1,1)", "C2": 6, "Omega_eigenvalue": (6 - 12) / 2, "sector": "antisymmetric"},
        "10": {"dim": 10, "hw": "(3,0)", "C2": 12, "Omega_eigenvalue": (12 - 12) / 2},
        "10*": {"dim": 10, "hw": "(0,3)", "C2": 12, "Omega_eigenvalue": (12 - 12) / 2},
        "27": {"dim": 27, "hw": "(2,2)", "C2": 16, "Omega_eigenvalue": (16 - 12) / 2},
    }


def verify_adjoint_permutation_eigenvalues() -> float:
    r"""Verify eigenvalues of the permutation P^{adj} on C^8 \otimes C^8.

    P^{adj} has eigenvalues +1 on Sym^2(adj) and -1 on Lambda^2(adj).
    For sl_3:  adj x adj = 1 + 8 + 8 + 10 + bar{10} + 27.
    Sym^2(adj) = 1 + 8 + 27 (dimension 36)
    Lambda^2(adj) = 8 + 10 + bar{10} (dimension 28)

    P^{adj} eigenvalues: +1 with multiplicity 36, -1 with multiplicity 28.

    Returns: max error in eigenvalue distribution.
    """
    P_adj = adjoint_permutation_matrix()
    evals = np.sort(np.linalg.eigvalsh(P_adj))

    expected = ([-1.0] * 28 + [1.0] * 36)
    expected.sort()

    return float(np.max(np.abs(evals - np.array(expected))))


def adjoint_permutation_matrix() -> np.ndarray:
    """Permutation matrix on C^8 otimes C^8."""
    d = DIM_G
    P = np.zeros((d * d, d * d))
    for i in range(d):
        for j in range(d):
            P[i * d + j, j * d + i] = 1.0
    return P


def adjoint_R_eigenvalues(u: complex) -> Dict[str, complex]:
    r"""Eigenvalues of R^{adj}(u) = u I + P^{adj} on each irreducible component.

    On irreps where P has eigenvalue +1 (symmetric part):
        R eigenvalue = u + 1
    On irreps where P has eigenvalue -1 (antisymmetric part):
        R eigenvalue = u - 1

    For adj x adj = Sym^2(adj) + Lambda^2(adj):
        Sym^2: 1 + 8 + 27 = 36 dimensions, R eigenvalue u + 1
        Lambda^2: 8 + 10 + 10 = 28 dimensions, R eigenvalue u - 1

    Wait, this is the SAME as the fundamental case: R(u) = u I + P has
    eigenvalues u+1 on Sym and u-1 on Lambda, regardless of the representation.
    This is because P^2 = I always.

    Returns: eigenvalues on symmetric and antisymmetric parts.
    """
    return {
        "Sym^2(adj)": {
            "dim": 36,
            "decomposition": "1 + 8 + 27",
            "R_eigenvalue": u + 1,
        },
        "Lambda^2(adj)": {
            "dim": 28,
            "decomposition": "8 + 10 + 10*",
            "R_eigenvalue": u - 1,
        },
    }


# ============================================================
# 7. Fusion rules and MC3 verification
# ============================================================

def fusion_rules_fundamental() -> Dict[str, object]:
    r"""Fusion rules for the fundamental representation of Y(sl_3).

    3 \otimes 3 = 6 \oplus \bar{3}

    where:
        6 = Sym^2(C^3) with highest weight (2,0)
        \bar{3} = \Lambda^2(C^3) with highest weight (0,1)

    The R-matrix has eigenvalues:
        u + 1 on Sym^2 (dim 6)
        u - 1 on Lambda^2 (dim 3)

    MC3 verification: these are the same fusion rules as U_q(sl_3)
    at generic q.  The R-matrix eigenvalues at u = 0 give
    q = +1 and -q^{-2} = -1, matching the q -> 1 limit.

    At generic q:
        R^{U_q} has eigenvalues q on Sym^2 and -q^{-2} on Lambda^2.
    The Yangian R-matrix R(u) = u I + P interpolates between these as:
        lim_{u -> infinity} R(u)/u = I  (trivial monodromy)
        R(0) = P  (maximal entanglement)
    """
    return {
        "3 x 3": {
            "Sym^2": {"dim": 6, "hw": "(2,0)", "R_eigenvalue": "u + 1"},
            "Lambda^2": {"dim": 3, "hw": "(0,1)", "R_eigenvalue": "u - 1"},
        },
        "MC3_status": "PROVED for all simple types (cor:mc3-all-types)",
        "equivalence": "Rep^fd(Y(sl_3)) ~ Rep(U_q(sl_3)) at generic q",
    }


def fusion_rules_fund_x_antifund() -> Dict[str, object]:
    r"""Fusion rules: 3 \otimes \bar{3} = 1 \oplus 8.

    The fundamental times anti-fundamental decomposes as:
        3 x bar{3} = 1 + 8  (trivial + adjoint)

    The R-matrix eigenvalues on these components:
        1 (trivial): Omega eigenvalue = C_2(1) - C_2(fund) - C_2(antifund)
                    = 0 - 4/3 - 4/3 = -8/3
        8 (adjoint): Omega eigenvalue = C_2(adj) - C_2(fund) - C_2(antifund)
                    = 3 - 4/3 - 4/3 = 1/3
    """
    # Omega eigenvalue = (C_2(irrep) - C_2(fund) - C_2(antifund)) / 2
    # C_2(fund) = C_2(antifund) = 8/3.  Total = 16/3.
    # 1:  (0 - 16/3) / 2 = -8/3
    # 8:  (6 - 16/3) / 2 = (2/3) / 2 = 1/3
    return {
        "3 x bar{3}": {
            "1": {"dim": 1, "hw": "(0,0)", "Omega_eigenvalue": -8.0/3},
            "8": {"dim": 8, "hw": "(1,1)", "Omega_eigenvalue": 1.0/3},
        },
    }


def verify_fusion_dimensions() -> bool:
    r"""Verify fusion rule dimensions are consistent.

    3 x 3 = 6 + 3 (dim check: 9 = 6 + 3)
    3 x bar{3} = 1 + 8 (dim check: 9 = 1 + 8)
    8 x 8 = 1 + 8 + 8 + 10 + 10 + 27 (dim check: 64 = 1 + 8 + 8 + 10 + 10 + 27)
    """
    checks = [
        6 + 3 == 9,
        1 + 8 == 9,
        1 + 8 + 8 + 10 + 10 + 27 == 64,
    ]
    return all(checks)


def verify_R_eigenvalue_on_fusion(u: complex) -> float:
    r"""Verify R-matrix eigenvalues match fusion rule predictions.

    On C^3 x C^3:
        R(u) = (u+1) P_sym + (u-1) P_asym
    where P_sym, P_asym are projectors onto Sym^2, Lambda^2.

    Returns: norm of R(u) - predicted decomposition.
    """
    P = permutation_matrix_3().astype(complex)
    I9 = np.eye(N * N, dtype=complex)
    P_sym = (I9 + P) / 2
    P_asym = (I9 - P) / 2

    R = R_matrix_fund_exact_yang(u)
    predicted = (u + 1) * P_sym + (u - 1) * P_asym
    return float(np.linalg.norm(R - predicted))


# ============================================================
# 8. KZ monodromy and semiclassical limit
# ============================================================

def kz_monodromy_matrix(kappa_val: complex, n_terms: int = 50) -> np.ndarray:
    r"""Compute KZ monodromy matrix exp(2 pi i Omega / kappa) on C^3 x C^3.

    The KZ equation d Phi / dz = (Omega / (kappa * z)) Phi has monodromy
    around z = 0 given by exp(2 pi i Omega / kappa).

    Since Omega = P - I/N has eigenvalues 2/3 (on Sym) and -4/3 (on Lambda),
    the monodromy matrix is:
        exp(2 pi i * 2/(3*kappa)) on Sym^2
        exp(2 pi i * (-4)/(3*kappa)) on Lambda^2

    We compute this via spectral decomposition (exact, no truncation needed).

    Args:
        kappa_val: level-dependent parameter.
        n_terms: unused (computation is exact via spectral decomposition).

    Returns: 9x9 monodromy matrix.
    """
    P = permutation_matrix_3().astype(complex)
    I9 = np.eye(N * N, dtype=complex)
    P_sym = (I9 + P) / 2
    P_asym = (I9 - P) / 2

    omega_sym = (N - 1.0) / N       # 2/3
    omega_asym = -(N + 1.0) / N     # -4/3

    lambda_sym = np.exp(2j * np.pi * omega_sym / kappa_val)
    lambda_asym = np.exp(2j * np.pi * omega_asym / kappa_val)

    return lambda_sym * P_sym + lambda_asym * P_asym


def verify_kz_monodromy_yang_limit(kappa_val: float = 100.0) -> float:
    r"""Verify that KZ monodromy approaches I as kappa -> infinity.

    At large kappa, the KZ connection becomes weak, and the monodromy
    approaches the identity matrix.

    Returns: norm of M - I.
    """
    M = kz_monodromy_matrix(kappa_val)
    I9 = np.eye(N * N, dtype=complex)
    return float(np.linalg.norm(M - I9))


def kz_monodromy_to_q(kappa_val: complex) -> complex:
    r"""Extract the quantum group parameter q from the KZ monodromy.

    The KZ monodromy at level k corresponds to the quantum group parameter
    q = exp(pi i / (k + h^vee)) = exp(pi i / kappa_normalized).

    For sl_3 with kappa = 4(k+3)/3:
        k + h^vee = k + 3
        q = exp(pi i / (k + 3))

    The monodromy eigenvalues are:
        Sym^2:    exp(2 pi i * (2/3) / kappa) = q^{C_2(Sym) - C_2(fund) - C_2(fund)}
        Lambda^2: exp(2 pi i * (-4/3) / kappa) = q^{C_2(Lambda) - C_2(fund) - C_2(fund)}

    Returns: the quantum group parameter q.
    """
    # kappa = 4(k+3)/3, so k+3 = 3*kappa/4
    k_plus_h = 3 * kappa_val / 4
    q = np.exp(1j * np.pi / k_plus_h)
    return q


def verify_monodromy_eigenvalue_ratio(k: int) -> float:
    r"""Verify ratio of KZ monodromy eigenvalues matches q-group prediction.

    The ratio lambda_sym / lambda_asym should equal q^{C_2(Sym) - C_2(Lambda)}.

    C_2(Sym^2(fund)) - C_2(Lambda^2(fund)) = (in our normalization)
    For Omega eigenvalues: 2/3 - (-4/3) = 2.
    So the ratio of exponents is 2/kappa.
    Monodromy ratio = exp(2 pi i * 2 / kappa).

    In terms of q: this should be q^{some power}.
    Since q = exp(pi i / (k+3)) and kappa = 4(k+3)/3:
        2/kappa = 2 * 3 / (4(k+3)) = 3/(2(k+3))
        2 pi i * 2/kappa = 2 pi i * 3/(2(k+3)) = 3 * pi i / (k+3)
        = 3 * log(q) / (pi i) * pi i = 3 * log(q)
    So ratio = q^3.

    Returns: |lambda_sym/lambda_asym - q^3|.
    """
    kappa_val = float(kappa_sl3(k))
    omega_sym = 2.0 / 3.0
    omega_asym = -4.0 / 3.0

    lambda_sym = np.exp(2j * np.pi * omega_sym / kappa_val)
    lambda_asym = np.exp(2j * np.pi * omega_asym / kappa_val)

    ratio = lambda_sym / lambda_asym
    q = kz_monodromy_to_q(kappa_val)
    q3 = q ** 3

    return float(abs(ratio - q3))


# ============================================================
# 9. Evaluation modules and tensor products
# ============================================================

def evaluation_module_drinfeld_polynomial(a: complex) -> List[complex]:
    r"""Drinfeld polynomial for the evaluation module V(a) of Y(sl_3).

    The fundamental evaluation module V(a) has Drinfeld polynomial:
        P_1(u) = u - a
        P_2(u) = 1

    (P_i corresponds to the i-th fundamental weight omega_i.)

    The quantum determinant on V(a) is:
        qdet T(u)|_{V(a)} = P_1(u) P_1(u-1) P_1(u-2) ... (shifted product)
        = (u-a)(u-a-1)(u-a-2)

    Returns: roots of the Drinfeld polynomial P_1.
    """
    return [a]


def tensor_product_evaluation(a1: complex, a2: complex) -> Dict[str, object]:
    r"""Tensor product of two evaluation modules V(a1) x V(a2).

    V(a1) x V(a2) is generically irreducible when a1 - a2 is not
    an integer.  When a1 - a2 = 1, there is a short exact sequence:
        0 -> V_{(2,0)}(a2) -> V(a1) x V(a2) -> V_{(0,1)}(a2) -> 0

    where V_{(2,0)} is the symmetric-square evaluation module and
    V_{(0,1)} is the anti-fundamental evaluation module.

    The R-matrix R(a1 - a2) is degenerate (rank 6) when a1 - a2 = 1
    (the Lambda^2 eigenvalue u-1 vanishes at u = 1).

    Returns: dict describing the tensor product.
    """
    diff = a1 - a2
    if abs(diff - 1.0) < 1e-10:
        return {
            "type": "reducible (a1 - a2 = 1)",
            "components": [
                {"hw": "(2,0)", "dim": 6, "module": "V_{Sym^2}(a2)"},
                {"hw": "(0,1)", "dim": 3, "module": "V_{Lambda^2}(a2)"},
            ],
            "R_matrix_rank": 6,
        }
    elif abs(diff + 1.0) < 1e-10:
        return {
            "type": "reducible (a1 - a2 = -1)",
            "components": [
                {"hw": "(2,0)", "dim": 6, "module": "V_{Sym^2}(a1)"},
                {"hw": "(0,1)", "dim": 3, "module": "V_{Lambda^2}(a1)"},
            ],
            "R_matrix_rank": 6,
        }
    else:
        return {
            "type": "irreducible (generic a1 - a2)",
            "a1_minus_a2": diff,
            "R_matrix_rank": 9,
        }


def verify_tensor_product_reducibility(a1: complex, a2: complex) -> Dict[str, object]:
    r"""Verify tensor product reducibility by checking R-matrix rank.

    R(a1 - a2) has:
        rank 9 (full) when a1 - a2 != +-1
        rank 6 when a1 - a2 = +-1 (the Lambda^2 or Sym^2 eigenvalue vanishes)

    Returns: dict with rank and eigenvalues.
    """
    R = R_matrix_fund_exact_yang(a1 - a2)
    rank = np.linalg.matrix_rank(R, tol=1e-10)
    evals = np.sort(np.linalg.eigvals(R).real)

    return {
        "a1_minus_a2": a1 - a2,
        "R_rank": rank,
        "eigenvalues": evals.tolist(),
        "reducible": rank < 9,
    }


# ============================================================
# 10. C_2 formula for sl_3 representations
# ============================================================

def casimir_eigenvalue_sl3(lambda1: int, lambda2: int) -> Rational:
    r"""Quadratic Casimir eigenvalue C_2(\lambda) for sl_3 representation.

    For highest weight \lambda = (\lambda_1, \lambda_2) in the omega-basis
    (Dynkin labels), the Casimir eigenvalue with the trace normalization
    (X, Y) = tr_{fund}(X Y) is:

        C_2(\lambda) = (\lambda, \lambda + 2\rho)

    where \rho = (1,1) and the inner product uses A^{-1} = (1/3)[[2,1],[1,2]]
    (inverse Cartan matrix for sl_3).

    Explicitly:
        C_2(\lambda_1, \lambda_2) = (2\lambda_1^2 + 2\lambda_2^2 + 2\lambda_1\lambda_2
                                      + 6\lambda_1 + 6\lambda_2) / 3

    Verification:
        C_2(1,0) = (2+0+0+6+0)/3 = 8/3 (fundamental)
        C_2(0,1) = (0+2+0+0+6)/3 = 8/3 (anti-fundamental)
        C_2(1,1) = (2+2+2+6+6)/3 = 6 (adjoint)
        C_2(2,0) = (8+0+0+12+0)/3 = 20/3 (symmetric square)
        C_2(3,0) = (18+0+0+18+0)/3 = 12
        C_2(0,3) = (0+18+0+0+18)/3 = 12
        C_2(2,2) = (8+8+8+12+12)/3 = 16
        C_2(0,0) = 0 (trivial)

    Returns: Rational Casimir eigenvalue.
    """
    return Rational(
        2 * lambda1 ** 2 + 2 * lambda2 ** 2 + 2 * lambda1 * lambda2
        + 6 * lambda1 + 6 * lambda2,
        3,
    )


def dimension_sl3(lambda1: int, lambda2: int) -> int:
    r"""Dimension of the sl_3 representation with Dynkin labels (lambda1, lambda2).

    dim(\lambda_1, \lambda_2) = (lambda_1 + 1)(lambda_2 + 1)(lambda_1 + lambda_2 + 2) / 2

    Returns: integer dimension.
    """
    return (lambda1 + 1) * (lambda2 + 1) * (lambda1 + lambda2 + 2) // 2


# ============================================================
# 11. Bar complex connection summary
# ============================================================

def bar_to_rtt_connection() -> Dict[str, str]:
    r"""Summary of the bar complex to RTT connection.

    The bar construction B(V_k(\hat{sl}_3)) produces a factorization coalgebra.
    The RTT presentation of Y(sl_3) emerges from this via:

    1. The collision residue r(z) = Omega/z = Res^{coll}_{0,2}(Theta_A)
       is the classical r-matrix (AP19: one pole order below OPE).

    2. The Yang R-matrix R(u) = u I + P is the EXACT solution of YBE
       with r(z) = (R(z) - I)/z as z -> infinity.  Equivalently,
       R(u) = u + P where Omega = P - I/N (Casimir identity for sl_N).

    3. The RTT relation R_{12}(u-v) T_1(u) T_2(v) = T_2(v) T_1(u) R_{12}(u-v)
       is the arity-2 component of the MC equation.

    4. The YBE R_{12} R_{13} R_{23} = R_{23} R_{13} R_{12}
       is the arity-3 component of d^2 = 0 (thm:convolution-d-squared-zero).

    5. The quantum determinant qdet T(u) is the arity-0 projection
       (it commutes with everything = it is a Casimir).

    6. MC3 (proved for all simple types) establishes:
       Rep^fd(Y(sl_3)) ~ Rep(U_q(sl_3)) at generic q.
       This is the categorical Clebsch-Gordan equivalence.
    """
    return {
        "step_1": "Bar collision residue -> classical r-matrix r(z) = Omega/z (AP19)",
        "step_2": "r-matrix exponentiates -> Yang R-matrix R(u) = u I + P",
        "step_3": "RTT relation = arity-2 MC equation",
        "step_4": "YBE = arity-3 d^2 = 0",
        "step_5": "Quantum determinant = arity-0 (Casimir) projection",
        "step_6": "MC3: Rep^fd(Y(sl_3)) ~ Rep(U_q(sl_3)) (categorical equivalence)",
    }


# ============================================================
# 12. Level-k deformation
# ============================================================

def R_matrix_level_k(u: complex, k: int) -> np.ndarray:
    r"""R-matrix at level k: R_k(u) = u I + P (independent of k!).

    For the rational Yang R-matrix, the level k does NOT enter
    into the R-matrix formula.  The level appears in:
    1. The kappa parameter: kappa = 4(k+3)/3
    2. The KZ connection: A(z) = Omega/(kappa z)
    3. The quantum group parameter: q = exp(pi i / (k+3))

    But the Yang R-matrix R(u) = u I + P is UNIVERSAL (level-independent).
    This is because it is the RATIONAL solution of YBE, valid for all
    values of the coupling.  The trigonometric/elliptic deformations
    (which DO depend on q and hence k) arise from:
    - Trigonometric: affine KZ, q-deformed coproduct
    - Elliptic: KZB equation, elliptic quantum groups

    Returns: 9x9 R-matrix.
    """
    return R_matrix_fund_exact_yang(u)


def kz_R_matrix_from_monodromy(k: int) -> np.ndarray:
    r"""The trigonometric R-matrix from KZ monodromy at level k.

    R^{trig}_{q} = q P_sym - q^{-1} P_asym (Drinfeld-Jimbo)

    where q = exp(pi i / (k + 3)) for sl_3.

    In the Drinfeld-Jimbo normalization:
    R^{DJ}|_{Sym^2} = q  (eigenvalue)
    R^{DJ}|_{Lambda^2} = -q^{-1}  (eigenvalue)

    The rational Yang R-matrix is the q -> 1 limit:
        R(u) = (u + 1) P_sym + (u - 1) P_asym
    which at u = 0 gives R(0) = P_sym - P_asym = P.

    Returns: 9x9 trigonometric R-matrix at level k.
    """
    kappa_val = float(kappa_sl3(k))
    q = kz_monodromy_to_q(kappa_val)

    P = permutation_matrix_3().astype(complex)
    I9 = np.eye(N * N, dtype=complex)
    P_sym = (I9 + P) / 2
    P_asym = (I9 - P) / 2

    return q * P_sym - (1.0 / q) * P_asym


# ============================================================
# Verification summary
# ============================================================

def full_rtt_verification() -> Dict[str, bool]:
    """Run all RTT verification tests and return results."""
    results = {}

    # RTT = YBE
    results["RTT from YBE (10,7)"] = verify_rtt_from_ybe(10.0, 7.0) < 1e-10
    results["RTT from YBE (3.5, 1.2)"] = verify_rtt_from_ybe(3.5, 1.2) < 1e-10
    results["RTT from YBE complex"] = verify_rtt_from_ybe(2+1j, 5-0.5j) < 1e-10

    # Quantum determinant
    results["qdet is scalar (u=5)"] = verify_qdet_is_scalar(5.0) < 1e-10
    results["qdet value (u=5)"] = verify_qdet_value(5.0) < 1e-10
    results["qdet value (u=3, a=1)"] = verify_qdet_value(3.0, 1.0) < 1e-10
    results["qdet antisymmetrizer"] = verify_qdet_antisymmetrizer(5.0) < 1e-10
    results["qdet centrality"] = verify_qdet_centrality(5.0, 3.0) < 1e-10

    # Drinfeld generators
    results["Drinfeld level-0 bracket"] = verify_drinfeld_level0_bracket() < 1e-10
    results["Drinfeld Serre relations"] = verify_drinfeld_serre_relations() < 1e-10

    # Adjoint
    results["adj permutation eigenvalues"] = verify_adjoint_permutation_eigenvalues() < 1e-10

    # Fusion
    results["fusion dimensions"] = verify_fusion_dimensions()
    results["R eigenvalue decomposition (u=2)"] = verify_R_eigenvalue_on_fusion(2.0) < 1e-10

    # KZ
    results["KZ monodromy large kappa"] = verify_kz_monodromy_yang_limit(100.0) < 0.5
    results["KZ eigenvalue ratio k=1"] = verify_monodromy_eigenvalue_ratio(1) < 1e-10
    results["KZ eigenvalue ratio k=5"] = verify_monodromy_eigenvalue_ratio(5) < 1e-10

    # Tensor product
    tp = verify_tensor_product_reducibility(1.0, 0.0)
    results["tensor product reducible at a1-a2=1"] = bool(tp["reducible"])
    tp2 = verify_tensor_product_reducibility(3.0, 0.0)
    results["tensor product irreducible at a1-a2=3 (generic)"] = tp2["R_rank"] == 9

    # Casimir formula
    results["C_2(fund) = 8/3"] = casimir_eigenvalue_sl3(1, 0) == Rational(8, 3)
    results["C_2(adj) = 6"] = casimir_eigenvalue_sl3(1, 1) == Rational(6)
    results["dim(fund) = 3"] = dimension_sl3(1, 0) == 3
    results["dim(adj) = 8"] = dimension_sl3(1, 1) == 8
    results["dim(27) = 27"] = dimension_sl3(2, 2) == 27

    return results


# ============================================================
# Main
# ============================================================

if __name__ == "__main__":
    print("=" * 70)
    print("RTT PRESENTATION OF Y(sl_3) FROM BAR-COBAR CONSTRUCTION")
    print("=" * 70)

    results = full_rtt_verification()
    passed = sum(1 for v in results.values() if v)
    total = len(results)

    for name, ok in results.items():
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")

    print(f"\n  {passed}/{total} passed")
